### ISSUE TITLE
[Flaky] Order dependent failure rspec ./spec/system/admin/enterprises/index_spec.rb:83

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10055]
### What we should change and why (this is tech debt)

Order dependent failure:

`bundle exec rspec --format progress --default-path spec "spec/system/admin/tag_rules_spec.rb" "spec/system/admin/enterprises/index_spec.rb"
`

```

Failures:

  1) Enterprises Index as an admin user editing enterprises in bulk with data that violates rules does not update the enterprises and displays errors
     Failure/Error: expect(second_distributor.owner).to_not eq d_manager
     
       expected: value != #<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, ...terprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
            got: #<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, ...terprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -#<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, last_request_at: nil, login: "michaela@mcglynn.info", ship_address_id: nil, bill_address_id: nil, created_at: "2022-11-25 01:41:13.312166774 +0000", updated_at: "2022-11-25 01:41:13.312166774 +0000", authentication_token: "xxxx166934047389675xxxxxxxxxxxxx", spree_api_key: nil, api_key: nil, enterprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
       +#<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, last_request_at: nil, login: "michaela@mcglynn.info", ship_address_id: nil, bill_address_id: nil, created_at: "2022-11-25 01:41:13.312166000 +0000", updated_at: "2022-11-25 01:41:13.312166000 +0000", authentication_token: "xxxx166934047389675xxxxxxxxxxxxx", spree_api_key: nil, api_key: nil, enterprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3544677610/jobs/5952175489

**Comment by filipefurtad0** [comment]
I've worked a few hours on this but was unable to progress: I can't seem to find out what is leaking from one spec to the other. I've commented out different example groups but found both specs to always pass: it is only when both files are ran entirely that the failure occurs.

I'd vote to keep the issue open, as this is relevant info, but I'm un-assigning myself.

**Comment by jibees** [comment]
This one seems to occurs more and more: 
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4182732309/jobs/7269323804

**Comment by mkllnk** [comment]
```
$ bundle exec rspec --bisect --order defined "spec/system/admin/tag_rules_spec.rb" "spec/system/admin/enterprises/index_spec.rb"
...
Bisect complete! Reduced necessary non-failing examples from 8 to 5 in 5 minutes 22 seconds.

The minimal reproduction command is:
  rspec ./spec/system/admin/enterprises/index_spec.rb[1:1:1,1:1:2:1:1,1:1:2:2:1] ./spec/system/admin/tag_rules_spec.rb[1:1:1,1:2:1,1:3:1] --order defined
```

However, that's not true. Running that doesn't fail. :disappointed: 

Since the *execution* of the specs doesn't seem to matter, I'm wondering if it's the *loading* of the spec code. I've seen it before that a `require` statement loaded code which altered global state. The only loaded code is the system helper file and the inclusion of two test helper modules. They are loaded in different order but changing that around doesn't help.

So I'm going back to deleting spec code to find a smaller code set that still fails. Interestingly, the contents of the `it` blocks in the tag rule spec don't seem to matter. It's when the setup code, `let!` or `before` is deleted that the spec starts passing. 

I removed the `before` blocks which leaves the `let!` blocks the only significant code here. So I found that we get a fail when the tag rules spec creates *exactly** three enterprises. No less and no more or it passes.

```rb
# frozen_string_literal: true

require 'system_helper'

describe 'Tag Rules' do
  it "allows creation of rules of each type" do
    create(:distributor_enterprise)
  end

  it "saves changes to rules of each type" do
    create(:distributor_enterprise)
  end

  it "deletes both default and customer rules from the database" do
    create(:distributor_enterprise)
  end
end
```

I can reduce the index spec a bit as well but now I need to call it a day. TBD. It seems to be around creating enterprises... :thinking:

**Comment by mkllnk** [comment]
I found that the only "leaking" code of the tag rules spec were to create three enterprises. It didn't matter when they were created, just before the failing spec. So I copied that part over and merge other parts of the index spec to create a single failing example:

```rb
# frozen_string_literal: true

require 'system_helper'

describe 'Enterprises Index' do
  include WebHelper
  include AuthenticationHelper

  context "as an admin user" do
    context "editing enterprises in bulk" do
      context "with data that violates rules" do
        let!(:s){ create(:supplier_enterprise) }
        let!(:d){ create(:distributor_enterprise, sells: 'none') }
        let!(:d_manager) { create(:user, enterprise_limit: 1) }

        it "does not update the enterprises and displays errors" do
          d_manager.enterprise_roles.build(enterprise: d).save
          expect(d.owner).to_not eq d_manager
          create(:distributor_enterprise)
          create(:distributor_enterprise)
          create(:distributor_enterprise)
          create(:supplier_enterprise)
          create(:distributor_enterprise)
          create(:supplier_enterprise)
          create(:distributor_enterprise)

          second_distributor = create(:distributor_enterprise, sells: 'none')

          d_manager.enterprise_roles.build(enterprise: second_distributor).save
          expect(d.owner).to_not eq d_manager

          login_as_admin_and_visit admin_enterprises_path

          d_row_index = enterprise_row_index(d.name)
          within("tr.enterprise-#{d.id}") do
            select d_manager.email,
                   from: "sets_enterprise_set_collection_attributes_#{d_row_index}_owner_id"
          end

          second_distributor_row_index = enterprise_row_index(second_distributor.name)
          within("tr.enterprise-#{second_distributor.id}") do
            select d_manager.email,
                   from: "sets_enterprise_set_collection_attributes_#{second_distributor_row_index}_owner_id"
          end
          click_button "Update"
          expect(flash_message).to eq('Update failed')
          expect(page).to have_content "#{d_manager.email} is not permitted to own any more enterprises (limit is 1)."
          second_distributor.reload
          expect(second_distributor.owner).to_not eq d_manager
        end

        def enterprise_row_index(enterprise_name)
          enterprise_row_number = all('tr').index { |tr| tr.text.include? enterprise_name }
          enterprise_row_number - 1
        end
      end
    end
  end
end
```

The exact number of created enterprises (and order) is important to make the spec fail. This is surprising because the database is reset between examples. These enterprises shouldn't exist in the original spec. But I hope that this will help me find out what exactly is going wrong.

**Comment by mkllnk** [comment]
It's a sorting problem.
![Screenshot from 2023-02-24 11-59-30](https://user-images.githubusercontent.com/3524483/221066073-5f6c187f-6c23-48b5-9005-1450d92586da.png)

The test creates two enterprises `d` and `second_distributor`. Running the spec on its own, they are named "Enterprise 1" and "Enterprise 2". Then you assign the same owner to both of them and saving fails on the second enterprise. This is all good until there are ten enterprises and `second_distributor.name` become "Distributor 10". We sort in alphabetical order, not numerical and therefore the second distributor gets the new owner and the first distributor (listed second on the screen) can't be assigned a new owner.

There are two ways of solving this. First we could correct the order by naming the enterprises. But we could also reduce the test to check that only one of the enterprises has the new owner. Which one succeeds is random. We could also fix the code to roll back the transaction if there's an error. So none of the enterprises would get the new owner.

**Comment by mkllnk** [comment]
The problem here was the enterprise name and it's not influenced by the database. We reset the database every time but FactoryBot has a feature to give names like Enterprise 1, Enterprise 2, Enterprise 3 etc. This is stored in memory and doesn't reset:
https://github.com/openfoodfoundation/openfoodnetwork/blob/890ab6796ed87fc59eec3c99b9a773f19b330379/spec/factories/enterprise_factory.rb#L12

Maybe there's a way to reset the sequences between test runs? That could be useful.
