### ISSUE TITLE
[Product->Create] Snail when setting "0" in the unit value field

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10100]
## Description
An error 500 occurs when creating a new product and putting "0" in the unit value field. 

## Expected Behavior
There should be an error message displayed to the user, such as:
"1 error prohibited this record from being saved:  Unit value must be greater than 0."

## Actual Behaviour
The user gets the 500 error page

The failing request is:
POST | https://coopcircuits.fr/admin/products
500 Internal Server Error

## Steps to Reproduce
1. Create a new product (admin/products/new)
2. Fill in the required fields, choose a unit, and set "0" in the "value" field
3. See that for "item" unit you get the error, for any other unit you get the snail

## Animated Gif/Screenshot
![Dec-05-2022 16-51-09](https://user-images.githubusercontent.com/28386648/205682387-f081142c-6d43-4ff3-845d-e8e88afe5beb.gif)

## Workaround
Don't put 0. 

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by vviekk** [comment]
Hi, 

Would it be acceptable to not allow user to click "create" with value less than `0.1`?
* `0.1` is an arbitary number. Assumed the value can be smaller than 1, if it can't then we can make the min value to 1.

![image](https://user-images.githubusercontent.com/91144693/224630203-00810f1d-773d-492b-b3e2-7c20588da759.png)

**Note: that this is a user side fix and not part of the explicit validation we do in the app. It just ensures that the user can't put in 0 in that field.**

But if the requirement is to have an explicit check on server side and show the appropriate error message like the following, we can add it part of our validation.

![image](https://user-images.githubusercontent.com/91144693/224631092-39251517-f650-466c-93e6-da641d091ec3.png)


**Suggestion: I think having the user side check would be a better fix as we simply don't make the server call with data we know is not valid. Having said that, if the create call can also be triggered from some other source, then it makes sense to have that explicit validation on server side (with the user side check) so that we give a valid response instead of 500.**

Let me know what would be the proffered solution.

Thanks :)

**Comment by vviekk** [comment]
I see that we are okay with client side validation. Eg: https://github.com/openfoodfoundation/openfoodnetwork/pull/10241

Making the changes.

**Comment by vviekk** [comment]
Update: we expect the same field to take input for unit value with description as well. Eg: `12 Boxes` 

https://github.com/openfoodfoundation/openfoodnetwork/blob/f15cb01f2ab1a2358590c78a9926a5f5d8b5821a/spec/javascripts/unit/admin/products/units_controller_spec.js.coffee#L51-L54

So moving forward with the second option of having the zero validation at server.
* There is another option to validate at user side but we might not be able to give user the proper error message or at lest not consistently with other errors. So going with validation at server with specific error saying it can't be zero.

**We would have to add translate key for this specific error or least a partial of  "can't be zero".**

**Comment by drummer83** [comment]
> Would it be acceptable to not allow user to click "create" with value less than `0.1`?

@vviekk I am not sure about your current way forward. I don't understand much about client side vs. server side. Just one thing I am certain about: Checking for >= 0.1 is not acceptable, because we can have units of 0.01 and so on. The check needs to be for > 0 I guess.
Maybe your are going a different way anyway - then just forget about my comment here.
Thanks for working on the fix!

**Comment by jibees** [comment]
Hi @vviekk 
Hope you're doing well ;) I'll unassigned you, and move this issue to another state. If you still intend to work on it, will re-assign you!

**Comment by abdellani** [comment]
Hi
In the first case, when the unite size = 'items'.
you got the error because you left the **unit name** empty ( not because of the value of 0)
![](https://user-images.githubusercontent.com/28386648/205680837-d08c4829-961d-4999-9e16-fc545cfe1a51.png)

If you set that field and set the value to 0, you'll get that snail.

**Comment by audez** [comment]
yea you're right :) i update the issue!
