### ISSUE TITLE
[BOM] Orders sorted alphabetically by first name instead of last name

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10116]
## Description
In Bulk Order Management (BOM) page, when sorting the orders by "Name", they are sorted alphabetically by first name instead of last name. 

## Steps to Reproduce
1. Pass 2 orders with names and first name beginning by different letters (for instance Aude Zoo and Bless You)
2. In BOM page (admin/orders/bulk_management), click on the table element "Name" to sort the orders alphabetically
3. See that they are sorted alphabetically by first name (Aude Zoo will appear before Bless You)

As a comparison, you can see in the "Orders" page and in the reports that they are sorted alphabetically by last name (Bless You will appear before Aude Zoo)

### BOM Page: alphabetically by first name
![Screen Shot 2022-12-07 at 21 13 53](https://user-images.githubusercontent.com/28386648/206286136-c4764eb7-34f5-4440-9771-2295a082ee39.png)

### Orders Page: alphabetically by last name
![Screen Shot 2022-12-07 at 21 03 29](https://user-images.githubusercontent.com/28386648/206288356-03f6bf30-4dd9-455c-b979-1f0e0197d5f5.png)

## Workaround
A producer who is using the packing report and the BOM page is doing this: "In order not to waste a lot of time looking for names in the list, I have to modify the 'packing' report on excel, select each different product and classify them each time by first name. I've been doing it for 3 years every week and I have to say that in the long run it's tedious."

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by thejwuscript** [comment]
I'd like to work on this issue.

**Comment by drummer83** [comment]
Sure, @thejwuscript! I have assigned it to you.
Let us know if there are any questions!
Looking forward to your contribution!

**Comment by RachL** [comment]
Aaah I have not seen this issue before and I just want to be sure we agree on how to handle this before you start @thejwuscript (please feel free to add your opinion on this as it does not seem obvious - at least to me :D )

@drummer83 @filipefurtad0 @jibees @lin-d-hop @audez do we all find it logical that the order page sorts by last name while the column starts by first name? I mean I would find it more logical that the alphabetical order just focuses on the first letter, regardless of the content.

So if users prefer sorting by last name I would suggest switching the display order: Last Name first and First name last, rather than changing how the column handles the sorting. Does it make sense?

**Comment by drummer83** [comment]
To me, consistency is all that matters. ☺️

**Comment by audez** [comment]
100% agreed for me! I find it very disturbing that it's ordered by last name but first name appear first. It would be much more coherent to put last name first; and it would be great to add this logic in reports too, so it's fully consistent :)

**Comment by filipefurtad0** [comment]
Hey all - thanks for checking in on that @RachL

> I would suggest switching the display order

Agree :+1: 

Maybe a detail to keep in mind: currently, in the `/orders` page, only the `last_name` is considered in ordering ([see this comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/8615#issuecomment-1008852291)).

I guess it would be great to consider `first_name` as well (so entries with the same `last_name` are ordered correctly), when addressing this issue - ping @thejwuscript, in case this can be improved in your upcoming PR :-)

**Comment by RachL** [comment]
> it would be great to add this logic in reports too

Easy tiger :D  a lot of people have spreadsheet formulas which merge first name + last name on some reports to be able to link them with reports showing columns with first name + last name already together. If we reverse the latter, we introduce a breaking change for them. I'm not saying that we shouldn't do it at some point, just that it would be out of scope here.

@thejwuscript are you ok to do a PR to put Last Name in front of First name on the page `admin/orders/bulk_management` thus enabling that the sorting of the column focuses on last name instead of surname? This would close this issue.

For the order list page, we would create a different issue.

**Comment by thejwuscript** [comment]
Okay, so it will be sorted by last name, and names will be displayed last name first. (ex. Einstein, Albert)
If the last names are identical, then sort by their first names.

Thanks for the wonderful discussion, I'll be working on those changes.

**Comment by dacook** [comment]
As Filipe mentioned, we should create an issue to update the other orders page in the same way in order to be consistent:
`/admin/orders`
Now that the PR is complete, we can make use of the method added in this one.
