### ISSUE TITLE
[API v0] Products report: Columns 'on hand' and 'on demand' not showing on response

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10187]
## Description

Follow-up #10041, which adds 'on hand' and 'on demand' columns to the UI - these are not showing up on the API v0 requests. This is an acceptance criteria from #10035:

`6. These columns to be hidden by default in UI. API will return all data 'columns'.`

## Expected Behavior

 'on hand' and 'on demand' data should be returned from API requests.

## Actual Behaviour

 'on hand' and 'on demand' data is not being returned from API requests.

## Steps to Reproduce

1. Send a GET request:
`https://staging.openfoodnetwork.org.uk/api/v0/reports/products_and_inventory?token=db4e79475fd7c47979b60eaabf793d6dd053728122b42067&report_subtype="all_products"&q[distributor_id_in][]="1822"&q[order_cycle_id][]="3657"&fields_to_show[]=supplier`
2. You should get supplier data for the products on that report

3. Now modify the request to use `on_hand` or `on_demand` instead:
`https://staging.openfoodnetwork.org.uk/api/v0/reports/products_and_inventory?token=db4e79475fd7c47979b60eaabf793d6dd053728122b42067&report_subtype="all_products"&q[distributor_id_in][]="1822"&q[order_cycle_id][]="3657"&fields_to_show[]=on_demand`
4. Notice you get empty results for those orders.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/208931197-8e5575cd-1cdc-456c-bd3e-09d36ea6bfea.png)

**Comment by abdellani** [comment]
Hi @filipefurtad0 


I spotted the problem. 
There was a small difference between the queries.

When the `report_subtype` value in the query is between the quote marks, rails will load the base class instead of the targeted class.

I tried to debug the following method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/d61affd82be0db5ee91e542153d32748322a0c59/lib/reporting/report_headers_builder.rb#L31-L40
with `report_subtype="all_products"`
```ruby
(byebug) report.class
Reporting::Reports::ProductsAndInventory::Base
```
with `report_subtype=all_products`
```ruby
(byebug) report.class
Reporting::Reports::ProductsAndInventory::AllProducts
```

So the following query should work
https://staging.openfoodnetwork.org.uk/api/v0/reports/products_and_inventory?report_subtype=all_products&q[distributor_id_in][]="1822"&q[order_cycle_id][]="3657"&token=db4e79475fd7c47979b60eaabf793d6dd053728122b42067&fields_to_hide[]=

**Comment by filipefurtad0** [comment]
Alright :raised_hands: 
That's it - thanks @abdellani. This works now on staging - using the key from the producer hub:

![image](https://user-images.githubusercontent.com/49817236/209129849-c8d69c82-3850-428f-a03b-bf96e3f4a767.png)

Closing this issue.

> When the report_subtype value in the query is between the quote marks, rails will load the base class instead of the targeted class.

Thanks for pointing this out, did not think this could play a role. Is this something to improve?

**Comment by abdellani** [comment]
@filipefurtad0 

I think that throwing an exception is better than failing silently and loading the Base class.
