### ISSUE TITLE
Google Maps API warning: NoApiKeys

### ISSUE THREAD

**Issue by bingxie** [openfoodfoundation/openfoodnetwork#1022]
So we need a place to let users set their google map api key.

**Comment by pmackay** [comment]
You mean so each instance has its own API key? 

Would this make sense as an application.yml level config?

**Comment by pmackay** [comment]
@bingxie @mkllnk what is the Google API key needed for now, if Map page uses OSM?

**Comment by mkllnk** [comment]
Unfortunately, OFN uses both at the moment. It uses Google Maps for searching and OSM for the tiles.

**Comment by pmackay** [comment]
@mkllnk is that for doing address lookups? Is GMaps only needed on the maps page? (slightly different point)

**Comment by mkllnk** [comment]
GMaps is also used to search by location. For example, if you visit `/shops` and type "Melbourne", it uses Google Maps Geocode Service to find Melbourne and then filters enterprises by that location.

**Comment by elf-pavlik** [comment]
I can't even find where this GMaps API key currently gets send

**Comment by mkllnk** [comment]
Does it even get set? Maybe the GMaps API works without key, but it prints the warning?

**Comment by elf-pavlik** [comment]
On the staging I just deployed map breaks after few seconds https://ofn.hackers4peace.net/map

![screen shot 2016-12-21 at 11 01 03 am](https://cloud.githubusercontent.com/assets/876431/21398439/e7bef15a-c76c-11e6-85a8-b1d1e1d6c2cd.png)

**Comment by mkllnk** [comment]
I can't find it either. But I found [an answer](http://stackoverflow.com/questions/37991340/error-google-maps-api-error-missingkeymaperror) saying that our domain works, because it was active before June 22nd 2016. All newer apps need an API key now. We have two options:

- Add an option to configure an API key.
- Get rid of Google Maps.

If we wanted to get rid of Google Maps, we need another service to know where places are. We receive GPS coordinates for places in the search and for addresses of businesses. We use that to compute the distance between places and filter the search.

**Comment by myriamboure** [comment]
Just a question: if OSM is not so well fueled in Australia, why not taking the opportunity to map on OSM while registering new enterprises on OFN? Like when you put your address, if not found in the OSM database, you can clic to add it and you can select the spot on the map and save. Maybe I'm dreaming :-) But that could be a way to get rid of Google maps and contribute at the same time to enrich the OSM Commons...

**Comment by elf-pavlik** [comment]
I think we need quick fix to allow Google Maps API key in config. And later work on providing toggle alternative to only depend on OSM. This way each instance can choose 'consumer' or 'pioneer' mode depending on region and community.

**Comment by pmackay** [comment]
There are dozens of geocoding services listed on https://github.com/alexreisner/geocoder. Are any others preferable to Google? Some dont need a key.

**Comment by elf-pavlik** [comment]
PR #1359 adds `GOOGLE_MAPS_API_KEY` to config and uses it in layout following
https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API

with that patch now https://ofn.hackers4peace.net/map loads

**Comment by mkllnk** [comment]
@pmackay I know three currently used ways to provide api keys.

1. The Spree configuration already contains settings for some keys and credentials. The Google Analytics key can be set in the admin panel, right?
2. An environment variable set in `application.yml`. That's the quickest to implement and was chosen by @elf-pavlik in #1359 . It's probably a good place, because it is a quite important feature of OFN. But we should remember to include that in the ofn-install project as well.
3. Local Ruby files in `config/initializers/` are used to initialise code that needs api keys, for example for Bugsnag. This is good for custom code of completely optional services.

**Comment by pmackay** [comment]
@mkllnk thanks! I was slightly more wondering about best practice to make keys available in the frontend and whether keeping it hidden is a concern, but if not thats fine (and it follows Google recommendations, so in this case I guess not!). Agree option 2 works well for this for backend.

**Comment by sstead** [comment]
Testing notes:
Maps working normally.  Can search on map, can place a new enterprise on the map, can search shops/producers by location. Group maps and directory searching also working as normal.
