### ISSUE TITLE
Provide an error message when using text in variant fields

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10221]
## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/products/XXXXXX/variants/XXXX/edit`
**- I want to be able to do:** see an error message when adding text or invalid characters in weight, height, width, and depth fields.

Currently content is replaced by 0.0 with no notification to the user.

Design of the error message should be equivalent to what we have in the product creation page: top red banner with the error and culprit fields highlighted in red.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/6a18d038-e6b6-4b9f-a9f1-307aa1f9b118)

## Acceptance Criteria & Tests

1. Create a product or edit one
2. Edit the variant detail
3. Add text in weight, height, width, and depth
4. See error message. What you have typed in the field should still be available so you can understand the error

**Comment by binarygit** [comment]
Hey @RachL :wave: 
I took a look at this and but when I type a `string` into the value field, I'm getting an error (not an accurate error) and the string is still there. Am I doing something wrong? because I can't reproduce the bug.
![Screenshot 2023-01-04 at 14-00-15 Products - OFN Administration](https://user-images.githubusercontent.com/87677429/210512148-90130f77-2043-4c76-92b0-766d63b80344.png)

**Comment by RachL** [comment]
hi @binarygit sorry for the misleading screenshot, it is just here as an example for which design to apply. The page were the field are located is the variant edit page : so you need to create a variant first and then edit it to see weight, height, width, and depth.

**Comment by binarygit** [comment]
@RachL After reading the code, I found out that the reason the values are set to `0.00` when the user enters any `non-numeric` chars is because when rails updates the values for those columns, it's converting those values to floats using `to_f`. 
Any non-numeric values when converted to floats in ruby return `0.0`, for eg `']]]]'.to_i => 0.0`.

I think it's cumbersome to add a custom validation for this in our variants model because it would mean that we are checking ASCII char. sets and whether the chars in the inputted string fall within the range of that charset.
We would need to do this to display the errors in the fashion we have in the SS you posted above.

So, I have a proposal where, we let the browser handle the validation for us. It makes sure that the user can input only numbers, and doesn't let the user submit if they input anything other than a number.
The only downside is that we can't display the error like in the SS above (and that I have two tests failing that I need to resolve :sweat_smile: )

=============

I couldn't post a SS of what I'm talking about because for some reason the error that the browser shows aren't getting picked up (when I SS nor when I'm recording).
Can you please just checkout my branch and see what I'm talking about...and let me know if this works for us? :smile:
