### ISSUE TITLE
DFC Products Part II

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#10289]
:information_source: **This work is being delivered under two funded features.** 

For aspect of this project that are related to the development of OFN code please use the Clockify project with the following name when working on this, including review and test: `#9170 OFN DFC Products`

For aspects of this project that are related to the development of the connector code, which is a Ruby project that might be used outside of OFN, please use the Clockify project with the following name when working on this, including review and test: `#10828 DFC Ruby Connector`

## Description

#9170 got us a significant way through the DFC implementation. Now we need to finish :)

In this next phase we need to implement CRU(not D) functionality on the DFC product endpoint, and finish mapping all of the fields between DFC and OFN.

[This sheet](https://docs.google.com/spreadsheets/d/1cLSIyHrux93iAMitIVDqGBLrF9ascBgqHuc8AIfmF_k/edit#gid=659581349) summarises the mapping between OFN and DFC fields. There are a few outstanding questions and likely more to come up in implementation but I hope this is enough to get started.

The OFN fields to be made available over DFC are:

- OFN:producer
- OFN:sku
- OFN:product name
- OFN:display.name
- OFN:category
- OFN:description
- OFN:units
- OFN:unit.type
- OFN:variant.unit.name - _note this will likely be limited to 'items' by the DFC protocol_
- OFN:price
- OFN:on.hand
- OFN:available.on
- OFN:on.demand
- OFN:shipping.category
- OFN:tax.category - _note there are outstanding questions here_

There are lots of notes and caveats in the [spreadsheet](https://docs.google.com/spreadsheets/d/1cLSIyHrux93iAMitIVDqGBLrF9ascBgqHuc8AIfmF_k/edit#gid=659581349). Not every field is updatable and some fields will need hard coded mapping between platforms eg category.

## Acceptance Criteria & Tests

1. Implement CRU(not D) functionality over the relevant fields such that OFN product model is exposed via DFC
2. Document how any hard coded mapping eg categories can be updated when necessary
3. We'll need to keep track of any decisions and compromises we make during implementation
4. Update the OFN API handbook with links to help people use this.
5. Unit tests as standard

## Tasks

- [x] #10781
- [x] #10826
- [x] #11229
- [x] #10828
- [x] #11212

**Comment by mkllnk** [comment]
I tested out replacing our own serializers with the DFC Connector to generate DFC JSON. There are some differences and I would like to know if they are just due to an updated version of the DFC standard. The diff:
![Screenshot from 2023-02-13 15-07-06](https://user-images.githubusercontent.com/3524483/218368412-6d168101-b996-4c7d-8d4e-2fc232b7f829.png)
Old:
```json
{
  "@id": "http://test.host/api/dfc-v1.6/enterprises/927/catalog_items/1220",
  "@type": "dfc-b:CatalogItem",
  "dfc-b:references": {
    "@type": "@id",
    "@id": "http://test.host/api/dfc-v1.6/enterprises/927/supplied_products/1220"
  },
  "dfc-b:sku": "ABC",
  "dfc-b:stockLimitation": null,
  "dfc-b:offeredThrough": [
    {
      "@id": "/offers/1220",
      "@type": "dfc:Offer",
      "dfc:offers_to": {
        "@type": "@id"
      },
      "dfc-b:price": "19.99",
      "dfc-b:stockLimitation": 5
    }
  ]
}
```
New:
```json
{
  "@context": {
    "dfc-b": "http://static.datafoodconsortium.org/ontologies/DFC_BusinessOntology.owl#"
  },
  "@type": "dfc-b:CatalogItem",
  "dfc-b:references": {
    "@type": "dfc-b:DefinedProduct",
    "dfc-b:name": "Product #1 - 9639",
    "dfc-b:description": "Laboriosam culpa nobis maxime dolorum incidunt veniam. Dolor mollitia commodi itaque at voluptates consectetur. Dignissimos dolores non natus autem. Similique magni officia dignissimos blanditiis esse possimus. Neque cum tempora quidem quod voluptatibus aperiam.\nEum suscipit labore quisquam neque. Dignissimos sed nulla ad aspernatur consequatur. Animi voluptas iure facere quaerat sapiente sint inventore.\nLibero inventore asperiores a reiciendis accusantium. Harum consequatur quam dolorem voluptatem iusto minima. Laborum quas magnam fuga esse explicabo alias. Dolorum eligendi alias corrupti vitae. Cumque dolores ipsam ut sapiente.\nAsperiores et expedita reprehenderit fuga mollitia veritatis. Dignissimos vel vitae sequi dolorum sapiente. Eveniet omnis cumque soluta veniam in distinctio. Iste dolorum molestiae nemo voluptate eum quam doloremque. Accusantium ullam aliquam similique dolores repellat.",
    "dfc-b:hasClaim": [],
    "dfc-b:hasAllergenCharacteristic": [],
    "dfc-b:hasNutrientCharacteristic": [],
    "dfc-b:hasPhysicalCharacteristic": [],
    "dfc-b:referencedBy": [],
    "dfc-b:hasCertification": [],
    "dfc-b:hasNatureOrigin": [],
    "dfc-b:hasPartOrigin": []
  },
  "dfc-b:sku": "ABC",
  "dfc-b:offeredThrough": {
    "@type": "dfc-b:Offer",
    "dfc-b:price": 19.99,
    "dfc-b:stockLimitation": 5,
    "dfc-b:offeredItem": "/offers/1220",
    "dfc-b:offeredTo": []
  },
  "@id": "http://test.host/api/dfc-v1.6/enterprises/927/catalog_items/1220"
}
```

**Comment by RaggedStaff** [comment]
The changes are mainly due to recent enrichment of the product ontology - the product facets have been more clearly defined & structured.

The JSON-LD looks valid to me, if a little ugly, have you put it through [the playground](https://json-ld.org/playground/) ?  I don't think we need to list all the blank facets,  I'll check in with Maxime about that. I'm also a little wary of the switch from SuppliedProduct to DefinedProduct, I don't know if the Prototype will accept that.

Final thing -  I can't see Product Type, do we need to map OFN Product categories to the DFC list ? (There will be gaps).

**Comment by lecoqlibre** [comment]
Great to have this! Thanks @mkllnk :)

The differences could be explained by:
- you have created a `DefinedProduct` instead of a `SuppliedProduct`.
- if you don't call the `semanticId=` setter, the object will be considered as a _BlankNode_ by the exporter so it will be nested in the returned JSON (dereferenced). In this example this applies to the product and to the offer.
- facets have been added to the `DefinedProduct` and all sub classes so the product contains more properties.

We should:

- discuss whether we should remove the empty properties like the facets in the exported JSON. @RaggedStaff I agree to remove them.
- add an option to _dereference nested objects_ to the `export` function of the connector. Right now it can export a single object that will not include nested objects (no dereferencing). The old example is mixing _references_ (`SuppliedProduct`) and nested _dereferences_ (`Offer`).

Right now I'm working on the `import` and `export` function of the connector (using the Semantizer library).

**Comment by mkllnk** [comment]
>  I can't see Product Type,

That's called Taxon in our database or Category on the old API. But I don't see it in the list to implement for this issue above. So I think it's out of scope.

But if we get to that at some point then we should probably rename the types in our database. They are user-defined per OFN instance.

> you have created a DefinedProduct instead of a SuppliedProduct.

Okay, I corrected that now.

> if you don't call the semanticId= setter, the object will be considered as a BlankNode by the exporter so it will be nested in the returned JSON (dereferenced). In this example this applies to the product and to the offer.

Okay, to get output that's closer to the old one I set `semanticId`. The new output is much smaller. Thank you for achieving this.

```json
{
  "@context": "http://static.datafoodconsortium.org/ontologies/context.json",
  "@type": "dfc-b:CatalogItem",
  "http://static.datafoodconsortium.org/ontologies/DFC_BusinessOntology.owl#references": "http://test.host/api/dfc-v1.6/enterprises/243/supplied_products/636",
  "dfc-b:sku": "ABC",
  "dfc-b:offeredThrough": {
    "@type": "dfc-b:Offer",
    "dfc-b:price": 19.99,
    "dfc-b:stockLimitation": 5,
    "dfc-b:offeredItem": "/offers/636"
  },
  "@id": "http://test.host/api/dfc-v1.6/enterprises/243/catalog_items/636"
}
```

Strangely, `references` is not shortened any more. Is that something I'm doing wrong?

**Comment by lecoqlibre** [comment]
@mkllnk You should set the semanticId on the `Offer` too. When your are exporting the data from OFN the primary objects must have an ID otherwise the prototype or other platforms won't be able to reference these objects.

Doing so will remove the object. Then to also include the `Offer` in the exported JSON you could export it along with the `CatalogItem`:
```
connector.export(catalogItem, offer)
```
The exported objects will be put in a `@graph` container.

> Strangely, references is not shortened any more. Is that something I'm doing wrong?

Yes I had the same problem. It seems like this issue is coming from the third-party JSON library we use. But this should not invalidate the JSON. I'll create an issue for this.

**Comment by RachL** [comment]
@mkllnk you should be able to use the DFC prototype again if needed.

**Comment by sigmundpetersen** [comment]
Seems like we could convert this to an epic to keep track of the different sub issues.
We could also keep it in Dev Ready as we do with the other roadmap items.

What do you think @mkllnk ?

**Comment by mkllnk** [comment]
@sigmundpetersen 

> Seems like we could convert this to an epic to keep track of the different sub issues.

Yes, sounds good.

> We could also keep it in Dev Ready as we do with the other roadmap items.

Okay, will move.
