### ISSUE TITLE
BOM page is not finding or displaying name, email or  order number  for some orders

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#10363]
## Description

Bulk Order Management page is not finding or displaying  the buyer's name,  email,  or the order number.  This is only happening for some orders.   The information appears fully in all reports.    If I click to open one of the orders in BOM that is  missing information,   I get the snail.

This does not seem to be a filtering issue -   it happens even if I do not select filters (ie just search for all orders for a given hub)

I am trying to figure out what the affected orders have in common -  and I THINK it could be that this happens when an order cycle is re-opened.  -  ie:  the same order cycle was closed,  but later re-opened by extending the close by date.  And I THINK that this happens when orders are placed in the front office,  AND if an edit is made to the order in a re-opened order cycle.,

## Expected Behavior
BOM page should show the customer name , order number..  for all orders in a given order cycle (or other filtered parameters) - even if the order cycle is re-opened.

## Actual Behaviour
For some orders,  BOM is not displaying full information.

## Steps to Reproduce

1.Place an order in an order cycle.
2. Close the order cycle.
3. Reopen the same order cycle by extending the close date -  do not change its name,  or open date.
4. Place a second order in the re-opened order cycle.
5. Verify that both orders appear on the Orders page,  using the order cycle filter.
6. Check to see if order number & buyer name... appear for both orders in BOM.

## Workaround
If the user selects to display '100 per page'  the missing order numbers and names miraculously appear!!

## Severity
s3.  

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment]
![buyer details missing in BOM](https://user-images.githubusercontent.com/13171778/216375829-3dcf1e20-e16f-4b6e-a4e3-4b3049381d07.png)

**Comment by BethanOFN** [comment]
Have also had a user report this in UK - have found a workaround for showing the order no/name/email in the list is to click '100 per page'

**Comment by audez** [comment]
Also seen on FR Prod, thanks for the workaround!

**Comment by tschumilas** [comment]
OMG -  I'd have never thought of that workaround -  that is awesome.  this is moved to an s3 then for sure.... THANKS!!

**Comment by filipefurtad0** [comment]
Some thoughts on my side:
- this is reproducible in staging - easiest way to see it is logging in as superadmin into staging-UK and visiting the BOM page. If one is logged in as an enterprise owner then the bug does not always occur
- This might have been introduced when [pagination was added](https://github.com/openfoodfoundation/openfoodnetwork/pull/10243) to the BOM page
- The workaround is not obvious to the user, and does not always work - at least in staging, I've just observed some such cases (for example: to the Last page in pagination; select 100 results per page)
- the snail occurs because the request to edit the page does not include de order number - the redirection occurs to something like `admin/orders//edit`, which triggers a 404, but yes a snail is visible to the user
- this is a regression and I'd vote to either revert the PR #10243 or make it an S2

Ping @openfoodfoundation/train-drivers-product-owners

**Comment by RachL** [comment]
@jibees can you have a look into it?

**Comment by tschumilas** [comment]
Is it possible that this issue - https://github.com/openfoodfoundation/openfoodnetwork/issues/9148  is also related to pagination?

**Comment by jibees** [comment]
As #9148 is few months old, I'd say it's not related (since pagination is more recent).
