### ISSUE TITLE
Pagination in BOM not aggregating results from quick search field

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10400]
## Description

Related to #10375.

If a search is made on BOM and the results are filtered through the quick search field, then these are spread out between different pages.

## Expected Behavior

Pagination should consider the results from the quick search field.

## Actual Behaviour

Pagination is not considering the results from the quick search field.

## Steps to Reproduce

1. Visit BOM on a hub with plenty of line items / orders so that these are spread out through several pages
2. Use the quick search for a name or line item
3. Notice these are appearing in the respective pages, and that the pagination numbering is inconsistent.

## Animated Gif/Screenshot

searching for "name" - which in this case can be a customer name, but also a line item:

Page 1 
![image](https://user-images.githubusercontent.com/49817236/217539967-fed5a9d4-35b1-4c8e-8fd7-287b24717d36.png)

Page 2
![image](https://user-images.githubusercontent.com/49817236/217540067-a49a5e3b-b12c-4170-adb2-dd29ef92cadd.png)

Page 3
![image](https://user-images.githubusercontent.com/49817236/217540179-2375ece0-bd24-4370-a41d-6d3785942410.png)

## Workaround

Navigate through the different pages, to see the results from the quick search field.

## Severity

I think all results are appearing. bug-s4?

## Your Environment

* Version used: current master d5b0891a748d8238936f7555946bb7788faa7f72
* Browser name and version: Firefox 109
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by jibees** [comment]
Yep, this is more a searching/filtering for the results of the current page (ie. displayed) than a search that refresh data. That's why this input is below the "filter results" button and near other actions that change the display of the current result. Actually, I'm not sure this is a bug... Maybe it's not clear enough?

**Comment by drummer83** [comment]
Just wanted to mention that the displayed number of results and the 'viewing' number need to be adjusted as well, when working on this.
![image](https://user-images.githubusercontent.com/1790176/218132011-dd364750-19a4-4df5-a400-bfc39bdf12c8.png)

**Comment by RachL** [comment]
@jibees I think it's also disturbing for users that compare this to the regular orders page. What would be your estimate to move the quick search above the filter and make it work with pagination? (I'm trying to see if we are looking at papercut material here).

**Comment by jibees** [comment]
Regarding the regular orders page (ie. `/admin/orders`), I cannot see any search. Am I missing something?

<img width="1359" alt="Capture d’écran 2023-02-15 à 10 17 38" src="https://user-images.githubusercontent.com/296452/218985392-a002f69d-02ff-469b-a72d-399026ab847a.png">

On products page, we do have a search:

<img width="1385" alt="Capture d’écran 2023-02-15 à 10 18 23" src="https://user-images.githubusercontent.com/296452/218985548-276c8b47-fa9a-4b99-b840-43a51da2dd8d.png">

I guess it's about 1 day to add this kind of search into the BOM page and remove this view filtering component.

**Comment by RachL** [comment]
ooopsy yes I meant product page 🙈

**Comment by jibees** [comment]
One comment.
I started working on it, but I'm wondering what kind of search we want to _create_.

 - **Previously**: we searched through all attributes a line item has, this was pretty easy because all data were present, consolidated, and displayed. 
 - **What we have now**: we have a paginated displaying that request server for each page and the conciliated data with the associated order (what basically do https://github.com/openfoodfoundation/openfoodnetwork/pull/10375)

**So what?**

 - Adding a search filter that search for on line_items attribute (like it's already done for Product and its name) is pretty easy: 
<img width="1360" alt="Capture d’écran 2023-02-17 à 09 30 30" src="https://user-images.githubusercontent.com/296452/219593354-2d45078e-7249-4439-99b6-dbc66111a1fa.png">

 - Searching for all attributes that build a displayed line items is not that easy. 

Then, I'm wondering if there can have a quick win: user mostly search through _insert a line item attribute here_, so let's do that quick win for now, and open an issue to improve that search. 

What do you think?

**Comment by jibees** [comment]
(Actually maybe I'm wrong and we could create a search query that search for all attributes ; I should investigate more)
