### ISSUE TITLE
[Split checkout] Users without shipping address are not able to reach step2 if there is only a pickup shipping method in step 1

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10479]
## Description

See user info here: https://openfoodnetwork.slack.com/archives/C01V3KW8RSM/p1677251613703549?thread_ts=1677249745.577039&cid=C01V3KW8RSM

when this user tries to go to payment step, they see an error message saying they should add a shipping address. yet the only shipping method is a pickup one (no shipping address required).

couldn't reproduce on staging, couldn't reproduce with my US super admin account 🤔 

## Steps to Reproduce

1. Go to https://openfoodnetwork.net/open-food-network-usa/shop#/shop
2. Go to /cart
3. Try to go to payment step
4. See error message on shipping address

## Animated Gif/Screenshot

See videos here: 

https://openfoodnetwork.slack.com/archives/C01V3KW8RSM/p1677249745577039

## Workaround

None

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.1.25
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Windows and ubuntu

**Comment by drummer83** [comment]
See #9056.

**Comment by rioug** [comment]
I managed to reproduce the issue by "massaging" my data , you need to make sure you have Customer with no shipping address when on the checkout page, then the error will trigger. I'll look at fixing it tomorrow

**Comment by audez** [comment]
Finally it was it.. 
The issue is big because it impacts all customers who previously checked out on legacy but didn't choose to save their address. All those who are registered in "Customers" list but don't have a shipping address.
![Uploading Screen Shot
![Screen Shot 2023-03-08 at 21 21 55](https://user-images.githubusercontent.com/28386648/223872745-94b8e5e7-256f-4ad5-bd5e-7d1343c2dcf3.png)
 2023-03-08 at 21.22.40.png…]()

It was hard to reproduce/understand because there must have been a recent change: if you take a fresh account today and do legacy (or split) checkout without choosing "Save shipping address", it will save the shipping address anyways. 

So to reproduce the case you have to:
- Create a fresh account
- As an admin of a shop in "Customer" tab, register the mail (don't put the shipping address)
- Checkout on split checkout on this shop with this customer account

Workarounds are: 
- Set it as an admin in Customers tab
- Checkout on a shipping method "Delivery" then come back
- Switching shipping method from "Pickup" to "Delivery"

They will all allow to update the shipping address.

The reason of the 422 error is: when sending the request the shipping address fields are empty and the request fails with 422.
![Screen Shot 2023-03-09 at 00 12 55](https://user-images.githubusercontent.com/28386648/223873689-29e0d395-bbeb-41e0-8978-9d9e0503db49.png)

It looks like normally, for pickup methods, if customer has no shipping address, the shipping address is inherited from the billing address - you can test it by checking out on split checkout, then deleting the customer in Customers tab, re-creating it with only the billing address - checking out again with no error and seeing that shipping data = billing data.

But it seems that for billing addresses that was saved from legacy checkout, the shipping address is not inherited and will be empty. This would be the case for our users. 

PS: sorry for the misleading [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9056#issuecomment-1266669916), now i can see in the screens that the failed requests was only when at least one field of shipping address was empty. There was no link with `order[bill_address_attributes][id]`
