### ISSUE TITLE
[Spike] Analyze if coordinator's column can be displayed for non coordinator producers

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10611]
## Description

**- As a:** profil only producer or producer shop, which is not coordinating an OC
**- On page:** `admin/order_cycles`
**- I want to be able to do:** Currently the column "coordinator" can be selected on all profiles. But the column will not show up if the user is a producer profile only or a producer shop AND the user is not coordinating any OC.

We need to understand if there is a reason this was not done or if this is a bug.

## Acceptance Criteria & Tests

1. Understand if displaying the columns can be done easily or not
2. Open issues accordingly: either displaying the column or removing the option to display this column for these profiles
3. if the work is papercut leave it in main repo, otherwise open issues in wishlist repo

**Comment by jibees** [comment]
###### Dev notes

We're not showing thoses columns (`producers`, `coordinators`, `shops`) because of the `simple_index` var, defined like this:
https://github.com/openfoodfoundation/openfoodnetwork/blob/068ac40a76e2eed50fcd8908b94e58494040b711/app/helpers/order_cycles_helper.rb#L55-L57

`can_manage_complex_order_cycles` is defined: 
https://github.com/openfoodfoundation/openfoodnetwork/blob/068ac40a76e2eed50fcd8908b94e58494040b711/lib/open_food_network/permissions.rb#L9-L13

`managed_and_related_enterprises_granting` is defined:
https://github.com/openfoodfoundation/openfoodnetwork/blob/068ac40a76e2eed50fcd8908b94e58494040b711/lib/open_food_network/permissions.rb#L151-L160

and `related_enterprises_granting` is defined:
https://github.com/openfoodfoundation/openfoodnetwork/blob/068ac40a76e2eed50fcd8908b94e58494040b711/lib/open_food_network/permissions.rb#L127-L134

**Comment by jibees** [comment]
Context on why this has been introduced is a bit difficult to understand: commit is 8 years old, no PR, no issue linked. The only thing we have is the commit message:
> Enterprise user selling own produce only sees simple order cycle listing

I guess this is something about: simplify the view for enterprise that only sells their own products (and only that).

**Comment by jibees** [comment]
Now, we have two main options:

 - Either, allow the user to **display those 3 missing columns** (producers, coordinators, shops) in the view by (almost) reverting this 8 years old commit ;
  - Or **remove those 3 columns from the Column Selector** in that particular case. 
  
  
Solution 1 is pretty simple (technically, setting aside the fact that maybe this has been done for a clear and still available reason). 
Solution 2 should be also pretty straightforward.

I think it's more a question for @openfoodfoundation/train-drivers-product-owners to know what the best solution is. 


_Reference for dev:_
Solution 2 could be something like:
```ruby
diff --git a/app/models/column_preference.rb b/app/models/column_preference.rb
index a4e52b577c..1729eb50c2 100644
--- a/app/models/column_preference.rb
+++ b/app/models/column_preference.rb
@@ -49,5 +49,11 @@ class ColumnPreference < ApplicationRecord
     return unless action_name == 'order_cycles_index'
 
     default_preferences.delete(:schedules) unless user.admin? || user.enterprises.where(enable_subscriptions: true).any?
+
+    return if OpenFoodNetwork::Permissions.new(user).can_manage_complex_order_cycles?
+
+    default_preferences.delete(:producers)
+    default_preferences.delete(:coordinator)
+    default_preferences.delete(:shops)
   end
 end
```
+ adding specs and maybe we should be more integrated/synchronised between model and view

**Comment by RachL** [comment]
@lin-d-hop do you have a clue why we would hide these columns? Was there any privacy concerns?

**Comment by lin-d-hop** [comment]
Apologies to reply so late.

I can't think of any reason. i think at the time of hiding/displaying these the motivation was simply to make the 'simple' OC as pure as possible. I don't think there was a privacy concern.

So maybe we go for option 1...?

**Comment by jibees** [comment]
I agree: Issue opened https://github.com/openfoodfoundation/openfoodnetwork/issues/10682 !!
