### ISSUE TITLE
Remove admin_style_v2 toggle

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10634]
## Description

As we are starting over in #10630, we will introduce a new feature toggle.

All associated code should not be reused

## Acceptance Criteria & Tests

1. The toggle should not be available anymore on `/admin/feature-toggle/features`
2.  Colors in the backend should remain unchanged.

**Comment by dacook** [comment]
@jibees , I'm sorry to have the job of removing the code you wrote. I didn't read through the history but assume there was a good reason. I hope that the history will still be a good starting point for the next steps.

So to make sure I'm removing all the right things, I looked for PRs with  "v2" in the name and found these four:

1. https://github.com/openfoodfoundation/openfoodnetwork/pull/10025/files
2. https://github.com/openfoodfoundation/openfoodnetwork/pull/10054/files
3. https://github.com/openfoodfoundation/openfoodnetwork/pull/10080/files
4. https://github.com/openfoodfoundation/openfoodnetwork/pull/10131/files

I noticed some new classnames that aren't otherwise used (eg ["secondary"](https://github.com/openfoodfoundation/openfoodnetwork/pull/10131/files#diff-f26b7dd38ad9ac173f82f442c6b5a0af10dbe3a71b62aca9b632cd41babe33c5)), so I think these will need removing along with everything else, otherwise they will unused.

So my plan is to revert all the commits in those four PRs. Does that sound good to you, or is there any other things to be aware of?

**Comment by dacook** [comment]
I went ahead and did this, please take a look and let me know what you think.
