### ISSUE TITLE
Move all managed instances to "Fully Enabled" split_checkout toggle

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#10658]
## Description
**- As a:** shopper
**- On page:** /checkout
**- I want to be able to do:** Only split checkout if I purchase an order on an instance managed by OFN global

## Acceptance Criteria & Tests

Split_checkout must be fully enabled or targeting 100% of actors on:

- NZ
- ES
- IE
- HU
- BE
- DE
- FR
- UK
- US
- AU
- CA

**Comment by dacook** [comment]
Hi, I'm not sure what has been discussed already, but if we want to fully enable split_checkout, why don't we remove the feature toggle altogether? Is it because we still want the old method as a backup? Or to continue supporting it for non-managed instances?

If we want to keep the toggle but enable for all instances, why don't we trust the instance managers to set that up?

In any case, it seems that we should start planning to remove the old method, and post an end-of-life notice about it with a date.

Sorry if this has already been answered elsewhere.

**Comment by dacook** [comment]
Thanks Rachel. If it helps unblock other work quickly, then I think a migration to fully enable the toggle is a good idea 👍
