### ISSUE TITLE
Missing translation: confirmation (order state)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10718]
## Description

The admin orders page displays a missing JS translation error for orders in the `confirmation` state

## Expected Behavior

Confirmation state should be translated

## Actual Behaviour

JS error is displayed

## Steps to Reproduce

1. Create an order in the confirmation state (summary step of split checkout, via UI)
2. Visit the orders page and untick the option to display only complete orders
3. See the JS translation error

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/232829145-446a126e-15e2-4243-a302-0bb1819c61e9.png)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.3
* Browser name and version: Firefox 111
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by filipefurtad0** [comment]
@jibees Maybe we could update `spec/system/admin/orders_spec.rb:279` to include this state (I'm happy to do that).

I'm wondering: why don't we see the JS error on the console, when running a spec with

`order3.update!(state: "confirmation")`

I'd expect this as we have the `js_errors` set to true on `spec/system/support/cuprite_setup.rb`...

**Comment by jibees** [comment]
> Maybe we could update spec/system/admin/orders_spec.rb:279 to include this state (I'm happy to do that).

Yes, good idea, will do that (seems pretty easy ;))

> I'm wondering: why don't we see the JS error on the console, when running a spec with

Because there isn't any js error in the console, only a warning in the view. 



+ Seems like we also forgot to assign a color to this state ... ;)

<img width="664" alt="Capture d’écran 2023-04-18 à 17 43 35" src="https://user-images.githubusercontent.com/296452/232830667-59ad64e9-4abe-4f53-8a69-acbb834b41cc.png">

I think I will assign the same orange than cart, but maybe you (I mean @openfoodfoundation/train-drivers-product-owners ) have a better idea?
