### ISSUE TITLE
[Checkout][BO orders] Viewing an order in state "confirmation" changes the state to "complete"

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10719]
## Description

EDIT: This happens for logged-in users as well as guest users. 

A user initiates checkout ~~as a guest~~, adds items, details, and selects payment but leaves at the summary step: order is left on state `confirmation`.

In the backoffice, if an order is viewed by the hub, it will progress to complete, without any action taken (other than visiting `admin/orders/<order_number>/edit`).

## Expected Behavior

Viewing an order as admin should not change the state of ~~guest~~ orders (the customer has not completed checkout, not agreed to ToS nor T&Cs).

## Actual Behaviour

Even if a ~~guest~~ user has not completed checkout on that shop nor agreed to ToS/T&Cs, the order will be completed by the admin, if the edit path is visited.

## Steps to Reproduce

1. As a customer begin checkout but stop at the `summary` step.
2. As an admin, visit /orders and uncheck the complete orders checkbox.
3. Find the order placed on step 1., and click the pencil icon (edit).
4. Notice that the state of the order changes from `confirmation` to `complete`.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/232839902-ca1d6465-8da5-4e24-be35-d0c921d755be.png)

## Workaround

?

## Severity

Not sure, maybe an edge case?

## Your Environment

* Version used: v4.3.3
* Browser name and version: Firefox 111
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by sigmundpetersen** [comment]
Maybe we should bump this to s2?
It's a bit ugly if the customer really wanted to stop at the summary step, then hubs completing the order by just visiting the order.
@filipefurtad0 @lin-d-hop @jibees what do you think?

**Comment by jibees** [comment]
I agree @sigmundpetersen. But I prefer to let answer @openfoodfoundation/train-drivers-product-owners ;)

**Comment by filipefurtad0** [comment]
Seems not to be an edge case, as some customers proceed only to the `/summary` page, as [reported here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1685662220843669), so I'd agree with bumping the severity :+1:

**Comment by drummer83** [comment]
I have just verified that this is not only happening for guest users but for logged-in users as well.
Will update the opening post.

**Comment by abdellani** [comment]
## Current behavior 

When the admin access the order's details page, there's an instruction to move the order's state to `payment`. (I'm not too fond of the idea. As an admin of the app, I wouldn't expect to change the order's state by just accessing it to view the details)

Since the order is already in the `confirmation` state, the `OrderWorkflow.advance_to_payment`  keep moving the order state forward until it reaches the final state `complete`).


The same thing happens when The user/guest starts an order and stops in the first step ('cart' state).
If the admin access that same order, the order will move automatically to `payment` (I don't know if this is a desired behavior)

https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/51db556b-fdcf-49ab-8678-f4743aa48a0b


In the first implementation of the [orders controller](https://github.com/openfoodfoundation/openfoodnetwork/pull/4513), I found the following comment:

> We should verify, on the edit order page, the order state and total value as well as the shipment and payment state appear correctly on the right side menu: the shipment/payment state only appear if the order is complete.

Is this still valid today?

## Possible solutions

I see two possible solutions:
1. stop moving the order state from the order's details page. (I'm testing this on #10936 )
2. change the behavior of `OrderWorkflow`, so that if the order is already in an advanced state (vs the target state), we don't run the loop to change the state. (this may affect other parts)

**Comment by Matt-Yorkley** [comment]
> When the admin access the order's details page, there's an instruction to move the order's state to payment. (I'm not too fond of the idea. As an admin of the app, I wouldn't expect to change the order's state by just accessing it to view the details)

Agreed, it's not nice. 

Okay there's a couple of things here; I think there are some cases where this logic is needed, like when an admin is creating a new order from scratch and adding a customer and their address and hitting save, we need to advance to payment state if it's valid. But the current code is blindly trying to advance it to payment all the time, and it's doing it in the `edit` action which is a terrible idea.

So I think we want to move it out of the `edit` action and into the `update` action for starters, and then we probably want to restrict it to something like:
```ruby
OrderWorkflow.new(@order).advance_to_payment if @order.state.in? ["cart", "address", "delivery"]
```

and it probably wants to come after the order has been (successfully?) updated with the `order_params`.
