### ISSUE TITLE
[Registration] An enterprise name already in use leads to being stuck in the process

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#10711]
## Description

When registering a new enterprise through the /register page, it can happen that the enterprise name a user entered on step 1 is already taken by another enterprise. There is an error message after step 3 and the 'Create profile' button gets disabled. However even after going back to step 1, entering a new name and proceeding to step 3 again, the 'Create profile' button is still disabled. I couldn't find a way to continue the process. I had to start all over again.

This is similar to #10216.

## Expected Behavior

The button 'Create profile' must become enabled again after the user has changed the enterprise name. If the (new) name is still taken, the error message should display again when clicking the button. If the name is available, continue to step 4.
The best case would be to check the enterprise name already after step 1 and display a message here that another name should be chosen. This part is optional though.

## Actual Behaviour

After the error message is shown, the button 'Create profile' is disabled and it remains disabled even after going back and entering a different enterprise name. There is no way to get from step 3 to step 4.

## Steps to Reproduce

1. Visit /register page.
2. Type an enterprise name which is already in use by another enterprise.
3. Fill in all other required fields and continue to step 3. 
4. Click 'Create profile'.
5. Observe the error message and that the button becomes disabled.
6. Go back to step 1 and enter a different enterprise name.
7. Proceed to step 3 again and try to continue. This is not possible due to the disabled button.

## Animated Gif/Screenshot

https://user-images.githubusercontent.com/1790176/232523573-3a88c32b-c0d6-4337-8bf6-5ae52a2d8c81.mp4

## Workaround

Start all over again.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by drummer83** [comment]
Sure, @cyrillefr, I will assign it to you.
Thanks! 👍🏻

**Comment by cyrillefr** [comment]
Hello @drummer83, 

I have looked at this issue. I have also had a look at #10216 (and the corresponding PR #10232).
There is a common pattern with the button that stays disabled that sticks users in the process.

My idea is to do a "simple" PR that addresses of course this issue but also this more general pattern.
Because I think this problem may appears each time an unexpected error returns.

From #10232, I read:
> This seems a great quick solution. But I've one concern: I'm wondering if this one solves the original issue, which is that user is block if they get back and then want to step forward. I don't think so, but I could be wrong. @binarygit any thoughts?

I have a solution for that: enable the button at step 3 (type) each type the back button is pressed from step 2 to step 1.
To do that, all I have to do is to extract the isDisabled property and its setter/getter from the scope for step 3 and put it at the form scope, so that it is available and common to every steps. Local test is OK.

What do you think of my idea ?

**Comment by drummer83** [comment]
Hi @cyrillefr,
Thanks for your proposal!
I think we need a @openfoodfoundation/core-devs to answer this.

**Comment by cyrillefr** [comment]
Hello @drummer83 , 

Do we/I need to contact someone ?
Is there an action to be taken ?
