### ISSUE TITLE
Create new order in backend - payment method fees not added

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1098]
This order is for $10.70. 
When I select Payment method 'cash with fee' ... 10c is added to the order as the fee for payment method. 
But this 10c isn't added to the payment.
![image](https://cloud.githubusercontent.com/assets/10843056/16972243/3334c214-4e6d-11e6-94ac-cbcca1eb7f48.png)
See how the amount due is $10.80 but the payment is for just $10.70. 
![image](https://cloud.githubusercontent.com/assets/10843056/16972245/397f83ac-4e6d-11e6-8c04-2a37e0e2f37d.png)
So if I click 'capture' only the $10.70 is marked as paid and the $10.80 is still due.
![image](https://cloud.githubusercontent.com/assets/10843056/16972253/4de104d8-4e6d-11e6-81ee-0cf325a589f8.png)

**Comment by myriamboure** [comment]
It seems to me that this bug is fixed, I retested and working good: I tested with a % type fee (https://www.useloom.com/share/729ba09c3de94977bd5cf072db49f2d5) and 10ct per order (https://www.useloom.com/share/f43e0390bbd5438eb0cb8ee82be5639c), no bug, the amount paid is the products + fees, well calculated and included in amount paid.
One thing that can be discussed is how payment fees are calculated, seems they are calculated on product cost exculding entreprise fees, which can be discussed but I'll open another issue/discussion on that if needs be. Closing, @sstead feel free to reopen if you see on your side that the bug is still there.
