### ISSUE TITLE
[Invoices] 'Actions' dropdown menu disappears after creating the first invoice

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11049]
## Description

Follow up of #10532.

After creating the first invoice the button for the 'Actions' dropdown menu disappears. Leaving and coming back to the invoice page brings it back.

## Expected Behavior

As soon as there is an invoice the actions dropdown menu should be available.

## Actual Behaviour

The menu disappears after the first invoice is created.

## Steps to Reproduce

1. Go to the invoices page.
2. Create a first invoice.
3. Observe the action dropdown menu.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by abdellani** [comment]
Looks like this problem is related to the usage of [angular.bootstrap](https://docs.angularjs.org/api/ng/function/angular.bootstrap)

https://github.com/openfoodfoundation/openfoodnetwork/blob/f6db69104fe8caa6bfafc209f2cb949aa25e89c6/app/views/spree/admin/shared/_order_links.html.haml#L3-L4

When the page is loaded for the first time, the angular component will be loaded to render the dropdown.
After generating the invoice, the `li` will be updated but the AngularJS code will not be called since the page is already loaded.

what do you think @jibees ?

**Comment by jibees** [comment]
> what do you think @jibees ?

Short answer: remove that angular dropdown... But I think it's probably widely used, and has maybe some implications i don't see right now.

**Comment by abdellani** [comment]
> But I think it's probably widely used, and has maybe some implications i don't see right now.

Yes, I confirm. It's used (at least) on the Order details pages on the admin dashboard.
Maybe we need to replace that component with something in haml/stimulus?

**Comment by jibees** [comment]
> Maybe we need to replace that component with something in haml/stimulus?

I suppose it could be a good idea. Would you like to deep dive into? Or should I go into?

**Comment by abdellani** [comment]
Yes, can you please do it :+1:
