### ISSUE TITLE
Non-empty orders in the cart state do not appear in orders page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11120]
## Description

PR https://github.com/openfoodfoundation/openfoodnetwork/pull/8148/ introduced hiding of cart orders, with no line-items.

It seems that since more recently, even non-empty orders are not appearing on the `/orders` page.

## Expected Behavior

Non-empty orders in the cart state, should appear in the `/orders` page.

## Actual Behaviour

Non-empty orders in the cart state, are not appearing in the `/orders` page.

## Steps to Reproduce

As a customer:
1. Visit a shop and add some items to the cart; proceed to the `/details` step.

As a hub:
2. Visit the /orders page
3. Uncheck "Display only complete orders"
4. Filter results -> notice the order is not appearing in the results

## Animated Gif/Screenshot

-

## Workaround

None; cart orders cannot be edited by the hub.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.4
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

From the spec https://github.com/openfoodfoundation/openfoodnetwork/pull/11121, it looks like non-empty cart orders:
- with **non-null** `bill_address_id` and `ship_address_id` -> appear on the `/orders` page
- with **null** `bill_address_id` and `ship_address_id` -> do not appear on the `/orders` page

This may relate to split-checkout design, in which orders only get address info after submitting the data from the `/details` step... However, moving from `/details` -> `/payment` changes the order state from `cart` -> `payment`...

**Comment by lin-d-hop** [comment]
I'm not sure this is an s2. I don't think viewing uncompleted carts counts as 'critical feature'.

Downgrading to s3 until a user complains.

**Comment by abdellani** [comment]
Hi @filipefurtad0 

Case 1: As a user (or a guest) who has already set a billing address
--- 
It is not possible to reproduce this bug with a registered user (or a guest) who already set his billing address
When I visit a shop, an order is created in the background. That order will start with `state=address` and will not be visible on the admin dashboard.
As soon as I add a new line item, the order becomes visible.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/66c61e45-6246-40e8-b2a3-c80b2dc8e8ee)

Case 2: As a user (or a guest) who didn't set a billing address
---

When the user accesses a shop and adds some line items, the order will start with `state=cart` and will stay invisible until the user submits the first form on the split checkout.
This is happening because, on the first step the billing address will be set.



One potential solution is to ignore the billing address, I'll draft a PR and see what will be the impact on the tests.
