### ISSUE TITLE
Missing products on Products screen (Safari)

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#11186]
## Description

UK users have reported issues with the Products page where not all of their products are appearing. This not only prevents users from editing said products e.g. updating prices, but is worrying users as it appears they've lost their product data. May be related to #11091 ?

## Expected Behavior

All products owned/managed by the user should display in the Products screen

## Actual Behaviour

Only some products are displayed, and user sees 'missing %[number] value' text next to the 'per page' selector (see user screenshot below). I have not been able to replicate this myself and will update ticket with Safari versions when the user confirms. There are a number of bugsnag entries for the admin/products page including [this one](https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/64a4829a691420000822ca59?filters[event.since]=2023-07-08T23%3A00%3A00.000Z&filters[event.before]=2023-07-09T22%3A06%3A00.000Z&filters[search]=admin%2Fproducts&event_id=64aae2cb00beda97d7200000) which may be connected?

## Steps to Reproduce

Currently unable to reproduce

## Animated Gif/Screenshot

User supplied screenshot:
![image0 (2)](https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/f5c51a0d-705a-45ce-93da-4669f550a932)

## Workaround

No workaround for users wishing to edit a product currently. I've asked users affected to try a different browser/apply a producer filter but haven't heard back yet.

## Your Environment

* Version used: UK Prod
* Browser name and version: Safari
* Operating System and version (desktop or mobile):  MacBook Pro, mid 2012, running OS X El Capitan, version 10.11.6

**Comment by BethanOFN** [comment]
User reported that updating to latest version of Safari fixed the issue for them

**Comment by NiftyGaloot** [comment]
Here's another report https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1689926836934319

**Comment by amidaOFN** [comment]
Have had AU user reports of this problem in Safari and Firefox on iPad and iPhone, but no issue on Chrome.

US also reported a user id their os as  'iPhone S operating iOS 15.7.7. my iPad is old — an Air (1st gen) and operates iOS 12.somethingorother'

**Comment by NiftyGaloot** [comment]
I duplicated the problem a little bit ago with Safari 13.1.2. 
Opened the develop window. I don't know if this will help, but here are the results:

[Error] Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied. (products, line 1)
[Debug] [bugsnag] – "Loaded!" (bugsnag.min.js, line 1)
[Error] Refused to connect to wss://openfoodnetwork.net/cable because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
[Error] SecurityError: The operation is insecure.
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:255531)
	value (admin-e31ca5b7fa88f205290d.js:2:255531)
	value
	value (admin-e31ca5b7fa88f205290d.js:2:260221)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1136242)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	i (admin-e31ca5b7fa88f205290d.js:2:1135965)
	forEach
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1135876)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1136799)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:913)
	Global Code (admin-e31ca5b7fa88f205290d.js:2:923)
[Error] ReferenceError: Can't find variable: moment
	Global Code (products:64)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:52501)
	completeTask (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:52131)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:37711)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:59855)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:59855)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:59855)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied. (products, line 1)
[Debug] [bugsnag] – "Loaded!" (bugsnag.min.js, line 1)
[Error] Refused to connect to wss://openfoodnetwork.net/cable because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.
[Error] SecurityError: The operation is insecure.
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:255531)
	value (admin-e31ca5b7fa88f205290d.js:2:255531)
	value
	value (admin-e31ca5b7fa88f205290d.js:2:260221)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1136242)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	i (admin-e31ca5b7fa88f205290d.js:2:1135965)
	forEach
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1135876)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:1136799)
	n (admin-e31ca5b7fa88f205290d.js:2:115)
	(anonymous function) (admin-e31ca5b7fa88f205290d.js:2:913)
	Global Code (admin-e31ca5b7fa88f205290d.js:2:923)
[Error] ReferenceError: Can't find variable: moment
	Global Code (products:64)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:66602)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	trigger (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:7808)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:7876)
	each (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:366)
	each (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:138)
	trigger (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:7875)
	triggerChange (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:80684)
	onSelect (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:81847)
	selectHighlighted (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:81309)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:80365)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:80268)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:59855)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:59855)
	dispatch (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4738)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:4550)
	(anonymous function) (bugsnag.min.js:1:31915)
[Error] undefined is not an object (evaluating 'scope.$eval(attrs.ofnDisplayAs).unit_value_with_description')
https://openfoodnetwork.net/assets/admin/all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:90494
	(anonymous function) (bugsnag.min.js:1:31340)
	(anonymous function) (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:42746)
	$digest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50058)
	$apply (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:50400)
	done (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44243)
	completeRequest (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44500)
	requestLoaded (all-52c261f76bbf3c89b71277a70701ce80be531c6faf1e85dd06cf2bbea6abdb07.js:44405)

**Comment by dacook** [comment]
I can replicate a problem on my Mac with **Safari 15.6.1**. For me _none_ of the products appear at all, for _any_ distributor. 
Pictured here with Chrome on left, Safari on right:
![Screen Shot 2023-07-28 at 9 58 50 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/ca94bc59-17ee-45ee-b0f5-fbcf20b43265)

I'm afraid to admit this because I may become responsible for fixing it 😬

**Comment by dacook** [comment]
Good news, it looks as though this will be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/11294 !

![Screen Shot 2023-07-28 at 10 32 22 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/518577af-cc6e-4348-8394-60a2135f6021)
