### ISSUE TITLE
MacOS/Safari issues

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11194]
An epic grouping recent MacOS / Safari issues.

**Comment by NiftyGaloot** [comment]
Here's another report of iOS issues: 

It seems like a lot of the new software updates are not compatible with iOS browsers (either that or the iOS browsers are not compatible with the software) are you experiencing that?

ie: I can no longer process stripe refunds on my phone, the products page kinda half works on my phone now and the orders page barely works at all. All of these pages used to work just fine on my phone a few months ago… 

any leads? Im struggling a little because i rely on being able to do a lot of work on my phone or tablet due to being off-grid and not having reliable computer/internet access. hoping…

**Comment by NiftyGaloot** [comment]
Heard from a hub manager. She says "Im on an iPhone S operating iOS 15.7.7. my iPad is old — an Air (1st gen) and operates iOS 12.somethingorother. Both devices demonstrate the same issues, and its independent of browser. Just a few months ago both devices navigated the OFN software just fine, so I suspect it is OFN updates causing the issues."

**Comment by RachL** [comment]
Only 2 issues left. I vote for not keeping this epic 😁 Closing
