### ISSUE TITLE
Update 'All Products' report to include Stock

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#11207]
## Description

In the All Products report there is a column Amount which is empty. Let's change this to include the stock levels. Please rename the column to 'Quantity in stock'.
Note we will ignore inventory on this report. The stock levels will be the producer stock level recorded in the DB. I believe this is in spree_stock_items.count_on_hand... but don't quote me on that and make sure you check for yourself :)

There is already a warning for the user that the inventory will be ignored on this report... so that's handy ;)

## Acceptance Criteria & Tests

1. Amount column is changed to 'Quantity in Stock'
2. This column should display values for each product that reflect the producer stock levels. Any inventory stock levels should be ignored.
3. Filtering should work as expected, for Distributor, Supplier and Order Cycle
4. Unit tests added 
5. Translations for this field
6.

**Comment by jibees** [comment]
`Inventory (on hand)` report also contains `AMOUNT`. Should I remove/change this column on that report also?

**Comment by jibees** [comment]
<img width="1377" alt="Capture d’écran 2023-07-18 à 16 02 16" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/b631fd08-0181-4170-82a6-3e5c62a9cc72">


Sorry, that's probably a stupid question, but what's the difference between the `On Hand` column and what should be the `Quantity in Stock` column? (I wanted to code but I then realized it was somewhere already done this way)

**Comment by lin-d-hop** [comment]
OOh FFS. In that case we are all noobs :rofl: This must have been added in the reports upgrade and not internalised into my brain at least.

Okay... so instead for this papercut can we:

1) Unhide these columns by default. I think no one will complain, and at least they are visible.
2) ~Strikethrough~ the name of the 'Inventory (on hand)' report on the /reports screen. Let's not remove it, but deprecate it like this and see if anyone complains. The link should still be clickable.

**Comment by jibees** [comment]
This comes from: https://github.com/openfoodfoundation/openfoodnetwork/pull/10041 ! and those two columns have been hidden by default. I will change this, thanks @lin-d-hop !

**Comment by kirstenalarsen** [comment]
I'm afraid I don't know the answer to your question above @jibees , but just wanted to comment on ignoring the Inventory (On Hand) report. Despite the name, this report actually has nothing to do with 'Inventory' as later introduced into OFN. It is simply the same report but rather than giving every product an Enterprise has, it is only the products that have stock available. 

These reports were originally created to support sending csv order forms for wholesale people who wouldn't order online (which is why the Amount column was blank - that was where they put their required amount). I am fine with the change being made, is good and solves a need. But I do think it is worth just doing both or it will add confusion that one behaves differently from the other. Another papercut would be to delete the inventory report and just add a selector to the report generator for 'all products' or 'products with stock available'
