### ISSUE TITLE
[DFC] Can't create products for instances requiring tax categories on products

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11212]
## Description

Follow-up from #11145.

We need to be able to create products for instances which require `tax_category` on products; this currently works if this requirement is disabled.

## Expected Behavior

Creating a product via DFC should be possible for instances which require a tax category over products.

## Actual Behaviour

Creating a product via DFC currently fails if the instance requires a tax category.

## Steps to Reproduce

As a super admin
1. Visit /admin/tax_settings/edit
2. Enable `products require tax category` option and click Update.
3. Follow the steps on "What to test" in PR #11145
4. See that you get an error 500:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/64b012c9492eca0007c8ff84?event_id=64b012c900bed74715b20000&i=sk&m=nw

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

I think we just need to add a tax category when creating the product:
https://github.com/openfoodfoundation/openfoodnetwork/blob/774bb7a6072d488056ed3886a70f419f2c3ad56e/engines/dfc_provider/app/services/supplied_product_builder.rb#L19-L29

**Comment by mkllnk** [comment]
I looked into this and found that the default tax category is associated automatically without any action required by the DFC API. I'm wondering if you activated the configuration without flagging a tax category as default? I would see this case as invalid instance configuration. I don't think that it would be valid to select a random tax category just because one is required.
