### ISSUE TITLE
Ability to BCC instance for all 'Welcome to OFN' emails

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1129]
This feature would alert instances when a new users has signed up and is setting up an enterprise. Currently a SuperAdmin needs to check the Users and Enterprise report periodically to know who has signed up.

When:
- When an enterprise user creates their first profile at /register
  Content of email:
  I think the more info provided the better
- Enterprise name
- Enterpsie address
- Owner's email address
- Description
- Producer or non/producer?

**Comment by myriamboure** [comment]
That would be great! We had done that locally in france but I was receiving ALL the emails that a hub manager was receiving, like all the order confirmations, etc. So we stopped it, but would be great to receive a notification only when a new hub is created, so that we can support the first step and say hello :-)

**Comment by lin-d-hop** [comment]
I get around this by having a notify.ofnuk@gmail account that all notifications are sent to then filtering out the transactional mail i don't want to read. The result is that in my inbox I have important emails, such as "<enterprise> is now on Open Food Network UK".

**Comment by sstead** [comment]
That's a great solution, thanks Lin!

**Comment by lin-d-hop** [comment]
Workaround is fine for this. #gitcull
