### ISSUE TITLE
[invoices] Don't generate a new invoice if adjustments label changes

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11338]
## Description

Editing an adjustment label generates a new invoice when it shouldn't: last invoice should just be updated see https://docs.google.com/spreadsheets/d/1hOM6UL4mWeRCFLcDQ3fTkbhbUQ2WvIUCCA1IerDBtUA/edit#gid=831959393 

## Steps to Reproduce

1. Activate invoice toggle
2. Go to an order with manual adjustment and generate an invoice
3. Edit the label of that manual adjustment
4. See the last invoice is not updated and the new invoice button is available

## Workaround
Generate a new invoice

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by abdellani** [comment]
Hi @RachL 

Can you please check the screenshot? (it that behavior wrong?)
(please ignore the sorting of the invoices, because this is solved on [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/11116)

https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/48dd875f-f936-4bde-bff3-520bd839234f

Note:
Adjustments on the spreadsheet referees to the data model stored in the database. It's different from the adjustment that we can see on the admin dashboard.
Adjustments on a spreadsheet can refer to different entities: taxes, line items, enterprise fees, tax on enterprise fees, shipping, cost of payment etc....

**Comment by RachL** [comment]
@abdellani ah I understand now, to update we need to press that button as well - I didn't know! Then maybe we need to rename the button in "create or update invoice"?

**Comment by abdellani** [comment]
> @abdellani ah I understand now, to update we need to press that button as well - I didn't know! Then maybe we need to rename the button in "create or update invoice"?

Yes, this is a better description of the role of the button.
