### ISSUE TITLE
New producer hub is offered "30 day free trial"

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1137]
When setting up a producer hub with Locavore I noticed that the final set up screen had a banner at the bottom saying "30 day free trial" 
Please can we change this to "6 month free trial"
Sorry I didn't get a screenshot as we were doing this on a hangout screenshare from his Mac

**Comment by lin-d-hop** [comment]
@NickWeir63, can you clarify which screen you are talking abotu here?

**Comment by NickWeir63** [comment]
I have just tried to recreate this issue by setting up a new account with the email address of delete@delete.com but could not find the screen that I saw when Mags and I were seeing the screenshare that Reuben showed us while he was setting up Locavore.  @MagsHall did you happen to notice this "6 month free trail" message when we were working with Reuben?
If not let's close this issue as we cant replicate it.

**Comment by MagsHall** [comment]
I think this pops up briefly when a new enterprise has gone through the set-up wizard, clicks on the link they have been emailed to confirm their email address, and enters Spree for the first time. I haven't been able to replicate it either though, as all my email addresses now have some kind of enterprise linked to them, so even if I go through the set-up wizard when I confirm my email address it takes me through to my existing Spree set up. And a dummy email won't work because you can't click on it to confirm the email address.

**Comment by lin-d-hop** [comment]
I also can't replicate this. I tried to set up a new enterprise with a new email account and did not see any mention of 30 day free trial. Also can't find any trace of it being hard coded.

Closing, if anyone notices again please take a screenshot so we can try and track down the issue.

**Comment by oeoeaio** [comment]
@lin-d-hop I may have just fixed this issue in da55eb6d...so perhaps that is why it is proving elusive.
