### ISSUE TITLE
[BUU] Make table and search section adaptive

### ISSUE THREAD

**Issue by mariocarabotta** [openfoodfoundation/openfoodnetwork#11403]
https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1691748836422049

**Comment by dacook** [comment]
I'm not sure if this has been improved for the French translation, or if it could be a problem for other languages.

It's also potentially a problem for long producer names. But I think it's a reasonable width:

![Screenshot 2024-06-12 at 11 08 12 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/19cb72ce-a72d-41e9-9a93-d06dbca36946)

It might be possible to make the dropdown width adapt to the content, but we probably don't want to do that (because of long producer names).
