### ISSUE TITLE
[Reports] Snail (error 500) if date range end is before date range start in Enterprise Fee Summary report (Bugsnag)

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11424]
## Description

If date range end is set before date range start in Enterprise Fee Summary report there is an error 500 (snail).

## Expected Behavior

There should be no snail.
The best behaviour would be to automatically swap start and end in this case (https://github.com/openfoodfoundation/wishlist/issues/460).

## Actual Behaviour

Error 500.

## Steps to Reproduce

1. Go to Enterprise Fees Summary report.
2. Select a date range with end date before start date.
3. Click 'Go' to generate the report.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/291e030a-ab58-45d8-87e3-0b0acc985705

## Workaround

Use end date after start date.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @drummer83 , I would like to help with this one, but navigating through `http://localhost:3000/admin/reports/enterprise_fee_summary/` leads to this:
![BOGUS](https://github.com/openfoodfoundation/openfoodnetwork/assets/5203082/61e3ce06-4def-4529-a553-b17645d835e6)

So, in table `from spree_payment_methods`, there are some lines that have `Spree::Gateway::Bogus` as a type, but there is no `Spree::Gateway::Bogus`  object in DB.
That should correspond to a app/models/spree/gateway/bogus.rb file. I have files for stripe & paypal (Spree::Gateway::PayPalExpress & Spree::Gateway::StripeSCA objects). 

I guess this comes from the test payments I have done, but I wonder how these non existing objects wound up in my local DB ... Have you got an idea what this issue is ?
(Also Enterprise Fees With Tax Report By Order seems to lead to a never ending spinning circle ...)

**Comment by drummer83** [comment]
Hmm, I'm not familiar with this. Does this help? https://github.com/openfoodfoundation/openfoodnetwork/pull/11701

If you're still stuck, you are welcome to ask in #dev channel on our Slack.

**Comment by cyrillefr** [comment]
Yes, thank you, I think it is the right answer.

**Comment by cyrillefr** [comment]
Hello @drummer83, 

May I work on this one ?

If so, I have watched a bit and I think I may have a solution.
We can use the range property of the `flatpickr` component to ensure to get two consecutive dates.
Furthermore, this feature is already used in the admin/orders bit of the admin and so we would not introduce some new way of doing things.

**Comment by sigmundpetersen** [comment]
Yes sure @cyrillefr go ahead 👍

**Comment by sigmundpetersen** [comment]
Hey @cyrillefr 👋 
So you still want to work on this one or should we rather unassign?
