### ISSUE TITLE
Profile badges should be removed if E2Es have been removed

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1157]
![image](https://cloud.githubusercontent.com/assets/10843056/18575720/424f8a98-7c1e-11e6-882b-83bf3fb4e07e.png)

**Comment by stveep** [comment]
This could be a good issue for a new dev to get started on - can we add a bit more information? This is affecting the /shops page. An E2E refers to an enterprise-to-enterprise relationship, where one Enterprise (a hub) sells products from another Enterprise (a producer). I believe that the little category badges are the Taxons associated with the hub Enterprise. So maybe what's needed is a callback to update these when an EnterpriseRelationship is destroyed?

**Comment by levent** [comment]
@stveep I believe this is being caused by a lack of cache invalidation. When I set the development cache_store to null store this problem stops happening.

I'm still getting my head around the codebase but the serializer relies on ```Enterprise#cache_key``` which by default in rails is a combination of class name, id and updated_at.

We could touch the Enterprise object when an Exchange is modified?

I'll attach an example PR.

**Comment by RohanM** [comment]
Hi @levent, this is really good. I've incorporated this change into a broader set of cache invalidation work, which was in turn needed to make some other changes performant. The changes are in the later commits on this branch: https://github.com/openfoodfoundation/openfoodnetwork/compare/shop-property-filters-take-2?expand=1

**Comment by levent** [comment]
Hi @RohanM, thanks. I will close my PR then https://github.com/openfoodfoundation/openfoodnetwork/pull/1198

**Comment by RohanM** [comment]
I ended up writing some slightly higher-level specs for the functionality, so that's all good. Thanks again!

**Comment by RachL** [comment]
2022 update: this is still an issue!

**Comment by macanudo527** [comment]
I'm trying to replicate this on my setup, but I'm having problems getting products to show up on a hub's profile page. I created a producer, gave permissions for the hub to edit it, and added products to the producer, but they still aren't showing up. Is there a page somewhere that goes over the workflow for this? I think I am missing a step

**Comment by RachL** [comment]
Hi @macanudo527 have you added them to an order cycle? Check https://guide.openfoodnetwork.org/basic-features/shopfront/order-cycle/order-cycles-for-hubs if you haven't

**Comment by macanudo527** [comment]
OK, I was able to add it to the OC and it showed up, but can't replicate this bug.

I added a producer to a hub and an OC for that hub. The products showed up on the /shop page. And the filter by button shows.
![Screenshot from 2023-02-01 11-11-18](https://user-images.githubusercontent.com/17987707/215929097-46491b11-b7f8-4ec4-853b-c09c1e53c39f.png)

I remove the E2E (under enterprises-> permissions). The filterby still exists.

I remove the OC with the product and the filterby disappears.
![Screenshot from 2023-02-01 11-17-49](https://user-images.githubusercontent.com/17987707/215929319-4b12d7be-07de-4988-a4a2-d687534c6705.png)

Is there something I'm missing? It seems like the software has changed significantly since the time this was first reported. Is this the right way to replicate the bug? @RachL were you able to replicate it?

**Comment by RachL** [comment]
@macanudo527 Yes I'm able to replicate. I think you are not looking at the correct place. You are looking inside a particular shop, while the bug is within the "/shops" page ie the list of shops.

when you are on the list of chop you can select a line and there you have some information showing up. There the badge is not removed:

![image](https://user-images.githubusercontent.com/6525576/216078083-92177778-33fb-4859-86ef-d51ed7500a6d.png)

**Comment by macanudo527** [comment]
I'm still not able to replicate it. I gave permissions to a hub for a producer (created an E2E). Created an OC. The 'shop for' tag appeared. I deleted the E2E. The 'shop for' tag is still there as well as the tag for the producer. I deleted the producer from the OC and both the 'shop for' and 'producer' tags disappeared.

I then recreated the E2E, gave permissions again. I added the producer to an OC. The producer and shop for reappear. I expire the OC, by giving it an earlier close date and the producer and shop for tags disappear.

Am I misunderstanding the bug? Sorry to keep asking, but what exact steps did you take to replicate this? I can not replicate it on a fresh setup.

**Comment by RachL** [comment]
hello @macanudo527 your comment made me realized you have found a second underlying bug: if you delete the permissions, the producer should be automatically removed from the OC, without needing to remove manually the producer from the OC. 

Indeed, the shop shouldn't be able to sell products from a producer that has removed their permissions.

Would you be willing to work on fixing this? You can link the PR with this issue as I think it will fix both problems.

**Comment by macanudo527** [comment]
I'll give it a try. I'm pretty sure I have my head wrapped around the processes. I'll put something together. I'll probably need some feedback on it.

**Comment by macanudo527** [comment]
I submitted a PR, but it doesn't solve the problem. I can't find what is wrong. The code destroys related `exchanges` and `exchange_variants`, but then creates another phantom `exchange_variant` connected to another exchange, but still shows up in the variant count for the OC.

It also touches Enterprise twice. I'm seeking feedback since I've already spent a good 2-3 hours and can't nail down what is causing this. Thanks for taking the time to read through it. I'm sure there is something obvious I'm missing. I haven't worked with Rails for about 6 months.

**Comment by macanudo527** [comment]
@RachL This is probably obvious, but I'm just double-checking. If permissions are revoked or the ER is deleted, should the producer removed from just current and future OCs (ones that are still open). Should they remain for past OCs?

**Comment by RachL** [comment]
@macanudo527 in terms of user needs, removing from current and future ones is enough. On the tech side what's the easiest? 

There is one case (maybe) from user point-of-vue where it can be tricky to remove them from past ones as well: 

- let's say permissions are revoke for a supplier and we remove them for all OC
- but then the permission is granted again. 

In that case, I guess we will enable to allow adding the supplier back on current or future OC. We won't assign them to any OC automatically, as there are no more trace of their past OC involvement. 

In that case, if the supplier goes to check previous orders they had for this hub in the reports menu, they won't be able to use the OC filter. Only the dates. But if that's the case, it's perhaps a minor problem and we can live with it. So if it's easier on the tech side to remove them everywhere, let's go for that.
