### ISSUE TITLE
SO - Opt-in option for enterprises to require customers to login to complete an order

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1160]
Enterprises can choose to force their customers to log in (ie. not use guest checkout) to place orders with them. This feature is needed for standing orders, for the use case where a user that has a standing order comes into their shop and goes through the checkout process, logging in after they've added items to their cart. If they have a standing order we need to be able to communicate this to them and give them the option of seeing these standing items in their cart/order (this communication is being built in #1084).

Ideally, #1159 would be done first. But since this is optional, a shop can choose to do this or not and it does not need to be foolproof.

- [x] Create the setting in the enterprise to 'allow guest orders'
- [x] Hide option to checkout as guest if it's not active

**Comment by sstead** [comment]
Could we better stress to Users that if they're using SO that they should also require login? Perhaps when they first click to 'Enable Standing Orders' (AND you have guest checkout allowed) a popup or exclamation should appear saying 'we suggest you also require login before your customers can checkout'.
![image](https://cloud.githubusercontent.com/assets/10843056/21377270/57c1e1e6-c791-11e6-9656-32456cca5b66.png)
