### ISSUE TITLE
Show pop-in alert when navigating away from /summary page without placing order

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11600]
## Description
**- As a:** guest or loggedin shopper
**- On page:** `/checkout/summary`
**- I want to be able to do:** 

Hubs are reporting that users believe they've placed an order, but have instead navigated away from the checkout/summary page without clicking 'complete order'. 

We want to add a modal soft warning when users attempt to navigate away from this page without clicking the complete order button (i.e. click browser back button/close browser/reloading/navigate away from page) 

Creating a designed modal was desired, but it can't cover all situations, so we will use the browser default popup:
![Screen Shot 2023-12-05 at 11 52 28 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/aa545aba-0b36-4e60-9773-94c069e4efac)
(See [BeforeUnloadEvent ](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event))

## Acceptance Criteria & Tests

1. Leave summary page by closing or reloading or clicking a button
2. Check the modal appears and the button works
3. Check going backwards in the checkout process (step 1 or 2 or carf page) does not trigger the message

do it with a guest user and loggedin user

Add automated specs in `/spec/system/`

**Comment by FionaDL** [comment]
Hello! Could I pick this up?

**Comment by sigmundpetersen** [comment]
Hi @FionaDL sure, thank you! 🙂 Don't hesitate to ask if you need any help!

**Comment by FionaDL** [comment]
Hey @sigmundpetersen my colleague and I tried to work on this together this week, but we don't think we will be able to pull it off :( Would you mind un-assigning us?

**Comment by sigmundpetersen** [comment]
No worries @FionaDL thank you for the feedback.
Please reach out if you find another issue you would like to work on instead.

**Comment by AkinAgbejoye** [comment]
Hi. I would like to pick this issue.

**Comment by sigmundpetersen** [comment]
Hi @AkinAgbejoye sure, thank you! 🙂 Don't hesitate to ask if you need any help!

**Comment by RachL** [comment]
hello @AkinAgbejoye I hope you are doing well. I'm just checking in: are you still working or planning to work on this?

**Comment by AkinAgbejoye** [comment]
I am really sorry, I have serious difficulty in setting up the project on
my windows and even linux, you can assign the task to another person.
I will revisit the whole stuff soon. Thanks and kind regards.

**Comment by dacook** [comment]
@jameleu are you able to add any details here or confirm if I'm right?

**Comment by jameleu** [comment]
@dacook Yes, I agree with you. 
1., 4. I agree.
2.I think using an event listener with "beforeunload" would work, but I think refreshing should not have a modal pop up since most people refreshing would be refreshing on accident or due to wanting to restart processes on the webpage, so they probably do not intend to leave the checkout yet. I think only when they do intend to leave the checkout should we tell them that they should not leave yet if they still plan to buy their cart.
3. I agree since tracking closing the browser is not possible since browsers, for security reasons, don't provide reliable way to handle this event to prevent misuse.

I think implementing the basic browser popup is the best solution so far since a lot of other shopping websites I use simply utilize that and it gets my attention and allows me to reconsider my actions sufficiently.

**Comment by dacook** [comment]
Thanks jameleu. @RachL, would you support changing this issue to implement the basic browser popup?

**Comment by sigmundpetersen** [comment]
Hi @jameleu 👋 
Did you want to continue with this, implementing the basic browser popup?

**Comment by dacook** [comment]
@RachL There are two possible tasks we can do:
1. Attempt the designed modal. We can only cover some cases with this (as per [my comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/11600#issuecomment-1839820800))
2. Add a browser modal. This can cover all cases, but doesn't look nice and has a very general message.

Perhaps we can create a separate issue for each, or just choose one and update this issue. I'll let you decide.

**Comment by tschumilas** [comment]
would both of the above approaches (designed modal or browser modal)  result in the message being blocked if the shopper has a browser pop-up blocker enabled?   I'm asking because I think this is the problem.  Today,  if a shopper is placing an order,  and an item goes out of stock,   a error appears that says "An item in your cart has become unailable, please update the selected quantities".  But shoppers are either not understanding,  or seeing that message.  So they cannot checkout.    We can translate the message and word it more strongly like:  'You must remove out of stock items from your cart before you can checkout'.  But I"m just not clear -  will they even see that message if their browser is blocking popups?  (sorry I don't understand the difference between a popup and a modal....)

**Comment by dacook** [comment]
In general, popup blockers will block something that pops up without a user interaction. So I think either of the suggestions on this issue are fine. But the out of stock popup you mentioned could potentially be blocked.

I couldn't say conclusively, but I had a look at the description of Poper Blocker, a popular browser extension, and it sounds like it would only stop that popup if you had intentionally configured it to.

I would dare say that it's much more likely that people ignore, or don't see the stock popup. That information should appear on the page the when the checkout fails, if it's not, I think we should address that in a new issue.

**Comment by dacook** [comment]
I've updated the description to use the basic browser popup instead of the designed popup.

**Comment by wandji20** [comment]
I would like to try this one
