### ISSUE TITLE
Order date and time format on edit order page isn't localized

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11606]
## Description

The order date and time on the edit order page in the back office is always shown in the English date and time format. It should be shown in the locale format though.

## Expected Behavior

The date format should depend on the selected language in OFN or on the browser language setting.
The time format should depend on the selected language in OFN or on the browser language setting, e.g. in Europe the 24 h format is used instead of a.m. and p.m.

## Actual Behaviour

The date format is always in English.

## Steps to Reproduce

1. Place an order.
2. As admin user go to admin/orders page.
3. Click on the edit symbol next to the order to edit it.
4. Look at the date format displayed in the right most column of the page.

## Workaround

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/df225813-8980-49d7-b565-b42a5af796ac)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.4.13
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
Hey @drummer83  - I'd like to work on this issue. Can I please get assigned to it? Thanks :)

**Comment by sigmundpetersen** [comment]
Hi @chahmedejaz sure, thank you! 🙂 I'll assign you. Don't hesitate to ask if you need any help!

**Comment by chahmedejaz** [comment]
Thank you @sigmundpetersen 😄 . Here are my findings on this issue:
- I spiked a bit and apparently this should be the case through out the application.
- I believe we should change the issue's title to something generic like "Date and Time format isn't localized through out application" or something more suitable and should fix this issue through out the application where we are using dates and times.
- If we just want it to be fixed only on the order's page, then no issue. Just wanted to confirm it beforehand :)

**Comment by sigmundpetersen** [comment]
Great! Let's get some input from @openfoodfoundation/developers and @openfoodfoundation/train-drivers-product-owners 👍

**Comment by RachL** [comment]
Ufff that's a nice finding thanks @chahmedejaz !

I guess if it's easier to fix it all at once, we can go for it. Otherwise we can go step by step and create issues for all cases?

**Comment by chahmedejaz** [comment]
> Ufff that's a nice finding thanks @chahmedejaz !
> 
> I guess if it's easier to fix it all at once, we can go for it. Otherwise we can go step by step and create issues for all cases?

I'll create a list of places and will see how many places we can fix by just fixing the order's page. Will update here after a bit more working. Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
Hey @sigmundpetersen, @RachL - 
- I spiked on pages whose date-time can be fixed by the reported issue and found these links, they all display the _Orders Information_ and hence the date as well:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/67ca3c41-19e4-4b81-99d7-604fbfb4f960)
- While researching for the date/time translations, I found ambiguous references for the time formats i.e. all references say a particular country supports 12 or 24hrs time format. 
- It would be great if I could get some guidance on localized time formatting. As reported in the issue, European countries have a 24-hour time format.
- As far as the date translation is concerned, I'm currently focusing on gathering their data and adding them to the system's locales.
- They will be further used in future for the all the date/time localization throughout the system. Following the system suported language codes: 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/1e84818a-bbca-4a45-bca5-ee4378a22936)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/6bc59d7d-cb89-4d72-95c4-359e1838fcfb)

Thanks.

**Comment by chahmedejaz** [comment]
**Update:**
- I've spiked for other affected pages and found that for now, the Orders page is using the long date format.
- Moreover, Not all languages are affected by this issue. 
- Only those languages are affected, which have country-specific variants e.g. Esponel for the US, German for Germany, German for Switzerland, etc.
- I'm using this site for the data/time locale references for the affected languages:
https://lh.2xlibre.net/locales/

**Comment by chahmedejaz** [comment]
**Update:**

- The date translations for the affected locales/languages as per [this](https://github.com/openfoodfoundation/openfoodnetwork/issues/11606#issuecomment-1752183553) have been updated
- Please review the following screenshot and let me know what you think about it:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/6d147465-7273-4e80-bd8b-d3cc6af93c79)
- Only the time formatting remains, here are my findings on this:
  - As of now, we are only translating dates as per the selected language except for the affected ones as explained [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/11606#issuecomment-1752183553) (_this will be fixed in this issue_). 
  - However, we are not translating time/time-format for any country or language. We are always displaying time in the `%l:%M %p` format e.g. 1:30 PM, 12:00AM etc
  - I spiked on the time formatting for the locales, every reference I could find showed that the locale supports both 12 or 24h formatting
  - It would be great if we have a set of requirements or guide/reference to work on time formatting issue.

Please let me know if you have any follow-up questions. Thanks.

CC: @sigmundpetersen, @RachL, @drummer83

**Comment by drummer83** [comment]
Hi @chahmedejaz,
Thank you for continuing your work on this. I'm not quite sure that I understood everything - I'm not a developer, just a tester. 
For adding translations we are using Transifex. Please have a look at[ this wiki page](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29) for details. It's usually enough to add strings to the en.yml file and the translators will then translate them into their own languages.
However, I think not only the translation but also the format of the date needs 'translation'. Your screenshot above shows `Oktober 09, 2023`. The correct German format would be `9. Oktober 2023` or `09.10.2023`. 
Is this possible with your approach? Or would we need a place to define the format for each instance in a setting?

Maybe a @openfoodfoundation/core-devs could comment how to solve this in a good way.

Regarding the time it's usually enough to specify if you want to use 12 h (with pm/am) or 24 h display. Again a core developer could maybe propose where this should be set.

Thanks again! 💪

**Comment by chahmedejaz** [comment]
> Regarding the time it's usually enough to specify if you want to use 12 h (with pm/am) or 24 h display. Again a core developer could maybe propose where this should be set.

Hi @drummer83 - 
- Yes, I read about Transfix. However, I found many locale files in the project which are being used for translations.
- That's why I thought adding the date translations there would be best. 
- Yes, I can add date and time formatting for all language with this approach as well. Will be adding those in the up-coming commits.
- Regarding the **setting** options for Date/Time formatting, I believe that would be a new feature issue.
- For this issue, we can just add date/time translations and apply the locale's conventional formatting e.g.
  - German date is 09.10.2023 we can display date like this
  - US English date format we can display it like 10/09/2023

**Comment by drummer83** [comment]
Sounds good to me. 👍🏻

I still think you should only edit the en.yml file. All the other ones are created automatically through Transifex.

**Comment by chahmedejaz** [comment]
> Sounds good to me. 👍🏻
> 
> I still think you should only edit the en.yml file. All the other ones are created automatically through Transifex.

- Oh, then I will use `en.yml` for the date translations. Will remove my changes regarding translations from other locales as well.
- However, for the date/time formatting (_10/09/2023, 09.10.2023_), I must override the default date/time formatting in the locale files. Otherwise, English formatting will be applied. 
- This is a constraint by the Rails framework itself.

**Comment by drummer83** [comment]
@mkllnk @dacook Is this going to work?

**Comment by dacook** [comment]
Hi Konrad and Ahmed, thanks for working through this issue. 

I agree with Konrad, it's better to just change the default locale file (en.yml), then update all others through Transifex. However I had a look at the current branch, this looks ok to me and I think it's fine to do it this way this time. Only because the translation of day/month names is unambiguous, so I don't think it needs reviewing by native speakers. 

Regarding the the date/time _format_, we need to set it with a format string (eg time is `%l:%M %p`). It sounds like two options are considered:
1. Add a new system config setting, where the instance manager can enter the format string/s
2. Add a new locale entry, where the translator(s) would be able to set it via Transifex.

I was going to suggest `#1` makes more sense, but now I see that date and time formatting is already handled by Rails I18n, so it seems most practical just to use that. We shouldn't need to update it often.
I can see that we currently use the default date format, and the time format is hard coded.

So, Ahmed would you agree on these next steps?
* **Date format:** add the `date.formats.long` key to `en.yml`. Then this can be customised in Transifex by local translators.
* **Time format:** add the `time.formats.short` key to `en.yml`. _Also_ update `base_helper` to use this format. Then it customised also.

It's possible to configure other date and time formats (by default there's also `date.default`, `date.short`), but I don't know if our application uses those. They would make more sense in tabular reports, but I'd consider reports out of scope for now.

**Comment by dacook** [comment]
I also saw that the API uses some hardcoded time formats too. If we wanted to consider changing those, it should be a separate issue.

**Comment by chahmedejaz** [comment]
> Hi Konrad and Ahmed, thanks for working through this issue.

Hey @dacook - 

- I agree moving forward with option #2.
- Will be adding the English date/time formats in `en.yml` and it can be translated by the Transifex by locals afterwards.
- I believe updating the `base_helper` would be fine. For `_table_row`, we should have a separate issue in which we can do spike on global affects of the changes and then update it accordingly. What do you say?

CC: @sigmundpetersen

**Comment by dacook** [comment]
> * For `_table_row`, we should have a separate issue in which we can do spike on global affects of the changes and then update it accordingly. What do you say?

Sounds good 👍

**Comment by chahmedejaz** [comment]
Hey @dacook - Sorry, while working on the time format thing, I realized:
- `short` is one of rails default time formats which return the time in `%d %b %H:%M` format e.g. `9 Oct 13:00`.
- Currently we have `base_helper` function like this:
- https://github.com/openfoodfoundation/openfoodnetwork/blob/0bd4fe315cb995207d4981f5b12516913372c957/app/helpers/spree/base_helper.rb#L38-L41
- I believe it's better to just replace this as follows:
```ruby
 def pretty_time(time)
   I18n.l(time, format: :long)
 end 
```
- I've added `time.formats.long: "%B %d, %Y%l:%M %p"` in `en.yml`. 
  - It can be customized to add each locale's date-time formatting in Transifex
  - This approach also saves us the array operation

Please let me know what you think about [these changes](https://github.com/chahmedejaz/openfoodnetwork/commit/378113a99d2e110ab5b35d3144b22e39e4333f13). Thanks.

One thing before submitting the PR, I know you have reviewed my branch, but just to be sure :sweat_smile:. Is it okay to add month or day names translations in their respective locales directly like these?:
- https://github.com/chahmedejaz/openfoodnetwork/commit/be949bee2a337f7f75fba06def7b4641a0a9d848
- https://github.com/chahmedejaz/openfoodnetwork/commit/6efd532d10691ac638d698acae902cab3b6e2e3e

Thanks again!  :)

**Comment by dacook** [comment]
HI @chahmedejaz , thanks for your investigation and explaining it here. This all looks right to me 👍 
Thanks for going ahead with the PR; I'll comment on there in more detail.
