### ISSUE TITLE
SO - Opt-in option for enterprises to allow their customers to make changes to their current order

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1161]
Allow enterprises to choose whether they will let their customers change their current order (ie. remove things that they have committed and/or paid to purchase) up to the point where the order cycle closes.

This links to #1085, because the functionality in #1085 will only work if the enterprise has opted in.
- [x] Create the setting in the enterprise to 'allow order changes' (guest orders should be discouraged when standing orders are activated, #1160)
- [x] Enable editing of current orders only for shops with standing orders activated
- [ ] ~~Allow standing orders only for logged in users~~
- [x] Show users their current standing order in the shop (that is #1083 and #1084)

**Comment by sstead** [comment]
1) Yes - Enterprises can choose whether to allow editing orders. Potential rephrase...
![image](https://cloud.githubusercontent.com/assets/10843056/20823977/ee612650-b8ac-11e6-93fb-f07c78c587c1.png)

2) Can't test- standing orders not yet here. But correct- only customers in shops that 'allow customers to change orders' can see and edit orders.
3) Can't test - standing orders not yet here

**Comment by yukoosawa** [comment]
@daniellemoorhead Not sure what the expected behaviour is - however when the 'allow changes' option is switched off, as a customer I didn't receive an email telling me the SO was being processed... Is an email sent only when the OC closes and the order is confirmed?

Am thinking from a customer experience perspective, it would be nice to receive the email saying the SO is being processed but if I want to modify that instance of the SO to call/contact the Shop directly.

**Comment by daniellemoorhead** [comment]
@yukoosawa that seems like a bug - if the option is switched off then the order is basically confirmed and cannot be modified but the processing of that standing order should still go through the same process. @oeoeaio any thoughts?
