### ISSUE TITLE
[BUU] Edits on new product page are leaving another product with an empty price

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#11633]
## Description

Better check the step to reproduce to understand

## Steps to Reproduce

Under admin_style_v3 feature toggle

1. Go to staging FR and set your user as a manager of Release Farm
2. Go to Products v3 page
3. Try changing something like removing a "y" in Fryys
4. Hit the save button
5. See an error message gets triggered on the large pizza about an empty price, also you didn't change the large pizza during your setting

## Animated Gif/Screenshot

Before saving

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/721bef3c-9436-497b-a03f-dfdceaafa52e)

After saving 

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/fc3e967e-0ea2-40d6-8e24-5ae1913cd3d4)

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by dacook** [comment]
This is due to the variant being invalid, a problem which would appear if you had updated that row, or edit it in the variant screen.
I wasn't able to replicate this on staging because I couldn't find any variants with a blank price anymore, but I think it would still be an issue.

But you're right that it's strange to be updating a row that hasn't been changed. I had hoped to filter and ignore unchanged rows on the client side (like we do with angular), but I can't find a way to do it with StimulusReflex, because its [form serialisation method](https://github.com/stimulusreflex/stimulus_reflex/blob/736e87df9d11ba1e503a57e61a890c5ab8d04997/javascript/utils.js#L22) isn't customisable . It's a real shame because the user interface makes it look like it's doing that (with the orange borders).
Sometimes I'd like to switch to using a rails standard form submit (probably with ujs), but I'm not sure if it's possible to customise serialisation in that case either.  One way to achieve it would be to alter the inputs, eg make them all disabled upon submit.

Hmm, otherwise it should be easy to do on the server side in Rails, we can just ignore unless `product`/`variant.changed?`

### Estimate
* Add `beforeBulkUpdate` to disable any un-`changed` elements. Ensure disabled elements look the same when being submitted.

**0.5 days**

**Comment by dacook** [comment]
Actually that probably won't make a difference, so I wouldn't bother retesting. 

I've updated the estimate section, to make the solution clearer.

**Comment by RachL** [comment]
I can't reproduce this one anymore. I'm closing it, let's reopen if we find out how to reproduce :+1:
