### ISSUE TITLE
Improve view of previous orders when several orders of same order cycle

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1166]
[updated by Myriam 22.10.2018]

## Description

Currently, all items of all current orders in a given OC are shown individually which can be confusing. 

![ee8fa8f6-6f67-11e6-9cb7-4cf90b42be9b](https://user-images.githubusercontent.com/8135376/47301732-dd4de500-d61f-11e8-8025-37ef6c87f6ac.png)
![b80c51e6-6f6a-11e6-8ad2-7693fc2cb482](https://user-images.githubusercontent.com/8135376/47302552-15eebe00-d622-11e8-955e-bc470bba756f.png)

## Expected behavior

Option 1: list separately each order below the active cart
Option 2: aggregate quantities on "previous orders made for that OC"
@sstead @kirstenalarsen @RachL I'm wondering if option 1 wouldn't be easier and less confusing as customer will be able to reconcile with her order confirmation... what do you think?

## Current behavior
For previous orders, order numbers are not specified, and quantities are not aggregated, so it's confusing.

## Why we should work on that small tweaks?
This is not a bug, working as designed, but not properly designed to handle multiple orders on a given OC.
With the recurring order feature released it is more likely that customer will make complementary orders on a given OC, so will have 2 or more orders in one OC. So we suggest to work on that small tweak with a S3 priority (we don't have complain from users yet... so don't know if emergency or not)

## Possible fix
(from Maikel)
- [ ] Add method to LineItemsController to remove a list of items (2h)
- [ ] Change UI to send a list of items instead of just one item to delete (4h)
- [ ] Process bought items and combine items of the same product (4h)

**Comment by mkllnk** [comment]
@sstead and @daniellemoorhead I just talked with Rob about this. And we think it's a rare edge case. I would also like to know what you think about this alternative:

![screenshot from 2016-11-11 14 51 21](https://cloud.githubusercontent.com/assets/3524483/20203785/7b1dd4a2-a81e-11e6-9dd4-2187285c1436.png)

Instead of condensing the items, we could separate them clearly by order. That way users see when they ordered what and can remove only from one order. For example, if they accidentally ordered twice, they don't have to cancel the whole thing and order a third time. They could just take off all items of one order.

**Comment by daniellemoorhead** [comment]
IMO I don't think the order number makes sense. The customer doesn't care about which order it's in, they only care about the fact that they ordered Loin Steak in this order cycle. To me, if they decide to order more it's because they needed more added to the original amount they bought, so rather than thinking "I want 1kg plus 1kg of loin steak" they're going to think "I want 2kg of loin steak". So I don't think the alternative solution that you've suggested is worth doing at all.

Here's my opinion on the approach we should take: 

1. We take the issue out of MVP, but make sure that we specifically test with the crowd during that two week iterative period whether or not it is actually an edge case. If people notice it and comment on it, then we can action it within that change period. If it's not considered a problem then we leave it as it is (ie. separate items) for the first release.

2. We figure out a way to measure, when we go live, exactly whether this is an edge case or not. And if we find that it's not the edge case we hypothesised it to be then we can look at developing this issue in a subsequent release.

@oeoeaio and @mkllnk how does this sound?

**Comment by mkllnk** [comment]
Sounds very good to me.

**Comment by daniellemoorhead** [comment]
Let's work on this issue in the 2 weeks of iterative changes with community testing.

**Comment by daniellemoorhead** [comment]
@yukoosawa FYI

**Comment by myriamboure** [comment]
Having 10 orders with one product is not a real life case, but more 2 or 3 orders with more products in them... let's keep that in mind when thinking about option 1 and 2 @daniellemoorhead @sstead and probably this tweaks can wait until we have user feedbacks on it.

**Comment by myriamboure** [comment]
Taking out of standing order project as not related directly to standing order, more general case of multiple orders on a given OC.

**Comment by myriamboure** [comment]
I'm finally closing that issue as opened a broader discussion so we agree on a solution, as things are entangled here around the "multiple orders in single open OC" case: https://community.openfoodnetwork.org/t/improve-management-of-multiple-ordering-process-in-a-given-open-oc/1469
