### ISSUE TITLE
Disable "Not notifying due to an invalid api_key" message in Dev

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/openfoodnetwork#11714]
In development mode, this message appears in the rails log, sometimes causing confusion, and it's always unnecessary.

It's because we don't have an API key set for the Bugsnag tool, because we don't want to capture all dev errors in Bugsnag.

The last comment here describes how you can configure it better:
https://github.com/bugsnag/bugsnag-ruby/issues/552#issuecomment-1222107387

(note that we do want to keep capturing errors for both staging and production).

**Comment by yasirazgar** [comment]
@dacook I would like to work on this

**Comment by yasirazgar** [comment]
@dacook I have fixed this in this [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/11733), but according to https://github.com/bugsnag/bugsnag-ruby/issues/552#issuecomment-1222107387 still we need to set the API key for this warning to go away and exclude development in `enabled_release_stages` so that no notifications are sent in development.
I tested the same after excluding development in `enabled_release_stages` the warning still shows up.

**Comment by dacook** [comment]
Thanks Yasir, I'll comment on the PR.
