### ISSUE TITLE
[VCR] Append Stripe gem version to cassettes

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11746]
### What we should change and why (this is tech debt)

Appending Stripe gem version to cassettes should make the tests fail - updated after discussion below.

~~We should change VCR settings so that, from time to time, cassettes are automatically re-recorded and real HTTP calls are made.~~

### Context

This came up [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/11742#pullrequestreview-1707619025).

### Impact and timeline

~~Keeping it "real": making real HTTP calls from time to time may detect breaking changes on 3rd party dependencies, early on.~~ We should get automatic build failures each time we have a Stripe bump; this should remind us to re-save the cassettes for which request have to be re-ran using the latest gem.

**Comment by mkllnk** [comment]
I'm not sure about this. The idea is good but it's hard in practice. For example, if the cassettes expire after a certain time then suddenly all CI build would start to make real requests, a lot of requests. And CI has no way to save the result. Well, in theory there are ways but I don't think it's worth going down that road.

And builds should be reproducible. It would be confusing if you run something, it works and the next minute you run it again and it fails.

The stripe gem now selects the API version number as well. So while the gem version stays the same, we should always get the same responses from Stripe. When the stripe gem is bumped, we should re-record the cassettes. But I think that it will be a manual task. It would be cool though if a new Stripe API version from an updated stripe gem would be seen as new requests by VCR so that it doesn't re-use old cassettes. In that case, the PR to bump stripe could say: sorry, VCR doesn't have cassettes for this, please record them. That's what would make sure that we don't forget to re-record. And we need to delete the old recordings. We could achieve this by naming the cassettes with a key that includes the stripe gem version number.

**Comment by dacook** [comment]
> We could achieve this by naming the cassettes with a key that includes the stripe gem version number.

Good thinking!

**Comment by filipefurtad0** [comment]
Great thinking indeed!

> That's what would make sure that we don't forget to re-record. And we need to delete the old recordings. We could achieve this by naming the cassettes with a key that includes the stripe gem version number.

Sounds good. Maybe we could a spec to compare the current stripe gem version with the gem version on the naming of the VCR cassette? Each time there would be a bump, versions would differ and the spec would turn red - this would then always signal that updating is needed.

**Comment by mkllnk** [comment]
@filipefurtad0 

> Maybe we could a spec to compare the current stripe gem version with the gem version on the naming of the VCR cassette?

My suggestion was much simpler. We can name the cassette like `"stripe-#{Stripe::VERSION}_test-X"` and when the version changes then we don't have the cassettes for the new version. If VCR is configured correctly, it will just fail at this point because it can't find the cassette and that's enough for us to know that we have to update the cassettes. We don't need to compare anything ourselves.

**Comment by filipefurtad0** [comment]
Ahh, got it - VCR does the check for us :+1:
