### ISSUE TITLE
Purchase order and some consumer orders not copied to Stroudco

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1190]
As discussed with Lynne, no copies of purchase order emails came through this week and some consumer order emails also get lost each week. 

Thanks for looking at this.

**Comment by lin-d-hop** [comment]
Thanks @OliverUK. This is an ongoing issue with deliverability to your specific email address as spam bots continue to occasionally pick up the bulk emailing as spam.
Since this might be an issue the could affect other UK users, would you make a thread about it on discourse such that I can update with relevant information?

**Comment by OliverUK** [comment]
Certainly Lynne

**Comment by lin-d-hop** [comment]
Thanks @OliverUK 
This issue is being tracked on discourse:
https://community.openfoodnetwork.org.uk/t/problems-with-notification-emails-not-arriving

An issue has been opened for relevant code change #1193 but this is still under discussion.
