### ISSUE TITLE
French local website impossible to find from openfoodnetwork.org

### ISSUE THREAD

**Issue by Zoyolin** [openfoodfoundation/openfoodnetwork#11905]
## Description
On [openfoodnetwork.org](https://openfoodnetwork.org/) there are a few ways to find your nearest local website. The links to:
France points to https://www.openfoodfrance.org/ which is not working, instead https://coopcircuits.fr is the working URL.
Happy to change severity if that's too high, I think it is a simple issue but pretty critical since searching for "open food network france" on a search engine points to that wrong URL too. Only workaround being to go to this place in docs where the information is duplicated, this time with coopcircuit. https://guide.openfoodnetwork.org/local-ofn-organizations-and-contacts

### Disclaimer
Since "coopcircuit" is quite an odd naming and I'm ignorant of OFN internal decision, it could be that the french platform is meant to move to a more recognisable URL like "openfoodfrance" is. I'm also not aware if that site is just temporarily down.

### Note on other bugs since I clicked around
That the South-africa and colombia's website aren't available too, but the URLs are just not reachable, it's not a timeout like for France.
That the Costa-rica's website isn't available too, but here cloudflare returns Error code 521.

## Expeted Behaviour
¤Click on OFN France¤ -> go to OFN france website.
## Actual Behaviour
¤Click on OFN France¤ -> Browser times out, no website loaded.
## Steps to Reproduce
- Go to https://openfoodnetwork.org/find-your-local-open-food-network/, hover a link to the French OFN and read target URL at the very bottom (on Mozilla Firefox). You can also scroll down to the site map under "LOCAL OFN" category, the link is the same.
- It will be https://www.openfoodfrance.org/.
- Click

## Workaround
No workaround, if you don't know about the coopcircuits key word you are lost, searching qwant or google hasn't found it.

## Severity
bug-s2

## Your Environment
Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0

## Possible Fix
IDK, forward URL or change the OFN.org website, reference coopcircuit on search engines...
Whether it is for documentation, the site map or the "find your local OFN" page, IDEALLY, the data should be pulled from the same place, to stay up to date and in sync, each client taking just the data they need.

**Comment by RachL** [comment]
Hi @Zoyolin thank you so much for the issue!

the website http://openfoodfrance.org/ has some ups and downs but it is supposed to work (it's now up again). Open Food France is the non profit running the OFN brand from a consulting branch in France. 

CoopCircuits is the user-own cooperative running the platform. French users didn't want to keep an English name :) 

Hence the two brand and two websites. Changing it would require a decision in FR, not from OFN global, so I'm closing the issue here, but feel free to ping the french team about this on slack, you can find them under the channel #france

Many thanks again!
