### ISSUE TITLE
[DFC Orders] UX to enable mapping variants

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#12069]
**Funded Feature. Please track ALL ASSOCIATED WORK under the associated tracking code: #11678 DFC Orders**

## Description
In order for users to be able to create the variant mappings to other platforms. There is quite a bit of complexity here.

![Image](https://github.com/openfoodfoundation/openfoodnetwork/assets/8669848/b5562626-e056-4066-beb1-d132542c1b20)

TODO: Unpack this and work through the OFN case

## Acceptance Criteria

When editing an OFN variant, you can add a DFC link and assign a quantity.

## Dependencies

If we want to discover available products for a nice drop-down then we need authenticated access to the other platforms DFC API at this point.

- [ ] #11947

**Comment by RachL** [comment]
FYI I don't know if it's important, but it took me a while to understand: this mapping here needs to happen because there is a chain of actors and perhaps transformation of a variant. Platform A has a variant that is sold differently on platform B, so there is a need for manual linking for traceability.

Otherwise, the simple case of a producer selling same variants through different platforms can be solved by deleting variants on one platform and re-creating them thanks to DFC from platform A to platform B. Then the link is already done, it's faster.

**Comment by mkllnk** [comment]
The mapping is happening in the other platform and will now be exposed through DFC transformations. We can retrieve this data from the DFC API and don't need to do this task in OFN. Closing.
