### ISSUE TITLE
[Admin] Missing translations: Page titles 'Overview', 'Properties', 'Product Import', 'Subscriptions', 'General Settings', 'Enterprise Roles'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12372]
## Description

The page titles of the following admin pages are always shown in English and they are not translated to the selected locale.
- 'Overview'
- 'Properties'
- 'Product Import'
- 'Subscriptions'
- 'General Settings'
- 'Enterprise Roles'

## Expected Behavior

All page titles should be shown in the selected locale.

## Actual Behaviour

The listed page titles above are always shown in English - no matter what locale is selected by the user.

## Steps to Reproduce

1. Log in as super admin (to see all of the pages above).
2. Visit the listed pages.
3. Check the page title in the browser.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/f1d528d3-b427-473a-aa04-60db18b7ec09)

## Workaround

None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by arunguleria** [comment]
Hi @drummer83, I would like to work on this.

**Comment by drummer83** [comment]
Sure, @arunguleria, I will assign it to you!
Thank you and let us know if you run into any issues.

**Comment by arunguleria** [comment]
Hi @drummer83 , Sure I'll check missing translations

**Comment by arunguleria** [comment]
Hi @drummer83 , I checked and fixed the issue but I have one query here. I found in the tab we're using Import name but on browser title we're using controller name. Please let me know can we add controller name in translation file.
Please check the below screenshot.

<img width="1512" alt="Screenshot 2024-04-30 at 1 09 52 PM" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/6175610/a5f1894c-2813-4ae3-9d26-fa87da59c8ff">

**Comment by drummer83** [comment]
@openfoodfoundation/core-devs Could you support please?
Thank you! 🤗

**Comment by dacook** [comment]
Hi @arunguleria , these are generated from the controller class name ([here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/admin/shared/_head.html.haml#L10)), and may be translated by adding a key of the same name. The keys are lowercase with underscores between words, for example:
* Products -> products
* General Settings -> general_settings

They will probably need to be placed under the Spree section in the default locale `en.yml`.
Once they are all there, translators will be able to update for each locale in Transifex later.

Hmm, `spree.general_settings` is already there, in `en` and also `de_DE` for example: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L3983
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/de_DE.yml#L3752

But I can see that some others, like `enterprise_roles` are not there. So that will need adding.
