### ISSUE TITLE
[BUU] Delete button missing, before saving a variant

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12400]
## Description

When we create a line for a new variant (by clicking the New Variant button), on the Backoffice UI Uplift (`admin_style_v3`) design, there is no possibility to delete this new line. The delete option appears only after saving the variant.

This means, that if you hit the button too many times, then you won't be able to save changes. You'll have to navigate away/refresh page, which can mean the info added to some variants will be lost.

## Expected Behavior

The delete variant button is visible before and after the variant is saved.

## Actual Behaviour

The delete variant button is visible only after the variant is saved.

## Steps to Reproduce

First enable [feature toggle](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggles) `admin_style_v3`

1. Visit the products page
2. Create a product
3. Hit the add variant button, to add a variant -> notice there is no delete button.

## Animated Gif/Screenshot

Legacy design:

(Note that you can also view the legacy screen in the new design, by visiting the shortcut `/admin/products_old`)
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/70bdc0a3-1318-4df2-a89a-60cc96939899)

Current design:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/fd9903d2-6077-491f-8123-96bca8e26f98)

## Workaround

Page refresh or just navigating away.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

May I work on this issue ?

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

seems I only have the 'legacy' design.
What is the BUU /''current' design ? Is there some switch to activate it ?
Also, the link to the larger picture from the 2nd picture 'Current design' seems broken.

**Comment by filipefurtad0** [comment]
> Is BUU shorthand BackOffice UI Update ?

Yes that's it :-)

> Is the switch to the 'current' style is to toggle admin_style_v3 in the Features-toggle in the admin ?

Exactly :+1: 

> Also, the link to the larger picture from the 2nd picture 'Current design' seems broken.

Can you see it below?

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/03a0cc5f-00fa-483a-bf36-b45d55826627)

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 , thanks for the clarifications and I can see the picture in large now.
Hello @mariocarabotta , thanks for the links to the original work, I think this will ease the resolution of this issue.

**Comment by dacook** [comment]
Thanks all, yes this looks good. I've added context the steps to reproduce section.
FYI I had briefly discussed icons in [this thread](https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1713372913282449), but I think the goal is to always use words instead of icons, so I like Filipe's suggested solution with the menu 👍 (even though it requires a second click).

Regarding the word "Delete", I think a better word would be be "**Remove**" for this case. This makes it clearer that you're not deleting something from the database, because it's not yet saved. The labels on the old screen are "Remove", for both existing and new variants. It should at least use a different translation key, so countries may translate it as needed.
![Screenshot 2024-04-30 at 10 16 02 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/937904f4-a0ac-4cc9-a746-87909bde9a14)

And finally, I notice that the old screen does **not ask for confirmation**, even if you've entered new data. I think that's ok here, especially because the new design requires a second click, which sort of acts as a confirmation.
