### ISSUE TITLE
[BUU] Dismissing changes is not working

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12473]
## Description

Some product are in a corrupted states, which prevent from dismissing changes and leaves some product pages stuck at the editing state.

this can be seen as super admin : 

- on page 1 in staging AU
- on page 2 in staging FR

## Steps to Reproduce

, We don't know how these products ended up in that state

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/444ebba2-c123-47c7-a6b0-55c981cdbbc6)

## Workaround
none

## Severity

bug-s2: a non-critical feature is broken, no workaround

**Comment by dacook** [comment]
With some experimenting I found it's due to the "None" (empty) tax category. Will have a look at what we chagned recently.

Also thinking about how we can surface unexpected errors like this better.

![Screenshot 2024-05-15 at 4 19 11 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/aaff49c0-55be-42e5-bfa5-27bd5ef51580)

**Comment by dacook** [comment]
Turned this off on au_staging and it now works :D

![Screenshot 2024-05-15 at 4 52 04 pm](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/112c60d9-091f-42c4-b1d0-8b9766cb3ca3)

It was already off on fr_staging. I'm not exactly sure what the problem was. 
On p2 there was a variant with "None", so I updated it. 2 errors went to 1. Then I updated it back to "None". 1 error became 0. 
So I suspect there was something wrong with two other records, but pressing save on them might have fixed it. I can't find any other pages with errors.

✅  So all fixed on AU and FR staging servers 

I've crated a PR to help debug this kind of thing with a row line indicator:
https://github.com/openfoodfoundation/openfoodnetwork/pull/12479. I'll ask MArio what he thinks about the design.

I also noticed a performance problem due to a recent PR. Will raise an issue I think.

**Comment by dacook** [comment]
Still a problem, demonstrated in https://github.com/openfoodfoundation/openfoodnetwork/pull/12486#issuecomment-2123374715

**Comment by dacook** [comment]
I found the second cause of this above issue, described and fixed it here: 
- https://github.com/openfoodfoundation/openfoodnetwork/pull/12521

**Comment by dacook** [comment]
Just came across another example of invalid data, in ca_prod: https://openfoodnetwork.ca/admin/products/22100/edit

This product has no producer, but that's not valid. The producer dropdown is not set up to show an empty selection.
The proposed fix will simply highlight this, like so:

![Screenshot 2024-05-28 at 10 59 28 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/28f52949-e62a-4854-bb48-bb7fad64916e)

Some other possible fixes are mentioned on the PR, but maybe this will be enough.

**Comment by dacook** [comment]
Although the dismiss button still doesn't work for invalid data, we decided to close because https://github.com/openfoodfoundation/openfoodnetwork/pull/12521 makes the invalid data a bit clearer, which helps the user to resolve by fixing the broken data.
