### ISSUE TITLE
[mobile ux] When I expand the hamburger menu on mobile, background image zoom in and overly pixelated

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1253]
## In a feature branch or master?
This can be merged directly to master 🎉 

## Description
On mobile/tablet, when expand hamburger menu, the background image zoom in excessively giving a pixelated look.

## Current behavior
Pixelated view, background image zoomed
![46837804-66844100-ce02-11e8-84ed-b2b68e34221d](https://user-images.githubusercontent.com/8135376/46982578-1bf21580-d0dd-11e8-81c7-af4daea3d8de.png)

## Expected behavior
No zoom in the image
![46837891-a0554780-ce02-11e8-9437-387910acfaee](https://user-images.githubusercontent.com/8135376/46982587-23192380-d0dd-11e8-8152-459f9b4099ef.png)

**Comment by sstead** [comment]
Update: The background image no longer disappears but it does zoom in excessively giving a pixelated look. 
![image](https://user-images.githubusercontent.com/10843056/46837804-66844100-ce02-11e8-84ed-b2b68e34221d.png)

**Comment by RachL** [comment]
@kirstenalarsen was this spotten in the mobile-ready work?

**Comment by Matt-Yorkley** [comment]
Also the hamburger sliding animation is set to be really slow, which makes the app feel like it's slow...

**Comment by luisramos0** [comment]
The background problem is due to this setting:
https://github.com/openfoodfoundation/openfoodnetwork/blob/66de0a4a7144377cdcd8df72bb82535866ab3e7a/app/assets/stylesheets/darkswarm/home_tagline.css.scss#L13

It sets the background-size to cover, see here: https://www.w3schools.com/cssref/css3_pr_background-size.asp
When the menu is open it tries to adapt the large bg image to the small strip on the right, thus the zoom.
I think we can create a specific style for #tagline when the menu is open and set something else on the image so it displays something nice. I tried setting background-size: auto but it's not so simple, maybe we need to truncate or offset the image?
