### ISSUE TITLE
Allow instance managers to activate/deactivate connected apps

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12549]
Blocked by https://github.com/openfoodfoundation/openfoodnetwork/issues/12543

**Funded feature code is #12543 [DFC] Anonymized orders endpoint**

## Description
**- As a:** super admin
**- On page:** we need to create a new page under the superadmin "configuration" menu, something like `/admin/connected_apps_settings/edit`
we can add it at the bottom of the 
**- I want to be able to do:** 

We can add it at the bottom of the menu:
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/cf8d3c07-96e7-49b3-9e1f-c20add73ee05)

When landing on this page, super admin can activate connected apps panel by choosing the connected apps they want to publish (content should be able to be edited in transifex):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/6525576/497cbf99-147a-4d1d-a60c-05f31c5020fb)

## Acceptance Criteria & Tests

1. Log in as superadmin
2.  Visit `/admin/connected_apps_settings/edit`
3.  See you can activate/deactivate connected apps
4. Check that when you update, and login as enterprise users : 
4a. `/admin/enterprises/ENTERPRISE-NAME/edit#/connected_apps_panel` is not appearing if no apps were selected
4b. `/admin/enterprises/ENTERPRISE-NAME/edit#/connected_apps_panel` is appearing if at least one app is available. 
5. Check that the discover regen app still work (can we do that in staging?)
6. All content should have its own translation key

**Comment by dacook** [comment]
@RachL I have been assuming that this issue is just about hiding the connected apps on the Enterprise Settings > Connected Apps tab.

But I just realised that maybe this should also disable any connected apps. For example, if I un-tick Discover Regen, should it also prevent any existing integrations from working? And if so:
1. Do we remove the enterprise connected app data from the database, (so that if we wanted to re-activate, the enterprise managers would have to re-connect)? Or
2. Do we update the integrations (disco regen and affiliate_sales_data) to disabled by these instance settings?

I think option 2 makes the most sense, and avoids the possibility of accidentally deleting enterprise data.

In this case, the PR will require some extra work.

**Comment by mkllnk** [comment]
Agree that it's fine to go the simplest route for now and just hide the settings. We don't know yet what we want to do in a wind-down process. We are not planning on shutting Disco Regen down. So keep the data and the rest is _still to be determined_.

**Comment by dacook** [comment]
Thanks all, ok will proceed without further changes 👍
