### ISSUE TITLE
[White label] Update button always inactive (can't make changes)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12566]
## Description

When using the White Label feature, the Update button never gets active, even though changes are made. This prevents using the feature.

## Expected Behavior

The Update button should become active, when changes are made.

## Actual Behaviour

The Update button never becomes active, even though changes are made.

## Steps to Reproduce

1. Log in as an enterprise owner
2. Visit the White Label section on the enterprise Dashboard
3. Try to create some white label content, or change some settings
4. Notice the Update button never gets active, and that you're unable to save changes.

## Animated Gif/Screenshot

After adding some content to the Trix editor:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e95823e0-23ee-4d0d-b9d9-617afab56203)

## Workaround

None.

## Severity

I think this is an:
bug-s2: a non-critical feature is broken, no workaround

But I'll await till someone confirms this is happening on their system -> I'm doubting this in a way, because specs pass. 

## Your Environment

* Version used: v4.4.50
* Browser name and version: Tested on both Firefox / Chrome, on different staging servers as well as on the local environment; what's strange here is that the spec passes -> `./spec/system/admin/enterprises_spec.rb:629`
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

I have done a quick test.
The button sticks to its disabled status.
Also, when typing text in the editor, it raises a JS error in the console.
In the toggled V3 version but also in the legacy version too.

I have tested with FireFox on Ubuntu 23.10
Also, the spec is green on my system.

**Comment by filipefurtad0** [comment]
I've investigated this locally.

It seems the bug is absent when we reset to 0bfa9fe997913817f14dd91dd6fc10e9ca1d1e0c (and do bundle install && yarn install && db:migrate && db:test:prepare) -> this corresponds to release v4.4.47

The bug is visible when the reset to commit d5dac4d8900dfd66d10eb5ed0e4f4f7436f126cb, which corresponds to v4.4.49.

Hope this is helpful to the dev picking this up. Again, quite surprised about the passing spec. Whatever it is that it is breaking it in ENVs dev, staging, prod, does not break it in test.

**Comment by cyrillefr** [comment]
Due to the bug severity, I don't know if can take this issue.
if this is open, I am ready to have a look and try to fix it.

**Comment by filipefurtad0** [comment]
I think everyone would be grateful for your help and contributions, as always :-)
I've assigned you. Let us know if we can help somehow.

**Comment by cyrillefr** [comment]
Hello @filipefurtad0 ,

A quick update. 
You guessed  right. The issue appears with https://github.com/openfoodfoundation/openfoodnetwork/commit/d5dac4d8900dfd66d10eb5ed0e4f4f7436f126cb
Version -1 before is good.

There is a problem with the `white label` item in that it is not in the html form. It should be. But it is not.
BuUUut, and that is the trickiest part -> in the test part, the html is correctly generated, the `white label` item is IN the html form. That is why there is no error in the specs ...

So, the generated html in dev and the test are not the same. I am still wondering why.
By the way, the error in the trix component(the text editor) is linked: it is because it is not in a form that a JS error in raised.

I have played a bit, and it is really startling: if i remove the `user` part, the `white label` is in the form.
If I loop on the properties of an enterprise, but in reverse, only the `white label` in the form, but every other is out.

My only strategy would be to rewrite some code to do exactly the same thing.
May be @mkllnk would have some hint as he wrote the commit.

**Comment by cyrillefr** [comment]
Just found out why.
The users side menu is linked to another form. But this form is only built if permissions are full.
Creating this new inner form closes the big form in which all the other side menu buttons are.
Hence, white_label is out of the form.

In testing, those permissions are not full, the inner form for users is not built, white_label is in the big form and test passes.

I don't how it would work before https://github.com/openfoodfoundation/openfoodnetwork/commit/d5dac4d8900dfd66d10eb5ed0e4f4f7436f126cb because there were also multiple forms.

I now must figure how to get both forms be properly associated.
