### ISSUE TITLE
[BUU] Messy flash notifications on new products page

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12596]
## Description

Discovered when working on #12567.

The error message about missing payment and shipping methods is displayed twice on top of itself. This requires to click 'Dismiss' twice. If an additional message is displayed (e.g. the 'changes saved' confirmation) only one of those two identical messages is shifted to the side which messes up the screen.

## Expected Behavior

- The message should be displayed only once.
- Any additional messages should be displayed in a tidy manner.

## Actual Behaviour

- The message is displayed twice.
- Any additional messages mess up the screen.

## Steps to Reproduce

1. Set up an active order cycle with just one payment or shipping method.
2. Delete this last payment or shipping method on page `/admin/shipping_methods` or `/admin/payment_methods`.
3. Go to `/admin/products` (with admin v3 feature toggle active)
4. Make changes to a product.
5. Click 'Save changes'.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/58cfe7c3-fbf2-49f7-9d4b-e9c5ad59973e)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by cyrillefr** [comment]
Hello @drummer83 ,

May I work on this issue ?

**Comment by drummer83** [comment]
Hi @cyrillefr,
Of course! I have assigned you.
Thanks!

**Comment by cyrillefr** [comment]
Hello @drummer83 ,

I cannot reproduce the exact same behaviour.

When I delete the last payment method from Fredo's fram, I get right after the "does not have valid" dismiss box.
When I update a product, I get the same box + "Changes saved" alongside.
Same when I update the description of a product.

Actually, I have the same dismiss box every time I click on a tab in the admin.

If I already have the box displayed and I go to the products page, after I change some weight, I only have one dismiss box ....

![MESSY_Flash_msg](https://github.com/user-attachments/assets/a282c49b-84c1-4ab1-9cc6-9adb9b41b47d)
[
![Messy_Flash_II](https://github.com/user-attachments/assets/15018b0a-4695-487b-b167-ca23f218c019)
](url)
![MESSY_Flash_III](https://github.com/user-attachments/assets/56ed620c-8c1a-4195-8fb9-56aa30778edb)

Could it be something happening between when this issue was posted and the current state of master ?

However, there is a dismiss box appearing after each page change ...

**Comment by cyrillefr** [comment]
Ok, now that I posted this message, it seems I can see 2 dismiss boxes.
Though, there is one that disappears after a few seconds ....

**Comment by drummer83** [comment]
Yes, the confirmation should disappear automatically. Only warnings and errors should stay.

**Comment by drummer83** [comment]
Yes, the confirmation should disappear automatically. Only warnings and errors should stay.


Sorry, I'm not at the computer, so can't have a closer look now.
