### ISSUE TITLE
Error 500 when product category left blank

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12591]
## Description

This seems to be a somewhat recent regression:
leaving the product category empty while creating a product returns an error 500.

## Expected Behavior

leaving the product category empty while creating should display a message to the user, no error 500 should be seen - See pic below, taken from staging-UK which has not been updated for quite a while now:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e8573814-6dce-4bf9-8f3e-d1c934e6b89b)

## Actual Behaviour

Leaving the product category empty while creating a product returns an error 500.

## Steps to Reproduce

1. Log in as an enterprise user
2. Visit the products page and click "New Product"
3. Fill in all the mandatory fields except Product Category
4. Click "Create"

## Animated Gif/Screenshot

[Screencast from 19-06-24 14_47_17.webm](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e05c7f6c-9c62-4333-af74-1946abc0e1cd)

## Workaround

Fill in product category before clicking "Create"

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.52
* Browser name and version: Firefox 126.0.2
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by wandji20** [comment]
Hi
After giving this one a try I noticed we can create products without passing values for product supplier or category and would not get the mentioned 500 error. 
I am not sure if I am missing something, but it makes sense that the request is successful since the `ensure_standard_variant` callback in `app/models/spree/product.rb` is only triggered after successfully creating a product object.
However, this callback fails to create the product variant when the supplier or category is missing in the product create params.
We can later create a variant for the product from the products table.

Ideally, I would change the callback to be called before the product is saved but I see we have a different approach to setting variant supplier and category (primary_taxon) when doing imports.
- `self.import_product` in `engines/dfc_provider/app/services/supplied_product_builder.rb`
- `save_new_product` in `app/models/product_import/entry_processor.rb`
- `mark_as_new_product` in `app/models/product_import/entry_validator.rb`

This approach may need some changes everywhere we are creating products and I don't know if it's important to have a variant created when creating a product.

Another possible solution will be to conditionally perform validation (presence) of supplier_id and primary_taxon_id at the controller level to include errors in the product error object.
This will only work when creating a product from the admin dashboard.

**Comment by rioug** [comment]
Thanks for looking in to this @wandji20 . If you want a bit of context you can look at https://github.com/openfoodfoundation/openfoodnetwork/issues/9069 .In short we are simplifying our data model, we are moving pretty much every thing to the variant. But we are yet to change the UI/UX, hence why we are creating a variant when creating a new product. But there is nothing enforcing that a product has to have at least one variant.

> Ideally, I would change the callback to be called before the product is saved

You can't really do that because you need a product to create a variant. But I think we could do something similar by having a `after_validation` callback on create that would manually check if we have a `supplier_id` and a `primary_taxon_id` and raise an error if anything is missing.
Would do you like to give that ago ? 
It might have some unforeseen consequences and break a lot of things, but if this is the case we can revisit and maybe use your last suggestion, ie: doing the validation at the controller level.

**Comment by wandji20** [comment]
Thanks for explaining @rioug
Seems to me it will make sense to use (your suggestion) an `after_validation` callback on `create` that would manually check if we have a `supplier_id` and a `primary_taxon_id` since it will be line [this plan](https://github.com/openfoodfoundation/openfoodnetwork/issues/9069#:~:text=Not%20make%20a%20split%20between%20products%20and%20variants.%20Everything%20is%20the%20same%20and%20all%20necessary%20information%20is%20held%20within%20the%20entity) for the product model.

I will give it a shot and reach out if I doubt anything
