### ISSUE TITLE
[BUU] No explanation why cloning failed

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#12626]
## Description

If cloning of a product fails there is an error message. However it does not indicate what's causing the problem, so the user may not be able to fix it.

## Expected Behavior

The error message should include information about what went wrong and what could be done. 

## Actual Behaviour

There is no additional information on the root cause.

## Steps to Reproduce

1. Activate the feature toggle 'admin_style_v3'.
2. Go to the page `/admin/products`.
3. Make cloning of a product fail. It's unclear how it can be done - it happened accidentally. Maybe it had to do with an invalid format of the product image?

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/fb9303ab-210d-4288-b02c-ad1fa5e8358f)

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
Hi @drummer83 - I've implemented it in such a way that the errors that can be fixed by the user will display which field has an invalid value. Any other errors will still display the default one.
Please review the new error message. Thanks.
![image](https://github.com/user-attachments/assets/129b365e-2075-484c-9592-365f338cf0c3)

CC: @RachL
