### ISSUE TITLE
Products not loading on shopfront: S3 exception

### ISSUE THREAD

**Issue by pragai** [openfoodfoundation/openfoodnetwork#12769]
## Description
On shopfront the loading of products freezes.
Example: https://openfood.hu/anyahajoegyesulet/shop#/shop_panel

## Expected Behavior
Load all products.

## Actual Behaviour
The first few chunk of product list loads, then the loader stays.

## Steps to Reproduce
Go to https://openfood.hu/anyahajoegyesulet/shop#/shop_panel
Scroll down a few times.
See loader do not disappear.

Error in dev toolbar, network response: 
https://openfood.hu/anyahajoegyesulet/shop#/shop_panel

## Animated Gif/Screenshot
![Screenshot from 2024-08-14 09-02-52](https://github.com/user-attachments/assets/86c4169c-c1d9-4bc6-aa2a-b35542ef777f)

## Workaround
None.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
Environment independent.

## Possible Fix
Catch and log S3 exception.

**Comment by chahmedejaz** [comment]
This error has been handled in this PR and ready for testing: https://github.com/openfoodfoundation/openfoodnetwork/pull/12766. It shouldn't be breaking products on the shopfront page after this PR.

However, we still need to find and fix the root cause of why the S3 exception occurred in the first place but that should be of a bit lower priority than this one. Thanks.
