### ISSUE TITLE
[Order Cycle Supplier Totals] Report broken for non-producer hubs

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12825]
## Description

The report Order Cycle Supplier Totals is displaying no results for distributor hubs (non-producer).

## Expected Behavior

The report Order Cycle Supplier Totals should display the totals for a given supplier/distributor.

## Actual Behaviour

The report Order Cycle Supplier Totals should display the totals for a given supplier/distributor.

## Steps to Reproduce

1. Set up a Hub A (shopfront), which will be an order cycle coordinator
2. Set up Hub B, which should be an owner of products (non-selling, i.e., distributor).  
3. As Hub B: under Enterprises set permission for Hub A to "add to order cycle"
4. As Hub A: create an order cycle and add the products from Hub B.
5. As a customer place some orders on Hub A.
6. As Hub A: run the Order Cycle Supplier Totals report 
  -> notice that if Hub B is set as non-producer, the report displays no results; I
  -> notice that if Hub B is set as a producer, the report displays the expected results; On the filter Producers add Hub B -> see that no results are shown
8. As Hub B: run the Order Cycle Supplier Totals report
  -> notice that if it is set as non-producer, the report displays no results

## Animated Gif/Screenshot

**Left - Hub B; Right - Hub A**

![image](https://github.com/user-attachments/assets/2fbc1786-b420-4c0c-a678-98b365600f3b)

![image](https://github.com/user-attachments/assets/f4e78d48-e8ad-481c-97c2-8b79f06a99c8)

**Left - Hub B; Right - Hub B**

![image](https://github.com/user-attachments/assets/d5c2d5b1-8b13-447f-b583-93bee8a60524)

![image](https://github.com/user-attachments/assets/bab66432-f704-4105-b3c2-ecae9c00b89c)

## Workaround

Setting Hub B as a producer hub.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.6.2
* Browser name and version: all
* Operating System and version (desktop or mobile): all

**Comment by BethanOFN** [comment]
This issue is the same as #12835 

**Steps to Reproduce**
1. Select/create an account (Enterprise A) where Primary Details are set to 'producer = yes' and 'sells = none' <img width="1139" alt="Screenshot 2024-09-05 at 09 12 42" src="https://github.com/user-attachments/assets/39fad00d-8671-4383-b641-9533505545a5">
2. Ensure Enterprise A has a product attached
3. Select/create an account (Enterprise B) where Primary Details are set to 'sells = any' (producer setting doesn't change bug)

<img width="1119" alt="Screenshot 2024-09-05 at 09 14 19" src="https://github.com/user-attachments/assets/e6eb5fd4-317e-4044-bb96-840c5db73e4c">

4. Grant Enterprise B permission to add to order cycle for Enterprise A
5. Create an order cycle for Enterprise B
6. Add Enterprise A's products to Enterprise B's order cycle
7. Create an order including Enterprise A's products 
8. As Enterprise A, try to generate **any report** 
9. Observe that page refreshes, any filters applied are cleared and no report data is loaded
