### ISSUE TITLE
Expanded order UI would look better if it's all the same width

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1282]
Device: Mobile/Tablet
Where: Account
![image](https://cloud.githubusercontent.com/assets/10843056/20950323/258327e0-bc73-11e6-8985-f2d980320b83.png)

**Comment by sstead** [comment]
Update:
Holding the tablet horizontal looks ok:
![image](https://user-images.githubusercontent.com/10843056/46839079-ed87e800-ce07-11e8-86bc-c58ef371da66.png)

But holding the tablet vertical it doesn't fit:
![image](https://user-images.githubusercontent.com/10843056/46839136-2e7ffc80-ce08-11e8-9310-18cdf8533117.png)

**Comment by myriamboure** [comment]
#killtablesifyouwantresponsiveux I think we would need some UX view on this. @RachL maybe?

**Comment by daniellemoorhead** [comment]
>Should we then stack that information somehow? I'm not sure having a horizontal scrollbar would make UX better 🤔

😱 

>#killtablesifyouwantresponsiveux

👏 😆

**Comment by RachL** [comment]
Sorry I'm late. But yes I don't understand why there is a table here. For example there are such things as the date where we do need a title (except if we need to be more precis e.g. delivery date vs shipping date).

On other e-commerce site I'm using, mobile orders are listed by date with 3 info : ID number, status and seller. If I want more info, I need to click on them.
![image](https://user-images.githubusercontent.com/6525576/47432872-8b33cd80-d79f-11e8-8eef-11223d25996d.png)



So yes it's more scroll @sauloperez but on mobile it's really not a problem I think. It's quite intuitive.

**Comment by myriamboure** [comment]
I think our case is a little more complex as there is one "page" per hub, a shopper can buy through multiple hubs. And we have some information about "status" (paid or not) and "balance" that are quite important. But I agree that we could work on some mockup of another design for that page, and certain info should be taken out, (like number of products in the order, and the last "display" which is redundant with the clickable order number).
This issue needs to be redescribed as well as since 2016 the account has changed, there are 4 tabs now, so probably the work that Yuko has done about tabs for the shopfront could be an inspiration of a "my account page" with 4 tabs. Do you want to put that in your todo to make a suggestion?
Can you first maybe retest with your phone (I can't do it on mine as bug preventing me from login in through my mobile so can't access account page :-() and see how it looks like now with the 4 tabs? If we see the info, I wouldn't qualify that as a bug and would close this and open a wishlist to improve customer account display, and we can do a super quick inception with one mockup so that it's ready to be prioritized (probably S sized, doesn't seem like a big job... but don't know). Also it could be just left aside for after the first iteration @kirstenalarsen is curating on mobile quick wins. This could be in a second round of small mobile impovements when the major things have been done. Agree? If yes, I would say: let's just close (and maybe open a wishlist or add that as a common on mobile improvement wishlist discussions)

**Comment by lin-d-hop** [comment]
Mobile redesign work has been done elsewhere. This issue is not in a mobile epic so will assume outdated. #gitcull
