### ISSUE TITLE
Asking a report has no result when the producer is set as profile only (doesn't sell products)

### ISSUE THREAD

**Issue by nicolasVr** [openfoodfoundation/openfoodnetwork#12835]
## Description
Several French instance users complained that they could not anymore display reports. They were producers who don't sell their product themselves, but through Hubs.

## Expected Behavior
Reports should display

## Actual Behaviour
No result is displayed (from my trials with all types of reports and with various options) and the form is blanked.

## Steps to Reproduce

1. Set up a Producer A with profile only and a product (the user should not own another shop).
2. Setup a hub B and create an order cycle with product of Producer A
3. Create at least an order
4. Check that Hub B can display reports, but A can not

## Animated Gif/Screenshot
What happens when A tries to create a report :
[RecordScreen-2024-09-02_11.33.38.webm](https://github.com/user-attachments/assets/d4926009-59e2-4d85-8faf-a09d13cebec6)

## Workaround
Workarounds are :
- transform the profile only as a shop
- create a fake shop managed or co-managed by the user
Here is what happens when the profile only producer has been set to become a shop :
[RecordScreen-2024-09-02_11.40.01.webm](https://github.com/user-attachments/assets/db3cb3f9-f54e-45ba-b6e1-053433aaf71a)

## Severity
S3 as there is a workaround, but it concerns a lot of users.

## Your Environment
Checked on coopcircuits.fr and staging

* Version used:
Not browser or OS dependant

**Comment by dacook** [comment]
This is a strange one, it's hard to reproduce with our tests. I've made a start based on Filipe's tests, but still can't quite get it right.
I think the system spec is replicating it reliably, and should be able to narrow down where the issue is. I was also able to replicate locally with sample data which should help verify.

Next is to fix the actual problem. I noticed that the code is looking at the permissions and requires that the supplier has granted add_to_order_cycle permission to the distributor. I think the only thing that matters is if the supplier's products are in an order, regardless of how they got there. So I'd like to simplify this query, but I can't see a way to do it yet :(

**Comment by BethanOFN** [comment]
This issue is the same as #12825 

**Steps to Reproduce**
1. Select/create an account (Enterprise A) where Primary Details are set to 'producer = yes' and 'sells = none' <img width="1139" alt="Screenshot 2024-09-05 at 09 12 42" src="https://github.com/user-attachments/assets/39fad00d-8671-4383-b641-9533505545a5">
2. Ensure Enterprise A has a product attached
3. Select/create an account (Enterprise B) where Primary Details are set to 'sells = any' (producer setting doesn't change bug)

<img width="1119" alt="Screenshot 2024-09-05 at 09 14 19" src="https://github.com/user-attachments/assets/e6eb5fd4-317e-4044-bb96-840c5db73e4c">

4. Grant Enterprise B permission to add to order cycle for Enterprise A
5. Create an order cycle for Enterprise B
6. Add Enterprise A's products to Enterprise B's order cycle
7. Create an order including Enterprise A's products 
8. As Enterprise A, try to generate **any report** 
9. Observe that page refreshes, any filters applied are cleared and no report data is loaded

**Comment by RachL** [comment]
FYI FR support has now 14 open issues for that bug (14 hubs that are impacted, but I don't know how many producers this means).
