### ISSUE TITLE
Display ordering in shopfront field too tight to allow re-ordering of the sequence

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#12852]
## Description
In the new admin interface,  the display ordering by shopfront field (in Shop Preferences in the enterprise settings) does not provide enough room for the user to effectively order the shop display by category  or by producer.

## Expected Behavior
This setting is used by shop managers to control the appearance of the shopfront (ie the order in which categories are displayed,  or the order in which producers area displayed).  The fields should have sufficient space to allow for this ordering.

## Actual Behaviour
The new interface space is too tight and its difficult to fit in two or more lines of categories or producers.

## Steps to Reproduce
1. For an enterprise that is either 'sells own'  or 'sells any'  -  go to the enterprise setting:  shop preferences
2. See the Display ordering in the shopfront setting.

## Animated Gif/Screenshot
![image](https://github.com/user-attachments/assets/374c2e8d-1684-42c6-aee1-59ea612bcbd3)

## Workaround
No workaround -  user has to 'guess' a bit at what the categories or producers are.

## Severity
S4

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by chahmedejaz** [comment]
@RachL - the display issue of the fields has been fixed such that it will be displaying all the selected choices. Here's the screenshot:
![image](https://github.com/user-attachments/assets/80ec813e-5274-48f9-a9c0-9198a4ca016a)

However, I noticed that in the new screen remove option was not implemented as you can also see in the above screenshot. This has also been implemented in the fix for this issue. Here:
![image](https://github.com/user-attachments/assets/624957c8-c233-4c61-8a9a-9441cefd6a23)

**Comment by chahmedejaz** [comment]
The display issue of the fields has been fixed such that it will be displaying all the selected choices. Here's the screenshot:
![image](https://github.com/user-attachments/assets/80ec813e-5274-48f9-a9c0-9198a4ca016a)

However, I noticed that in the new screen remove option was not implemented as you can also see in the above screenshot. This has also been implemented in the fix for this issue. Here:
![image](https://github.com/user-attachments/assets/624957c8-c233-4c61-8a9a-9441cefd6a23)
