### ISSUE TITLE
Report Orders and Distributors should display variant

### ISSUE THREAD

**Issue by nicolasVr** [openfoodfoundation/openfoodnetwork#12878]
## Description
This report should display the product variant. Instead the "variant" column displays the unit. So this report can not be used by shops who use variants.

## Expected Behavior
Report should display the product variant.

## Actual Behaviour
Only Product, unit... are included in report.

## Steps to Reproduce
Ask a report where some products have various variants.

## Workaround
Unkown

## Severity
s3 ?
Together with https://github.com/openfoodfoundation/openfoodnetwork/issues/12877 hubs have some difficulty using various delivery methods in a same order cycle.

**Comment by chahmedejaz** [comment]
Hi @RachL - I've fixed this such that the values for the current "Variant" column are moved to the new columns named "Variant Unit" and the "Variant" column is now displaying the variant display name. Please review the attached screenshot below:
![image](https://github.com/user-attachments/assets/65b5098f-91e7-4a4b-a7e6-a25d07af4e66)

I think we should rename the "Item Name" to "Product Name" as it displays that. But in the scenario where the display name for the variant is not set, then we would be displaying the Product name in its place (which is also the same behavior on the products page). 
Another thought to this might be to show the variant display name in "Item Name" if it's present. If no variant display name is set then "Item Name" displays the product name.

Please share your thoughts on it. Thanks

**Comment by nicolasVr** [comment]
Thanks Ahmed. Your fix answers my request. I think it would be fine to rename "Item Name" to "Product Name".

**Comment by RachL** [comment]
Hi @chahmedejaz thanks for the fix ❤️ ! LGTM

> Another thought to this might be to show the variant display name in "Item Name" if it's present. If no variant display name is set then "Item Name" displays the product name.

What is the display we choose on the order? I would keep the same behavior as this report is showing orders.

**Comment by chahmedejaz** [comment]
> What is the display we choose on the order? I would keep the same behavior as this report is showing orders.

@RachL - On the order's page, if the variant has the display name set, it gets displayed along with the unit in the round braces. If the variant name is not set, only the unit is displayed without braces.

**With variant name:**
![image](https://github.com/user-attachments/assets/f2b7be7c-13a4-4605-bb3f-8e909df3268f)

**Without variant name:**
![image](https://github.com/user-attachments/assets/842308dd-0c16-4903-890d-0e37342a302b)

Now this behavior suggests another solution to use this in the current variant column i.e. If the variant name is present, then display it along with the unit in braces. Otherwise, display the unit without braces. 
And this solution might turn out to be this:
![image](https://github.com/user-attachments/assets/a3147dbf-6be0-40ba-9e38-8a7afa61d001)

CC: @nicolasVr

**Comment by chahmedejaz** [comment]
Just found out that _Order Cycle Distributor Totals by Supplier_ report has the same behavior as above. So, I think let's continue with this solution. 🙌
