### ISSUE TITLE
[DFC Orders] Issue with DFC Imported Products on Bulk Edit Products Screen

### ISSUE THREAD

**Issue by RaggedStaff** [openfoodfoundation/openfoodnetwork#12909]
## Description

Following import of Barnbarroch products from Shopify store, the Bulk Product Edit screen appears to apply some automatic amendments & enforce saving of those amendments.

It seems to be related to products without a weight/default Unit for `SuppliedProduct:hasQuantity`.

## Expected Behavior

Expecting the import to successfully set any/all default values required by OFN as part of the import.

## Actual Behaviour

Seems that the Product level default units are not being set, only the variant unit.

## Steps to Reproduce

1. Login to staging.openfoodnetwork.org.uk
2. Unsure you have an authorised/linked OIDC account for test-hodmedod's Shopify store
3. Run DFC Product Import from [Product Import screen](https://staging.openfoodnetwork.org.uk/admin/product_import).
4. Go to [Bulk Product Edit Screen](https://staging.openfoodnetwork.org.uk/admin/products). Observe modified values for 2 Products (Dulse Flakes).

## Animated Gif/Screenshot

https://github.com/user-attachments/assets/1f914b80-11aa-4c25-9d30-ce2963fa0858

## Workaround

None

## Your Environment

* Version used: latest Production version (08/10/24 deployment)
* Browser name and version: Firefox v131.0.2 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by dacook** [comment]
Unfortunately your video just appears as a black screen, but I found the items and can see what you mean: https://staging.openfoodnetwork.org.uk/admin/products?search_term=Dulse+flakes
![Screenshot 2024-10-14 at 9 33 08 AM](https://github.com/user-attachments/assets/a33c5ce3-d8c0-4a9c-a6d1-44e686854741)

I think this is due to data being in an incorrect state. This probably requires an update to the DFC product import logic. (Probably we need to validate this in the model too). I'll leave this for Maikel to review this when he's available.

**Comment by mkllnk** [comment]
Hm, I don't know what the incorrect state is. Why is the edit screen thinking that we deal with weight? The unit is set to items.

**Comment by mkllnk** [comment]
Okay, I found one bug. The scale was set to 1000 like a kilogram but that's not invalid. That would just be a 1000-pack of items.

**Comment by mkllnk** [comment]
Found it: we have another field `variant_unit_with_scale` which was set to `items_1` instead of just `items`.
