### ISSUE TITLE
Estimate work needed to remove items from cart if they run out of stock

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#12918]
⚠️ **Please use clockify code #12476 Flower Farms**

## Description

**- As a:** shopper
**- On page:** `/cart/XXX` and `/checkout/XXX`
**- I want to be able to do:** 

if one of the items i've added to my cart becomes out of stock I see a generic message telling me my cart was updated.

Shopper can dismiss the message. It should appear on all shopfront pages when products have become unavailable.

![image](https://github.com/user-attachments/assets/5651c04b-977e-4059-a826-af027a1e8731)

## Acceptance Criteria & Tests

The spike results need to give a clear solution in terms of tech solution. And an estimate of the amount of work needed. **No development should be started at this stage.**

**Comment by mkllnk** [comment]
This should already be happening when adding to cart. Code references:

* app/controllers/cart_controller.rb
* app/assets/javascripts/darkswarm/services/cart.js.coffee
* app/assets/javascripts/templates/out_of_stock.html.haml

**Comment by mkllnk** [comment]
And on the checkout pages, we redirect to the cart and display an error:

> An item in your cart has become unavailable.

Code references:

* app/controllers/checkout_controller.rb
* app/controllers/concerns/order_stock_check.rb

Do we need to test this to confirm?

**Comment by RachL** [comment]
@mkllnk ah yes stupid me we could reuse the same message! However what we need to change is the fact that the user needs to remove the item themselves. Here we want to remove them automatically (with no action from the user). So no more redirection to cart when this happens.

**Comment by rioug** [comment]
Out of stock check happens in a few places :
- app/controllers/enterprises_controller.rb
- app/controllers/spree/orders_controller.rb:
- app/controllers/checkout_controller.rb , via app/controllers/concerns/order_stock_check.rb:

We need to ensure the removal of out sock item in all of these scenarios. 
I am assuming, no change to the backoffice

Estimation : **2 days**
@RachL should we add the removed item(s) to the message ?

**Comment by RachL** [comment]
@rioug awesome thanks! I will create a proper issue so we can start working on this ping @tschumilas 

> should we add the removed item(s) to the message ?

I would say no for now (it can be a long list for some hubs) so let's see if this is something that is asked by users and we can always add it later.

**Comment by RachL** [comment]
:sweat: aaaargh actually if you only have one product in your cart and stock gets to 0 we throw an error 500 to the shopper :scream: good thing we will work on this soon!

**Comment by RachL** [comment]
@rioug apologies, i'm seeing now that the current message is different if you are on the shop or if you are within the checkout process or if you are on the cart :exploding_head: .

On the shopfront we are already listing products:

![image](https://github.com/user-attachments/assets/702171d0-43a3-4980-8109-a2f86d08b86b)


:warning: this message ONLY happens if you add/change a product to your cart and a product previously added is reduced.

Once you are on one of the checkout steps (e.g. payment step), you are redirected to the cart and you need to manually change the quantities or remove if out of stock:

![image](https://github.com/user-attachments/assets/d569287b-b4f2-41cb-adc6-2bcdfc491eed)

if on the cart page you are asking for a quantity higher than stock, then the cart will already update automatically:

![image](https://github.com/user-attachments/assets/ac72eaeb-4ec5-4e50-bc0f-c2573cc4857e)


If easy on the tech side, I would suggest:

- Keep shopfront popin, but remove products from cart automatically
- Apply this popin and removal behavior to the checkout steps instead of redirecting to the cart. this means that the order total can change. do we need to reload the page?
- on the cart page keep current behavior

@tschumilas would you agree?

Final bonus question: we now have a design for modals in the shopfront. maybe we should take the opportunity here to apply this design to the modal?

https://www.figma.com/file/QMLtSme5zWp5UOunWOEZgB/Order-Cycle?type=design&node-id=9%3A6&mode=design&t=3hezHWn5hkPdqJn0-1
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/68649866/7464a62a-1231-4a8e-8e52-bfca55aeb6aa)

**Comment by tschumilas** [comment]
Nice work here -  I didn't know about these different popups.    
When would the 'your order has not been placed'  modal appear?

**Comment by RachL** [comment]
@tschumilas nowhere, this is just a design template sorry for the confusion

**Comment by rioug** [comment]
-  Keep shopfront popin, but remove products from cart automatically

I think that's somewhat already happening, it sets the quantity to 0 but that should be easy to just remove the product

-  Apply this popin and removal behavior to the checkout steps instead of redirecting to the cart. this means that the order total can change. do we need to reload the page?

The stock check happens when loading the page, so we can just update the order before rendering the page and displaying the pop up. No need to reload the page. 

-  on the cart page keep current behavior

:+1: 

Updated estimation : 

Out of stock check happens in a few places :

- app/controllers/enterprises_controller.rb
- app/controllers/spree/orders_controller.rb:
- app/controllers/checkout_controller.rb , via app/controllers/concerns/order_stock_check.rb:

We need to ensure the removal of out sock item in all of these scenarios, and check fees are updated accordingly. We need to display a pop up when the order has been updated due to stock changes, see design above. Related code : 
app/assets/javascripts/templates/out_of_stock.html.haml
Ideally we would use a `ModalComponent`, and get the `AngularJs` modal to load it via StimulusJs/Turbo to avoid code duplication.

I am assuming, no change to the backoffice

Estimation : **3 days**

@RachL I added an extra day to deal with the pop up as it's potentially tricky to do.

**Comment by RachL** [comment]
Thanks @rioug ! 
I've noticed we still need to remove items when on cart. I figure we can live with this for now and see if t causes pb in production. The biggest pain point currently is checkout process, so my suggestion is to focus on it for now. 

New issue ready to pickup here: https://github.com/openfoodfoundation/openfoodnetwork/issues/13054

Closing here.
