### ISSUE TITLE
Payment type text wrapping when not needed. 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1301]
Device: Mobile/Tablet
Where: Shopping cart
Recommendation: Text padding / line height should be reduced
![image](https://cloud.githubusercontent.com/assets/10843056/20952118/471590d6-bc7e-11e6-9cdc-3e3987db0ef6.png)

**Comment by Matt-Yorkley** [comment]
The text folding was in place because a message box is shown to the right if the selected payment option has additional notes attached to it (shown when selected). 

![screenshot from 2016-12-17 20-37-42](https://cloud.githubusercontent.com/assets/9029026/21289640/0d9a48dc-c49a-11e6-8f0e-09f64af6b6d1.png)

I've adjusted the widths for small and medium devices so the text is full-width (instead of half) and the notes are shown underneath.

![screenshot from 2016-12-17 20-38-06](https://cloud.githubusercontent.com/assets/9029026/21289662/9182fe50-c49a-11e6-8ead-3137f2d81aee.png)

The payment options section uses the same sort of layout so I've adjusted it to match, as the issue was replicated there too.

**Comment by lin-d-hop** [comment]
Great! Do you think it is worth also putting a max length on this field @Matt-Yorkley?

**Comment by Matt-Yorkley** [comment]
I think it's ok as it is, it was just an issue with the way lines were wrapping. 50% of the screen is not much space on a 370px screen!

**Comment by OliverUK** [comment]
Tested on my mobile phone (BQ Aquaris X5) using Firefox as browser. The checkout sections in question now look as below.

![screenshot_20170103-171050](https://cloud.githubusercontent.com/assets/17590921/21616082/15044276-d1d8-11e6-9e58-5b4945067e2d.png)
![screenshot_20170103-171133](https://cloud.githubusercontent.com/assets/17590921/21616083/15051ac0-d1d8-11e6-9dc8-5bcf34a884db.png)

**Comment by OliverUK** [comment]
![screenshot_20170103-171821](https://cloud.githubusercontent.com/assets/17590921/21616364/196f7f8c-d1d9-11e6-95cb-d0476601e4ae.png)
