### ISSUE TITLE
Field hint text is using Australian suggestions on UK Staging (ie. Suburb Northcote) 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1310]
Field hint text is using Australian suggestions and labels (ie. Postcode 3070, Suburb Northcote, State)
Recommendation: Make this able to be set in super admin. Even better, have changeable fields based on country selected.
Devices: All 
Where: Register - UK staging

**Comment by lin-d-hop** [comment]
Currently this is set in translations.

Are others happy with this? UK are happy enough having these details set in translation files (our staging file was just rather outdated... just committed an update.)

**Comment by myriamboure** [comment]
The translation works ok when a user set up an enterprise from the front office link ("join the network" link) BUT it is not well displayed when you create an enterprise from the back office "new entreprise" button.
So there is a bug there. But happy with having that in translation.
See screenshots below.
![screenshot from 2016-12-11 19-57-13](https://cloud.githubusercontent.com/assets/8135376/21082460/47c25c1a-bfdc-11e6-84ba-5fd982166c54.png)
![screenshot from 2016-12-11 19-58-22](https://cloud.githubusercontent.com/assets/8135376/21082463/4970468a-bfdc-11e6-8e71-b0f237f0559b.png)

**Comment by Matt-Yorkley** [comment]
@lin-d-hop There's translation keys already set for these, but the template file for adding new enterprises in the backend doesn't use the translations yet, it still has the hard-coded strings. 

Also I've just noticed it seems to use a hardcoded list for the states dropdown, which doesn't change when you select a different country. The form seems to be calling the wrong angular module as well (admin.users instead of admin.enterprises), maybe that's why.

**Comment by lin-d-hop** [comment]
Yeah this is not an issue on the enterprise sign up screen, just low priority maintenance.

However @Matt-Yorkley it would be worth replacing the backend hardcoded strings as you picked up.

**Comment by Matt-Yorkley** [comment]
There's already work underway on finishing off missing translations in #1095 . I've left some notes in that thread.

**Comment by lin-d-hop** [comment]
Great. Closing :-)
