### ISSUE TITLE
Limit countries in enterprise sign up to those with states

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1330]
In the enterprise sign up form State (or County in UK translation) a required field. However not all countries have states attached to them.

It is likely that many countries will have producers from multiple countries. But if a country has no states linked to it a user cannot sign up to this country. Therefore it would make sense to limit the countries displayed in the enterprise sign up drop down to those with states attached.

In fixing this issue it would be great if you could check that 'setting states' is clearly documented in the github wiki.

Note on UK staging default is not set to UK. Would be good to fix this at the same time.

**Comment by myriamboure** [comment]
Lynne do you mean that we need to find an equivalent to "state" for each country, set it up, and then only the countries set up will be proposed?
In France for example we don't need states, but I guess the "search by state" is based on it so we used some other geographical notion not to loose the search functionality. I suspect that can apply to every country so why limiting display to countries with states if we say all countries should have states? 
Or should we make optional the fact of using the "state" field?

**Comment by Matt-Yorkley** [comment]
I've been working on this today. @myriamboure will there not be a list of regions at all for France? In the UK our equivalent for states is counties.

Limiting the list to countries with their states set up means the user doesn't have to scroll through a list of every country in the world, which is quite nice. The list will only show the countries that have been configured on that OFN instance.

@lin-d-hop limiting the list of countries is quite simple but setting the default country might require changing things around quite a bit, and I'm conscious of the fact there are at least two PRs open that both modify the frontend registration form. Might be best to wait until they're both tested and merged?

**Comment by myriamboure** [comment]
Ok, @Matt-Yorkley it seems to me that by default, all countries have the "state required" checkbox checked. So do you mean you would change that, say that by default the checkbox is unchecked and only when checkbox is checked the country is proposed in the list at registration?
I'm just wondering if that wouldn't be more logical to add a checkbox saying "active for the instance" and if checked country is displayed if not not displayed, just thinking if we have more and more people setting up instances it's better if it is logical and not too much tweaked. I think we should leave the instance decide if they want this info to be compulsory or not for the user to fill in (state required or not), which won't be the case anymore. BUT if it's much simpler to do the tweak as long as we know it is fine :-)

Then I would suggest to rename the filled then "active for the instance" and just say in the super admin guidebook that it is compulsory to set up an notion of a regional level that entreprises can associate to their profile and that users can search by.
Instances are then free to have some autofill rule if they don't want to ask the user to fill it.

For France it's ok, I said we can find an equivalent of "county" for France. No ideal in terms of user friendliness, usually platforms don't ask that usually. But we kept this and we asked the "departement" (small region) in order to enable people to search for hubs around them by "departement". We can work later on having it filled in automatically as the departement is the first to figures of the postcode, so we'll make our cuisine out of it!

**Comment by Matt-Yorkley** [comment]
@myriamboure I hadn't looked at modifying the backend, the current proposal just limits the options displayed at registration to countries that have states set. It looks like having states or regions is going to be mandatory.

I could look at implementing checkboxes in superadmin for which countries are active on the instance, possibly in a separate issue. What do you think, @lin-d-hop ?

**Comment by myriamboure** [comment]
Ok I think I understand @Matt-Yorkley , Countries have states only when you import the seeds files needed, or add the manually in configuration. As we say it's compulsory if a country has no states attached, it is not proposed at registration. That sounds fine to me, I don't think that's a priority then to say which countries are active or not, maybe we should just document that in super-admin set up here https://community.openfoodnetwork.org/t/initial-set-up-and-configuration/198

**Comment by lin-d-hop** [comment]
@myriamboure Similarly for the UK county is not generally a compulsory field. 
@Matt-Yorkley In your investigations what are the implications (if any) of removing the compulsory nature of states? If this is a simple fix I think it would be worth doing as well.
@sstead Can you see an issue with making 'state' non compulsory in enterprise sign up?

**Comment by Matt-Yorkley** [comment]
I think it is compulsory, currently. We could add a superadmin option like a checkbox to make it non-compulsory. I think it's useful for postage though, it means proper addresses have to be set.

**Comment by lin-d-hop** [comment]
Yep it is currently compulsory.
In the UK this field is superfluous. It only serves a purpose if the postcode was written incorrectly with the wrong county code.  In Australia it is more important, you would generally always ask for state to be specified even though it is captured in the first digit of the postcode. In France it sounds like it is also superfluous.

@Matt-Yorkley In your investigations what are the implications (if any) of removing the compulsory nature of states? Are there known on effects in other places ie area lookups that rely on state?
@sstead Can you see an issue with making 'state' non compulsory in enterprise sign up?

I agree @Matt-Yorkley that it should be facilitated through a checkbox in super admin. But currently I'm not sure if this is a suitable change or not, not knowing the dependencies.

**Comment by sstead** [comment]
I'm not certain of how the address is interpreted and placed, and whether an address could be placed in Australia without State. As mentioned State is typically required in Aus. I would say only make states non-compulsory if you can be sure that this won't lead to 'invalid' addresses that the map can't place. In the past we've had trouble with invalid addresses - sometimes the enterprise gets placed in Africa or somewhere random, and other times it's caused groups to malfunction (hiding all enterprises because one is invalid).

**Comment by pmackay** [comment]
Could I just ask, related to this, is it essential to ask enterprises what country they are in? Might it be worth having the country as an optional field? In OFN instances where the country is always the same, it would be a great UX improvement not to ask it.

**Comment by lin-d-hop** [comment]
I do think we need to ask country. Uk is working with spanish producers already. But we should limit countries and have a default for sure.⁣

**Comment by Matt-Yorkley** [comment]
So I've made a PR or this and it's ready for review/testing. It should make UK the default option and limit the list to countries with states, so effectively the country will be already filled out for the user.

**Comment by lin-d-hop** [comment]
PR number? Thanks @Matt-Yorkley!!

**Comment by Matt-Yorkley** [comment]
If you scroll up in this thread you'll see I did it before Christmas :P 

#1334.

**Comment by lin-d-hop** [comment]
@OliverUK this is ready for testing now :-)

**Comment by OliverUK** [comment]
@lin-d-hop this was already staged on Buildkite so I told it to rebuild and tried to stage it again but it failed.

**Comment by lin-d-hop** [comment]
@OliverUK can you share the error message?
If the build is already on staging the deployment will fail. You should be able to see this in the error messages. If that is the case you can just go ahead and test.

**Comment by OliverUK** [comment]
I thought you had told me that any deploy overwrites the previous? I deployed something else first so assumed the changes made here would no longer be on staging.

Removing app/assets/javascripts/templates/registration/type.html.haml
Removing app/assets/javascripts/templates/registration/steps.html.haml
Removing app/assets/javascripts/templates/registration/social.html.haml
Removing app/assets/javascripts/templates/registration/limit_reached.html.haml
Removing app/assets/javascripts/templates/registration/introduction.html.haml
Removing app/assets/javascripts/templates/registration/images/promo.html.haml
Removing app/assets/javascripts/templates/registration/images/logo.html.haml
Removing app/assets/javascripts/templates/registration/images.html.haml
Removing app/assets/javascripts/templates/registration/finished.html.haml
CONFLICT (modify/delete): app/assets/javascripts/templates/registration/details.html.haml deleted in origin/master and modified in HEAD. Version HEAD of app/assets/javascripts/templates/registration/details.html.haml left in tree.
Removing app/assets/javascripts/templates/registration/contact.html.haml
Removing app/assets/javascripts/templates/registration/about.html.haml
Removing app/assets/javascripts/templates/registration.html.haml
Automatic merge failed; fix conflicts and then commit the result.

**Comment by lin-d-hop** [comment]
Hi @OliverUK, Sorry just saw this. Perhaps you could tag me in future? 

You are right that the changes don't persist. But if you try to deploy the build that is already deployed it will fail with the error that it is already deployed.

I'll take a look at the error above.

If you would also move things from test ready to dev it will help me to know when issues are being looked at by you and when they need to be looked at by devs.

One day we'll figure out a process that works :-)

**Comment by mkllnk** [comment]
@lin-d-hop I merged #1609. You are welcome to test and comment on or close this issue.

**Comment by lin-d-hop** [comment]
Great! Thanks @mkllnk Will close and reopen if we notice new issues.
