### ISSUE TITLE
Cart disappears when payment options not configured correctly.

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#1343]
I've noticed that a hub's payment options have to be set to "testing", "development", "production" or "staging", and if there are no payment methods assigned to a hub with the correct environment set, it assumes the hub has no payment options. Then when I click view cart I get bounced to the home page with an error message about the hub being "temporarily closed", which is not very informative as the hub definitely appears to be open. Also the cart gets emptied without warning. It seems it happens when the hub either has no valid payment options or no valid delivery options. Maybe that check should be made before the user starts interacting with the hub's products rather than after their cart is filled up.

Shopping: 

![screenshot from 2016-12-19 11-15-45](https://cloud.githubusercontent.com/assets/9029026/21310974/d48a45da-c5dc-11e6-913f-0787d2217b3c.png)

After clicking on cart:

![screenshot from 2016-12-19 11-15-35](https://cloud.githubusercontent.com/assets/9029026/21310980/de7e2f48-c5dc-11e6-92d2-59b331f8b257.png)

I'm thinking the shop should not be shown as open if customers aren't actually able to purchase anything (payment or shipping not configured), as opposed to appearing open and only telling the customer at the checkout that the shop is closed (for an unknown reason).

**Comment by lin-d-hop** [comment]
For the most part this happens. If there are no payment or shipping methods hubs with active order cycles do not appear as open. So it seems that this same check does not consider errors in payment or shipping methods.

The solution, then, would be a update the existing check on whether a hub has shipping/payment methods before displaying as open. Not sure where this happens... can dig around if needed :-)

**Comment by lin-d-hop** [comment]
@OliverUK ready to test now :-)

**Comment by OliverUK** [comment]
@lin-d-hop 
Questions for testing purposes. The environment is set in super admin so under what circumstances would a hub have a shipping or payment method which isn't configured properly unless a super admin fiddles with it?
I assume if I sign up on the production site and create an enterprise, my methods are automatically set to production?

**Comment by OliverUK** [comment]
Incidentally I tried a not-properly-configured Paypal payment option on the Stroudco shop on production and was able to shop but got an error message on checkout. It just stayed on the checkout page waiting for me to take an alternative action.

**Comment by lin-d-hop** [comment]
@OliverUK You are correct that this won't generally happen. Matt would have discovered this on playing with test data from another database.
It still seems like a good check to have in place, but it should never come up on production.

**Comment by sstead** [comment]
Hey all, while this looks like a bug, this is actually related to the ability to setup a 'display only' shopfront. See [relevant user guide page](https://openfoodnetwork.org/user-guide/advanced-features/creating-display-only-order-cycles/). Some users have requested that they can show their product range when they don't have an open order cycle, and this was the work around.

I agree, the shopper's experience of encountering a shop that looks open but later kicks them out is terrible. We could either remove this 'display only' shopfront functionality, or we could improve the shopper's experience- by alerting them as soon as they land in the shop that it's 'display only', or by labeling it as such in the directory.

**Comment by daniellemoorhead** [comment]
Hey there @lin-d-hop @Matt-Yorkley @OliverUK we'd like to sort this one out for 1.8.9 release. See @sstead's comment above, where do we take this next?

**Comment by OliverUK** [comment]
Hi @daniellemoorhead 
I got confused at the time what needed testing because the problem was discovered as a result of incorrect super admin settings. But now I understand the fix will also sort out incorrect user settings, i.e. no payment or shipping method = shop closed. Is this correct @lin-d-hop ? Does it still need testing? There doesn't seem to be a build.

**Comment by Matt-Yorkley** [comment]
Okay, so maybe a better solution would be: show a clear message on the shop page that the shop is "display only" or not ready for sales, disable "add to cart" buttons on the shop page, and also make it clear when browsing the shops directory that this shop is "display only".

**Comment by Matt-Yorkley** [comment]
@sstead How does that sound? ^

**Comment by sstead** [comment]
That sounds good to me Matt. Is it significantly more work to save this 'display only' feature by improving the UX, rather than just removing it and showing the shop as closed?
If it is a lot of work to save it and others deem it not a priority feature, I'd also support removing the 'display only' option. I don't know of anyone using it. Plus, ideally if we wanted to offer a display only shopfront, it would be configured in the OC, as a tickbox saying 'display this OC in closed form when no OC is open'. The current process for setting up this 'display only' shopfront is pretty fiddly- you need to disable shipping/payment methods, change your shopfront message to say 'display only' and then undo this again when you do open an OC... because it's so fiddly few people use it... so is it worth saving?

**Comment by OliverUK** [comment]
@sstead 

> so is it worth saving?

Not in my opinion.

**Comment by daniellemoorhead** [comment]
So what are the next steps with this @sstead @OliverUK @Matt-Yorkley?

**Comment by Matt-Yorkley** [comment]
@daniellemoorhead Well the current PR basically removes this "display only" functionality and fixes the existing issue with shopping in unusable hubs. As @sstead mentioned it might be quite a bit of work to make a properly functioning "display only" type thing and it's pretty low priority.

So the question is are people happy with "display only" shops no longer appearing in the shops index for the time being?

**Comment by daniellemoorhead** [comment]
Consensus between @sstead and @oeoeaio is for this to go ahead. @mkllnk / @sstead will test today and should all going to plan be pushed as part of 1.8.9.

**Comment by sstead** [comment]
@Matt-Yorkley we've agreed it's best to remove the 'display only shop' feature. So if there are no shipping and/or payment methods setup, the shop will show as closed. Testing shows this fix is half way there...

I have an open OC, but either my shipping method and/or payment methods are deactivated.

What's working:
- The shops shows as closed on the shops listing and in the profile (this includes in a Group)
- This works for simple producer OCs and Hub OCs
- This error message remains. I think we should keep it in case anyone does have lingering display only OCs.
![image](https://cloud.githubusercontent.com/assets/10843056/24534868/558ae308-161c-11e7-94b5-2a821e0c066f.png)

What's not working:
- If I click on the closed shop link in the shops listing, or if I go direct to the shop's URL, I find a shopfront that appears open. I'm not able to shop (get kicked out when I try to proceed through checkout). We need to change this so that the shop shows as closed.

**Comment by Matt-Yorkley** [comment]
@sstead I've updated the closed (non-configured) shops. 

- They now show the proper "orders closed" header at the top of the page. 
- If there's an open order cycle for the shop you can still see the products but can't checkout.

**Comment by sstead** [comment]
Ok this looks good. We still have some 'dispaly only' functionality but it's much more clear that the shop is closed. 

This is what shows if a shop has an active OC but no active shipping and or payment methods:

![image](https://cloud.githubusercontent.com/assets/10843056/25164986/739ec3f0-2517-11e7-9942-f08ca4885b5e.png)

These shops won't show in the shops listing, and their profile links show as Closed.

I'm happy for this to be pushed.
