### ISSUE TITLE
Links in wzywg not working- adding openfood at start of URL

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1348]
![image](https://cloud.githubusercontent.com/assets/10843056/21378809/1cfec568-c79d-11e6-8c40-8109da870db7.png)

**Comment by lin-d-hop** [comment]
Flagging for @Matt-Yorkley

**Comment by myriamboure** [comment]
This should be fixed now by https://github.com/openfoodfoundation/openfoodnetwork/pull/2298 @sstead please check if you still have an issue. For your info this PR is open to open hyperlinks in another tab so that it doesn't take users out of the OFN platform. https://github.com/openfoodfoundation/openfoodnetwork/pull/2384
