### ISSUE TITLE
Adding multiple notification email addresses breaks email notification process

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1363]
The Tree St Andrews put multiple email addresses into the 'Notifications' box on the Enterprise Admin screen (see below).  This had the effect of preventing them receiving any notification emails.
Please can we change this so that: 
1) only one address can be entered and
2) rather than entering any email address in the this box, we have to select a user from the list of registered users.
In the long term it would be good if we could allow multiple users to receive notifications
Thanks
![screenshot 2017-01-09 11 35 16](https://cloud.githubusercontent.com/assets/10517702/21765424/b5fe3d3a-d660-11e6-9305-a8494a39c243.png)

**Comment by lin-d-hop** [comment]
@sstead in Aus I imagine there are cases that people have put in emails that are not the email of the user account they signed up with.
For the purposes of validating emails in this field do you think it is better to use enterprise emails (which have been verified) or just to do some simple checking that the text in this field is the correct format and only one email.

**Comment by sstead** [comment]
The notifications box has a hidden functionality... if I enter an email that is not a registered user on the OFN, that person is sent an email confirmation. If they confirm their email they're added as an enterprise user, prompted to create a password and become a manager of that enterprise. 

This functionality was put in place so that when OFN Aus created profiles on behalf of producers (e.g. if we setup a group with 50+ new profiles) we can transfer ownership to the actual producer by simply typing their email in the notifications box... the ball is then rolling for them to become managers.

If a non-user email has been put in the notifications, but that email isn't yet confirmed, notifications will continue to go to the last valid notification email (usually the owner/manager). Users are told that they must confirm the email. 

**Given the above, it's preferable that this field continues to accepts non-user emails. If possible, the suggestion to have the field check that only 1 valid email address has been entered is best. Perhaps with future option to +Add Notificaton Email, in the same way you add multiple managers.**

**Comment by myriamboure** [comment]
Closing as this is what have been done in the email confirmation project, so that's in place :-) If we want later on to be able to have multiple people receiving notification we can create an icebox (if the need is there...)
