### ISSUE TITLE
Group map showing invalid address in Ocean off Africa

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1383]
![image](https://cloud.githubusercontent.com/assets/10843056/21915043/489693e0-d98b-11e6-8c4b-ccae8dc046ec.png)

**Comment by daniellemoorhead** [comment]
Note: This is happening for the UK team as well as they create new groups (see closed duplicate issue #1567). 

Seems to be linked to an address which can't be geocoded for the map. Doesn't happen on the main shop map, just on the group map.

Ping @lin-d-hop @NickWeir63 in case you want a UK dev to pick this up and resolve it.

**Comment by lin-d-hop** [comment]
This happens when an address is not geocoded correctly. The solution is to fix the shop address by checking in google maps that it is accurately geocoded.
I don't think there is a good technical solution to this. It is better to actually notice the incorrectly positioned enterprise and update the address that to have the enterprise not show on the map.
