### ISSUE TITLE
Improve communication of 'Items not available in this standing order' in email.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1413]
Expected: In the 'Standing Order open' email , customers will be told if some items in their standing order are not available in the current order cycle and therefore not going to be delivered.

Email was sent with unavailable items not listed - however I was not told they were unavailable, they just didn't show up.

*Issue spotted by Yuko

**Comment by daniellemoorhead** [comment]
@oeoeaio to investigate further to understand if this is actually a bug.

**Comment by daniellemoorhead** [comment]
@yukoosawa need to get a better understanding of how you did this, @oeoeaio can't replicate.

**Comment by yukoosawa** [comment]
@daniellemoorhead I've retested this scenario in Staging1 (post 2017-02-17 build from Rob) and it looks like it is now working correctly.

From memory, at the time of testing (2017-01-19) I completed the following steps:

_Shop (yukomart)_
- Created the OC
- Created the customer SO which included an item for which 0 inventory was available (Nappa Cabbage)
- Created the Schedule and added OC, which triggered the order creation

Customer
1. Email was sent by shop saying the OC was open
2. Expected the email to say item (Nappa Cabbage) was not available, which it didn't.

That version of Staging1 has since been wiped and rebuilt. I tested the same scenario today and got the expected message in the email.

![screen shot 2017-02-17 at 12 09 08 am](https://cloud.githubusercontent.com/assets/19785399/23053167/603efbce-f4a5-11e6-9c5f-7299ffac8160.png)

**Comment by daniellemoorhead** [comment]
@oeoeaio given @yukoosawa's retest and proof may be worth looking at once all the other stuff is done.

**Comment by yukoosawa** [comment]
Follow up to my previous comment. The email sent to me for my SO confirmation lists the unavailable item. In this instance the confirmation feels odd as I will not be receiving anything... But possibly an edge case??

Steps:
1. OC closes with yukomart
2. User sent a confirmation email for the processed SO
3. Product list includes the item with 0 inventory

Note:
- Known issue re: charging a user a delivery fee for 0 items still being presented (https://github.com/openfoodfoundation/openfoodnetwork/issues/1414)
![screen shot 2017-02-17 at 10 39 28 am](https://cloud.githubusercontent.com/assets/19785399/23077920/78ecd0f0-f514-11e6-89df-d2b6d630dcae.png)

**Comment by oeoeaio** [comment]
Noted. Will cover off that issue as part of #1414

**Comment by oeoeaio** [comment]
I think this should have been fixed as part of what I did for #1414. Need to test both emails (one at start of OC and one at end of OC).

**Comment by sstead** [comment]
Messaging is now fine.
