### ISSUE TITLE
Standing Order email OFN logo lacks contrast

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1415]
The OFN logo in the email header is using white text which isn’t legible on the grey background. If you print the email, the white text is invisible on the white background.

This may not be an issue on production, using production logo?

![image](https://cloud.githubusercontent.com/assets/10843056/22278024/610e77ac-e314-11e6-8fc2-1bf50de6ffdd.png)

*Issue spotted by Yuko

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley do you think this is something you could sort out in your improvement tweaks meanderings? It's an issue that came up in the testing of standing orders but it's current functionality rather than caused specifically by the new feature.

Actually, wondering whether you guys in the UK have the same issue? @NickWeir63 are you able to tell us if it's a problem for the UK too?

**Comment by NickWeir63** [comment]
I am forwarding this to @OliverUK who is doing the UK testing on this.   I will pick it up if he doesn't have time

**Comment by OliverUK** [comment]
I can't find any of the emails sent from staging 2 so maybe I didn't keep them. @NickWeir63  I think you forwarded them to me? 
We tested on the AUS sever so not sure if it would have looked any different for us in the UK.

**Comment by NickWeir63** [comment]
Yes @oliver is right - we were testing on Aus Staging 2- see below
![screenshot 2017-02-17 14 48 51](https://cloud.githubusercontent.com/assets/10517702/23069692/577de97a-f520-11e6-8396-c801ed835873.png)

**Comment by myriamboure** [comment]
Removing #bug label as this is a new feature not yet released and in the test ready pipe of the subscription project. #gitcull2018

**Comment by myriamboure** [comment]
Logo displays correctly on French production, so seemed it was linked to Aus staging, closing the issue then.
