### ISSUE TITLE
Numbers do not overwrite when shopping in Explorer

### ISSUE THREAD

**Issue by MagsHall** [openfoodfoundation/openfoodnetwork#1417]
On UK production, when shopping if I enter a quantity to purchase in the box the default 0 is not overwritten. I have to delete this 0 and enter the quantity I want, or risk purchasing a multiple of 10! 

This is only occurring in Windows Explorer 11 and not on other browsers. 

![numbers not overwriting](https://cloud.githubusercontent.com/assets/19837861/22297310/cb89465c-e314-11e6-9803-152e9c61aefb.png)

**Comment by stveep** [comment]
This seems to be an incompatibility with Angular and IE11. I came up with a fix that just ensures the existing text is highlighted when you click inside the box. It looks a bit uglier but that can be fixed with some CSS targeted at these boxes, as long as this solves the original problem.

Please test that it doesn't break anything on other browsers.

[Aside] I think the original problem only occurs the first time a box is clicked. It might be due to the ng-pristine/untouched attributes in some way but I couldn't figure out exactly why.

**Comment by MagsHall** [comment]
@stveep Are the changes on the staging server? I can't see any difference on production.

**Comment by lin-d-hop** [comment]
@MagsHall If you need something on staging best to give @OliverUK a shout.

**Comment by stveep** [comment]
I have just put it on staging.

**Comment by MagsHall** [comment]
So all looks fine on staging when browsing in Chrome, but products are not loading on the shopfront when I try to browse in IE11

**Comment by OliverUK** [comment]
I'm afraid I don't have IE, so can't help test this one.

**Comment by enricostano** [comment]
Does OFN has a "kind of official" supported browsers list somewhere?

**Comment by daniellemoorhead** [comment]
Reopened this @lin-d-hop as @NickWeir63 has offered to test on IE on the PR #1425. If you'd rather keep it closed then feel free to reclose this plus the PR.

>Does OFN has a "kind of official" supported browsers list somewhere?

@enricostano not as far as I'm aware.

**Comment by RachL** [comment]
The new design has fixed this one 🎉
