### ISSUE TITLE
Customer Enterprise Search Logic

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1453]
When a customer user searches for an enterprise the existing logic gives some funny results.

When an enterprise exists that matches the input string, no distance results are shown. These are only shown when no name matches exist. 

Given that many, many enterprises have the name of the town in their enterprise name, this means that when searching a town you don't see all of the enterprises in that town unless no enterprise uses the town name.

**_Example:_**
![oxfordsearch](https://cloud.githubusercontent.com/assets/8669848/22925177/a587dcf8-f29f-11e6-9cec-0f3b3f3be133.png)

As 'Cultivate Oxfordshire Ltd' has Oxford in the name, a search for 'Oxford' does not show any of the other shops in Oxford. 

**_Proposal:_** 
Change so that distanceMatches are shown by default.
@oeoeaio @mkllnk @stveep @myriamboure Does this make sense to you? Do you think this be applied for all instances?

Ping @NickWeir63

**_Notes:_** 
app/assets/javascripts/darkswarm/controllers/enterprises_controller.js.coffee 
$scope.updateVisibleMatches
$scope.distanceMatchesShown

There is also some funny logic going on when you make closed enterprises visible as well... tbc...

**Comment by mkllnk** [comment]
Your proposal sounds logical to me. Is there any performance implication? Well, there are probably a lot of other performance issues on that site...

**Comment by lin-d-hop** [comment]
I suspect there are some performance issues. Ill include this in the investigations. Thanks @maikel 

⁣Sent from BlueMail ​

**Comment by jeronimo** [comment]
After a lot of investigation it appears there only one flag needed to be enabled to get results. There are no tests coverage so it is hard to define if attached behaviour is acceptable?

![screen shot 2017-03-24 at 09 41 30](https://cloud.githubusercontent.com/assets/88912/24289356/dadb0618-1078-11e7-9df1-4b753dbdf1eb.jpg)

Note: Performance should be fine with 50+ shops but might be an issue in the future with 300+ or so.

**Comment by Matt-Yorkley** [comment]
@jeronimo is this PR ready for testing/review? If you ping me or @lin-d-hop or someone from the UK team when you've finished a PR and it's ready, we can add it to the testing pipeline to move things along. :)

**Comment by lin-d-hop** [comment]
Hi @Matt-Yorkley, thanks for the ping on this! I've spoken to @jeronimo briefly about this one. It looks good but might benefit from some further improvements to UX as the current behaviour is very confusing.

@OliverUK Could you test that this fix works as expected. Could you also look at the way it currently works and make some suggestions about what would be more clear from a user perspective when using the search feature?

Also relevant:
https://github.com/openfoodfoundation/openfoodnetwork/issues/1382
https://github.com/openfoodfoundation/openfoodnetwork/issues/943

**Comment by OliverUK** [comment]
@lin-d-hop 
Sure. Is there a build for it?

I noticed on production that if I type Stroud, I only get enterprises with Stroud in the name but if I type Stroud+[space] I get all nearby enterprises. Of course we are all used to the Google-style search as you type and so we don't expect a space or return to make any difference. But in this case it does.

Personally I think the search as you type which we find all over OFN front and back makes some processes quite slow. Mistype anything in a product search in BEP and you have to wait for it to figure out it hasn't got your "fsteak" before you can delete your mistaken search term and hopefully you remember to highlight it and press delete rather than going backspace, as otherwise OFN will try and search for your "fstea" and your "fste" etc while you delete. But I realise no self-respecting developer will want to go back to "search after you hit return" because now that we can do search as you type, it feels so backward, right? ;)

To come back to the matter at hand though, it would solve the problem if no search took place until I hit return. Alternatively if typing a town name or part of it could yield the same result as doing so with a space after, that would also work. 

Generally it seems to work well. I can type Edinb and get results for Edinburgh.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Searching Logic (Oxford, space)](https://trello.com/c/mPoiy17B/43-searching-logic-oxford-space)

**Comment by lin-d-hop** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/discovery/1177
