### ISSUE TITLE
Upload and display organic certificates when clicking on the property

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1546]
As a producer / hub manager I want to be able to upload a PDF document when associating a property to a producer / product.
Today I can only write a description. Producers and hubs want to be fully transparent and upload the organic certificate.

### Producer vs product properties
Usually there is not one certificate per product, it's one document for a producer with the list of certified products. With a tool like https://smallpdf.com/ it's super easy to make one PDF document with whatever pictures or multiple PDF. So I propose to be able to **uplolad only one certificate document per producer per "certification" in the producer profile**, "properties", at the right of "description", add an "upload certificate button."
(sorry the button is really not nice ;))
![upload](https://cloud.githubusercontent.com/assets/8135376/25330053/85374c8e-28de-11e7-88af-1210d178d825.png)

If I add a property at the product level, which is not one already inherited from the producer, I can upload a file also there and the property and associated document is added to the producer properties.

### Display
Maybe we need in the same section a **set up button "display properties certificates in the producer profile and product description" (yes /no)**

On producer profile and product, today the tag for product categories and for properties already appears, but the strange thing is that when you go over the property tag with the mouse, the clickable hand appears, but there is nothing to click ! So it would be great to **be able to click the property and see the producer certificate associated to that property**. If there is no certificate, the clickable hand shouldn't appear.

**Comment by myriamboure** [comment]
@daniellemoorhead @sstead I'd like to move forward on that, it seems pretty intuitive and I don't think needs much debate, what do you think? Can I assign that to a dev so that we start on it ?
For me it's just a step one, I'll  create another issue later on to be able to add and display a label logo instead of the textual text when a logo is available for a label.

**Comment by sstead** [comment]
Sounds good Myriam, I have no opposition to this. I haven't heard from anyone is Australia requesting this feature, but it sounds like it's important in France :)

**Comment by myriamboure** [comment]
@lin-d-hop is it fine also for uk ? @ltrls is about to work on it now.

**Comment by myriamboure** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/issues/1770 should be fixed as well when dealing with this issue

**Comment by sstead** [comment]
@myriamboure just trying to clarify with screenshots below.. 

Currently the only place that the 'Property Description' shows is when you hover your mouse over the Property button, in the Product modal. See below. Are you suggesting that hovering will show the description text, and if I click, another modal will open with the uploaded document? Or maybe the document will open in another tab?
![image](https://user-images.githubusercontent.com/10843056/30890795-6656d988-a372-11e7-8515-9cc449fbe19b.png)
If the Property has no description or document, hovering or clicking will just show 'no descripton'?

**In shops (either hub or producer shops)**
Are you proposing we make the buttons in the producer profile modal clickable (see below)? This modal appears if the user clicks the producer name below a product, or from the top 'producers' tab. But again, where will the document open? A modal within a modal is not ideal, so perhaps a new tab?
![image](https://user-images.githubusercontent.com/10843056/30890987-aaa73866-a373-11e7-8c63-8cdfad867c17.png)

**On the producer directory* 
Will the Property button show the description (if mouse hovers) and show the uploaded document (if user clicks on button)? (will document open in another modal, or another tab?)
![image](https://user-images.githubusercontent.com/10843056/30890896-113a3200-a373-11e7-9105-006a7ae1f79b.png)

**On the map directory**
Property buttons for producers could be hoverable/clickable... (will document open in another modal, or another tab?)
![image](https://user-images.githubusercontent.com/10843056/30891161-c7f33ce8-a374-11e7-877d-4694857a5418.png)

Property buttons for hubs can't be clickable, because that property may encompass multiple producers.
![image](https://user-images.githubusercontent.com/10843056/30891135-91be1dfa-a374-11e7-94a8-95105f5c9599.png)

**In the shops directory**
I would suggest that in the shops directory the buttons are not hoverable/clickable. As above, the producer shops could reliably display a description, but the hub shops could not (as there might be >1 producer with the property). So best to be consistent and not make any interactive.
![image](https://user-images.githubusercontent.com/10843056/30891230-42045b52-a375-11e7-9555-9d94c1fd2140.png)

**Comment by myriamboure** [comment]
Wahou, that's a precise specification @sstead you are my Master Yoda :-)
I agree that it's best to open in any case the certification document in another tab, that will be clearer.
I agree basically on all what you suggest, on producers related modals, hover shows description and click open new tab with document (is document available, if not, not clickable). On hubs modals, not hoverable/clickable.

So I suggest we work on that first and then see how we can improve the Product modal UX in issue https://github.com/openfoodfoundation/openfoodnetwork/issues/1770 if that's ok with you...

**Comment by sstead** [comment]
Sounds good!

**Comment by myriamboure** [comment]
Closing for now as the icebox item is created, hope we'll be able to move that forward quickly :-( https://community.openfoodnetwork.org/t/upload-and-display-organic-certificates-when-clicking-on-the-property/1145
