### ISSUE TITLE
Enterprise Edit page doesn't activate update button properly

### ISSUE THREAD

**Issue by kothagunda** [openfoodfoundation/openfoodnetwork#1719]
## Description
When i edit an Enterprise, the update button doesn't get enabled when i edit the text in a text box of a field. Only after i click another field, or some other part of the page,  the update button gets enabled, so that i can click and update(save).

## Expected Behavior
Update button activates when user starts typing in the field.

## Actual Behavior
If you modify some text field, you need then to click off the field, which then activates the update button.

## Steps to Reproduce
1.In enterprise menu, start modifying a text field, you see the upate button is not activated.
2. Click off the field, it activates

## Animated Gif/Screenshot
https://www.useloom.com/share/0c38cf471e874807b8bab80eeb768629

## Severity
S3 - All users are impacted, it doens't prevent to use the platform but is pretty annoying on a UX prospective.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by daniellemoorhead** [comment]
Current functionality: click off the field, which then activates the update button.

Expected: update button activates when user starts typing in the field.

**Comment by RachL** [comment]
I just tested this. Indeed if you type in the "name" field", you have to get out of the field so that the button activates. However on the description field, the button is activated directly.

As there is a workaround and that I think the cases where the name field will be updated without the description field, I'm downgrading this to bug-s4: it's annoying, but you can use it. If you don't agree shout out :-)

**Comment by lin-d-hop** [comment]
Closing as this UX bug hasnt actually prevented any users from updating details.
