### ISSUE TITLE
Paperclip attachments location

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1774]
After deploying the last release of OFN to our production environment https://alpha.katuma.org we discovered that all the images created by the users were gone. The links were broken and were pointing to non existent directories under `/public/images/enterprises`.

We discovered that in the models with Paperclip attachments we are specifying a `path` to `/public/images`: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/enterprise.rb#L55

As per Paperclip [documentation](https://github.com/thoughtbot/paperclip/tree/v3.5.4#understanding-storage) by default all the attachments are stored under `/public/system`, a folder that should be a symlink to `/shared/system` directory.

This is correctly covered in our `ofn_install` Ansible scripts [here](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/app/tasks/main.yml#L16) and [here](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/deploy/tasks/main.yml#L50).

But since we store our Paperclip attachments in `public/images`, that is not a symlink to `/shared`, we'll loose its content at every deploy.

#### Questions:
1. Why did we use `public/images` instead of the standard `public/system` directory?
2. I noticed that in the AUS staging1 server we actually store the attachments in `/public/system`.... How is that achieved since the code says otherwise? Is the same in AUS production?
3. What should we do? I created a [PR](https://github.com/openfoodfoundation/ofn-install/pull/75) to add a `/shared/images` directory in `ofn-install` repo, but I'm wondering if we should address this issue once and for all moving back to the Paperclip's default `/public/system`.
4. How many instances use File Storage instead of S3 or other provider?

cc/ @pmackay @mkllnk

**Comment by sigmundpetersen** [comment]
Scandinavia use S3

**Comment by kirstenalarsen** [comment]
I believe Aus also uses S3 . . or something other than paperclip . . @mkllnk @RohanM  @oeoeaio ?

**Comment by mkllnk** [comment]
Yes, we use S3.

@kirstenalarsen paperclip is the software that allows us to store the images on S3 or locally, depending on the configuration.

**Comment by mkllnk** [comment]
@enricostano Why do you loose the content? Does the `public` directory get emptied on deploy? Are you using `ofn-install` for deploys?

The ofn-install scripts seem to assume that images are stored in `system`. The last change of this was by Rohan three years ago. I guess we didn't notice that this was broken since we use S3.

So your PR makes sure that local images are stored in the shared folder, right? Do you have any idea how to transition to Paperclip's default? If we just change the path, we would break all existing instances, right?

**Comment by mkllnk** [comment]
@enricostano 
> I noticed that in the AUS staging1 server we actually store the attachments in /public/system.... How is that achieved since the code says otherwise? Is the same in AUS production?

I think it is a setting in the database. We also had a weird thing that staging1 was access the S3 bucket of staging2. Same setting in Aus production. But I haven't really looked into the code to find out the details.

**Comment by sauloperez** [comment]
> Does the public directory get emptied on deploy?

Nope. The problem is that the content uploaded on a previous release's public images folder (something like `releases/<timestamp_of_the_deploy>/public/images`) is not available to any new release so, image URLs are then broken.

> Are you using ofn-install for deploys?

Yes, we do

> The ofn-install scripts seem to assume that images are stored in `system`

Unfortunately, we configure `public/images` in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/enterprise.rb#L55

That is why as @enricostano says in https://github.com/openfoodfoundation/ofn-install/pull/75 "We need to add /shared/images directory to store Paperclip attachments and keep them across releases." so files in `public/images` will also be shared across releases.

**Comment by enricostano** [comment]
I merged https://github.com/openfoodfoundation/ofn-install/pull/75, we can close this issue for now. Thanks for the feedback!
