### ISSUE TITLE
Improve the Edit/New Variant Screen

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1805]
As noted by @sstead on #1741:

I've had another user get confused in the Edit Product area. Specifically she was trying to add variants... see image below with suggestion for how to improve...
Note there are 2 places to add variants- 1) in the bulk product edit area, by expanding the table and clicking the + symbol on the left. 2) in edit product - product variants. We want to model method 2 off the fields in method 1.

![image](https://user-images.githubusercontent.com/10843056/29955334-3a2899d2-8f22-11e7-8423-300531cd7cb5.png)

To do:
- [ ] Hide cost price, height, width, and depth. (these fields aren't used in OFN, so can be hidden).
- [ ] Model the Weight (existing) Unit Description (existing) and Display As (new) off the way these fields display in +New Product interface. As illustrate above. Note difference in how Items are displayed compared to other unit types (kg, L, mL)
- [ ] If possible make the arrangement more table-like - as we see in the Bulk Edit Product area (in pic above). Or have the layout similar to +New Product (below). A familiar layout will be less confusing to users, but this isn't essential.
![image](https://user-images.githubusercontent.com/10843056/29955285-f4823b0e-8f21-11e7-84be-b9615b55a8b6.png)

**Comment by myriamboure** [comment]
Just wondering, it seemed to me that Spree upgrade would improve a lot the product / variant interface, shouldn't we focus on getting the upgrade up and running ? Just fear that we might destroy the work done very quickly ;) Ping @enricostano 

I don't agree with hiding the  height, width, and depth field @daniellemoorhead actually we are in discussion in France with various big users (including GLP) and they would need information on the total weight and volume for the products to be shipped so that they can organize efficiently the transport (transports are negotiated by total volume and weight) so we will soon need those fields and even develop aggregation tools at the OC level on those fields.

Question : what was the "cost" field designed for ? It seems it was designed the other way around compared to what OFN does, the hub would put in master price how much he sells and in cost how much he buys... so yes with the OFN design I guess it sounds useless. Then we should also remove the "cost" field from reports, it is in some locations and that is pretty confusing as well for users.

**Comment by enricostano** [comment]
cc/ @sseerrggii @sauloperez @mllocs

**Comment by sauloperez** [comment]
> Just wondering, it seemed to me that Spree upgrade would improve a lot the product / variant interface, shouldn't we focus on getting the upgrade up and running ? Just fear that we might destroy the work done very quickly ;)

absolutely, but yes, I also think we need to improve this screen. It is an issue that showed up in the user interviews that we did so far in Katuma.

**Comment by daniellemoorhead** [comment]
@myriamboure this is actually added by @sstead onto a different issue that was being worked on. I just created a new issue for it (she's away) so that it didn't get lost as it won't get done as part of the other issue. So best to direct thoughts to her, it was her idea 🙂

**Comment by luisramos0** [comment]
ping @RachL @lin-d-hop : @HugsDaniel is bringing this variant edit page from spree_backend here #4078 
Maybe a good time to make some of these fixes?

I am not sure what's the status of the request. remove cost_price for example?

**Comment by RachL** [comment]
@luisramos0 @HugsDaniel 

1. Cost price: there has been some controversy in slack regarding cost price https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1557146918008600?thread_ts=1557146918.008600 

It might be more widely used than we think it is. I wouldn't remove it for now. I feel like it is best if the community takes the time to think about it.

2. Can we check in databases if height, width, and depth are used? If not yes, let's remove them.

3. Placeholders: yes, they never hurt :)

4. About the layout, I wouldn't change the layout to match the new product one. I'm not a big fan of the layout for new product. I believe it would be more interesting to tackle this with a new layout that would fit both cases and also be more responsive. So I would leave this for later.

But that's just my opinion :)

**Comment by luisramos0** [comment]
re width and height, in FR live we have around 20 variants using it.

otherwise, we are saying we will ignore this issue for now and we just do #3793

**Comment by RachL** [comment]
@luisramos0 yes I have the feeling this issue needs some product work and more data. What if other instances are using width and height more widely?

**Comment by RachL** [comment]
We are discussing this in the #network channel, and I believe network rewamp will cover all those issues. In any case it won't be a papercut, so I'm closing this here.
