### ISSUE TITLE
 Enable different fees to be charged based on tag used

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1824]
waiting for agreement on the spec here before detailing https://community.openfoodnetwork.org/t/enable-different-fees-to-be-charged-based-on-tag-used/1054

**Comment by myriamboure** [comment]
It seems that Sally validates our approach, so I sum up here the spec (= option 1 in [this post](https://community.openfoodnetwork.org/t/enable-different-fees-to-be-charged-based-on-tag-used/1054/7?u=myriamboure) of the discussion) :

Following the "default rule" and "tag rule" logic, we need :

- [ ]  **to be able to tag an enterprise fee: add a column "tag" in the "enterprise fee" table**, like the one already in the "inventory table" for instance. [There are some display issue on the entreprise fee table, we can't see the name when typing it, but I'll treat that in a separate issue, low priority)
![screenshot from 2017-10-06 16-51-47](https://user-images.githubusercontent.com/8135376/31283871-24121082-aab7-11e7-93aa-afe5d0195efc.png)
![screenshot from 2017-10-06 16-53-30](https://user-images.githubusercontent.com/8135376/31283879-31530954-aab7-11e7-9e28-9a0db46be34b.png)

- [ ] **create the rule that makes it possible to tell if customer and entreprise fee as the same tag, if this tag, entreprise fee is "applicable" or "non applicable"**

![discount tag](https://user-images.githubusercontent.com/8135376/31284174-1ef1eed2-aab8-11e7-96c8-1cd13692d454.jpg)
![fee2](https://user-images.githubusercontent.com/8135376/31284183-24e10d00-aab8-11e7-854b-c0f734750912.jpg)

- [ ] and of course make sure that the rule works well, and the calculation are happening properly with the good entreprise fees baing charged according to the good tag of the customer :-)

**Things to check:**
> make sure we can create mutiple tag rules on the same tags and type base (I think it should be ok logically)
> if a user tag is removed later on, we need to make sure it doesn't change the history in the past orders... I guess that's ok but just to keep in mind. And useful for testing notes ;-)

**Comment by myriamboure** [comment]
Ok so following the discourse discussion I specified the work to do. Please @kirstenalarsen or @oeoeaio if you have anything to add on that go ahead, we want to launch asap, for our big cooperative food hub that we love :-)

**Comment by myriamboure** [comment]
Precision: the tag rule concerns any enterprise fee, whether it be at coordinator, incoming or outgoing level.

**Comment by oeoeaio** [comment]
Sorry for my slow response @myriamboure. I must have missed the previous notification email.

I haven't done any deep investigation into this, but my first thought is that applying fees to products based on a customer tag will require a different approach to loading product information into the shop. At the moment, price information is cached along with all other product information, so that large numbers of products can be loaded quickly into the shop. If we want to change product prices based on the tags that have been applied to the customer, then we will need to regenerate prices for all products each time the shop is loaded. As I said, I haven't investigated this thoroughly, but I think this part is likely to be the most difficult component of the work.

**Comment by myriamboure** [comment]
Thanks @oeoeaio for your comments, I guess we should be cautious in not increasing the loading time through that process. We'll investigate first on that.

**Comment by myriamboure** [comment]
Closing as Icebox item created : https://community.openfoodnetwork.org/t/a-product-can-have-multiple-prices/1148
