### ISSUE TITLE
Scroll bar disabled on mobile view of map profiles

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1834]
When the browser window is small, the scroll bar for longer profiles, viewed from the map, doesn't function.

![image](https://user-images.githubusercontent.com/10843056/30464723-9ec58c34-9a16-11e7-92c5-1bd3d7e7d789.png)

**Comment by g33kyshivam** [comment]
Hey, I would love to work on this issue!

**Comment by sauloperez** [comment]
Sure @g33kyshivam. All yours

**Comment by g33kyshivam** [comment]
I am unable to run "bundle install". When I set the ruby version to 2.1.5 as per the requirement , run the bundle install , it throws this message, "rbenv: bundler: command not found". Please help @sauloperez

**Comment by sauloperez** [comment]
do have `bundler` installed? Run `gem install bundler` and then try again.

**Comment by g33kyshivam** [comment]
Yeah , it works ! Thanks for helping @sauloperez .Working on the issue

**Comment by g33kyshivam** [comment]
Hey @sauloperez , I m facing a issue while installing the gems, there is a long error message. Please help. This is my first time, contributing to a rails project

**Comment by g33kyshivam** [comment]
this was the log-->
/home/g33kyshivam/.rbenv/versions/2.1.5/bin/ruby extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/g33kyshivam/.rbenv/versions/2.1.5/bin/ruby
	--with-pg
	--without-pg
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config

extconf failed, exit code 1

**Comment by sauloperez** [comment]
can you please share the command you ran and the full log? https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Ubuntu or any of the other seutp guides might be of help

**Comment by myriamboure** [comment]
Closing for now as part of icebox: https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244 and we have lots of good first issue, we wil reopen when the icebox move forwards.
