### ISSUE TITLE
Allow producer to manage a hub's inventory

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1859]
Use case :  a producer wants to limit the stock allowed to a given hub. Today the producer can't access the hub inventory to set up himself the stock available for this hub.
Can we add an entreprise relationship that says:
"hub X" autorizes "producer Y" to manage inventory ? and in that case the producer can access and overrides his own products information in the hub inventory ?
Is there today any other way to do that ?
Ping @sstead @enricostano @sauloperez

**Comment by sauloperez** [comment]
Sorry, I completely unaware of how enterprise relationships work, but I can't think of another way :thinking:

**Comment by sstead** [comment]
I agree that this would be a very useful feature. It would be handy our Prom Coast food hub, and others using a model where producers update their own stock details. @oeoeaio and I thought this through breifly, and he's what we think...

Using the 'permission to add to inventory' E2E backwards could be problematic for Producer Hubs. It would only work where it's clearly a 'hub only' giving a 'producer only' permission, if there's producer hubs it would get confused.

Rob suggests that eventually, when we have 'inventory 2.0' this kind of permission would be managed at an inventory level, not at an enterprise level. Therefore he's happy to begin this transition, and house this particular permission within the Inventory tab, rather than adding another to the Ent Relationship page

**Suggested layout for the hub**
![image](https://user-images.githubusercontent.com/10843056/30892121-30b3ca86-a37a-11e7-8db6-e3934a137418.png)
![image](https://user-images.githubusercontent.com/10843056/30892129-3972a570-a37a-11e7-9183-7d95da321949.png)

**Producer view**
When the producer goes to Inventory, they will be able to select the hub that they supply to who has given them permission to edit Inventory.
- they will only see the inventory list, not the New or Hidden lists
- they will only see their products

How does this sound?

**Comment by myriamboure** [comment]
> Using the 'permission to add to inventory' E2E backwards could be problematic for Producer Hubs. It would only work where it's clearly a 'hub only' giving a 'producer only' permission, if there's producer hubs it would get confused.
@sstead can you explain more ?
I don't get that point... 
If hub 1 is a producer 1 but in his hub, sells also products from producer 2
If he grants persmission to producer 2 to manager inventory, producer 2 will only be able to see his own products in hub 1's inventory.
What is the issue ? Thanks for this clarification ;-)

**Comment by sstead** [comment]
The current logic for permission to add to Inventory:
- If a producer grants permission to a Hub, that Hub can override the producer's product details in Inventory.

Proposed new permission logic:
- If a hub grants permission to a producer, that producer can see their items in the hub's inventory and edit details without needing to be a manager of the hub. 

The above logic breaks if:
- A Producer Hub (A) grants permission to another Producer Hub (B).
There are 2 possible interpretations:
1) The system may interpret that A is supplying B, and that A wants to allow B to override their product details in Shop B's Inventory. 
Or...
2) The system may interpret that A is a shop getting supplies from B, and that A is allowing the producer B to manage their products in shop A's inventory.

This is a rare case, but in this scenario, the logic would not know which permission was intended and would probably give both permissions.

I don't think this conflict was Rob's whole reason for preferring to house this permission in Inventory, rather than in Relationships. I think he had other reasons relating to the future of Inventory, when we transition to having multiple inventory lists. @oeoeaio might care to comment...

**Comment by myriamboure** [comment]
@augnustin @enricostano @sauloperez  I heard this morning that the future versions of spree was handling inventory much better, but when I look at https://guides.spreecommerce.org/user/configuring_inventory.html I have the impression they use inventory for something pretty different than us.
More for "stock" management, movements of stock and stock location, but I think we changed quite a lot the spree logic with enable a "hub" to have it's own "catalog" (=inventory) by importing producers catalogs and overriding certain information. I guess all those permission things would anyway be something added by OFN on to of Spree, so not so much Spree dependant ?

I don't get the technical constraint in the Producer Hub A / Producer Hub B case (if one give a permission to the other we know which one has which permission ?) but it's probably too technical to me, in the way it's coded so I just trust @oeoeaio ;-)

What you propose sounds ok to me, it seems pretty easy to use. I'm just wondering if that's not a bit confusing to manage some permissions in "entreprise relationships" and some other in other tabs, but I think as soon as it's clearly explained in the user guide and just a one time set up one or the other can work. So happy to follow your proposal if that makes sense to the Spree guys ;-)

**Comment by oeoeaio** [comment]
Hi @myriamboure. Me again. Can you tell I'm catching up on my emails? :)

The issue isn't super technical, it's just that there is no way to use the existing 'inventory' permission to allow the existing functionality AND the new functionality independently of each other. By reusing the existing permission, there are scenarios where both the existing and new meaning of the permission would be applied, with no way to  separate them, or determine the intention of enterprise that granted the permission. Sally has provided the main example that we could think of where an existing relationship that granted 'inventory' permission would have a new meaning (that the granting enterprise may not be aware of) if we add the new functionality to the same permission.

With regard to the location of the interface: I agree that it is confusing to have permissions in two different places. I was thinking about the future (that I hope we will get to) where shops can have multiple inventories for different uses, and they might want to apply different permissions to them, however we can just make that change when we actually need to. Generally a bad idea to design software in anticipation of some potential future change. So, how about we just create a new permission that describes the ability to make changes to one's own products in another enterprise's inventory? Sorry to keep changing my mind!

**Comment by myriamboure** [comment]
Yes @oeoeaio you are catching up, thanks :+1: 

My initial suggestion was not to use the existing inventory permission but as you say, create a new one that we can call "manage inventory" so we would have 2 different permissions:
- add to inventory: a producer allows a hub to add the producers' products to his inventory
- manage his own products in inventory: a hub allows a producer to manage his products details in the hub's inventory (=ability to make changes to one's own products in another enterprise's inventory)

I suggest as you say that we don't anticipate too much the future and go for the easier way to meet our current need. Happy that you changed your mind, that will make this job easier :-)
Are the two descriptions ok ? Any  other wording suggestion @sstead ?

**Comment by myriamboure** [comment]
Closing for now, icebox item created, waiting to be prioritized https://community.openfoodnetwork.org/t/enable-product-chain-tracking-hubs-variants-creation/1152
