### ISSUE TITLE
Enable sorting by producer in shopfront 

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1861]
## Description
**- As a:** enterprise user and super admin
**- On page:** admin/enterprises/ENTERPRISENAME/edit#/shop_preferences
**- I want to be able to do:** to order the products in the shopfront by producer.

I propose to change a bit the shopfront ordering options, by creating another option ordering (either by category OR by producer).

The producer list available can be from those with whom the hub has a permission to add to order cycle.
![shopfront ordering](https://user-images.githubusercontent.com/8135376/30855124-1f91c580-a2b4-11e7-9c6f-74e0842b7e47.jpg)

## Acceptance Tests
1. I can login as an enterprise user or an admin
2. I can go on the enterprise settings and select "shop preferences"
3. The new producer field now allows me to select producer as well and I can drag & drop to change the order.
4. For this first iteration I can either use the category field OR the producer field. Not both. (Except if it is really easy on the tech site).
5. Once I save, I can see that the order is correct on the shopfront.

EDIT Made on April 2019 by @RachL to put the issue inside a template.

**Comment by sstead** [comment]
I love this idea!

**Comment by myriamboure** [comment]
@augnustin seems like I can @ now ;-) If you would like that issue could be something you could work on to get your hand into OFN, I don't think it's over complex, but still will help you understand some complexity of the software. Cheers :-)

**Comment by enricostano** [comment]
@sseerrggii @sauloperez this is something that we'll need in a near future too, right?

**Comment by lin-d-hop** [comment]
This is also asked for in the UK. I think we should go for it :-)

**Comment by sauloperez** [comment]
I guess so @enricostano

**Comment by myriamboure** [comment]
Please feel free to pick it up if you know someone who can work on it ;) Else we have it in the French pipeline but might not be the first we pick.

**Comment by myriamboure** [comment]
#gitcull2017
https://community.openfoodnetwork.org/t/enable-shopfront-ordering-by-producer/1161

**Comment by luisramos0** [comment]
I dont think this is a good-first-issue 🤕 it's not too difficult but involves changing haml, controllers, creating an angular directive and changing the shopfront product query...
It's an interesting issue though good-interesting-issue :-)
I'd say this is a M.

@jasonk357 pinged me about this issue on slack. I am pasting here some useful hints for whoever picks this up:
- on app/views/admin/enterprises/form/_shop_preferences.html.haml we have the html where we will need to add the producer part below the existing category part
- the category part names are shopfront_category_ordering that becomes enterprise_preferred_shopfront_taxon_order
- shopfront_taxon_order is a preference in the Enterprise model
- in angular the category list if built with the directive ofn-taxon-autocomplete which is in app/assets/javascripts/admin/taxons/directives/taxon_autocomplete.js.coffee
- in terms of data model, it’s important to know that Product category is one taxonomy and so each category is a Taxon (this is the main taxonomy in the system, but there are/could be others)
- but anyway, the list of producers that we need to add is not a taxonomy, it will be a list of producers, and producers are enterprises
- so we need to build a new directive that instead of taxons handles producers (producers are available in Enterprise through the scope :is_primary_producer)
- then you need to change the shopfront product query to filter by these producers. the product query is in lib/open_food_network/products_renderer.rb#taxon_order

**Comment by kirstenalarsen** [comment]
I am adding this to Welcome New Developers as a trickier one useful for someone wanting to demonstrate skills

**Comment by kirstenalarsen** [comment]
Lots of requests for this in Australia with rapid onboarding of farmers' markets

**Comment by Erioldoesdesign** [comment]
Just dropping in here that I love this issue and can see why it's highly requested. From w UX/UI pov I think what Myriam suggested works fine and is logical.

I wonder how Shopify enables users setting up stores to 'configure' their stores and make them 'their own'.

From a shopper-user perspective, I wonder if there are expectations on hubs with multiple producers to, when sorted by producer, to have a visual difference of some kind, imagine if a real or market place each stall has there own banner, chalkboard and table cloth, do shopper-users expect something from the digital perspective? It's beyond the scope of the tech on this issue but would make for an 'joyful' shopping experience.

**Comment by guidoDutra** [comment]
Hello, I've been working on this issue, can I get is assigned to me?

**Comment by guidoDutra** [comment]
Hello, I opened a draft PR for this issue, but I'm stuck with a particular issue related to data injection. I [made a post](https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1622460380082500) in the slack dev channel about it. Any help is appreciated :)
Btw @luisramos0 I've been following your hints that were posted above, so let me know if you can advise

**Comment by guidoDutra** [comment]
Just updated the PR, I managed to inject the list of suppliers. The only thing missing now is to filter the suppliers per those with whom the hub has a permission to add to order cycle. Once I figure that out I'll open the PR

I'm not sure my solution is appropriate, so I'll be waiting for some feedback as well

**Comment by kirstenalarsen** [comment]
would it be better to filter by producers that are actually included in the order cycle than those hub has permission for? The former list will remove those that would return an empty result i.e. the Hub often has permission to add many more producers than actually have products available / included in the current order cycle. I think better UX to just include those that will bring up active result. I'll repost this comment on the issue  . .
