### ISSUE TITLE
[Spree 2 Upgrade] Replace Order#shipping_method with Order#shipments 

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2009]
`Order#shipping_method` is gone in Spree 2.0, so any line of code that uses it in OFN will fail. We can provide the same behaviour but being spree-2.0 compatible without having to wait for a specific spree-2.0 branch :metal:

The work has already been started in: https://github.com/openfoodfoundation/openfoodnetwork/pull/1651

**Comment by sauloperez** [comment]
It might to big of a PR to get all this done in one shot. Let's first investigate, post the outcomes and then we decide. We could create individual issues for each them and fix them bit by bit.

**Comment by luisramos0** [comment]
Note from #2523 - when removing line items from a completed/finalised order, the shipments/stock_locations are updated in the order.contents.remove_variant method. This needs to be adapted. See #2523 for more details.

**Comment by luisramos0** [comment]
Actions from my investigation:
- I have created an issue to handle the setting of order.shipping_method (shipping_method=) #2662 
- I have created PRs to implement adapters to both order.shipping_method and order.shipping_method= (respectively #2654 and #2669 )
- I have created issues and respective PRs to fix specs broken with errors related to this change (order spec issue #2664 and PR #2668 and adjustment_spec issue #2665 and PR #2670 )
- I have created an issue and PR to adapt last_used_ship_address in Address Finder #2663 and PR 2667
I have created separate items to keep all issues focused and all PRs small.

I am requesting the validation of the approach for #2654 (and #2669) [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/2654#issuecomment-419717043).

**Comment by daniellemoorhead** [comment]
Hey @luisramos0 the PR attached to this issue is merged, yet this is still in the code review column...can it be closed, or are you waiting on #2662 to be merged before it's done? 

If you're waiting, then suggest disconnecting #2654 and connecting #2662 instead. Or, if as it says in #2654 that it closes #2009 then go right ahead and close this 😄

**Comment by luisramos0** [comment]
Thanks for the heads up @daniellemoorhead 

I disconnected this from #2654 , 2654 is starting but not closing this one.

There's more work to be done and it's not just 2662. Actually 2662 may not be necessary.

What's still not done in this issue is to go through all the changes in the original PR #1651 and see what's still valid. This issue acceptance criteria is the absence of errors related to order#shipping_method.

**Comment by luisramos0** [comment]
Ok, so I have reviewed everything in #1651 and created separate issues. Mostly around order.shipping_method_id and not order.shipping_method.
Issues created: #2678, #2679, #2681, #2682, #2683 and #2684  🎉 

What remains to be done as part of this issue is to fix the order_spec.
I changed my mind. For clarity I am closing this one. I have opened #2685 to fix the fee calculations in the order_spec.
