### ISSUE TITLE
Understand how variant's count_on_hand data migration works

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2012]
Spree data migration by default would create only one Stock Location for all the Enterprises and create a Stock Item for each Variant.

In this way we end up we all the stock information for all the Enterprises in one place.

Is this is OK as a first iteration? This will need a big data migration in the future if we want to offer Stock Locations for each Enterprise.

**Comment by sauloperez** [comment]
https://github.com/spree/spree/commit/2c48bfbaad98b8af35a5e95ba268a057c6973b47 is the migration we're talking about.

**Comment by sauloperez** [comment]
It does feel like the appropriate step for a 1st iteration but this also means that, if Spree v2.0.0 updates the frontend to allow for stock location creation, we should diverge and stick to our current frontend to hide such option. This way we could postpone the effort of making StockLocations work with our Enterprises.

**Comment by sauloperez** [comment]
The stock location admin page was introduced in https://github.com/spree/spree/commit/129d27f9615d0614b5cfc64f57522d9352c325d1

**Comment by sauloperez** [comment]
This is how it looks like. A new item added at the bottom of the product admin page.

![stock](https://user-images.githubusercontent.com/762088/37719247-dd550154-2d24-11e8-8435-604f6db954ca.png)

**Comment by myriamboure** [comment]
Sounds cool! I'm looking forward to see that happening I'm sure some hubs will be very happy to be able to manage "deported stock" :-) I understand it will be step 2 but we definitely want to offer that to our users :-) Spree 2.0 come come come!

**Comment by sauloperez** [comment]
I'm not sure how close we are to that step 2 @myriamboure :trollface:

**Comment by sauloperez** [comment]
The latest Spree migration we have in OFN is `20180405114604_drop_products_count_on_hand.spree.rb`, which belongs to `dc775dbeb` commit. From that one onwards are still to be brought to the app.

**Comment by mkllnk** [comment]
I'm looking at this now as well. Just summarising here:

- Status Quo: Every variant has exactly one `count_on_hand` value.
- After Spree 2.0 migrations: Every variant has one `count_on_hand` value via `StockItem` at the `default` location. This data model is completely backwards compatible and reversible.
- Possible with Spree 2.0: Creating more stock locations so that each variant can have a `count_on_hand` value at each stock location.

As @sauloperez said, the minimal effort would be to hide the possibility of creating multiple stock locations and use the new model exactly how we used the old model. Enabling the use of multiple stock locations is an option we can consider later. It could make one use of our variant overrides obsolete. But we should really see where we want to go with the network feature and how this fits into there.

**Comment by sauloperez** [comment]
Before closing this I should

- [ ] Add the outcome of the spike to https://github.com/openfoodfoundation/openfoodnetwork/wiki/Spree-Upgrade-Themes
