### ISSUE TITLE
Refactor uses of spree_variants.count_on_hand

### ISSUE THREAD

**Issue by oeoeaio** [openfoodfoundation/openfoodnetwork#2014]
`VariantOverride` is particularly coupled to this column, but we should be able to override the new `variant.total_on_hand` method instead of `variant.count_on_hand` to achieve the same result. This is a bandaid solution but a longer term solution to this issue will likely appear out of Networked Products discussions.

**Comment by sauloperez** [comment]
As per the investigation done in https://github.com/openfoodfoundation/openfoodnetwork/pull/2183, we can't get rid of `spree_products.count_on_hand` yet as removing it requires removing `spree_variants.count_on_hand` as well. They depend on each other.

As shown in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/spree/product_decorator.rb#L257-L271, `#save_master` triggers Spree's `#recalculate_product_on_hand`, which indeed updates said column on the `spree_products` table.

**Comment by mkllnk** [comment]
`Spree::Variant` decorator

- `scope :in_stock`: Not on Spree's model. Plenty of use of method `in_stock?`, but no use of the scope `in_stock`.

`VariantOverride`

- It has its own `count_on_hand` value. If this value is present, it uses it for stock management. Otherwise it expects that it's not used for stock. `increment_stock!` will intentionally raise an error instead of using the variant's `count_on_hand` value.

More uses of `count_on_hand`:

- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/models/product_import/entry_processor.rb#L69-L74
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/models/product_import/entry_processor.rb#L196-L198
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/models/product_import/entry_validator.rb#L265-L271
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/serializers/api/variant_serializer.rb#L2
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/services/order_factory.rb#L46
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/views/shop/products/_form.html.haml#L34
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/views/spree/admin/variants/_autocomplete.js.erb#L19
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/app/views/spree/admin/variants/search.rabl#L5
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/lib/open_food_network/products_and_inventory_report_base.rb#L41
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/lib/open_food_network/scope_variant_to_hub.rb#L25
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/lib/open_food_network/scope_variant_to_hub.rb#L43-L47
- https://github.com/openfoodfoundation/openfoodnetwork/blob/eb9064f5be3433ed72f708c32bccbaa635a2988d/lib/open_food_network/scope_variant_to_hub.rb#L51-L55
- Lots of specs

I think we should address one area at a time.

**Comment by mkllnk** [comment]
After reviewing all uses again, I found that #2575 is the only issue left to do. That should solve all listed issues. Closing this one.
