### ISSUE TITLE
Translation missing on "modify address" pop-in

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2056]
## Steps to Reproduce
1. Go to "customers", select a shop, the customer lists dispay. You have the possibility to modify the shipping and billing address for a customer.
2. Click on one of those addresses to modify it.
3. You see the fields are not translated.

## Animated Gif/Screenshot
![screenshot from 2018-01-29 15-10-32](https://user-images.githubusercontent.com/8135376/35515281-0adb0f68-0509-11e8-8da5-5a8c69320fc0.png)

## Severity
3

**Comment by sstead** [comment]
yes, this is a problem on Aus production too. @sauloperez @enricostano 

![image](https://user-images.githubusercontent.com/10843056/35897467-766be4d8-0c15-11e8-90f9-c6c59cd12e8b.png)

**Comment by mjal** [comment]
We only have Australian states in database now
I have a [pull request](https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mjal:2057states-are-not-displayed-in-modify-address-pop-in-and-prevent-saving) ready for this one but it only covers French states. If we do it this way, we may also add states for other countries.
Spree uses [carmen](https://github.com/carmen-ruby/carmen) since 2.4, so a spree upgrade will also solve this issue.
Should I submit the pull request anyway ?

**Comment by enricostano** [comment]
Is this a regression? Was working before?

**Comment by myriamboure** [comment]
I think it never worked... as far as I know was never translated on the french instance.
