### ISSUE TITLE
Fix reports accessibility issue

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2099]
## Description
As part of the defined 2018 roadmap the product curation team has selected as a priority for Q1 in the "Make what we have great!" goal to fix the accessibility issue people have on existing reports.
This epic might need an inception session to confirm the feature candidate and so that one or more stories (issues) can be created and associated.

## Feature candidate
- First one is "remove default filtering and don't load the report before filtering options are set"
It seems that won't solve the timeout issue (https://www.useloom.com/share/d7d6c0f263cb42a48e839743edba3551) so I propose to organize an inception session to make sure we agree on the best feature candidate to solve the problem, before we detail the stories.

## Metric
The proposed metric to measure if we the need we focus one has been satisfied is:
- people who are on a broadband network and trying to get max one year activity data don't experience timeout.

## Icebox item
Existing reports are accessible for all users (https://community.openfoodnetwork.org/t/improve-reports-performance-to-ensure-they-are-accessible-for-all-users/1196/2)

**Comment by myriamboure** [comment]
2h spike time-boxed on this to start with by @mkllnk then we'll see if we need an inception to decide together what we do.

**Comment by mkllnk** [comment]
Okay, I spent 2.5 hours on this and basically found two things.

Since we are talking about performance here, a benchmark would be helpful.
I just loaded the normal orders and fulfillment report as super admin on the
Australian instance. It took 1m42s. That is pretty bad.

### limit search

The first idea is to not load the reports until filter criteria are set. This is very easy to implement.
One benefit is that they don't have to wait until they can set the search
criteria. The other one is that it enables people to load only one week or one day at a time which should
speed it up. Let's test this.

Dates: 2018-03-01 00:00:00 +1100 - 2018-03-07 00:00:00 +1100
7 days loaded in 1m18s

Dates: 2018-03-01 00:00:00 +1100 - 2018-03-01 00:00:00 +1100
1 day loaded in 1m12s

Everything: 1 day, 1 producer, 1 shop and 1 order cycle selected
loaded in 1m6s

Conclusion: While this helps a little bit, there is still a big problem and even
loading only one day could time out on some servers.

### optimise database queries

The next idea is to look at the database queries to generate this report
which can probably be optimised. I just loaded the dev sample data on my
computer to generate the queries of the report and check what takes long or
doesn't scale.

Searching the items for the report:
```ruby
permissions.visible_orders.complete.not_state(:canceled).search(params[:q])
```

`permissions` is a library object and the constructor doesn't perform any
queries. `visible_orders` with super admin:

```
  SQL (0.8ms)  SELECT "enterprises"."id" FROM "enterprises" 
  SQL (0.5ms)  SELECT "spree_orders"."id" FROM "spree_orders" WHERE "spree_orders"."distributor_id" IN (1, 5, 11, 12, 13, 14, 15, 16, 4, 3, 2, 10, 6, 7, 9, 8)
  SQL (0.3ms)  SELECT "order_cycles"."id" FROM "order_cycles" 
  SQL (1.7ms)  SELECT "spree_orders"."id" FROM "spree_orders" WHERE "spree_orders"."order_cycle_id" IN (1)
  SQL (0.7ms)  SELECT "spree_orders"."id" FROM "spree_orders" WHERE "spree_orders"."id" IN (2, 1)
   (0.4ms)  SELECT COUNT(*) FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't'
  Enterprise Load (0.6ms)  SELECT "enterprises".* FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't'
  SQL (0.6ms)  SELECT "enterprise_relationships"."child_id" FROM "enterprise_relationships" INNER JOIN "enterprise_relationship_permissions" ON "enterprise_relationship_permissions"."enterprise_relationship_id" = "enterprise_relationships"."id" WHERE (parent_id IN (4,3,2)) AND (enterprise_relationship_permissions.name = 'add_to_order_cycle')
   (0.5ms)  SELECT COUNT(*) FROM "enterprises" WHERE (enterprises.id IN (NULL))
  SQL (0.5ms)  SELECT "enterprise_relationships"."parent_id" FROM "enterprise_relationships" INNER JOIN "enterprise_relationship_permissions" ON "enterprise_relationship_permissions"."enterprise_relationship_id" = "enterprise_relationships"."id" WHERE (child_id IN (NULL)) AND (enterprise_relationship_permissions.name = 'add_to_order_cycle')
   (0.5ms)  SELECT COUNT(*) FROM "enterprises" WHERE (enterprises.id IN (NULL))
   (0.5ms)  SELECT COUNT(*) FROM "enterprises" WHERE "enterprises"."is_primary_producer" = 't' AND (enterprises.id IN (NULL))
  SQL (0.9ms)  SELECT "spree_orders"."id" FROM "spree_orders" LEFT OUTER JOIN spree_line_items ON (spree_line_items.order_id = spree_orders.id) LEFT OUTER JOIN spree_variants ON (spree_variants.id = spree_line_items.variant_id) LEFT OUTER JOIN spree_products ON (spree_products.id = spree_variants.product_id) WHERE (spree_orders.distributor_id IN (NULL) AND spree_products.supplier_id IN (NULL))
  Spree::Order Load (1.1ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."id" IN (2, 1)
```

That looks like it has some potential for optimisation.
Selecting all enterprise ids does not scale and is not necessary.
We want only distributors here and that would be better in a sub-query.

Selecting all order cycle ids doesn't scale either and would be better in a sub-query.

While this is maybe not ideal, it takes only 5 seconds of query time on our production server.
With ruby retrieving the data it takes 9 seconds.
So this is not the bulk of the computation.

Instead of looking into the SQL queries on my computer, I now just go through the steps on the production server to benchmark how long they take.

```ruby
    def search
      permissions.visible_orders.complete.not_state(:canceled).search(params[:q])
    end

    def table_items
      orders = search.result

      line_items = permissions.visible_line_items.merge(Spree::LineItem.where(order_id: orders))
      line_items = line_items.supplied_by_any(params[:supplier_id_in]) if params[:supplier_id_in].present?
      #....
    end
```
The search query just retrieves order ids.
The table rendering function `table_items` then loads all these orders just to
use their ids to load line items and optionally filter them by producer.
This is information that has been in the first queries already.
It takes 24 seconds on our server.

```ruby
      # If empty array is passed in, the where clause will return all line_items, which is bad
      line_items_with_hidden_details =
        permissions.editable_line_items.empty? ? line_items : line_items.where('"spree_line_items"."id" NOT IN (?)', permissions.editable_line_items)
```

Then there is a search for line items we shouldn't be able to see details about,
because we have missing permissions. That takes another 20 seconds.

```ruby
      line_items.select{ |li| line_items_with_hidden_details.include? li }.each do |line_item|
        # TODO We should really be hiding customer code here too, but until we
        # have an actual association between order and customer, it's a bit tricky
        line_item.order.bill_address.andand.assign_attributes(firstname: I18n.t('admin.reports.hidden'), lastname: "", phone: "", address1: "", address2: "", city: "", zipcode: "", state: nil)
        line_item.order.ship_address.andand.assign_attributes(firstname: I18n.t('admin.reports.hidden'), lastname: "", phone: "", address1: "", address2: "", city: "", zipcode: "", state: nil)
        line_item.order.assign_attributes(email: I18n.t('admin.reports.hidden'))
      end
```

Each of these line items is then modified to set values to "hidden".
That took 1m54s on our server when executed in the console.
Since this is really slow, it would probably be better to select these values
on database level instead of modifying them in Rails later on.

### summary

Time is up and I didn't look into the rendering of the reports.
I also didn't look at pagination to load the report in chunks.
But the most promising approach seems to be to optimise the database queries.
Maybe we should also look at specific use cases and think if there is a better
representation. For example, if we only want reports for one shop or one producer
then the data query can be simplified a lot. It could also simplify the user
interface. Do we need the report "Give me every ordered line item I have access to"?

**Comment by sauloperez** [comment]
Don't you guys run NewRelic in Australia? that should give accurate real-world data of the whole stack and point out to spots to optimize.

Even though those queries could certainly kill our DB (the one selecting all enterprises :scream: ), it looks like the biggest problem is iterating over big ActiveRecord objects to hide the details. For my experience, doing that with large collections has a negative impact on the GC.

**Comment by mkllnk** [comment]
Oh, yes, I forgot about compiling the report in the background. The user could select which reports they want and then it's done with a Delayed Job. Once ready, the user gets notified via email.

@myriamboure About the filtering: A lot of the filtering is done so that you don't see information you don't have any permission to see. So we can't let the user do that. The filtering the user could do, is no big deal here.

**Comment by sauloperez** [comment]
> Oh, yes, I forgot about compiling the report in the background. The user could select which reports they want and then it's done with a Delayed Job. Once ready, the user gets notified via email.

I believe we do have lots of low hanging fruits before having to bring in all that complexity.

**Comment by myriamboure** [comment]
After talking with @enricostano and @sauloperez I understood the confusion we were in.
In milanote we had formulated our goal as "people can use existing reports",  but I think this is not precise enough, so I propose to **separate that in two**:
- **people can from the menu "report" access any give report PAGE.** (they manage to reach the page where they are supposed to be able to generate/download a give report)
- **when they are on the report page, people can generate/download the given report with max 1 year data**.

That was the big thing that I was confused about, so that's why I thought removing filtering wouldn't solve our accessibility issue, we were not talking about the same level of accessibility.
SO to solve that
1- I created a second icebox item and rephrased the first one to really make clear those two focus points ([icebox for "access the page"](https://community.openfoodnetwork.org/t/make-sure-all-enterprise-managers-can-access-reports-filtering-menu/1282) / [icebox for "access the report"](https://community.openfoodnetwork.org/t/improve-reports-performance-to-ensure-all-users-can-generate-reports-for-max-1-year-data/1196))
2- I adjusted the lines in the roadmap spreadsheet: the feature candidate for icebox "access the page" is "remove filtering and don't charge any data before filtering" / the feature candidate for icebox "access the report" is unknown but @mkllnk spike are first inputs that can help us find one.
3- I think we need to change the priority in milanote to "People can use existing reports" to "People can access any report page" (to be discussed but seems that we are not going to rewrite reports this year)
4- I created a new EPIC #2210 which is in fact what we have decided to prioritize = make sure users can access any report PAGE (which was not clear to me), and we need to create a story for the feature candidate we agreed upon.
5- I'm then going to close that epic for now until we decide to prioritize the next step which is "access the report".

If anyone disagree please reopen and discuss, else let's start with the first bit which is to enable access to the report page.
@daniellemoorhead that is a good case about being super precise about focus. #wearelearning :-)
