### ISSUE TITLE
Delivery note

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2230]
## What is the problem we are solving 
- Jane/Mary cannot know the differences between what she order (to Mary or Fred) and what she was invoiced for.
- We cannot issue legally valid invoices on OFN

## Success factors = expected outcome 
- An invoice generated from OFN shows what was invoiced = delivered compared to what was originally ordered.
- It is not possible to issue two invoices with the same invoice number and different content.

## Metric
- Any enterprise receiving an order from a customer can issue a delivery note and corresponding invoice to that customer.
- It is not possible to modify an order when the corresponding delivery note has been issued.

## Useful information for/from inception
Here are the results from the first inception session: https://community.openfoodnetwork.org/t/inception-session-delivery-note/1286

## Link to the "Icebox" item in Discourse
https://community.openfoodnetwork.org/t/make-ofn-invoices-legally-compliant/1199

## First feature candidate to be implemented
The first feature candidate is to **"add delivery note, adapt the process, and print invoice = delivery note"**. 
We are having a broader discussion with the community on which type of order cycles we want to support. Meanwhile there is at least a first story we can start to work on which is "create a delivery note for an order".

Other stories we have started to list during inception (depend on discussion of type of OC we want to support):
![screenshot from 2018-04-16 18-10-16](https://user-images.githubusercontent.com/8135376/38822216-06006566-41a3-11e8-9091-2889ba2ab691.png)

**Comment by daniellemoorhead** [comment]
@myriamboure I'm wondering how this feature backlog item relates to what we discussed in the product curation session? This seems like the overarching problem to be solved for invoicing, so should an new/additional epic be created that is for the delivery note feature? And how does this relate to #2396, that one looks like it's the bulk invoice print/send feature...but that feature is also mentioned here.

Shall we just call each of these 'Invoice Delivery Note' and 'Bulk Invoice Printing', and put the goal into what we are trying to achieve in the description?

**Comment by myriamboure** [comment]
@daniellemoorhead For me the epic is "the need" (the icebox candidate we choose to prioritize). As what we want to do is satisfy a need, so when we review the epic we need to check that the need is satisfy, not that the feature is implemented. As you see I explain in the epic the feature candidate we choose, then in the inception stage we list all stories and attach them to the epic. If at the end we realize when testing the whole thing that the need is not properly met we need to implement a second feature candidate. That's what I understood from the processes we agreed upon, but we can rediscuss and change while in Barcelone if that's not satisfying for you. For me the processes is good, I have applied it for cookies for instance and it seems good to me.
This specific epic was selected in the previous curation meeting. Again, there is a problem here that was discrepencies and impossibility to understand invoice as didn't uderstand follow the change from order, AND as we modify directly order invoices can be generated with same number and different contant which is illegal. That was the problem, so the epic. Feature candidate we choose is "introduce delivery note to follow amendments to original order and print invoice from those new info".
Nothing is mentionned here about the issue in #2396 which is different, it is that today it takes lot of time to send invoices to users, and users should receive an invoice for each purchase...
#focusonneed

**Comment by RachL** [comment]
@myriamboure As we discussed, we need to add a story (after the delivery note works) saying we should use the content of the delivery note to generate an invoice. Shall we keep this epic and just link stories to it, or do we do a separated epic for delivery notes ? I don't remember what we did say :(

**Comment by myriamboure** [comment]
@RachL actually you can really keep that epic, maybe adjust some wording to make sure everything is clear. I just changed the title, see if that's clearer.
The need is "to be able to capture the difference between ordered and delivered and make sure invoices are based on what was delivered" > feature candidate we selected = issues delivery note, so associated to that epic you will have all the stories about the slides document we discussed today (the new delivery note menu and workflow until you have the delivery note attached to the order line. One of those stories will be to rewrite the invoice generation script so that it sources info from delivery note info, with some default rule like "if no delivery note has been issued default is that delivery note info = order info"... we need to make sure that no modification can happen on the order after delivery note has been issue (which will solve invoice legal compliance issue of being able to issue two invoices with different content and same number...).
We might have to review a bit the invoice format to make sure amendments are visible on it to satisfy the need of clarity for the user.
Is that clear?

The second point we mentionned today in our discussion about "bulk orders actions" (print invoices) is a totally separate focus point and so epic.

**Comment by RachL** [comment]
@myriamboure @enricostano @sauloperez @luisramos0 @Matt-Yorkley @HugsDaniel  here are my notes from the last Barcelona's inception.

- **Workflow**: A user can modify an order till the order cycle is closed, then this order can only be modified by an admin until the delivery note is created (the order is locked once the delivery note is generated). Users (managers and superadmin) can edit a delivery note only until invoice is created. 

- **To keep in mind for the future**: we can have several delivery note for 1 order (even many for many, but we will first do 1 for 1, then many for one and then see if many to many is useful)

- **First iteration**: should focus on delivery note, without touching invoices. Once it is stable, we will work on invoices (creating invoices from the delivery note). Result of first iteration should be: **I can CRUD a delivery quantity in bulk**.

As we said we should start a new page from scratch for this, I've done some [mockups](https://drive.google.com/drive/u/0/folders/1dQTajE6c1BR0je2CcbtvsAbmbmdwP63D) using a sketch tool and introducing 2 small good pratices on the page: breadcrumps and text intro (see PDF file in the folder).
My remaining questions: 
- Do you confirm that on first iteration we do not create PDF files - so my last sketch screen does not exist? If so we will just need to know how we are going to test that the delivered quantity is up-to-date.
- We said that we should choose between product or customers views in first iteration, so what shall we start with?

When we will go further, I would like some delivery note example from various countries in order to design what the final document will look like. I think this is still missing from our various discussions.

**Comment by myriamboure** [comment]
@RachL I'm not sure I understand "I can CRUD a delivery quantity in bulk"?  Do you mean "I can CRUD delivered quantities for many products and customers in just one view?" Is it what you mean here by "bulk"? Just to make sure, I guess that's what it means and I also noted that from the meeting but it's not clear now...

Small feedbacks on your mockups:
- we use "end date" in all other page if I'm not misleading, no "finish date"
- about "status", only "complete" orders are elligible for delivery note, if the customers has not gone till the end of checkbout there is no order. But some hubs might want the orders to be paid before they prepare and send them, so having a status filter maybe on "All complete orders / only paid orders " would make sense? But it could be on iteration 2...
- I think we need to keep the email filter, some hubs treat orders one by one within a permanent order cycle and bulk doesn't mean anything for them
- "check delivery quantities" seem strange to me, I would see more "enter delivered quantities"
- on the "by product" view you still need the customer name in the table, we need to know how much of this product we put in each customer basket.

About your questions:
- I am note sure we will create and store a PDF for each order, don't we just generate it on demand if users click on the delivery note icon/button near the order, or trigger an action on order "view delivery note"?, like we have today "print invoice"? But we need a way to access the data. What we said is that those data can be modified until invoice is printed, but that won't happen in iteration one, will it? As the invoice is still not printed from delivery note info. I think we need to include in version 1 of the feature that invoices are printing from delivery note info, as else we will have conflicting information between the two documents, invoices will still be printed on ordered quantities, so hubs will want to make adjustments, and that would be a mess.
- if we have to choose between two views I would start with "per product", arbitrary as we need both definitely and I guess practices of hubs are equaly likely on both.

**Comment by kirstenalarsen** [comment]
I am a bit unclear about the creation of the delivery note / bulk modification function - it seems to duplicate the Bulk Order Management page a lot. 

![image](https://user-images.githubusercontent.com/2911176/44757987-41e74900-ab75-11e8-86af-dd571f492d16.png)

I'm not clear why we wouldn't be working tweak this page e.g.
* add status as a filter
* add quantity delivered and possibly make 'uneditable' quantity ordered
* some kind of view switch to allow viewing / selecting by total order rather than just single line items
* add as an Action "generate delivery notes"
* NB. the column 'weight/volume' allows for an adjustment to the order e.g. if customer ordered meat by 1kg and has to be adjusted to actual weight - this is not dissimilar to the intent of delivery note as I understand it, except that it would be changing the underlying order

I am not sure how much (if at all) this page is being used - perhaps matomo can tell us? But it seems to me to make a lot more sense to refine / improve this page rather than create a standalone page that does almost but not exactly the same thing - so much confusion?!

**Comment by kirstenalarsen** [comment]
@lin-d-hop might be able to tell us if she thinks anyone is using the variable weights thing in uk?

**Comment by kirstenalarsen** [comment]
also @myriamboure @RachL given that a lot of ofn hubs take payment at time of order is it correct to assume that the delivery note will provide info about what is happening with refunds etc?

**Comment by RachL** [comment]
Before our meeting with @myriamboure tomorrow here are some feedbacks from my side on what has been written here. Tomorrow once we have everything, I will clean the epic mess and generate a proper icebox. ping @kirstenalarsen 

>     we use "end date" in all other page if I'm not misleading, no "finish date".

I'm fine with "end date", but just so you know I've only find "end date" in reports ;) We have also "stop" and "finish"

>    about "status", only "complete" orders are elligible for delivery note, if the customers has not gone till the end of checkbout there is no order. But some hubs might want the orders to be paid before they prepare and send them, so having a status filter maybe on "All complete orders / only paid orders " would make sense? But it could be on iteration 2...

Let's keep that for iteration 2, lets work only on complete orders for now

 >   "check delivery quantities" seem strange to me, I would see more "enter delivered quantities"

I've used "check" because quantities are pre-filed. In the case everything went as planed, there is nothing to enter, isn't it?

> I am note sure we will create and store a PDF for each order, don't we just generate it on demand if users click on the delivery note icon/button near the order, or trigger an action on order "view delivery note"?, like we have today "print invoice"? But we need a way to access the data. What we said is that those data can be modified until invoice is printed, but that won't happen in iteration one, will it? As the invoice is still not printed from delivery note info. I think we need to include in version 1 of the feature that invoices are printing from delivery note info, as else we will have conflicting information between the two documents, invoices will still be printed on ordered quantities, so hubs will want to make adjustments, and that would be a mess.

All developers agreed that this is a big piece and that just by adding delivering quantities we will see other problems we did not anticipated. So I'm not comfortable going back on that decision. On the PDF side, if you generate on demand, there is no bulk action anymore, isn't it?

> I am a bit unclear about the creation of the delivery note / bulk modification function - it seems to duplicate the Bulk Order Management page a lot.

At the gathering we chose to start from scratch mainly for technical reason. I will have a look at this page and see if we can find something easy to use as we are only working on complete orders for delivery notes. But I'm curious: do you remember why there is a bulk order management page different from the orders page? And as we will put bulk invoice printing and other bulk action directly on the order page maybe we will be able to move the functionality from this page to the regular order page as well?

>also @myriamboure @RachL given that a lot of ofn hubs take payment at time of order is it correct to assume that the delivery note will provide info about what is happening with refunds etc?

Delivery note will indeed keep a trace on what has been delivered vs what has been ordered and sometimes also paid for.

**Comment by myriamboure** [comment]
> also @myriamboure @RachL given that a lot of ofn hubs take payment at time of order is it correct to assume that the delivery note will provide info about what is happening with refunds etc?

Interestingly @kirstenalarsen in France, rebellious people who don't want to give money to banks, I would say only around 5% of sales on OFN use online payment at time of order. 95% of payments happen at delivery time, by cash or checknotes (you know this thing that has disappeared in almost all countries? ;-)).

I agree with @RachL that what the BOM page is for is unclear, maybe the title is not descriptive enough... Order page you don't have info about the products ordered, on BOM page you manage info about the products ordered, so maybe we should check "what do we do with those pages" and be more explicit. And from that we can be clearer if delivery note should be part of BOM renamed page or a new page. 

The only use I have seen / done myself when I was running a hub of this page was:
1- When we were using group buy feature, to see for a given product all what was ordered and adjust given group buy size.
2- For variable weight items, we were selling cheese and weight was between 100 and 200g so were adjusting weight so that price adjust.

So I agree that for those 2 actions, it is part of the scope of delivery note actually, both are actions capturing a difference between what has been ordered and what will be delivered. So maybe you started building a delivery not feature without noticing it when you built it ;-)

We'll brainstorm with Rachel on all that tomorrow and come back to you !

**Comment by kirstenalarsen** [comment]
yay - just catching up on slack and see @sauloperez poking head up in delivery note which alleviates concern above :)

**Comment by sauloperez** [comment]
> We need to be sure that the solution meets Katuma's need. (and do we need to check in whether it is still priority katuma need? @sauloperez ?)

it is number one priority for Katuma without any doubt. We're even working on potential grants to pay its development.

**Comment by myriamboure** [comment]
Agree with you @kirstenalarsen to find scoped and as tiny as possible implementation solution, but what we tried to do with Rachel is "go back to the need". We have opened a new version of a draft icebox https://community.openfoodnetwork.org/t/make-info-on-quantity-ordered-delivered-invoiced-voided-paid-accurate-and-improve-packing-operation-efficiency/1441/3. 
I definitely agree that this "packing support" feature (enabling to capture gaps and print some delivery note) could be just an evolution of the bulk order management page. But still not trivial as we need to save separatly the amendment info (my suggestion was to use Spree 2.2 adjustments possibility).

The tricky part of the need IMO is about the reconciliation need that you mentioned previously @kirstenalarsen between the invoice / payment already done and what has been actually delivered. So ensure it is clear for Jane what she has paid for exactly and if she has paid, how much she has been refunded for instance.

Let's continue the discussion on Discourse as I think we will close the GH issues and reopen them when we have done the proper analysis and understanding of the need.
