### ISSUE TITLE
Error on updating enterprise users when not initialised

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#2257]
There are some rare cases in which a user is unable to save changes to a new enterprise after fiddling around with the users.

## Description

The `receives_notifications` field is not initialised properly on a new enterprise. I observed the default value `? string:1 ?` which looks like an Angular glitch. When trying to submit the form, a server error is generated.

## Expected Behavior

I should always be able to submit the enterprise edit form.

## Actual Behavior
```
 ActiveRecord::StatementInvalid in Admin::EnterprisesController#update

PG::Error: ERROR:  invalid input syntax for integer: "? string:1 ?"
LINE 1: ...rprise_roles" SET receives_notifications=(user_id='? string:...
                                                             ^
: UPDATE "enterprise_roles" SET receives_notifications=(user_id='? string:1 ?') WHERE "enterprise_roles"."enterprise_id" = 2

Parameters:

{"utf8"=>"✓",
 "_method"=>"put",
 "enterprise"=>{"name"=>"...",
 ...
 "receives_notifications"=>"? string:1 ?",
 ...}
```

## Steps to Reproduce

1. Log in as super admin.
2. Create an enterprise.
3. Go to the users tab of that enterprise.
4. Without submitting, add a manager to the enterprise that is not the owner.
5. Remove that manager again.
6. The update button is now clickable, click it.
7. You get a server error.

## Context

I was testing https://github.com/openfoodfoundation/openfoodnetwork/issues/2254. This is part of email confirmation.

## Severity
S3 - there is a workaround.

You can first add the owner as manager. It send appears in the notifications dropdown. Select them there as well and the form should work.

## Your Environment

Dev environment.

## Possible Fix

Two ideas:

- Initialise the mangers/notifications data properly.
- Upgrade Angular.

**Comment by Matt-Yorkley** [comment]
I had a look at this today with the latest version of master and I couldn't replicate the issue...

**Comment by myriamboure** [comment]
I just reproduced it @Matt-Yorkley but this is a wider problem pretty annoying, look at https://www.useloom.com/share/0bef9464293a43489f94620670e8414b
and 
https://www.useloom.com/share/ccf2821aacab48f2b9974ee59efbfbd3
and
https://www.useloom.com/share/f440103fc1f04341bf6cb429c18928aa
Whenever I do some action, put to invisible the enterprise, change tax situation, add a manager, I get the system error!
I think that worth a s2 as it's VERY disurbing for ALL users. @Matt-Yorkley can you work on it?

**Comment by Matt-Yorkley** [comment]
@myriamboure so this is every time you save an enterprise?

**Comment by Matt-Yorkley** [comment]
I can't replicate this on UK production or in my dev environment (including when changing tax or switching enterprise to not visible) so I don't have much to go on in terms of fixing it.

I'd agree it's at least S2 if the snail page is popping up when saving enterprises.

**Comment by daniellemoorhead** [comment]
@myriamboure is it possible to confirm this is happening for any other instance? @mkllnk are you able to help @Matt-Yorkley to reproduce this bug?

**Comment by myriamboure** [comment]
I got it! the bug doesn't happen on an existing enterprise, only on the new one I just created, as an admin! I created the enterprise with my admin account, from back office ("new enterprise button"), but when I save, and look at the enterprise list, there is no "owner" displayed. If I enter the enterprise setting menu and go to "managers" tab, strangely, there is a owner but no "manager". 
![screenshot from 2018-06-01 08-55-44](https://user-images.githubusercontent.com/8135376/40826191-45e01b72-657a-11e8-8241-5f134783ecb5.png)
Normally the owner SHOULD always be a manager as well, but he is not in that case! When I add the same owner address as a manager, it fixes the issue, so I think the problem is that if I create as an admin an enterprise from back office, it doesn't create the manager at the same time as the owner.
@Matt-Yorkley can you reproduce now and see how to fix that?
