### ISSUE TITLE
NoMethodError in admin/order_cycles#index

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2271]
## Description
Katuma's Bugsnag reported the following error a week ago.

![captura de pantalla 2018-05-09 a les 15 19 36](https://user-images.githubusercontent.com/762088/39816821-a80f3340-539c-11e8-8c32-f3be23e08f8a.png)

## Expected Behavior
At the point the `OrderCycle` model is used `user` should always be defined.

## Actual Behavior
The app fails with the mentioned error when issuing the following request: 

```
curl --request GET \
  --header 'Accept: application/json, text/javascript, */*' \
  --header 'X-Csrf-Token: 7xGaO9wLnV3Ey6PjKvrt9KY/4u+VXVpFEYZFAiERzaI=' \
  --header 'User-Agent: Mozilla/5.0 (Linux; Android 7.0; SM-J710F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.126 Mobile Safari/537.36' \
  --header 'Referer: https://alpha.katuma.org/admin/order_cycles' \
  --header 'Accept-Encoding: gzip, deflate, br' \
  --header 'Accept-Language: es-ES,es;q=0.9' \
  --header 'Cookie: [FILTERED]' \
  'https://alpha.katuma.org/admin/order_cycles.json?ams_prefix=index&q%5Borders_close_at_gt%5D=Sun+Apr+01+2018+00:00:00+GMT%2B0200+(CEST)'
```

## Steps to Reproduce

1. Log in as admin
1. Navigate to Order Cycles
1. Clear session in browser manually
1. Click "Show 30 more days"
1. 💥 

## Severity
The reach of this bug is still unknown but doesn't seem to affect too many users, so severity 3.

## Your Environment
* Version used: v1.14
* Browser name and version: Possibly Firefox
* Operating System and version (desktop or mobile): Android

**Comment by frank-west-iii** [comment]
Seems like this might be related to a session timeout.

The problem lies in the order of execution for the `before_filters`
https://github.com/openfoodfoundation/openfoodnetwork/blob/d218a51d96965dc9b55edcca61dbf0eaeb2c0355/app/controllers/admin/order_cycles_controller.rb#L9

**Comment by sauloperez** [comment]
great investigation @frank-west-iii ! I'm not sure what's best then here. Perhaps it's an error we can live with. 

> There might be a way to override this behavior from Spree?

These two words together (override and Spree) are terrifying :trollface:

**Comment by frank-west-iii** [comment]
Agree re: overriding Spree. 👍

**Comment by myriamboure** [comment]
So what is the status for this bug @sauloperez @frank-west-iii do we move it forward? Leave with it and close? Or do something?

**Comment by frank-west-iii** [comment]
We could at least fix the error so it does not occur again.

The user will still not see any updates to their page when they click an action like "Show 30 more days". It will just fail silently for them. The user might then refresh their browser or take an action that will require them to log in again and the page will work again for them until they time out their session again 😄 

The UX for it is not great, but that may be a more widespread issue across the application rather than this specific issue.

I can remove the error from our logs, but a much bigger conversation may need to be had about handling 401 errors across the application on AJAX requests.
