### ISSUE TITLE
[Spree Build] Set up CI for openfoodfoundation/spree

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2286]
## Description

As agreed in the [first spree upgrade catch-up](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Team-catch-ups--%F0%9F%92%AC#may-9-2018), we want to set up a CI integration to watch after [Spree fork](https://github.com/openfoodfoundation/spree/tree/2-0-4-stable)'s test suite. This will make its maintenance a bit easier.

**Comment by oeoeaio** [comment]
@sauloperez I have had a go at setting up CI on [Semaphore](https://semaphoreci.com/openfoodfoundation/spree/branches/2-0-4-stable/builds/6) but there seems to be a problem resolving dependencies. I am happy to play around with getting it working on Travis too/instead if that is preferable.

**Comment by oeoeaio** [comment]
Ok, I was using the wrong version of ruby, this one is mostly running but there are a lot of failures and there still seems to be an issue resolving dependencies for `Spree Sample`...
https://semaphoreci.com/openfoodfoundation/spree/branches/2-0-4-stable/builds/7

**Comment by oeoeaio** [comment]
>Do you have any idea whether it's because we broke something or Spree's test suite wasn't passing back then? 

@sauloperez no, I don't have any idea sorry. We haven't made many changes to `2-0-4-stable` though right? It's just https://github.com/coopdevs/spree/pull/6 and https://github.com/openfoodfoundation/spree/pull/5?

**Comment by sauloperez** [comment]
> I'm not sure whether the failures would speed it up or slow it down.

yes, that's a good point. I would say failures will slow it down in most of the cases as exception handling it's rather costly.

**Comment by mkllnk** [comment]
I just looked at the current Spree master and it has a Travis and CircleCI configuration. Our version 2.0.4 has a Travis configuration already. So I thought I try that, hoping that we benefit from their maintenance of the config file. But it turns out they trigger 24 builds for different combinations of their modules, databases and ruby versions. It's also exposing similar issues addressed by Pau in https://github.com/coopdevs/spree/pull/5. I found somewhere that the bundler version may be too new. Spree needs bundler 1.13.7.

https://travis-ci.org/mkllnk/spree/builds/395350373

Trying to get my head around the Spree upgrade is really just falling into a hell of broken code. You guys learned a lot already. I need to catch up. :-)

**Comment by mkllnk** [comment]
I think this issue should be blocked until someone gets the tests running locally.

**Comment by mkllnk** [comment]
I just had a successfully failing spec run on my local machine. I had to call `bundle` in all Spree modules to get all gems installed just to run the core specs. I also had to uninstall other versions of rake so that the right version is loaded.
```
Finished in 42.7 seconds
981 examples, 10 failures, 2 pending

Failed examples:

rspec ./spec/models/spree/credit_card_spec.rb:108 # Spree::CreditCard#valid? should only validate on create
rspec ./spec/models/spree/credit_card_spec.rb:123 # Spree::CreditCard#save should not actually store the number
rspec ./spec/models/spree/credit_card_spec.rb:127 # Spree::CreditCard#save should not actually store the security code
rspec ./spec/models/spree/order/payment_spec.rb:16 # Spree::Order processes all payments
rspec ./spec/models/spree/order/payment_spec.rb:29 # Spree::Order does not go over total for order
rspec ./spec/models/spree/order/payment_spec.rb:44 # Spree::Order does not use failed payments
rspec ./spec/models/spree/payment_spec.rb:513 # Spree::Payment#save when profiles are supported when there is an error connecting to the gateway should call gateway_error 
rspec ./spec/models/spree/product_spec.rb:224 # Spree::Product validations find_by_param permalinks must be unique cannot create another product with the same permalink
rspec ./spec/models/spree/stock/coordinator_spec.rb:20 # Spree::Stock::Coordinator build packages builds a package for every stock location
rspec ./spec/models/spree/stock/coordinator_spec.rb:27 # Spree::Stock::Coordinator build packages missing stock items in stock location builds packages only for valid stock locations
```
That looks manageable. It's not great that the test suite fails, but better than not running. I wanted to see if we broke anything already and selected https://github.com/openfoodfoundation/spree/commit/8e2fd9ad530614b049b77976b5dc8708e0ff9589 to run the specs as well. It has two fails less! These two didn't fail before we changed code:
```
rspec ./spec/models/spree/stock/coordinator_spec.rb:20 # Spree::Stock::Coordinator build packages builds a package for every stock location
rspec ./spec/models/spree/stock/coordinator_spec.rb:27 # Spree::Stock::Coordinator build packages missing stock items in stock location builds packages only for valid stock locations
```

They pass when run on their own, but not when running the whole test suite. Using git bisect, I found that https://github.com/openfoodfoundation/spree/commit/24cc3e484f2f481d55f5a5481f2daca9e9fa5cfa broke a lot of tests. The follow-up commit https://github.com/openfoodfoundation/spree/commit/86a1f42adf1d98576745623e7740e5e70992f043 fixed most of them, but not the two in question.

I propose to deactivate the currently failings tests with a big TODO, possibly creating GH issues for each of them. That enables us to find every new commit that breaks more specs.

**Comment by sauloperez** [comment]
Seems reasonable to skip these two so that we can move forward while someone else tries to fix them.

**Comment by daniellemoorhead** [comment]
@mkllnk there has been no work on this for a long time...but it's still sitting in the code review column. 

Can it be moved back to Dev Ready until it's picked up again?

#keepthetrainmoving

**Comment by mkllnk** [comment]
Oh, I think @HugsDaniel is actually working on it. Is that right, Hugo?

**Comment by daniellemoorhead** [comment]
@HugsDaniel if you're working on it can you move this issue back to 'In Dev' if you haven't got a PR yet, or connect the PR to this issue so that they are together on the zenhub board. Thanks!

**Comment by HugsDaniel** [comment]
Hey guys, I didn't see the issue but that's part of what I'm working on yes ! Following the conversation between @sauloperez @mkllnk and @oeoeaio, Semaphore seem to be up and running with https://github.com/openfoodfoundation/spree.

**Comment by sigmundpetersen** [comment]
Can we close? https://github.com/openfoodfoundation/spree/pull/9 @HugsDaniel

**Comment by sauloperez** [comment]
We made it work in Semaphore CI running only Postgresql
