### ISSUE TITLE
Add GoCardless support

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#229]
Integrate CoCardless so that repeat DD payments can be taken. 

This functionality will be particularly useful in conjuction with repeat orders #402

**Comment by NickWeir63** [comment]
Another option for this is https://stripe.com/gb which looks very promising.  @elf-pavlik Is this also something that could be explored at the hackathon?
Thanks

**Comment by kirstenalarsen** [comment]
I've put this into the hackathon milestone so is on their radar, can move back if they don't pick it up / get done

**Comment by myriamboure** [comment]
Actually we are also very interested in Stripe as a payment gateway, especially the "Connect" option, which works a bit like Mangopay (both seems interesting). The good thing is that with those payment gateway when a customer pays, the money is directly distributed to the good bank account (the product prices go to the producers accounts directly, the fees go to the hubs, etc.) We just have to "write" the process. I'm just not sure that can work alongside with other payment gateway, and we want the hub manage to be able to choose the payment gateway he wants to  use, so that can be a limitation. But great if that can be investigated during the hackaton :-)

**Comment by lin-d-hop** [comment]
I would like to move these into separate issues. GoCardless will be great to repeat orders when we get closer to that functionality. A DD can be any amount once authorised, so if the basket is £13 one week and £15 the next, as long as we give the appropriate notification we can just adjust the amount we take. Perfect for repeat orders.

Mangopay and Stripe will be useful for setting up complex payment relationships to minimise the work of hubs. I can imagine this will be a major plus for many CSA style operations that would like to diversify but can't justify extra accounting work to do so. I would also love to see this functionality implemented.... one day :-)
