### ISSUE TITLE
Embedded shops not working (blank screen) - 1.15.1? or was it earlier?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2302]
## Description
I was checking the embedded shop at Black Mountain Food Hub (UK) and noticed it wasn't working. I then went to set one up on staging1.openfood.com.au and it is also not working (blank screen). 

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/f31d4c21-ce17-4940-a553-3dd5c8324518)

Both shops seem to be working fine in OFN itself

## Actual Behavior
The external website should show an embedded OFN shop

## Steps to Reproduce
Create an open shop front
Follow [instructions](https://ofn-user-guide.gitbook.io/ofn-user-guide-master/advanced-features/shop-setup/embedded-shopfront) to embed it in a wordpress site or other
Ensure the domain is listed in config of the host instance

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a8f627a0-c47a-45f6-a827-a2cf2e3159a6)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c072195d-d607-48d6-86c5-8457f0412e76)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/8d792713-4d4d-4846-88bd-adcc29eafff9)

## Severity
I think it's at least S2 - not many are using this feature, but those that are it's pretty critical. Black Mountain order cycle is open at the moment so they are likely having customers arrive at  a blank page

## Your Environment
Mac
Chrome

## Possible Fix
Could have been in last release? I am not sure who is in best position to confirm when they were last working?

**Comment by mkllnk** [comment]
Hm, I've heard about people having problems setting up embedded shops, but the old ones still seem to work: https://openfoodnetwork.org/user-guide/advanced-features/demo-embedded-shop/ (Firefox 52.8, Linux). Our production server has v1.15.1 and a few more updates.

**Comment by kirstenalarsen** [comment]
hmmmm ok, that one works for me too . .

**Comment by kirstenalarsen** [comment]
so perhaps it is me . . when i tried to checkout from that shop @mkllnk i got blank screened again . . 
![image](https://user-images.githubusercontent.com/2911176/40295308-2b3396c0-5d1c-11e8-8c0d-ffa1975cf80f.png)

**Comment by kirstenalarsen** [comment]
just tried that shop in chrome and is telling me this 

![image](https://user-images.githubusercontent.com/2911176/40295363-5830ea7e-5d1c-11e8-896a-28bbaccfe730.png)

**Comment by kirstenalarsen** [comment]
seems like maybe something i need to do at wordpress end, perhaps is ssl thing. But that doesn't explain uk issue

**Comment by myriamboure** [comment]
We are on v1.12 in France and #2026 had been merged and fixed the problem, embed shopfronts was working. I don't know which version UK was until this week but I did a demo of blackmountain food hub less than 2 weeks ago and it was working. If something broke it it is pos v1.12 I reckon. Any idea devs? https://github.com/openfoodfoundation/openfoodnetwork/releases...

**Comment by myriamboure** [comment]
Could it be connected to some update needed in ssl certificate on blackmountainfoodhub website then?

**Comment by myriamboure** [comment]
I just retested with French production on v1.12, that includes #2026 fix, and is working correctly, see the domain openfoodnetwork.org is in position 3 in the list and the shopfront is well dispayed in the wordpress.

![screenshot from 2018-05-21 13-14-28](https://user-images.githubusercontent.com/8135376/40305136-8c1607ac-5cf9-11e8-9c76-b017e216d53b.png)
![screenshot from 2018-05-21 13-12-35](https://user-images.githubusercontent.com/8135376/40305138-8f29eaa8-5cf9-11e8-8ecd-72714e58289e.png)

So:
- either it's a ssl issue on external website site
- either it's a problem that happened since v1.12

**Comment by myriamboure** [comment]
Ok I might have a clue. One user in France is trying to embed a shopfront.
He did the test in two websites, both domains are in the whitelist an have appropriate ssl certificates:
- https://ledebutdesharicots.fr/test-shop/: here it works
- https://www.micromarche.fr/maison-de-quartier-de-l-ile/ here it still doesn't work and for the this page he still get the error message "Refused to display 'https://www.openfoodfrance.org/micromarche-maison-de-quartier-de-l-ile-de-nantes/shop?embedded_shopfront=true' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors micromarche.fr"."

Does it ring any bell?
All work ok in the global wordpress and in some sites, but not all, so why?
@Matt-Yorkley maybe you will have an idea as you worked on #2026

**Comment by Matt-Yorkley** [comment]
I fixed this today on UK production. It was down to an SSL header (`Strict-Transport-Policy`) that was being set twice because of our server configs, which caused the header output to be invalid.

**Comment by NickWeir63** [comment]
Hi Matt
Here is another (possibly linked) and urgent issue with an embedded group for the Biodynamic Association.......

From: Tom Stedall [mailto:tom@spiraledge.co.uk] 
Sent: 21 May 2018 17:13
To: Nick Weir; Biodynamic Association
Subject: Re: IMP Probs with our OFN BDA producers map
Hi Nick,

Ok, thanks. Getting it working is higher priority than the scrolling. This is the console error:

Refused to display 'https://openfoodnetwork.org.uk/groups/biodynamic-association-licencees?embedded_shopfront=true' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors biodynamic.org.uk".

I'm curious if it is us or you - it was working on Friday, and nothing has obviously changed. Maybe your team have encountered this before? I can also get onto WP Enginem quickly if needed, they are very helpful.

Best wishes,
Tom


On Mon, 21 May 2018, at 5:09 PM, Nick Weir wrote:
Hi Tom
Thanks for the link.  No it is not working for me either .
I will ask a colleague to look at this ASAP and try to get it up again to back up your social media promotions about the map
Apologies again
Nick
 
From: Tom Stedall [mailto:tom@spiraledge.co.uk] 
Sent: 21 May 2018 17:05
To: Nick Weir, OFN; Biodynamic Association
Subject: Re: IMP Probs with our OFN BDA producers map
 
Hi Nick,
 
That's ok, these things happen!
 
Our map is here: https://www.biodynamic.org.uk/where-to-buy/
 
Still not loading for me but we use WP Engine, so maybe a caching issue. Can you see it?
 
Also my question re container height - I wanted to give it one that was large enough so that the page scroll (as opposed to the iframe scroll) allowed you to see the whole country, but increasing the size of the iframe reduced the zoom to an unhelpful extent. Any advice on this appreciated!
 
Best wishes,
Tom

**Comment by myriamboure** [comment]
@NickWeir63 it seems the map of biodynamic association is working now so I guess it was connected to the same issue, right?

**Comment by lin-d-hop** [comment]
Yes, same issue. This #2305 has now been deployed to uk production.

Note - the issue wasn't spotted as only naked URLs (without www) were tested with embed fix in 1.12. Just noting that here for future testing wisdom.

Please could we have #2305 merged for the next release @sauloperez?

Thanks everyone, particularly @Matt-Yorkley, for your help with this!

**Comment by myriamboure** [comment]
Hum... sorry I didn't notice that when testing, but I didn't see how to test apart from using the wordpress where we have the demo shop... hard to thing about all possibilities, sorry :-( I guess would be great to make a release when this and the OC s1 issue are fixed as both are emergency ones (hopefully can be fixed today as well).

**Comment by NickWeir63** [comment]
Thanks for doing the testing @myriamboure I find it very difficult to do it at all so appreciate your time on it.  Could we embed a shopfront and a group on UK staging for future testing?

**Comment by myriamboure** [comment]
No you can't @NickWeir63 you need an external website to embed a shot and staging is not an external website. You need some other website, like a wordpress, etc. with an ssl certificate to be able to embed a shop from staging in order to test those kind of things.
