### ISSUE TITLE
Product Import: override in "set available date" doesn't work

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2320]
## Description
I import a csv with one info on "available_on" column for one of the two products. Then select import option "set availabe date", "override all" (or "override if empty", doesn't matter) and I choose 2018.05.31 in that example. On next step in the "review" stage I don't see the available on column in the table which is confusing as I can't check if the info I asked to change will be taken into account. I proceed till the end and view products, I check and available on field, it is not set to the date I asked..

## Expected Behavior
I see the info I'm about to update in the "review" step + "Available on" field is updated accurately.

## Actual Behavior
It is not.

## Steps to Reproduce
1. Go to hidden https://staging.openfoodnetwork.org.uk/admin/product_import
2. Upload a csv with a column "available_on" with some content for one product, not for the other.
3. Choose "set available date", choose "override if empty" (or "override all" doesn't matter) and select a given date.
4. Import, you see the table has no "available on" columns so I can't check if it has been taken into account or not.
5. Proceed till the end and check (add column "available on") nothing is changed.

## Animated Gif/Screenshot
https://www.useloom.com/share/b88d4613de714b0aa75bbc28f612c4cd

## Context
Listing product Import issues after first big PR

## Your Environment
* Version used: branch #1492 on UK staging
* Browser name and version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by Matt-Yorkley** [comment]
The date format should be `YYYY-MM-DD`, so `2018-05-31` should work. I'll add some notes to the guide.

**Comment by myriamboure** [comment]
I just retested @Matt-Yorkley with the good date format and it is still not working:
Imported:
![screenshot from 2018-06-18 08-35-54](https://user-images.githubusercontent.com/8135376/41521493-a63e7e5e-72d2-11e8-92a3-88c16408177d.png)
Result:
![screenshot from 2018-06-18 08-36-34](https://user-images.githubusercontent.com/8135376/41521508-b9af7e7a-72d2-11e8-8b2b-9aaf30787457.png)
Note: I was not importing a new product but updating an existing one.
Note2: I had already aske to add a line on available-on date in th guide (cf https://github.com/openfoodfoundation/openfoodnetwork/issues/2326)

**Comment by Matt-Yorkley** [comment]
Ah, I think it will work on new products but not existing ones. So this and a few of the other remaining issues all fall under the same category, and basically require a single fix, but we might need to have a broader discussion about it and do some more inception on it. Maybe we should move this to Discourse?

The issue is this: when creating products, some fields get saved within individual variant records, and some fields get saved on the product record, which acts as a sort of "master" record for all variants under it. When adding a new product for the first time, those fields can be set, but when updating an existing product they can't. This is because if we update them (certain fields stored in the product record), the value will essentially overwrite that field for every variant of that product, which in some cases is not what we want. So then the 2 options are: either we overwrite the field for all variants of that product, which will probably lead to results the user had not anticipated, or we don't allow it to be overwritten, which also probably leads to results the user had not anticipated. Neither option is especially satisfying. I could alter the logic to overwrite instead of ignore, but I'm not sure if that's the best solution. 

**Product fields:** name, description, available_on, tax_category, shipping_category, supplier, primary_taxon, group_buy, variant_unit, variant_unit_scale, variant_unit_name.

**Variant fields:** sku, weight, count_on_hand, on_demand, unit_value, unit_description, display_name, display_as.

Every item in a shop is effectively a Variant, that has it's own unique attributes for "Variant fields" above, and inherits it's remaining attributes ("Product fields") from a Product record, which are shared with sibling variants, if any.

**Comment by myriamboure** [comment]
Reopening the issue as the PR is not really fixing it ;-) Was adding info on what to do but there is still an issue which is not fixed. I commented in the PR.

**Comment by myriamboure** [comment]
Closing for https://github.com/openfoodfoundation/openfoodnetwork/issues/2460
