### ISSUE TITLE
Missing translation in "payment step" in new order from admin

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2374]
## Description
"back to payment list" button is not translated in https://www.openfoodfrance.org/admin/orders/R030367412/payments/new page
![paymet](https://user-images.githubusercontent.com/8135376/41380632-e59f7032-6f65-11e8-88bd-84f7fe33cafd.png)

## Steps to Reproduce
1. From back office, orders, click on "new order"
2. Follow the steps till you arrive at "payment step" and see button not translated.

## Severity
S4

## Your Environment
* Version used: v1.15.2

**Comment by haseleyi** [comment]
The missing translation is in line 8 of this spree view: https://github.com/coopdevs/spree/blob/2-0-4-stable/backend/app/views/spree/admin/payments/new.html.erb

The key is there, but we're getting English instead of French.

Our [internationalization wiki](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29) says: "Add missing Spree translations: you may find that a spree view or controller complains about missing translations. The fix to these problems is to look up the translation in one of the en.yml files in Spree and copy the translation entry to OFN's en.yml file."

It looks like our en.yml has the key, but our fr.yml doesn't. Could we just need to translate this on Transifex?

**Comment by haseleyi** [comment]
You're right! The view finds my translation key when I add a global to our en.yml, but not when I pursue lazy lookup and place it under 'spree' or 'admin.' Am I looking in the wrong place in the locale file? Despite the spree version discrepancy, the view is still in
spree/backend/app/views/spree/admin/payments/new.html.erb in my gem.

**Comment by sigmundpetersen** [comment]
I think @luisramos0 has worked on i18n and may give some advice

**Comment by luisramos0** [comment]
hey @haseleyi our en.yml doesnt have the key. Looks like you just have to copy the key to our en.yml. Should be on the root en: not inside en.spree.
After your PR gets merged, it will appear in transifex and the fr.yml file will get updated on the following transifez PR.
If you want to test the French translation before committing you can add the entry to the fr.yml file locally and see the translation working (dont commit this one).
I hope I was clear :-)
