### ISSUE TITLE
[Cookies] Investigate what it takes to replace google analytics by Matomo

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2404]
## Description

To implement the cookie regulation and be legally compliant we have two options:
- if we stay with google analytics we need to do more work on ability to enable/disable cookies, and let instance decide about default opt-in/opt-out, etc.
- if we switch to matomo (piwik) we can leave it as an essential cookie as it doesn't collect any personal data so it simplifies a lot the implementation of the cookie feature. As we said we anyway want to switch to Matomo maybe it worth spending max 2 hours on investigating what it takes to implement Matomo and if worth doing it now to gain time on cookie feature.

**Comment by luisramos0** [comment]
Hi @myriamboure,
Do you want me to do a feature comparison between the two tools? Is there any feature in GA that we may need and not have in Matomo?
For now I'll focus on the tech part of installation and configuration.
Thanks,
Luís

**Comment by luisramos0** [comment]
Please let me know if I should add this info somewhere else or if here is fine.

To use Matomo for Analytics we need:

# Decide Cloud-hosted vs On-premises
Hosted version, provided by InnoCraft: https://matomo.org/hosting/
Price depends on data volume but 25eur/month could be enough for now. Pricing details https://www.innocraft.cloud/#pricing
Question: Can we use cloud-hosted version of Matomo and still be GDPR compliant?
Answer: From I see here, looks like the answer is _yes_ because Matomo anonymizes data. More details here: https://matomo.org/gdpr/

On-premises version is FREE. The costs are system installation, system maintenance and price of upgrading server or getting a new server for matomo. Matomo will probably not have a great impact on server load as the volume of visits to the websites is not very large. I think, for now, we may just be able to install Matomo on the web servers where OFN instances are running.

# Install Matomo On-premises
If you want to have Matomo on premises you need to install Matomo on one of your servers.
To install Matomo we need to have PHP and Mysql on the server. The installation procedure looks  straight forward. Details here: https://matomo.org/docs/installation/
Installation can be done using docker containers as well. Details here: https://github.com/matomo-org/docker

# Make OFN use Matomo

### GA and Matomo will co-exist in OFN?
We can/should/must (?) keep GA as a possible Analytics solution for OFN together with Matomo. An instance manager can decide if she wants to use GA or Matomo.
One of the advantages of GA is that it's free, with Matomo you either pay for the cloud-hosted option or "pay" with resources usage on your existing servers. With Matomo on permises you may need to resize your server or buy a new one. If you decide to buy a new server you may consider the cloud hosted solution provided by innocraft, see links above.

### Tracking Tags
We must:
* insert Matomo's tracking tag in OFN
  * we need to be able to configure Matomo for each instance. Example configurable items:
    * enable/disable Matomo's tracking tags
    * identification and credentials of Matomo's service to use (either local or hosted in a remote server)
  * This can be achieved through a configuration file or through new configurable entries in the BackOffice. I'd suggest this to be defined in a configuration file as these configs will change very rarely for a given instance.
* make Analytics tags appear only if GA is being used
  * we can either use the same config file we use for matomo's config or maybe we can use the existing spree analytics trackers under /admin/trackers to see if GA is being used or not. I think it could be a good alternative to enable/disable GA tracking tags: GA tracking tags will be inserted on the FrontOffice only if there are trackers configured on the BackOffice

# Estimation
I am not sure how you guys do estimates, if you do any. Here are my estimates :-)
* 1st instalation of Matomo on a server for the first time and documenting it for following installations - 8 to 16 hours
* 2nd instalation of Matomo on another server - 4 hours
* Code change on OFN to support Matomo or GA
  * if we use config file - 8 hours
  * if we build config screen - longer than 8 hours...

I think that's it. Questions/comments/concerns? :-)

**Comment by myriamboure** [comment]
Thank you for that first analysis @luisramos0 !

### About hosted or self and GA or not GA

I'm not sure having each instance install Matomo is a solution. Especially as we are heading toward a single instance used worldwide.
Is it possible to  have one single installation for the whole instances? Like we have a global wordpress installation for the global website? Can we have one Matomo following all OFN instances performances?
If we go for a self hosted version of Matomo I don't know if we should keep the possibility to use GA. We want to have a clear product vision and defend it, so if every instance agree that we want to avoid google when we can that could be part of our product policy.
Else I think it is worth considering the hosted version, 300€ budget a year seems like a decent budget for the value added. And sorry @luisramos0 but Google Analytics is not free, it's just that our users are the product ;-) As you say each instance will have to choose if they want to use GA or Matomo in that case.

### Would using hosted version of Matomo really prevent us to ask user consent on analytics cookies (opt-in or opt-out)

It is confusing and from my understanding it seems we will have to request consent from our users as if we were using GA... or at least give the possibility to opt-out. I sent a message to Innocraft to ask them so hopefully we'll know soon.

I did some investigation about Matomo compliance with GDPR and [here](https://matomo.org/blog/2018/04/how-to-complete-your-privacy-policy-with-matomo-analytics-under-gdpr/) is a model that they recommend. Interestingly we are in the case: "The processing of personal data with Matomo is based on explicit consent. Your privacy is our highest concern. That’s why we will not process any personal data with Matomo unless you give us clear explicit consent."
Given this it seems Matomo themselves recommend to ask our users their explicit consent...

[Here](https://matomo.org/blog/2014/10/cnil-recommends-piwik-analytics-tool-no-cookie-consent/) I find this: "If you are already using Matomo (Piwik) you need to do two simple things: (1) anonymise visitor IP addresses (at least two bytes) and (2) include the opt-out iframe solution in your website (learn more)."

[Here](https://matomo.org/blog/2017/01/new-proposed-eprivacy-regulation-piwik-might-not-need-tracking-consent-compared-google-analytics-co/) as well: "The difference with other analytics solutions is that you can download and install Matomo (Piwik) on your own infrastructure. Websites and mobile apps tracking users with their own Matomo very likely won’t require a consent from their users if these regulations become reality."

### Elements to decide

I think the key elements to decide are:
- if hosted version of Matomo require user consent, then I would suggest we stick with GA for now and implement the cookie feature without Matomo and we can add or switch to Matomo later on whenever we want. The cookie feature will remain the same.
- ... unless we decide to go for self-deployment of Matomo for all instances or in each instance. But if we leave the possibility to use GA we still need to implement the cookies analytics opt-in/out so if we do again I would suggest we stick with initial plan...
- only case where we don't have to implement the opt-in/ou on analytics cookies is if self-hosted and only Matomo IMO.

Let's see what tech people think about it ;-)

**Comment by luisramos0** [comment]
Hi Myriam, Thanks for your feedback!
That's useful info about GDPR and matomo! I think we should go for the self-hosted version of matomo.

Re single OFN instance worldwide, I'd be worried about geographical distance. I'd go for single european instance but I wouldn't want Australian users hitting a database in France or vice-versa...
I say this, because this is the same for Matomo. I would be ok for a Matomo server for Europe, but not shared with Australia due to distance and impacts on site performance/UX.

Re "But if we leave the possibility to use GA we still need to implement the cookies analytics opt-in/out so if we do again I would suggest we stick with initial plan..."
You could keep using GA for instances outside Europe that do not have cookies consent enabled. But I agree it's easier and clearer to remove GA from all instances.

**Comment by myriamboure** [comment]
About single instance @luisramos0  we discussed that in global gathering in Australia, there are very good options now to manage single instance with various servers behind, load balancing, etc. (I'm not tech so I stop here) and we all agreed it is a direction we want to go, but you will learn more in Barcelona ;-)
But maybe that wouldn't work for Matomo... let's discuss later today.

**Comment by luisramos0** [comment]
Adding a bit more detail about piwik opt-out feature.
**This is applicable to both self-hosted and cloud-hosted** (I think this is the way we should go): we just need to anonymize user IP on our side and include the piwik optout iframe on our cookie policy page (very similar to what's specified for analytics on the "cookie inception' document):
https://matomo.org/docs/privacy/#step-3-include-a-web-analytics-opt-out-feature-on-your-site-using-an-iframe
This iframe will do all the opt-out work for us.

**Comment by myriamboure** [comment]
I got an answer from the Matomo team to my questions:

1) Even if you are not processing any personal data, it is a good practice to propose an opt-out service to your visitors. However you can insert this system within your privacy policy page or in a place where people would expect to find it. That's the golden rule, always be fair with your visitors.
It is in general allowed to track users by default, but we can only recommend you read our articles: https://matomo.org/blog/category/privacy/

2) There is no difference in terms of self-hosted or Cloud hosted, when it comes to the opt-out/opt-in situation. We offer a Data Processing Agreement which guarantees that we don't use your data in any way or don't modify it or access it. Learn more: https://www.innocraft.cloud/dpa

We recommend you signup for our free trial here: https://www.innocraft.cloud/start-30-day-free-analytics-trial

Seems it adds some precious info for our discussion and decision.

**Comment by luisramos0** [comment]
Really useful info, thanks!!

**Comment by myriamboure** [comment]
Ok so in Barclona we get to a decision to start using the hosted version of Matomo and that GDPR countries would HAVE to use it instead of Google Analytics. @luisramos0 I'm happy that Open Food France account start paying for it on part of the budget we allocate to global pool, so just find what we need and I can sort out how to pay for it. We don't have a credit card but I can put mine and get paied back by OFFrance every month... until we have a credit card.

**Comment by luisramos0** [comment]
ok, thanks. I'll let you know in a few days when I get to set up Matomo.

**Comment by luisramos0** [comment]
Interesting integration of spree with piwik, may be good to have a look as we improve integration with piwik in terms of e-commerce tracking:
https://github.com/berkes/spree_piwik

**Comment by myriamboure** [comment]
I'm closing that issue for now as we have taken the decision to start with using Saas version of Matomo to start with.

**Comment by luisramos0** [comment]
As we start using matomo, we will only have page views and generic numbers, no ecommerce stats.
This would not include dashboard for users, only matomo stats @myriamboure . This integration marks events on the platform about checkout process, etc and those events statistics can be seen in matomo.
