### ISSUE TITLE
Improvement to Shop Header in mobile

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#2446]
There are many sections to the shop header that can be improved. This issue bites off a small chunk that is particularly annoying on mobile and tablets.

## Description
This is the section of the shop header that we are going to focus on - the example is from [this shop](https://www.openfoodnetwork.org.uk/balsallcommon/shop)

![screenshot from 2018-07-10 18-41-17](https://user-images.githubusercontent.com/8669848/42529405-4bfc7b70-8476-11e8-9d54-e8485b29df0d.png)

In mobile the banner takes up a huge amount of space, adding to our excessive scrolling problem.
![screenshot from 2018-07-10 19-22-34](https://user-images.githubusercontent.com/8669848/42529550-adf77438-8476-11e8-968b-9187feb5e095.png)

## Expected Behavior
This issue has not been mocked, so it would be good to see a simple redesign in screen shots before a potential PR. 

An additional thing to note is that the text that appears in the 'Ready For' box has no length limit, so we will need to acknowledge this and display a shortened version that displays in full when the user would like to see it all ie 'on click'.

## Actual Behavior
The mobile experience is ugly and clunky.

## Steps to Reproduce
1. Look at a shop header on mobile.

## Animated Gif/Screenshot
See above.

**Comment by amort2000** [comment]
The banner problems here begin at the top of the screen with the OFN log which is escaping the confines of the menu bar and, weirdly, is bigger at mobile screen sizes than on desktop. 

Can I suggest that the first priority to fixing the banner is to fix the size of the size of the OFN log so that it stays constrained by the menu (like it is in desktop size screens wider than 1024px). This is having a direct impact on the positioning of elements below it and so needs to be fixed first. 

I can't see any thing that looks like the logo has been logged as a problem, but if it has please let me know and I'll take a look at it from there..

**Comment by lin-d-hop** [comment]
I have made an issues to remove the hard coded height and width from banner logos. #2470

**Comment by kirstenalarsen** [comment]
Noting that #2470 is closed, and the rest of this is superceded by Mobile Ready - I am closing this issue. The only thing worth capturing is that there is still an issue with ofn logo escaping banner on mobile in uk - is this an issue with ofn or the logo itself @lin-d-hop ? any idea? Could you check and if is an ofn issue create a new specific bug for it? thanks :)
