### ISSUE TITLE
[Product Import] Review csv template on landing page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2481]
## Description
We have review the UX of product import to avoid confusion, reduce the number of clics, and try to find some consistency.
Here we want to tackle the template part which was before included in issue #2455
The goal is to have csv template with all possible columns.

## Acceptance criteria

Templates for product listings and inventories are accurate. Especially, the template for inventory only has the necessary columns, some existing columns can be delete. Some column headers have been renamed for more clarity. See https://docs.google.com/document/d/1QDtKQe64enO5ZLnht9PxQ8bOlaMHCueJBMWSyW4zCng/edit# for headers in each template.

**Comment by RachL** [comment]
@myriamboure @Matt-Yorkley can you update the google doc with the accurate liste of columns available ? Thanks :)

**Comment by myriamboure** [comment]
I did it already @RachL just need a check by @Matt-Yorkley to make sure we are on the same page ;-) I kept in inventory all what is necessary to identify which product/variant we talk about in the system, and then the fields that can be modified through inventories.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley @RachL @myriamboure is this just the updating of the Google doc? And if you did it Myriam, @Matt-Yorkley have you checked it yet? Can we consider this done?

**Comment by myriamboure** [comment]
No it's not @daniellemoorhead it is updating the csv you can upload from product import landing page given the info in the google doc, so it's a job that needs to be done by @Matt-Yorkley now = updating the csv templates ;-) If you disagree with my column analysis for Product and Inventory please let me know by using the suggesting mode in the google doc so I can understand my mistake ;-) Then @daniellemoorhead we will use the google doc as a base to write the user guide, but we are not yet there ;-)

**Comment by daniellemoorhead** [comment]
I'm not going to be able to offer any specific advice not already provided by people that understand the system far better than I do @myriamboure. I was asking to understand whether this can be moved through to done soon, as it has been 26 days since you put that last active comment on this issue. 

#toottoot #drivingthetrain

**Comment by Matt-Yorkley** [comment]
I think with the inventory template, there are actually not many fields that are relevant to inventory import, so the list is quite small. Various things can't be updated on inventory at all, and there are a few fields needed to match the item to an existing product.

@myriamboure can you clarify what specific changes you are suggesting?

**Comment by myriamboure** [comment]
@Matt-Yorkley cf https://docs.google.com/document/d/1QDtKQe64enO5ZLnht9PxQ8bOlaMHCueJBMWSyW4zCng/edit#
You still need to be able to identify the product, so: 
- product_name (needed to identify the product)
-distributor (called supplier until now but proposed to rename for clarity, please comment in the googledoc if you disagree)(needed to identify where to import)
- supplier (the real original supplier, consistent with supplier notion in product catalog import template)(needed to identify the product)
- units (needed to identify the product)
- unit_type (needed to identify the product)
- product_item_name (proposed to rename for clarity, variant unit name is unprecise here as only apply for item type unit...)(needed to identify the product)
- variant_name (display_name : this is the variant display name, so would rename variant name) do we need that to identify the product or not really? I think it's just logical to keep it as hubs will identify variants with their name, so strange to take it out even if we technically don't need it)
- on_hand (can be modified in inventory upload)
- price (can be modified in inventory upload)
- SKU (can be modified in inventory upload)
- on_demand (can be modified in inventory upload)

I'm wondering about the order of the columns, would be great to have something more logical than the thing in the current user guide. Like All about product identification first, and then the SKU, price, stock, etc. 

Please Matt let's discuss and comment in the google doc for the specifics if you disagree that might be easier ;-)

**Comment by Matt-Yorkley** [comment]
`variant_unit_name` is one of the standard fields on products in the database and we need to use it. I'd like to keep it the same instead of starting to map alternative/custom names for the attributes.

**Comment by Matt-Yorkley** [comment]
So I need to add `description` to the product list template, and add `sku` and `on_demand` to the inventory template.

On renaming the supplier / producer / distributor fields I'm trying to figure out the best way to do it. I initially used "supplier" because that's what it is in the database, but yes it is a bit confusing. I'm not sure "distributor" is best either, because a product can be stocked by an enterprise that is supplying others or distributing to customers, so maybe the best option would just be "enterprise"? 

The fields are different for product list and inventory, where we need the enterprise the product is being imported into, and the enterprise that is the originating source of the product. In this case I think using the same name "enterprise" for the enterprise the item is being imported into would be good, then maybe "supplier" for the source enterprise?

**Comment by myriamboure** [comment]
> a product can be stocked by an enterprise that is supplying others or distributing to customers

@Matt-Yorkley no this is not possible today, a product cannot be in the catalog of a distributor. It can be used by a distributor and stocked by it, but we are in the skin of the one who import, so for product list you only need "supplier", there is no notion of distributor, but for inventory, then you need both the supplier and the distributor who stock the product in its inventory. We can replace distributor by "hub" if that's clearer. I wouldn't use enterprise because we can't distinguish the supplier vs distributor role, and we need to, especially in inventory import. I really think supplier vs distributor is the clearer for everyone. @lin-d-hop @sineadfenton what do you think?

**Comment by myriamboure** [comment]
Yes but it doesn't impact product import, no?
Whoever import in product list, it will always be in the producer catalog, it has to.
For inventory, the case that can be a little bit more tricky is that if the producer import in its own inventory. Then he will be both producer and distributor, as inventory is only used for distribution purpose, if she has no shop she has no point to use inventory.
If hub import products from suppliers in its inventory, then it's clear the the hub is distributor and supplier is supplier.
I don't see which case you are annoyed by @Matt-Yorkley ...?

**Comment by Matt-Yorkley** [comment]
Would a producer import their own inventory from themselves?

**Comment by myriamboure** [comment]
I think we discussed it on the phone but some can if they run different order cycles with different prices for their products ;-) Sop they would import on one side their product list, and on the other side their inventory with other prices for instance. This is an edge case, but works in current version of product import.

**Comment by myriamboure** [comment]
@Matt-Yorkley I guess this one is next on the last PI stories? Then the last one will be to make the menu visible, and BOOM!

**Comment by myriamboure** [comment]
@Matt-Yorkley same here, this is prioritary over bulk invoice printing. Thanks!

**Comment by myriamboure** [comment]
Just a quick reminder @Matt-Yorkley that this is more priority than moving forward on bulk invoice printing, we want to releasssse PI !!!
https://media.giphy.com/media/ZKTNelSY55g4w/giphy.gif!

**Comment by myriamboure** [comment]
Can someone tell me why my gif doesn't show? Pfff, I don't get GH sometimes ;-) 

![](https://media.giphy.com/media/ZKTNelSY55g4w/giphy.gif!)

**Comment by daniellemoorhead** [comment]
![](https://sparklespandex.files.wordpress.com/2015/08/aziz.gif)
