### ISSUE TITLE
FrontOffice - Edit Completed Order - If product stock level is zero, customer can't adjust quantity

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2507]
## Description
I'm a customer with a subscription. In my order I received QTY 4 of a product, these were the last 4 in stock, there's now an on hand value of zero for that product. I, the customer, go to edit my order (because my shop allows me to) as I only now want 2 of that product. I find that I can't change the qty and see an error message 'there is zero in stock'. I should be able to reduce my order to 3,2, or 1. But I can only have zero, or leave my order as it is at 4.

## Steps to Reproduce
1. Create a sub order where the order purchases all the remaining stock for an item.
2. Make sure the shop allows customers to edit orders
3. As the customer view your order and try to change the QTY for that item. You'll see the bug.

## Animated Gif/Screenshot
https://www.useloom.com/share/8a583f5fc1544beeb99942af551f3f35

## Context
I'm trying to edit a sub order. 
This may occur for regular orders in shops that allow changes too. 

## Severity
s3

## Your Environment
Chrome, PC, Staging1

## Possible Fix
Allow me to reduce the qty, and return any items to on hand stock.

**Comment by luisramos0** [comment]
I just tested this with an order not related to subscriptions and I can replicate. So, although editing a completed order may be more relevant to subscriptions, this bug is not related to subscriptions.

I am taking this out of the subs backlog and move it to the Bug Backlog.

I had a look at the code, and ***maybe*** in v1 this was specific to subs and in now in v2 is a generic bug.
[This commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/1835d97013f83576d2c4a93b80bdb08f7015bf34#diff-24e541b4ab015c71c58ee244899f4e7aL124) could well have introduced this bug: if the order is complete, before we check stock we need to remove the quantity already reserved in the order...

**Comment by luisramos0** [comment]
I put it at the top of the bug backlog, I think we need to fix this soon.
