### ISSUE TITLE
[Spree 2 Upgrade] Fix Spree's test suite

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2530]
## Description

This is a placeholder for Spree's test suite related issues.

**Comment by luisramos0** [comment]
Note: this is not related to the OFN build, this is the Spree build: https://github.com/openfoodfoundation/spree/tree/2-0-4-stable.

The OFN build (https://github.com/openfoodfoundation/openfoodnetwork/tree/2-0-stable) is the one we are measuring the success rate for progress. There's no specific issue for this one because all other spree upgrade issues are part of making this build green.

**Comment by sauloperez** [comment]
Done!
