### ISSUE TITLE
Address in checkout unfillable on old Samsung phone

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2568]
This issue is probably connected to the discussion on supported browsers and versions.
But I want to make sure it is linked to old version of browser, and nothing else more annoying.

## Description
A user has reported the following case: she uses a Samsung phone 
Samsung note: GT.N7000 (10 year old apparently)
Version of androïd 2.3.6
Version number: GINGERBREAD.XXKKA
When she tries to buy from her phone, she reaches checkout, but when trying to enter her name and address at checkout, she can't, no keypad appears when she clicks in the field, she is just blocked.

## Expected Behavior
User manage to checkout

## Actual Behavior
User can't

## Steps to Reproduce
See in description.

## Context
Reported by a customer of an Open Food France hub.

## Severity
s3 (workaround: she asks the hub manager to order for her via email and hub manager make an order from backoffice. She has no computer.)

## Your Environment
Cf description + she uses the default Samsung browser.

## Possible Fix
Change phone? ...

**Comment by daniellemoorhead** [comment]
I don't think I agree with your severity level @myriamboure. We've only had 1 user affected by this, and they have a 10 year old phone (smart phones only started to exist in 2006/7 so that's a very very early model).

I understand that you want to support older hardware/OS and do 🖕 to design obsolescence...but given it's only impacting 1 user I believe this is a severity 5. I'm changing it to this, feel free to refute my logic and change again if you don't agree 😄

**Comment by myriamboure** [comment]
I agree with you @daniellemoorhead but I just want to know what to tell that user... and make sure the problem she encounters is linked to the old phone thing...

**Comment by sigmundpetersen** [comment]
Okay, tested with the following on OFN France production:
Model: Samsung S9 (SM-G960x)
Android: 8.0.0
Samsung Internet browser version: 7.4.00.69 (10 Jul 2018)

I can proceed to checkout and fill in all fields OK.

ping @myriamboure

**Comment by myriamboure** [comment]
I'm just going to close this issue... the phone is too old we can't do anything :-(
