### ISSUE TITLE
Translation missing on reports page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2592]
## Description
New sentence to guide users towards using filters in reports is not currently being translated
![image](https://user-images.githubusercontent.com/6525576/44676581-04c76d80-aa34-11e8-97b5-43ee83586abe.png)

## Steps to Reproduce
As an admin, go to reports : /admin/reports

Click on any report and the sentence will appear.

## Context
A French user reported it. 

## Severity
S4

## Your Environment
* Version used: v1.18

**Comment by HugsDaniel** [comment]
@RachL I'm unable to reproduce the issue, after pulling all locales from Transifex I do have the sentence in french : 
![screenshot from 2018-09-06 11-45-53](https://user-images.githubusercontent.com/28786869/45149786-a97f4300-b1ca-11e8-877a-4abb4db1bf5f.png)

**Comment by RachL** [comment]
@HugsDaniel I just saw on French staging that it is indeed resolved. So It will be ok in production after next release; Yay! :) Closing this one and I'm making a note to myself to check once the release has been made. Thanks Hugo!

**Comment by myriamboure** [comment]
@mkllnk @luisramos0 I think this is another proof that there is a big issue with our transifex process... this sentence has been translated since ages and production have been upgraded recently. It's like the producer packing choose stage in register modal, went back to English. We have regularly things translated in transifex since long that never go through product, or disappear... we need to investigate and understand what happens.

**Comment by mkllnk** [comment]
This is the timeline that lead to this:

- 12 June: French is translated to a 100% and PR #2370 is opened.
- 13 June: The Transifex branch is merged into master.
- 18 June: #2361 gets merged and this text is available for translation.
- 12 July: v1.16.0 is released without any changes to the French locale (the translation is missing).
- 19 July: v1.17.0 is released (missing French translations).
-  4 August: v1.18.0 is released (missing French translations).
- 10 August: The French translation reaches 100% and it's included in the Transifex pull request #2536.
- 13 August: #2536 including the French translation is merged.
- There has been no release since then.

@myriamboure Are you sure you translated French to a 100% between 18 June and 10 August? I can't find any evidence of that. Maybe the process we are missing is a trigger for translating. Does Transifex tell you when there is stuff to translate?

**Comment by myriamboure** [comment]
Wahou, impressive @mkllnk ;-) But on Transifex it shows that the string has been translated on 28 June... so it should have been in the last three releases...
![capture d ecran de 2018-09-07 14-45-42](https://user-images.githubusercontent.com/8135376/45219941-d4da5e80-b2ac-11e8-9788-b4775a0b84b4.png)

**Comment by myriamboure** [comment]
And no @mkllnk we don't receive any notification when we have something to translate, it would be great!

**Comment by sigmundpetersen** [comment]
_All_ strings have to be translated for a PR to be created from Transifex to GH @myriamboure . So if as Maikel says French was not translated **100%** between June 18 and August 10, the string in question would not have made it to the releases.

It's possible to pull all translations manually before a release though. I think @luisramos0 did that before the release today.

**Comment by luisramos0** [comment]
yes, I pulled all translations for this release.

**Comment by myriamboure** [comment]
Ok so that's probably a good practice to add to your release manual @luisramos0 @Matt-Yorkley @sauloperez @mkllnk to avoid those kind of issues...

**Comment by mkllnk** [comment]
If we pull the translations manually, we don't need that Transifex integration at all...
