### ISSUE TITLE
Ability to adjust variable weights on orders

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#276]

**Comment by pmackay** [comment]
Would be useful to get some input from @RohanM on how this might be tackled.

**Comment by lin-d-hop** [comment]
Agreed. I've thought through this a little, you know, for fun, as you do... the best fit option I've come up with so far goes something like this:
*Under Order tab, in the Edit button for an order...*
Upon Editing an Order, an additional field for *unit* can be displayed and editable, eg 500g. When edited this field would then be used to adjust the price for the product in question eg price = price * newUnitValue / oldUnitValue. 
As far as i can tell this will mean a new field being added to spree_line_items to store the unit, adjusted or otherwise.
Does that sound realistic? Feasible? Not fraught with nightmares or bugs?

**Comment by kirstenalarsen** [comment]
Think we should have a chat about this one. Concern for me would then be all the places that the order is referenced (including reports etc) and either needing it to change to read from the new value, or having an option or something

Also, i'm pretty sure that changing these values doesn't recalculate the adjustments (e.g. fees) so we might need to take a look at that at the same time. The other way to do it would be to just calculate a new adjustment . . hmm. Will have a think about this. I think it could be a good one to get Rob involved in too

**Comment by lin-d-hop** [comment]
Closing as this has been merged.

Improvements have been suggested and @oeoeaio is looking at them in #568 

@oeoeaio Let me know if you need me to tackle any of the improvements.

Thanks for all your help Aussies!
