### ISSUE TITLE
[Spree Upgrade][PI] Make Product Import create stock items (1 broken spec)

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2783]
## Description

In Product Import spreadsheet entries map directly to product, variant and variant override records. That is, an entry can become any of these entities in our DB.

With Spree 2.0 this gets more complex and `variant.count_on_hand` becomes `variant.stock_items.first.count_on_hand`. It can't be longer assumed that `entry.attributes == variant.attributes` (or product or variant override).

**Comment by sauloperez** [comment]
`spec/models/product_importer_spec.rb:312` fails due to the same root cause. Product Import assumes variants have an `on_demand` column and that is no longer the case.

**Comment by luisramos0** [comment]
the description is a bit outdated now because we have since then agreed that we will not play with stock items but instead use the variant_stock facade to handle these cases. done in #3355

**Comment by luisramos0** [comment]
the only case where this is still a problem is the only broken spec after #3355:
spec/models/product_importer_spec.rb:684

In this spec, we test entry_processor.assign_defaults where we set the defaults.
The challenge here is that we set the defaults before we save the "object", but the object can be product or variant, SO, it's not straight forward to do the same as in #3355 where, for variants we save the variant and then set on_hand, for product we set on_hand in the variant.

Let use this issue to represent this broken spec, ok?

**Comment by luisramos0** [comment]
Hey @mkllnk yes, I totally agree with the problem and I like the solution.
Interfaces would come handy here where you would have an Importable Interface and a Factory that takes an Entry and returns an Importable. You would have 5 implementations of Importable: new_product, new_variant, etc. What you describe is similar to this but without interfaces...

Having said that, I dont think this is strictly needed now, I think it's tech debt that we don't necessarily need to pay now (my opinion). We can add one more branch now and get the upgrade done.

The main reason I say this about this task is that ProductImport (although it has a few OO flaws, this is just one) is far from being core to OFN and we should invest quality refactoring time on core parts of the system, that's where it will pay off really quickly. For this reason I'd create a tech debt issue that is lower in priority than for example both #2952 and #2763
It's obviously your call, just wanted to share my opinion.

**Comment by mkllnk** [comment]
@luisramos0 
> Interfaces would come handy here where you would have an Importable Interface and a Factory that takes an Entry and returns an Importable.

I totally agree. This is where I miss Java, too. In Ruby we don't have typed variables and therefore no support of interfaces. We only have unit tests to verify it something adheres to an interface.

I also share your opinion about the priority since I found a quick hacky solution in #3425. I created a new tech-debt issue: #3438.

**Comment by sauloperez** [comment]
I had that same concern when I first looked at PI's code being familiar with v2 data model. I do agree that if we can fix PI in v2 with too much hassle we can focus on other more core things.

However, I'm of the opinion that when implementing new requirements to any existing code devs should take a first refactoring step to adapt the existing design to fit the new needs. This makes refactorings well scoped and quick and make subsequent requirements easy to implement.

In this case, I'd have done that the first time we touched PI in v2. Just a first small refactor. But that's just my experience and opinion.

**Comment by luisramos0** [comment]
Agree @sauloperez we could have done the refactor and this refactor move is very important as it will clarify PI a lot. I am just not sure about the size. I think it's a M and that's why I think we should skip it for now.

In the last 6 months for the spree upgrade, I think I have 20 examples (PRs) where I could have done a lot more refactoring. Choosing the refactoring path means delaying delivery, in the spree upgrade case, I could easily take another 6 months just for refactoring! Taking this path of not refactoring is true tech debt in my opinion, true tech debt is deliberate. "We must ship now I deal with the consequences" https://martinfowler.com/bliki/TechnicalDebtQuadrant.html

**Comment by sauloperez** [comment]
Yes, I also agree. It's been reeeeeaaaally hard for me to be pragmatic and refrain myself from refactoring and cleaning things up within the upgrade. I'm sure you've noticed :trollface:

**Comment by luisramos0** [comment]
yes, it's very hard but the bright side is that we do see how to improve it and we are slowly improving the code base.
