### ISSUE TITLE
[Spree Upgrade] Fix specs related to Subscriptions (pending specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2786]
Subscription_mailer_spec is badly broken with 21 broken specs.
These specs were made pending but need to be fixed at some point.

spec/jobs/subscription_placement_job_spec.rb is badly broken.
These specs were made pending but need to be fixed at some point.

Moved all specs in subscription_form_spec to pending
Moved all specs in spec/features/admin/subscriptions_spec to pending
Moved all specs in subscription_confirm_job_spec to pending

See #2787 , #2795 and #2902

**Comment by kristinalim** [comment]
Current status in #3589 branch:

* `spec/mailers/subscription_mailer_spec.rb` - Done
* `spec/jobs/subscription_placement_job_spec.rb` - Fixed in #3589 
* `spec/services/subscription_form_spec.rb` - Done
* `spec/features/admin/subscriptions_spec` - Done
* `spec/jobs/subscription_confirm_job_spec.rb` - Done

**Comment by luisramos0** [comment]
Amazing 🎉
