### ISSUE TITLE
Update OFN Germany logo

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2838]
@kirstenalarsen commented on [Fri Oct 05 2018](https://github.com/openfoodfoundation/ofn-install/issues/253)

Both front and back (customer and enterprise views)

**Comment by Matt-Yorkley** [comment]
I was looking at this yesterday, and there's a Spree config value called `Spree::Config[:admin_interface_logo]` which allows for setting a custom logo for the backend, but it doesn't seem to be editable from anywhere in our current configs. It might be nice to add this option for all instances.

**Comment by mkllnk** [comment]
What's the task here? What should the logo be? Do we use our templates and call it Open Food Network Germany? Or Deutschland? And which colour do we choose?

Since it's not very fashionable as a German to be proud of Germany, I wouldn't include it in the logo. Was there any particular request or can we leave it as is?

**Comment by myriamboure** [comment]
I guess we should ask the local instance most active people, like Odi, and maybe @kirstenalarsen already had some discussion with Janina, etc. about it ?

**Comment by sigmundpetersen** [comment]
Can we move this to ofn-install repo?

**Comment by mkllnk** [comment]
I don't think it fits in there better than here. I think it should go to a Germany specific board. Do we have that @kirstenalarsen?

**Comment by lin-d-hop** [comment]
Or in the ATAP?
It doesnt really fit as a github issue sooooo #gitcull
