### ISSUE TITLE
[Subscriptions] When setting up OC I can't select French states in address zone, but I can for Italy (on French instance)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2862]
## Description

French instance has three states/region bases setup for local addresses: France, Italy and Spain.
As a hub manager I try to setup a recurring order for a French customer, when setting up their address I can't proceed as I can't select any French state/region. 
But strangely if I choose "Italy" or "Spain" I can see the states/regions and choose.
It seems in subscription states change is not properly handled.

## Expected Behavior

I can setup a subscription for my customer.

## Actual Behavior

I can't as state for that customer cannot be setup.

## Steps to Reproduce

1. Go to "subscription", select hub, and "new subscription" on an instance that has multiple local states/regions configured.
2. When entering address, see when switching between states/regions and see.

## Animated Gif/Screenshot

![capture du 2018-10-12 13-28-17](https://user-images.githubusercontent.com/8135376/46866928-8d06a400-ce23-11e8-9af6-0032d57632ab.png)
![capture du 2018-10-12 13-28-42](https://user-images.githubusercontent.com/8135376/46866940-93951b80-ce23-11e8-88c9-7d2a88a613c6.png)
![capture du 2018-10-12 13-28-53](https://user-images.githubusercontent.com/8135376/46866944-97c13900-ce23-11e8-8d9a-470db4a7546b.png)

## Context

Reviewing subs scope and project with Rachel and testing some remaining issues.

## Severity

S2, this is a non-critical feature that is broken with no workaround and we have an active user of that feature in France.
We tried to first set up the customer address in customer list, but the states are still not visible in subscription and blocking setting up subs.

**Comment by luisramos0** [comment]
hey @myriamboure 
I was confused when you used "multilingual" here, please clarify
This is just the list of French states that is not showing up on the address form. It is not related to language selection, correct? it's the country selection.
Can we remove that word from the description?

**Comment by luisramos0** [comment]
also, when you edit an enterprise or customer outside subscriptions, can you select French states for french addresses? I assume so but would like to confirm.

**Comment by myriamboure** [comment]
Yes you are right @luisramos0 sorry if it was confusing, I change it straight away. You got the issue.

**Comment by luisramos0** [comment]
Hey @myriamboure 
you say this is blocking creating subs? you can create subs with empty state in the address. correct? a workaround would be to put the state in another text field of the address. let me know if this is correct. we may not be testing the same thing.

Anyway, this is a simple javascript bug I'll have a PR ready in the next 24hours.

**Comment by myriamboure** [comment]
Actually it is blocking subs creation @luisramos0 what we have done to test is do as if we were living in Spain :-) Ahh ! in English "state" might be use also as a text field like for "Victoria" or "South Australia" in Australia ;-) Sorry so I thing the field that is blocking in English is named "region", we have translated by the equivalent of state in French so I was confused, but did you understand ok in your fix?

**Comment by luisramos0** [comment]
lets clarify translations first, I believe there's a translation problem here in Admin - Configuration - Régions (which is States in English) - it should be Départments. Or the other way around, the address field should be called Région and not Départment. In OFN, there are only 2 concepts, country and state (lets ignore Zone which is not directly related to addresses). Translating the concept State differently in different parts of the app (Region and Department) is confusing I believe. Please let me know if I am missing something here.

What I want to confirm with you is that: "you can create a subscription with the field State (translated Department in French) empty if, when you see the form, you simply select a country without states and proceed to next screen" (I also suggested for testing purposes you can add the state name in a text field above, for example, address or code postale).

If you select a country with states and then a country without states, that will not work because the field is not clearing.. this is bug number 2 here, the states field should always clear when you select a new country. I'll also fix this one in the PR.

**Comment by myriamboure** [comment]
Actually I think I have to say "mea culpa" on this one @luisramos0 we tested with Rachel and had a bug preventing us to create the subs, but apparently it was connected to something else as I just reproduced and you are right, it is not preventing the creation of a subs... so it wouldn't have been s2 :-( But anyway this is solved now so let's finish it...

Forget about the "suburb" translation issue I will cover it in another issue.
Oups !

**Comment by luisramos0** [comment]
ok! I am sorry, I just wanted to clarify it.

>> the "suburb" translation issue
"suburb" is another text field :-)
