### ISSUE TITLE
On group, profile only hubs don't appear in the hub list

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2868]
## Description

We are creating a group for a local territory willing to cooperate with OFFrance. We created a group and are listing also hubs that don't use the OFFrance platform, so "profile only". They don't appear on the hub list, but they do appear on the map.

## Expected Behavior

Profile only hubs appear in the group hubs tab.

## Actual Behavior

They don't.

## Steps to Reproduce

1. Create a group, add a profile only hub.
2. Check, you see it on the map, but not on the tab "our hubs".
3. Change the enterprise for "sell all" type profile or "sell own".
4. Check again the group tab "our hubs" and you will see it now.

## Animated Gif/Screenshot

https://www.useloom.com/share/1878d760737148f484f979da3d540a35

## Context

We are setting hub a demo to convince a local territory to join OFFrance.

## Severity
S2, this is a non critical feature  but there is no workaround, we are stuck for our demo on this that is supposed to happen on Thursday this week.

## Your Environment

* Version used: V1.21
* Browser name and version: Chrome and Firefox
* Operating System and version (desktop or mobile): Ubuntu 18

**Comment by luisramos0** [comment]
I am not sure why this was put under API, anyway, now that I am looking at it.

@myriamboure I cant replicate this.
With test date, a "profile only" hub is an enterprise that sells none and is not a producer, right?
So, with our test data, I see "Fred's farm" on the "Producer group" under "Our Producers".
If I go to the backoffice and untick the "producers" checkbox I believe I am making "Fred's Farm" a profile only hub and that makes it appear under "Our Hubs" in the "Producer group"

![Screenshot 2019-07-18 at 16 08 36](https://user-images.githubusercontent.com/1640378/61469161-a02c3e80-a976-11e9-9cb4-8269eaac4ac2.png)

So, it looks like it's not such a generic bug, maybe some condition in that hub that is breaking something.
Or **maybe** this was fixed in v2 :-D

can you still see this in FR live?

**Comment by RachL** [comment]
@luisramos0 @myriamboure I can't replicate this issue either.

You will see my test here: https://staging.openfoodfrance.org/groups/awesome#/producers

![image](https://user-images.githubusercontent.com/6525576/61539667-49893800-aa3c-11e9-801f-8b7bc006ab5a.png)


Closing this for now.
