### ISSUE TITLE
Users inventory levels changed for unknown reason

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#2960]
## Description
An Australian user reported that their Inventory levels (set on /inventory) changed without them doing anything on Oct 30th evening. The user checked the levels before opening the shop, and then found some time later that the numbers had changed to incorrect numbers. Thus it's unlikely to be caused by user error. The user is not using upload tool.

The user reported the on hand values for most of her approx 250 products had changed. Some were raised (from zero to >0) or lowered ( from e.g. 9 to 0). Example products impacted: carrots, cucumbers,  Rhon de nice zucchinis,  rockmelon, Fuji apples,  all of the avocado varieties,  kiwi fruit . These items were all originally set to 0 on hand, but after the error they had stock on hand.  The user could see no pattern/logic in the new on hand figures that appeared.

About the Enterprise - Terrewah Farm - This is a producer hub. They have permission to stock one other enterprise's products. The vast majority of products in her Inventory belong to Terrewah Farm. Should this user be usiing Inventory - probably not as it's mostly a producer shop- no need for overrides.
![image](https://user-images.githubusercontent.com/10843056/47760477-93908900-dd08-11e8-9c30-42d7aaf4d147.png)

One possibility is that this bug is related to https://github.com/openfoodfoundation/openfoodnetwork/pull/2893 . Why? Because this PR was merged to Aus production shortly before the issue was reported. This might not be related though. See discussion on the PR.

## Expected Behavior
Inventory levels should remain as levels last saved by user.

## Actual Behavior
Inventory levels have been reported to change without the users' involvement.

## Steps to Reproduce
? Unknown.

## Context
She received orders for items that should have been out of stock and vice versa.

## Severity
If this is a widely reaching but it's S2, but so far there's only been one report of issues. May be Aus only, or certain enterprise configuration only.

## Your Environment
Aus production.

**Comment by kirstenalarsen** [comment]
@luisramos0 @mkllnk @myriamboure does this seem connected to the other discussions?

**Comment by myriamboure** [comment]
> About the Enterprise - Terrewah Farm - This is a producer hub. They have permission to stock one other enterprise's products. The vast majority of products in her Inventory belong to Terrewah Farm. Should this user be usiing Inventory - probably not as it's mostly a producer shop- no need for overrides.

I don't understand @sstead it seems there are multiple enterprises involved here, to understand the issue we need the whole picture I think. If I look at the permission I see that Terrewah farm not only sells her products but also the products of Minimbah farm.
Terrewah farm has in her inventory: her own products, from Terrewah farm, and Minimbah products.

Question:
- did the stock variation happened only with Terrewah products, or also Minimbah products ?

It seems there is no excplicit permission for Terrawah farm "hub" to manage Terrewah farm "products or inventory", can that cause some issue with the PR @luisramos0 ? There is a default/implicit permission apparently on code side, but was it taken into account in your PR? Can it be that the permission was broken by the PR but some strange conflict happen and maybe some old on hand quantity appear in the inventory because strange conflicts?

**Comment by luisramos0** [comment]
Well done @myriamboure I think that's the problem.

Looks like there is a bug in 2893 related to users managing their own stock in inventory.

It's not strange conflict. As 2893 is deployed, permission to own inventory items is revoked and user starts to see her variant levels of stock and not the inventory levels. This explains the randomness.

The migration we have on 2893 is revoking inventory items that belong to the supplier herself.

Workaround: add permission to manage own inventory. On the permissions screen, add entry
"Terrawah farm" allows "Terrawah farm" to manage inventory

Fix: we need to fix the migration in 2893 to not revoke inventory items that are from the supplier herself.

**Comment by luisramos0** [comment]
There are revoked inventory items in the DB for this farm. And those revoked entries are owned by the user herself.

This is the list of hubs affected in AUS.
```
openfoodnetwork=> select distinct vo.hub_id from spree_products p, spree_variants v, variant_overrides vo
where p.supplier_id = vo.hub_id
and p.id = v.product_id and vo.variant_id = v.id;
 hub_id
--------
   2026
   2018
   2092
   1945
   1983
   1839
    221
   2268
   2146
   1881
   2141
    215
   2164
   1979
    626
   2070
(16 rows)
```

We should revert 2893: new problems occur everytime a hub that manages own inventory assigns permissions (I assume it's not a big percentage of users, in AUS live db I see ~700 inventory items of this type).
To fix the data now we should run this quick fix in AUS:

```
update variant_overrides vo
set vo.permission_revoked_at = nil
where vo.id in ( 
select distinct vo.id from spree_products p, spree_variants v, variant_overrides vo
where p.supplier_id = vo.hub_id
and p.id = v.product_id and vo.variant_id = v.id )
```

**Comment by luisramos0** [comment]
actually, I am changing my mind, we need the quick fix and we need to fix the migration BUT we dont need to revert. I will explain in a few minutes.

**Comment by luisramos0** [comment]
So, we don't need to fix the code because only the migration will revoke inventory items when  override.hub_id = product.supplier_id

The code will only revoke permissions that are part of the permission being created or deleted.

Actually there is a problem in the code but it's a edge case I think we can ignore. It's when a permission to manage own inventory is added and then removed (it's a edge case, but will break the inventory). The fix is to re-add the permission. I think we can ignore this case.
By "permission to manage own inventory" I mean using the enterprise permissions page and put the same enterprise on both sides of the permission.

I am creating a PR to fix the migration of #2893

**Comment by luisramos0** [comment]
Just to be clear: after this PR the user will be back at seeing previous stock levels that do not take into account sales that happened between the release yesterday and when the this PR is deployed.

**Comment by myriamboure** [comment]
Oups, @sstead I guess taking some snapshot of the inventory levels and checking just after is merged and fixing might avoid stress for the customer :-) I would do that I think personally... :see_no_evil:
