### ISSUE TITLE
Investigate spree_auth_devise & upgrade it

### ISSUE THREAD

**Issue by HugsDaniel** [openfoodfoundation/openfoodnetwork#2989]
## Description

Following what has been found in #2986 and #2985 , we should investigate our fork of spree_auth_devise and move forward to the 2-0-stable version.

Highlighted points to be investigated so far : 
- [ ] User vs LegacyUser

**Comment by Matt-Yorkley** [comment]
We discussed that our fork of spree_auth_devise needs to be investigated at some point, but that it's not a priority for the upgrade unless it needs fixing.

**Comment by luisramos0** [comment]
hey @Matt-Yorkley @HugsDaniel 
in ofn 2-0-stable I see spree_auth_devise (2.0.0). that means the upgrade is done as part of the spree upgrade. did you mean something else? otherwise I'd close this or move to a tech debt issue outside of the spree upgrade. if we keep this as a tech debt issue I think we need more details.
for info on what legacyuser is, see this https://github.com/spree/spree/commit/444eb0c07bc8b44182f6aaa40c934151df05253e

**Comment by luisramos0** [comment]
From my very quick investigation:
- we are using branch 2-0-stable of our for of spree_auth_devise
- this dependency is not creating any trouble for the spree upgrade right now

So, I think this should not be part of the spree upgrade.

I think we can have this issue as tech debt outside the upgrade to represent the need to document what does our fork contain and also the upgrade of this dependency.

**Comment by luisramos0** [comment]
We no longer depend on spree_auth_devise :tada: 
I'll close this issue now.
