### ISSUE TITLE
Unable to import Inventory

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3116]
## Description
On Australian production the CSV inventory template looks like this:
![image](https://user-images.githubusercontent.com/10843056/48885298-ef6baf00-ee7b-11e8-8f8c-a90dbb670c77.png)
Is this template up to date? Should this template also include On Demand and Category?

I have attempted to import the following csv with the Inventories upload option:
![image](https://user-images.githubusercontent.com/10843056/48885498-a10ae000-ee7c-11e8-8775-c3538114ffcd.png)

I don't fully understand how the Inventory upload tool should operate, so I tested the functionality which I guessed it would have:
**1) In the shop's Inventory, this product was already on the shop's inventory list. It was set to inherit all details from the product list. I wanted to import this csv to override the price from $30 to $20 and stock from 0 to 100 On Hand**
- When I uploaded the csv, I got the following error... despite the fact that this product does exist.
![image](https://user-images.githubusercontent.com/10843056/48885890-fe536100-ee7d-11e8-8532-f20f251d3aa4.png)

![image](https://user-images.githubusercontent.com/10843056/48885614-078ffe00-ee7d-11e8-8d6c-6e1a0ca88662.png)

**2) In the shop's Inventory, this product was in the shop's HIDDEN list. I was testing whether uploading the CSV would move the product into the INVENTORY list**
- I got the same error as above

**3) In the shop's Inventory, this product was in the shop's NEW list. I was testing whether uploading the CSV would move the product into the INVENTORY list**
- First i got an error 'category can't be blank' - this is confusing because the template doesn't include Category
- I added Category (oil and spreads) and then I got the same error as in 1) above.

![image](https://user-images.githubusercontent.com/10843056/48886311-9c93f680-ee7f-11e8-8eee-2f50bd3d6b82.png)

* note screenshots above have inconsistencies with capital letters, but this wasn't the issue
## Expected Behavior
Please tell me how the Inventory upload tool should work?
- Should it be used to move a product from the NEW list to the INVENTORY list?
- Should it be used to only update overrides on a product which is already on the INVENTORY list?
- Should it be used to move a product from the HIDDEN list to the INVENTORY list (and vice versa)?

## Actual Behavior
See description

## Steps to Reproduce
Here's the CSV - https://docs.google.com/spreadsheets/d/1Qby6YOjGuUz0ybz75HrKQwxmQDiYY7gowPYs-d5rQs8/edit#gid=0 
You can try to upload it on Aus production for Producer of Peanuts and Demo Hub

## Severity
s3 - not urgent yet, as the feature isn't launched.

## Your Environment
Aus production 
PC, Chrome

**Comment by daniellemoorhead** [comment]
Ping @myriamboure @RachL FYI as the product owners of Product Import :)

**Comment by myriamboure** [comment]
@sstead about category, it doesn't have to be in the template for inventory. You don't need the category to identify the product, and you can't modify that information in inventory, so it is not needed.
On the other hand, on-demand is needed yes, it was clearly specified in https://github.com/openfoodfoundation/openfoodnetwork/issues/2481#issuecomment-415803595 and the spreadsheet, so if it not, that's an issue.

Actually I checked with the list and the current template and we miss three fields in the inventory template. 
- variant_unit_name
- sku
- on_demand

I opened a separate issue to avoid mixing with the other issue  you describe here Sally, so on this first point conversation can move [there](https://github.com/openfoodfoundation/openfoodnetwork/issues/3160).

**Comment by myriamboure** [comment]
@Matt-Yorkley do we need the category field in inventory as well to be able to identify the product? We removed it from the template because we said it was not needed to identify and not possible to modify, but were we wrong ?
If that is the case, it is possible that the other issues identify by Sally are related, right? Like the "product can't be found" problem could be linked to that ?
But it seems even when she adds category, the error is still there... can you clarify what's happening @Matt-Yorkley ?
Thanks !

**Comment by myriamboure** [comment]
@Matt-Yorkley I agree with @daniellemoorhead that finishing PI should be your first priority. When trying to make too many things move forward in parallele things get stuck for weeks... like this one since 2 weeks ;-) Can you please check what's the issue ? Thanks !

![](https://media.giphy.com/media/l1J9ETWjKTdN7FZOE/giphy.gif)

**Comment by Matt-Yorkley** [comment]
This was an odd one, because there are specs covering inventory import that were passing. It turns out adding the `display_name` field in the CSV causes these errors, and it seems to work fine if that field is removed. The `category` field is irrelevant in inventory import. I've added an extra test and updated the CSV template for inventory import.

**Comment by Matt-Yorkley** [comment]
I couldn't replicate the issue in manual or automatic tests. The "Category can't be blank" error only shows when importing into product list, and the "Product not found" error shows when the item doesn't match on either `name`, `display_name` or `unit_value` for any existing variants.
