### ISSUE TITLE
Fractional cents in fee calculations can result in price discrepancy

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#312]
Say I have an item priced $55.55, and that item has a 10% fee on it. When I add two of these to my cart, the item price should be $61.11 and the total cost should be $122.22. Instead, I see a total cost of $122.21.

What is happening here is that the 10% fee is being calculated and stored for the entire line item of quantity two (55.55 * 0.1 * 2 = 11.11). When we want to calculate the item price inclusive of fees, we divide this by two, giving 55.55 + (11.11/2) = 61.105. We round this up to 61.11.

However, when we calculate the total for the line item, we simply add the adjustment. 55.55*2 + 11.11 = 122.21. Because there is no intermediate rounding, we end up one cent lower.

This is not a terrible UX for the customer - they are offered a price, and at checkout it ends up being a bit cheaper. However, it's not fantastic either - they would not expect any discrepancy.

Fixing this is hard. We'd need to change how adjustments are applied to orders. And by the numbers, nothing's wrong - everyone is being charged the correct amount of money.

I'm leaving this as it stands for now, but we might want to consider changing it in the future.

**Comment by NickWeir63** [comment]
I think this bug is what is causing a discrepancy discovered by a Stroudco shopper who ordered 8 of one item and ended up with a 2p (£0.02) disprepancy.  However the discrepancy was not in her favour (whereas the issue Rohan is describing above would be in her favour)
Anyway here is what we see.  The shopper orders 8 x 1 pint goats milk and gets this basket total (note 2p difference between line total and order total)
![screenshot 2016-05-11 16 55 45](https://cloud.githubusercontent.com/assets/10517702/15187549/64570114-1799-11e6-979b-1f64248b35a2.png)
We can see that 

- The producer's master price is 86p
- We add 20% which comes to £1.032
- When multiplied up by 8 pints this comes to £8.256

 
@OliverUK suggested would it be possible to disregard the third decimal place and multiply up £1.03 instead of £1.032......?

Also - why are the line total and the basket/order total different?

Thanks

**Comment by OliverUK** [comment]
@RohanM @NickWeir63 

Looks like the line total is calculated using £1.03 x 8 = £8.24. Does it drop the 2 or round down?
The order total uses £1.032 and then rounds up. 

We'll continue getting strange results until the sales price has any invisible decimals (like here the 2) removed before further calculations, IMHO.

**Comment by lin-d-hop** [comment]
@OliverUK Could you give us an idea of how often this is happening on your end?

**Comment by OliverUK** [comment]
@lin-d-hop My guess is all the time. I notice it every time someone buys only one item, because that's when you can immediately see the difference between the line total and order total.

**Comment by daniellemoorhead** [comment]
Hey @RohanM, given this bug is also overcharging customers it seems that we do need to fix it.

In your original comment you said:

> Fixing this is hard. We'd need to change how adjustments are applied to orders. And by the numbers, nothing's wrong - everyone is being charged the correct amount of money. I'm leaving this as it stands for now, but we might want to consider changing it in the future.

Do you have an idea of how to fix it? And if so, do you know (order of magnitude guestimate, like a week, 2 weeks, a month, way longer) how long it will take to fix?

**Comment by NickWeir63** [comment]
thanks @serenityhill for talking to Rohan about a time estimate on this

**Comment by RohanM** [comment]
Hi everyone,

This is on my radar and I'll look at a solution the coming Wednesday (in a week).

**Comment by RohanM** [comment]
I've just opened PR #1127 that addresses this problem by performing rounding earlier when calculating adjustments for the cart.
