### ISSUE TITLE
Customer Hub ID - Hubs can have IDs for their customers 

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#315]
Add a field to the customer table which will allow organisations transferring from another system to maintain their previous customer IDs.

**Comment by pmackay** [comment]
As per discussion, could work to have a customer number within a hub, which could come from a legacy system, e.g. Stroudco or be populated automatically for new hubs.

**Comment by lin-d-hop** [comment]
Renamed to Customer Hub ID. I guess a customer would have to be able to have many of these, meaning many to many relationship (many customers each with many hubs).

As per conversation... this is a blocker on data migration until we have a DB field for it. Doesn't have to be implemented fully implemented on our side for a bit longer.
@RohanM @oeoeaio @kirstenalarsen What do y'all think on the possibility of a new table(?) to hold the internal ID field for a hub?

**Comment by kirstenalarsen** [comment]
Hi @lin-d-hop, just to confirm that @oeoeaio and I are going to have a look at this tomorrow morning and either do or put some notes here. Will respond to q. re. table . . sorry for block

**Comment by kirstenalarsen** [comment]
okey dokey. Sorry for the delay, we wanted to make sure we'd thought about this a bit because the way it is done sets the stage for a bunch of other things . .

We think that an OFN shopper will have multiple Customers - one for each Enterprise they have shopped through. Then this Customer can (over time) start being used to manage accounts, memberships etc. In the first instance this customer should just be connected to an email (not a User) because the system currently allows checking out as guest (therefore a User isn't actually created for everyone).

So the most basic step is:
- create a new Customer model which has the fields email; enterprise_id; and a text field for customer number / code / whatever you want to call it
*** hopefully this will be enough for your database migration and calling the field where you need it in reports.

However to be useful beyond that there will be some other requirements that we will probably need to break out into separate features
1. Build interface to manage customers and their number (and other info to be added later) - particularly useful for other Enterprises who want to use this but don't have existing data to migrate
- could be done with a new tab on the enterprise management panel (e.g. like contact; shop preferences etc), with an angularised search e.g. just start typing email or number [? name?]
2. Link existing orders to new Customers
3. When new email creates an Order, auto-generate new Customer and link the Order
4. When existing email creates an Order, auto-link to Customer

Does that make sense @lin-d-hop?

**Comment by lin-d-hop** [comment]
Seems to make sense to me :-)

I'm totally new to creating new models and the like but I just gave it a go:
1) Ran the command
rails g model Customer email:string enterprises:references customer_code:text
2) Ran db:migrate.

So in order to do a PR on this my thinking is that I just add the following files:
app/models/customer.rb
db/migrate/20150122123742_create_customers.rb
spec/models/customer_spec.rb
And that the schema.rb file is updated when we run our own db:migrate. Is that right?

So there's a pull request with that much in it..... #329

Maybe it's all wrong anyway :-)

**Comment by kirstenalarsen** [comment]
hi lynne, as far as I know this is great . . but unfortunately it's a long weekend in jan in australia, and as you're probably aware this is a low productivity time. I forgot that rob was away for the long weekend, so sadly no one can review and get back to you before next week :( so sorry for delay on your quick turnaround. when are you leaving uk?

**Comment by lin-d-hop** [comment]
This has now been added in PR #392 

Lets see if its up to scratch...

**Comment by RohanM** [comment]
I've removed the aus review label as that PR (now #399) is merged :)

**Comment by lin-d-hop** [comment]
Closing as merged
