### ISSUE TITLE
[i18n] Untranslated "producer profile" in pack selection page (front end)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3162]
![capture du 2018-12-02 00-13-02](https://user-images.githubusercontent.com/8135376/49333884-6107d380-f5c7-11e8-97a7-7e24eb69dc98.png)

I guess also "PRODUCER PROFILE" here should be replaced by the name of the enterprise that was just created...

**Comment by amers185** [comment]
If this issue is still open, I would like to work on it.

**Comment by sigmundpetersen** [comment]
Please have a look at our wiki page on i18n for an introduction on how we work on translations https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29

**Comment by luisramos0** [comment]
fyi, this page will be tested in https://github.com/openfoodfoundation/openfoodnetwork/pull/3609
I dont think 3609 fixes this bug though.

**Comment by amers185** [comment]
@sigmundpetersen Thank you. I am familiar with the project because I was part of a group of college students who recently worked on the OFN documentation issue. I want to continue contributing in an individual capacity even though our group project ended. @luisramos0 Shall I continue working on the issue even if it will be tested in 3609?

**Comment by luisramos0** [comment]
hi @amers185 
nice! thanks for your interest!

I just checked. you can fix this, it's independent of #3609
I leave you a hint ;-) https://github.com/openfoodfoundation/openfoodnetwork/blob/fb29a7c7c210e22863a6bbd4a1619da0d1c75b19/app/views/admin/enterprises/welcome.html.haml#L7

**Comment by amers185** [comment]
Ah thank you. So, on a high-level, this is not a missing key issue? Rather its more of not calling the right profile?

**Comment by luisramos0** [comment]
no, you have to make the code call the t function so that it looks up the translation key.

**Comment by amers185** [comment]
I feel rather dumb for asking this since I have only really inserted your code but this modification: "#{"producer " - if @enterprise.is_primary_producer? t('.producer_profile') - else t('.profile')}profile" in my IDE gives me an expected expression error at the dash before else and an expected herdoc end error? I have looked over different ways to try nested loops within tags for HAML but I am not quite share what I am doing wrong here. Further, how can I proceed to check for changes I make on the local host? As in, is there a go to strategy to navigate the local host given I do not know where this page is on the actual website? I cannot even access the french version on my local host. Again, my apologies for all these questions.

**Comment by luisramos0** [comment]
welcome to rails routing :-D
re second question: you need to look at the routes and then follow them to controllers and views.
look in admin.rb
- resources :enterprises do
welcome is a normal member, so, with the old sample data: 
admin/enterprises/enterprise-2/welcome

you can load the old sample data locally with bundle exec rake ofn:dev:load_sample_data

the new sample data is loaded with ofn:data:sample_data

re the code, I'd have to do it myself to see, I am guessing the syntax a bit here but you could also try:
```
- profile_translation_key = @enterprise.is_primary_producer ? '.producer_profile' : '.profile' 
= t(profile_translation_key)

```

**Comment by amers185** [comment]
I come back with more questions. Your advice was very helpful. I modified the syntax slightly and replaced one of the "=" signs with a ";". While that got rid of the original error, I still got this error:
![Screenshot from 2019-03-21 16-49-23](https://user-images.githubusercontent.com/31739308/54787429-b0ffba00-4bf9-11e9-802a-51e0c62d1cd8.png)
I have a hunch that it has to do something with me being unable to load data because I get these errors when I run the commands you mention:
![Screenshot from 2019-03-21 16-50-09](https://user-images.githubusercontent.com/31739308/54787482-ddb3d180-4bf9-11e9-975e-b82d5057f082.png)
 @luisramos0 Any help would be appreciated.

**Comment by luisramos0** [comment]
you can follow the error messages and run --tasks to see what tasks you have available
the tasks I get are:
rake ofn:dev:load_sample_data
rake ofn:sample_data

re the code, I recommend you read about ruby string interpolation and also about haml hyphen

Even if that one liner worked it wouldnt be accepted, it's way too much for a single line.
You can do this in a helper too.

What was the problem with my suggestion above?

**Comment by sigmundpetersen** [comment]
@luisramos0 in the previous post you suggested `ofn:data:sample_data` while in the last post the tasks you list mention `ofn:sample_data`

Could this be a typo that prevented @amers185 from running the task?

**Comment by amers185** [comment]
@luisramos0 : I ran the rake --tasks command and rake --trace commands. I am getting some errors. Perhaps, I have set up the project incorrectly and I need to to set it up again. I get this screenshot:
![raketasks](https://user-images.githubusercontent.com/31739308/54828244-c15b7780-4c81-11e9-8539-cfa70b84e816.png)
I further modified my code to make it modular and I get the same error:
![modular](https://user-images.githubusercontent.com/31739308/54828393-11d2d500-4c82-11e9-8820-5d15184d9f4a.png)
With your code, I was getting this error:
![yourcode](https://user-images.githubusercontent.com/31739308/54828525-5d857e80-4c82-11e9-99b8-be6355c82d3e.png)
I intend to spend the weekend going over different tutorials and bolster my knowledge. Thank you for your patience with me.

**Comment by amers185** [comment]
On another note, I tried update my fork and bring it up to master by doing a hard rest but I get this: Permission to openfoodfoundation/openfoodnetwork.git denied to amers185. I was previously working on @kevinchristianson's fork and when I trying to do a hard set over their, the commands go through? What gives?

**Comment by luisramos0** [comment]
re rake, the solution is in the error message ;-) prepend with "bundle exec"

re code, you merged my code in a single line (line 7, you need to split it in multiple lines as I shared.

**Comment by amers185** [comment]
So the solution works?

**Comment by luisramos0** [comment]
that instructions in a single line is not acceptable imo, you need to at least split it into 2 lines as I shared above.

to test translations you need to edit application.yml and change it to french and see if translations from fr.yml are used.
you may need to add translation keys to both fr.yml and (for testing only) fr.yml

**Comment by amers185** [comment]
I have split it up as you suggested. It looks like this now:
![Screenshot from 2019-03-22 12-09-43](https://user-images.githubusercontent.com/31739308/54840737-9d0c9480-4c9b-11e9-8cac-e71a2ecf8e13.png)
When I hover over .producer_profile, it says that that the value for the key cannot be found in any locale. Even though the key exists in en.yml: 
![image](https://user-images.githubusercontent.com/31739308/54841032-579c9700-4c9c-11e9-9f53-b69a7f3178a8.png)
When I run it in the browser, I get this:
![image](https://user-images.githubusercontent.com/31739308/54841065-6f741b00-4c9c-11e9-97e5-37eba56d8220.png)

**Comment by amers185** [comment]
I have looked into string interpolation. According to several tutorials, this should work:
`"#{@enterprise.is_primary_producer ?  t('.producer_profile') : t('.profile')}"` And it shows the following page: 
![image](https://user-images.githubusercontent.com/31739308/54849718-12d02a80-4cb3-11e9-80a4-d588921db51a.png)
In this case, tried changing the producer_profile value in en.yml file but the change does not get reflected in the view. So I am wondering what is happening there?

Unfortunately, I am unable to make the nested format with multi-line conditionals work and it gives the following page:
![image](https://user-images.githubusercontent.com/31739308/54849817-5b87e380-4cb3-11e9-92a6-126468ac580f.png)
This is my code for it:
![image](https://user-images.githubusercontent.com/31739308/54849939-b0c3f500-4cb3-11e9-9772-1abd3d821318.png)
So, I am at quite a loss. Sorry for the deluge of messages. @luisramos0

**Comment by luisramos0** [comment]
Hey, you can do it!
string interpolation is for simple things, that code will never be acceptable with an if statement inside the interpolation.
you have to use view helpers or at least the hyphen on a separate line, before you call the t function
I wouldnt even try to fix that if inside the interpolation

**Comment by luisramos0** [comment]
I had a look at it, my original suggestion is correct and works:
```
- profile_translation_key = @enterprise.is_primary_producer ? '.producer_profile' : '.profile' 
= t(profile_translation_key)
```
All you need to do afterwords is to add the translation key in the right spot, because this is a lazy loading translation (with the dot). See [here](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#development) for more info. It's a good place to learn, I think most of this is generic rails i18n.
to look up lazy loading you need to see where the file is
you are in app/views/admin/enterprises/welcome.html.haml
that means your translation key namespace is admin.enterprises.welcome, so here, t('.profile') means t('admin.enterprises.welcome.profile') so, the translations key must go under:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6cd07cd10795ce474dc48ed6735bad00cb13c5d2/config/locales/en.yml#L913

![Screenshot 2019-03-22 at 21 52 14](https://user-images.githubusercontent.com/1640378/54855073-e0432380-4cec-11e9-8584-58d49a64ff8f.png)
![Screenshot 2019-03-22 at 21 52 56](https://user-images.githubusercontent.com/1640378/54855074-e0432380-4cec-11e9-9035-db7abdb0f3df.png)

you dont need to test French, just make sure the en.yml key is being picked up, as I do in the screenshot above with custom string Profileee, in this case, the en.yml file should contain "Profile" and "Producer Profile". The French part is done after the PR is merged.

I hope this helps.

**Comment by amers185** [comment]
I was able to follow your instructions and it works now. Thank you so much for guiding me. I am sorry for not picking up your hints. I kept trying to make it work with string interpolation and then kept changing the wrong keys. I undid the changes I made earlier and made the correct changes. This was a very instructive experience. Thank you for being so patient. I guess a PR follows?

**Comment by luisramos0** [comment]
yes please!
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Making-a-great-pull-request
