### ISSUE TITLE
[i18n] "groups" menu is not translated in backoffice

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#3289]
## Description
Enterprise user with group menu don't see translation for the menu entry

## Step to reproduce

1. Login as super admin or as an enterprise user with ability to manage a group
2. Look at the "groups" menu, it is not translated

## Screenshot
![image](https://user-images.githubusercontent.com/6525576/56751186-c54d4e80-6785-11e9-8720-3708443b4acd.png)

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by RachL** [comment]
@myriamboure "groups" menu only exist for super admin right? So I think this should be downgraded to s4. Plus if I'm not mistaken the other yellowed translation are correctly translated.

Can you update the issue or give me your go to update the issue this way:

- add profile and URL
- crop the screenshot so that only the groups translation appears
- put it in the bug template as an s4 (we can leave with stuff not translated for super admin)

I think these info are mandatory if we put this as a good first issue.

**Comment by sigmundpetersen** [comment]
It's not only available for super admins but a super admin has to be contacted [to create one](https://guide.openfoodnetwork.org/advanced-features/groups/group-page) 🙂

**Comment by RachL** [comment]
Ok thanks @sigmundpetersen

**Comment by luisramos0** [comment]
this has been fixed in v2. moving to "test ready" to be verified by a tester.

**Comment by RachL** [comment]
@luisramos0 you are right :) Ichecked all the translations before v2. Need to do a second round...Closing the issue!
