### ISSUE TITLE
Unticking payment options not saved - display only functionality

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3314]
## Description

When unticking the payment boxes so none are selected, the user selects save, the page loads, indictating this is being processed and it then takes you to the enterprise profile page. When you go back to look at the payment option, those you unticked, are still ticked.

Following these instructions to try and set up a display only shop - https://guide.openfoodnetwork.org/advanced-features/order-cycles/display-only-order-cycles

## Expected Behavior

When unticking an option, it should save and remain that way, unticked

## Actual Behavior

The unticked boxes are not processed after saving - when the user goes back to look at the payment options, the edits have not pulled through.

This has been tested on UK production, using OFN UK Demo Hub and Audacious Veg

## Steps to Reproduce

1. Setup an active and live order cycle
2. Go to payment options and untick all options
3. Save
4. Go back to the payment options and see the changes have not been pulled through

## Animated Gif/Screenshot

http://recordit.co/stqpISPrmY

## Context

This is functionality we have available on the user guide, so it would be good to have it work, or temporarily removed of the guide?

## Severity

There appears to be no workaround for this functionality, however I'm not sure how commonly it is used - s2?

## Your Environment

* Version used: 
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Windows10

## Possible Fix

Saving changes actually pulls through

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Display Only Order Cycles not working correctly](https://trello.com/c/WQo2uSL9/353-display-only-order-cycles-not-working-correctly)

**Comment by myriamboure** [comment]
@sineadfenton this issue appeared some months ago, some dev tried to work on it but in inhided a big chunk to be chewed and we opened a wishlist to be prioritized. It's more than just fixing a bug, it's kind of a refactor of the whole logic. https://github.com/openfoodfoundation/openfoodnetwork/issues/2023
Here is the wishlist: https://community.openfoodnetwork.org/t/hubs-manages-without-friction-shipping-and-payment-methods-and-can-grant-permissions-on-them/1269
I suggest you vote on this wishlist if we want the community to work on it sooner rather than later. We definitely know we need to work on it in the coming months anyway, but you know, we have so many priorities... So I think either we agree it is not considered as a bug and prioritize the wishlist (and we can close that issue), either we question that and reprioritize as a bug but it will be a big job, needs inception time on it with POs and devs. And we need anyway to prioritize compared to other bugs.
@lin-d-hop @daniellemoorhead until now we were in the wishlist direction, do we keep as is and close this ?

**Comment by WalkingBlackBear** [comment]
I just stumbled across this bug today as well - but it's not limited to payment options, it involves shipping methods as well.  Exact issue though, unchecking it doesn't actually save.  I've been trying to find workarounds to allow people to browse when the order cycle is closed.

Odd as it may seem, a complaint we've fielded many times in the past when people couldn't view products when the OC wasn't open was that we were "trying to hide our prices from them."  I never really thought of it being a pricing transparency issue, but it seems that perception exists when people can't browse outside of OCs.

Personally, I compare it to you can't really browse a Farmer's Market when they're not set up and open for business either ... same thing.  But being online, I guess there's an expectation of 'always on' shopping.

**Comment by sigmundpetersen** [comment]
Closing as handled by wishlist item
