### ISSUE TITLE
[Spree Upgrade] Order Cycles don't update to reflect changes made after they're created (product cache in v2)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3392]
## Description
I'm noticing that if I make changes to things after an OC has been created, the changes that I made won't carry through to that OC in the shopfront.

Changes I've made that have not carried forward into the shop include:
- Changing the category of a product - the shop filter still sees it as the past category
- Adding a fee to the OC - the fee won't show in the shop like it should
- Adding a new product to the OC - the new product won't show
- Price - if I change the product's price it won't update

## Expected Behavior
The shopfront OCs should always show the up to date information

## Actual Behavior
Once an OC is open in a shop it won't update 

## Steps to Reproduce
1. Open an OC with some products in it
2. See the price of the products in the shop
3. Change the price of the products
4. See - has the price updated?

## Animated Gif/Screenshot
https://www.useloom.com/share/403e9539031e402390468cb03284372b?focus_title=1&muted=1

## Severity
Not on production 
bug-s4: it's annoying, but you can use it

## Your Environment
French staging, Chrome, PC, Desktop, Spree upgrade

**Comment by luisramos0** [comment]
this issue will be related to #3391 #productcache

**Comment by luisramos0** [comment]
can we validate in staging FR that this is not happening with disabled cache and close it?
we have #3391 to represent the product cache issue.

**Comment by RachL** [comment]
* Open an OC with some products in it => OK
* See the price of the products in the shop => OK
* Change the price of the products => OK
* See - has the price updated? => YES

@luisramos0 is it normal to not have a PR attached?

**Comment by luisramos0** [comment]
oh my god, it just works! can we deploy live? 🤣 

-- is it normal to not have a PR attached?
welcome to ofn v2, it just works 🚀 

now, back to reality: staging FR has a hacked version of v2 that includes #3404 
I did this so that we dont have to wait for the PR to get approved, tested, merged to master, then merged to v2, to test this. this way we are already sure it was a problem with the cache that needs to be looked at as part of fixing #3391
I think we can close this one.
Thanks @RachL 

any other bugs in v2? go for it 💪

**Comment by mkllnk** [comment]
@luisramos0 Can this issue be closed? It's a bit confusing to have an issue be treated like a PR. ;-)

**Comment by luisramos0** [comment]
yes, let's close this.
