### ISSUE TITLE
Hub's suppliers can prepare individual orders for the hub's customers

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#3442]
Prioritised by the global community in Jan 2019. 
More detail here: https://community.openfoodnetwork.org/t/hubs-suppliers-can-prepare-the-invidual-orders-for-the-hubs-customers/1151/21

**Comment by RachL** [comment]
wooopsy I forgot about the product feature board! @daniellemoorhead I created another epic: https://github.com/openfoodfoundation/openfoodnetwork/issues/5051

(WIP still need to catch up with Pau to finish it and the linked issues).

The new epic might be just a first step of this one, or it might be the full step: future will tell us. I would close this one and leave the discourse post to follow if anything is missing and create new epics along the way. But that's mainly because I would like to have less open issues in GH and I might be in cleaning mode :D What do you think?
