### ISSUE TITLE
[i18n] missing translations orders, bulk orders and subscriptions

### ISSUE THREAD

**Issue by berteh** [openfoodfoundation/openfoodnetwork#3452]
Some translations missing in current BE instance (and thus some others too I guess?)

orders:
![dashboard-orders-missing-translations](https://user-images.githubusercontent.com/36950/52400473-84676700-2abf-11e9-980d-7f79f3c8d411.png)

bulk orders:
![dashboard-bulkorders-missing-translations](https://user-images.githubusercontent.com/36950/52400504-9c3eeb00-2abf-11e9-94fb-485a2a2a3b75.png)

create new subscription step 3:
![dashboard-new-subscription-step3-missing-translations](https://user-images.githubusercontent.com/36950/52400518-a660e980-2abf-11e9-8d78-ebd8a22d235b.png)

**Comment by berteh** [comment]
OFN version was 1.25.0 according to

**Comment by luisramos0** [comment]
I think these are all translatable already, it will just be a problem with fr_BE language on transifex.
you can verify that by looking at FR_fr in openfoodfrance:
![screenshot 2019-02-07 at 09 53 30](https://user-images.githubusercontent.com/1640378/52403316-59c8de80-2abe-11e9-9991-489c57b26e93.png)

So, this is not a GH issue, it's a translations issue.
I added you to #translations on slack

**Comment by berteh** [comment]
ok; thanks.

**Comment by luisramos0** [comment]
actually there are a few bits in subs to be fixed, they are in this issue:
https://github.com/openfoodfoundation/openfoodnetwork/issues/2874

I didnt find an issue to fix the dollar sign though! it's also showing up in openfoodfrance. @myriamboure is the subscriptions product lead.

**Comment by sigmundpetersen** [comment]
I think fixing the currency symbol is actually in Code Review in #3451 🎉

**Comment by luisramos0** [comment]
yes, thats it!

**Comment by sigmundpetersen** [comment]
Actually @luisramos0 there are missing translations on the order page also on Norway 1.25.0. I guess in France they have found the missing translations manually and added to fr.yml. 

So let's keep this open.

**Comment by luisramos0** [comment]
please give specific examples @sigmundpetersen otherwise there's no way to fix it :-)
screenshot?

**Comment by sigmundpetersen** [comment]
![orders](https://user-images.githubusercontent.com/1451633/52479536-3f1f6400-2ba9-11e9-9eb0-ea3d82031e67.png)

**Comment by luisramos0** [comment]
ah, nice one @sigmundpetersen 
I am not sure exactly how spree translations are picked up but these entries are spree default translations. That's why FR and ES get these and nb and FRbe dont. These entries are not in en.yml and they don't get to transifex but the translations are included in some way through spree.

in spree v2, I believe this will not happen and as part of the upgrade we are moving most spree translations to our en.yml, for example, https://github.com/openfoodfoundation/openfoodnetwork/commit/4450380cb038434354456e175e514ec42ad4cf80

@mkllnk I think you know how this works, right?
1. how come show_only_complete_orders is not in transifex, it is translated in FR and ES, but not in nb or FRbe?
2. has this stopped working in spree 2?

Thanks!

**Comment by mkllnk** [comment]
You are right, there are translations coming from Spree. But not all Spree text is translated. We can copy them into our English source file to make them available for translation in Transifex. We can't rely on Spree's translations.

**Comment by luisramos0** [comment]
I'll have a look at this one as I tackle #3140
