### ISSUE TITLE
Add social media links in footer of all emails to customers and users

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#3492]
Facebook link at the bottom of the welcome email sent to a new producer/user is broken for OFN UK and there is no link to the Open Food Network UK Instagram account. 

## Description

Social media is an effective way of communicating and interacting with new producers and customers.  At the moment when a person signs up to OFN UK they receive a welcome email.  At the bottom of this are links to Facebook and Twitter.  The Facebook link connects to the wrong page.  It would be good to also link to OFN UK Instagram account.

## Expected Behavior

The Facebook link should go to 
https://www.facebook.com/openfoodnetworkuk/
There should also be a link to Instagram 
https://www.instagram.com/openfoodnetworkuk/

## Actual Behavior

At the moment the Facebook link goes to
https://www.facebook.com/OpenFoodNetUK
And there is no link to Instagram.

## Steps to Reproduce

1. Register as a new user
2. Receive welcome email and follow social media links at bottom of email.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/52785610-4be00400-3050-11e9-9be5-fb08f2a5692e.png)

![image](https://user-images.githubusercontent.com/45104035/52785618-54383f00-3050-11e9-9e7f-b10842d1013d.png)

## Context

Connecting and interacting with customers and producers via social media is essential for online business today.

## Severity

bug-s4

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by daniellemoorhead** [comment]
@lin-d-hop I think this is something that can be set in the super admin config? Regardless, I think it's something the UK team can fix and doesn't require a code change. Feel free to enlighten me if otherwise. 😄 

@lbwright22 according the the severity definitions this isn't a severity 2 bug as it doesn't stop users from completing core tasks. Inability to access facebook from the email is annoying, but doesn't stop anyone from using the actual system. So I'm downgrading this to a severity 4 (could be a 5, but I'm ok with a 4)

You can read about the severity levels here: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

**Comment by lin-d-hop** [comment]
@lbwright221 when you took a look at this before opening the issue did you try to fix it in the Super-admin -> Configuration -> Content tab first?

If not please have a go at that :-)
