### ISSUE TITLE
SKU showing up incorrectly on different reports for variant products

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3528]
## Description

The reports are showing up different SKU values for the same product.

The product will have a code of XXXX, within the product report this is shown correctly, but in the order cycle customer totals this is incorrect showing up as XXXXY - two different reports of the order cycle customer total have been run, and both show different SKUs which are not the true SKU

## Expected Behavior

SKU should be the same for a product everywhere

## Actual Behaviour

The product will have a code of XXXX, within the product report this is shown correctly, but in the order cycle customer totals this is incorrect showing up as XXXXY - two different reports of the order cycle customer total have been run, and both show different SKUs which are not the true SKU

This is happening with hodmedods MASTER in UK production

## Steps to Reproduce

1. Look at a the SKU for Camelina   Seed, Non-Organic - 10 x 250g (250g x 10) - NGCSCX (left)
2.  Customer totals report run on the 12th states NGCSR2 (top right)
3. Same report run today only sates NGCS (middle right)
4. All products report states NGCSCX which is correct (bottom right)

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/28807449/53159602-10988480-35be-11e9-9113-9ef28b543047.png)

## Context

SKU is a key field that allows OFN to operate with other systems. If it can't be reliable then it renders the reports useless, making OFN impossible to use for users that need to use reports to interoperate with other systems in their businesses.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:
* Browser name and version: chrome
* Operating System and version (desktop or mobile): windows 10
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by sineadfenton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order cycle reports wrong SKU for variant](https://trello.com/c/3UCKpRMA/380-order-cycle-reports-wrong-sku-for-variant)

**Comment by lin-d-hop** [comment]
This bug is now blocking a major new user that has signed up to OFN UK. This user is a really big win for OFN and if we can't sort this issue it will be a major blow to our reputation. It blocks non-critical functionality with no workaround. I am increasing the priority to S2. I know we have a lot of priorities and if you disagree please do say so.

**Comment by mkllnk** [comment]
I'm reading in the code and it seems like the displayed SKU is the SKU of the first variant within the same order. The logic to group line items by order is quite complex. I'm not sure yet how easy it will be to solve.

**Comment by kirstenalarsen** [comment]
go @mkllnk you can do it . . I am feeling @lin-d-hop 's pain - I HATE that feeling when a new user that you really want hits something stupid and annoying like this :(

**Comment by mkllnk** [comment]
Oh, actually, the report is not listing variants but products. @lin-d-hop I now think this is not a bug but you expected a variant's SKU while you got a product's SKU. That makes sense since there can be multiple variants of the same product in one order. What should it print then? Options forward:

* Leave it as is.
* Introduce a new column for variant SKUs, printing them all together like `NGCSCX NGCSCY`.
* Change the current SKU column to print the product's and the variant's SKUs like `NGCS NGCSCX NGCSCY`.

This decision needs some input from other product owners. We don't have Sally any more. @RachL do you know how your users use this report? @kirstenalarsen any idea?

**Comment by mkllnk** [comment]
I won't finish this today, waiting for input from @lin-d-hop. Someone else can take over or I work on this on Tuesday again. My work so far: https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:3528-order-cycle-customers-report-sku?expand=1

The line of code where the SKU is printed:
https://github.com/openfoodfoundation/openfoodnetwork/blob/130ba64f2f101da797125bf7ad73bbeb7e83a12b/lib/open_food_network/orders_and_fulfillments_report.rb#L225

**Comment by lin-d-hop** [comment]
@mkllnk So this feels like another issue caused by our changing use of variants over time. This feels like a similar issue to the price issue we sometimes see - product has a price, variants have prices. But we never want to show the product price, we always want to show the variant price. I appears that SKU just hasn't been rigorously used yet by anyone (unlike price) so we haven't had to update reports and thoroughly for this field.

SKUs logically should be linked to variants, not products. The point of SKU is to identify stock keeping units. If someone asks "How many tshirts do you have?" you can always tell them "Sum(sizes)". But if someone asks "How many _small_ tshirts do you have?" you want to be able to answer that question too. Thus SKU should consistently report the most granular identification it can. If a variant name is specified (eg small or 250gx10) then the appropriate SKU should also be displayed.

Given the point of SKU is to identify a stock unit, and stock units must be variants, I would say that:
- We want the last option - one row per variant. Essentially Orders_and_Fulfilments is printing line items. And line items are variants, not products.
- To ensure this doesn't affect existing users using SKU (are there any?) do we need to do a DB migration to update any variant SKU to the product SKU where the product SKU exists but the variant SKU does not exist?

@RachL Is there anyone using SKU in France that might be affected? @kirstenalarsen anyone in Aus?

**Comment by RachL** [comment]
@lin-d-hop a few users are using it in France. I agree that one row per variant is the way to go.
