### ISSUE TITLE
[Spree Upgrade] Error 500 when trying to add a product

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3529]
## Description
I've created the Enterprise "Le Jardin de Rachel". I wanted to create my first product, but reached an error 500 when trying to do so (I've tried several combination of information).

Tried again as super admin, for the same producer, but also for the producer of nut: same problems.

## Expected Behavior
I should be able to create a product.

## Actual Behaviour
I can't.

## Steps to Reproduce
1. Log in as super admin or as a producer
2. Go to /products
3. Click on "New product"
4. Fill in the filed (I've tried, with stock, with on demand, with tax, without). 
5. Hit "create", you should see our dear friend the snail saying hello :)

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/60b95be5-477c-4e5e-824b-12df2352c0ba)

after hitting create:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/12831190-6c5b-48c4-8a6a-f48d40457628)

## Context
Testing v2 on https://staging.openfoodfrance.org

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: ?? 
* Browser name and version: Firefox 64 and Chromium 73
* Operating System and version (desktop or mobile): Ubuntu 18;10 and Windows 10

**Comment by luisramos0** [comment]
This is a problem related to default stock location #3254
There were 2 stock locations in the FR staging DB.
One of them didnt have any products. I have deleted it manually and the problem is fixed.

I think we should close this issue because the date of the creation of the stock location was prior to #3254 being done, so this is probably fixed by #3254. We can reopen this issue if it happens again or in any other v2 instance.

I am moving this to Test Ready @RachL pls close if the problem is solved on FR staging.

Thanks

**Comment by luisramos0** [comment]
@sauloperez fyi

**Comment by RachL** [comment]
@luisramos0 yes this is working now, so closing!
