### ISSUE TITLE
Password migration

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#355]
Passwords are encrypted and cant be migrated. Need to create a mechanism to create temporary Stroudco passwords and e-mail them to users with instructions to reset them to their preferred password

**Comment by RohanM** [comment]
There's a reset password feature built into OFN, which we get through the devise gem. There's some docs on how it's used at the top of this file:

https://github.com/plataformatec/devise/blob/master/lib/devise/models/recoverable.rb

The key part is:

```ruby
# creates a new token and send it with instructions about how to reset the password
User.find(1).send_reset_password_instructions
```

I reckon that might do everything you need in one go. So once the migration has been run, you can call `send_reset_password_instructions` on all imported users and they'll receive an email to reset their password.

**Comment by NickWeir63** [comment]
Following up on Rohan's suggestion above we plan to send this link out to all Stroudco shoppers and producers so that they can reset their own passwords https://openfoodnetwork.org.uk/#/forgot
At the moment UK production is not sending emails at all so we will wait until that is fixed and then send it out
