### ISSUE TITLE
[Spree upgrade] Super admin showing enterprise pages

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3551]
## Description
Each time you log in as super admin, a page asking you to choose an enterprise package will be shown. Further more, the dashboard is displaying in enterprise mode.

## Steps to Reproduce & Animated Gif/Screenshot
1. Log in as spree@example.com on staging FR
2. You will see this screen:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/1d4194b0-f5aa-42c9-a734-ff8da83b6413)

3. Choose an option, then you can access super admin function except for dashboard
4. If you log out, and re-log in the package option will be shown again

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: ??
* Browser name and version: Firefox 64
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by luisramos0** [comment]
interesting, we can already see that @sigmundpetersen is a amazing tester and discovered an edge case :-)

This is caused by enterprise "Sigmund Test" not having the Sells value set.
The enterprise sells value is unspecified if you register the enterprise through the frontoffice, if you create the enterprise in the backoffice, the sells value is mandatory.

The problem here is the crazy redirection logic that happens on /admin, simplified version:
- /admin redirects to enterprises pages if user is owner of at least one enterprise with sells: 'unspecified'
- the enterprises page shown is:
  - the welcome page (change type page) if the user is a manager of only one enterprise
  - the list of enterprises if the user is a manager of more than one enterprise

So, this "sigmund test" enterprise has sells "unspecified" and the spree user in staging FR is only manager of this enterprise, so, you land on that welcome (change type) page.

So, it's a feature not a bug. Maybe you want to test this behaviour?
This is unrelated to spree upgrade or v2.

The code: https://github.com/openfoodfoundation/openfoodnetwork/blob/2-0-stable/app/controllers/spree/admin/overview_controller_decorator.rb

**Comment by sigmundpetersen** [comment]
Haha you're welcome 😝 
Please tell me if I should set the Sells value, you can of course do it also @RachL

**Comment by RachL** [comment]
hmmm @luisramos0 this is strange I always sign up my enterprises from frontoffice and this never occured before....

@sigmundpetersen can you provide the steps you've followed to create your account?

**Comment by sigmundpetersen** [comment]
Well I didn't create an account, I created a new enterprise logged in as spree@example.com and from the front office. Maybe that's the edge case.

**Comment by RachL** [comment]
Oh ok... but that never happens in real life right? :trollface: I mean this is something we would need to move to discourse: be able to create an enterprise as a superadmin... with superadmin as the only manager?

**Comment by luisramos0** [comment]
yes, it's not really super admin, it's just someone who already manages one or more enterprises and instead of going to admin/enterprises they go through the frontoffice registration process.

**Comment by RachL** [comment]
@luisramos0 ok indeed I just re-tested with my enterprise profile. Indeed the sell checkbox is not ticked. However everything else works fine for the superadmin. So this bug was really linked to creating an enterprise trough the frontoffice as a superadmin. Good to know! I'm closing this. And I've no idea were to put the sell problem, yet but will figure out something :D

**Comment by luisramos0** [comment]
to be precise, it's not super admin, it's a manager of some existing enterprise. please correct me if you see I am wrong about this though your tests.
