### ISSUE TITLE
Display broken on embedded shop for iphone & ipad olders

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3592]
## Description
Iphone and ipads users cannot see the whole product list on an embedded shopfront (only the first 20 out of 243). If they go directly on OFN main website, no issues.

Myriam has managed to reproduce the bug on Safari, but we don't know yet if it happens on other browser as well.

No issues for Android users.

## Steps to Reproduce
1. Go to https://panierslibres.fr/index.php/commander/ with an iOS device
2. Try to scroll and go further than the 20th product (see screenshot below)

## Animated Gif/Screenshot

**On a Safari**
![image](https://user-images.githubusercontent.com/6525576/54033952-feba0280-41b5-11e9-8b80-87b0ab56e850.png)

**On Android 7 (OS Fairphone Open 19.02.1 using Firefox 65.0.1)**
This is the last product which is correct:
![image](https://user-images.githubusercontent.com/6525576/54474652-ab643780-47e7-11e9-9ff0-2d6fd0eb05e1.png)

**On Android 9 (OS MIUI 10.2 using Chrome 72 )**
This is the last prodyt which is correct:
![image](https://user-images.githubusercontent.com/6525576/54476444-de192a80-47fd-11e9-8761-8b4e1e390aaa.png)

**On desktop (OS Ubuntu 18.10 & Windows 7 using Firefox 65.0)**
This is the last product which is correct:
![image](https://user-images.githubusercontent.com/6525576/54474678-13b31900-47e8-11e9-8af7-b75f95ade39a.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v1.27
* Browser name and version: Safari for Iphone
* Operating System and version (desktop or mobile): All ios users? To be confirmed

**Comment by myriamboure** [comment]
@RachL there is a workaround but I'm not sure it is acceptable commercially speaking. This bug touch a very touchy part of the hub business : ability of people to make orders. If the hub loose orders because people don't see the redirection link and just are blocked with 10 products to by from, it is problematic, I'm not sure the workaround or giving a redirection link is acceptable. I would be tempted to put s2. Or I would suggest we tell the user that she might better not integrate the shop and only redirect given that bug. @lin-d-hop in UK don't you have similar issues ?

**Comment by RachL** [comment]
@myriamboure I'm trying to summarize our slack discussion: today we have no clear definition of the perimeter of devices/OS/browsers we claim to be compliant with. So we don't say anywhere that embedded shops will work on mobile. We don't say they won't either, but from what I've read, this did not seemed to have been clearly in the perimeter of the feature. Otherwise, maybe something else than iframes would have been considered: scrolling in an iframe on mobile is a tough thing (no matter the device).

Considering this perimeter problem, I'm not comfortable to upgrade this as an s2 (it could even be part of the mobile ready feature).

Anyway we need to clearly communicate to our users and maybe the user guide could be a good place for this.

In the meantime, even if we upgrade this as an s2, the issue is not dev ready IMO:
- we need to know if it is related to safari only or common to all browsers on an iOS device
- we need a process to reproduce this kind of errors. Here the browsers simulations are unabled to reproduce them, and I don't think we have a dev with this type of device, am I right?

Pinging other people to have their opinion: @daniellemoorhead @kirstenalarsen  @luisramos0 @sauloperez @mkllnk

**Comment by mkllnk** [comment]
I'm not sure what the problem here is but it could be about the way the OFN page is embedded. Maybe it has to be solved outside of OFN. Once we know, we could give better support to explain how to embed it with scrolling on ios.

**Comment by daniellemoorhead** [comment]
>I'm not sure what the problem here is but it could be about the way the OFN page is embedded. Maybe it has to be solved outside of OFN. 

The problem is determining if this is the case or not @mkllnk. How is it possible to know? The food hub won't have tech support, so I think we as the OFN need to determine whether our offering causes this. Because it's our product that we're offering. 

@lin-d-hop do any of the embedded shops in the UK have the same problem?

@RachL I'm attempting to replicate on Firefox on my iPhone however so far the products aren't displaying at all, I just get the loading blue circle thing. I'll update you if I have success later on.

**Comment by daniellemoorhead** [comment]
Oh, also, I don't know if this is a scrolling issue, or a display issue. To me it looked like it scrolled fine to the bottom of the list, it didn't cut off halfway or look like I should be able to scroll but can't. Which is why I think it's more about product display and how many show up. @RachL when you posted on Slack you said 19 products showed up. When I looked I had 20 products.  The inconsistency in itself is weird, but it also points to not being a problem with the scrolling function. 

Semantic point, but I think worth bringing up because of the bug description. It's better to describe it as not all products display in an embedded shopfront on iPhone/Safari, than scrolling is broken...

**Comment by daniellemoorhead** [comment]
And finally, can someone with an Android provide a screenshot of the same shop with more products in it?

**Comment by RachL** [comment]
@daniellemoorhead good point! FYI the shops is currently selling 243 products - only 20 of them show up of iOS users using the embedded version. I've updated the issue, and added my screenshot as an Android user.  As the OC will close in 12h I've added desktop view as well. 
I'm on a Google free - raw open source version of Android, so I will try to find other type of Android users.

But actually I think the first question we must ask ourselves is: are our embedded shopfront offered / promised / designed as mobile ready? I believe it is not. If we agree on that, we should clearly state it in our user guide and other type of documentation and plan this work in the mobile ready work or as a v2 of it. If we don't, then yes this needs to be treated as a bug.

**Comment by RachL** [comment]
Update, with screenshot from an Android 9 with Chrome version. No issues.

**Comment by kirstenalarsen** [comment]
@RachL is this the issue we discussed in Drome and suggested that there should be a link that takes them to the non-embedded shop if this happens? Do you still see that as a viable quickfix to this?

**Comment by RachL** [comment]
@kirstenalarsen yes. I'm wondering however if it can really be a quickfix with an iframe. We need some dev insights. I worked quite a lot with embedded stuff in my previous job and at that time dev were always arguing that an iframe is not the ideal solution for mobile, even when trying to add condition like "if a mobile, then switch to non embedded view".
