### ISSUE TITLE
Create New Variant Fails if Unit Type is set to "Item"

### ISSUE THREAD

**Issue by WalkingBlackBear** [openfoodfoundation/openfoodnetwork#3649]
## Description

When creating a new variant via the +New Variant link on the product page, it will fail EVERY time if the unit type is set to "item."

## Expected Behavior

The form should include the "Unit description" field, which is required to complete submission and create the new variant.

## Actual Behaviour

The "Unit descirption" field does not appear on the add variant screen if the unit type is set to "item." Because it is missing, it can not be submitted, and form validation fails because this mandatory (but hidden) field is blank when it is submitted.

## Steps to Reproduce

1. Go to products page.
2. Click "+ New Variant" button in upper right.
3. Complete the form as presented.
4. Submit.
5. Receive error message.

## Animated Gif/Screenshot
![VariantError-ItemUnit](https://user-images.githubusercontent.com/10343651/54887569-72b90380-4e62-11e9-952c-7d7a28e48979.gif)

## Context

I am unable to create new variants of a product if the unit type is set to "Item." If it is changed to any other type (weight, volume) on the product page, everything works as expected. For "item" types, it does not.

It IS still possible to create a new variant through the bulk edit screen, expanding the product, and clicking the + on the left. But this also fails in a significant way. While it allows creating a new variant, there is NO way to add a description of it so long as the unit type is set to "item." You can also NOT edit the description of **any existing product** variant with an "item" unit type.  Everything works as expected for all other unit types. It all seems to hinge on the unit description field being missing for "item" types.

## Severity

bug-s3

I would honestly consider this an s2, because there really is no workaround for being able to give "item" types a variant description. Setting the unit to weight or volume, creating a description, then changing it back almost works - except it adds a unit quantity to the description, including a "0" if you leave it blank.  But there is one functioning workaround ... create a completely new product instead of a variant. So I ultimately went with s3.

## Your Environment

* Version used: Production
* Browser name and version: Chrome 73
* Operating System and version (desktop or mobile): Windows 10 Pro desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. OFN-Canada ... I have no idea what version it's running on. 

## Possible Fix

Include the "Unit description" field in the add variant form, exactly the same way it is for literally every other unit variant. Seems that would solve the issue in a hurry, because it's already working for every other unit type.

In discussion on Slack, Luis Ramos added this:
> Luis Ramos   
> the code is actually excluding the fields explicitly, I have no idea why.. that will have to be investigated as part of your issue
> the code:    - if @product.variant_unit != ‘items’

**Comment by kirstenalarsen** [comment]
I think that this might be connected to a thing done in Spree 2 that separated or combined database fields or something? @sauloperez @luisramos0 do you remember this discussion and associated action.

FYI, now that I am aware of this I think it should be S2. It seems to be a problem with creation of reliable variants, which may be underlying significant bug in #4216 and could be causing other problems?

**Comment by luisramos0** [comment]
@kirstenalarsen I cant remember anything related to v2 and these fields. can be a memory problem...
The only thing I remember is that I discovered the mess that is the list of fields in the variants during the upgrade work. Particularly how option types (spree original way of handling unit variants) and the fields introduced by OFN (unit_value and unit_description).

Anyway, this bug was a "feature" introduced in #1531
In the end of the description of 1531:
"Unit Description field is now hidden when unit type is "items", as this field only applies to products using "weight" or "volume"."

Anyway, the unit_description field is editable in the bulk product edit page in the column "Unit"...
So, this bug has a very explicit workaround, use the bulk product edit page and change the unit_description there using the column "unit".

Anyway, I dont want to go into any kind of clean up in this space now...
I think it's risky to make the field unit_value available when unit is items - I think unit_value presence can trigger the calculation of scales, etc...
But I believe we can unhide the unit_description field safely, it's already available in the bulk product edit page.

SO,
I am keeping the variant.unit_value field hidden when unit is items and showing the unit_description field for all variants, just like the bulk product page.
This is a simple change that fixes this bug and will not cause trouble for sure.

This does not clean up the mess we have in terms of product and variant unit fields:
1. - product.variant_unit - weight, volume or items
2. - product.variant_unit_scale (only for weight or volume products)
3. - product.variant_unit_name - (only for items only products) 
4. - product.option_type - repeated product.variant_unit in spree data model
5. - variant.unit_value - independent field (only for weight or volume only products)
6. - variant.unit_description - independent field
7. - variant.option_value - repeated variant.unit_value (or variant.unit_description) in spree data model
8. - variant.weight - independent field (or copy of unit_value for weight products)
9. - variant.display_name - independent field
10. - variant.display_as - independent field

The major problem is really the repeated data between variant_unit/unit_value and option_type/option_value. This is messed up with lots of logic in the code...
