### ISSUE TITLE
[Spree upgrade] Better use of description field in Product Import

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3664]
## Description
Description can be created but not updated through product import. This is causing problem when product have italic or bold text, that cannot be translated in the csv easily by a user (except if the user knows html).

Further more, it may have prevented to find products for inventory creation here: https://github.com/openfoodfoundation/openfoodnetwork/pull/3315

## Steps to Reproduce
1. Use file product_listv2_test2 https://drive.google.com/drive/u/0/folders/1fI0r3CuHEs0e2y3N46QHIUPJkMs4mfrf on AU staging
2. You be able to update those products as description field is not matching the description in the DB

## Your Environment
* Version used: v2
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Ubuntu 18.10

## Possible Fix
Not check the description field during upload?

**Comment by Matt-Yorkley** [comment]
I think this is probably pre-existing, so we could move this out of the Spree Upgrade column and into PI Backlog.

**Comment by Matt-Yorkley** [comment]
@RachL The only solution to this is to not raise an error when the description field is present in the CSV file where products are being updated, so that the import proceeds. The user can continue with the import but the description will not be updated. I think we already explain that it can't be updated in the user guide already. 

It shouldn't have had any effect on finding products for inventory creation.

**Comment by luisramos0** [comment]
---- I think this is probably pre-existing, so we could move this out of the Spree Upgrade column and into PI Backlog.

I only saw this note now. Moving to PI backlog then.
