### ISSUE TITLE
Product doesn't display price in shopfront

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#3675]
## Description
One product in a user's shopfront displays with a price of $0.00 instead of the  price entered when product was created. It seems to be set up like the others. 

## Expected Behavior
The shopfront should reflect the price of the variant instead of zero.

## Actual Behavior
The product displays with a price of zero.

## Steps to Reproduce

Have not been able to reproduce the bug. To get the correct product/price combo into the shopfront: added a new product with a similar name, removed the problem product from the user's order cycle, changed the producer of the problem product to a test enterprise, and added the new product to the order cycle. Price shows up fine.

## Animated Gif/Screenshot

Product (Broccoli) shows up with a $0 price in shopfront
![Priceless Broccoli](https://user-images.githubusercontent.com/37803238/55328314-ef3e7a00-5440-11e9-8079-8dc774378aa9.jpg)

Product is apparently configured just like the others
![5 dollar price shows up 6 does not](https://user-images.githubusercontent.com/37803238/55328374-1301c000-5441-11e9-97e1-ce432f862751.jpg)

New product is added and shows up fine
![Shop after re-adding](https://user-images.githubusercontent.com/37803238/55328429-2f056180-5441-11e9-9650-b8e069397fca.jpg)

Problem product is reassigned to "test" producer with appropriate image
![This Brocc has Aphids](https://user-images.githubusercontent.com/37803238/55328468-46444f00-5441-11e9-810d-038e7708b4d8.jpg)

## Context
The user wasn't able to sell any of his product (for money). It added to the cart and decremented inventory, all with a price of zero.

## Severity

bug-s4, unless it happens more often. Since we don't know why it happened, it's hard to tell how many users will be impacted.

## Your Environment

* Version used: not sure (current version on openfoodnetwork.net

**Comment by tschumilas** [comment]
Not a bug -   this farm is using the inventory tool to manage their product list.  So that means their shopfront will pull the information (price, stock on hand) from their inventory list IF the product is in the inventory.  IF the product is NOT in the inventory (and the purple sprouting broccoli has NOT been added to inventory) -  the shop will then pull info from the 'products' list.  So -  the shop is pulling the correct information  -  if the owner adds the purple broccoli to their inventory - they can manage stock there like they are for other products.
