### ISSUE TITLE
[Spree upgrade][Phase 2] Reports : user balance not calculated in same way as v1

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3677]
## Description
We noticed while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/3316 the "balance" column is calculated per order, whereas in production it is calculated for ALL orders, like this:

**payment_total** - **completed_order_total**

where
**payment_total** = the sum of payment.amount of all completed payments in all orders (not cancelled) of that user in that distributor
**completed_orders_total** = the sum of order.total of all orders (not cancelled) of that user in that distributor

## Steps to Reproduce
1. Go to https://staging.openfoodfrance.org/admin/reports and look for both of the OC management reports
2. Select hub **OFN UK Demo Hub**
3. You see that the balance show are a difference between the payment total (0 in thoses cases as it as not been capture yet) and the order total
4. In production this difference is made summing up ALL orders for this customer and is thus -1.8 in both cases

## Animated Gif/Screenshot
FR staging (with UK data):

![image](https://user-images.githubusercontent.com/6525576/55348492-9827bc00-54b7-11e9-8691-c21827cd8595.png)

UK production: 

![image](https://user-images.githubusercontent.com/6525576/55348676-0bc9c900-54b8-11e9-99d3-c8cbf3db2549.png)

## Severity
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Windows 10

## Possible Fix
Leave it like this?

**Comment by luisramos0** [comment]
This is a problem only in the data anonimization script. When we anonimize the live data, we don't match user emails in orders. So, if a user makes two orders, the two orders will have the same user_id BUT the email field in the order will be anonimized to different emails. This is why you see different first name and email in the table rows in the staging data although it is the same data as uk live (I checked the db).
Because the report is grouping users by order.email (not by user.email and then look for orders with that user_id), the report takes these two orders as two different users.

So, we could fix the data anonimization process but it will not be straight forward, I'd leave it for now.

**Comment by RachL** [comment]
Ok so I'm closing this for now. Thanks for the feedback!
