### ISSUE TITLE
[Subs] Intermittent Failures on Payments

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#3727]
## Description

We are getting weekly reports of payments failing in subscriptions.
This is not happening on all customers - generally one or two customers per week. A number of enterprises have reported this issue but on UK Prod it seems to be affecting Farmham Community Farm the most.

## Expected Behavior

Subscription payments should complete as expected without error

## Actual Behaviour

Occasional payment failures with the error:
Errors: You cannot use a Stripe token more than once

## Steps to Reproduce

I don't yet know how to reproduce this error, but chat to me on Slack and I'll share details of specific customers to help with searching the logs.

## Animated Gif/Screenshot

![Screenshot from 2019-04-11 10-45-04](https://user-images.githubusercontent.com/8669848/55947746-fc304a00-5c46-11e9-9eea-b0a012bceb0a.png)

## Context

This means that the hub needs to take payment for the subscription outside of OFN then manually update OFN to say that payment has in fact been received. This is a major headache for the hub.

## Severity

S2
## Your Environment

* Version used: v1.29
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. UK Production

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Failing Subs](https://trello.com/c/eBNWazqb/426-failing-subs)

**Comment by lin-d-hop** [comment]
User asking about this again.

**Comment by mkllnk** [comment]
I looked through the code and the token comes from Stripe. Each time we want to take a payment, we ask Stripe to generate a token for us and then we use that token for the purchase transaction. From the code, I can't see how the same token can be re-used twice. It could be a bug in the Stripe gem.

@lin-d-hop Do you know when this error first happened? I'm wondering if a new gem version could have a bug.

**Comment by mkllnk** [comment]
I just tested the token method in development mode and I get different tokens:
```
Stripe::Token.create({card: card.gateway_payment_profile_id, customer: card.gateway_customer_profile_id}, stripe_account: "acct_1Exxx")
=> #<Stripe::Token:0x2ac68b43f798 id=tok_1EQUaVKbre...
=> #<Stripe::Token:0x2ac68b5788e4 id=tok_1EQUZx...
=> #<Stripe::Token:0x2ac68b6a6c48 id=tok_1EQUZqKb...
```

Oh, I just found this line:
https://github.com/openfoodfoundation/openfoodnetwork/blob/c5720bede5d7f199ede875181672d1c89e50489b/app/models/spree/gateway/stripe_connect.rb#L92

I'm not sure in which case this happens. It should still be valid. When I add a card in my profile it has a `gateway_customer_profile_id`. But the majority of cards in Australian production don't have it. When checking out as a guest and providing the card details during checkout, `gateway_customer_profile_id` is missing. That should still be valid though.

@lin-d-hop Users need to have a card in their profile for subscriptions, right?

**Comment by mkllnk** [comment]
I found a pattern. Lynne gave pointed me to the affected customers and all their failed payments are referencing a card without `gateway_customer_profile_id`. These are cards added during checkout and I guess that they can't be re-used for multiple payments. The customer has to add the card in their profile which should then be connected properly. This is just a theory.

I queried this for all three affected users like this:
```rb
Spree::CreditCard.where(id: Spree::Payment.where(order_id: Spree::User.find_by_email("...@...org.uk").orders).failed.select(:source_id)).pluck(:gateway_customer_profile_id)
# => [nil]
```

I'm calling it a day now. Looking into it tomorrow again. But maybe we have a workaround.

**Comment by mkllnk** [comment]
It would be interesting to know what the usual way of storing the credit card is. I wasn't able to find any more before going on holiday. So this issue is ready to be picked up again.

**Comment by mkllnk** [comment]
I'm testing my way through this to understand the possible gap in the workflow. Our theory is that a one-time credit card is selected for a subscription.

If the customer hasn't used a credit card yet no subscription can be created.
![Screenshot from 2019-05-08 18-43-34](https://user-images.githubusercontent.com/3524483/57362030-3860b700-71c1-11e9-9dbf-a1fff4600538.png)

If the customer checked out with a credit card but *not* tick the box *Save this card*, the subscription can still not be created.

If the customer checked out with a credit card and ticked the box *Save this card*, it still doesn't help. The card is saved but the shop is not authorized yet.

If the customer adds a card in their profile, the shop is still not allowed to charge it. I can't see a way to allow the shop. I need to read the manual tomorrow. ;-)

**Comment by mkllnk** [comment]
This is very confusing. I'm still not sure what's happening here. Current issues:

- After I created a customer, the customer didn't see the shop to authorize in the account. There was a server error about a Spree method that couldn't be found. The spec passed though and suddenly it worked. :man_shrugging: 
- After authorizing the shop, I still get the message that there is no card available for subscriptions. Somehow the `default_card_present` attribute hasn't been included by the customer serializer. :man_shrugging: 

Anyway, I found a way to have an invalid default card. Some explanation:

- A user can have several credit cards stored in the profile.
- A user can choose a default card from the cards in the profile.
- A newly added card automatically becomes the default if there is no other default.
- A user can authorize a shop to use the default card which is then used for subscriptions.

Now the offending logic:

- Cards used for one-time purchases are in the database but invisible.
- The user cannot select an invisible card to be the default card. So you would think it can't be used for subscriptions.
- But if there is no default card, any newly created card becomes the default, including the one-time purchase cards. This is a bug. A subscription then tries to charge a one-time card which is not allowed by Stripe. :boom: 

@lin-d-hop With this observation, the solution is to tell the affected customer to create/select a default card in their account. Can you pass that on and check if that solves the problem for the affected customers? I will prepare a fix so that it doesn't happen again, in case a customer removes the stored card and then checks out with a new card (without storing it).
