### ISSUE TITLE
The appearance of text in About Us editor doesn't perfectly correspond to what's displayed on the site.

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#375]
Specifically, if you hit enter once in this text editor after a paragraph, you'll get a actual paragraph break in the site. But within the text editor, you don't get a clean paragraph break, so people are inclined to hit enter twice.

The worst that will happen if this is not fixed is that the about us sections will have 2 line gaps between paragraphs.

**Comment by OliverUK** [comment]
@lin-d-hop 
I'm a bit lost now - remember this is new to me - how all this different issues/commits etc are connected with each other. Do I still need to deploy something to test this? 
Right now I can't get an about us text to display on the staging front end at all.

<img width="413" alt="screen shot 2016-12-10 at 21 36 59" src="https://cloud.githubusercontent.com/assets/17590921/21076449/61bcdc08-bf23-11e6-9b18-1d558a3d5157.png">

<img width="666" alt="screen shot 2016-12-10 at 21 46 12" src="https://cloud.githubusercontent.com/assets/17590921/21076451/69abce1a-bf23-11e6-8f64-f350f706bfa4.png">

**Comment by lin-d-hop** [comment]
Hi @OliverUK 
So I deployed the PR related to this issue to staging. In particular this issue was testing line breaks in the text editors.

![aboutedit](https://cloud.githubusercontent.com/assets/8669848/21140410/c8b61c9a-c12f-11e6-9dcb-1b224800e5b4.png)
![aboutdisplay](https://cloud.githubusercontent.com/assets/8669848/21140409/c8b49320-c12f-11e6-8ee5-a1103166d130.png)


As an aside, it looks like the staging deploy you tested on above broke the About, no? Was this the PR for #1020? Looks like that should be tested on that fix.

**Comment by daniellemoorhead** [comment]
Thanks @lin-d-hop, when something's ready to hand over to the Oz team can you add Sally to assignees and put the aus review label on it. Makes it easier to track then :)

**Comment by lin-d-hop** [comment]
Hi @Matt-Yorkley, 
Given the entanglement between this fix and #1020 do you think it might be an idea to combine them in a new branch and test all of the display issues that popped up in @ssteads testing of #1327? Just a thought, feel free to disagree. The testing of the two branches is feeling more complicated than it needs to be from where I'm sitting.

**Comment by lin-d-hop** [comment]
Line breaks fix merged so closing this issue.
