### ISSUE TITLE
Missing translation keys in type of fees dropdown

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3781]
## Description
When using the enterprise fee menu the whole dropdown for the column showing the type of fee isn't translated.

## Steps to Reproduce
1. As an enterprise admin got to admin/enterprise_fees
2. Clic on "manage fees"
3. See the screen captured below

## Animated Gif/Screenshot
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/bd34b0b7-3d6d-4457-bac8-b7821f3dd99d)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v1.29
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Ubuntu 18.10
* OFN Platform instance where you discovered the bug: French production

**Comment by luisramos0** [comment]
these translations are already in place and used in the frontoffice, we just need to use them in the enterprise fees page:
![Screenshot 2019-05-29 at 21 15 20](https://user-images.githubusercontent.com/1640378/58588165-f58d7e80-8256-11e9-8106-f0251fbde8ef.png)

**Comment by luisramos0** [comment]
@RachL the enterprise fees page in French is bad because **the fee name field is too small**: this is only in French because of the translation of "Montant fixe par article (hors articles au poids/volume)"
![Screenshot 2019-05-29 at 21 38 44](https://user-images.githubusercontent.com/1640378/58589587-2622e780-825a-11e9-9cbe-fa3db3a1bcff.png)


if you change this in transifex this page will be much better:
flat_rate_per_item: "Montant fixe par article (hors articles au poids/volume)"
maybe just
flat_rate_per_item: "Montant fixe par article"

I tried it locally and the page looks much better:
![Screenshot 2019-05-29 at 21 37 35](https://user-images.githubusercontent.com/1640378/58589529-01c70b00-825a-11e9-9d7a-54714ffd58b8.png)

**Comment by RachL** [comment]
@luisramos0 nice tip ! Thx :)
