### ISSUE TITLE
Error 502 on order cycle management reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3805]
## Description
Got an error 502 trying to go on admin/reports/order_cycle_management

## Steps to Reproduce
1. Log in as rachel.arnould+carrots@gmail.com
2. Go on https://staging.katuma.org/admin/reports/order_cycle_management?report_type=payment_methods
3. See a 502 error

Same for /admin/reports/order_cycle_management?report_type=delivery

and admin/reports/order_cycle_management

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/57220942-7b722d00-6ffd-11e9-85f0-90fda600cc6b.png)

## Severity
I'm putting s3 because I'm pretty sure this is due to katume staging. Otherwise it's an s2

## Your Environment
* Version used: v2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): desktop

**Comment by sauloperez** [comment]
Ok, fixed.

That's the report we hacked on September 2017, when we got our first user (Guida's hub, with her as manager) and implemented in https://github.com/coopdevs/katuma-provisioning. We panicked because there was not an appropriate way to have the data used to pack the orders. Now we know that information does exist in other reports so I look forward to deprecating it real soon.

That's another app that runs next to OFN. It was simply killed 3 weeks ago and we didn't start it again. You can check it again if you want @RachL but this report is on us. Nothing to do with the release.

**Comment by RachL** [comment]
@sauloperez yes now it's working. Is it a report that I should continue to test?

**Comment by sauloperez** [comment]
not at all @RachL
