### ISSUE TITLE
[v2] Cannot checkout if a shipping zone is not specified for a shipping method

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#3928]
## Description

Shipping zones are now mandatory on shipping methods.

But you can create a shipping method without a shipping category. When this happens, the hub manager does not see his mistake, but his buyers won't be able to checkout that product.

Similar to #3879

## Expected Behavior

It should not be possible that a user successfully creates a shipping method that breaks checkout.

## Actual Behaviour

Above is possible

## Steps to Reproduce

1. Create a shipping method with no zones
2. Use in an order cycle
3. Try to check out on that order cycle
4. SLUGS

## Context

Found in testing.

## Severity

S3

## Your Environment

* Version used: v2 testing #3840 
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu Desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using.  UK staging

## Possible Fix

@luisramos0 suggests the easiest solution is to stop a check for shipping method zones on checkout. Agreed in Slack.

**Comment by luisramos0** [comment]
for reference, from the v2 release notes about this:
"Zones in Shipping Methods: Shipping Methods can now be part of multiple checkout zones. This is coming from spree v2. Each OFN instance is working on a specific zone and you should assign your shipping methods to that zone always, otherwise users may not be able to checkout using your shipping method."

**Comment by luisramos0** [comment]
the error in checkout is not a slug as mentioned above, the user presses the checkout button, sees a loading image and then the loading disappears and user is left on the checkout page without any error message.

**Comment by luisramos0** [comment]
In v1, if the hub only has shipping methods in a zone different from the instance zone, when the user checkouts, it fails with an error message for the user:
"No shipping methods available for selected location, please change your address and try again."
But there's nothing the user can do to fix it because the list of countries displayed is the list of countries of the instance zone, not the countries of the shipping method zone...
The manager needs to fix the shipping method zone and set it as the zone of the instance.

When user creates new shipping method, the zone is mandatory and preselected, but the preselection in the form is the first alphabetically sorted, I checked all live instances and the first zone (alpha sorted) is the always the instance zone so the problem is avoided....
Even in uk live where the instance zone is Europe:
![Screenshot 2019-06-15 at 20 17 52](https://user-images.githubusercontent.com/1640378/59555479-c5f6aa00-8faa-11e9-99df-eb65ea23ea3f.png)

So, the situation is not ideal in v1 but it works:
- zone is mandatory
- default zone ends up being the instance zone
- end user sees an error if manager changes the zone to a different one from the default selection

In v2 shipping methods can be created without zone and that will make users see a checkout fail without errors, user will be stuck in checkout form page.

3 options were given:
a) Shipping methods cannot be created without zones -> error message shown to user (preferred)
b) There is a default zone that is applied to shipping methods on creation
c) Don't check zones on checkout

I am going for option C and mimic #3384 and "remove matching of shipping method zone to user address on checkout"
