### ISSUE TITLE
Firefox not completing user search queries 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#396]
e.g. when trying to add Owner to group or enterprise, or with search on hub/producer list views 

error "done is not defined"

only in Firefox, doesn't affect customer use of site but will prevent Enterprise Users creating and managing owners and managers for groups and enterprises 

![image](https://cloud.githubusercontent.com/assets/2911176/6387478/cee99524-bddf-11e4-847a-17af90c450a5.png)

**Comment by mkllnk** [comment]
This is a very annoying one. The bug is a bit shy and doesn't come up on my local machine. It could be something with the kind of compression of Javascript which is happening in production but not in development. My best guess: the compression of JQuery results in a script which is not well understood by Firefox. Firefox tries to make an HTTP call and at the end it can't find the `done` method to process the result.

All possible solutions can have bad side-effects and may not work:

 * upgrade to a newer JQuery version
 * use a different compression

But I need more time to find the root cause.
