### ISSUE TITLE
Customer Tagging and discount functionality

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#406]

**Comment by NickWeir63** [comment]
Stroudco wants to use this to replace our current system of charging temporary members (shoppers who are not paying a £2 per month standing order) £1 per order.  We plan to increase the margin from 12% to 15% on all products and then give a 3% discount to members (shoppers who are paying a £2 per month standing order) and people who do regular volunteering.

**Comment by pmackay** [comment]
So how would this work exactly? Is the idea that when an order is made, the customer can enter a code that gives them a discount? And that code is some custom string that is defined along with what effect it has on the order?

**Comment by NickWeir63** [comment]
ideally Stroudco would like it to be a field that the hub administrator could update so that if the shopper was paying a standing order or doing regular volunteering the administrator could change the field and the shopper would get 3% off everything they ordered

**Comment by lin-d-hop** [comment]
I've thought about this a little. It can be a code the customer enters on each order. It would be nice if it could be a persistant field for a customer so that customers didnt necessarily have to enter each time, but that;s more of a nice to have.

It would need to support both percentage discounts and flat rate discounts to cover the use cases I've thought of (eg invite a friend and both get a £5 credit, x% discount this week only, y% discount for members, z% discount for volunteers the week after they help out)

It would be important that there could be multiple possible codes at a time, and also that the codes could be regex (an expression rather than a value) so that no one had to monitor if everyone who entered 'volunteerdiscount' actually did volunteer for a discount, it was a generated code each week. It would also be good to have the ability for codes to expire, after a time period or once used or per customer, so that no one enters the £5 credit code 7 times.

**Comment by pmackay** [comment]
@NickWeir63 are these the main 2 types of customers this relates to?
* people paying standing orders
* volunteers
In each case, how often might their status change? Should OFN have a way to track if a customer is doing either of these things? How do you track this currently? 

If this status doesnt change regularly, it might be better to see if this can be handled using Enterprise fees maybe, rather than requiring the user to enter a promo code on each order. They can handle flat fees, so could a fee definition be extended to be conditional on whether the user is registered as paying a standing order?

**Comment by NickWeir63** [comment]
Yes this relates to people paying standing orders and volunteers.

We dont need OFN to track this - we do it manually at the moment by checking the bank statements to make sure the standing order is still being paid and if it stops we add a 'T' for temporary to the front of the membership number (shopper id) which triggers the system to add £1 to every order.

The status does not change regularly

Yes it would be good if the administrator could manage this rather than the shopper having to enter a promo code each time they order.  So if the administrator could set the fee definition for each shopper in a way that would allow us to charge casual shoppers a 15% markup and shoppers who are paying standing orders or volunteering regularly to be charged a 12% markup.

**Comment by pmackay** [comment]
OK so sounds like an approach might be:
* Admins can set a flag or status on members of their hub to indicate if they are members or volunteers.
* See if enterprise fees can be extended to apply conditionally to orders from customers with the flag set.

@kirstenalarsen, @RohanM would you be able to comment on whether this sound logical?

**Comment by lin-d-hop** [comment]
@kirstenalarsen and I have had a couple conversations about this.

Spree has promotion code functionality built in which it would be good to use.

The challenge is that this has not been used since enterprises, admin levels and order cycles have been built into OFN so it WILL break LOTS of things. Therefore it is a fair sized chunk of work to enable this and make sure it works with everything.

So the suggestion is to start by spiking this, so see how big the task will actually be, by turning on promo codes in Spree and seeing what breaks. As part of this task it's really important to compare how similar the promo code functionality is to Spree 2, as there is going to be a mirgration to Spree2 in the hopefully not too distant future and it would be rubbish to have to completely redo this work at that time.

After spiking it would be good to post the results here and then we can figure out if we can break it down into smaller tasks and being the implementation.

Note standing orders functionality is at least a few months away.

**Comment by pmackay** [comment]
Can you expand a bit on why promo codes would be best for this feature? At
least I'm not sure the actual user need Nick has expressed is best handled
via promo codes, despite the title. That's not to say that promo codes
wouldnt also be useful...

**Comment by RohanM** [comment]
I also have a suspicion that promo codes are not quite the right tool for the job. One way of solving this would be:

- Admin can tick a box next to a user to mark them as a member or volunteer
- All product prices in the store are entered as the full price, that non-member non-volunteers pay
- When a user reaches checkout, look to see if they are a member or volunteer. If so, create an `Adjustment` on their order with the 3% discount. Adjustments are Spree's way of modifying the price of an order, and fit the job better here than enterprise fees do.

The way I've written it up here means that members will see the full price while shopping, but will then see their discount at the checkout. I think this is better than the alternative, where non-members see the discounted price while shopping, but then are hit with an extra fee at checkout.

How does this approach sound?

**Comment by kirstenalarsen** [comment]
this seems to relate very closely to the discussion we had last week about tagging customers, which was going to lead to a spike on use of the tagging gem (see http://community.openfoodnetwork.org/t/customer-accounts/34) - then we could be using the tagging both for delivery runs, members, volunteers etc?

Would it be worth @pmackay doing that spike on tagging and/or we could have discussion about whether UK want to start work on the customer accounts interface to get this in place?

NB. if we do this, could also use tags like 'retail' and 'wholesale' that potentially affected the prices and products shown on the actual shopfront . . later ;)

**Comment by NickWeir63** [comment]
I like @RohanM 's suggestion above of the checkout adjustment on the order with the 3% discount

**Comment by lin-d-hop** [comment]
Just removed the aus review label as it sounds like this gives a good base for someone to start work on this. 

So the first step would be exploring @kirstenalarsens suggestion by spiking tags. This would mean that the functionality added for this task is very reusable for other features.

@pmackay was wondering about what to look at next.... and @NickWeir63 was just asking if we can have this for UK launch. So would you maybe be up for looking at this next @pmackay?

**Comment by lin-d-hop** [comment]
@RohanM @kirstenalarsen 
@pmackay has suggested that there was discussion between using "tags" and using "Spree roles" for this. Has there been a decision between these two? Can you clarify if the original spike on tags is the next step? Or do we need an exploration of "Spree Roles"?
Thanks.

**Comment by RohanM** [comment]
Hi @lin-d-hop!

I had a chat to @oeoeaio, and he pointed out that using spree roles wouldn't be suitable, since they're specific to a user, not a customer. We need to able to have a user who's a member of one hub and not of another.

Looking at how to implement this, I think it'd be good to avoid introducing magic into the system. If we have a simple rule that anyone with the "member" tag gets a 3% discount, it's not obvious why that particular tag would do that, or how to change the discount percentage. You just need to know that the "member" tag is the magical discount tag.

We could avoid that by making a system where we could assign different discounts to different tags. That gives us a place to set the discounts, and it'd open the door to multi-tiered membership structures. We'd be creating rules like "Shopping at hub x, if I'm a customer with tag 'member', then give me a 3% discount".

How does that sound to you?

**Comment by kirstenalarsen** [comment]
hi people - see discussion here - http://community.openfoodnetwork.org/t/customers-can-be-members-volunteers-staff-etc/132

**Comment by lin-d-hop** [comment]
Rob had a look at this and thinks that the existing spree promotion functionality might be usable here. As a caveat Raf looked at promotions at one point and apparently it broke everything...

**Comment by NickWeir63** [comment]
We agreed at our skype today that we would review this issue at our next skype on 17th Dec and see if Steve or one of the Aus team might be able to take it on

**Comment by kirstenalarsen** [comment]
not sure if we are switching this to aus team or not - leaving in UK milestone for now pending further discussion

**Comment by daniellemoorhead** [comment]
Further specifications around customer tagging can be found on Discourse - http://community.openfoodnetwork.org/t/wholesale-and-tagging/505

I'm creating issues for each of the features that @oeoeaio has included in the spec, will close this issue once they've all be added.

**Comment by daniellemoorhead** [comment]
Closing this issue, has been superseded by #851.
