### ISSUE TITLE
Super admin cannot edit users emails anymore

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4094]
## Description
In `admin/users` when clicking on an email it is not possible to change this email again in v2. In v1 (tested by Kirsten in AU) it is still working.

## Steps to Reproduce

1. Go to `admin/users` 
2. Click on an email
3. Change the email
4. Hit update
5. A green message will tell you that it has worked. But nothing has changed: the old email is still there. I didn't saw anything in the dev tools network tab.

UPDATE: I've changed the email in my scenario from rachel.arnould+fred to rachel. arnould+fre . l thought the new email is not saved, I still received a welcome email this new address.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/62130532-7f9aa780-b2d9-11e9-8306-088b4d8fb35a.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.2.1
* Browser name and version: Firefox 67
* Operating System and version (desktop or mobile): Ubuntu 19.10

**Comment by sigmundpetersen** [comment]
Same as #4031?

**Comment by kirstenalarsen** [comment]
uh oh @RachL - now that I read the issue I realise I didn't test thoroughly enough - only as far as getting the green 'account updated' message. I hadn't actually checked if the email had changed - and it hasn't :( So I think the bug is pre-existing

As far as deleting an account goes, I think it is possible that this bug has existed for a while. As in, I know that here in Aus we 'delete' accounts by changing the owner of an enterprise, and don't know that we have ever actually deleted the user? 

This issue raises the question of whether we actually need to keep a V1 running on a staging server for comparative purposes when we upgrade Aus?

**Comment by RachL** [comment]
Aargh ok you are right, this is a duplicate, so I'm closing this one.
