### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4214]
Draft is here: https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/untagged-11a70473234c07bd4e89

Target commit is here: https://github.com/openfoodfoundation/openfoodnetwork/commit/07d4528276c28be04bfe1800c4d58be029290b4d

Build to deploy is here: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/821

- [x] Draft
- [x] Test
- [x] Release
- [ ] Deploy

**Comment by RachL** [comment]
Full testing notes here: https://docs.google.com/document/d/1tG0mZr831_9Y6f4dgUGvJTRGtGqeGQNhvmthVTYcuKY/edit#

Everything is ok, except I've managed to reproduced https://github.com/openfoodfoundation/openfoodnetwork/issues/4053 with super admin login :'(

Bugsnag slack report: https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1567538086016100

@luisramos0 's comment on slack:
> this could be related to the variant price PR… the missing fields are quantity and price, this calculator is breaking because of missing variant.price (quantity is set to 1). for some reason variant.price can be broken…

What do you think @Matt-Yorkley ? If it is an edge case and that Cartastrophe is still improving things we can release and create a new issue for that case. But I'm not 100% sure what I did in particular for this. In both test I was on same staging server and same test shop...

**Comment by luisramos0** [comment]
thanks @RachL 
I dont think the error "ActionView::Template::Error: object must respond to #price and #quantity" is a replication of 4053 because the products that are causing the error in the cart are not deleted. So I think this is a different problem...

From my quick investigation, I couldnt understand what's going on.
I wouldnt release before investigating this problem...

**Comment by luisramos0** [comment]
for reference, the error is on serializing current_order
and in all the latest cart orders for this user spree@example.com
I see only variant id 8 product 4 in order 98, this product is not deleted.

**Comment by Matt-Yorkley** [comment]
Is there a chance that product had it's price deleted before this PR? That would still trigger the error, as the object was previously hard-deleted?

**Comment by RachL** [comment]
@Matt-Yorkley how do you delete a price on a product?

**Comment by Matt-Yorkley** [comment]
You can't do it directly, but if you used that login previously to replicate the bug you will have a broken product in the cart.

**Comment by RachL** [comment]
When testing #4204 I've used Mary's Green Apples. And I think @luisramos0 has mentioned that the problem here are Carrots? 

But yes, maybe in an even previous test I have deleted carrots somewhere.... However the problem would have pop up when testing #4204 no?

**Comment by sauloperez** [comment]
if we passed testing in #4204 @Matt-Yorkley 's explanation seems feasiable. Personally, I would not delay the release and would create one right after if we spot any issue.

**Comment by sauloperez** [comment]
I just tried placing an order in katuma staging and had a suspicious issue related to price. When proceeding with the checkout after choosing a product I got the snail. Then, navigating to staging.katuma.org also resulted in a 500.

These are the bugsnag notifications related to it: https://app.bugsnag.com/katuma/katuma/errors/5d6fbf3c557cf80019a4f157?filters[event.since][0]=30d&filters[error.status][0]=open, https://app.bugsnag.com/katuma/katuma/errors/5d6ebba3ba09db001a1e6bf4?filters[event.since][0]=30d&filters[error.status][0]=open

It's worth taking a look.

**Comment by sigmundpetersen** [comment]
Could we stage the release on FR as well which has freshly seeded test data? Then we could verify whether it's a data problem or a code problem?

**Comment by luisramos0** [comment]
hey, I checked all latest carts for this user and there are no deleted products or variants, all variants have price...

I think there's something going on with the price because the error:
ActionView::Template::Error: object must respond to #price and #quantity
is triggered from the enterprise fee calculator that has quantity 1 hardcoded, so it must be the price that has a problem...

If you guys agree I can make a PR reverting PR #4204, deploy it to katuma staging and check if the snail is still there.
This is just my gut feeling, maybe just because 4204 added act_as_paranoid to price 🤣 

Again gut feeling but I dont think we should release this version as is...

**Comment by Matt-Yorkley** [comment]
Ok, we have a new draft on a custom branch with #4204 reverted: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-4-0-minus-pr-4204
