### ISSUE TITLE
cannot remove images from enterprise profile

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#423]
the enterprise user is able to replace images, but has no way to actually just remove them. sometimes would be really useful just to be able to set back to 'no image'

Create 'remove image' for logo and enterprise banner 

![image](https://cloud.githubusercontent.com/assets/2911176/6650540/f326a6aa-ca6b-11e4-8398-55d410b095e3.png)

**Comment by myriamboure** [comment]
Captured in icebox https://community.openfoodnetwork.org/t/hubs-can-easily-navigate-back-office-and-manage-their-shopfront/1246 but leave it here as seems a pretty easy so added good first issue to enable contributors to pick it up

**Comment by kristinalim** [comment]
I will be working on this issue. :slightly_smiling_face:

**Comment by kristinalim** [comment]
Should we require the user to click on the "Update" button before removing the image from the server?

If yes, we will need to have some indicators in the form that show whether the currently selected action is "Upload File" or "Remove Image". Please let me know what you think of this:

https://www.useloom.com/share/c6a7c0663b1642dda1f6a300d11bc479

If not, we can have the button trigger a confirm box where we explicitly tell the user that the image will _immediately_ be removed. Emphasizing this is important, because this behaviour is different from that of the nearby "Choose File" field where nothing happens until the user actually clicks on the "Update" button.

**Comment by sauloperez** [comment]
The option of prompting an alert box seems the most appropriate. I'd use the default JS `alert` function.

**Comment by myriamboure** [comment]
@mkllnk @RachL cf the other discussion on deletion, I think it would be great to have a standard behavior for deletions. Do you confirm that an alert box is ok? Then in that case I guess we don't need to activate the update button if a deletion has been done as it has already been confirmed by the alert pop-in which is more safe than update button.

**Comment by mkllnk** [comment]
Alert box is okay. I guess you discussed these two options:

* One click removes the visible image, but doesn't save the change. The user then has to click Update to make it permanent. They could also upload another image before they click update.
* One click triggers an alert box. Confirming the alert box will delete the image straight away, like clicking Update, but the rest of the form is not touched (not saving other changes).

I'm okay with both solutions. My ideal solution: One click removes the image straight away. That is like option two, but without alert. A restore button appears in case it was done accidentally. But this solution is far more complicated and the effort is probably not worth it at the moment.
