### ISSUE TITLE
Some transifex translations are not going through properly on a front end onboarding page

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4328]
## Description
I changed lots of transifex strings last week, before Kristina prepared the new release. They all went through apart in two places (was done at the same time, before some that went through so it's not a question of timing.

**Problem 1:**

Modification made in Transifex:
![Capture du 2019-09-26 09-34-41](https://user-images.githubusercontent.com/8135376/65667998-2f259900-e041-11e9-8a28-78b273355879.png)

What I still view in production:
![Capture du 2019-09-26 09-37-56](https://user-images.githubusercontent.com/8135376/65668091-58dec000-e041-11e9-8314-5703d1714e3e.png)

This is really annoying as there is no more logic in the text, as all the changes were consistent together, but now we say contradictory things on the same page, cause I changed quite deeply the meaning of the concerned translation.
And it's a touchy stage, onboarding stage. It would be great to fix quickly...

The concerned key is registration.steps.about.success 

**Problem 2:**
 Within the admin panel, "enterprise" menu, if I want to change the package of the enterprise (column "package" in the table), none of the translations I made went through, they are still the old ones for all producers and non-producers packages.

Example :
"Hub shop" package was translated since 8 days ago by "Boutique hub", and 8 days ago I changed for "Boutique multi-producteurs"
![Capture du 2019-09-26 11-20-39](https://user-images.githubusercontent.com/8135376/65676238-d1e51400-e04f-11e9-8f2f-8f754142a89c.png)

But in production, I still see the old translation:
![Capture du 2019-09-26 11-22-08](https://user-images.githubusercontent.com/8135376/65676282-e7f2d480-e04f-11e9-8c5e-be49a3bf65cc.png)

The concerned keys are all the key containing 'js.admin.panels.enterprise_package', none of the package descriptions here have taken the new translations.

## Severity
For France this translation issue would be s2 IMO... but I guess it won't be that prioritory for global... so I'm putting S3 (@RachL you can check what you think)

* Version used: 2.5.0 on French production

**Comment by luisramos0** [comment]
hey Myriam, you can save and check this URL to see what’s in the app: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/fr.yml
in this page you can also filter by version and see how the translation was in that version
I did this now and I confirm the translation is in the app in version 2.5.0
I just confirmed the translation in on the FR production server as well.

**Comment by luisramos0** [comment]
ok, the translations are there but because these are javascript (browser side) translations, that is not enough.
The translations file on the JS side is not up to date. IT was not updated.
I think it indicates a problem in asset compilation?

I thought of the introduction of mini_racer in #4287 but this PR has not been released yet...

This problem can be reproduced in staging FR.

**Comment by myriamboure** [comment]
@RachL for priorization process see Luis comment in Slack: "if not S2, at least a good candidate for top 5 S3s".
I would vote for s2 of course as it's pretty annoying for France as first onboarding screens are impacted... but you see with all the priorities.

**Comment by luisramos0** [comment]
in the last delivery train catch up we agreed this is an S2

**Comment by luisramos0** [comment]
oops, I staged master to staging FR and the problem is not there anymore. I don't understand why.
I think the best/faster solution is to prepare another release and see if the problem persists...

**Comment by luisramos0** [comment]
I temporarily upgraded to S1 as I thought js was not being updated (the JS bundle file in FR production is from August 30th). I then confirmed the JS code has not changed since August.
so, it's only a translations problem. we keep S2.

It looks like that if the JS code is not updated, the js bundle is not updated and the new translations  are not picked up.
maybe there's some i18n-js config we could change to achieve this but I have not managed to find it.
According to my change and tests in #538 the problem is fixed if we run assets:clean before assets:precompile (so that the new translations are always included in the JS bundle).
