### ISSUE TITLE
Bug undefined method `cached' for Api::CachedEnterpriseSerializer:Class

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#434]
Hi @RohanM 

After pulling the latest repo, I am now getting the following error in the browser when running the app:

undefined method `cached' for Api::CachedEnterpriseSerializer:Class
Extracted source (around line #1):

1: = inject_enterprises 
2: #hubs.hubs{"ng-controller" => "EnterprisesCtrl"}
3:   .row
4:     .small-12.columns
Trace of template inclusion: app/views/home/index.html.haml

Rails.root: C:/ofn/openfoodnetwork3/openfoodnetwork

Application Trace | Framework Trace | Full Trace
app/serializers/api/enterprise_serializer.rb:32:in `<class:CachedEnterpriseSerializer>'
app/serializers/api/enterprise_serializer.rb:31:in `<top (required)>'
app/helpers/injection_helper.rb:3:in `inject_enterprises'
app/views/home/_hubs.html.haml:1:in `_52e1f121b181ae7af6688b7b9ec6b5b2'
app/views/home/index.html.haml:12:in `_a8b1782bc812acb25fa3e9b5c3a27f1a'

Cheers

Aidan

**Comment by RohanM** [comment]
Hi Aidan,

That looks unusual. `cached` is a method provided by `ActiveModel::Serializer`, and should be available. Have you tried bundle install to make sure you're up to date? Otherwise I would investigate your copy of the gem, checking that the method is defined, and perhaps trying `gem pristine active_model_serializers`. It's a tricky one to fix remotely though, have you been able to make any more progress on it?

**Comment by aidandunsdon** [comment]
Created a clean repository and did new bundle install - bug did not reappear
