### ISSUE TITLE
Reports show ghost variants

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4366]
## Description

Several reports, filtered by order cycle, show variants that are not in the order cycle. This happens after a product has been assigned to a different supplier. Changing the supplier has the affect that all variants of that product disappear from all order cycles. They are not shown on the order cycle edit page and are not shown in the shop front. But they are still connected to the order cycle via the old supplier and show up in reports.

The affected reports include:

- inventory reports including Lettuce Share
- all products report

## Expected Behavior

1. When filtering a report by order cycle, only products actually visible in the order cycle should show up.
2. When the supplier of a product changes, it should not affect order cycles. This is undefined though and needs some specification.
  - Option 1: We remove the product from all order cycles. This is like the current behaviour but without ghost entries.
  - Option 2: We update all order cycles to change the supplier of the product in the order cycles as well. This would leave the product in the order cycle. This is not possible though if the coordinator of the order cycle doesn't have permission to add products form the new supplier.

## Actual Behaviour

The changed product disappears from all order cycles but remains on reports. These ghost products are carried forward when cloning order cycles.

## Steps to Reproduce

1. You need two producers and one order cycle.
2. Add a product from one producer to the order cycle and observe that it's showing in the LettuceShare report.
3. Go to the products page and change the supplier of that product.
4. Observe that the product is not visible in the order cycle any more but still shows up in the LettuceShare report.

## Workaround

If the coordinator of the order cycle has full permissions over the supplier, they can delete the product and create it again.

## Severity

bug-s2: a non-critical feature is broken, no workaround

The mentioned workaround is not possible for all users. But if you think it's enough of a workaround, we can demote this bug to s3.

## Your Environment

* Version used: v2.5.1

## Possible Fix

Option 1 mentioned above would be my favourite solution. Remove products from all order cycles when the owner changes. I would usually suggest to do this in the controller to avoid complex callbacks but a callback may be right to ensure data consistency:

After saving a product, if the owner changed, delete all associated exchange variants. Since we don't have the products cache any more, we can delete all of them in a single SQL query to avoid a performance bottleneck. We don't have a model for ExchangeVariant and Exchange doesn't have any other callbacks to consider.

**Comment by Matt-Yorkley** [comment]
I didn't know products could change owner like that! I assume we are missing a lot of spec coverage here.

I know this is stepping into the network model a bit, but I feel like in the case of a change of ownership, a product should be copied to the new supplier and soft-deleted for the old supplier, so that records can remain accurate. 

So for instance, if `Producer A` was selling a `Carrots` product last month, reports for last month should still be able to reference that product as it was last month, i.e owned by `Producer A`, even if the ownership changed to `Producer B` yesterday.

Does that make sense? Or is it not necessary?

**Comment by luisramos0** [comment]
Matt, I think that is correct and necessary.
Instead of simply changing owner we need to clone and delete the product. The clone process needs to include the variants: the current product clone feature does not include cloning the variants.

**Comment by luisramos0** [comment]
According to Maikels options above, I think this makes Option 3: we clone the product and delete the product. The deleted product can remain in the OC and it should be ignored.

**Comment by luisramos0** [comment]
Are there real users experiencing this Maikel? If not, I'd make it S3.

**Comment by mkllnk** [comment]
Yes, real users are experiencing this. Our biggest user in Aus and Theresa found inconsistencies as well.

**Comment by tschumilas** [comment]
Just fyi -  I'm also experiencing this. In 2 situations,   I created  new enterprises and re-assigned existing products to them.   In both cases I did this because the users wanted to back out of using inventory (which they found overly cumbersome and time consuming).    Ironically,  I posted on slack to ask if anyone thought there would be issues doing this.  Ha ha.    It seemed to work at the time - but its only now,  that I'm running some year end reports for these users,  that I was experiencing weird stuff.   I couldn't figure it out -  so I'm glad @mkllnk  did!  And I'm glad you guys are on it!! Thanks.

**Comment by luisramos0** [comment]
thanks @tschumilas can you give a specific example that we can test?

I am fixing it by removing products from Order cycles if they change supplier BUT if a report gets data from orders, the orders are still attached to the Order Cycle and the products on those orders (the ones that have the supplier changed) will not be in the Order cycle any longer. 

I'll try to explain in terms of data model.
We have
Order Cycle - Exchange - Variant - Product - Supplier
and when order is placed
Order Cycle - Orders - Line Item - Variant - Product - Supplier

If the Product supplier change we break the first line bteween Exchange and Variant (remove Product from Order Cycle).
But the Order Cycle is still connected to the product with the new supplier through already existing orders.
This may be a problem in a report...
