### ISSUE TITLE
Backoffice New Order not working for specific user

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4484]
## Description

A user is failing to be able to place an order through the backoffice.

The order is on an OC that is tagged and the customer has the matching tag. I am not sure if this is relevant but I know that other orders are successfully being placed through the backoffice.

## Expected Behavior

For Hub: Cambridge Food Hub
Trying to place the following order:
1x ChariTea Green 24x330ml
1x  ChariTea Black 24x330ml
1x  ChariTea Red 24x330ml
1x  ChariTea Mate 24x330ml
+ The £9.60 enterprise fee

The customer details are:
Info[at]charliescoffee.co
Name: Charlie's Coffee Company
Address: (shipping and billing)
44-45 Burleigh Street
Cambridge
CB1 1DJ

I have included a gif of the endless loop I end up in.

## Actual Behaviour

There is no clear error message. 

## Steps to Reproduce

1. I add items to the order. Then see that I need to add customer details to choose the shipping method.
2. I add customer details.
3. Then go back to the order and I can no longer see the list of items or the ability to add a shipping method.
4. If I try to go to payment then I am told I haven't entered all the customer details and am taken to that screen.
5. And then I am stuck in a loop.

## Animated Gif/Screenshot

![backendorder](https://user-images.githubusercontent.com/8669848/69439514-0c60e980-0d3f-11ea-8452-f405eeddc620.gif)

## Workaround

Haven't found one.

## Severity

 bug-s2 - or awaiting workaround. Removing tagging is not a suitable workaround for this user (I haven't tested if that works though will look on staging)

## Your Environment

* Version used: UK Prod 2.6.3
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
Hello, I'll have a look now.

There's an hidden checkout workflow error that we are not showing to the user here:
"We are unable to ship the selected items to your shipping address. Please choose another shipping address."
I think this error would be shown to the user if this was a user checkout in the frontoffice.

I am investigating what is causing this error.

**Comment by luisramos0** [comment]
we are again (#4355) looking at "producer" overriding their own products.
what's causing the problem is that the "add variant to order" sees the correct inventory stock levels and lets user add variant to order BUT the checkout workflow is not "scoping" the variants and sees the stock in the catalog, not the inventory AND because the products are out of stock in the catalog, the checkout workflow fails...
I believe the quick workaround for this is to add stock to the products on the catalog, this will make checkout work AND will not break the stock logic: the quantity will still be taken from the inventory numbers...

The actual fix will be to scope variants during the checkout workflow process of creating what internally are called packages.
products in catalog out of stock

**Comment by lin-d-hop** [comment]
To be tested after #4355 is fixed (which is the UKs next S3)

Thanks @luisramos0 I'll get this updated.

**Comment by luisramos0** [comment]
I am not sure I was clear, I only mentioned 4355 because it is the same type of situation (overriding own products). This and 4355 require different fixes.

And now that I rethink this... this bug is not specific to "overriding own inventory", I havent tested but I think this will happen every time the product added is an override AND the producer stock is zero. It's a bit worse than initially described...

**Comment by lin-d-hop** [comment]
Can we get rid of inventory yet?

**Comment by luisramos0** [comment]
if you remove these from inventory you will bump into #4355

**Comment by RachL** [comment]
I don't think we will ever fix this one, but please reopen @lin-d-hop if you think otherwise
