### ISSUE TITLE
[mobile ux] Update fonts and colours

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4566]
## Description
**- As a:** enterprise user
**- On page:** my shopfront
**- I want to be able to do:** have the fonts and colours updated so they match those in the new design.

## Acceptance Criteria & Tests
Dev to check if the correct font types and hex colours are being used in the CSS. Not sure if they've already been updated or not...?

**Fonts and **
![Screen Shot 2019-12-13 at 2.36.42 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/5ae2fba1-78e8-48ef-a012-77a3fd324d3d)
![Screen Shot 2019-12-13 at 2.38.14 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/7fbe1b6c-a035-4c18-8a19-e26adec62b03)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley is this issue even needed? Are the fonts and associated colours already all in there and good to go?

**Comment by Matt-Yorkley** [comment]
I don't think this issue serves much purpose for now. We can just do a some checks of the styling when the mobile epics are a bit more finished, which I assume we would do anyway...

**Comment by RachL** [comment]
Giving your comments, I moving it back to the mobile backlog.

**Comment by daniellemoorhead** [comment]
I'm feeling like this issue actually does need to be done @Matt-Yorkley and @mkllnk given the conversations we've had on other mobile ux PRs around why the font colours aren't changed. Would be great to update the font colours and styles earlier than later, it means that we lose the red "danger" font colour sooner which is definitely a good thing.

**Comment by daniellemoorhead** [comment]
I reckon this has all been implemented as part of the shopfront tabs work. @Matt-Yorkley and @mkllnk can you confirm this is the case? If yes go ahead and close this issue.

**Comment by mkllnk** [comment]
We are still using the Oswald font instead of Roboto. I'm not sure about all the colours.

**Comment by daniellemoorhead** [comment]
OK, so that means this story needs to be completed. It will need to be added to the dev ready column and completed @mkllnk :)

**Comment by mkllnk** [comment]
@daniellemoorhead @yukoosawa On a closer look I found that we use Oswald for headlines and Roboto for the body. So I guess you want to change all headlines to Roboto as well. We may need to adjust the boldness. Here are two screenshots to compare the font switch. I'm not sure if everything looks better or not. Maybe I'm just used to the old design.

Oswald headings:
![Screenshot from 2020-02-24 14-47-09](https://user-images.githubusercontent.com/3524483/75127807-46160780-5715-11ea-9582-110a78b5d63f.png)

Roboto headings:
![Screenshot from 2020-02-24 14-49-43](https://user-images.githubusercontent.com/3524483/75127811-4dd5ac00-5715-11ea-8d13-fdcc2be9a159.png)

A few questions:

- Can you confirm that you want to switch to Roboto?
- Can you advise boldness levels or should I just experiment and try to match the old design?
- And can you confirm that this is wanted for the whole front-office? Just because the issue only specifies "my shopfront" as location for the change.

**Comment by mkllnk** [comment]
@daniellemoorhead @yukoosawa I'm updating the colours but I found that there are 7 shades of red. They are used for hovering links, background colours of varying strength etc. The most complicated is probably the products table with variants. The variants have alternating grey backgrounds and when you hover they have different orange backgrounds.

I tried my best but maybe Yuko would like to look at it on a staging server and adjust if necessary? Here are a couple of screenshots:

![Screenshot from 2020-02-24 16-19-34](https://user-images.githubusercontent.com/3524483/75130347-00137080-5722-11ea-8950-899314897dce.png)
![Screenshot from 2020-02-24 16-24-20](https://user-images.githubusercontent.com/3524483/75130373-29cc9780-5722-11ea-8743-999ad55bfac6.png)

**Comment by yukoosawa** [comment]
@mkllnk Let's leave the headings at Oswald for now. Although I think Roboto is easier to read, especially at smaller sizes - but I'm not ready to change all the headings as it's likely to break / have unexpected consequences :)

As for the orange, can we use an existing orange (like the one used in the main navigation cart background) for the shopfront rather than changing all the shades of red? Again I don't want to do a site wide change without understanding it's full impact.

**Comment by daniellemoorhead** [comment]
@mkllnk 

> As for the orange, can we use an existing orange (like the one used in the main navigation cart background) for the shopfront rather than changing all the shades of red? Again I don't want to do a site wide change without understanding it's full impact.

Does this make sense? Does it unblock what to do about this card?

**Comment by daniellemoorhead** [comment]
This is done as part of the shop tabs feature branch, closing this as testing on #4764

**Comment by mkllnk** [comment]
Okay, so we don't change the font right now and the colours have been changed in #4764 already. Closing this.
