### ISSUE TITLE
[mobile ux] Restyle price breakdown modal on mobile

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4600]
## In a feature branch or master?
Product listing feature branch 

## Description
**- As a:** shopper
**- On page:** product listings on a shop
**- I want to be able to do:** see all the price breakdown details on the modal

## Acceptance Criteria & Tests

Key changes / call outs
- [ ] On hover state for pie = fill: #0096AD
- [ ] On click state for pie = fill: #0096AD
- [ ] Modal redesigned as per screenshot
- [ ] Remove the redundant 'Full Price Breakdown / Price Graph' link to toggle view; all content is now presented in the single modal view
- [ ] If user navigates to another tab in shopfront, close modal (so we don't get the display bug that currently happens in screenshot below)
_BUUUUUUG_
<img width="1414" alt="Screen Shot 2020-01-05 at 12 30 45 AM" src="https://user-images.githubusercontent.com/19785399/72491910-8070b880-37e9-11ea-845b-73a75ee91845.png">

Notes
- Pie icon is included in the current production OFN font/svg set
- Note position of modal on Mobile vs Tablet/Desktop due to space constraint
- Note in other regions, currency position/text changes (ie. openfoodfrance.org)

**HOW IT LOOKS NOW**
<img width="293" alt="Screen Shot 2019-12-18 at 3 46 31 pm" src="https://user-images.githubusercontent.com/10949052/71056555-d5e78480-21ad-11ea-9b0a-967bdd9a5187.png">

**HOW IT NEEDS TO LOOK**
**_Mobile_**

![Mobile: Shop - Price Breakdown](https://user-images.githubusercontent.com/19785399/72670149-2863cd00-3a08-11ea-81da-1ea3feae11bd.png)

**_Tablet_**

![Tablet: Shop - Price Breakdown](https://user-images.githubusercontent.com/19785399/72670152-30237180-3a08-11ea-837c-4ec3b0139daa.png)

**_Desktop_**

![Desktop: Shop - Price Breakdown](https://user-images.githubusercontent.com/19785399/72670155-39144300-3a08-11ea-9fdb-bb29447192b6.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard

**Comment by yukoosawa** [comment]
**DESIGN NOTES**
- Pie icon is included in the current production OFN font/svg set
- Hover state, update icon colour
-- fill: #0096AD
- On click, update icon colour, update icon to X
-- fill: #0096AD
- Modal redesigned to only require a single view for content (no more extra clicks!)
-- Note position of modal on Mobile vs Tablet/Desktop due to space constraint
-- Note in other regions, currency position/text changes (ie. openfoodfrance.org)
- Behaviour
-- Tap X to close
-- Tap area should be 40x40px for mobile
-- If user navigates to another tab in shopfront, close modal (so we don't get the display bug that currently happens)
<img width="600" alt="Screen Shot 2020-01-05 at 12 30 45 AM" src="https://user-images.githubusercontent.com/19785399/71792478-dcc42300-3006-11ea-8c39-b5a6a49933e6.png">


**HOW IT NEEDS TO LOOK**
Mobile
![Mobile: Shop - Price Breakdown@1x](https://user-images.githubusercontent.com/19785399/71791749-13e50500-3004-11ea-95b9-778a01263e2f.png)

Tablet
![Tablet: Shop - Price Breakdown@1x](https://user-images.githubusercontent.com/19785399/71791752-17788c00-3004-11ea-93f6-3768d89d742b.png)

Desktop
![Desktop: Shop - Price Breakdown@1x](https://user-images.githubusercontent.com/19785399/71791758-1b0c1300-3004-11ea-8053-8777d01a2231.png)

Design details are kept in our Zeplin account: https://app.zeplin.io/project/59532764a6c78ff3c534b372/dashboard?seid=5e129b773cbeb61b6ec65e78

**Comment by mkllnk** [comment]
@daniellemoorhead @yukoosawa The designs show two different positions for the price breakdown popover, at the bottom on mobile and at the left on bigger screens. Can we make it consistent and always display it at the bottom? That would be a lot easier.

**Comment by yukoosawa** [comment]
@mkllnk @daniellemoorhead Sorry for the late reply. Positioned at the bottom for all breakpoints is fine.

**Comment by daniellemoorhead** [comment]
Closing this as the remaining tweaks required will be part of another story.
