### ISSUE TITLE
[Spree 2.1] Enterprise Role saving errors

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4646]
It looks like `EnterpriseRole`, or possibly just the factory that creates them when creating enterprises with users is broken.

This is causing a large number of failing specs, including most of the remaining API test failures.

When an enterprise is created with user objects attached, we get this error (whilst the factory is saving the enterprise object):

```
622) Spree::Admin::SearchController Distributor Enterprise User searching for known users when search query is not an exact match returns a list of users that I share management of enteprises with
       Failure/Error: let!(:enterprise) { create(:enterprise, owner: owner, users: [owner, manager]) }
       
       ActiveRecord::RecordInvalid:
         Validation failed: Enterprise roles is invalid, Enterprise roles is invalid
       # ./spec/controllers/spree/admin/search_controller_spec.rb:9:in `block (3 levels) in <top (required)>'
```

A test with this line will fail: 

```
let!(:enterprise) { create(:enterprise, owner: user1, users: [user1, user2]) }
```

But for some reason this will pass, and allow the test to continue:

```
let!(:enterprise) { create(:enterprise, owner: user1) }
before { enterprise.users << [user1, user2] }
```

**Comment by luisramos0** [comment]
I think this is the case of hundreds of broken specs...

I suspect the existing quick fix in the Enterprise model to comment out the method enforce_ownership_limit (or ensure_owner_is_manager?) is not working.
I think this error is causing specs to fail with errors such as:
- unauthorized/redirection errors in specs like spec/controllers/admin/customers_controller_spec.rb:80
- "unexpected token at '<html><body>You are being" controllers failing with unauthorized because user roles are not correctly set
- other test with redirection to "test.host/unauthorized", same reason as above
- error "Enterprise roles is invalid" as mentioned above but also "Enterprise roles user can't"

**Comment by luisramos0** [comment]
I gave this one a good try, no success :-(
I tried to understand what Matt describes above: bin/rspec spec/controllers/spree/admin/search_controller_spec.rb:9

Something related to the Enterprise model associations:
```
  has_many :enterprise_roles, dependent: :destroy
  has_many :users, through: :enterprise_roles
```
or this before_validaton method:
```
  def ensure_owner_is_manager
    users << owner unless users.include?(owner)
  end
```
or what's happening in ControllerHelper#login_as_enterprise_user

It always prints the error "Enterprise roles is invalid"

**Comment by luisramos0** [comment]
I was about to open another issue for another error but now I realize it could be the same cause, the error message is very similar, this time with Adjustments:
```
 29) Api::OrdersController#index as an admin user returns the order number
      Failure/Error: while !order.completed? do break unless order.next! end
      
      StateMachine::InvalidTransition:
        Cannot transition state via :next from :address (Reason(s): Adjustments is invalid)
      # ./spec/factories/order_factory.rb:90:in `block (3 levels) in <top (required)>'
      # ./spec/controllers/api/orders_controller_spec.rb:33:in `block (3 levels) in <module:Api>'

```

**Comment by luisramos0** [comment]
I now wonder if this is maybe all related to strong parameters....
I see a lot of ActiveModel::ForbiddenAttributesErrors that are certainly related to strong parameters and missing attr_accessible entries.
I see for example ForbiddenAttributesError in spec/features/admin/enterprise_roles_spec.rb:46 being fixed by simply adding "attr_accessible :user" to app/models/EnterpriseRole.rb

**Comment by Matt-Yorkley** [comment]
I'm pretty sure this comes up in specs that don't use the params object at all...

**Comment by mkllnk** [comment]
Spree used to create users with the admin role. We remove it in our factories:
https://github.com/openfoodfoundation/openfoodnetwork/blob/a1cb6928dbb17fe032f9a41f10be97969c7bc392/spec/factories/user_factory.rb#L17
I'm wondering if that behaviour changed and if some of these tests only passed because the user was admin.

Looking at Matt's example above: In another project I've seen that if you create a test object with an association to another object, the other object is not necessarily updated. So in this example, after creating the enterprise, you would need to reload the user so that it knows that it has enterprises. Otherwise it doesn't know that an enterprise has been created in the database and a user without enterprises is not allowed to see the backend. Our factory code may do less magic after the update.

**Comment by Matt-Yorkley** [comment]
> In another project I've seen that if you create a test object with an association to another object, the other object is not necessarily updated.

Maybe that's it. It only seems to come up with collections of associated objects passed to a new object. I did some investigating before, and it's definitely something to do with the order that Enterprise, User, and EnterpriseRole objects get persisted. 

Maybe we can just tweak some of the instantiation logic in the factories? I think there's callback-type blocks that can be used to perform tasks after a new object is saved...

**Comment by luisramos0** [comment]
yeah, that's it :+1: I found a solution: https://github.com/openfoodfoundation/openfoodnetwork/pull/4821/files
