### ISSUE TITLE
When logged into customer account, looking at my previous orders, I get the cat.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#466]
Lisa@live.com was not able to see her past orders in her customer account, when she clicked on 3 of the 5 orders she got the cat

**Comment by kirstenalarsen** [comment]
I suspect this is to do with the changed order confirmation page. @summerscope @oeoeaio - would the new order confirmation page be looking for any information that is not actually available to older orders?

**Comment by mkllnk** [comment]
It looks like @oeoeaio fixed it already. There was a problem if an order had no line items, but Rob fixed that. There was also a problem with an invalid currency, but I can't find that in the database any more.

I looked for the user lisa@live.com, but couldn't find it in the database. Did she change her email address or was that account deleted?

**Comment by mkllnk** [comment]
Okay, found it. It was reported in BugSnag as "NoMethodError · spree/orders#show" and happens if you haven't selected a hub before. In that case, you don't have a current_distributor. Instead of failing, I change the code to not display the hub's banner at the top.

Ideally, we should not display the banner of the current distributor, but of the distributor of the order to show.
