### ISSUE TITLE
Shop tabs and navigation UX in cart and checkout

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4711]
Continuing discussion from #4706

We need to discuss and incept / finalise changes to the shop tabs and navigation on the cart and checkout pages. Feel free to update this description!

Here's a few things to consider (not an exhaustive list):

- To what extent do we actually want/need to show the tab content during cart/checkout? Eg: do people need to be able to check an enterprise's twitter handle half way through placing an order?
- If we keep the shop tabs in cart and checkout will will probably need to remove the shop tab in those views.
- If we don't keep the tabs, we will want a way for the user to navigate back to the selected shop from the cart/checkout pages. Maybe the enterprise name in the header could be a clickable link in those two pages?

**Comment by daniellemoorhead** [comment]
@yukoosawa ping! I'm going to review all the notes from last week and then if any further detail required I'll get in touch.

**Comment by daniellemoorhead** [comment]
@Matt-Yorkley and @mkllnk et al, an update on this

@yukoosawa and I went through this today and here's the overview of the plan:

1. When this work was first scoped there were no changes planned for the checkout section. That's why there are no designs available and why Yuko hasn't thought about this stuff.

2. We agree that removing the tabs from the edit cart and the checkout flow is the correct design - they can still hit their browser back button, or also hit the 'continue shopping' or 'back to cart' buttons in this flow. So there is no work required around tabs and this process.

3. We will, however, need to change the order cycle section on the edit cart and checkout screens. I'll be creating a new issue for this and Yuko will design how the order cycle and page heading will display (see screenshots below)

![Screen Shot 2020-02-07 at 2 39 21 pm](https://user-images.githubusercontent.com/10949052/73999157-e3eca100-49b7-11ea-8d99-74857119de4a.png)

![Screen Shot 2020-02-07 at 2 39 32 pm](https://user-images.githubusercontent.com/10949052/73999161-e6e79180-49b7-11ea-9e19-bdaa4d252006.png)

We'll need to make a decision about whether we also want to update the checkout and edit cart pages - something I'll bring to the product curation and global community next Tuesday.
