### ISSUE TITLE
Product filters not working for Food Connect following V2.7.1 Girasol deployment

### ISSUE THREAD

**Issue by JenSheridan** [openfoodfoundation/openfoodnetwork#4729]
## Description
Following deployment of v2.7.1 this morning, Food Connect shop (https://www.openfoodnetwork.org.au/foodconnectwholesale/shop#/shop ) has lost some of their product filters, including can't filter by 'Fruit'.

## Expected Behavior
When you try to filter the Products using the product categories, you should be able to choose 'Fruit' as an option. 

This should load when you click +11 More Categories on the shopfront
![image](https://user-images.githubusercontent.com/39814473/73323324-37b20880-429b-11ea-98ef-202f2b4c80ab.png)

## Actual Behaviour
The drop down of +13 more (mobile) or +11 more (web) products doesn't load. 

When you use the shop search bar on mobile, 'Fruit' doesn't return any products labelled in the fruit category, only products with fruit in the title. 

## Steps to Reproduce
Go to https://www.openfoodnetwork.org.au/foodconnectwholesale/shop#/home 

Click across to shop

Click to load additional product categories

## Workaround
If you reload https://www.openfoodnetwork.org.au/foodconnectwholesale/shop#/shop the categories work. Same if you visit that URL directly. 

## Severity

bug-s2: a non-critical feature is broken, no workaround

Customers don't know to reload, so effectively broken in their eyes. 

## Your Environment
Experienced on Chrome desktop and Mobile Safari

NB: This bug doesn't seem to be affecting shops without a home tab. It also isn't affecting some other shops that DO have a home tab e.g. https://www.openfoodnetwork.org.au/harcourt-coop/shop#/shop

**Comment by mkllnk** [comment]
I have a dirty hot fix for this which I deployed on the Australian production server:
https://github.com/openfoodfoundation/openfoodnetwork/commit/0c4f23d0c1ea4c4b5e628365f5a7c665cc461265

It reloads every tab after clicking on it. That's much slower than before but initialises the filter code correctly.

@Matt-Yorkley What do you think about using normal links here instead of tabs?

**Comment by mkllnk** [comment]
I have been tracing down the issue here. It seems like our code is doing everything right. The filters load correctly but the dropdown is implemented by the Foundation framework. Foundation initialises itself at page load and doesn't react to new elements. We can call `Foundation.init()` when switching to the shop tab. I don't know if it could have any negative side effects. I'm not aware of any other Foundation functionality on the page.

It's okay to have an interim solution. We will change the dropdown in #4603 and should probably replace the Foundation logic with custom code here.
