### ISSUE TITLE
[mobile ux] On edit cart page the continue shopping button and the edit order button on the orders page takes you to the shop tab

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#4771]
## In a feature branch or master?
This can be merged straight to master 🎉 

## Description

**- As a:** shopper
**- On page:** edit cart and also on the user account orders page
**- I want to be able to:** go back to the shop tab when I click 'Continue shopping' or 'Edit order'

## Acceptance Criteria & Tests
**Current behaviour**
- continue shopping button defaults to the home tab
- If home tab does not exist it goes to the shop tab

**Expected behaviour**
- continue shopping button always defaults to the shop tab

**Comment by mkllnk** [comment]
@daniellemoorhead I think we need to revise this. The button is now going back to the shop. But if the shop has a shopfront message, it goes to the home tab instead of the products.

Unfortunately, this is now happening from a lot of places:

- If you try to check out or edit an order without selecting an order cycle.
- If you are not allowed to check out.
- From the shop link in the menu.
- From the orders and orders edit page.

I think it's okay to go to the shop home tab from the menu. I'm not sure about error responses. Maybe I need to look more into what kind of error it is. The home tab could have some additional information why a checkout may fail or what you should do in case something goes wrong. So that could be valid.

But what about the links from the orders page? To the home tab or straight to the products?

**Comment by daniellemoorhead** [comment]
>I think it's okay to go to the shop home tab from the menu.

Agree, the "shopping at..." link can go to home tab. NO CHANGE

>I'm not sure about error responses. Maybe I need to look more into what kind of error it is.

I need a list of the different states in the process to understand if they go back to the home tab or the shop tab. I know of:
1. The order cycle closes while you have products in your cart but you haven't checked out yet. -> take them back to home tab
2. There are products in your cart that then become unavailable that you need to remove from your cart. <- take them to the edit cart page
3. ...?

>But what about the links from the orders page?

Take them to the shop tab (products list). CHANGE REQUIRED
