### ISSUE TITLE
Wrong payment method

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4779]
## Description

As an admin I can see on this order:

https://www.openfoodfrance.org/admin/orders/R463586725/payments 

Hub ID: 942

That the buyer experienced 3 failed stripe payments and ended up confirming her order by cash.

Yet she sees a confirmation page and email saying she has paid thanks to stripe (paiement par carte bancaire):

Even though the status is correctly at "unpaid" the confirmation of the payment method leads the buyer to think she does not have to pay :/

## Steps to Reproduce
I can't reproduce it yet...

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/74145831-0bce4580-4c00-11ea-8378-48caa62e6b65.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
I'm trying to get more info on what's happened.

**Comment by luisramos0** [comment]
hello Rachel, on trying to replicate did you try to pay with a stripe card that fails and then finish with cash? Does that workflow leave the order with status paid?

**Comment by lin-d-hop** [comment]
Just noting that FR switched to the up-to-date Stripe API in case it's relevant.

**Comment by RachL** [comment]
@luisramos0 yes when I try to reproduce with a failed payment the status is correct, and especially the payment method is correct: it shows me that I paid by cash.

I think that I'm not reproducing with the right stripe failure? I mean, in this case we've sent an order confirmation saying the order was paid through stripe but that the amount is still pending... not sure how to reproduce that part. At some point stripe has send the info that everything went ok?

**Comment by mkllnk** [comment]
Some clarification. The payments for the order:
![Screenshot from 2020-02-12 10-14-41](https://user-images.githubusercontent.com/3524483/74288456-8a51f100-4d80-11ea-8c65-846051b3e890.png)

And what the customer sees:
![Screenshot from 2020-02-12 10-15-28](https://user-images.githubusercontent.com/3524483/74288496-a0f84800-4d80-11ea-8536-bdda23310526.png)

So it does say that it's not paid. But the confusing thing is that the payment method is displayed as "paid by card". The culprit is in this line just looking at the first payment:

https://github.com/openfoodfoundation/openfoodnetwork/blob/e1eface5f8e8906cc22545cc26e408030a0ac99c/app/views/spree/shared/_order_details.html.haml#L16

I'm wondering what the best logic to display a payment method would be. There are many different states for payments:

```rb
[
    [0] "pending",
    [1] "failed",
    [2] "invalid",
    [3] "void",
    [4] "checkout",
    [5] "processing",
    [6] "completed"
]
```

* We should ignore failed payments. If there are only failed payments, the order shouldn't be complete. So there should always be a non-failed payment to display. The same for invalid payments.
* I'm not sure about `void`. I guess someone could complete an order and the payment is "voided" later?
* The `checkout` state shouldn't be possible for complete orders. And `processing` is only a temporary state while the payment is being made.
* If there is a pending payment, we should display that payment method.
* If the order is paid for, we should display the method with which it has been paid.

An additional complication is that, in theory, an order can have multiple complete payments. It could have been paid in instalments. And these payments can have different payment methods.

**Should the UI allow for multiple payment methods to be displayed?**

That would be the only correct way. And I guess we should then display the methods of all pending and complete payments. Or all of them? @RachL

**Comment by RachL** [comment]
@mkllnk I'm droping here some thought before our call on this:

- it is indeed a payment method display problem. What is hard in the buyer mind is that a payment by credit card cannot be unpaid, so they don't trust the payment status because for them paid by credit card with order success = payment success

- do we know why we are looking at the first payment on this page? I do understand that if there are several payments, it is a nightmare to follow. But at checkout you cannot pay with several payments. So there are two things here: 
1. Maybe we shouldn't have recorded the failed credit card payment as a payment?
2. Maybe we should display the last payment, because I believe the last one is the one who triggered the order success?

So I wouldn't display all payment methods at this stage, but the first successful one, or the last one?

**Comment by luisramos0** [comment]
Nice one! The good news is that it looks like just a problem of displaying what happened, not a problem with what happened: that would be harder to fix.

1. @RachL we must record the failed credit card payment as a payment. Maybe you are saying we shouldnt display it to the manager or user?

2. I am sure the logic that looks at the first payment is there as a way to ignore all the complexity Maikel discribed. I think a smarter approach would be to use LAST not FIRST. There's higher probability that the last is successful (you tend to retry if something fails). I think if we change this from FIRST to LAST, it will just work fine for the vast majority of cases. I vote for that: show the payment method of the last payment.
After that, we can keep this issue open as an S4 to represent the unhandled complexity Maikel described above.

**Comment by RachL** [comment]
@luisramos0 yes sorry if I wasn't clear, my point was that it might be too complex now to think about a UI where we display to the buyer all the payment methods.

I agree that displaying last would fix the main problem and we can see later for the rest. It's not a priority to work on that.

**Comment by mkllnk** [comment]
Great! I was hoping end up with this solution. Describing all the complexity I actually forgot to mention that this is an option! It's super easy. And considering that it took six years for someone to come up with this issue, it is very unlikely that we'll have an issue with a better-even-though-not-perfect solution. :+1:
