### ISSUE TITLE
Products not sorted alphabetically within OC edit/create page

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4845]
## Description

As part of https://github.com/openfoodfoundation/openfoodnetwork/pull/4454#issuecomment-590526052 we introduced alphabetical ordering of products in OC admin page. However this is not working anymore.

There is no actual workaround except doing a search within the page.

## Steps to Reproduce

1. Create or edit an OC for hub 922 in French prod or use Mercia Food hub in UK staging (ID 201002)
2. Observe ordering of product in both incoming and outgoing steps

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/75271637-ce230c80-57fc-11ea-8a4f-2153477efa69.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.7.6
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
ok, I can explain the regression!
First of all, we dont have auto tests to verify alpha ordering, a MUST have for this issue here so this doesnt happen again...

Alpha ordering was introduced in #4454 merged on Nov 27th.
But after this we had all the work in the OC edit page coming in #4455 merged Dec 17th. From 4455 we started fetching the products from a completely different place (pagination!). Not ordered.

In this issue we can remove unnecessary product order from [EnterpriseSerializer](https://github.com/openfoodfoundation/openfoodnetwork/blob/03c91dfac1abd7358fd0d8cdc667f8232c44cf80/app/serializers/api/admin/for_order_cycle/enterprise_serializer.rb#L35) and add it where it is needed: ExchangeProductsRenderer: [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/03c91dfac1abd7358fd0d8cdc667f8232c44cf80/app/services/exchange_products_renderer.rb#L33) for incoming and [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/03c91dfac1abd7358fd0d8cdc667f8232c44cf80/app/services/exchange_products_renderer.rb#L48) for outgoing, or maybe [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/03c91dfac1abd7358fd0d8cdc667f8232c44cf80/app/services/exchange_products_renderer.rb#L11) for both cases.

Good first issue only if the dev knows how to build ActiveRecord queries already. 
It will be as simple as adding something like  relation.order(:name) or relation.order("spree_products.name") in the correct place. And then test it in the ExchangeProductsRenderer spec.

**Comment by yihyang** [comment]
Hi there, I have created a new PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6268 based on @luisramos0 's comment. Please let me know if there are things that needs to be updated, thanks
