### ISSUE TITLE
[Release Blocker] Product Import failed on release testing

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4871]
## Description

When testing product import the import fails. After file (link below) loads each of the lines in the file appear to be fine for importing - each line has a green tick and reads fine. However the top level status says that no products can be imported.

Tried the same file (with necessary changes to enterprise name and category) on UK production and the import worked fine.

## Expected Behavior

Import should work or give appropriate errors

## Actual Behaviour

Import failed with no useful error

## Steps to Reproduce

1) Specify the file [I used this one](https://docs.google.com/spreadsheets/d/1goLbnkFmt4yLFuqU9zCbTmrQ4xryhVbXbczniDFqK-I/edit#gid=0)
2) Enterprise is found fine
3) All products individually show a green tick as though they are good for import. However the status says that all products have an error and cannot be imported.

## Animated Gif/Screenshot

![Screenshot from 2020-03-01 17-25-18](https://user-images.githubusercontent.com/8669848/75630653-a4932800-5be4-11ea-9f90-18c5ba1bf1d8.png)

## Severity

S2 as a release blocker

## Your Environment

* Version used: 2.7.7 on FR staging
* Browser name and version: Chrome

**Comment by Matt-Yorkley** [comment]
Ok, I think this is a pre-existing issue and it only applies to French staging. There's a different config option that's set there, which means all products must have a Tax Category in order to be valid. If you fill in the `tax_category` column the import is successful. It's odd that no validation message is shown though.

Notes:
- We haven't touched Product Import in this release, it's a pre-existing issue
- We can open a new issue to address the missing validation messages for empty `tax_category` on instances that use that specific config option
- I think we don't need to block the release deployment?

**Comment by lin-d-hop** [comment]
Thanks Matt. As we removed spree_backend I figured all issues were worth reporting.
I always do release testing on FR staging and had never encountered this so thanks for tracking it down.
Agree it's not a release blocker.
Good to go.

**Comment by filipefurtad0** [comment]
Thanks for bringing this up @lin-d-hop and your notes @Matt-Yorkley.
I came across this at some point, but couldn't explain the behaviour. I've added a note on our Testing Handbook.
Cheers.
