### ISSUE TITLE
Edit order cycle screen on UK staging does not show 'Incoming' nor 'Outgoing' options

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#492]
Both @getweaving and I are finding the the 'Edit Order Cycle' screen that we get to in UK staging by clicking the edit icon to the right of the open order cycle does not show the usual 'Incoming' and 'Outgoing' options like it does on Staging 2.  Instead we get the screen shown in 
![screenshot 2015-04-10 15 34 59](https://cloud.githubusercontent.com/assets/10517702/7090073/4d85810c-df98-11e4-99b4-e43878fcd8f7.png)
the attached screenshot.
We are also finding that the Stroudco products imported by @aidandunsdon and edited by Alexis and I are not showing on the shopper screens.  This is a recent development.  Last week the products that we edited did show up on the shopper screens.

**Comment by lin-d-hop** [comment]
@NickWeir63 This was likely because you updated StroudCo to operate as a Producer, rather than a Hub. Only Hubs have the ability to accept incoming and outgoing orders.

I have updated this in super admin and this should be working again now. Please confirm this on staging and then close this issue.
Cheers :-)

**Comment by NickWeir63** [comment]
Yes this is sorted @lin-d-hop - thanks very much.  sorry for being a numpty

**Comment by pmackay** [comment]
Great spot @lin-d-hop, I wonder if that info is captured in the growing
docs on OFN Community and if its findable? :)
