### ISSUE TITLE
Improve Notifications when Subs Placement job fails

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#4981]
## Description

Currently the Subscriptions Placement job fails with very specific error messages related to the order placement that failed. When the Subs Placement job errors the whole job is killed and the remaining subscriptions are not placed. This issue is to update the notifications that are sent to Bugsnag and Slack on failure of the Subs Placement job.

## Acceptance Criteria & Tests

When the Subs placement job fails an additional message should be sent to Bugsnag and Slack to:
- Indicate clearly that a Subs Placement job failed, meaning subscriptions were not placed
- Indicate the name of the Enterprise for which the job failed.
- Indicate the name of the Schedule and Order Cycle for which the job failed if possible.

With the enterprise name an support person should be able to figure out the Schedule and Order Cycle, but if these can be included in the message it will save time and increase confidence of the support person to take the appropriate mitigating action.

I am not sure how a tester will test this.

I think it might be a devtest issue. If any devs can see how testers can test this I would like to hear.

**Comment by sauloperez** [comment]
We just realized https://app.datadoghq.com/apm/trace/2306158473115529589?spanID=8579172554628913600 is a good example of this.

Needs to be confirmed but it really looks like because a `Credit card Credit Card has expired` exception was raised the user didn't receive any email telling the payment failed thus, we might get a customer support request in a few days.

We need to refactor the `if` branch to use conditionals instead of exceptions if we want the `else` branch to be evaluated :point_down: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/01e27dd68c1cba039265500ebd2e05ddfd01f7bc/app/jobs/subscription_confirm_job.rb#L48-L52

Or instead, catch these exceptions and send the failed-payment email in the rescue block.
