### ISSUE TITLE
duplicating an order cycle should check P-OC and remove enterprises and exchanges where permission no longer applies

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#502]
## Description
If P-OC (from a producer to a hub) is revoked, an established order cycle, that's already stocking the products, will continue to stock them. Further, if this order cycle is duplicated, it will continue to show the products of the enterprise which no longer grants P-OC. Only a new order cycle will remove this enterprise.

## Expected Behavior
If the P-OC permission is revoked, the products should straight away be taken out of the corresponding OC (the OC from the hub with wich the permission have been revoked). And of course if I duplicate the OC the producers shouldn't appear neither in incoming or outgoing.

## Actual Behavior
If the P-OC permission is revoked, products remain in the corresponding OC, and if I duplicate the OC, the producer and products are still listed. Technically a hub can keep on distributing a product that he has not authorization for during a very long time if he keeps duplicating OCs...

## Steps to Reproduce
1. Create an OC for a hub and list products from a producer. Launch.
2. Revoke the permission between the producer and the hub.
3.You see the products are still in the OC.
4.Try to duplicate the OC. Same result.

## Animated Gif/Screenshot

La belle ferme is a supplier for Hub demo open food france:
![bug4](https://user-images.githubusercontent.com/8135376/36849593-bb60d7c8-1d64-11e8-956d-ca569e3623ec.png)
An OC is opened with La Belle Ferme products listed
![bug5](https://user-images.githubusercontent.com/8135376/36849597-be1b673a-1d64-11e8-8f9d-2102f81f2c50.png)
I revoke the permission.
The products are still listed in the order cycle. I try to reload, no change.

If I duplicate this OC, the products for wich the hub has no more the permission are still there: https://www.useloom.com/share/3afad2db239f4692bc3b4c749e27bbe7

Only when I create a new order cycle, they can’t be added anymore:
https://www.useloom.com/share/f87ac10933a1486f8ade3e29add29da3

## Context
Re-testing old bugs.

## Severity
S3 - this is part of the "networking" feature we offer, but no user reported issues with that. And there is a workaround which is to create a new OC.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by myriamboure** [comment]
When thinking again about it, I think the problem is a bit more complex and the solution not so straightforward, as the hub may have stored some of the producer products and still want them to be sold in its OC. The problem with the way inventories work is that even if you use info from shop inventory you still need to stock the products from the producer... my proposal, as it's not such a big issue for now as I'm not sure we never had one problem with those type of permission withdrawal, is to close that issue as we are rethinking completely the product chain model and that will definitely involve review completely the inventory logic (will disappear as it is), permission logic, and also order cycle. What do you think @sstead @kirstenalarsen ? I think we don't want to spend time in solving bugs on things we are going to change soon if no one is impacted...

**Comment by sstead** [comment]
I agree that this is not a priority bug @myriamboure and by the time it does get prioritised much of the logic will have changed. So I'm happy that it's closed.
