### ISSUE TITLE
Failures at Checkout with StripeSCA and mastercards

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5068]
## Description

After switching to Stripe SCA users a reporting a small but significant number of failed payments.

The errors are caught and reported in Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5e79c71a41fa51001712e4f6?filters[event.since][0]=30d&filters[error.status][0]=new

For active Stripe users I have reverted their payment method from Stripe SCA to the old Stripe payment method.

## Expected Behavior

Successful Payments

## Actual Behaviour

Error on payment

## Steps to Reproduce

1. Currently unsure of the cause but I think Luis has some ideas
2.
3.
4.

## Animated Gif/Screenshot

![image1](https://user-images.githubusercontent.com/8669848/77514300-7bc22380-6e6e-11ea-8529-198dace2236d.png)

## Workaround

Revert to Stripe payment method

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 2.8 UK
* Browser name and version: Multiple
* Operating System and version (desktop or mobile): Multiple

**Comment by lin-d-hop** [comment]
IMages from Stripe relevant to this issue:

![Screenshot from 2020-03-27 13-31-40](https://user-images.githubusercontent.com/8669848/77773509-9b5d7580-7041-11ea-87a9-3af588c85762.png)


![Screenshot from 2020-03-27 13-32-16](https://user-images.githubusercontent.com/8669848/77773514-9e586600-7041-11ea-8c58-bea9957351c7.png)

**Comment by luisramos0** [comment]
The new stripe paymentMethodsAPI has a different list of card brands from the tokenAPI. For example tokenAPI returns "MasterCard" while paymentMethodsAPI has "mastercard" while active merchant uses "master" :see_no_evil: #mapping

This was not seen before because it doesnt cause any trouble with test cards. I think this will fix our problem in production although I can prove it. We need to try it with a read mastercard.
