### ISSUE TITLE
Could we add 'mark-up' as an enterprise fee type?

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#510]
Stroudco is concerned that if we call the enterprise fee a 'sales fee' we will need to pay VAT on it.  But if we call it a 'mark-up' that is VAT exempt.
Would it be possible to add mark-up as a separate category?
thanks
Nick
![screenshot 2015-04-22 16 57 39](https://cloud.githubusercontent.com/assets/10517702/7279115/7a7f4cd8-e911-11e4-9d93-ebe52ff84509.png)

**Comment by lin-d-hop** [comment]
@NickWeir63 Would it be appropriate to use the Name field to call it 'Mark Up' or '12% Mark Up' rather than '12%'.

I am very confident that you would not have to pay tax on it if you made it clear it was a mark up through the name. I'm sure the tax man wouldn't have an issue with an organisation working within the limits of a system then clearly labelling it.

**Comment by NickWeir63** [comment]
@lin-d-hop OK - good point.  I will close this issue
thanks
N
copying this to @FiferMags for interest because she helped me talk this through
