### ISSUE TITLE
[mobile ux] Use mobile keyboards for phone numbers and email addresses

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5104]
## Description

**- As a:** shopper on mobile
**- On page:** shop and account sections of the website
**- I want:** the relevant number or email keyboard to display so I don't have to keep switching between the standard keyboard.

NOTE: http://mobileinputtypes.com/

## Acceptance Criteria & Tests

**Sign up form**
- [ ] Email address field focus displays EMAIL keyboard
- [ ] Password fields focus displays PASSWORD keyboard

![Screen Shot 2020-03-30 at 4.43.17 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/9ab713a0-3a25-46b2-8b6f-718a48fb1023)

**Log in form**
- [ ] Email address field focus displays EMAIL keyboard
- [ ] Password fields focus displays PASSWORD keyboard

![Screen Shot 2020-03-30 at 4.42.39 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/b41bee94-b6dc-4c2a-898f-0f1d3488da1c)

**Forgot password form**
- [ ] Email address field focus displays EMAIL keyboard

![Screen Shot 2020-03-30 at 4.43.25 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/805e8703-c91b-478f-88ae-9cac1fb53f6e)

**Checkout form**
- [ ] Email address field focus displays email keyboard
- [ ] Phone number field focus displays TEL keyboard

![Screen Shot 2020-03-30 at 4.46.16 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/3584c728-3ad6-4d11-83f5-bda1f55ef910)

**Account setting page**
- [ ] Email address field focus displays EMAIL keyboard
- [ ] Password fields focus displays PASSWORD keyboard

![Screen Shot 2020-03-30 at 4.51.00 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/8347205c-cde6-48e0-93be-6b9c27afbf6c)

**Account credit cards page**
- [ ] New card details field focus displays TEL keyboard

![Screen Shot 2020-03-30 at 4.51.58 pm.png](https://images.zenhubusercontent.com/56ba8a956caf56c9d38c5f61/a039c46e-cb68-4517-93d1-045dfc79aa42)

**Comment by daniellemoorhead** [comment]
Hey @Matt-Yorkley does this seem worthy of the 'good first issue' label?

**Comment by Matt-Yorkley** [comment]
Yep, should be an easy one.

**Comment by rmklaus12** [comment]
I'll grab this one.

**Comment by sigmundpetersen** [comment]
Great thanks @rmklaus12 !

**Comment by rmklaus12** [comment]
Best practices question on this one - one issue for similar changes in multiple files. 
Separate commit for each file changed? Or something else? 🤔
Thanks :-)

**Comment by daniellemoorhead** [comment]
>one issue for similar changes in multiple files. Separate commit for each file changed? Or something else?

@mkllnk ?

**Comment by mkllnk** [comment]
@rmklaus12 
> one issue for similar changes in multiple files.
Separate commit for each file changed? Or something else?

Once commit for similar changes in multiple files sounds better. It's not about files but you can also separate by "view", meaning which page you are making the changes on. There is no definitive answer but what you are trying to achieve is:

* Each commit makes sense on its own. It doesn't break anything and you could deploy it.
* It's easy to review. So it's big enough to have a meaning but small enough to easily see the thing you are changing.
* Each commit addresses one thing. For example, you don't mix re-formatting at the top of a file with logic changes at the end of that file.

If you need to change only one attribute for each input field, you could probably do it all in one commit. But if different input methods have their own risks of being supported by different phones, it's good to separate them so that we can easily revert one commit without affected all the other inputs. For example if we find that `email` works perfectly, but `number` causes issues in some cases.

**Comment by rmklaus12** [comment]
@daniellemoorhead - the "Account credit cards page" does not have a telephone field :-) But if you were looking for a numeric keypad, that is showing up on my newer iPhone, but will test other's and get the telephone input type added.
