### ISSUE TITLE
Autosave missing when moving from Incoming to Outgoing Products setting up or editing Order Cycles

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5108]
## Description

When creating a hub order cycle you can move from screen two (incoming products) to screen three (outgoing products) by clicking on the tab at the top rather than using the buttons on the bottom right of the screen. 
When editing a hub order cycle you can move between screens one, two and three by clicking on the tab at the top rather than using the buttons on the bottom right of the screen. 
Navigating by the top menu bar means that any changes made to an order cycle before moving page are lost.

## Expected Behavior

Navigating by top menu bar of the hub order cycle should automatically save changes made or the hyperlinks should be removed from the top menu bar to force users to select 'save' or 'save and next' to navigate.

## Steps to Reproduce

1. Make change to incoming products of an order cycle.
2. Move to outgoing products section by clicking on the top menu '3. outgoing products'
3. Move back to 2. incoming products and changes made in step 1 are lost.
4.

## Workaround

![image](https://user-images.githubusercontent.com/45104035/77898578-443ee700-7273-11ea-81e6-65e753e93f29.png)

![image](https://user-images.githubusercontent.com/45104035/77898607-502aa900-7273-11ea-8e9b-bcb48efbd188.png)

## Severity

bug-s4

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Autosave on OC next buttons](https://trello.com/c/PKh4F9s7/784-autosave-on-oc-next-buttons)

**Comment by luisramos0** [comment]
just double checking: did you mean to move it to "prioritised papercuts" or to directly to "dev ready"?

**Comment by RachL** [comment]
Yes this cannot be moved to dev ready. Dev ready is for core-team only :)

**Comment by kirstenalarsen** [comment]
I don't think it should autosave - too error prone. Consistent behaviour with other parts of the site (like Enterprise Settings) would be to get a warning if you're leaving a tab or page with unsaved data. Let's do that

![image](https://user-images.githubusercontent.com/2911176/78467796-b1f78100-7753-11ea-91f1-78c95fb8e83e.png)

**Comment by mbudm** [comment]
I'm taking a look at this

**Comment by luisramos0** [comment]
Hey @mbudm I am not sure how good a first issue this is because you have to make the links in app/views/admin/order_cycles/_wizard_progress.html.haml verify if the forms are dirty...

I think you could use this to disable the links if the form is dirty:
ng-disabled: "order_cycle_form.$dirty"

But that's not exactly what's needed.

**Comment by mbudm** [comment]
Hi @luisramos0 yeah, originally I was looking at this in the wrong order cycle form but @mkllnk put me on the right track. I agree it's a bit more fiddly than first seems.

However your point about the dirty flag being accessible at `order_cycle_form.$dirty` made me think of a potential solution. 

I'm thinking to add click handlers to the wizard progress links, and in that handler check the dirty flag/show the alert/pass the redirect value (the href prop) to the alert so that if the user wishes to proceed they can. If the dirty flag is false then the click handler lets the default event occur (change the location to href attribute).

Let me know how that sounds, I should get a bit of spare time this week to try it out.

**Comment by luisramos0** [comment]
Hi @mbudm yes, that sounds like the right solution yes :ok_hand: 
You need to chose the right angular controller to put the handler (there's a little structure of controllers to control the different pages). I think this is where you will need to add the click handler:
app/assets/javascripts/admin/order_cycles/controllers/edit.js.coffee
