### ISSUE TITLE
Shop can see whether an order has refund owing on Orders page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5173]
## Description

- As an enterprise user (shop or hub)
- On page admin/orders
- I want to be able to see which orders have refunds owing 

Currently when an order is paid it looks like this
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a7bef105-5e61-4047-af4f-43fbf9295aa7)

and when a change has been made to the order so the customer is owed money (or has an account credit) it displays like this
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c1824032-8d3c-42c7-b82f-8a7046f1aaf3)

The Total column shows the revised total of the order, but I cannot see how much I actually owe them, in this case $5
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/a57b6bd6-c9b1-4e83-91cb-d7d9dbed0944)

Could we print this amount on the Orders page somewhere, so that the Shop can at least see at a glance what they owe. 

Suggested solution to print the amount in brackets after the link in the Payment State column, so 
- Credit Owed (40.00)
- Balance Due ($40.00)
not sure if there should be a -ve sign?

- ?? leads to ability to process refund from this page as per [wishlist item](https://community.openfoodnetwork.org/t/batch-processing-of-refunds/1893). I started creating an issue to do a single one but think it might be a  bit tricky

 
## Acceptance Criteria & Tests

1. Create a customer order and accept the payment
2. Remove an item from the order
3. Go to admin/orders and filter to see that order (if necessary)
4. The amount owing to the customer should show on the page, so I can easily see how much needs to be refunded, or how much has been added to their account credit

**Comment by luisramos0** [comment]
papercut size :+1:
related to https://github.com/openfoodfoundation/openfoodnetwork/pull/5031/files

**Comment by mathewdbutton** [comment]
Hey @kirstenalarsen I was going to try and pick this issue up if that's cool.

A quick mock up of what I was thinking
![Screen Shot 2020-04-28 at 10 28 22 pm](https://user-images.githubusercontent.com/1100707/80487107-9f154c80-899f-11ea-8f94-83eea9127f8b.png)

I wondered if the text should go underneath the payment state to take into consideration any refunds/balance due that run several digits long and squish up the table.

>Credit Owed (40.00)
>Balance Due ($40.00)
>not sure if there should be a -ve sign?

I wondered if the payment state itself could drive what the value in brackets meant instead of needing a -ve sign e.g.
```
Credit Owed
($4.00)
```
means we owe the customer $4
and
```
Balance Due
($4.00)
```
Means we're still to be paid $4

It might bit a little ambiguous though so perhaps a -ve or a colour could help, I'm not sure, any thoughts?

**Comment by kirstenalarsen** [comment]
Hi @mathewdbutton - yes I wasn't sure about this either! I think perhaps the negative is actually confusing here - saying 'credit owed: -$5.00' makes it a double negative and seem like perhaps it's a balance due! So I think let's go with what you've suggested above . .
@lin-d-hop @RachL @tschumilas any different views on this?

**Comment by tschumilas** [comment]
The only point where this might get confusing -  is if I am managing an account that has a credit owed, and I'm going to refund it  -  I do that by issuing a negative payment -  don't I?   I go to new payment, and make a negative payment.  So thats where the negative sign helps me frankly -  otherwise,  i could accidently issue a postive payment -  and then then is just further over-payment.   If we remove the negative sign,  whoever is processing the credit,  has to think to put it into the payment box.
Gosh its late -  am i making sense?

**Comment by kirstenalarsen** [comment]
I am pretty sure it gets automatically put into the new payment box as a negative ?

**Comment by kirstenalarsen** [comment]
But I don't have a strong view - if @tschumilas reckons -ve is best let's go with that :)

**Comment by RachL** [comment]
Yes let's keep the negative for now and see with user feedback later on. But I do agree that I'm myself re-assured by this sign :)

**Comment by luisramos0** [comment]
For me the -ve sign is confusing. It's a balance due of 5usd and a credit of 5usd.

**Comment by mathewdbutton** [comment]
I think I'll go with majority vote here, as I seem to be swayed by both arguments here. We'll see what the feedback looks like.

**Comment by kirstenalarsen** [comment]
can i do a facepalm emoji in github :) ? I'm calling it - go with the -ve thanks @mathewdbutton. If people are confused it's an easy thing to change

**Comment by mathewdbutton** [comment]
🤦 I got you covered @kirstenalarsen. Yeah I think it then keeps it consistent with the payments page which also displays the same information like this, with the -ve sign.

**Comment by Matt-Yorkley** [comment]
Closed by #5341
