### ISSUE TITLE
Customer account / payment methods report improvements

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#518]
and question . .

This report takes ages to load in a system that has lots of info in it. I'd suggest putting an initial filter into it (like the other reports), that only loads the last week or month to start with, so that it doesn't take so long to come up

![image](https://cloud.githubusercontent.com/assets/2911176/7290467/cc82ab54-e9c2-11e4-9b94-ffa70265575f.png)

Also, I am getting some data in it that doesn't make much sense to me. I am trying to work out what's going on, but not quite sure what it's trying to do, so just putting in a bunch of potential issues below and you can separate them out as you see fit :)

Issue 1: 
Logged in as southeastfood hub. The coordinator of sefhub has quite a few orders under her name (Naomi Atkins) BUT some of these are on her personal email and others on the admin email  
It appears that the balance calculation is using her name rather than the login email. I'm pretty sure this is incorrect, should be using the User (distinct email address) not the customer name for this calculation
![image](https://cloud.githubusercontent.com/assets/2911176/7290556/6f36fff2-e9c4-11e4-8059-5b859396bd46.png)

![image](https://cloud.githubusercontent.com/assets/2911176/7290567/94376be8-e9c4-11e4-9409-523f440a58f2.png)

Issue 2:
when looking at the same user (e.g.     ), different entries have different balance values

![image](https://cloud.githubusercontent.com/assets/2911176/7290600/25cefdb4-e9c5-11e4-80e1-28cadb4070a5.png)

![image](https://cloud.githubusercontent.com/assets/2911176/7290605/3aafd0e6-e9c5-11e4-80ae-09b5c8498b59.png)

Issue 3:
Assuming a +ve balance mean she is owed, and -ve balance means she owes, then the negative balance should add up to unpaid orders under that User (email)

This is showing (variously) the two values above, and one at -$5K (and a couple of others). 
![image](https://cloud.githubusercontent.com/assets/2911176/7290631/d239f0d6-e9c5-11e4-9cda-6d4f81899123.png)

I'm not sure where these values are coming from - can you tell me what it should be calculating (user, name, hub combo etc?) so I can then see if it is. The figures don't seem to be total outstanding against any of the above from my first estimates

**Comment by lin-d-hop** [comment]
Hrm... none of that looks very good at all...

The motivation behind this report was to show payment methods/deliveries for order cycle management. Would it make sense to you to have to select an order cycle to view data?

The calculation takes a 'user' (based on the person who did the order on the report row) and a 'distributor' (again referring to the specific report row) and finds all orders for that user-distributor combo, then sums all the payments processed to that user-distributor combo.

The user and distributor are both queried on ID. Happy to change to 'email' if that is a more fitting identifier. But the results above don't really fit what i'd expect. More explorations required...

@kirstenalarsen would you mind sending/asking someone to send through an au staging dump please. My last one is out of date and i reset my local db due to some rake errors. Also theres not enough data to test this with in the uk staging yet. Thanks!

**Comment by lin-d-hop** [comment]
This is now on staging2 :-)
@NickWeir63 do you have the time to test the changes and see if Kirstens issues above have been solved?

**Comment by NickWeir63** [comment]
Great.  Yes I can do this testing.  Please can someone send me the login details for southeastfood hub or a superadmin login for staging2
thanks

**Comment by lin-d-hop** [comment]
I always find it on slack by searching for testing@

**Comment by NickWeir63** [comment]
Logged into staging2 using the superadmin creds which Lynne gave me (testing@admin.com) but when I clicked on payment methods i got the grumpy cat.  this happened twice
![screenshot 2015-09-09 20 28 46](https://cloud.githubusercontent.com/assets/10517702/9772132/430939dc-5732-11e5-8075-270d86ce1993.png)

do we need to put an aus review label on this?

**Comment by lin-d-hop** [comment]
Haha, no need to screen shot grumpy cat ;-)

Nope I'll have a look. I noticed today that some changes I've made are being missed so I need to look into it more....
