### ISSUE TITLE
Archive/delete old migrations

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5215]
It would be really nice if we could delete/archive our old migrations. We have **442** migrations going back to **2012** and every one of them is run during every deploy. 

This makes the database migration step really slow, and is basically completely pointless, as all those state changes have already been applied. 

Having a huge pile of ancient migrations also increases the chance that at some point we'll change or delete some models in a way that breaks things.

I think we can do something (roughly) like this:
https://medium.com/clutter-engineering/cleaning-up-old-rails-migrations-1b55b638abb5

**Comment by mkllnk** [comment]
I'm pretty sure that old migrations are not run on every deploy. I've seen logging in the past where it looks like they would run but they actually don't.

I love a good cleanup. I never bothered with this because sometimes I find the old migrations helpful in understanding why a certain change was done. I can find the migration, see the commit and an explanation. But I guess I can search the history through the schema file.

I've seen another approach before where the old migrations are squashed to one that contains the schema of that time. So if you run db:migrate on an empty database, it still works. I prefer the linked idea above of failing in that case though. It might force us to adjust some deployment scripts, not sure.

**Comment by Matt-Yorkley** [comment]
I just tried switching and remaking my test database and running `db:migrate` and got this:
```
rake aborted!
LoadError: cannot load such file -- spree/core/preference_rescue
/home/user/Github/openfoodnetwork/db/migrate/20120327000664_namespace_promo_tables.rb:1:in `<top (required)>'
/home/user/.rbenv/versions/2.3.7/bin/bundle:22:in `load'
/home/user/.rbenv/versions/2.3.7/bin/bundle:22:in `<main>'

Caused by:
Polyglot::PolyglotLoadError: Failed to load spree/core/preference_rescue using extensions deface, rb
/home/user/Github/openfoodnetwork/db/migrate/20120327000664_namespace_promo_tables.rb:1:in `<top (required)>'
/home/user/.rbenv/versions/2.3.7/bin/bundle:22:in `load'
/home/user/.rbenv/versions/2.3.7/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
```

Looks like a migration from 2012 depends on deface...?

This issue might need to be prioritised very soon... :warning:
