### ISSUE TITLE
Missing Items from Orders

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5219]
## Description

A Hub had their first order cycle this week and took 67 orders. They fulfilled the orders using the email confirmation emails. All orders were correctly fulfilled - no known / deliberate changes to orders

Now, all (most?) of the orders have none or only one or two items in them - and are showing credit owed or balance due (if no items in them at all)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d4c47787-afcc-4ed0-9fd5-2efa59d7d27d)

It looks like the orders have had items deleted from them. The User swears they did not do this - and it is hard to imagine how they could have deleted most of the items from 67 orders without realising they were doing so. Possibly using Bulk Order Management, but they are adamant that they only used that to look at things

They have just cloned the order cycle to create their new order cycle and they were confused about stock / oc's etc and whether they needed to remove all the products from the new order cycle. 

## Expected Behavior
Orders should have all the items in them that the Customer ordered unless someone has actually edited the order to remove them

## Actual Behaviour
It appears that somehow items have been removed from orders without the hub manager doing so. There is a high possibility of user error but seems incredible that they would have actually managed to do this without realising

## Steps to Reproduce
Cannot yet replicate

1.
2.
3.
4.

## Workaround
na

## Severity
If this is not user error it is S1

**Comment by luisramos0** [comment]
here's a summary of what I have written in slack:

Incepted Invoices work: one solution to this will be the incepted invoices work with @rachel back in Nov2018 in Porto where we will need to take a copy of the order when the invoice is produced so that we know what the order looked like when the invoice was generated. Currently, we dont know what is the order history in terms of line_items.

The state of the orders: I confirm that the orders are mostly empty and some have a few line items, never like the amount payed.

OC clue: the orders are from 7, 8 and 9 April but if I look at the OC the variants were added to the OC on the 12April... I think this means the variants were removed from the OC and then re-added...

I wonder if we remove variants from the OC, are the already completed orders affected?
I'll test this now. It's doesnt, at least in my simple test.

It's still a fact that the variants were removed and re-added to the OC after the orders were placed.
But I cant find an explanation for this.
The only way this situation can be created in a more or less quick way is to open bulk order management and click each of the delete buttons.
BTW, the "ask?" button in the bulk order mgmt page is broken, isnt it? It still asks for confirmation on delete after it has been unchecked.

I think it will be useful to have another dev throw their brains at this one.

**Comment by kirstenalarsen** [comment]
ok - I am going to have to go through the orders and create adjustments to balance them all out (otherwise they won't get charged for the value of the orders). I am not going to recreate the orders with correct items in them as that's just too onerous. I would love a little 2nd eyes-over from @mkllnk before I go and change all the data  . .

**Comment by mkllnk** [comment]
I checked the sent out emails and one example confirms that the order was correct when placed but got altered later on. For example, order R826725577 is empty now with credit owed but the order confirmation was this:

![Screenshot from 2020-04-14 15-06-46](https://user-images.githubusercontent.com/3524483/79188226-d04f3200-7e61-11ea-9889-cc7b111b0e44.png)

**Comment by mkllnk** [comment]
The order cycle has 219 variants and 67 orders. When I look at bulk order management, all but one order disappeared. The easiest way to do that is to go to bulk order management, tick the "select all" tick box, then click on actions and "Delete Selected". That's three clicks.

I also checked the shop settings. Customers are not allowed to change their orders after checkout. Some orders still have an amount cached but once you click to edit the order it's updated to a $0 total.

**Comment by mkllnk** [comment]
I looked at two database backups.

1. Thursday 9th April 10am. The order cycle was still open and not all orders were in yet. Everything looks normal.
2. Friday 10th April 10am. All orders are in but bulk order management shows only the one item that is still in production. So something happened in those 24 hours that removed all line items but one.

That excludes a random effect that slowly creeps in over days. It looks like a sudden event. I also looked at the dates when variants where added. @luisramos0 I don't know how you got to your dates. I'm seeing the newest variants being added on Friday 10th April but there are plenty of variants that were added on Monday the 6th. And I guess orders for those variants disappeared as well.
```rb
oc = OrderCycle.find_by_name "11th april 2020"
ExchangeVariant.where(exchange_id: oc.exchanges).group(:created_at).order(:created_at).count
# {2020-04-06 01:32:04 UTC=>13, 2020-04-06 01:33:32 UTC=>13, 2020-04-06 01:33:50 UTC=>9, 2020-04-06 01:34:27 UTC=>27, 2020-04-06 01:34:50 UTC=>12, 2020-04-06 01:35:10 UTC=>4, 2020-04-06 01:36:02 UTC=>4, 2020-04-06 01:36:25 UTC=>6, 2020-04-06 02:14:12 UTC=>88, 2020-04-06 02:37:24 UTC=>3, 2020-04-06 07:04:19 UTC=>12, 2020-04-06 07:05:07 UTC=>27, 2020-04-07 00:35:03 UTC=>34, 2020-04-07 01:04:32 UTC=>3, 2020-04-07 01:36:28 UTC=>10, 2020-04-07 03:43:29 UTC=>2, 2020-04-07 03:45:34 UTC=>91, 2020-04-07 04:42:08 UTC=>4, 2020-04-07 04:43:14 UTC=>4, 2020-04-07 08:20:24 UTC=>5, 2020-04-08 02:09:11 UTC=>2, 2020-04-08 02:09:59 UTC=>1, 2020-04-08 02:09:59 UTC=>3, 2020-04-08 03:43:53 UTC=>11, 2020-04-08 05:48:56 UTC=>12, 2020-04-08 10:45:39 UTC=>7, 2020-04-08 10:46:19 UTC=>3, 2020-04-09 00:21:52 UTC=>3, 2020-04-09 00:22:55 UTC=>25}
```

My best guess is still user error. :shrug:

**Comment by luisramos0** [comment]
ah, BOM has the delete all action :boom:

**Comment by mkllnk** [comment]
I think we said at the delivery train meeting that we will close this unless we find it's not user error or more users are doing the same mistake.
