### ISSUE TITLE
Properties- change name of 'value' field to 'description', just so its function is more obvious to users.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#522]
![image](https://cloud.githubusercontent.com/assets/10843056/7312634/4073b146-ea92-11e4-8155-3ce6d3261b61.png)

**Comment by OliverUK** [comment]
@lin-d-hop @Matt-Yorkley 
Hi guys!
The label successfully changed to "description" rather than "value" in PRODUCT Properties. However, there is now a misalignment as shown below.
![screen shot 2016-12-09 at 14 05 19](https://cloud.githubusercontent.com/assets/17590921/21051629/25e1458a-be19-11e6-9e59-95334e341385.png)

In ENTERPRISE Properties the label is still "Value" and not "Description"
![screen shot 2016-12-09 at 14 07 42](https://cloud.githubusercontent.com/assets/17590921/21051649/3e1e3dce-be19-11e6-80a3-73e750ce6a79.png)

**Comment by lin-d-hop** [comment]
Thanks @OliverUK. Back to @Matt-Yorkley.

**Comment by Matt-Yorkley** [comment]
It looks ok on my local version:

![screenshot from 2016-12-09 22-33-53](https://cloud.githubusercontent.com/assets/9029026/21066958/68c132b0-be60-11e6-8648-7e29a86d7ac0.png)

I'm not sure why it would have changed..?

**Comment by OliverUK** [comment]
@lin-d-hop I tried build 136 uk/property_names in buildkite but don't seem to get any result. On reflection it may have been the wrong build?

**Comment by lin-d-hop** [comment]
@OliverUK My bad, should be in there now.

**Comment by OliverUK** [comment]
@lin-d-hop 
![screen shot 2017-01-22 at 10 03 42](https://cloud.githubusercontent.com/assets/17590921/22181744/20e3abc0-e08a-11e6-93f4-6fcbfe6f62d0.png)

**Comment by lin-d-hop** [comment]
@OliverUK try again with uk/property-names

**Comment by OliverUK** [comment]
@lin-d-hop 
![screen shot 2017-01-25 at 17 04 25](https://cloud.githubusercontent.com/assets/17590921/22300753/5ea0b64a-e320-11e6-913b-0aefccadeec0.png)

**Comment by OliverUK** [comment]
@lin-d-hop  still can't get this to stage

**Comment by lin-d-hop** [comment]
@OliverUK whats the error? You can find it by expanding the Staging button.

**Comment by lin-d-hop** [comment]
The relevant line (for future) is CONFLICT (content): Merge conflict in config/locales/en.yml

**Comment by OliverUK** [comment]
Gotcha.

**Comment by OliverUK** [comment]
Staged and tested. The enterprise properties now display "Description" rather than "Value" and the same applies to product properties. However please note the way it now displays the product property screen.

![screen shot 2017-02-03 at 15 10 25](https://cloud.githubusercontent.com/assets/17590921/22596376/3adfe64a-ea23-11e6-8bcf-983b9b1159fd.png)
![screen shot 2017-02-03 at 15 12 05](https://cloud.githubusercontent.com/assets/17590921/22596377/3ae185fe-ea23-11e6-9015-38bcc13c2999.png)

**Comment by OliverUK** [comment]
Here is how the product property currently displays on production.
![screen shot 2017-02-03 at 15 15 26](https://cloud.githubusercontent.com/assets/17590921/22596495/a809eedc-ea23-11e6-9d5e-b30d678c8d81.png)

**Comment by lin-d-hop** [comment]
@OliverUK Made a tiny change to this PR to fix the bug you found. Would you test again please? Thanks!

**Comment by OliverUK** [comment]
Build failed @lin-d-hop

**Comment by lin-d-hop** [comment]
@OliverUK we really need to get you past this being a total blocker for you....

**Comment by lin-d-hop** [comment]
Deployed to UK staging. All working as Expected:

![propertiesstaging](https://cloud.githubusercontent.com/assets/8669848/23368942/7d5f0144-fd07-11e6-85cc-f47d620bcf66.png)
![propertiesstaging2](https://cloud.githubusercontent.com/assets/8669848/23368945/7fa29d3a-fd07-11e6-9383-26c49420fe3a.png)

@OliverUK not sure why, this worked for me :-/ Not sure why it didnt for you sorry mate!

**Comment by daniellemoorhead** [comment]
@mkllnk to stage on Aus and @sstead to give the OK for 1.8.9 release next week.

**Comment by sstead** [comment]
Great, looks good to me.
![image](https://cloud.githubusercontent.com/assets/10843056/24440278/093023d4-149f-11e7-94d4-663b43769cc0.png)
