### ISSUE TITLE
OFN UK page load time https://openfoodnetwork.org.uk/producers

### ISSUE THREAD

**Issue by samuk** [openfoodfoundation/openfoodnetwork#5224]
## Description
Page take ~20 seconds to load
Trying to look at our record to update it

## Expected Behavior
Page should load in ~<2seconds

## Actual Behaviour
The page takes ~20 seconds to load

## Steps to Reproduce
Visit this page in Chromium https://openfoodnetwork.org.uk/producers
Or check this report https://tools.pingdom.com/#5c5d52ce73000000

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
Hi @samuk ,
Thanks for raising this! Great to have you here!

You are right - this page is problematic. We've hidden it on UK production because we just haven't been able to prioritise this page performance just yet.

In normal times we try to keep a cap on our open github issues .... mostly for morale purposes. In that vein I'm going to close this issue.

But please do keep reporting the things that you see as you find your way around!

**Comment by lin-d-hop** [comment]
Just to note for when we find this later...

Sam navigated here from a Google Search.... so we want to look at hiding pages like this from bots.
