### ISSUE TITLE
How does OFN count the number of incomplete orders?

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5236]
## Description

I have a user with 747 uncompleted orders. He is a bit worried because he never had any real orders. So he is afraid people don't manage to order...

## Steps to Reproduce

See uncompleted orders for hub 730 in French production

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/79369170-d243ee80-7f50-11ea-880b-1c053af7a544.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.2
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by lin-d-hop** [comment]
This number is based on the number of incomplete carts.
But for some reason OFN creates WAAAAY more carts that people actually need. A shopper will create a bunch of carts in the process of getting to checkout.

This quirk is coming up in all kinds of discussions at the moment so I think we might be working on it soon :-)

**Comment by luisramos0** [comment]
:+1:
I looked at FR live and this user is an outlier with 700+ carts, but I saw quite a few users with around 100 carts...
We need to create a new cart when the user changes shop but I dont think we should create a new cart when the user comes back after a few days for example.

**Comment by lin-d-hop** [comment]
I want to solve this properly as UK's S3 this round :trollface: 

@openfoodfoundation/train-drivers-product-owners We need to define the correct behaviour in order to solve this issue :-)

**Comment by RachL** [comment]
I would say that ad soon as an item is put in cart, the order should show as incompleted.

If the shopper comes back, it would be nice to use the same cart and not open a new one.

All the other cases where we open a cart (like when someone is visiting a shop), if we need them for technical reason, let's keep them. But we need to remove them from the list of uncompleted orders?

**Comment by jaycmb** [comment]
> I would say that as soon as an item is put in cart, the order should show as incompleted.

Current behaviour is order is in state `cart` as soon as items are selected (and stays in this stae until payment +shipment selected and shopper clicked 'place order').

> All the other cases where we open a cart (like when someone is visiting a shop)

We open a cart automatically when someone is visiting a shop?!

> If the shopper comes back, it would be nice to use the same cart and not open a new one.

That would be nice indeed, but sounds like more complicated. 
Should that involve showing the shopper previously saved items in the cart? Or only "reuse" previously generated cart/order if a user returns within a certain time period after having abandoned the cart (e.,g. because switching to another shop within same session)?

**Comment by RachL** [comment]
> Current behaviour is order is in state cart as soon as items are selected

@jaycmb are you sure of this? Many of the cart currently opened do not have any items.

> We open a cart automatically when someone is visiting a shop?!

More specifically, each time the person is login back in, see the discussion that has generated the issue:

https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1586458155387700

> but sounds like more complicated.

I'm not so sure about that. It sounds like Luis mentioned it above ☝️ 

> We need to create a new cart when the user changes shop but I dont think we should create a new cart when the user comes back after a few days for example.

If the user switch shops he is loosing the cart, I think we should keep this behavior.

**Comment by RachL** [comment]
@apricot12 @jibees if one of you picks this s3 up, the only task for now is to do a spike to understand in which cases today we open a cart. From there we will create other issues to remove or add cases where we open a cart.

Is the data in this issue useful or should I close it and just open a spike issue?

**Comment by jibees** [comment]
Regarding the code, and assuming that an order (ie. a cart) is opened when calling `lib/spree/core/controller_helpers/order.rb@current_order(true)`, we do create an order (if it does not exist) in the following place:

- `app/controllers/base_controller.rb#38`: when we set an order_cycle
- `app/controllers/cart_controller.rb#7`: `POST` on `/cart/populate`. Called by `app/assets/javascripts/darkswarm/services/cart.js.coffee@adjust() via update()` each time we edit a ship variant
- `app/controllers/enterprises_controller.rb#66`: `GET` on `/:id/shop` when order has insufficient_stock_lines (and then redirect to `/`)
- `app/controllers/enterprises_controller.rb#70`: when calling `reset_order` ie. each `prepend_before_action` on `/shop`
- `app/controllers/shop_controller.rb#15`: `POST` on `/shop/order_cycle`
- `app/controllers/spree/orders_controller.rb#43`: `GET` on `/orders/:id/edit` 
- `app/controllers/spree/orders_controller.rb#112`: `PATCH` on `/orders/:id`
- `app/helpers/shared_helper.rb#5`: called via view `app/views/shared/_distributor.html.haml`
- `app/services/order_completion_reset.rb#28`: seems to be used for _the "continue shopping" feature once an order is completed._
- `lib/spree/core/controller_helpers/order.rb#80`: not sure to understand but seems to be called each time we use Order (via `before_action` on `base.class_eval`)...

Saying that, I'm afraid that it is totally useless, because it seems to be called/used a lot. 

(_Next step_: trying to re-create each functionnal steps that leads to those lines.)

I'm wondering if there is an opportunity to log (with a certain level of severity, or a certain tag, or whatever, ...) each time an order is actually created (on `lib/spree/core/controller_helpers/order.rb#41`) with its own stack and then understand where does this empty cart comes from. 
Certainly a question more for @openfoodfoundation/core-devs

**Comment by Matt-Yorkley** [comment]
Yeah, there's lots of places where we create or discard carts for various reasons. I'm not sure we can easily remove them...

**Comment by kirstenalarsen** [comment]
This is really reassuring to me - so all those incomplete orders are not actually abandoned carts. It would be really good to have an understanding of how many of them are (and a way to track that) as that’s a metric I’d like us to be actually focusing on

**Comment by mkllnk** [comment]
I guess that you need to look at carts with items in there and ignore the empty carts because they get created all the time.

**Comment by RachL** [comment]
thanks @mkllnk for the suggestion! At delivery train today we decided that as a first step here we would hide uncompleted order with no line items from the user. This should close this s3 for now. @jibees it's all yours!

In parallel, we need to work on our metrics like conversion rates, both for our users but also to correctly assess the impact of the new slipt checkout work.
