### ISSUE TITLE
Notify producer email behaving in an overzealous manner

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5242]
## Description

Clicking the notify producer button can send 8 to 13 times the same email :boom:

## Steps to Reproduce

 In French production it is happening with hub 1395

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/79462356-aa5b9600-7ff7-11ea-8e61-22edce980f09.png)

## Severity

If this can damage our email reputation I would say s2 :(

## Your Environment
* Version used: v2.9.2
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by sauloperez** [comment]
We've seen errors like https://app.bugsnag.com/open-food-france/open-food-france-prod/errors/5e94a9c53d908b0017b28cfc?filters%5Bevent.since%5D%5B%5D=1d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bsearch%5D%5B%5D%5Btype%5D=eq&filters%5Bsearch%5D%5B%5D%5Bvalue%5D=Job&event_id=5e9862d50059ecf518a00000 since April 13th. My bet is that this failure causes DJ to retry the job and thus, emailing again recipients that did get the email successfully.

**Comment by sauloperez** [comment]
Confirmed, a job for the hub 1395 is the last one that failed.

![Screenshot from 2020-04-16 16-32-28](https://user-images.githubusercontent.com/762088/79468993-ec88d580-7fff-11ea-844d-a87cf67fc68b.png)

**Comment by sauloperez** [comment]
Just to be clear, the OrderCycleNotificationJob is enqueued once but delivers as many emails as suppliers. If any of these fail, DJ retries the entire job. That's why successful recipients get spammed while the failed ones keep failing.

**Comment by luisramos0** [comment]
Nice one Pau.

>>  we should enqueue a job per supplier

Yes, very easy. Basically moving the to first lines (each) in OrderCycleNotificationJob#perform to OrderCyclesController#notify_producers
