### ISSUE TITLE
Missing translations keys in orders listing

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5246]
## Description
Except the first one, none of the table titles of this page have translation...

## Steps to Reproduce
1. Go to `/admin/orders?q[s]=completed_at+desc`
2. See columns titles

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/79487457-8d838a80-8018-11ea-8f42-da79c2e41a9b.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.2
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by rmklaus12** [comment]
Similar to #4966 I resolved this one as well. In both, the keys needed to be in spree.admin.shared, which did not exist in en.yml. I added those and the necessary keys for the ones missing and missing translation errors/classes are not resolved. Is there anything I might be missing?
As they would be my first PRs, I'm hoping to get the go ahead since they are not currently assigned to me.

**Comment by sigmundpetersen** [comment]
Hey @rmklaus12 I assigned you and moved the issue to the In Dev column (same with 4966). Please submit your PR and you will get feedback on the code directly 🙂 Thanks!
