### ISSUE TITLE
Welcome Email URL Error

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#525]
The welcome email for a new user says:

Your login email is info@deanforestfoodhub.org.uk

You can start shopping online now at demo.spreecommerce.com 

We need to update the url to start shopping

**Comment by nickwhite75** [comment]
anyone changed it?

**Comment by NickWeir63** [comment]
I tried to test this but didnt get a welcome email.  UK staging is not sending out emails to confirm orders or to change passwords so I guess this is the same problem.  When @aidandunsdon and @pmackay have fixed issue 627 I will have another go at this

**Comment by NickWeir63** [comment]
This is now working on staging with this message:
Welcome to OFN UK Staging! 
 
Your login 
Your login email is nickweir23@gmail.com 
You can start shopping online now at staging.openfoodnetwork.org.uk 

I haven't been able to test this on Production because the email notifications aren't working at the moment

**Comment by elf-pavlik** [comment]
Did you resolve this issue already?

**Comment by pmackay** [comment]
@NickWeir63 do you know if this is ok now on UK production?

**Comment by NickWeir63** [comment]
Sorry yes this is tested and does work OK - thanks all
