### ISSUE TITLE
Impossible to filter order page with several OC

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5299]
## Description

When selecting several OC as a search field on the order page, the result only shows one OC.

## Steps to Reproduce
1. Go to `/orders?q[s]=completed_at+desc`
2. Select several order cycles (OC) in the search field
3. Check the results

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.3
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by dacook** [comment]
This seems unrelated to sorting, I think the issue is that it's only showing orders for the last selected Order Cycle. 

I can see that only the last OC ID selected has been retained in the api orders controller params
(app/controllers/api/orders_controller.rb). Eg: 
http://0.0.0.0:3000/api/orders.json?page=1&per_page=15&q[completed_at_not_null]=true&q[order_cycle_id_in]=1&q[order_cycle_id_in]=3&q[s]=completed_at+desc
Results in:
```
{"completed_at_not_null"=>"true", "order_cycle_id_in"=>"3", "s"=>"completed_at desc"}
```
I assume tags are used like this elsewhere so will take a look...

**Comment by dacook** [comment]
I must be a bit rusty on my GET param knowledge.. but it seems it needs to have trailing square brackets, ie:
http://0.0.0.0:3000/api/orders.json?q[completed_at_not_null]=true&q[order_cycle_id_in][]=1&q[order_cycle_id_in][]=3

Firefox seems to consider either form acceptable as an array, but I guess Rails doesn't.

The DOM seems correct:
`<select ... id="q_order_cycle_id_in" multiple="multiple" name="q[order_cycle_id_in][]"`

Ahh this kind of issue would happen anywhere an `_in` operator is used. After a codebase search I find a couple other examples, and they all add the square brackets in the the JS.

So this was only affecting the orders screen. Note that it was also affecting the Distributors multi select tag here too.

Fixed, will work on adding a test when I next get the chance.
