### ISSUE TITLE
Release v2.9.8 Fricandó

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5391]
Steps: 

- [x] Include translations
- [x] https://github.com/openfoodfoundation/openfoodnetwork/releases
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/1409
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A

**Comment by Matt-Yorkley** [comment]
Notes: 
- #5317 has been added to the release (release notes, target commit, and test build are all updated)
- #5352 has not been tested yet, but might go in?

**Comment by Matt-Yorkley** [comment]
#5352 is now in, everything updated :+1:

**Comment by filipefurtad0** [comment]
Hey @sauloperez and @Matt-Yorkley ,

The release is good to go.

Testing notes:
https://docs.google.com/document/d/1r08803V_vzv4o7e7loIkYP7xdyD98mecEPnp-1TBCZM/edit#

One comment:
The report admin/reports/orders_and_distributors shows repeated entries for the same order. For example, an order of 4 items shows up as 16 entries in this report. Is this the expected behaviour? In any case, I observed this before staging and before the more recent PRs.

**Comment by sauloperez** [comment]
> The report admin/reports/orders_and_distributors shows repeated entries for the same order. For example, an order of 4 items shows up as 16 entries in this report. Is this the expected behaviour? In any case, I observed this before staging and before the more recent PRs.

I'm not sure what's the expected of that report but this sounds like a bug to me. Can you create an issue and discuss there?

**Comment by filipefurtad0** [comment]
I'll do so - thanks for the feedback @sauloperez !
