### ISSUE TITLE
JS errors on checkout

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5402]
## Description

Some users have a js error that prevent them to checkout on some browsers (around 27 cases in the past 7 days).

The checkout button does react to the click of the pointer.

The same happens with the connection button as is #5080 However user can workaround it by connecting after changing their password. On checkout the option for workarounds are limited if the user does not know how to use a second browser.

From France all claims are on browser Chrome only so far.

## Steps to Reproduce

No idea...

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/81598680-fbc52e00-93c7-11ea-951f-d5e326d6005f.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.7
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment]
3 new complaints since last week. All on Chrome.

**Comment by luisramos0** [comment]
I dont see this particular error in bugsnag...

The error is on a call to t in Checkout.submit.
Because there are two entries in the console log shown for Checkout.submit, I think it will be the call inside the catch at the end:
https://github.com/openfoodfoundation/openfoodnetwork/blob/c73defa8a1eaca230f58196058c8ae4e5bfec827/app/assets/javascripts/darkswarm/services/checkout.js.coffee#L15-L25

In this case the user must have seen the message "Submitting your order: please wait".

If the error happened inside the catch, it would explain why we dont see the bugsnag error, because the bugsnag alert is sent on the next line (throw).
One simple improvement we can do is to always send the original error to bugsnag, even if there is a problem translating the "checkout failed" message. I created a PR for that.

I am not sure this is enough. I am afraid the original error message will be one of the generic messages we already see in bugsnag. But maybe not.

I'll ping devs on slack so someone else has a look as well.

**Comment by luisramos0** [comment]
5402 wont fix the problem for sure but it will probably give us more info in bugsang about the issue.

**Comment by luisramos0** [comment]
@errors is probably dead code but I didnt want to touch it in my previous refactoring code, so I left it...

**Comment by luisramos0** [comment]
We will wait and see the errors now that 5528 is live.

**Comment by Matt-Yorkley** [comment]
Okay, I had a rummage around in Bugsnag for checkout-related errors. 

### Response data is null

There's a number of cases where it looks like we've used this conditional on the response (in `#handle_checkout_error_response`): 
```javascript
if response.data.path
```
and we've hit this error: `TypeError: response.data is null `. Maybe we can adapt it to be a bit more cautious, eg:
```javascript
if response.data?.path?
```

There's also a separate set of very similar errors, which are also triggered from within `#handle_checkout_error_response`:
```
TypeError: Cannot read property 'path' of null
```

### Element not mounted

This error pops up several times:
```
We could not retrieve data from the specified Element. Please make sure the Element you are attempting to use is still mounted.
```
I'm pretty sure this is Stripe-related and the `Element` is a Stripe Elements object.

**Comment by Matt-Yorkley** [comment]
### Chrome security policies

The bit that concerns me most with the dev-tools screenshot in the original issue (especially given that the reports seem to be related to Chrome) is this:

![chrome](https://user-images.githubusercontent.com/9029026/84359418-e448b300-abc8-11ea-849d-34b2f3a0e924.png)

Essentially Chrome is proposing changes to cross-site resource loading that will break OFN, and telling us the changes will be enforced in some upcoming version. There are a few security-labelling type things that are currently optional that we should implement sooner or later, both with cookies and with scripts. Essentially the code just needs to be explicit about declaring what external content be regarded as safe, like "yes, allow scripts and cookies from stripe.com".

Relevant info here, specifically on the Chrome / Cookies issue: 
https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html

**Comment by Matt-Yorkley** [comment]
I think this probably deserves three separate issues/PRs (outlined above).

**Comment by luisramos0** [comment]
Awesome investigation Matt :tada: 
I think we should do 5583 and 5585 now and maybe leave 5584 for a bit later.

**Comment by RachL** [comment]
Let's keep #5584 only open. Closing this one.
