### ISSUE TITLE
Release v2.9.10 Chop suey

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#5488]
Steps: 

- [x] Include translations
- [x] [Draft new release](https://github.com/openfoodfoundation/openfoodnetwork/releases/edit/untagged-754247139ddad4f264f8)
- [x] Notify #instance-managers of user-facing changes.
- [x] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-9-10/builds/1
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

**Comment by RachL** [comment]
@kristinalim all good :) https://docs.google.com/document/d/1VATnN9bnV6wKNydZMJbbnGNQVvW8DLH37vnql9fvXaY/edit#

I just noticed we are introducing a text for enterprise managers that is not really accurate, but Luis already made a PR to fix the issue: https://github.com/openfoodfoundation/openfoodnetwork/pull/5392#issuecomment-633481713

So basically the text will be wrong during - worse case scenario - 1 week and will affect only managers creating new shipping methods. Maybe it is ok as long as we inform instance managers? Otherwise it might be good to change the text introduced in #5399  before deploying the release.

Thoughts?

**Comment by luisramos0** [comment]
I think the PR is easy enough to be reviewed and tested today:
https://github.com/openfoodfoundation/openfoodnetwork/pull/5493

**Comment by RachL** [comment]
@kristinalim actually there might be a release blocker in what Luis' is describing here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5440#issuecomment-633668755 

I will make an issue when I come back online in a few hours, unless someone else already has.

**Comment by filipefurtad0** [comment]
Here it is:
Switching between shops does not work correctly #5496

**Comment by luisramos0** [comment]
I think the easiest way forward is to create a branch with the release and patch it with both #5501 and #5493
After that we can stage that patch and run some tests to validate it's good to go.
Sounds good?

**Comment by RachL** [comment]
@luisramos0 yes!

**Comment by luisramos0** [comment]
I have created the branch with 2.9.10 + 5501 + 5493 and updated the sempahore link in the description of this issue. It's ready for testing.

**Comment by filipefurtad0** [comment]
It's good to @luisramos0 :tada:

**Comment by luisramos0** [comment]
ok, I published it now.
@kristinalim I think this can now be deployed whenever possible.
