### ISSUE TITLE
Ensure all new translations copies are included in the release

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#5499]
## Description

It's been a few times already that the Transifex PR doesn't get merged before the release publication and thus, those copies don't get into the release. This is especially annoying for non-English speaking instances and their managers.

It seems that pulling translations manually when drafting the release doesn't include those present in the PR.

**- As a:** instance manager
**- I want to be able to:** get the translations I made in Transifex to be included in the upcoming release without having to remind the release manager to do so or hear it from annoyed users.

## Acceptance Criteria & Tests

The translations made in Transifex do not require any manual intervention to be included in the release beyond the existing pull step of the release preparation. There are enough manual processes and stuff in the pipe already.

When a translator does her work, she can be sure these copies will be visible in the app upon next deploy.

**Comment by sauloperez** [comment]
It seems that https://github.com/marketplace/actions/merge-pull-requests#configuration is potential solution. It lets us keep using the PR so we still have visibility over the process.

> MERGE_FILTER_AUTHOR: When set, only pull requests raised by this author will be merged automatically.

**Comment by luisramos0** [comment]
yes, sounds good to me :+1:

**Comment by mkllnk** [comment]
Thank you @sauloperez for bringing this up. Our process needs improvement. Let's discuss it.

> It's been a few times already that the Transifex PR doesn't get merged before the release publication

Really? When did we forget merge the PR?

> It seems that pulling translations manually when drafting the release doesn't include those present in the PR.

I don't know how that's possible. Transifex doesn't know about our PR. And I just tested this, `tx pull --force` downloads all translation files even though there is an open PR. My theory is that the translations happened after drafting the release. But it would be interesting to look at an example, we should have all data to confirm this.

I see several issues with the current process. Often it happens this way:

- A language is translated to 100%.
- Our txgh server receives a webhook and creates the Transifex pull request (or adds to it).
- People fix a typo and this doesn't trigger a webhook, we don't see it in Transifex.
- People translate but don't complete 100% and we don't see it.
- We merge the Transifex pull request before the release.
- We then download all missed changes and commit them straight to master.

> It seems that https://github.com/marketplace/actions/merge-pull-requests#configuration is a potential solution. It lets us keep using the PR so we still have visibility over the process.

Closed pull requests are pretty invisible to me.

I'm wondering if we should simplify the process and commit straight to master instead of opening a pull request. It's still visible in the commit history. We didn't want to do that in the beginning because we were deploying straight from master but now we have a release process with testing which should safe-guard against any weird Transifex commits (which didn't happen so far).

Another improvement of the process would be to check for new translations before publishing the release. If there are new ones, we can add them to the tested release commit and tag that one for the release. This would catch all translations between Thursday and Monday which are probably the ones we often miss in a release.

What do you think?

**Comment by RachL** [comment]
> Really? When did we forget merge the PR?

@mkllnk it's not really about forgetting. The scenario is more like this:
1. Some last PR are merged
2. The release is prepared with translation
3. Translator are notified there are new string to translate because of 1. They do it. BUt 2 already happened, so it will not be included in the next release.

And this is pretty bad when (1) included keys shown on the shopfront. All improvement in the OC dropdown and cart page lately have fallen into this scenario. And as for our reputation, this lead to text that is not understood by French users...
A fresh example: https://github.com/openfoodfoundation/openfoodnetwork/issues/5399 is still shown in English on the French instance.

> Another improvement of the process would be to check for new translations before publishing the release. If there are new ones, we can add them to the tested release commit and tag that one for the release. This would catch all translations between Thursday and Monday which are probably the ones we often miss in a release.

Yes that would totally solve my scenario.

**Comment by sauloperez** [comment]
Alright, thanks for clarifying the scenario @mkllnk and @RachL .

The problem I see is that there's a conflict between last-minute PRs and getting translations on time before the deploy. Even with any extra machinery to get them included in the draft release are we sure all translators will notice they need to add new copies? the release manager will need to tell them before the deployment day or do you see all non-English instances checking translations on Monday @RachL ?

**Comment by RachL** [comment]
@sauloperez I would like to stress that those were not last minute PR. If on Thursday you merge PR AND you prepare the release, _none_ of the PR you have merged that day will have translations: transifex notifies translators only after the PR is merged.

So yes maybe we can define a rule, like Monday is the last day to review translation, but maybe on he reverse side we need to make a rule that say we cannot squeaze PR if they have translation key for the shopfront, unless they are s1 or something?

There is no way we can make translation happen before merging a PR right?

**Comment by mkllnk** [comment]
> There is no way we can make translation happen before merging a PR right?

That's right. Transifex doesn't support this.

> make a rule that say we cannot squeaze PR if they have translation key for the shopfront, unless they are s1 or something?

Possible. So on Thursdays we can only merge PRs that don't add content to the language file. What if someone merged on Wednesday? One day is not enough for translators.

> Monday is the last day to review translation

That sounds good to me. So people have four days to translate. If we need more translation time, we need to prepare the release earlier.

It's still not perfect because master may contain different content to the drafted release and on Monday people will translate that latest content which may be in conflict with the drafted release content.

This could work though:

- Thursday the last PRs get merged.
- The release is drafted.
- Testers are notified to test.
- Translators are notified to translate.
- Since testers are busy with the release, it's unlikely that new PRs are merged before the weekend.
- After the release translation, we wait for the next release before translating again. (This step may not be important. The chance of a conflict is very low.)

One issue here is that Transifex looks at our translations only once a day. We can change that by switching to the new Transifex Github integration: https://www.transifex.com/blog/2019/github-integration/

**Comment by RachL** [comment]
> One day is not enough for translators.

Hmm. I wonder about that. I'm now realizing that Transifex is powerfull but also a blocker for releasing more often :/ 
Another question sorry: so Transifex does not support translating before the PR. In a continuous delivery scenario, pushing to transifex could update "directly" the live platform? I know we are not there yet, I'm just trying to understand the boundaries of a tool like Transifex. In my other projects I edit the yaml file directly 😁 so I have no big experience in translation tools.

**Comment by mkllnk** [comment]
> pushing to transifex could update "directly" the live platform?

Not directly. A Transifex update can be pushed to master straight away. And in continuous delivery we would then deploy master and it would be "live". It would maybe take an hour from a commit to production deploy.

Maybe we should tell Transifex what our requirements are. I'm sure others need that as well. It would be awesome if they could support pull request translations one day.

**Comment by sauloperez** [comment]
I see we all mostly agree. We all see frictions everywhere and it really feels like a chicken egg problem. My biggest concern since the beginning was also now going in the opposite direction of releasing/deploying more often.

IMO the chicken-egg nature of this lies on two facts:

* As @mkll pointed out, if we decide we deploy after merging the Transifex PR, we don't know which commits landed in `master` between the last release and this merge commit. It could be risky.
* Another option, deploying from the transifex branch the basic assumption that production servers get deployed from `master` and thus, it's the only "source of truth". This adds risks to the processes that depend on this assumption.

We had a quick chat with @rachl and two interesting things came up:

* It's a competitive advantage in FR. "French by default" is a sales argument of OFF competitors.
* Missing translations is somewhat acceptable in the back-office but is a much bigger problem in the front-office.

We haven't found any quick solution. There doesn't seem to be a way around taking the next step towards more frequent releases. That means investing in specific bits of test automation and raise the bar a bit more, so we also gain a bit more confidence and then drop some manual cases from the release testing or not. Currently, is manual testing what makes it hard to release more than once a week.

In the meantime, we propose the dev in charge to be the one to ensure the new copies get translated. Beware of the timing of the merge and ping instance managers if needed to make sure they make it to the release. Watch that PR so what gets shipped is of quality enough, like we do with everything else.

**Comment by RachL** [comment]
So as we discussed it in delivery train I'm closing here and adding a link in the notes.
