### ISSUE TITLE
[Spree 2.1] Broken spec - ShopsController missing routes

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#5504]
These were introduced recently from merging master. 

Errors:

```

  1) ShopsController as a non-authenticated user #show returns shopfront data for an enterprise
     Failure/Error: spree_get :show, id: producer.id
     
     AbstractController::ActionNotFound:
       The action 'show' could not be found for ShopsController
     # ./spec/controllers/api/shops_controller_spec.rb:27:in `block (4 levels) in <module:Api>'

  2) ShopsController as a non-authenticated user #closed_shops returns data for all closed shops
     Failure/Error: spree_get :closed_shops, nil
     
     AbstractController::ActionNotFound:
       The action 'closed_shops' could not be found for ShopsController
     # ./spec/controllers/api/shops_controller_spec.rb:37:in `block (4 levels) in <module:Api>'

```

**Comment by Matt-Yorkley** [comment]
I can't replicate this locally...?

**Comment by luisramos0** [comment]
me neither. but it's broken here:
https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5487/builds/11
maybe just flaky.

**Comment by Matt-Yorkley** [comment]
These specs are now green in the latest `3-0-stable` build.

**Comment by Matt-Yorkley** [comment]
This might be flaky...

**Comment by luisramos0** [comment]
This is the same as #5533 Api::EnterprisesController and Api::ShopsController are the only controllers that also have an equivalent controller on the base namespace EnterprisesController and ShopsController. Rspec picks those controllers instead of the Api:: ones.

I'll apply the fix to both controllers just in case:
https://github.com/openfoodfoundation/openfoodnetwork/issues/5533#issuecomment-637716769
