### ISSUE TITLE
Product pictures are not showing up for France

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5524]
## Description

Product pictures have disappear since the last release.

## Steps to Reproduce

1. Go to any shops on OFF https://www.openfoodfrance.org/shops#/

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/d59e1bce-3053-4323-9809-c006010b4f85)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
* Version used: v2.9.10
* Browser name and version: All
* Operating System and version (desktop or mobile): both

**Comment by RachL** [comment]
This is looking good! Thanks @Matt-Yorkley 👍

**Comment by luisramos0** [comment]
@Matt-Yorkley can you add a few details here, what was the problem and how ti was solved?
I am curious about what are the specific S3 settings we have in FR.

**Comment by Matt-Yorkley** [comment]
Okay, so the issue here was related to S3 image settings and only affected France. All other instances with S3 seem to use this setting for the path:

![Screenshot from 2020-05-29 11-53-34](https://user-images.githubusercontent.com/9029026/83247016-376f3e80-a1a3-11ea-90ad-2a4da447b950.png)

Whereas France was using this setting:

![Screenshot from 2020-05-28 22-35-10](https://user-images.githubusercontent.com/9029026/83247094-5a015780-a1a3-11ea-8ac7-1005c19c02c0.png)

`:rails_root` is a placeholder here which expands the full path, which in this case was the full image, which recent changed from being in `/current` to a symlink in a different location.

The "path" given here is basically a virtual path that Amazon uses to identify/name images. So the generated URLs on our side were not pointing to the correct place in the bucket, but to a different path that included a per-release timestamp.

I manually adjusted the setting and changed the `:rails_root` prefix to `/home/openfoodnetwork/apps/current` and the image paths were all fixed.

**Comment by luisramos0** [comment]
thanks for explaining Matt! This info may be useful in the future as well.

**Comment by rafaelbbrazdmc** [comment]
Exactly same issues in Brazil! I did this and works well.

**Comment by RachL** [comment]
I'm reopening this one. Pictures are down again :'(

**Comment by luisramos0** [comment]
I see the values in live FR are again the values Matt comment above says are incorrect for France.
I changed the values but still no luck.
The error message is something like "All access restricted to that object"..
I tried to login on AWS FR and I see this:
![image](https://user-images.githubusercontent.com/1640378/85955295-6c72da80-b975-11ea-8306-364b1af7b385.png)

**Comment by Matt-Yorkley** [comment]
If nobody has logged in and changed the settings, could the "All access to this object has been disabled" message be due to a billing issue?

**Comment by luisramos0** [comment]
yes, 7usd to be paid...
Apart from that needed "fix" (pay the bill) I wonder why the settings were back to not start with :rails_root...

**Comment by luisramos0** [comment]
I think I may have changed the wrong values, Matt's comment was about "Attachments PATH" while I changed "attachments  URL" and "attachments default URL". I reverted my changes now, this may need to be verified after the aws account is unlocked.

**Comment by RachL** [comment]
@luisramos0 @Matt-Yorkley thanks! It appeared the credit card for this account expired in February. I don't understand why we didn't get any emails :( anyway I've paid now. But I guess it will take some time to be reactivated.

**Comment by RachL** [comment]
Ok images are back! I'm closing. Thank you everyone!
