### ISSUE TITLE
Stripe Belgium

### ISSUE THREAD

**Issue by TheoGallez** [openfoodfoundation/openfoodnetwork#5550]
## Description
The API doesn't match between Stripe account and OFN. 
I clic to the connect stripe, I clic to accept condition between OFN/stripe en then a choice: 
- I have an account, I try to merge it => error 
- I création an account, I try to merge it => error

## Expected Behavior
The API have to match between Stripe and OFN. 

## Actual Behaviour
Both account with se same e-mail address in OFN and Strip don't match the link between Stripe and OFN. 
One exemple is: info@rosoir.be
https://openfoodnetwork.be/stripe/callbacks?state=eyJhbGciOiJIUzI1NiJ9.eyJlbnRlcnByaXNlX2lkIjoibGUtY29tcHRvaXItZmVybWllci1kdS1yb3NvaXIifQ.0FxnFouLt-yCozWzZ1e4XjH8s6-RotF0i8xMiVL46E4&scope=read_write&code=ac_HLiGWfbRQMTP4Vfb0nBP53ZHavTxbmHE

## Your Environment
I can't have a personal stripe account because I'm not a producer/hub. 
I can manage the account of the instance stripe account. => but I need help to understand how to manage it. 
The IPA heu... ;) The API is right between OFN Belgium and stripe. 

I'm available online 2-5pm this 3 June and 8:30am to 5pm this 4 June. (Belgium hour)

**Comment by RachL** [comment]
Hub ID is 315

**Comment by TheoGallez** [comment]
Waiting for news of the producer. I test it with the support. 
He chose stripe SCA. I change with stripe. (paiement methode)

**Comment by RachL** [comment]
@TheoGallez as there is no news I'm assuming this is ok now. Feel free to reopen if it is not the case! Thanks :)

**Comment by SophieDuponcheel** [comment]
Salut Rachel :) 
This problem has been around for some time but I've been busy with other things.
I still have the problem with stripe, I can't connect the stripe account with the entreprise/shops "central Oxfam magasins du monde". Rachel had already tested with another stripe account, and it worked. 
Maybe it's a problem because the stripe account (the bank account number) is the same as the one used for OFN Belgium?

Thanks for helping me

![image](https://user-images.githubusercontent.com/63047606/84236849-9d8b8800-aaf8-11ea-86d6-b74dc167620b.png)

![image](https://user-images.githubusercontent.com/63047606/84236866-a419ff80-aaf8-11ea-95c9-5e7e7e58368a.png)

**Comment by lin-d-hop** [comment]
Sophie, two possible things.

1) You cannot connect an enterprise account to the same account as the Stripe Connect account. You should see an error like this:
![Screenshot from 2020-06-10 08-32-58](https://user-images.githubusercontent.com/8669848/84240025-50f27d80-aaf5-11ea-9110-eb1480ff0124.png)

The Stripe Connect account is the instance stripe account and this needs to be different from the Stripe account for the enterprise you are connecting. You will need two Stripe accounts for this (though it should not matter if they are connected to the same bank account).

2) I've had trouble connecting Stripe in the past when I was logged in in the browser with a different Stripe account than I was trying to connect with OFN. Try logging out in the browser and in OFN and then log in fresh in OFN.
