### ISSUE TITLE
Make date filter inclusive of the date selected

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5555]
## Description
**- As a:** enterprise user or super admin
**- On page:** `/admin/orders?q[s]=completed_at+desc`
**- I want to be able to do:** when selecting dates, I would like the search results to take the end date I've selected into account.

Currently the dates are selected at midnight, which means the start date is taken into account but not the end date. This is confusing for users.

We need to change the date selection to `completed_at_lteq` and `completed_at_gteq`

Reference: https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching#lteq-less-than-or-equal-to

## Acceptance Criteria & Tests
1. Got to `/admin/orders?q[s]=completed_at+desc`
2. Select a start and an end date
3. You should see the orders from these dates included in the search result.
4. Change the date selected and see the result are changed accordingly.

Do this test as enterprise manager, but also as super admin.

**Comment by dmarcoux** [comment]
Hi @RachL, could you assign me to this issue? I would like to tackle it.

**Comment by sigmundpetersen** [comment]
Hey @dmarcoux here you go 🙂 Thank you!

**Comment by RachL** [comment]
ping @luisramos0 I think you've suggested setting completed_at_lteq and completed_at_gteq . Maybe you have an opinion on the proposed solution? :point_up:

**Comment by luisramos0** [comment]
hey @dmarcoux thanks for your analysis.
I think the timezone issue is a problem in your local environment. The default timezone is melbourne:
https://github.com/openfoodfoundation/openfoodnetwork/blob/dd9d9e331677539783be44015867b08bb410314c/config/application.yml.example#L10
and the comment is that # Time zone must match the operating system time zone in order to pass all tests.
Maybe we can improve the docs or this comment.

I still the solution will be to use order_completed_at_gteq and/or order_completed_at_lteq so that <= and >= are used instead of < and >

I see in the code that the bulk orders management page (admin/orders/bulk_management) is slightly different.
In admin/orders code:
 'q[completed_at_lt]': $scope['q']['completed_at_lt'],
 'q[completed_at_gt]': $scope['q']['completed_at_gt'],
in admin/orders/bulk_management
"q[order_completed_at_gteq]": $scope.formattedStartDate,
"q[order_completed_at_lt]": $scope.formattedEndDate

We just need to play with these params and see what makes it work the way we want.
The requirement is clear:
filter on 2020-06-03 to 2020-06-06
should return order between 2020-06-03 00:00:00 and 2020-06-06 23:59:59
