### ISSUE TITLE
[Rails 4.1] Mutator methods called on Relation

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5607]
Where we use mutator methods, we need to convert the relation to an array:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#mutator-methods-called-on-relation

This is already done in some commits here but it's not complete:
https://github.com/openfoodfoundation/openfoodnetwork/compare/rails-4-1?expand=1

**Comment by andresgutgon** [comment]
Hi @luisramos0 I'm a bit idiot and worked on this issue without realising you already had a PR open 🙈  Sorry for that. 

Any way I open PR because I think I walked all the places where mutator methods were used and I also fixed a couple of unrelated issues:

1. [A broken query in Rails 4.1.x](https://github.com/openfoodfoundation/openfoodnetwork/pull/6063#discussion_r491688453)
2. And this open issue [ActiveSupport::Concern::MultipleIncludedBlocks #6023
](https://github.com/openfoodfoundation/openfoodnetwork/issues/6023)

Feel free to close my PR or use whatever you think can be helpfult. 

Next time I'll filter [issues without assignee for Rails 4-1 epic](https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+%5BRails+4.1%5D) 😅

**Comment by andresgutgon** [comment]
Also note that my branch is pointing to `rails-4-1` branch. Not sure how you're working here. What's the idea make mergeable each issue into master or put everything on `rails-4-1`, do QA and merge into master that branch?

**Comment by luisramos0** [comment]
ah, I now see these message :+1: 
If possible we make rails 4.1 changes in master, if not possible we work on the rails 4.1 branch.
I think your PR is good for master.

I think the easiest way is for me to take over your PR yes, I'll get from it what's not in my PR and create a separate PR against master, ok? Thanks a lot for your contribution btw!

**Comment by luisramos0** [comment]
All broken specs are fixed here. Closing.
