### ISSUE TITLE
[Rails 4.1] Changes on default scopes

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5608]
The default scope works differently on rails 4.1 we need to investigate and see what's the impact on our code:
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#changes-on-default-scopes

**Comment by jeduardo824** [comment]
I searched through the code, and I think the only place we may have problems with that is on https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/variant_override.rb#L15 because the models contain other scopes. Other models using default_scope are using it only for sorting, and they don't have any other scopes declared inside them.

**Comment by luisramos0** [comment]
awesome, thanks!
We did get into some trouble lately with gem paranoia and whether deleted entries would be included in the default scope or not...

**Comment by luisramos0** [comment]
Closing in favor of the issue with the reference to some broken specs. Maybe related to this or not.
https://github.com/openfoodfoundation/openfoodnetwork/issues/5608
