### ISSUE TITLE
Products can't be added to Outgoing O/C (Aus Customer)

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5773]
## Description

Products can't be added to Order Cycle. When customer clicks on expand arrow to view Products in Outgoing Products tab of Order Cycle, this message appears:

_Loading.._

Expanded product list never loads. Products cannot be added to Order Cycle. 

## Expected Behavior

List of Products available to add to Outgoing should appear. 

## Actual Behaviour

Customer sees message:

_Loading.._

When logged in as Superadmin and viewing this Order Cycle, this error appears:

[missing %{num_of_variants_loaded} value] of 428 Variants Loaded

## Steps to Reproduce

1. Go to any Order Cycle for Baw Baw Food Hub (current order cycle closes 19 July 2020)
2. Go to Outgoing Tab
3. Click on Expand arrow in Products
4. Error (when logged in as Superadmin)
5. Loading... (when logged in as Manager of Enterprise)

## Animated Gif/Screenshot

![Screen Shot 2020-07-16 at 11 23 56 AM](https://user-images.githubusercontent.com/47620442/87617325-9c362680-c75a-11ea-9ffc-6007d666e837.png)

![Screen Shot 2020-07-16 at 11 36 18 AM](https://user-images.githubusercontent.com/47620442/87617340-a35d3480-c75a-11ea-930e-078693c6a7ea.png)

## Workaround
No workaround. Can't add products to Order Cycle (Order Cycle is currently open, but new products need to be added)

**Comment by luisramos0** [comment]
Maybe time to activate bugsnag JS on the backoffice...
If we had that, we would see the JS error on the user browser.

@emilyjeanrogers if you are doing user support and can replicate errors, it's useful if you can provide the data available in the browser dev tools. I managed to reproduce in this case and I can see this:
![image](https://user-images.githubusercontent.com/1640378/87680854-d660f180-c775-11ea-9b05-502f6e75eb13.png)

It's usually on the console tab or the network tab (like in this case) and then on the network tab, on the line with a non-green color.

Anyway, now we need to find out why this syntax error is poping up for this hub.

**Comment by luisramos0** [comment]
I can confirm this is a v3regression.

Something changed about the SQL that is generated here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/4e3502cce7c5a8c51115a218fca641de3e95bc05/app/services/exchange_products_renderer.rb#L48-L52

The problem only occurs if filter_visible is used in the supplied_products method.

I tried changing the OC settings to not filter on "coordinator only" and found that it's not working in v3 :see_no_evil: 
![image](https://user-images.githubusercontent.com/1640378/87687080-36a76180-c77d-11ea-9580-8be3b636e5a5.png)

This would have been the quick workaround for this issue because this bug only happens if the "coordinator inventory only" filter is not selected. So, this is issue only happens if the option on the left is selected.

This bug in the form (cant change the OC config) is very easy to fix but maybe even before a PR is created, as a quick workaround, we can change the value directly in the database so that the Hub can operate immediately?

**Comment by luisramos0** [comment]
This is also fairly easy to replicate with sample data. Just activate the OC setting "coordinator inventory only" and go to outgoing exchanges, it breaks for me with sample data (added Fred's Garlic to Fredo's Inventory and tried to sell it in an OC with the filter on).

**Comment by RachL** [comment]
@luisramos0 do we have automated tests for this? Or can they be added as part of the fix? I must admit that on my side I never test this option during release testing :(

**Comment by luisramos0** [comment]
Yeah, I have the code fix done in #5775 I need to write some tests now.

**Comment by luisramos0** [comment]
The PR is ready for review now.
@RachL we now have 2 simple auto tests that make sure:
1. no products are shown if this option is active and the coordinator's inventory is empty
2 that only a specific variant added to the coordinator's inventory will show in the exchanges if the option is active
