### ISSUE TITLE
Wrong translation key in payment method form

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5781]
## Description

When creating a new payment method, the translation for "name" in French picks up the wrong key and displays "Product/variant". This is highly annoying when onboarding users.

## Steps to Reproduce
1. As a manager, go to an enterprise payment method list
2. Edit a payment method or create a new one
3. See the wrong translation

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/87806277-e56ba080-c856-11ea-8695-1bd3676059a2.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.10
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
this is bug in transifex, translator missed the context but also name is not prouduit/variante :man_shrugging: 
https://www.transifex.com/open-food-foundation/open-food-network/translate/#fr/enyml/292060826?q=key%3Apayment_methods.form.name

and
https://www.transifex.com/open-food-foundation/open-food-network/translate/#fr/enyml/292060836?q=key%3Apayment_methods.index.name

this is new because these broken translations are now used since https://github.com/openfoodfoundation/openfoodnetwork/pull/5425

anyway, the fix is in transifex.

**Comment by RachL** [comment]
@luisramos0 I don't understand. Myriam translated this a year ago, specifically changing what she did 3 years before.  And when I've changed the user guide recently, the screenshot shows the correct translation... Are we sure nothing has changed in our keys? If I change in transifex it won't have an effect on the product form?

**Comment by luisramos0** [comment]
Sorry, Rachel it's not obvious to follow. Yes, there was a change in the keys in #5425 that caused these keys to be used now and thus causing the issue.
I am not sure where these keys were used 3 years ago so I cant understand why Myriam translated them as they are.
But I am sure that now they need to be adapted to fit this form and that they will not affect the product form (because of the context).

**Comment by RachL** [comment]
ok all clear thank you @luisramos0 ! I've changed in transifex so I'm closing here.
