### ISSUE TITLE
Images down on UK Prod

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#5861]
## Description

Shop logos and product images missing.
Across every shop I've checked so far.
Eg https://openfoodnetwork.org.uk/stroudco/shop#/shop

Probs AWS config related like all the other 'images missing' V3 issues.

## Expected Behavior

Images on products

## Actual Behaviour

No images on products

## Steps to Reproduce

1. Do a little dance
2. Make a little love
3. Get down tonight
4. Go to an OFN UK shop and be smacked by unusually brutalist desktop appearances.
5. Wonder if you'll ever find your groove again.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 3.2.1
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
Fixed now.
Thanks @luisramos0 

_Looks for her groove. Under the table. Behind the cushion. It can't have gone far._

**Comment by luisramos0** [comment]
Yeah, I think this was a re-occurrence of https://github.com/openfoodfoundation/openfoodnetwork/issues/5668
I just clicked the "use S3" checkbox and restarted the server. It's a problem with the upgrade itself (see 5668 for details), because we are on v3 everywhere, it wont happen again.
US is not using S3 so we are safe :+1:

**Comment by filipefurtad0** [comment]
| instance URL  |  server up? | uses AWS3? | images? |
|:-------------:|:------:|:------:|:------:|
app.katuma.org | yes| no | yes
csicsoka.org | no| ? | ?
openfoodnetwork.ie | yes| no | yes
openfoodnetwork.ca | yes| no | yes
openfoodnetwork.org.uk | yes| yes | ~no~ yes, now fixed
openfoodnetwork.de | yes | no | yes
openfoodnetwork.be | yes | yes, except logo? | yes, except logo (see below)
openfoodnetwork.net | yes | no | yes
coopcircuits.fr | yes| yes | yes
openfoodnetwork.org.au | yes| yes | yes
openfoodnetwork.org.nz | yes| no | yes

**BE-prod**:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/505f4579-f75f-4f4b-85c5-e1f42449a7a1)

Missing images seem to be the logo, only; the URL points to local storage instead of AWS3.


On UK-prod, images were fixed by running:
```

ActiveStorage::Blob.
      where(service_name: "amazon_public").
      where("content_type LIKE 'image/%'").
      update_all(service_name: "amazon")
```

Closing.

**Comment by Matt-Yorkley** [comment]
That's a temporary fix for now, but the latest release still hasn't been deployed successfully on various servers.

**Comment by lin-d-hop** [comment]
CLosing again as everything is looking good again :)
