### ISSUE TITLE
Customers: columns need to be sortable - nothing happening on click

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#589]
![image](https://cloud.githubusercontent.com/assets/2911176/7976983/994068aa-0ac7-11e5-94de-eb65db47e10f.png)

**Comment by oeoeaio** [comment]
From memory, this is a scoping issue. The sorting was working but then I moved the ColumnsCtrl (where the sorting parameters are stored) so that it only wrapped the columns header elements. That broke everything because the ngRepeat directive for listing customers no longer has access to the sorting parameters. 

I think if we just move the `predicate` and `reverse` parameters into an `$scope.sorting` object a higher scope (customersCtrl in this instance) that should pretty much fix the problem...

**Comment by kristinalim** [comment]
I am able to reproduce this bug, and would like to work on it. I have already gone through contribution guidelines, and will submit a PR within the day.
