### ISSUE TITLE
Standardize image settings (paperclip attachment styles) across instances

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#5911]
## Description
We use a 3rd party library called paperclip https://github.com/thoughtbot/paperclip

### Issue 1 - shopfront thumbnails dont fit placeholder
The thumbnails on the shopfront for all servers except AU and DE show images with 100x100px but the placeholder is clearly 112x112px:
![image](https://user-images.githubusercontent.com/1640378/90396932-ff371800-e08e-11ea-9c6a-6a9645e8b6e1.png)
This can be fixed by changing the default settings from 100x100 to 112x112 as done on AU and DE servers.

### Issue 2 - apparently, the setting # crops images incorrectly
To avoid a known issue with paperclip attachment styles that use # (https://mrfrosti.com/2015/04/28/dont-u?se-in-the-paperclip-gem/) we could move from # to > in all instances that are using # right now: UK, AU and DE. This will need thumbnails to be regenerated on these servers.

### Issue 3 - image files could be converted to a specific image format
To make files smaller we could force a file format like jpg on all images. This can be done with attachment styles like we do now in AU and DE:
{\"mini\":[\"48x48#\",\"jpg\"]...
All images would have to be migrated according to Maikel, I am not sure this is the same process as regenarate thumbnails.

### Current Settings
These is the current config for the 8 globally managed servers:

default (all servers except the ones listed below that have custom settings):
attachment_styles: "{\"mini\":[\"48x48>\",\"\"],\"small\":[\"100x100>\",\"\"],\"product\":[\"240x240>\",\"\"],\"large\":[\"600x600>\",\"\"]}"

UK (different from default in the use of # for mini and small)
\"mini\":[\"48x48#\",\"\"],\"small\":[\"100x100#\

DE and AU (different from default in the use of # for mini and small, in the small size 112px and in forcing file format JPG)
{\"mini\":[\"48x48#\",\"jpg\"],\"small\":[\"112x112#\",\"jpg\"],\"product\":[\"240x240>\",\"\"],\"large\":[\"600x600>\",\"jpg\"]}"

**Comment by luisramos0** [comment]
This can be a (kind of large) papercut enhancement, or, from issue 1 above, we can call this an S3 bug?
Feel free to change this classification :+1:

**Comment by Matt-Yorkley** [comment]
So maybe we go with the AU/DE settings and apply them to all? 

I would avoid converting all the filetypes (issue 3).

**Comment by luisramos0** [comment]
yes, we would use AU DE config in all servers.
in AU DE we have "jpg"] which is what converts everything to jpg. https://github.com/thoughtbot/paperclip#post-processing
would you keep the original file types as in the current default?

**Comment by Matt-Yorkley** [comment]
I'm just a bit worried about messing up images in production. We'll have to test it thoroughly.

**Comment by luisramos0** [comment]
yeah, it's also why I am not doing any of these things now.

**Comment by mkllnk** [comment]
I agree with issue 1 and 3 but I'm not sure about issue 2 with the cropping. And maybe we need some designer input here.

Cropping has the advantage of always filling in the space in the design. The downside is losing top and bottom edges if the original image isn't square. Depending on the picture, this may not be noticed or look really odd. So far, we haven't had any complaints about cropping in Australia.

Keeping the aspect ratio has the advantage of always showing the whole picture so that the picture will never have some content missing, writing cut in half or anything odd like that. But it may not fit the design.

If the picture is higher than wide, there is a bigger margin between the image and the product description. And if the product images are not consistent, the design will look inconsistent as well. We could compensate a little bit by allowing for more height in the design. Keeping the width consistent would be great but we can't allow infinite height.

If the picture is wider than high, there is a bit more padding under the picture towards the variants. I don't think that this will be a problem in the design. It would look better to have them all the same size but at least they will align vertically.

So apparently, someone made the decision in the past that cropping is better than inconsistent alignments. Do we still share the same opinion?

 I will post something on Slack

**Comment by mkllnk** [comment]
About conversion to jpg: I guess that it results in smaller files but we should test that and have some numbers. JPG is really good for photos with lots of colours but PNG is better with a small colour palette. So it depends on the images people upload.

**Comment by mkllnk** [comment]
Okay, I found that copying all images from production to my disk is too much effort right now. I found a few examples though were the PNG was 4 times bigger than the JPG. I think that it's safe to go with that.

**Comment by sigmundpetersen** [comment]
@luisramos0 was this closed by https://github.com/openfoodfoundation/ofn-install/issues/651 ?
Or should we disconnect and move it to another column?

**Comment by luisramos0** [comment]
it's still under discussion in #6014

**Comment by Matt-Yorkley** [comment]
Image settings are now standardised across all instances :+1:

**Comment by luisramos0** [comment]
from the original issue description.
Issue 1 is fixed yes :+1: 
Issue 2 - we keep using #, from what I understand because it's not too bad
Issue 3 - I dont think this is fixed, right? We still have a mix of image formats.

I just wanted to clarify it. Maybe we can leave it as is :+1: 

In terms of image styles, no styles in ofn-install, no styles on the admin UI, only the Image.rb model with:
```ruby
                      styles: { mini: "48x48#", small: "227x227#",
                                product: "240x240>", large: "600x600>" },
```
Simplicity :muscle:

**Comment by Matt-Yorkley** [comment]
Yep :+1:

The images look so much better with the `#` cropping setting! :heart_eyes: 

We could make an issue for part 3 and see how we want to prioritise it.

**Comment by luisramos0** [comment]
ok, thanks for confirming. I am not opening the jpg issue (issue 3). We have way too many important things to get done! :-)
