### ISSUE TITLE
[mobile ux] View cart makes the page content move to the right by a few pixels

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5916]
## Expected Behavior
When the cart opens, no matter which page you're on, the body content stays exactly where it is.

## Actual Behaviour
When the cart opens, no matter which page you're on, the body content moves to the right by a few pixels and then moves back to the original place. 

## Animated Gif/Screenshot
https://www.loom.com/share/8228c59980f842729bfcd754caa7f1e4

## Workaround
n/a

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

## Your Environment
This occurs on Mac + Chrome/Safari and Windows 10 + Chrome

**Comment by Erioldoesdesign** [comment]
I had a noodle to see if I could find a simple fix for this or at least guide someone with more FE dev skills to the right place: https://www.loom.com/share/50697c79fb224811b5b0894465bf3e25

**Comment by luisramos0** [comment]
Awesome @Erioldoesdesign I am going to play with that overflow property and create a PR :+1:

**Comment by luisramos0** [comment]
ok, @Erioldoesdesign I see that your suggestion makes the scroll bar stay there when the cart view opens. That's why this issue disappears.

I now see that this removal of the scroll bar was explicitly done by @Matt-Yorkley in a specific commit here: https://github.com/openfoodfoundation/openfoodnetwork/commit/a6edc1c97356fa564ae78e67cece576f7bde7fcb

If I revert this commit, when I open the cart, the scroll bar is there (the slight move doesnt happen) but I can scroll and the main page content moves up and down... not terrible but not ideal. Would this be acceptable? (it's all I have got right now)
![scroll](https://user-images.githubusercontent.com/1640378/95452623-712a3000-0961-11eb-8cf3-af4e90f114db.gif)

Other alternatives: we could show the scroll but disable it with some magic: https://stackoverflow.com/questions/8701754/just-disable-scroll-not-hide-it

I am leaving this for now, someone with better CSS skills than me may well fix this issue quickly.

**Comment by mkllnk** [comment]
Scrolling could actually be useful if I want to check for a product while the cart is open. @Erioldoesdesign What do you think? Is @luisramos0 change a good solution?

**Comment by Erioldoesdesign** [comment]
@mkllnk sorry for the delay on this! 

So the pop-out cart needs to be scrollable for the cases where shoppers have more items in their cart and users are not focussed on the 'main page' content when this cart is open so scrolling that main page is odd behaviour so sadly, the example that Luis gave reverting one of Matt's PR's doesn't help...

Looks like someone with the better CSS magic skills as Luis said would need to investigate. Not sure whether I know where to dig in the CSS for this kind of solution 🤔

**Comment by turinglabsorg** [comment]
i've solved the issue with this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6863

**Comment by guidoDutra** [comment]
Hello, can I be assigned to this as my first issue?

**Comment by Erioldoesdesign** [comment]
@guidoDutra you might want to ping @mkllnk @andrewpbrett @Matt-Yorkley or @sauloperez to see how progress the other contributors PR is and what might still be needed on it
