### ISSUE TITLE
Wrong tax amount per rate on invoices

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5986]
## Description

Invoices present currently a line with total tax amount, however this line does not show a correct number. Amount excluding tax and including tax are correct however.

## Steps to Reproduce

1. Go check an order, example in FR prod R028838087
2. Print the invoice and check the total tax amount here it is :

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/3369782a-ffc5-4595-b55e-56bec10e3287)

3. Go see `/admin/reports/sales_tax` for that particular order
4. See that the invoice is showing only the amount at 20% VAT and not the total amount like it says it is.

Another super weird example is order R214658240

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/16cc44aa-bd31-4200-abca-30615426ffed)

But total tax should be 7.73

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/9f502454-732e-4081-a376-3a6c71dfd01e)

## Workaround
None I'm afraid. But I wonder if the fix might not solve my breakdown need explained here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5881

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: 3.2.5
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by tschumilas** [comment]
It looks like OFN-CAN is accurately calculating tax,  and accurately showing it on invoices
![image](https://user-images.githubusercontent.com/13171778/92148531-b56a6380-edea-11ea-945e-74350375131c.png)

**Comment by RachL** [comment]
thank you @tschumilas that's interesting!

**Comment by tschumilas** [comment]
I wonder if it is just affecting one invoice template.  I can switch and look at the other template - but I want to wait until night so I don't mess up users.

**Comment by RachL** [comment]
@tschumilas don't bother I'm just seeing now that the report doesn't make sense either...

**Comment by Matt-Yorkley** [comment]
Looking at order R028838087, there are lots of line items with different Tax rates:

![Screenshot from 2020-09-12 14-45-04](https://user-images.githubusercontent.com/9029026/92996881-3cb48700-f50f-11ea-884c-d3004246c543.png)

It seems like that total displayed in the invoice is picking out the tax for one line item instead of totalling all of them (we can see the `0.37` there).

**Comment by Matt-Yorkley** [comment]
I think this bug was introduced fairly recently...

**Comment by RachL** [comment]
@Matt-Yorkley yes that would explain why users are only screaming now : we had lower traffic in July, and all the big hubs that are using VAT only started again recently and emailed us about the problem. Thanks for looking into it :)

**Comment by pacodelaluna** [comment]
@Matt-Yorkley Actually, I am understanding that there is one taxt adjustment line per order item line. I don't think the issue is the number of lines but really the calculation. The first item are beers for 2.21e with 20% tax, so it should be 0.442e tax, but the first tax adjustment line is showing 0.37e. I am trying to dig this up.
