### ISSUE TITLE
Subs failing to launch

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5991]
## Description

Error appearing in FR prod.

Hub ID : 173 (one of our first users...)

The OC that closed on August the 29th at 8pm closed without launching any subscription orders.

## Steps to Reproduce

💩 don't know

## Animated Gif/Screenshot

Nothing to share here

## Workaround

doing the orders manually

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.2.4
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): desktop

**Comment by luisramos0** [comment]
You must be referring to the OC that ends on the 26th of Aug.
The OC that ends on the 26th did not generate any orders.
The OC that starts on the 31st did generate the orders coreclty.

I can see they assigned the schedule just a few hours before the Order cycle opened:
![image](https://user-images.githubusercontent.com/1640378/92245763-b79cf280-eebc-11ea-8286-12d8bd052f80.png)
![image](https://user-images.githubusercontent.com/1640378/92247655-6c381380-eebf-11ea-8936-34b82c31416b.png)

There are no "proxy orders" for this OC, that means the problem is with sync_subscriptions, not in the subs jobs.
When an OC is saved or changed, the proxy orders are generated in this sync process.

For example, for one of these subs, id 57 in the logs I see:
[2020-08-23 17:45:46#11099]  INFO -- : Syncing Proxy Orders of subscription 57

This looks absolutely correct because it's the same time (mind the timezone) the schedule was added to the OC :-)

In this sync process the proxy orders were supposed to be generated. But they weren't.
The only instruction between the log entry I see on the logs and the INSERT statement is the code that verifies the OC open/close dates match the subscriptions being/end date. These dates currently match on the database.
We only have 7 days of history in bugsnag, so we dont know if there was one alert there. I dont see anything on that day on slack.
In the code that inserts the proxy orders I see:
query << " ON CONFLICT DO NOTHING"

I wonder if problems inserting the proxy orders are being swallowed by this...

So, we dont have papertrail for the Order Cycle but the OC updated_at date is from before the OC opened, so, it doesnt look like user error.
But I cant see what went wrong with inserting the proxy orders in the DB...

Quick way for another dev to have a look:
- this code [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/4fe24da3ecd3190dd9c7ed1996b7b3abf7c40fdb/engines/order_management/app/services/order_management/subscriptions/proxy_order_syncer.rb#L48) 
generated the log entry above but the DB is empty for the 23rd:
![image](https://user-images.githubusercontent.com/1640378/92251227-6b55b080-eec4-11ea-8376-9ec453d05f20.png)

I think that's all I can think of right now.

**Comment by luisramos0** [comment]
oh, I now see this as S3 in "all the things". Subs not generated have been S2s lately. That's why I started the investigation...
Anyway, I think this investigation was worth while now.

We can move to S3 and see if it happens again. Or we can keep on S2 and have another dev look at this. I vote for S2 at least for the conversation with another dev, we may get more hints about what is going on here.

**Comment by luisramos0** [comment]
@lbwright22 reported something similar in UK.

I investigated this a bit further by copying the UK database to my computer.
I am now thinking this is an existing but, it's nothing new.

Subs work with two jobs:
- placement job (runs in the start of the OC to create the customer orders)
- confirm job (runs in the end of the OC to confirm the customer orders and process payments)
But the placement job needs proxy orders created to work. A Proxy Order is the representation of one Subscription inside an Order Cycle.
I have talked about this before, I think the solution design is wrong here because these proxy orders are created based on users actions on the UI. This should be done by a job on the background like placement and confirm: I think this deserves a separate improvement issue. Basically we should **make ProxyOrderSyncer a job**, not something that is executed in specific parts of the app.

There are several points where we create proxy orders in the code:
- when the subscription is created/edited
- whenever there is a change in schedules, in the schedules modal in the OC list page
- whenever there is a change in the OC schedules in the OC edit page

I think the bug is that this sync will only happen if the OC is "not closed", which means if the orders_close_at of the OC is in the future.
**Could this be related to cloning OCs?**
Users will clone a past OC where the orders_closed_at date is in the past.
- If the user, on the OC edit page, changes the schedule of the cloned OC, the proxy orders will not be generated because the OC close date is in the past
- If the user, on the OC edit page, changes the dates of the cloned OC to be in the future, the proxy orders are not generated because there was no change in the schedules. I think this is the bug.

I think there will be a workaround:
- go to the OC edit page
- remove the schedule
- re-open the OC by changing the orders_close_at to a future date
- re-add the schedule
This will generate the proxy orders and make the placement job parse the subscriptions on the next run (can take 5 minutes).
If you then close the OC (change the orders_closed_at to a date in the past, the ConfirmJob will run and the payments will be processed.

**Comment by Matt-Yorkley** [comment]
So there are two parts to subscription orders being processed; creating proxy orders, and processing proxy orders. Creating proxy orders only happens while an OC is open, and processing proxy orders only happens when an OC closes. Is that right?

The issue is that cloning or changing an OC will not necessarily trigger the creation of new proxy orders for the new OC, or the cloned OC might not meet the criteria at the point it's cloned (because the close dates haven't been readjusted yet)? And the mechanics of proxy orders are opaque to the user.

I'm wondering if some UI improvements would help here. Am I right in thinking proxy orders are fairly invisible to an enterprise user until the OC closes? There's not a clear or easy way to "inspect" proxy orders that are currently attached to an OC, right?

**Comment by RachL** [comment]
@Matt-Yorkley 

> Am I right in thinking proxy orders are fairly invisible to an enterprise user until the OC closes? There's not a clear or easy way to "inspect" proxy orders that are currently attached to an OC, right?

When the OC starts, if you go to a subscription and you edit it, it "creates" the order. But I don't know if it confirms the order already or if it is still a proxy order. In that case, yes you don't see proxy orders anywhere on the UI.

So if I follow : the idea would be to show them somewhere, that way we could know in advance when they are not created?

**Comment by Matt-Yorkley** [comment]
>  the idea would be to show them somewhere

That's one option that might help a lot...

**Comment by Erioldoesdesign** [comment]
@Matt-Yorkley wanna talk through UI ideas sometime? I'd like to understand more about the problem that is arising for users here

**Comment by filipefurtad0** [comment]
Hi all,

Could not reproduce this bug so far. I am not sure to reproduce the scenario you describe @luisramos0 :

> Users will clone a past OC where the orders_closed_at date is in the past.

Cloning OCs does not copy the schedule nor the open/close dates into the cloned OC, so it should not play a role whether the clone comes from an open or a closed OC. This info needs to be added manually, after cloning so it seems unlikely (but possible) that the user introduces dates in the past.

So I am not entirely sure on the starting point, to go on and reproduce the bug with the steps:

>    If the user, on the OC edit page, changes the schedule of the cloned OC, the proxy orders will not be generated because the OC close date is in the past
>    If the user, on the OC edit page, changes the dates of the cloned OC to be in the future, the proxy orders are not generated because there was no change in the schedules.

I did not observe the bug by going around these test cases.

**Comment by luisramos0** [comment]
In delivery train meeting we decided to close this and take this to product curation process. There are two items here:
- UX review of the subscriptions list page - improve it so that users will know if orders are placed or not
- tech change - make the subs/orders sync process happen in a job instead of being triggered by user actions

**Comment by Erioldoesdesign** [comment]
I've added 'UX review of the subscriptions list page - improve it so that users will know if orders are placed or not' to our sort of ['rough list' of design tasks](https://www.notion.so/openfoodnetwork/80136d14907a43eabdfe653b4f1ff1d2?v=8024a87bff994e40b73cb9f65c59ffde&p=d806928ec3f94d70903b9a15efc1444b) pre-our pipe being set up.
