### ISSUE TITLE
Improve auto test coverage on order customer details

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6045]
### What we should change and why (this is tech debt)
We do have some functional tests in the admin order customer details page like [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/3a894a1cdb2f40098a025793a10aa44b7ab5ec4b/spec/features/admin/order_spec.rb#L132).
But mostly the page is not covered with tests:
- customer search by email
- country/state selector
- checkbox "use billing address" as the shipping address
- etc

### Context
This came up in https://github.com/openfoodfoundation/openfoodnetwork/pull/5976

### Impact and timeline
It's a risk but it's been this way for a while. Now that we brought all code from spree, it's more obvious.

**Comment by shen-sat** [comment]
Hi @luisramos0 👋 😄 I'm going to pick this issue up. Before I start work on it, because I've never worked on the "Customer Details" page before, I wanted to run my thoughts past you:

From what I understand The Customer Details page is chance for an admin to change the customer details for a given order. I'm assuming that when an admin enters this page, all the relevant fields should already be filled in (with a customer's details).

Therefore, a test for this page should test that an admin can successfully _change_ the customer details for this page. Does that sound correct?

If so, I will test the following happy path: 
- admin visits page
- admin changes the following customer details in Billing Address section:
    - email
    - first name
    - last name
    - street address
    - street address (cont'd)
    - city
    - zip
    - country
    - state
    - phone
- admin chekcs the box "use billing address" under Shipping Address section
- admin no longer sees customer details under Shipping Address section
- admin clicks Update button
- admin sees "Customer Details updated" flash message

What do you think? If the above happy path is correct I will begin writing the test 💪

**Comment by filipefurtad0** [comment]
Hey @shen-sat ,

This page is used to edit but also to create new orders from scratch.

So, some of the cases you describe are addressed in the example on line 192 - https://github.com/openfoodfoundation/openfoodnetwork/blob/3a894a1cdb2f40098a025793a10aa44b7ab5ec4b/spec/features/admin/order_spec.rb#L132

Here filling in of the fields is tested. But I think it would be good to have an assertion which covers that the values are correctly stored and/or are visible after clicking Update (line 226). What do you think?

Also, it would be good to add some assertions to make sure that:

- the "use billing address" checkbox copies the data and hides the shipping address form
- the address form updates the list of states if the country is changed to another country other than the country in which the instance is set (default)

Please feel free to drop a line if you need help, thanks for your effort on this :+1:

**Comment by shen-sat** [comment]
Hi @filipefurtad0 thank you for the clarifications! 🙏   

That all makes sense at a first glance - I'll get on with writing the tests and I'll let you know if I run into more questions :)

**Comment by shen-sat** [comment]
I haven't forgotten about this, apologies for being so slow to pick this up - life has been mad busy 🙃 If someone wants to pick it up then please do 👍🏾 Otherwise, I can start work on this in January 🎆
