### ISSUE TITLE
Weight fees calculated incorrectly for large quantities of small units

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6072]
## Description
The sample data includes a bunch of product variants that are sold by the gram. If I have a enterprise or shipping fee that is per weight ($1 per kg, for example), it calculates the fee for one gram to be $0.001 and rounds it down to $0, which is fine. However, if I put a quantity of 1000 in my cart, I'm now buying 1kg of this product and should be charged $1. The fee is rounded down on each individual quantity of the item, though, so it's a total fee of $0.

## Expected Behavior
Buying 1000 quantity of a 1g product variant should charge a fee based on 1kg of total weight.

## Actual Behaviour
Buying 1000 quantity of a 1g product variant charges $0 in fees.

## Steps to Reproduce

1. Set up an enterprise fee with a weight calculator of $1 per kg
2. Set up a product variant that is sold by the gram
3. Put 1000 quantity in your cart
4. Enterprise fee should be $1

## Animated Gif/Screenshot
<img width="986" alt="Screen Shot 2020-09-21 at 7 57 18 AM" src="https://user-images.githubusercontent.com/35588/93783031-1b732b00-fbe0-11ea-94d8-ea7bc9a11d57.png">
<img width="959" alt="Screen Shot 2020-09-21 at 7 58 04 AM" src="https://user-images.githubusercontent.com/35588/93783106-3180eb80-fbe0-11ea-997b-844242d535ca.png">

## Workaround
This is unlikely to be an issue for most people since they would probably just set the units to be something more sensible so that people aren't ordering 1000 quantity, but it would be nice to clean up so that we're doing the correct thing. 

## Severity

bug-s5: we can live with it, only a few users impacted

## Your Environment
Safari on macOS Catalina

**Comment by tschumilas** [comment]
I wish I could remember the case now,  but I came across this rounding problem elsewhere very recently. Same thing -  a fee showed up as $0 because the small value rounded out.  I can't for the life of me remember the case -  but it wasn't an enterprise fee calculated by weight.   But it WAS a fee calculation.   It makes me wonder if our rounding has broader implications?   Sorry for not being more clear - I'm going to try to remember the exact problem case.  (I know, I know -  I should do issues when I find these things.  Simply not enough time.)

**Comment by andrewpbrett** [comment]
Closing as dupe of https://github.com/openfoodfoundation/openfoodnetwork/issues/2522
