### ISSUE TITLE
Make OFN Footer in Order Confirmation Email less prominent

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#6102]
## Description

**- As a:** user / shopper I receive an Order Confirmation Email after placing an order. At the bottom of the email are contact details for two different organisations. a) The Producer I ordered from and b) OFN. I am confused about who to contact regarding my order and accidentally email OFN instead of the Producer.

This is the current Footer:

![Screen Shot 2020-09-29 at 3 51 25 PM](https://user-images.githubusercontent.com/47620442/94517814-11020280-026c-11eb-8a7b-4e03e4de5f65.png)

**- On page:** In the Footer of the Order Confirmation Email sent from the platform (eg orders@openfoodnetwork.org in Aus) when a customer places an order with an Enterprise on the Open Food Network

**- I want to be able to:** 

Clearly see contact details for the Producer and know how to contact them in relation to my order. Currently it is unclear which of the contact details I should use to contact the Producers.

Discussion about this Issue in Discourse: 
https://community.openfoodnetwork.org/t/ofn-footer-in-order-confirmation-email-is-confusing-to-shoppers/2045/9

See the above conversation for background to this proposal. It is proposed that the OFN Footer be updated to remove the coloured social media links, and instead contain only a single line of text and a linked URL as follows:

**Your shopping experience is powered by the Open Food Network** 

Below is a representation of the desired text and link display:

![Screen Shot 2020-09-29 at 4 04 32 PM](https://user-images.githubusercontent.com/47620442/94518978-87533480-026d-11eb-965f-650d0329ac62.png)

The text **Open Food Network** will link to a URL or email. This is set at instance level by:
- a new configuration option in Configuration/Content
- user selects email OR url
- they put the email or url that they want 

## Acceptance Criteria & Tests

As an OFN Shopper
1. As an OFN shopper, complete an order in an open shopfront
2. Go to your inbox and view the Order Confirmation Email 
3. Footer of Order Confirmation email no longer includes Connect with Us header or coloured buttons to Facebook, Twitter, Linkedin and Instagram. 
4. Footer of Order Confirmation email no longer includes Email us and OFN email address 
5. Footer of Order Confirmation email only includes a single line of text in a grey shaded box
6. Link in text is correct as per the configuration by the Instance Manager

As an Instance Manager
1. As an Instance Manager it is possible to edit the destination for the footer of the Order Confirmation Email.
2. In Configuration/Content, the Instance Manager will be able to select email OR URL 
3. In Configuration/Content, the Instance Manager will be able to enter an email or URL

**Comment by RachL** [comment]
I really wonder if it is feasible to put hello@openfoodnetwork.org. It means that shoppers all over the world may end up writing an email... Who is managing this email today?

**Comment by emilyjeanrogers** [comment]
In Aus we have an email address (hello@openfoodnetwork.org.au) already in the current footer of every order confirmation email. It is much more prominent than what is proposed. We get on average 3 - 5 emails every week from a shopper trying to make contact with the Producer - so that is the reason for this Issue being raised. I think by reducing the prominence and making it clear that it is not the email address for the Producer we would significantly reduce the incidence of these emails. 

That said - I'm leaning towards a web link, ideally the Instance 'About Page' URL rather than an email address.  

@luisramos0 has just noted the following in the Discourse thread
![Screen Shot 2020-11-06 at 12 08 48 PM](https://user-images.githubusercontent.com/47620442/98313932-0be16180-2029-11eb-99c7-96fce57b972b.png)
:

I don't know what the right URL would be for each instance. For Aus this would be https://about.openfoodnetwork.org.au/ @kirstenalarsen could you add your thoughts here on how to specify this?

**Comment by tschumilas** [comment]
I'm so excited about this.  Thanks for perservering and getting us here @emilyjeanrogers  - support team issue creator extraordinaire!

**Comment by jamalsia** [comment]
hi; I am also interested in knowing how to configure the footer (facebook, instagram,linkedin...), as emails will be sent to hello@openfoodnetwork.org.

**Comment by kirstenalarsen** [comment]
@emilyjeanrogers please fill in Acceptance Criteria & Tests - when this is done and someone is testing, how will they know it is done and we're happy to deploy?

**Comment by Erioldoesdesign** [comment]
If you have questions about wording/styling of user help text ping @Erioldoesdesign or @jaycmb to support through dev pipe :)

**Comment by emilyjeanrogers** [comment]
> @emilyjeanrogers please fill in Acceptance Criteria & Tests - when this is done and someone is testing, how will they know it is done and we're happy to deploy?

Done. I thought this might be a Dev thing.

**Comment by mkllnk** [comment]
I started working on this and made two decision so far:

### Affected emails

The issue talks about the order confirmation email but the same social footer is displayed in nine emails. I decided to leave the old version in emails to enterprise users and change it to the new version in shopper emails. I also left the old version in the sign-up confirmation because it may be that a new user is really excited and wants to follow on social media. There shouldn't be any support need at this point.

Keep old version:

- enterprise_mailer/manager_invitation
- enterprise_mailer/welcome
- spree/order_mailer/confirm_email_for_shop
- spree/user_mailer/signup_confirmation

Change to new version:

- spree/order_mailer/cancel_email
- spree/order_mailer/confirm_email_for_customer
- spree/user_mailer/confirmation_instructions
- subscription_mailer/confirmation_summary_email
- subscription_mailer/placement_summary_email

### Where does the link go to

The footer contact email is configurable in the backoffice. If it's set, I would link to that email. There's is an existing link to the local instance site in the footer already:
![Screenshot from 2021-01-15 11-47-42](https://user-images.githubusercontent.com/3524483/104666254-8c0dfc80-5727-11eb-9e00-d7494bebae87.png)

If the footer email is not configured then I would link to the global website. This is still churning in my head though because it's not consistent. They are two very different use cases.

1. I want to know more about OFN. The "powered by" line seems very apt here and going to the global website is exactly what I want.
2. I'm lost. Clicking on "Open Food Network" in the "powered by" line is clutching on straws and luckily it leads me to an email address where I can get help.

Since the people in scenario 1 are likely to know how to use a search engine, I think that it's more important to have another avenue for the lost people in scenario 2. But ideally, people contact the shop for help and the "powered by" line is just for the curious ones (and brand recognition). :shrug: 

I think I will cater for the lost people now and we can open another papercut to change it if needed. This is the quickest for now.
