### ISSUE TITLE
Price Discrepancy between amount paid and current order price

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#6107]
## Description

Order #R274237235 displaying as Unpaid in Enterprise's Orders page https://openfoodnetwork.org.uk/admin/orders and under the customer's account.

Amount paid at checkout (PayPal) was £12.94 
Total order value now is £13.04
No adjustments recorded between checkout and today.
The price discrepancy between order confirmation email (at time of checkout) and now is in the gammon steaks.

## Expected Behavior

Customer places order and pays full amount by PayPal.
Order has payment status : Paid.

## Actual Behaviour

Customer places order and pays full amount by PayPal.
at checkout:
![emailel](https://user-images.githubusercontent.com/45104035/94550013-f9fee880-024a-11eb-9481-2bb00c138cc3.jpg)
Order payment status : Balance Due £0.10
![orderel](https://user-images.githubusercontent.com/45104035/94550010-f9665200-024a-11eb-965b-212a5bedb4c3.jpg)

## Steps to Reproduce

Unable to reproduce.

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by luisramos0** [comment]
Hello, just looking at the screenshots I can see it's the transaction fee of the gammon.
From the email 2.97 - 2.60 = 0.37
From the order page: 2.60 + 0.47 = 3.07

**Comment by luisramos0** [comment]
Looking at the DB I can see someone changed the order. The order was placed on the 20th but the gammon line item updated_at is from 2020-09-24 14:50:59...

Ok, I looked around the DB, I notice we dont have edit trail for prices :-(
But I ended up finding the problem:
![image](https://user-images.githubusercontent.com/1640378/94566227-03e01600-0262-11eb-94ae-76cd3e5147fe.png)
The BOM was used to change the unit value from 300g to 310g.

Original order of 300g gammon with price 2.52 and fee 18% = 2.97
After BOM change, 310g of gammon instead of 300g, price goes to 2.60 * 18% = 3.07

I think I explained what happened, will close the issue. Please do reopen it if you think my explanation is not correct :+1:

**Comment by luisramos0** [comment]
this looked like an S2 to me as well, that's why I jumped on it :+1:
