### ISSUE TITLE
Fix calendar picker day selection

### ISSUE THREAD

**Issue by kabhotz** [openfoodfoundation/openfoodnetwork#6170]
**What? Why?**
In the Italian instance when a user open a cycle order the calendar picker doesn't show the correct date on the text box.
After choosing the day there are AA and GG instead 2020 and 12.

![screenshot_2020-10-12_at_22 52 56_720](https://user-images.githubusercontent.com/8977332/95969992-b9d56380-0e0f-11eb-95fe-5865c88c86f8.png)

**What should we test?**
Log in as enterprise user or super admin
Change your language to other than english
Go to the order cycles menu
Create a new order cycle or edit a current one
See the calendar dropdown
This dropdown also appears in the "reports" menu

**Comment by luisramos0** [comment]
this must be caused by this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/5995

**Comment by andresgutgon** [comment]
I can't reproduce in my local Docker dev env 
![image](https://user-images.githubusercontent.com/49499/96371055-43629980-1160-11eb-8283-9e31d750682d.png)

Must be something related with the italian instance but not sure how to reproduce :/

**Comment by andresgutgon** [comment]
Ok, for some reason I see all site in italian but not javascript translations.

What I see the error (Is my theory) comes from Ruby / SpreeI18n gem misconfiguration:
![image](https://user-images.githubusercontent.com/49499/96373181-064fd480-116b-11eb-8734-ef5429f8ca22.png)

**Comment by andresgutgon** [comment]
We're overriting italian locale 😅 
![image](https://user-images.githubusercontent.com/49499/96375338-c859ad00-1178-11eb-91d5-8bce9645af76.png)

**Comment by luisramos0** [comment]
As per discussion in the PR #6218 this problem is caused by translators that change the date format to something not valid, in this case aa-mm-gg where it should always be something with yy/mm/dd


This is happening in quite a few languages in transifex. The fix to this is to update the translation in transifex to use valid formats with yy mm dd. Same applies to the format key where entries like %Y and %m should always be used.

I think we should keep this issue open because we should eliminate the root cause: the root cause is the fact that we are mixing configurations with translations. These entries should not be translations but more configurations. I'd make this issue a request to move these entries from en.yml to some config file.

**Comment by andresgutgon** [comment]
To keep everything working the same way, with Rails locales system I would just move these copies to another `.yml` file:
```
locales/
  en.yml
  l18n_formats/
    en.yml
```
And exclude `i18n_format` from Transifex process

**Comment by luisramos0** [comment]
nice Andres, thanks a lot for that suggestion :ok_hand: 
We have a few more candidate translation keys for that already...

**Comment by lin-d-hop** [comment]
:boom:
