### ISSUE TITLE
[mobile ux] Text wrapping issue in the OC's ready for dropdown

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6196]
## Description

When visiting a shop that has only 1 ready for option, if the ready for field has a long text (requires wrapping onto 2 lines), the box does not wrap up like it should. We should wrap the text on the 2 lines.

## Expected Behavior

![image](https://user-images.githubusercontent.com/6525576/96245698-e2906100-0fa7-11eb-98b8-93f4dd0938de.png)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/6525576/96245757-f9cf4e80-0fa7-11eb-94c2-467099d2231f.png)

## Steps to Reproduce

1.  In `/admin/order_cycles`
2. Create an order cycle for a shop and insert "As per pick up point instructions (35)" in the "ready for" field
3. Go see the behavior on the open shop

## Workaround

No actual workaround, but it's shopfront facing, so not good.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.2.10
* Browser name and version: both latest Firefox and Chrome
* Operating System and version (desktop or mobile): Both

**Comment by Erioldoesdesign** [comment]
I did some CSS digging on this because it's good learning ✨ 

So I managed using chrome inspect and playing with the css to get the overflow to expand the field by adding a height:max content;

![Screenshot 2020-10-28 at 17 06 36](https://user-images.githubusercontent.com/11681324/97471677-df4e8b00-1940-11eb-97ba-ff82d62790b1.png)

But then as above, the 'ready for' section doesn't stretch 😭 


So I fixed that by using heigh: inherit (i think)
![Screenshot 2020-10-28 at 17 08 24](https://user-images.githubusercontent.com/11681324/97471680-e07fb800-1940-11eb-9a8d-593a17aa9048.png)

but then i wanted ready for to be vertically centred aligned. I used padding 10px to do that but if we're using flexbox i think there's more elegant ways to do it

![Screenshot 2020-10-28 at 17 12 12](https://user-images.githubusercontent.com/11681324/97471685-e1184e80-1940-11eb-8f48-5c641bafa0f5.png)


Someone with better FE/CSS knowledge should logical-check this but hopefully I've found what needs editing. 

Now if only I had an environment to branch and try doing the FE coding (some day! 😍 )

**Comment by jibees** [comment]
Hi! 
My first issue here, very proud! Please be tolerant ;)
I've managed to fix the issue (thanks a lot @Erioldoesdesign for your feedback, yes, I'm using `flex` ;)), it now work with one or two lines, but no three. When I tried to change the display of the Order Cycle, I wasn't able to put a string greater than 35 characters (due to html attribute `maxlength="35"`), so I guess it might not have any string on 3 lines.
Btw, here's the result: 
<img width="456" alt="Capture d’écran 2021-01-06 à 09 24 17" src="https://user-images.githubusercontent.com/296452/103746180-f70d5400-5000-11eb-86af-df508a2ea48a.png">

**Comment by Erioldoesdesign** [comment]
I missed this in my list of unread email notifications about issues 😭 great work @jibees and glad my strange code in Chrome-inspect was helpful 😄
