### ISSUE TITLE
Migrate Paperclip to ActiveStorage

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6347]
### What we should change and why (this is tech debt)
Our file attachments manager gem Paperclip (upload files to S3 for example) is deprecated in favor of ActiveStorage. ActiveStorage comes with rails 5. After we are on rails 5, we can migrate to ActiveStorage.

We think this will be an easy task.

### Context
Paperclip upgrades and rails upgrades

### Impact and timeline
This will move us away from deprecated dependencies.

**Comment by achauve** [comment]
Since it blocks gem updates and new gem addition, it's getting more urgent.

**Comment by achauve** [comment]
@openfoodfoundation/train-drivers-product-owners for information

**Comment by RachL** [comment]
let's go @achauve 🎉

**Comment by sigmundpetersen** [comment]
FYI there is also the ongoing effort in #8469 and #8470.
Maybe you could help eachother out 🙂

**Comment by mkllnk** [comment]
I'll keep my notes in this comment for now.

Previous PRs:

- #8469
- #8470
- #8576

Some resources:

https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md
https://gorails.com/episodes/migrate-from-paperclip-to-rails-active-storage
https://blog.codeminer42.com/migrating-from-paperclip-to-activestorage-b37ef187fb17/
https://medium.com/sortlist-engineering/migrating-from-paperclip-to-activestorage-a-different-approach-4bffa2260e17
https://www.fastruby.io/blog/upgrades/active-storage/gradually-migrate-from-paperclip.html

**Comment by mkllnk** [comment]
Just a little update: I made heaps of progress. I'm working on this branch: https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:active-storage

I have migration code and compatibility code so that we don't lose any images during the migration. Models, controllers, serializers and views have been updated to use the new ActiveStorage API.

### Outstanding work

- [ ] Rewrite the migration code to use already stored image files. I wrote the code to re-upload files because we need access to the files anyway to calculate a required checksum. But I now found that this method would take days to migrate all images. And Amazon S3 provides the checksum with a simple API call. So I want to query the checksum that way and leave the files where they are.
- [ ] Remove the compatibility code again. It's better to do that after the rewrite (previous point) so that I don't get merge conflicts.
