### ISSUE TITLE
Update to latest versions of rails and ruby

### ISSUE THREAD

**Issue by soilforlifeforms** [openfoodfoundation/openfoodnetwork#635]
I am interested to know why rails 3 and ruby 1.9 are still being used in this project. Would this be something the authors would be interested in pulling if I update the software?

**Comment by pmackay** [comment]
I think they're linked with the older version of Spree being used, and the reason Spree is not up-to-date is because its been quite heavily customised. 
If you plan to look at doing updates, best to get more details from @RohanM first :)

**Comment by RohanM** [comment]
I'd *love* to update Rails and Ruby to the latest versions. @pmackay has pretty much hit the nail on the head - the version of Spree we're using is incompatible with later versions of Rails, and although we've only made minimal changes to Spree itself (we have a fork, mostly with minor bug fixes and backported security updates), our code is coupled to some internal details of Spree which changed significantly from 1.3 to 2.0. This means that upgrading is a pretty significant task, and one that's hard to estimate. I'd be happy to accept a PR around this, but I'd recommend spending some time getting familiar with the system before attempting it, since it would require a strong knowledge of the internals. Let me know your thoughts, and keep in touch if you're having a shot at it.

**Comment by pmackay** [comment]
Another good reason to update - https://spreecommerce.com/blog/security-updates-2015-3-3. May not affect our current branch but keeping uptodate makes security patches easier to deploy.

**Comment by kirstenalarsen** [comment]
no shortage of reasons to update, it’s resources that’s the problem :)

**Comment by pmackay** [comment]
Now on Ruby 2 and Rohan working on Spree upgrade. Closing as this is general and its being handled elsewhere.
