### ISSUE TITLE
Missing translation "Tax Rates"

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6387]
## Description

The translation key for "Tax Rates" is missing.

## Steps to Reproduce

1. Log in as Superadmin
2. Click Configuration or navigate to /admin/general_settings/edit
3. Hover with the cursor over Tax rates. You can also choose another language other than English and go back to this page.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/ffb4ed6e-2c33-45dd-be50-255a99159d65)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.4.1
* Browser name and version: Firefox 82
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by bradkIsaacs** [comment]
I have reproduced the issue, but I also noticed that if you change the language to Spanish or Castellano (Spanish in Spanish), you still see tax rates instead of las tasas de impuestos
![Screenshot from 2020-11-18 09-00-40](https://user-images.githubusercontent.com/32146934/99554590-98224b80-297c-11eb-9f9b-ce1177f1aa0c.png)

**Comment by filipefurtad0** [comment]
Hi @bradkIsaacs - Welcome!
Yes, that's the bug. It should show the translation on the language in use, instead of displaying "Tax Rates" for all languages.

Do let us know, if you would like to work on this issue :+1:

**Comment by bradkIsaacs** [comment]
@filipefurtad0 yes, I would like to fix this bug. By happens chance  do you know the location of this ruby file is located? Would save me some time from searching for it. Also issue #6350 looks very similar and could probably be combined.

**Comment by filipefurtad0** [comment]
Great, thanks @bradkIsaacs ,
I've assigned you to this issue.

I think the file you need to change to address this issue is `config/locales/en.yml`.

To learn more on the process please see our wiki [page on translations](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29) and let us know if you have any questions.

Thanks for pointing out issue #6350 - it's indeed a duplicate.

**Comment by bradkIsaacs** [comment]
Running into some trouble.Focusing in on es.yml at line 2919: tax rate: "% Impuestos" change that to tax rate: "las tasas de impuestos". Still shows TAX RATES. 
![Screenshot from 2020-11-18 12-07-56](https://user-images.githubusercontent.com/32146934/99576215-ed6b5680-2996-11eb-8925-3f3ef6f0cd00.png)

**Comment by Matt-Yorkley** [comment]
The way our translations work is that we only update the English translation in the base file `en.yml` and all the other files are updated via an integration with an external service called Transifex.

**Comment by bradkIsaacs** [comment]
Working in en.yml change lines: 1069, 2251, and 3066 to read test, but still shows Tax Rates. English admin
![Screenshot from 2020-11-18 12-51-03](https://user-images.githubusercontent.com/32146934/99580659-f3fccc80-299c-11eb-9049-bd3233a5fbf2.png)

**Comment by Matt-Yorkley** [comment]
Did you restart the Rails server?

**Comment by bradkIsaacs** [comment]
@Matt-Yorkley Yes i restarted the server and got the same results every time.

**Comment by bradkIsaacs** [comment]
@filipefurtad0 I'm little confused on how fix the issue. According to @Matt-Yorkley only the en.yml file can be changed and tested locally and the remaining .yml files are updated via a third party Transifex. If you ask me sounds this is an issue for Transifex, I went ahead and looked the other .yml files at the line labeled "Tax Rate:" and all of them are correct, all but Spanish. So I'm confused on how to help when there's a mistake that seems to be unfixable locally?

**Comment by filipefurtad0** [comment]
Hi @bradkIsaacs ,

Yes, `en.yml` is the base file.

> and all of them are correct, all but Spanish.

This is affecting Spanish as well as other languages. You can check that, by adding locales to your `config/application.yml` file and visiting that page in other languages. See for example this [page](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Locale-and-sample-data) for details.

I'd say that you need to make sure that the `t` function is being correctly called for the relevant `app/views` page, and that it is correctly linked to an entry in `en.yml`. This entry, in turn, will be used for inserting the translation for that string, for all other languages. Again, more details on our wiki page on translations.

Hope that helps!

**Comment by bradkIsaacs** [comment]
@filipefurtad0 I don't think you understand the issue. es.yml is the only incorrect translation I have found:
ar.yml line 3011 Translation Correct
ca.yml line 2919 Translation Correct
de_De.yml line 2842 Translation Correct
**Skipped all en_*.yml files**
es.yml line 2919 Translation Incorrect
es_CO.yml line 2907 Translation Correct
es_CR.yml line 2856 Translation Correct
fil_PH.yml line 2681 Translation Correct
fr.yml line line 2944 Translation "By Tax Rate" Correct?
it.yml line 2891 Translation Correct
nb.yml line 2912 Translation "Fee Rates" Correct?
and since these .yml are made by transifex so I don't understand what I'm supposed to do.

**Comment by RachL** [comment]
hello @bradkIsaacs sorry for late answer here. All non-English translations are incorrect as they show "Tax rates" the default English version. This issue is therefore to add a translation key for that particular string which can then be picked up by Transifex. For more info on our translation process: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)

Hope this helps.
