### ISSUE TITLE
Error when trying to change an order

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#6392]
## Description

This bug has been reported by Bugsnag and I haven't verified it yet. But a server error is triggered when a shop allows the editing of complete orders and a user visits the shop. It was introduced by a recent change to fix the admin panel for Slavik languages.

## Expected Behavior

You can browse any shop and it notifies you if you have a complete order for the current order cycle that can be changed.

## Actual Behaviour

The code for the notification raises an error and I'm not sure if the user sees the snail or just doesn't see the notification.

## Steps to Reproduce

This is a guess so far:

1. Set up a shop which allows to change orders after completion.
2. Place an order for that shop.
3. Return to the shop front.

## Animated Gif/Screenshot

 
Todo.

## Workaround

Unknown.

## Severity

I'll assign S2 until an investigation shows that affected users can still shop.

## Your Environment

* Version used: v3.4.1-beta on au-prod

## Possible Fix

PR #6280 changed the translation file and apparently it's invalid even though it fixed another issue. The locale has to be valid in all languages for all supported plurals.

## Error in OpenFoodNetwork

**ActionView::Template::Error** in **shop#changeable_orders_alert**
translation data {:few=>"You have <a href='%{path}' target='_blank'>%{count} orders with %{shop}</a> currently open for review. You can make changes until %{oc_close}.", :many=>"You have <a href='%{path}' target='_blank'>%{count} orders with %{shop}</a> currently open for review. You can make changes until %{oc_close}.", :other=>"You have <a href='%{path}' target='_blank'>%{count} orders with %{shop}</a> currently open for review. You can make changes until %{oc_close}."} can not be used with :count => 1

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5fb35304edef780018513e42?event_id=5fb5fc760063ec492f7d0000&i=gh&m=ci)

## Stacktrace

    app/helpers/spree/orders_helper.rb:37 - shop_changeable_orders_alert_html
    app/views/shop/changeable_orders_alert.html.haml:1 - _app_views_shop_changeable_orders_alert_html_haml__2712048062995329904_47261193784120
    app/controllers/shop_controller.rb:25 - changeable_orders_alert

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5fb35304edef780018513e42?event_id=5fb5fc760063ec492f7d0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by Matt-Yorkley** [comment]
**Short version:**
`en_AU` needs those missing translations to be added in Transifex.

**Long version:** 
We first saw this bug come up in relation to the Russian locale in https://github.com/openfoodfoundation/openfoodnetwork/issues/6273. Apparently it's a known bug in the `i18n` gem. Normally if a translation is missing in a given locale, the system will use the key from the base language `en.yml` as a fallback. It's not great if you're using a non-engligh language, but it's essentially an error-handling mechanism. The `Pluralization` module in `i18n` does some slightly different things with how it applies translations, and essentially it doesn't work well with this fallback mechanism. So for these keys that are grouped under a parent key and used with numeric values, eg `one`, `few`, `many` etc, if a missing key is encountered it throws an error instead of sing the fallback in `en.yml`.

**Comment by mkllnk** [comment]
I just copied all untranslated strings from the source file in Transifex. So if you include the latest translations, this problem should be resolved. :crossed_fingers:

**Comment by andrewpbrett** [comment]
I moved this to Test Ready; it looks like we could link https://github.com/openfoodfoundation/openfoodnetwork/pull/6408/commits/54feb2f57d7e5952c9b9096973597141a6e33522#diff-f2cdbc174e9c79652b73e56581f15484bff54e892955edf57a6a5a8190fa4347R1751 as fixing it?

**Comment by mkllnk** [comment]
Good idea, I just linked the PR. But I don't think that the PR needs testing. We will just see if the problem disappears in production.

**Comment by mkllnk** [comment]
And maybe the new link will close this issue too early?

**Comment by Matt-Yorkley** [comment]
I included the latest translations before deploying on Tuesday... possibly fixed already? It needs a prod-test.

**Comment by mkllnk** [comment]
I checked Bugsnag and the last reported event was on Tuesday Nov 24th, 21:33:26 GMT+11. There have been no events since. Seems fixed. :heavy_check_mark:

**Comment by filipefurtad0** [comment]
It seems this is still observed:
- for fr_BE locale: (in production) -> 1. key 'one' is missing:
https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/61d42e718886860007083962?event_id=61d42e71008b9ee9ef4e0000&amp;i=sk&amp;m=nw

- for the `cy` locale: (in staging, will occur as well in production) -> 2. key 'two' is missing:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61d859632138360007deacd0?event_id=61d85963008b9405aacc0000&i=sk&m=nw

I've downgraded since these seem to occur not often. Should be fixed when these keys are translated.

**Comment by sigmundpetersen** [comment]
I think we can close this.
`cy` translation has been improved I think.
For `fr_BE` this has to be fixed in Transifex and is just a case of incomplete translations.
