### ISSUE TITLE
[Rails 4.2] Checkout issues

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6411]
## Description

Checkout seems broken, through both registered-user path:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fbd26c1476ed900173382fc?event_id=5fbd26c100651acc421b0000&i=sk&m=nw

And unregistered-user path:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fbd2765e202130017ba007e?event_id=5fbd27650064e7cc38680000&i=sk&m=nw

Orders and payment methods work well in the backoffice.

## Expected Behavior

Checkout page is accessible and works

## Actual Behaviour

Checkout page is broken.

## Steps to Reproduce

1. Log-in.
2. Visit a shop
3. Place items in the cart
4. Edit your cart or proceed directly to checkout -> Boom error 500

Reproducible as guest customer.

![r42_checkout_bug](https://user-images.githubusercontent.com/49817236/100156340-9dadf300-2ea0-11eb-8095-551b451bc1b6.gif)

**Comment by andrewpbrett** [comment]
I'm not positive that that commit will address it; I wasn't able to reproduce the error locally to confirm. But I think it's happening because we're doing `localize_number` on the `amount` attribute and so it overrides the getter/setter methods, making it not just a regular database column.

If that does in fact fix things, we might want to double check other places where that might be a problem; I looked through [this comparison](https://github.com/openfoodfoundation/openfoodnetwork/compare/rails-4-1) and didn't see any other places where we'd need to change it, but I could be wrong.

**Comment by filipefurtad0** [comment]
Awesome @andrewpbrett,
Your commit addresses this PR - /checkout page is now accessible through both logged- and guest- users. Checkout works as well.

As to:
> we might want to double check other places where that might be a problem;

Something to keep in mind...

I'll close this issue for now :+1:

**Comment by filipefurtad0** [comment]
Reopening as a reminder to add unit specs as discussed [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/6354#discussion_r530387818).

**Comment by RachL** [comment]
@filipefurtad0 can we open a separate issue for the specs? This s1 bugs does not exist anymore right?

**Comment by filipefurtad0** [comment]
Yes, thanks Rachel - created #6436 
Closing here.
