### ISSUE TITLE
Missing translation "Refund"

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6414]
## Description

The translation key for "Refund" is missing, when editing an order, in the Order Adjustments section.

## Steps to Reproduce

As far as I know, this bug is only seen, when a tax which is applied to a given zone and set to be included in the price. If a customer has a billing address outside this zone then this will turn up as a refunded amount, in adjustments.

1. As superadmin, set a tax for a given zone. Set it as included in the price.
2. As a customer place an order, but add a billing address not included in the zone set in step 1.
3. Log in as Admin.
4. Go to Orders, find the previously set order and click Edit 
5. The missing translation should be visible under Order Details -> Order Adjustments

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/100262357-ecf92f80-2f43-11eb-97ab-b9239ed407d3.png)

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.4.2
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by nelsonwenner** [comment]
Hello, can I be assigned to this as my first issue?

**Comment by sigmundpetersen** [comment]
Yes thank you @nelsonwenner, I have assigned you.
Welcome to OFN 🎉

**Comment by jibees** [comment]
@nelsonwenner feel free to check out our wiki about i18n: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)

**Comment by sinansonmez** [comment]
Hello @RachL. Can you assign this to me so I can start working on it?

**Comment by sinansonmez** [comment]
Dear @filipefurtad0 I tried to recreate this issue. 
1. Set a tax zone for North America (default tax zone is EU, second screenshot below)
<img width="1408" alt="Screen Shot 2021-09-12 at 14 45 05" src="https://user-images.githubusercontent.com/37421564/132988469-539f3b76-347f-4ffa-93a9-724d5a115b5d.png">

![Screen Shot 2021-09-12 at 14 57 11](https://user-images.githubusercontent.com/37421564/132988481-9df5278b-be79-4e96-a060-64b89d573c68.png)

2. Created an order for Australia (payment method is `Cash on collection`. I don't see the issue that you generated. 

![Screen Shot 2021-09-12 at 14 56 14](https://user-images.githubusercontent.com/37421564/132988543-cfc9fa3c-a938-4432-be52-3040e55629d3.png)

![Screen Shot 2021-09-12 at 14 56 37](https://user-images.githubusercontent.com/37421564/132988553-e6993533-d98c-4465-9d2c-1d1a43dc4662.png)

I thought, I don't see the issue because I selected `Cash on collection`. I gave another order with a fake card. Again no issue. Please let me know if I am missing sth. 

![Screen Shot 2021-09-12 at 15 18 35](https://user-images.githubusercontent.com/37421564/132989140-566bb004-bd62-4111-a342-c06c27a6fdfa.png)

**Comment by filipefurtad0** [comment]
Hi @sinansonmez ,
Thanks for the effort in reproducing this issue.

Can you confirm if the shop set to charge taxes? This can be found under `admin/enterprises/<enteprise_name>/edit#!/business_details`:
![image](https://user-images.githubusercontent.com/49817236/133075602-b0083232-8e3a-42ce-b83a-c5e384d88088.png)

**Comment by sinansonmez** [comment]
Thanks for the hint @filipefurtad0 The shop was not set to charge taxes. Then I updated the setting and created another order. I still don't see the issue
<img width="1170" alt="Screen Shot 2021-09-13 at 13 51 16" src="https://user-images.githubusercontent.com/37421564/133079052-53dd0156-743b-40ca-9a23-7c0afd2d27ad.png">

<img width="1440" alt="Screen Shot 2021-09-13 at 13 55 53" src="https://user-images.githubusercontent.com/37421564/133079235-9a3f203e-1118-4ed2-9dfd-2e759476eb12.png">

**Comment by filipefurtad0** [comment]
Thanks @sinansonmez .
What is the tax category associated with the products on the order?

**Comment by filipefurtad0** [comment]
Also, since you opted to make your customer checkout from Australia, you'll need to set the default Zone to "North America":

![image](https://user-images.githubusercontent.com/49817236/133099543-10240b85-9e16-4115-b0e0-8a85003c9cd2.png)

But I see this issue is not current anymore, it seems the translation key has been added in the meantime :+1: So it can be closed actually.

Sorry for all the work @sinansonmez ! Tax issues are tricky to set up. Please feel free to have a look on other issues on our board https://github.com/orgs/openfoodfoundation/projects/2

Closing.

**Comment by sinansonmez** [comment]
Thanks for the info @filipefurtad0   At least I was able to help to identify that the issue doesnt exist anymore and can be closed. Sure I will check other issues to support OFN
