### ISSUE TITLE
Lots of (apparently transient?) issues with UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#649]
I have now put most of the Stroudco producers onto the current order cycle - this is about 1000 products.  It now takes over 10 minutes (maybe more - i got bored waiting!) to load products when I first click on Stroudco as a shopper
![screenshot 2015-08-13 20 56 17](https://cloud.githubusercontent.com/assets/10517702/9260352/0e76fd00-41ff-11e5-8ca7-4a61a1026df8.png)

**Comment by pmackay** [comment]
I think this is going to be something @RohanM needs to review, in relation to the performance improvements he's been doing.

**Comment by NickWeir63** [comment]
Thanks Paul.  I have temporarily closed this order cycle because I don't want the UK people who are starting to look at OFN to see how slow this is.  I am happy for you guys to reopen the order cycle if this would help you to see how slow it is.  Thanks

**Comment by NickWeir63** [comment]
@paul following our chat on Friday, I have added all the Stroudco products to UK staging.  When I go to the shop the 'Loading products' wheel is only up for about a minute then the products load.  So it looks like there is something different about Production which is slowing down the loading process.  I have left all the products loaded into the Production database for now and left the order cycle closed so that people don't get to see the slow loading.  Let me know if you want me to reduce the number of products active in the Production order cycle.  Should we remove the Aus review label on this one for now?  Cheers Nick

**Comment by RohanM** [comment]
@pmackay What version of OFN are you running on staging and production? I've done some work on the product load speed, but there's still room for improvement. Let me know where you're up to and if it needs more work.

**Comment by pmackay** [comment]
@RohanM both staging and production are at v1.0. Should we be updating to anything more recent that will help? 

Any ideas why there could be differences between the two servers? They are the same spec I believe.

**Comment by NickWeir63** [comment]
I was working on another issue with @pmackay and found that when i reduced the number of products  in the Production order cycle to 425 the shop loaded in less than 2 minutes.  I then added back in the 184 Stroudco products (these are storecupboard items which we buy in bulk from a wholesaler and sell individually).  This brought the number of products up to 609.  This made a dramatic difference to loading times (i gave up after waiting 7 minutes).  

When I went back in to the order cycle to try delete Stroudco as a producer from the order cycle the order cycle 'loading' screen (see screenshot) hung for over 20 minutes
![screenshot 2015-08-24 13 59 39](https://cloud.githubusercontent.com/assets/10517702/9440640/9d022402-4a68-11e5-963e-ee30ef3ea9e6.png)

I also tried logging in as superadmin but get stuck at the same point trying to open the Stroudco order cycle.

The reason I was doing this test was to see if the slow loading problem was due to trying to load Stroudco as a producer into a Stroudco order cycle.  This is probably not the problem because the same 184 Stroudco products are loaded into the open order cycle on UK Staging and I have no problem accessing this order cycle on staging (which has a total of 821 products which open quickly on the shop.

However I am a bit stuck now because I can't get into this order cycle. Can anybody take Stroudco as a producer off the Stroudco order cycle on Production so that I can test adding in other producers to see if adding in other producers causes the same performance problems as adding in Stroudco products?

Thanks

**Comment by NickWeir63** [comment]
It seems that there are other problems with UK production (which are not happening on staging).  Here is an email from Karen
From: roots fruits and leaves [mailto:rootsfruitsandleaves@gmail.com] 
Sent: 26 August 2015 10:28
To: nick@openfoodnetwork.org.uk
Cc: mags@commongoodfood.org; Lynne Davis; Paul Mackay
Subject: Re: OFN
 
Hi Nick
 
I have now updated products, producers, images etc onto OFN to bring it up to date and managed yesterday to do some trial orders, however its still not working fully.  Here's a list of what is not working:
 
As a customer 
•	I could not 'log in' to place my order (when I pressed enter nothing happened after typing my email address and password) ... I had to sign is as a guest in order for my order to be processed
•	I did not receive a confirmation email, even though a message appeared on the screen to say my order had been successful
•	I could not see product images, just a thumbnail
As a hub manager
•	I could not amend the quantities of each product before I opened the order cycle
•	I could not see a photo of the products, just a thumbnail
•	Some products that I had not selected appeared for sale
•	I did not get an email to say a customer had placed an order
•	I set up a new order cycle to trial it again this morning, which I could not access via OFN although it was highlighted in green 

I hope you can help me with this.
 
Cheers, Karen

**Comment by NickWeir63** [comment]
@kirstenalarsen asked us to prioritise issues we would like Aus support with.  In the UK skype yesterday this was the top prioity.  Can you suggest why we are getting so many issues on UK production which are not happening on UK staging (both using version 1.0)?
thanks
N

**Comment by kirstenalarsen** [comment]
If they are not happening on staging then they are not problems with the code. I suspect that a number of the issues she’s pointing to are likely user errors - so good practice for your customer service ‘team' (?!) to work out what’s going on

If you guys look closely into them and can replicate them as actual errors (on either staging or production) then i suggest you raise a github issue for each clearly specified issue 

here’s a couple of hints for your investigations . . 

As a customer 
• I could not 'log in' to place my order (when I pressed enter nothing happened after typing my email address and password) ... I had to sign is as a guest in order for my order to be processed

i do have a suspicion that there is a slight bug here which occasionally requires you to click the button twice. I have never taken any notice of it because i assume that most people are not changing users as often as i am. If you investigate and confirm then log bug

• I did not receive a confirmation email, even though a message appeared on the screen to say my order had been successful

check that the order exists in the system, and check the email - possible typo in the email. If not then check your emails are working ok   

• I could not see product images, just a thumbnail

don’t know what she means. perhaps a problem with where images stored and not loading correctly in production?


As a hub manager

probably best to log in as her and see if you can understand what’s going on


• I could not amend the quantities of each product before I opened the order cycle
• I could not see a photo of the products, just a thumbnail
• Some products that I had not selected appeared for sale
• I did not get an email to say a customer had placed an order
• I set up a new order cycle to trial it again this morning, which I could not access via OFN although it was highlighted in green

**Comment by kirstenalarsen** [comment]
ok, now that I'm looking in github rather than responding to email i see that there is a base issue re. loading speed. Similar comment from me though - can someone investigate Nick's query and check if there is an actual tech problem e.g. has someone else logged in and explored? If is ok on staging and not on production then it's nothing that upgrading is going to fix, and maybe something to do with a setting somewhere (maybe around images if related to the other issues outlined above?). Also, I'd be curious as to whether it's something to do with the actual Stroudco producer . . the more fine-grained info you can get about what triggers this the better, but first someone needs to get the order cycle open again (i don't seem to have a working admin login to ofn uk atm)

**Comment by NickWeir63** [comment]
thanks Kirsten.  my admin login is nick@nickweir.co.uk password localfood1  the superadmin login is spree@example.com password spree123
@pmackay will be updating new ssl certs to the UK production server which will give us access past this screen which is showing at the moment
![screenshot 2015-09-02 11 45 00](https://cloud.githubusercontent.com/assets/10517702/9656381/d949072c-522f-11e5-8798-d9ac4e94975f.png)

**Comment by lin-d-hop** [comment]
I'm planning on looking through roots shoots and leaves issues on Monday to see how much is user error. 

However any help we can get on the load speeds would be super awesome... the load speed issue is def concerning me.

**Comment by NickWeir63** [comment]
I am less worried about load speed.  When I load all the stroudco products onto staging the shop loads within 2 minutes (slow but not desperate)

**Comment by pmackay** [comment]
Longer term its important to improve on the load speed. Lots of people would leave if a web page takes 2 minutes to load.

**Comment by lin-d-hop** [comment]
Oh I didn't realise staging was so much better now. Great!
2mins is manageable if we can implement paging...

**Comment by NickWeir63** [comment]
OK now with big thanks to @pmackay we have UK Production back up and running.  I have done some more testing and the shopfront loads within 2 minutes but I am still having problems opening the Stroudco order cycle - it hangs on this screen. Can anyone suggest why?  Thanks Nick
![screenshot 2015-08-24 13 59 39](https://cloud.githubusercontent.com/assets/10517702/9748279/9d218f12-567b-11e5-8028-d0c4b86ccebf.png)

**Comment by NickWeir63** [comment]
This morning I could access the order cycle perfectly - not sure if anyone has done anythign to make this happen - maybe @pmackay did the fix that Kirsten suggested yesterday?  Anyway, this is all looking good now.  I will leave this open until @aidandunsdon has tested the issues raised by Roots Fruits and Leaves, but i have taken off the critical label. 
Thanks

**Comment by NickWeir63** [comment]
Another problem which is specific to UK production (and does not happen on UK staging) is that I cannot load images to products - see github issue 643 in UK Current milestone
On UK production - cannot add new product images #643

**Comment by NickWeir63** [comment]
I have just logged in to the Roots Fruits and Leaves shopfront on production using their admin log in details and went through all the problems that they reported on 26th August (see above).  Apart from these 2:
1) I also could not get the system to send confirmation emails to either the hub or the shopper (I then tried putting in a Stroudco order and again - no confirmation emails) and 
2) the loss of images which I think is a separate issue -see 643)  
All the other issues that she reported above are resolved.  Has  anybody done anything to UK production that would have fixed all these things?
Strange!!

**Comment by lin-d-hop** [comment]
How certain are you that some were not user error?

WRT others, they'll be related to the deployment tweaks no doubt.

**Comment by NickWeir63** [comment]
Yes they could have been user error - I dont have enough info from Karen to know for sure.  However we still have this issue of not being able to upload images to products in production (although we can in UK staging).  I also tried to add images to the Roots Fruits and Leaves products on production and got the same grumpy cat.

**Comment by NickWeir63** [comment]
Also - UK production is not sending any emails (order confirmation, password reset, etc)

**Comment by NickWeir63** [comment]
I can now load product images to UK production - thanks @mkllnk I will leave this issue open until we have resolved the emailing problem

**Comment by RohanM** [comment]
@NickWeir63 Could you check emails? @mkllnk and I have done some work and it should be fixed now.

**Comment by NickWeir63** [comment]
@RohanM and @mkllnk Thanks for trying to sort this.  I have just tried submitting an order on UK production and resetting a password.  I didn't get any of the expected emails within 15 minutes - maybe they will take longer - I will check again in the morning.  In the meantime I have asked Sara (at Tamar Valley Food HUb) to try and see if she gets emails.

**Comment by RohanM** [comment]
Hi @NickWeir63. Looks like there was one detail I missed. Have another shot and see if it's up and running now.

**Comment by NickWeir63** [comment]
Hi @RohanM - YES!!!! it is working for me and I have just checked with Sara and she is receiving emails too - thanks very much!
Sara can now go ahead and set up her trial.
I will close this now - thanks to all involved
