### ISSUE TITLE
Error 500 (snail) when downloading tax rate reports

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6548]
## Description

Hub 922 in FR prod gets a snail when trying to download the tax rates report https://www.coopcircuits.fr/admin/reports/sales_tax?report_type=tax_rates

Then need that report from October the 27th to November the 23rd for their VAT declaration.

I think the culprit order is between 2020-11-18 23:00 and 2020-11-19 00:00

Can anyone have a look and help how to workaround this one?

Might be related to this bugsnag: https://app.bugsnag.com/open-food-france/coopcircuits/errors/5fd0ac47df0f450018de2896?filters[event.since][0]=30d&filters[error.status][0]=open

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: last one
* Browser name and version: both
* Operating System and version (desktop or mobile): desktop

**Comment by RachL** [comment]
UPDATE: Pau found the culprit order. It is R145644366

**Comment by sauloperez** [comment]
I just found the root cause. The order R145644366 (1651288) has no line items and, with reason, it makes the DB query blow up. Rails doesn't know how to turn https://github.com/openfoodfoundation/openfoodnetwork/blob/ebe71429db0738990d9b115[…]11305299993747b23/app/services/order_tax_adjustments_fetcher.rb into a SQL statement because it can't compare the adjustable_id column to an empty array. I'll post that in the issue.

This is what I did from a Rails console by following lib/open_food_network/sales_tax_report.rb's and app/services/order_tax_adjustments_fetcher.rb's code:

```rb
irb(main):001:0> q = { completed_at_gt: "2020-11-18 23:00", completed_at_lt: "2020-11-19 00:00", distributor_id_eq: 922 }
irb(main):002:0> user = Spree::User.find_by(email: "rachel.arnould+test@protonmail.com") 
irb(main):003:0> orders = Permissions::Order.new(user).editable_orders.complete.not_state(:canceled).search(q).result
irb(main):004:0> orders.count
=> 3    
irb(main):005:0> orders.each { |order| OrderTaxAdjustmentsFetcher.new(order).totals }
=> RuntimeError: unsupported: NilClass    
irb(main):006:0> OrderTaxAdjustmentsFetcher.new(orders.first).totals
=> RuntimeError: unsupported: NilClass
irb(main):013:0> fetcher = OrderTaxAdjustmentsFetcher.new(orders.first) 
irb(main):014:0> fetcher.send(:all).to_sql                                                                                      
=> RuntimeError: unsupported: NilClass
irb(main):004:0> order_adjustments = fetcher.send(:order_adjustments)
irb(main):006:0> Spree::Adjustment.with_tax.where(order_adjustments)
=> #<ActiveRecord::Relation []>
irb(main):008:0> line_item_adjustments = fetcher.send(:line_item_adjustments)
irb(main):009:0> line_item_adjustments.to_sql
=> RuntimeError: unsupported: NilClass
irb(main):010:0> order.line_item_ids
=> []                            
irb(main):011:0> order.line_items
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):014:0> Spree::Adjustment.arel_table[:adjustable_id].eq_any(order.line_item_ids).to_sql
=> RuntimeError: unsupported: NilClass
irb(main):017:0> Spree::Adjustment.arel_table[:adjustable_id].eq_any([]).to_sql
=> RuntimeError: unsupported: NilClass
```

Removing this pointless order should fix it. Then, the long term fix is forbid orders without line items at DB level (if possible) because it's something we don't support.

**Comment by sauloperez** [comment]
Order destroyed and according to @RachL it worked. She can get the report again.

**Comment by RachL** [comment]
YAY!!!! Thank you @sauloperez closing :) let's open an issue about the orders without line items part?
