### ISSUE TITLE
[Rails 5] Make db2fog work in rails 5 or find a replacement

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6669]
### What we should change and why (this is tech debt)
db2fog doesnt work in rails 5. 

### Context
See epic.

### Impact and timeline
Currently it's the blocker to start up the app in rails 5.
Try   DEPENDENCIES_NEXT=1 rails s

**Comment by luisramos0** [comment]
I wonder if this issue is still relevant: https://github.com/openfoodfoundation/openfoodnetwork/issues/3723

**Comment by mkllnk** [comment]
According to [Ruby Toolbox](https://www.ruby-toolbox.com/categories/backups) the [backup gem](https://github.com/backup/backup) is the clear winner to replace db2fog. They are looking for a new maintainer at the moment. It's far better maintained than db2fog though and due to a lack of alternatives I would imagine that someone will continue with it.
