### ISSUE TITLE
Order with wrong total amount

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6680]
## Description

Hub ID in FR prod: 173 (one of FR oldest user 🧙 )

Ok so here is the full story of bread in this order. For non French people `Pain de méteil - c-Pain de méteil moulé 800 g (1 pain 800 g)` is the bread product in this order. Buckle up:

- This is a hub where bread bakers were supposed to be on holiday this week. So when preparing their OC, they removed all bread products from the OC.

- The hub manager is also a shopper at the hub and has 3 subscriptions for it (bread, cheese, veggies)

- On January the 10th, at the opening of the cycle, the hub manager receives an email telling them that the order has been placed but that "unfortunately some products requested were not available" (so far so good: the bread was not in the cycle products and they have bread as a subscription in addition to vegetables and cheese)

- On January the 12th, they learn that the bakers have come back earlier from their holidays and that they will have plenty of bread, So they add the bread in the shop. 

- Now, for some reason that I haven't been able to reproduce yet they are telling me that the subscription never was updated (If I find out why, I will open another issue). So they manually created orders with bread inside.

- they have managed to end up with an order (# R110771347 ) that does not count bread and therefor has a wrong total. updating and re-calculating does not change anything. Why?

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/5ad4c569-154f-4ff8-9d1b-6ca5d4d9b00f)

I'm searching if there are other orders in that state.

## Steps to Reproduce
 No idea.

## Animated Gif/Screenshot
see above

## Workaround
they can re-do everything manually

## Severity
bug-s2: a non-critical feature is broken, no workaround

I'm putting s2 for quick investigation to understand if we have more logs to help me debug.

## Your Environment

* Version used: v3.5
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Both

## Possible Fix
 -

**Comment by Matt-Yorkley** [comment]
@RachL just for a bit of clarity; was the order in the screenshot:

a) generated by a Subscription
b) created manually via shopping/checkout
c) created manually via admin
d) some combination of partly created by a Subscription and then manually edited via admin afterwards

**Comment by RachL** [comment]
@Matt-Yorkley D. Cheese (Tomme de vache) and veggy box (panier de légumes) were created by a subscription and bread was added manually afterwards.
At least this is what the hub is claiming to have done 😓

**Comment by RachL** [comment]
@Matt-Yorkley I managed to get a screenshare with the hub tonight. Actually when they added bread, they created a second order... so forget my previous comment, my apologies.

It seems that when a subscription is launched and the product within the subs is not selected in the OC, there is still a line added to an order at 0. This is what the customer sees for this order in his account:

![image](https://user-images.githubusercontent.com/6525576/105226098-d2b48a00-5b5f-11eb-873c-6e92ade1d358.png)

So the line is really at 0 which seems to indicate that the order total is actually correct!

@openfoodfoundation/train-drivers-product-owners do you know if this how subs were designed? Ie when a product is not sold in an OC it still appears on the order with a quantity at 0?

It still does not explain why in the backend, the quantity is 1 though 🤯 :

![image](https://user-images.githubusercontent.com/6525576/105226294-1909e900-5b60-11eb-8679-5ac9e9de5de9.png)

**Comment by andrewpbrett** [comment]
This is actually similar to #6806. The difference between the backend (showing a quantity of 1) and the customer view (showing a quantity of 0) happens because on the backend, we look at `order.shipments` and then at the `manifest` for each of those shipments:

https://github.com/openfoodfoundation/openfoodnetwork/blob/90f5659e68310c428ebf137c563d2fc154707808/app/models/spree/shipment.rb#L171-L178

The `manifest` method doesn't look at the `quantity` field on the line items, it just counts how many line items there for each variant. 

As opposed to the customer view, which looks at each line item and displays that line item's `quantity`. 

I'm guessing that at some point, the line item for the méteil bread had its quantity changed to 0, but we didn't remove the inventory unit from the shipment/manifest, and we should have. 

Similar to #6806, I don't think there's anything we're doing that's obviously wrong, or recently changed that could be causing a widespread bug, so this is likely an edge case. If we continue to see these differences between shipment manifests, especially for standard orders (i.e. not subscriptions, not having changed availabilities of the products), we should take a further dive into it, but I'd recommend that we downgrade to S3, but keep it open for reference since it's still an unsolved Mystery.

**Comment by Matt-Yorkley** [comment]
> when a subscription is launched and the product within the subs is not selected in the OC, there is still a line added to an order at 0

That sounds like a case we could try to replicate. So a subscription is created then one of the items is removed from the order cycle...?

**Comment by andrewpbrett** [comment]
That's a good idea @Matt-Yorkley. I did the following:

- Create a subscription for an existing open order cycle that had the product (Garlic) available
- Remove the product from the order cycle
- Try to run the placement and confirmation jobs (`rake ofn:subs:test:repeat_placement_job` and `rake ofn:subs:test:force_confirmation_job`)

The result was that the order didn't get created from the proxy order in the first place. The subscription page shows the message `There are no open or upcoming order cycles for this product.`

In a real situation, the order in which these different things happen could be what's causing this - like if the order is created, but not confirmed, and the product is removed from the order cycle in between those two events. Still, I think we do the right thing in most cases and I'm not sure what could have resulted in the discrepancy here. 

@RachL have you seen any similar sounding reports since this first one? Are you okay if we downgrade for now until there is more information?

**Comment by RachL** [comment]
@andrewpbrett no further examples no. However i just reproduced it. :muscle:  I guess that you did a test only with one product, right?

I did a test with a subs containing several products (like in the example here).  In this case, the subscription does goes through. After the OC launched, I removed the item "test for subs" from the OC.The confirmation email wasn't received yet, so when I got it it looked like this:

![image](https://user-images.githubusercontent.com/6525576/109327118-441ae300-7858-11eb-8381-ee837e05e8e4.png)

Which is correct.

But in admin view the quantity is still at 1 (the order total is correct tough):

![image](https://user-images.githubusercontent.com/6525576/109326828-eeded180-7857-11eb-9f7e-69f9d819a698.png)

You can find the order on FR staging: https://staging.coopcircuits.fr/admin/orders/R228178474/edit

Customer view is correct though.
