### ISSUE TITLE
NoMethodError in admin/enterprise_groups#update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#675]
## Exception in OpenFoodNetwork

**NoMethodError** in **admin/enterprise_groups#update**
undefined method &#x60;update_attributes&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/55f91a59687e12feb8777de4?event_id=55f91acd474f2f3b3d49ffd7)
## Stacktrace

```
bundler/gems/spree-afcc23e489eb/core/app/controllers/spree/admin/resource_controller.rb:28 - update
gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4 - send_action
gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167 - process_action
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/55f91a59687e12feb8777de4?event_id=55f91acd474f2f3b3d49ffd7)

**Comment by mkllnk** [comment]
I can't reproduce this one. Maybe @sstead can try to break it again?

**Comment by sstead** [comment]
I think I just recreated it with the Jonai Farms group. 
So it's an old group, created before you had to write something in the description box. So there's no description. 

Go into edit the Jonai Farms group > change the name to Jonai Farmssssss and click update. Then it will highlight the Description box red. But don't write anything in it. Then change the name back to Jonai Farms and hit update, and you should get the cat.

Don't write anything in the description field. Otherwise you'll lose this test case. Once something is written in the description field, it can't be removed, and then you can't recreate the Grumpy Cat.

So maybe a fix is to just write something in all the description boxes and save it. Then no cat? I'm no developer though :P

**Comment by kirstenalarsen** [comment]
your solutions sounds perfect Sally - I say go for it :)

**Comment by sstead** [comment]
Ok, I've written something in all the description boxes of Australian groups, and any future groups will be forced to write something in their description boxes. But people in the UK, @lin-d-hop  and @NickWeir63  if you have any previously created groups, with nothing in the description box, you might encounter this Grump Cat. So perhaps write something in any empty description boxes to stop this occurring with you.

**Comment by NickWeir63** [comment]
thanks Sally

**Comment by myriamboure** [comment]
Closing as the issue seems to have been fixed.
