### ISSUE TITLE
Deployment of the release draft v3.5.7 failing

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#6828]
## Description

Deployment of the release draft #6818 is failing in staging-FR and -AU with errors, respectively:

staging-FR: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/459
staging-AU: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/298

Bugsnag reported:
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/6021138f7ebfc50017fa970f?event_id=6021138f00699cd2ad150000&i=sk&m=nw

Deployment worked for staging-UK. Did not test deploying in staging-ES.

## Steps to Reproduce

Send a deploy job from https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/2151 to staging-FR or -AU

**Comment by sauloperez** [comment]
The data migration included in the release failed due to an empty product. If this happened in staging, it'll surely happen in production due to the amount of data and weird combinations there. We'll need to take a look @andrewpbrett .

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/6021138f7ebfc50017fa970f?event_id=6021138f00699cd2ad150000&i=sk&m=nw has all the required context.

**Comment by sauloperez** [comment]
The root cause is:

```sql
SELECT COUNT(*)
FROM spree_variants
LEFT JOIN spree_products ON spree_products.id = spree_variants.product_id
WHERE spree_products.id IS NULL;
 count 
-------
    11
(1 row)
```

https://github.com/openfoodfoundation/openfoodnetwork/pull/6792 doesn't account for variants without product. So, we need to fix the migration and then, likely investigate why that happens and forbid it at the DB level. A variant without a product becomes useless and it'll only break features.

**Comment by sauloperez** [comment]
:see_no_evil: testing locally with an FR's staging dump it's also causing the following line to raise

https://github.com/openfoodfoundation/openfoodnetwork/blob/173cf9e536dd3c75bedc2faef1fc81c3b9cceae1/app/models/spree/variant.rb#L262
