### ISSUE TITLE
[Reports] Enterprise Fees w Tax By Producer

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#6844]
## Description

As a hub manager I want to be able to view report that includes a breakdown of fees including tax information by producer.

A mock of the report data in CSV form is available [here.](https://docs.google.com/spreadsheets/d/1JtrP9fhqEA5wdzvddf1Q3hGbEXvIqJv2HQ5yWrV1ZKg/edit#gid=0)

- _Enterprise_: The hub for which the correlating order was placed
- _Producer_: The producer that supplied the produce
- _Producer Tax Status_: Is the producer tax registered or not
- _Order cycle_: Identifier for the order cycle in which the order was placed
- _Name_: Enterprise fee name. Note that for this report to be maximally useful we are including the 'Produce' within this report. This is not technically an enterprise fee. It is essentially costs that do not map to fees on the order.
- _Type_: The fee type eg Admin, Packing. Note the 'Produce' fee can have type 'Line Items'
- _Owner_: The enterprise that allocated this fee to the produce
- _Tax Category_: Self explanatory. Note that some fees 'inherit' their tax category. Also the 'Produce' will have a mixed category.
- _Tax Rate_: Self explanatory. Will not be applicable for 'inherit' and 'produce' categories.
- _Total (tax excl)_:  Total cost without tax
- _Total (tax)_: Total amount of tax applied
- _Total (tax incl)_: Total including tax (eg sum of last two rows)

Note that after each Producer a row of totals will be displayed.

The report will need filters to ensure that relevant data can be accessed. Also [summarised here](https://docs.google.com/spreadsheets/d/1JtrP9fhqEA5wdzvddf1Q3hGbEXvIqJv2HQ5yWrV1ZKg/edit#gid=1948210413):

- _Date Range_ (Datepicker): Allows weekly/monthly/annual reporting
- _Distributor_ (Auto-fill text) Allows multi-enterprise hubs granularity
- _Producer_ (Auto-fill text) Filter to a specific producer for fee calculations
- _Order Cycle_ (Auto-fill text) Reporting by OC
- _Fee Name_ (Auto-fill text) Filter to only include specific fees eg for a specific delivery run
- _Fee Owner_ (Auto-fill text) Filter to select the Enterprise that should be collecting the fees (reconciliation)
- _Customer Email_ (Auto-fill text) Report can then be used for wholesale customers tax calculations
- _Download CSV_ (Checkbox) Search = Download when ticked

The report should be accessible via the UI via Reports -> Enterprise Fees Reports -> Enterprise Fees with Tax
https://community.openfoodnetwork.org/uploads/default/original/2X/7/78a043e39d6619ca3307d2bec50e934f53971bfb.png

## Acceptance Criteria & Tests

1. All fields described above are present and data matches the description
2. Report can be downloaded as a CSV
3. Report can be accessed via the UI
4. Report can be filtered on all fields mentioned above
5. Totals row show correctly summed total amounts
6. In the UI figures should be rounded to 2 decimal places. In the CSV figures should be rounded to 6 decimal places.
7. All fields are translatable

**Comment by dacook** [comment]
Hi @lin-d-hop (cdd @abdellani), I put together a proof of concept to show the "cost of produce" row as a "summary row" for order cycle, which makes the most sense to me and seems to work fine:
![Screen Shot 2023-03-20 at 5 10 15 pm](https://user-images.githubusercontent.com/4188088/226261205-0b877813-e0a2-4ed8-bf24-70f7b42fdf82.png)

This doesn't perfectly match the example spreadsheet however:
* It's at the bottom, not the top. I think I could fix this by adding another option to the reports framework, do you think it should?
* The totals aren't included in the "TOTALS" row. This seems possible to add, but I'm not sure if it should be. Would it be better for the row to be "TOTAL ENTERPRISE FEES" instead?

I'll push up my work-in-progress code to the branch, but it will need more work before it's ready to review.
It's important to note that this is a change to the reports framework, so I'd probably split the change into a separate PR first, then we can build this report using the new option.

**Comment by filipefurtad0** [comment]
Hey @dacook @abdellani ,

This is a big piece - thanks for this work everyone :muscle: 

There is a lot to unpack and verify here, I've tried to make the simplest possible check, to assert on what it delivers.

I've generated the new report, restricting it to include only one order only, so it's makes it easier to track down the totals. Below, I try to compare within the same image:

|Enterprise Fees w Tax By Producer | Enterprise Fee Summary | Order |
| --| --| --| 

![image](https://user-images.githubusercontent.com/49817236/231472463-8bda5bb0-a7bd-4317-bae2-633f2d66905f.png)

Observations:

1) the `Total incl. tax ($)` in the Enterprise Fees w Tax By Producer does not equal the order `total`, on the `order/edit` page -> it seems that the difference is because the new report is not including `Transaction Fees` (this corresponds to the 0.5 difference in values). However, we can see that Enterprise Fee Summary report does include Transaction fees (marked in green).

Should we have consistency in the values within these three outputs (the two reports and the values on the order)?

2) The information Tax Category, Tax Rate Name and Tax Rate is not displayed on the report, in the `Cost of produce`; the line item has - in this case - indeed a tax value associated, as we can see on the `order/edit` page - seen under Adjustments tab:

![image](https://user-images.githubusercontent.com/49817236/231478816-f776d2c8-24a8-4ced-b718-52e48ced3b1e.png)


I think these two points need to be addressed before releasing. What do you think?

PS: I have to say, I find the name of these reports somewhat misleading (Enterprise Fee Summary) as they include _both_ Enterprise Fees and Transaction fees... I've noticed this for the first time during this testing section.

**Comment by dacook** [comment]
Thanks @filipefurtad0 for pulling all this information together, I really appreciate a new perspective on this.

I think it makes perfect sense to include _all_ fees, to ensure the totals line up with the order total. Especially because the existing "Enterprise Fee Summary" report does already.

So really, we should remove "enterprise" from the report names (maybe there's a better way to name it, but I don't know..). Ie:
* Fees w Tax by Producer
* Fee Summary

**Comment by dacook** [comment]
@lin-d-hop can you confirm you're ok with adding payment fees to this report, for the sake of consistency and completeness as outlined above?

**Comment by abdellani** [comment]
@filipefurtad0 
Thanks a lot for your efforts :pray: 

I have the following comments:
1.
> The information Tax Category, Tax Rate Name and Tax Rate is not displayed on the report, in the Cost of produce; the line item has - in this case - indeed a tax value associated, as we can see on the order/edit page - seen under Adjustments tab:

The "Cost of Produce" may match multiple Tax Categories/Rate because this row groups different products.
if we list all the matched categories, it'll still not be possible to know the cost for every matched category.

2. Now, I'm wondering if we don't have a similar issue with the shipping fees.

**Comment by filipefurtad0** [comment]
Hey @dacook @abdellani ,

> "Cost of Produce" may match multiple Tax Categories/Rate because

Yes, indeed. I'm not what is the acceptance criteria would be in this case. In the given example we have a `Product` tax category, without any tax rate assigned:

![image](https://user-images.githubusercontent.com/49817236/232447867-d6b6ead3-8ab7-4842-b7dd-780ccd40ecaf.png)

@lin-d-hop , what do you think? Should all tax categories/rates (noting that it is possible to have more than a tax rate per category, too) be listed for each `Cost of Produce` line?

> I'm wondering if we don't have a similar issue with the shipping fees.

In theory, yes - a shipping fee may have a Tax Category which may comprise more than one Tax Rate (as mentioned above). But I think this would be an edge case.

**Comment by abdellani** [comment]
>> I'm wondering if we don't have a similar issue with the shipping fees.

>In theory, yes - a shipping fee may have a Tax Category which may comprise more than one Tax Rate (as mentioned above). But I think this would be an edge case.


@filipefurtad0  I was referring to this issue: 
> the Total incl. tax ($) in the Enterprise Fees w Tax By Producer does not equal the order total, on the order/edit page -> it seems that the difference is because the new report is not including Transaction Fees (this corresponds to the 0.5 difference in values). However, we can see that Enterprise Fee Summary report does include Transaction fees (marked in green).

Do we also need to include the shipping fees in the report too?
Sorry for the confusion.

**Comment by lin-d-hop** [comment]
Hi all,
Sorry to leave you all hanging without feedback for so long.

It feels like the crux of the confusion here is related to how these reports group line items.

The Enterprise Fees by producer report should be sorted and grouped by producer, not by order. This report is intended to view data that will be relevant between Producers and Sellers. This means that it won't include order level fees as an ideal. Realistically, users often apply fees to products and order cycles in ways that are not clear cut. However shipping and payment method fees are always applied as a relationship between sellers and shoppers. 

Enterprise fees BY PRODUCER is not intended to display all the order fees. This is intended to summarise the fees on products, which will aid in producer payments. 

In a real world example this report should group all the line items for a producer under the report filtering. So in the case that you have many producers and orders in an order cycle, and you have filtered to an order cycle, the report should return all the line items grouped by producer for that order cycle.

In a classic testing case in which you have 1 producer and 1 order and 1 order cycle, the results will be a little misleading as you would expect the total to match the order and it will not. However in the user world this will rarely be the case. So the resulting grouping by producer will not be misleading as you won't expect order level fees here. 

This is to contrast the Enterprise fees BY ORDER report. In this report the line items will be grouped per order. With an order level grouping we want the order totals to match exactly the order totals from other areas of the app. This means including all fees - shipping and payment method fees.

In neither report the Cost of Producer line will be able to show tax rates as this will be mixed. This is why we have also created the Tax Reports, that are intended to give the full breakdown of taxes on line items. The Enterprise fees reports focus on ... fees, separating these out fully so that fee totals can more easily be calculated for accounting purposes.

With regard to the naming of the report - yes within the OFN code Enteprise fees and Transaction fees are quite different. But Enterprise Fees is the collective term used for fees, at least in the UK. As this is translatable the default can be named whatever feels right and instances can change this in translation. I don't feel like Enterprise Fees is misleading but would be happy if others felt the need to change to 'Fees Reports' or 'Enterprise and Transaction Fees Reports'.

I'm sorry if this hasn't been clear. I feel like this has been discussed many times but with the changing team working on this issue I can appreciate if this wasn't clear enough in the issue descriptions.

Let me know if this clashes drastically with others understandings or if I've been unclear still or if this misunderstanding has created technical complications.
