### ISSUE TITLE
Spike: cleaning our google set-up vs switching completely to OSM

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6884]
## Description

The purpose of this spike is to assess how long does it take to:

A. Display gmaps our main map layer and reversing #6882

B. Switch our system to completely and only support Open Street Map

Option B will need to take into account:

- Previous Epic summarizing the technical work left here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5542
- Maybe this is interesting? https://github.com/openfoodfoundation/openfoodnetwork/issues/5078
- OSM can work with several geocoders
- Farms are often located on roads that do not exist yet on OSM, so the journey/experience for the user might be different on OSM vs the current one on Gmaps. An estimate of the time and tasks required is therefore needed by the design team.

## Acceptance Criteria & Tests

We should be able to take a decision base on the result of the spike. => To be details a bit more this is too vague

**Comment by RachL** [comment]
@mkllnk I wrote the issue quickly to unblock you, but there might be stuff missing sorry, not much brain left 😴

**Comment by mkllnk** [comment]
I'm now checking if going back to Google tiles is actually the easiest option. The change was introduced in daa5b00a2aa2851bc0a782bea854b3893087af63 (5 years ago) and doesn't look that huge. But maybe following changes made it more difficult to go back. I think it's the only quick way to fully comply with Google and not remove features.

**Comment by mkllnk** [comment]
I think I found the best solution now:

- Using Google Maps with OSM tiles is against the license. Removing the Google brand is not easy, may buy us time but still violates the license.
- It's much easier to display Google Maps tiles again because we are actually using Google Maps under the hood. I'll open a small PR this afternoon.
- There is a feature toggle in the admin dashboard to switch on OSM completely which works great but still needs a little work. That's the right way forward for the OSM feature. There is no need to mix OSM with Google. Cillian did a great job there.
