### ISSUE TITLE
[Rails 5.0] Unsupported rails environment for compass

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7034]
### What we should change and why (this is tech debt)

Warning displayed on the console, on Rails 5.0:
`Unsupported rails environment for compass`

### Context

After running a subscription placement job the warning appeared in the console, but the subscription is placed as usual - nothing seems to be breaking.

I guess this relates to the initializer `compass.rb` and the 'compass-rails' gem, but I have not found anything broken on the app...

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley and @luisramos0,

this seems to relate to [this commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/7c9024101b9ae22c3e34cea8a7a00eccab5d758c):

I've looked around and found no css- or image-related issues: is there anywhere on the app you feel should be tested, in respect to this error, specifically?

**Comment by Matt-Yorkley** [comment]
There were some issues initially that meant the CSS was not compiling at all. It required adjusting some gem versions, and it now seems to work fine, but with this deprecation warning. I think it'll be solved when we start updating the gems again afterwards, otherwise we can resolve it separately as a tech-debt issue :+1:

**Comment by Matt-Yorkley** [comment]
I think this might be closed by https://github.com/openfoodfoundation/openfoodnetwork/issues/7104 :+1:

**Comment by Matt-Yorkley** [comment]
Closed by #7104 :tada:
