### ISSUE TITLE
Overlapping formatting in Pause Subscription 'Are you Sure?' pop out

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7195]
## Description

Since release on 23/03/21

![pause pop out](https://user-images.githubusercontent.com/45104035/112297861-483af480-8c8e-11eb-8149-7d7634335fee.jpg)

## Steps to Reproduce

1. Visit Subscriptions
2. click the 'pause' button
3. Observe mis-aligned text and images in pop out warning window
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
one for @jibees?
Since it seems to be a rails 5 regression I've moved to dev ready.

**Comment by sauloperez** [comment]
I find it curious it involves a question mark. Perhaps the recent CSS changes for unit price are the root cause (and the awful lack of encapsulation in CSS :joy: ).

**Comment by jibees** [comment]
I've tested locally, and it seems to be ok:
<img width="665" alt="Capture d’écran 2021-03-25 à 09 41 59" src="https://user-images.githubusercontent.com/296452/112444554-75e77280-8d4e-11eb-9da1-5c922cbc0671.png">

This is probably due to your browser configuration maybe with a small width. @lbwright22 could you confirm you were on mobile? Or on device with small screen? I will try tofix this, but I first need to know about your configuration, just to be sure. Thanks! 🙏

**Comment by lbwright22** [comment]
Hi @jibees I get the same result today: it is on Edge on my laptop. The screen was minimised and then reset to full screen.
The over lapping question mark and text appears when full screen

**Comment by Matt-Yorkley** [comment]
If it was just after a deployment there's a chance it could just have been a temporary issue caused by browser caching...

**Comment by jibees** [comment]
As far as I understood, it happens when the popup is displayed on a small screen (and if you increase the screen size afterwards, the popup does not change size automatically since its size is computed just before it displays)
If I'm right, I think it's not a regression, and the severity is not as high.

**Comment by jibees** [comment]
Dear @openfoodfoundation/train-drivers-product-owners 
Could you please prioritize this one? 🙏

**Comment by lbwright22** [comment]
@jibees and @Matt-Yorkley I can't reproduce this error today.
I *think* the scenario was:
1. Edge browser, laptop
2. minimised screen to work with the subscriptions page
3. changed screen from minimised to full, did not refresh the page.
4. then clicked on 'pause' and pop up was overlapping.
As I said, it is not a biggie and not happening today.
