### ISSUE TITLE
GST not visible / obvious in shopfront - should we do something about this? [discuss]

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#725]
Raised by FC, how much of an issue is it? should we attempt to resolve?

**Comment by myriamboure** [comment]
That sounds good @kirstenalarsen , we would love the VAT to be shown in the price breadown. And further that, we should be able also to fill in a price without VAT, the VAT is actually not connected to the price product, it's really strange to fill in price with VAT;.. imagine tomorrow the country change the VAT rate (which happens sometimes) then we have to change alllll the prices, whereas if we would fill in the price of products without VAT and add the VAT on top of it, that would take 30 sec to change the VAT rate and apply to all... Also in BtoB we need to be able to show the products in the shop without VAT (as in BtoB the VAT is  neutral for the company).

**Comment by kirstenalarsen** [comment]
@myriamboure you don't put the prices in with vat, you choose whether the product should have tax attached or not, then it will be added or not so that tax rate changes already work as you describe. re. BtoB and option to show prices with or without tax, I'd see that more as wishlist - perhaps create a new tax wishlist page if there are features that you'd want considered in the future?

**Comment by myriamboure** [comment]
@kirstenalarsen I don't understand... I'm not sure that works like, that, or then there may be a problem with the internationalisation... Look at Nick answer here: http://community.openfoodnetwork.org/t/vat-included-excluded-from-price/361, he manage VAT by creating an entreprise fee... I'm not sure it is really a "best practice", especially I think that can be a problem in the exports, for entreprises to manage their VAT declaration, etc. I looked in the Spree documentation and it's written (https://guides.spreecommerce.com/user/configuring_taxes.html)  "Included in Price - Check this box if you have already added the cost of tax into the price of the items." So we tried with thicking the box and not thinking, there is not impact on the price in the shopfront... Actually what is done is explained here: http://community.openfoodnetwork.org/t/how-does-tax-work-vat-and-gst/64 in "What happens when an existing enterprise registers for GST?":
"- A hub that is not registered for GST is selling the cake.
- The hub sells the cake for $22 - there is no change to the price.
- The hub then registers for GST.
- The cake still sells for $22, **but now $2 of that is charged to the customer as GST**, and the hub keeps only $20 after tax."

So what I understand, and what we have experienced in our hub, is that we have to fill in the price including VAT, we precise which category of tax the product belong to, and then in the report and invoice the VAT included in this price is presented separately to indicate what is the VAT collected.
So we tried with thiking and not-thinking in the tax rate the box "Included in price", and there is no impact... I guess there is a bug somewhere here, no? Because that should have an impact, no?

Are we doing something wrong? Can you explain us how to do then?

**Comment by olivierkrener** [comment]
@kirstenalarsen, we can setup an enterprise to include GST and this will indeed allow us to put product prices without GST **BUT** then the price including GST will only be displayed at checkout time, not in the shopfront. Example: a cake sell $20 with GST 10%
1. Price in shopfront: $20
2. Price at check-out: $20 + $2 GST = $22
This is misleading for customers... all price in other shops are always shown GST included (in Europe at least)

@NickWeir63, I see from https://github.com/openfoodfoundation/openfoodnetwork/issues/773 that you are still struggling with GST. In http://community.openfoodnetwork.org/t/vat-included-excluded-from-price/361 you wrote you are setting GST via enterprise fees - are you still using this solution?

**Comment by NickWeir63** [comment]
yes

**Comment by myriamboure** [comment]
Ping @daniellemoorhead, I think Kirsten won't be really available in the coming weeks ;-)

**Comment by daniellemoorhead** [comment]
Will chat with @RohanM and @oeoeaio and @mkllnk about this tomorrow and get back to you :)

**Comment by myriamboure** [comment]
@daniellemoorhead and @oeoeaio (I see you seem to be working on this ;-))
Just a quick precision about our need:
- we need to be able to put products prices / fees without VAT and say which VAT rate should be applied, and this should be shown in the shopfront, ideally presented in the price graph with another line VAT summing up the VAT for the product and for each of the fees applied on the product.
- then on the basket page, order confirmation, invoice, after the total line, there is always a line saying "Including VAT: amount". If there are different VAT rates applied on different things, there should be one line per VAT rate "Including VAT Food 15%: x amount" then another line "Including VAT General 25%: x amount" (just as information for the client, because it's already in the line TOTAL that sums all the individual products of course). It's legally compulsory to write the VAT amount on the invoice.
I hope this is clear! Ask me if any question
@NickWeir63 is it the same need that you have for UK?

**Comment by oeoeaio** [comment]
Please continue this conversation at: http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487

**Comment by daniellemoorhead** [comment]
Please continue this conversation at: http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487

**Comment by oeoeaio** [comment]
@olivierkrener, @myriamboure 

I think we need to split this into a three separate tasks.
  1. Make tax visible in the shopfront (regardless of whether the tax rate is included-in-price or not), and show included tax in the price breakdown
  2. Show breakdown of aggregated tax of different rates changed on a order in the cart, summary, email, etc.
  3. Allow tax breakdown to be visible on individual line_items at later stages of the checkout (rather than an aggregated sum)

### Reasoning
For part 1, I think that on-the-fly calculation of the tax that needs to be applied to a product on the shopfront is something that we can piggy-back onto the infrastructure for calculation of discounts etc that we are proposing to build as part of the [Wholesale and Tagging](http://community.openfoodnetwork.org/t/wholesale-and-tagging/505/14?u=oeoeaio) work. There would still be a fair amount of additional work in extracting the current tax calculation logic into a reusable module, but I think this is achievable. My current estimate for the additional work required to implement this is around three - four days (bear in mind that this is AFTER infrastructure around on-the-fly adjustments to product prices in the shopfront have been built):
  * 1 day to extract existing logic around calculation of tax into a reusable module
  * 2 days to implement injection of taxation information into the shopfront, and alter the breakdown interface to expose this to the customer) 
  * 3 hours for testing


Part 2 should be relatively simple to implement. I estimate that we'd need about 1.5-2 days: 
  * 4 hours to spec and build a function to expose tax totals by tax rate
  * 3 hours to implement in the cart, summary and emails.
  * 3 hours for testing

Part 3 would require a fair amount of refactoring around how Spree currently handles storing information regarding tax charged on a line_item. Fortunately this has been significantly improved in recent versions of Spree, so I propose that a Spree upgrade is the best option for implementation of this feature. Obviously this is a significant task.

**Comment by daniellemoorhead** [comment]
@NickWeir63 thought it best to include you in on this. See Rob's comment above on a way forward.

**Comment by NickWeir63** [comment]
Thanks - looks good to me.  I will run it past Oliver (Stroudco manager) too

**Comment by NickWeir63** [comment]
Oliver says:
Two possible solutions would help me. Either

a) any sort of marker against a line that shows it's got VAT on it, or
b) something like the following:
Tax Analysis		
Tax rate	Total	Tax Included
20%	£45.00	£9.00
0%	£201.00	£0.00

**Comment by myriamboure** [comment]
Thanks @oeoeaio !
For us, in terms of priority, showing the VAT in the price breakdown is not the major issue (nice to have), the important is to be able to choose to display products with or without VAT, + your point 2 (aggregated sum for each VAT rate). For your point 3, I'm not sure, our obligation is on the invoice, show per item: the unit price with VAT (or without, but I guess it's better to adopt the BtoC standard here), the quantity, the VAT rate, amount total incl. VAT (or without, same as above), and below you have the aggregations. But I'm not sure we need a tax breakdown per item (we need to show the VAT rate, not the amount of tax for each item)

The only thing is, I'm afraid the solution you proposed here: http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487/14?u=myriamboure might cause an issue, as it will display two lines for each tax rate, as each tax rate would have two tax categories included/not included (which doesn't make sense)...

Ping @sigmundpetersen might worth checking for Norway.

**Comment by OliverUK** [comment]
Oliver from Stroudco here. I've given this some thought and at this stage the important thing for us is to know the total amount that has VAT and the total amount that does not.

**Comment by oeoeaio** [comment]
Thanks for that @OliverUK. Just trying to get a handle on your requirement to expose the component amounts of the order that attract a given tax rate (in addition to the tax charged on them). Is this a requirement for tax reporting to the end customer in the UK in general or is this an internal StroudCo requirement? If internal, just wondering if this information might be better exposed in some other way?

**Comment by OliverUK** [comment]
@oeoeaio Based on our current circumstances, you could actually leave it as is and I would simply calculate the total amount of VAT items backwards from the VAT amount included. I need that total amount for inputting invoices into Quickbooks. But our situation could soon change to something where we also need people to be able to see in the shop front if an items has VAT and whether or not that VAT is included in the price.

**Comment by sstead** [comment]
Current visibility of tax FYI...

In the shopfront (no visibility)
![image](https://cloud.githubusercontent.com/assets/10843056/16508273/c904a082-3f74-11e6-9e2c-1df098680961.png)

In the edit cart page (see total GST associated with order)
![image](https://cloud.githubusercontent.com/assets/10843056/16508283/e2438464-3f74-11e6-8034-f7443dc745ba.png)

In the checkout page (No visibility)
![image](https://cloud.githubusercontent.com/assets/10843056/16508299/03b82f82-3f75-11e6-8df7-31d52a1049b5.png)

In the order confirmation page (see total GST associated with order)
![image](https://cloud.githubusercontent.com/assets/10843056/16508312/19651192-3f75-11e6-8168-8589940c8ee2.png)

**Comment by myriamboure** [comment]
Just a question: if various tax rates are applied to different products in the shopfront (for example 5,5% for food and 20% for handcraft soap sold in the hub as well), will it appear as one tax line per tax rate/tax category? Or just like in Sally's example, one line for all taxes? In the invoices in France, it's a legal requirement to have the amount of t... (only in invoices, but probably great in order confirmation as well) but I guess if no one else need it we'll find some budget to have this customized for France ;)

**Comment by daniellemoorhead** [comment]
@oeoeaio or @sstead are you able to help @myriamboure with her question?

**Comment by sstead** [comment]
Hi @myriamboure I just did some testing on our staging server and it looks like the two tax rates are joined into one figure in the checkout and in the order confirmation. The sales tax report also joins the two taxes into one figure which is not ideal for you in France.

**Comment by myriamboure** [comment]
Ok, thanks for the precision @sstead. I will add that to the list of the things we need to fund for France then. Cheers!

**Comment by lin-d-hop** [comment]
#gitcull2017
Captured in and linked from http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487
