### ISSUE TITLE
'Saving' information without scrolling - products page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#727]
"I am editing product names, etc. and thought it would be great to have another "saving" next to the bottom "save changes" button when saving. Otherwise I find I have to scroll back to the top to see if saving has finished. 

@oeoeaio has introduced some new code to handle similar issues to this on the bulk order management page (or new variant overrides?), which could probably be also applied into the products page

**Comment by oeoeaio** [comment]
Easy!
On Tue, Dec 8, 2015 at 15:00, openfoodfoundation/openfoodnetwork
<reply@reply.github.com>
wrote:
"I am editing product names, etc. and thought it would be great to have another
"saving" next to the bottom "save changes" button when saving. Otherwise I find
I have to scroll back to the top to see if saving has finished.

@oeoeaio [https://github.com/oeoeaio] has introduced some new code to handle similar issues to this on the bulk order
management page (or new variant overrides?), which could probably be also
applied into the products page

—
Reply to this email directly or view it on GitHub
[https://github.com/openfoodfoundation/openfoodnetwork/issues/727] .[https://github.com/notifications/beacon/AB-Nk94Oc38b9WtJeilPC34ksMl6q35Tks5pNk15gaJpZM4Gwt8j.gif]

**Comment by kirstenalarsen** [comment]
@oeoeaio - could you just put a couple of pointers here to that code in case someone at hackathon wants to pick it up, and/or is it actually in your branch that we haven't yet pushed to master?

**Comment by oeoeaio** [comment]
This is implemented in the bulk order management page which is in master now.

**Comment by elf-pavlik** [comment]
I understand we should have possibility to reuse [saveBar](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/index_utils/directives/save_bar.js.coffee)

**Comment by oeoeaio** [comment]
@elf-pavlik yes, that should be easy to do.

**Comment by RachL** [comment]
This has been done as well. So closing it 🎉 

![image](https://user-images.githubusercontent.com/6525576/55335189-f5f9db00-549a-11e9-81b4-4780f6f69c08.png)
