### ISSUE TITLE
Second StripeSCA payment method cannot take backoffice payments

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#7278]
## Description

A UI issue when a hub has two StripeSCA payment methods and needs to be able to use both in the backoffice.

Only one StripeSCA payment method will display the fields for entering card details in the backoffice. The second one will simply not display the fields for entering details.

## Expected Behavior

Every payment method should allow details to be entered to enable use of the payment method in the backoffice

## Actual Behaviour

A second StripeSCA payment method will not allow card details to be entered. Fields are not displayed.

## Steps to Reproduce

1. Create two StripeSCA payment methods
2. Go to the backoffice and to take a payment
3. See the first StripeSCA payment method allows you to enter card details
4. See the second StripeSCA payment method will not

## Animated Gif/Screenshot

![Screenshot from 2021-03-30 08-24-18](https://user-images.githubusercontent.com/8669848/112954531-609b8b00-9136-11eb-89d5-3a999be24bbc.png)

## Workaround

Hide the first payment method to use the second payment method.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 3.6.1 but existed long before.
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by apricot12** [comment]
So I've taken a look at this. It looks like to have multiple stripe payment methods for the same Enterprise, we'll have to move the forms for card input into a separate page upon choosing the payment method. This is because the card details form is mounted onto the `#card-element` ID. As seen here:
```
angular.module('admin.payments').directive "stripeElements", ($injector, AdminStripeElements) ->
  restrict: 'E'
  template: "<label for='card-element'>\
             <div id='card-element'></div>\
             <div id='card-errors' class='error'></div>\
             </label>"

  link: (scope, elem, attr)->
    if $injector.has('stripeObject')
      stripe = $injector.get('stripeObject')

      card = stripe.elements().create 'card',
        hidePostalCode: false
        style:
          base:
            fontFamily: "Roboto, Arial, sans-serif"
            fontSize: '16px'
            color: '#5c5c5c'
            '::placeholder':
              color: '#6c6c6c'
      card.mount('#card-element')
```
[Stripe JS SDK doc about element.mount](https://stripe.com/docs/js/element/the_element_container)

The problem here is that both of our stripe payment methods will have the exact same ID and so it will just automatically mount on to the first one. 

Now this is my understanding of the matter. Maybe @jibees can provide more insight into the matter?

**Comment by apricot12** [comment]
OH! I didnt realize that JB already made a PR for this.

**Comment by jibees** [comment]
@apricot12 
Good catch ;) You can review now my PR: #8487 🙏
