### ISSUE TITLE
remove unused git branches

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/openfoodnetwork#739]
```
$ git branch -a | grep upstream | wc -l
87
```

not the most exciting task to delete those all those unused git branches, but with more people trying to contribute it could reduce some unnecessary noise

**Comment by pmackay** [comment]
@mkllnk @oeoeaio something you could help with?

**Comment by mkllnk** [comment]
We tried to cull a lot already. We probably should have another go. Rohan just told me on Friday that they used to tag some old branches with the name `archive/old-branch-name` in case someone still needs it. What do you think of that?

I think that @RohanM should make the final decision on the older branches because he has been in the project the longest. Maybe we can compile a list of branches to delete?

**Comment by pmackay** [comment]
What’s the need to keep branches around for a long time? Is it beneficial after a feature has been merged? Helps to understand how the Aus team prefers to manage them :)

**Comment by oeoeaio** [comment]
From my understanding, most old branches that are kept are features that we started working on and haven't gotten around to finishing yet. I have moved any old branches that I care about out into my own fork, so I personally don't care about any branches in the main repository that aren't under active development.

**Comment by mkllnk** [comment]
That's a really good idea. I moved three of my branches to my own fork. But there are still 27 stale branches. I split them up by author of last commit. @RohanM What do you think how to proceed?

```
- `spree-2.0` Updated 3 years ago by dacook
- `report-column-toggling` Updated 2 years ago by dacook

- `prod-sep-2013` Updated 2 years ago by RohanM
- `caching_ams` Updated 2 years ago by RohanM
- `checkout-spec-reliability` Updated a year ago by RohanM
- `registration-spec-fix` Updated a year ago by RohanM
- `tagged-variants` Updated a year ago by RohanM
- `fix-line-item-fractional-cents` Updated a year ago by RohanM
- `Matt-Yorkley-reports_vat` Updated a year ago by RohanM
- `spree2` Updated a year ago by RohanM
- `tax-frontend` Updated 10 months ago by RohanM
- `postgres-referential-integrity-patch` Updated 9 months ago by RohanM
- `angular-1-2-26` Updated 9 months ago by RohanM
- `combined/ginerr-and-variable-weights` Updated 9 months ago by RohanM 
- `remove-product-distributions` Updated 7 months ago by RohanM
- `uk/packing-reports-uk2` Updated 6 months ago by RohanM

- `filtering` Updated 2 years ago by willrjmarshall

- `postcode` Updated 2 years ago by rafaqz
- `order_fix` Updated a year ago by rafaqz

- `modal-scroll` Updated a year ago by oeoeaio

- `userbalancecalculator` Updated a year ago by Lynne Davis

- `test-merging-master` Updated 9 months ago by Continuous Integration
- `ng-cloak` Updated 8 months ago by Continuous Integration
- `combined/folklabs-producer-emails_lin-d-hop-packing-reports-uk-cherry` Updated 7 months ago by Continuous Integration

- `indicate-required-fields-for-new-enterprise-form` Updated 8 months ago by Liv Galendez

- `uk/642-uk-buildkite` Updated 6 months ago by pmackay

- `feature/ofn` Updated 6 months ago by datashaman
```

**Comment by elf-pavlik** [comment]
> I have moved any old branches that I care about out into my own fork, so I personally don't care about any branches in the main repository that aren't under active development. 

:+1: 

> I moved three of my branches to my own fork.

:+1: 

Maybe someone could make a dedicated junkyard / graveyard fork, even on bitbucket or gitlab and just link to it from read me? This would allow to safely remove all the branches from this repo, except those that core team says "yes! we really need it this branch here".

**Comment by mkllnk** [comment]
I created another repository [openfoodnetwork-archive](https://github.com/openfoodfoundation/openfoodnetwork-archive/branches) with a copy of the repository with all old branches. I then went through the stale branches and deleted stuff that is older than a year. A lot of these branches were of people that are not even in the team any more. But I also deleted a couple of @RohanM's branches. I hope that was okay? They are not lost.

```sh
git fetch -p
# x [deleted]         (none)     -> origin/build-pipeline-test
# x [deleted]         (none)     -> origin/caching_ams
# x [deleted]         (none)     -> origin/checkout-spec-reliability
# x [deleted]         (none)     -> origin/filtering
# x [deleted]         (none)     -> origin/i18n_fr
# x [deleted]         (none)     -> origin/modal-scroll
# x [deleted]         (none)     -> origin/order_fix
# x [deleted]         (none)     -> origin/postcode
# x [deleted]         (none)     -> origin/prod-sep-2013
# x [deleted]         (none)     -> origin/registration-spec-fix
# x [deleted]         (none)     -> origin/report-column-toggling
# x [deleted]         (none)     -> origin/rm-enterprise-rabl
# x [deleted]         (none)     -> origin/spree-2.0
# x [deleted]         (none)     -> origin/test-merging-master
# x [deleted]         (none)     -> origin/uk/filter-producers-for-map
# x [deleted]         (none)     -> origin/uk/i18n
git branch -a |grep origin |wc -l
# 35
```

That should be alright. I have around three active branches all the time. With the UK and other contributors, we have maybe ten people with a few branches each.

I'm using my own fork more and more. All early work and experiments are on my own fork. I push branches to the main repository only once they are ready to review and test. We might switch to a model in which we create pull requests from our forks and don't need to keep any branches within the main project.

@elf-pavlik Do you think this issue is solved? Or do you have more ideas to keep this repository tidy?

**Comment by elf-pavlik** [comment]
```
git branch -a | grep upstream | wc -l
34
```

from 87 i reported when opening this issue :dancer: 

thanks @mkllnk 

> I'm using my own fork more and more. All early work and experiments are on my own fork. I push branches to the main repository only once they are ready to review and test. We might switch to a model in which we create pull requests from our forks and don't need to keep any branches within the main project.

:+1:
