### ISSUE TITLE
bugsnag creeping into the app

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/openfoodnetwork#740]
I've never used BugSnag before but on first sight I really don't like that it creeps into various parts of the application

```
$ grep -r Bugsnag . | wc -l
46
```

Other error reporting systems seem to have much less intrusive integrations e.g. [open source Sentry](https://github.com/getsentry/sentry) 

> `gem "sentry-raven" #, :github => "getsentry/raven-ruby"`
>  `export SENTRY_DSN=http://public:secret@example.com/project-id`

from https://github.com/getsentry/raven-ruby

1) Does bugsnag also support less intrusive integration?
2) How we can allow each instance to choose its preferred error tracking service?

**Comment by mkllnk** [comment]
Bugsnag's integration is not intrusive at all. If you just use the gem and add one config file with your API key, then all errors get reported to the Bugsnag website. The code you find with grep is our additional use. There are some things we check for and report through Bugsnag without throwing an exception that prompts the user with a server error.

We should introduce another layer for that. There are two things on my mind:

 * Are there exceptions you can throw that are not causing a server for the user, but are reported by error tracking services? Something like a warning exception? If so, we could throw one of those exceptions instead of calling Bugsnag.notify.
 * Alternatively, we could introduce another layer, like a logger. Instead of Bugsnag.notify(error) we would call something like OpenFoodNetwork.report(error). That method would write to a log file by default and can be configured to use Bugsnag or another bug reporting system.

The first solution would be nicer.

**Comment by pmackay** [comment]
Some related ideas: https://community.openfoodnetwork.org/t/better-logging-for-helping-to-resolve-production-issues/786

**Comment by lin-d-hop** [comment]
#gitcull2017
A larger dicsussion around logging needed before looking closer at this.
