### ISSUE TITLE
Add Customer Name to Subscriptions management page

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7403]
## Description

Page https://openfoodnetwork.org.uk/admin/subscriptions currently documents all subscriptions by the shopper's email address and not name.
Local food hub managers need to be able to identify if a shopper's subscription is active, paused, cancelled, pending quickly/at a glance.  Local food enterprises know their customers by name not email.
Search function searches by email not name.

## Expected Behavior

Customer name as well as email address is displayed on https://openfoodnetwork.org.uk/admin/subscriptions page.  Mock up:
![subspagetweak](https://user-images.githubusercontent.com/45104035/114526418-dfb4b700-9c3e-11eb-9388-20344a7c76c5.jpg)
Hub manager can search subscription list by customer name as well as email.

## Actual Behaviour

Customer name does not appear on page https://openfoodnetwork.org.uk/admin/subscriptions.
![subspagecurrent](https://user-images.githubusercontent.com/45104035/114526536-fc50ef00-9c3e-11eb-8f1a-6e13b2fb8e0d.jpg)

## Steps to Reproduce

1.
2.
3.
4.

## Severity

bug s4
paper cut
design input needed.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Dear @openfoodfoundation/train-drivers-product-owners,

 - I change `Search by email...` to `Filter by email or name...` : I added `or name` because now we can search through name since it's displayed into the table, and I replace `Search` by `Filter` because we only filter the displayed subscriptions and I think it's more about filtering than search.
 - The first column (the `Customer` one) now display both the email and the name.

###### Screenshot
<img width="824" alt="Capture d’écran 2021-04-20 à 15 37 27" src="https://user-images.githubusercontent.com/296452/115405190-524d0600-a1ee-11eb-919a-64b551c4d48b.png">

###### Video
![2021-04-20 15 36 52](https://user-images.githubusercontent.com/296452/115405941-fc2c9280-a1ee-11eb-8a88-bb4eb3a834e6.gif)

Please, tell me what you think!

**Comment by RachL** [comment]
@jibees is this text available for translation?

**Comment by jibees** [comment]
@RachL Already available under the `subscriptions.filters.query_placeholder` key. 
 - Should I create another key since this one is already translated?
 - Should I don't care about the translation since it's handled by instance managers?

**Comment by jaycmb** [comment]
> I replace Search by Filter because we only filter the displayed subscriptions and I think it's more about filtering than search.

To me the functionality 'looks & feels like' a search, even if it technically works more like a filter.
For a filter the user would expect to have filters, not a search bar with an open input field.

**Comment by jibees** [comment]
Ok, I don't change anything about translation, that's better ;)
