### ISSUE TITLE
Shopper checkout error 

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7415]
## Description

Shopper unable to complete checkout.  
Error message unclear as to cause.

enterprise ID 202036
time/date 18:50 (ish) 13/04/21

![COMshoppercheckoutfail](https://user-images.githubusercontent.com/45104035/114680757-6633cc00-9d05-11eb-8128-2ce4870c6ec4.png)

Other shoppers able to complete checkout later that day (through Stripe).
Stripe account shows no history of the transaction.

## Expected Behavior

Error message encountered when checkout is unsuccessful details the reason why

## Actual Behaviour

Error message encountered when checkout was unsuccessful does not detail steps the shopper can take to complete their shopping.

## Steps to Reproduce

Bugsnag: 

https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/5f61d13464b255001708cda0?filters[event.since][0]=2021-04-13T16%3A50%3A00.000Z&filters[error.status][0]=open

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lin-d-hop** [comment]
Looks like user error:
{"code":"incomplete_number","type":"validation_error","message":"Your card number is incomplete."}

It would be great if this error message was passed on to the shopper.

Is it possible this was introduced in the latest release? If not then since we've only seen 2 cases ever it doesnt seem to be a big problem for us.

**Comment by RachL** [comment]
@lin-d-hop do we know if this error has occurred again?

**Comment by RachL** [comment]
I'm closing as this was on the old checkout and apparently never occurred again.
