### ISSUE TITLE
incorrect product displayed in multi OC shop

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#7458]
## Description
Enterprise ID : 998 

A shop with 3 OC opened simultaneously, with 3 identicals product's content 
<img width="1164" alt="Capture d’écran 2021-04-22 à 16 12 18" src="https://user-images.githubusercontent.com/67476305/115729252-8c9cdb80-a385-11eb-9caf-798da8458d2c.png">

## Expected Behavior
Products diplaying identical in the [shop](https://www.coopcircuits.fr/le-potager-de-saint-inn/shop) for the 3 OC

## Actual Behaviour
The shop displaying 20 products for the 1st OC "Commande des plants pour le 30 avril" 
<img width="1164" alt="Capture d’écran 2021-04-22 à 16 12 18" src="https://user-images.githubusercontent.com/67476305/115730202-5e6bcb80-a386-11eb-8808-fbc7566b12b9.png">

When swicth from the top right button or the 2nd OC "Commande pour le 14 mai" the shop displaying 20 products 
<img width="1229" alt="Capture d’écran 2021-04-22 à 16 19 25" src="https://user-images.githubusercontent.com/67476305/115730973-0b464880-a387-11eb-9daa-9117b138f680.png">

But, when you switch for the third OC "Commande pour le 28 mai" the shop displaying 10 products.
So, It missed 10 products, the displaying stopped to the tenth product " poivron Corno Di Toro Roux " 

<img width="1001" alt="Capture d’écran 2021-04-22 à 16 22 24" src="https://user-images.githubusercontent.com/67476305/115730936-02557700-a387-11eb-870d-bcdd39d0b888.png">

## Steps to Reproduce

1. To the shop https://www.coopcircuits.fr/le-potager-de-saint-inn/shop
2. Consult products 
3. Change OC from the first to the third
4. Compare products

## Workaround
Ask client to reload the web page

## Severity

bug-s3: a feature is broken but there is a workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Browser name and version: Firefox 87.0 (64 bits) and Chrome Version 89.0.4389.128

**Comment by Matt-Yorkley** [comment]
I can replicate the issue in that shop :+1: If I reload the page or switch back and forth between the tabs, it then shows all the products (not just those first 10).

Products not loading is at least an S2, right?

**Comment by Cecilia-Hn** [comment]
Thanks @Matt-Yorkley !

**Comment by jibees** [comment]
I can't reproduce it on my machine (still need to done some more configuration), but what I can see from production, is the next scenario:

___Before__: refresh the page, and go to the shop_

_**Step 1**: select one OC_
First request is requesting the tenth first product, and the second one (immediatly after, not after scrolling the page or whatever) is requesting the following ten (`page=2&per_page=10`)
<img width="349" alt="Capture d’écran 2021-04-23 à 11 45 00" src="https://user-images.githubusercontent.com/296452/115853568-9aa43800-a429-11eb-8218-7f3e0f6b8923.png">

_**Step 2**: change to another OC_
The first request is the same, then, just after, we have 2 identical requests (one to the other and to the previous one, because of the parameters: `page=1&per_page=10`)
<img width="636" alt="Capture d’écran 2021-04-23 à 11 45 07" src="https://user-images.githubusercontent.com/296452/115853868-ec4cc280-a429-11eb-909c-530af9a4b5a7.png">
Just after a scroll on products, then we have the following request:
<img width="563" alt="Capture d’écran 2021-04-23 à 11 51 23" src="https://user-images.githubusercontent.com/296452/115854122-3b92f300-a42a-11eb-96e2-9598c0e1b056.png">
which seems to be legitimate as we scroll down to the next 10 products.

_**Step 3** : change to another OC_
Only the first request, and nothing happen (scrolling or not):
<img width="211" alt="Capture d’écran 2021-04-23 à 11 45 26" src="https://user-images.githubusercontent.com/296452/115854333-6da45500-a42a-11eb-8e8f-bcf8bc842077.png">

**Comment by jibees** [comment]
The issue is: we don't change the `$scope.page` parameter to `1` if we do change `order_cycle`
