### ISSUE TITLE
Problems setting order cycle times

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#746]
## Description
 In Firefox or Safari or Explorer, when setting up or updating an OC time, if I type in the time manually as 23:59:59, OFN resets it to 23:45:59.

## Expected Behavior
The time I type should stay as it is.

## Actual Behavior
OFN reset min to 15 min slots (00, 15, 30 or 45)

## Steps to Reproduce
1. Open Firefox or Safari or Explorer
2. Go to order cycle, edit one or create one
3. Try to set up the date manually

## Animated Gif/Screenshot
https://www.useloom.com/share/97d3ae91016f4271acf42da2d487d2fd

## Context
Reported by Nick, retested by Myriam (only on Firefox).

## Severity
S4. Not a major thing and we can work around this by changing the time on the order cycle before actually opening the order cycle.

## Your Environment
- Version used: 1.11
- Browser name and version: Firefox Quantum 58.0.2 (64 bits)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by NickWeir63** [comment]
This issue happens in Explorer too

**Comment by NickWeir63** [comment]
Sara pointed out that we can work around this by changing the time on the order cycle before actually opening the order cycle.

**Comment by RachL** [comment]
Hello @NickWeir63 There was another bug with time selection that is now solve since 1.28 Completo. The current solution involves a selector which help select slots of 15min. However I just tested and if you add a custom hour/min combination it stays with the custom combination and does not reset. So I think we are good here and I'm closing this.
