### ISSUE TITLE
Group Creation does not allow for state/province selection when country is sleected

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#7489]
## Description![Stateless](https://user-images.githubusercontent.com/37803238/116170518-d1917c80-a6bb-11eb-96be-53f0ab875205.gif) 

When creating a group, when a superadmin sets contact details, they must choose the country (i.e. the instance's country is not default), and when "United States" is chosen, a list of states is unavailable.

## Expected Behavior
The Country should default to the instance's country (I think) and a list of states as populated at /admin/countries/12/states should appear.

## Actual Behaviour
The country must be chosen from a dropdown list, and when the country is selected, the "State" dropdown does not present any choices..

## Steps to Reproduce
1. Log in as superadmin, go to "groups" in admin panel
2. Click "Create Enterprise Group
3. Click to Contact details
4. Enter Country from dropdown
5. No state list appears

## Animated Gif/Screenshot

![Stateless](https://user-images.githubusercontent.com/37803238/116170518-d1917c80-a6bb-11eb-96be-53f0ab875205.gif)

## Workaround
Create the group, then come back and adjust the state once the group is created

## Severity

bug-s5: we can live with it, only a few users impacted. It really only shows up when creating a group, making it a two step process.

**Comment by andrewpbrett** [comment]
Upgraded to an S3 since this also shows up on the "Checkout as a Guest" screen. 

I looked at the US server and `Spree::Config[:default_country_id]` was returning `12`, which is indeed the country code for St. Vincent and not the US. However, `Spree::Country.find_by(iso: ENV.fetch("DEFAULT_COUNTRY_CODE", "US")).id` returned the correct id for the US. In `db/default/countries.rb` it seems like we should set the correct default country with:

`Spree::Config[:default_country_id] = Spree::Country.find_by(iso: ENV.fetch("DEFAULT_COUNTRY_CODE", "US")).id`

But perhaps this line is not being run, or something changed recently such that we're overwriting the code somewhere else. 

I also noticed that on the AU server, the Country with id `12` is in fact Australia, which means the countries table is different on different instances. So maybe this was a default at one point.

As a stopgap, I manually updated the default country on all managed instances by doing 

`Spree::Config[:default_country_id] = Spree::Country.find_by(iso: ENV.fetch("DEFAULT_COUNTRY_CODE", "US")).id`

in a console. This may or may not be a solution that persists across deploys/provisionings, so we should check after the next deployment/provisioning. Even if it does persist, we should still investigate why the config isn't being set up properly for new instances.

**Comment by RachL** [comment]
FYI @andrewpbrett it did not persisted, as foreseen :(

**Comment by andrewpbrett** [comment]
Thanks for the heads up @RachL. I reset them all so they should be back to the correct country again; I think I have an idea of how it's happening and how to actually fix it as well.

**Comment by andrewpbrett** [comment]
This looks like the commit that changed it: https://github.com/openfoodfoundation/openfoodnetwork/commit/39fa315ecca814932cd0c0d417b4891a647676c4
