### ISSUE TITLE
New order breaks if I change distributor midway through creating order

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#749]
[The likeliness of this happening is very low - reviewed by Myriam / March 2018]

## Description
If you create an order from back end (admin), and while adding the products, change distributor, the system display an error message telling you that this distributor cannot provide the products listed BUT let you move forward in passing the order creating lot of confusion and unwanted results

## Expected Behavior
When the error message is displayed, it should not be possible to click any other thing until you either:
- delete the products listed (from the previous distributor)
- or changed back the distributor to the previous one
So you should only be able to do that, any other click on any other thing in the modal should be impossible.

## Steps to Reproduce
1. From back end, create an order and select one distributor and order cycle
2. Then add a product to the order
3. Then change the distributor and order cycle > you see error message, but ignore it
4. Then add a new product (belonging to the second order cycle). It allowed me to do this, but told me I had made a mistake, adding a product from the wrong order cycle. 
5. But when I removed the first product and went onto the next step (customer details), it got confused

## Animated Gif/Screenshot
![bug6](https://user-images.githubusercontent.com/8135376/37086053-e6903b5a-21f6-11e8-8eaf-2503490aa2a8.png)

## Context
When reviewing an old bug from Sally.

## Severity
S5 very unlikely anyone ever see that.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
See expected behavior.

**Comment by myriamboure** [comment]
I propose to close that issue as sincerly this is really unlikely this ever happen for real... AND even if it is possible to continue and pass the order that way, when you change distributor you have a big warning telling you that this distributor cannot provide the products listed... I think we can say it's enough given the probability of this behavior, no?
![screenshot from 2018-03-03 00-05-20](https://user-images.githubusercontent.com/8135376/36926222-dfc3f9ac-1e76-11e8-8194-fd631170e6cc.png)

Else I suggest we open a S5 bug with expected behavior:
when error message display, should not be possible to click any other thing until you either:
- delete the products listed (from the previous distributor)
- or changed back the distributor to the previous one
So you should only be able to do that, any other click on any other thing in the modal should be impossible.

@sstead @daniellemoorhead what do you think is the best practice for such very improbable cases?

**Comment by daniellemoorhead** [comment]
I think your solution is a good one @myriamboure and it's definitely an S5 👍

**Comment by lin-d-hop** [comment]
Closing as the bug description is not accurate in v2 and the error is quite clear now.
