### ISSUE TITLE
Upgrade papertrail

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#7551]
### What we should change and why (this is tech debt)

Broken build when dependabot upgraded papertrail gem. <s>Could consider switching to Active Storage instead?</s> 

### Context

https://github.com/openfoodfoundation/openfoodnetwork/pull/7550

**Comment by luisramos0** [comment]
I think you are mixing with paperclip that will be related to active storage.

This was is about tracking changes to dbs in a db table.

This is breaking because tracking associations has been extracted to a separate gem as it's mentioned in the warning we see when we run rails s:
"Association Tracking for PaperTrail has been extracted to a separate gem. To use it, please add `paper_trail-association_tracking` to your Gemfile. If you don't use it (most people don't, that's the default) and you set `track_associations = false` somewhere (probably a rails initializer) you can remove that line now."

I added a commit to 7550 to remove the initializer as the warning recommends (we have it set to false), let's see what the build says.

**Comment by andrewpbrett** [comment]
Closed via #7550
