### ISSUE TITLE
Multiple Stripe payments collected for incomplete order created in back office

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7614]
## Description

Order ID R506827701

Order created in the back office by hub manager.
Each time they added a card payment it stated that there was 'An Error Saving Payment'
![imbywallpaymentbackend](https://user-images.githubusercontent.com/45104035/117789350-2b5b8000-b240-11eb-9b3e-e2d97922abdf.png)

I am unable to find a bugsnag for this.  NOTE billing name is different to the name on bank card used for final payment, but consistent otherwise

Order remains 'incomplete' at 'Payment' stage on OFN platform with four pending payments showing:
![imbywallorder](https://user-images.githubusercontent.com/45104035/117789551-5c3bb500-b240-11eb-86b5-c49c1311aec1.jpg)

Stripe records show that all four payments have been collected:
![imbywallstripe](https://user-images.githubusercontent.com/45104035/117789608-6958a400-b240-11eb-8a9a-b7925d4ab05b.jpg)

Clicking on the 'X' to void the last three payments on the OFN system and 'tick' on the first (to capture one payment on OFN and hence move the order to 'complete' for delivery and supplier reporting) resulted in three payments as 'void' and one as 'failed'. 
![imbywallorderpost](https://user-images.githubusercontent.com/45104035/117792328-17654d80-b243-11eb-9942-d079a2e2f761.jpg)
But on Stripe ALL FOUR are refunded:#
![imbywallstripepost](https://user-images.githubusercontent.com/45104035/117792407-2815c380-b243-11eb-9fbe-a5206d49103d.jpg)

## Expected Behavior

Order created in back office.
Shopper pays by card over and hub manager enters in card details.
If card details are correct, OFN and Stripe both record payment has successfully been taken.  OFN order moves from the incomplete 'Payment' status to 'complete' 'paid' status.
If card details are not correct OFN shows incomplete payment failed.  No payment collected by Stripe- this also shows 'failed' payment attempt.  Order remains at 'Payment' status on OFN platform.

## Actual Behaviour

Order created in back office.
Shopper pays by card over and hub manager enters in card details.
OFN displays 'Error in taking payment' notice but Stripe processes the payment.
Order remains in 'Payment' incomplete status on OFN platform.
Payment collected from shopper multiple times.

## Steps to Reproduce

1.
2.
3.
4.

## Severity

Bug S1

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment]
Note that further investigation shows that two items in the order were out of stock:
1. Hogget leg on the bone 1.5kg (two were in the basket but only one available)
2. salad leaves with edible flowers 150g bags (2 in basket but none available)

**Comment by andrewpbrett** [comment]
@lbwright22 thanks for reporting this, we're looking into it. Is that first screenshot from you reproducing the error, or from the hub manager?

**Comment by lbwright22** [comment]
@andrewpbrett the first screen shot is from the hub manager (although I edited out the customer details)

**Comment by andrewpbrett** [comment]
Thanks @lbwright22!

This is the relevant bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f2954c78473a50018ef45a9

It does looks like the root cause is those items being out of stock, but we should obviously be handling it differently. Thanks for noting that, very helpful when debugging. 

I'm hoping to have a PR written to address this soon. Is there anything else you need immediately to address this specific payment @lbwright22? The sort-of-good news is that it only occurs in this case where one of the order's items is out of stock, and not to all backoffice payments.

**Comment by Matt-Yorkley** [comment]
Shout if you want some backup @andrewpbrett.

Also we could do some rubber-ducking in the issue comments, it might help with asynchronous problem solving?

**Comment by andrewpbrett** [comment]
So according to the Bugsnag, this is happening because we try to save a StockItem with a negative quantity. 

And we get to that part of the code by doing `OrderWorkflow.new(@order).complete!`:

https://github.com/openfoodfoundation/openfoodnetwork/blob/4932e1dcb5473891ce867811f63b2c2559e4aaec/app/controllers/spree/admin/payments_controller.rb#L36-L50

**Comment by andrewpbrett** [comment]
Ah, okay. Before we get to that if-branch, we call `authorize_stripe_sca_payment` on line 34. That's consistent with the payments showing up as Pending in the OFN backend. Again, however, the payment should not be taken at that point. I'll look in to the Stripe logs next. 

Also of note: there are other Bugsnag reports that trace back to this same line, where we try to `save!` a StockItem, but the trace leads somewhere else (`products#bulk_update`, for example).

**Comment by andrewpbrett** [comment]
We attempt to process the payments any time we transition to complete:

https://github.com/openfoodfoundation/openfoodnetwork/blob/4932e1dcb5473891ce867811f63b2c2559e4aaec/app/models/spree/order/checkout.rb#L70-L74

**Comment by andrewpbrett** [comment]
@Matt-Yorkley I have to put this down for a little while (maybe until tomorrow) so feel free to pick it up from here if it hasn't advanced by the time you see it. 

I think because of the edge-case-iness it might not have the urgency of an S1 any more. Still a big bug to fix, but unlikely that it will pop up again any time soon. 

Throwing out some ideas on how we could fix it from here:

We could check all the line items to make sure they're in stock before processing the payments. One way would be doing `finalize` before `process_payments`. But... I have a feeling there's a reason we're doing it in the order we are. 

So maybe we need to specifically check that the order's items are all in stock before processing payments. But that's solving this specific problem; in the future, there could be other things that could go wrong when we call `finalize!` and ideally we'd have a way to recover from any of them. But I don't think the solution should be to process the payments, and then reverse/refund them if something goes wrong. We need a way to tell if `finalize` is going to succeed, like a dry run flag or something... 

Or we could go back to the first suggestion, examine why exactly we call `process_payments` **before** calling `finalize!` instead of the other way around, and reverse the order.

**Comment by Matt-Yorkley** [comment]
Nice digging! :duck:

So... the stock is actually reduced at the point the order is "finalized" (competed), but in order to do that the order needs to have a valid payment that's been created (even if the payment is actually not paid yet). But... we're not checking the stock levels before reaching that completion step when we create an order via admin, and in admin the final step that kicks the order into completion happens here in the payments controller after the new payment has been submitted...

I think the `#process_payments` call that happens in the checkout flow isn't what _creates_ the actual payment object though, right? It processes a payment object which should already exist at the point the order is finalized? At least in the frontoffice checkout flow.

I think we need to do a stock check and bounce the user back to first page with an error message if something is out of stock, before that point where we try to call `OrderWorkflow.new(@order).complete!` in `Spree::Admin::PaymentsController#create`. It'll only be needed on incomplete orders.

**Comment by andrewpbrett** [comment]
That first paragraph is an excellent summary 👍 

> I think we just need to do an explicit stock check

Yeah I'm also leaning toward that route. If I get a PR together I'll push it up and @-mention you @Matt-Yorkley, even if it's WIP, so we're not duplicating work. I don't have a ton of time left today but it'd be nice to get this in this week's release. I think we'll have to redraft anyway because of #7644.
