### ISSUE TITLE
BOM: Selecting an item and clicking "Delete Selected" allows the removal of the last line item from an order

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7637]
## Description

Please note that this bug can be addressed together with #8131 or separately. 

Similar to bug #7627, but concerning `/admin/orders/bulk_management`:
Selecting a line item and clicking "Delete Selected" on the actions menu allows the removal of the last item from the order.

The consequences are the same as in bug #7627:

- precursor from #5505
- on a complete order - which is a condition for showing up on the list under bulk order management - it changes the Shipment state from Ready to None (NULL).

## Expected Behavior

Selecting the last item of an order and using the "Delete Selected" button:
- should display a modal "Deleting this item will cancel the order as it is the last line item, do you wish to proceed: yes/no" (similar to the one implemented by #8040)
- selecting "yes" should cancel the order -> changing the order status to cancelled and shipment status to none

## Actual Behaviour

Deleting the last item is allowed; no error is displayed and so the admin is unaware that the last item is being deleted.

## Steps to Reproduce

As admin
1. Take note of the order number of an order with one line item only
2. Visit `/admin/orders/bulk_management` and look for that order
3. Select that order and, on the Actions menu, click "Delete Selected"

## Animated Gif/Screenshot

![Peek 2021-05-13 13-39](https://user-images.githubusercontent.com/49817236/118126814-c1360d00-b3f0-11eb-88d8-d49020eb158d.gif)

## Workaround

Same as in 7627; not sure if valid.

## Severity

Proposing:
bug-s3: a feature is broken but there is a workaround
ping @openfoodfoundation/train-drivers-product-owners 

## Your Environment

* Version used: v3.7.0
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by jaycmb** [comment]
Thanks for opening @filipefurtad0.
Should be add to expected behaviour the specifics of the error alert to be consistent with #8131 :

- should display a modal  "Deleting this item will cancel the order as it is the last line item, do you wish to proceed: yes/no".
- selecting "yes" should cancel the order -> changing the order status to cancelled and shipment status to none

Just to ensure that we have the same behaviour for all cases where the user would delete the last item of an order:
- trash bin on BOM
- global action drowpdown delete selected on BOM
- deleting last item on order page

**Comment by filipefurtad0** [comment]
Updated :ok_hand:

**Comment by drummer83** [comment]
Has this been solved by #8294?
I believe this one here is also covered by #8131, isn't it?

**Comment by RachL** [comment]
Yes!
