### ISSUE TITLE
[Spike] Payment method developed for Turkey

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#7658]
## Description

See discussion here: https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1620662346160700

As Stripe and Paypal are not available in Turkey, the Turkish team has developed an integration with a payment gateway on an OFN fork:

https://github.com/fatihorhan/openfoodnetwork
https://github.com/fatihorhan/ofn-install

This situation is not sustainable for them as their main developer has left the project. They would like to know if it is possible to merge this with the main code base.

## Acceptance Criteria & Tests

1. Assess if we could merge the code as is, and if not what are the options to move forward
2. Time box on code review: 2 hours

**Comment by lin-d-hop** [comment]
This is also relevant for Russia, [see discussion here.](https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1622751542094400)

It would be good to try and come to an agreed general approach for payment gateways as we might be able to leverage some volunteer contributions to help prepare the OFN code (checkout controller paths/decorators for example).

**Comment by luisramos0** [comment]
Hello, pls see my comment on the slack thread with my evaluation.
I think we should clearly divide this investigation in two parts:
- simple payment gateways like StripeConnect with simple processing workflow, for example, call api and receive reply, without redicts
- complex payment gateway like StrpeSCA and this one where we need to redirect to checkout page after processing

The code for the second type will be very mixed up with core ofn checkout code (it's the biggest problem with this code for the Turkish gateway, a good part of it is copy pasted from the stripeSCA gateway).
We could do some modifications to our checkout code to make these extensions easier to do in the future. I think it's worth the effort at some point.

**Comment by mkllnk** [comment]
That are good points, Luis. I reckon that all modern payment methods will be of the complex type though. Regulations make it necessary to add this complexity with user interaction. We can't just charge a credit card with a simple API call anymore.

I had a look through the Turkish code and my gut says that it's 70% good, 20% needs improvement and 10% won't be included in OFN. It would be a day's work to create a proper pull request just for the payment method. I do think that it's worth it because all of the code is already there.

Moving the code into it's own gem would be more work. And conditionally loading gems would make our code more complex. I think it's easier to keep in sync when keeping it in the main repository for now. Over time, it would be good to move some of the code into a gem and give instances the option to configure which methods they want to have active.

There are some more code additions, some of which could be merged, others not.

- Colour changes in icons, difficult.
- Wider shop search, medium.
- Additional hints in the payment method form, easy.
- Custom log level, medium.
- Custom footer for QR code, medium.
- Toggle effect of the cart, medium.
- Custom terms of service, already done but needs slight modification.


I rebased the Turkish branch on our current master to see how difficult that is and it was easy. The customisations are untested though. Here's the new branch: https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:tr-master

**Comment by luisramos0** [comment]
Nice, this is progressing.
Yes Matt, that's what I meant in terms of making checkout code easier to extend :+1: 
There's also subscriptions code, I think there's some stripe stuff in there that could also be extendable to other payment methods.

I am not very happy to add this code to OFN, we would have to maintain it and it will break I am sure and we will spend time with it. Having code in the repo that we do not test/maintain is just wrong I think.
I think the question is: can we add this code to the repo and maintain it? do we have the resources to do it?

**Comment by battoo** [comment]
@Matt-Yorkley ''As I understand it; the QR code in the footer is a legal requirement that has very serious consequences if it's not met. Some of those other tweaks like changing the log level or the colours on map icons are probably not vital and could be dropped.''  this is correct.

**Comment by fatihorhan** [comment]
Hello all. I'm the author of these changes. Thanks for reviewing this code and considering to add to OFN.

You have valid concerns about adding untested code to the codebase. I have general rspec and rails knowledge, if you can provide assistance in parts specific to OFN codebase I think we can add tests to the payment code.

**Comment by mkllnk** [comment]
That is excellent news, @fatihorhan. Would you be able to create pull requests for separate features? For example, for the QR code, we could have a general HTML field which is defined as super-admin (Settings -> Content) and displayed in the footer. Or you could try to use the existing content fields to display the QR code.
And another pull request for the payment method would be great. Ask us on Slack when you have questions or in a pull request draft.

**Comment by lin-d-hop** [comment]
Hi @battoo and @fatihorhan 
We talked about this work in our delivery team meeting today. We'd really like to support you to merge this work and we've got a couple of options. You can read more [here](https://community.openfoodnetwork.org/t/delivery-circle-meeting-notes-june-29th/2338) (notes on this topic at the bottom).

It will be important to note that whichever option you choose, until Turkey are a fully supported and contributing instance we won't be able to provide maintenance on this payment method. This means that if a change breaks the payments we can let you know, but we won't be able to fix it. Happy to discuss any of this more on Slack :-) And I really hope we can work toward getting this merged for you asap!

**Comment by mkllnk** [comment]
Just re-iterating that we are waiting for your input here. This issue was about estimating the work that needs to be done and it can be closed now.

**Comment by battoo** [comment]
Hello Maikel,

Thanks for the info.
Please note that we are working on this issue and will get back to you
soon. Our reaction delayed because of some personal occupations.

Regards,
Batuhan

16 Tem 2021 Cum, saat 03:32 tarihinde Maikel ***@***.***>
şunu yazdı:
