### ISSUE TITLE
Error 502 after deploying Rails 6.0 upgrade PR

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7676]
## Description

Deployment fails when staging PR #7554: accessing the URL displays a `502 Bad Gateway` error.

![image](https://user-images.githubusercontent.com/49817236/118991561-c3154880-b97b-11eb-8a71-aad748cbcc61.png)

Initialization is failing:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60a667b40c51f00007c9875d?event_id=60a667b4007c9d7ed59e0000&i=sk&m=nw

**Comment by luisramos0** [comment]
Hi Filipe, thanks! 

I still have access to the staging server :tada:

I can see this is the error:
```
LoadError: No such file to load -- active_storage/base_controller.rb
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:411:in `block in require_or_load'
  /home/openfoodnetwork/.gem/ruby/2.5.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:40:in `block in load_interlock'

```

**Comment by luisramos0** [comment]
The quickfix for this is to revert a bit of this commit: https://github.com/openfoodfoundation/openfoodnetwork/commit/d8694564e0edd3da90810b9b7d04f02aac9e6a37

like this:
https://github.com/openfoodfoundation/openfoodnetwork/pull/7554/commits/f7e1ec6d44530caded0e15cbc466aa578c7ab2ef

and the problem is solved. I think we can try to deploy #7554 as is and it will work. 

I dont understand why active_storage base_controller is being required. Maybe a new internal dependency tree in rails 6?

For action_mailbox, it's weird but this is the error:
mnt/EXTRA/.rvm/gems/ruby-2.5.8@openfoodnetwork/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require': No such file to load -- action_mailbox/base_controller.rb (LoadError)

It looks like active_support depends on action_mailbox!?

@Matt-Yorkley any idea?

**Comment by Matt-Yorkley** [comment]
So `ActiveStorage` is the new standard for handing file uploads, but we haven't switched to using it yet as it might be quite a bit of work. It's definitely something we should be doing, it just been regarded as low-priority tech debt.

We should definitely try to avoid loading `ActiveMailbox` though! We'll have to rummage around in the source code there and see why those extra dependencies are being loaded :man_shrugging:

**Comment by Matt-Yorkley** [comment]
Aha! I think it's because in the custom rails-dependencies-loading commit I wrote previously, I removed `require 'rails/all'` (which loads everything), but in `lib/spree/core.rb` there's still a call to `require 'rails/all'`, so as soon as we load `Spree` it loads all the things we explicitly tried to avoid (including `ActionMailbox`). 

The fact that the backtrace points to `ActiveSupport` is just because that's what's handing the loading of dependencies (in general).

**Comment by sauloperez** [comment]
I wonder why aren't we using `require 'rails/all'` regardless of the fact that we won't enable those new Active*.

**Comment by Matt-Yorkley** [comment]
Discussion here: https://github.com/openfoodfoundation/openfoodnetwork/pull/7554#discussion_r628895710

**Comment by sauloperez** [comment]
It'd be great if we could find a way to require all BUT actionmailbox. I don't know if there is.

**Comment by luisramos0** [comment]
Hello, the deployment is now working fine, I am closing this, Filipe, let me know if you still have any issues with this.

**Comment by filipefurtad0** [comment]
Hey @luisramos0 ,

Some issues with deployment seem to have re-appeared, please see:

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/au-staging/deploys/340

```
fatal: [staging.openfoodnetwork.org.au]: FAILED! => {"changed": true, "cmd": ["bash", "-lc", "bundle install --gemfile /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2021-05-29-092150/Gemfile --path /home/openfoodnetwork/.gem --deployment "], "delta": "0:00:02.377365", "end": "2021-05-29 09:22:46.854262", "msg": "non-zero return code", "rc": 7, "start": "2021-05-29 09:22:44.476897", "stderr": "", "stderr_lines": [], "stdout": "Unable to find a spec satisfying actioncable (= 6.0.3.6) in the set. Perhaps the\nlockfile is corrupted?", "stdout_lines": ["Unable to find a spec satisfying actioncable (= 6.0.3.6) in the set. Perhaps the", "lockfile is corrupted?"]}
```

Re-opening.

**Comment by luisramos0** [comment]
Sorry Filipe, simple error during the rebase. It should be ok now :+1:

**Comment by filipefurtad0** [comment]
No worries Luis, thanks :+1
Deployment is working fine now and [email issues](https://github.com/openfoodfoundation/openfoodnetwork/issues/7554#issuecomment-851287592) seem resolved as well :+1: 
Closing.
