### ISSUE TITLE
Changes made to Order Cycle not captured by 'Save' if Date Picker is open

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7689]
## Description

Final edits made to a cloned order cycle on the order cycle admin page ( https://openfoodnetwork.org.uk/admin/order_cycles ) are not captured by 'Save' if the date picker is open.

This results in order cycles opening and closing at non-desirable times.

## Expected Behavior

Clone an order cycle.
Edit the name, open and close date and time as shown in video below.
Click 'Save' while the date picker is still open.
All edits made are captured.

## Actual Behaviour

Clone an order cycle.
Edit the name, open and close date and time as shown in video below.
Click 'Save' while the date picker is still open.
The final edit made to the order cycle (in the case of the video it is the minutes in the closing time) is not captured.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

https://user-images.githubusercontent.com/45104035/119632573-d6effd00-be08-11eb-9a09-84408580289f.mp4

## Workaround

Close the date picker before clicking 'Save'

## Severity

S4

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment]
Why not add a "Close" button? This makes it more obvious that you should close the date picker first (with or without this button) before clicking on the "Save" button:

<img width="352" alt="Capture d’écran 2021-05-27 à 11 54 39" src="https://user-images.githubusercontent.com/296452/119806265-5271ad00-bee2-11eb-9ea8-e4e41833585f.png">

**Comment by drummer83** [comment]
Yes, I like it! Maybe align the 'close' button to the right, to have it a bit separated from the 'now' button?

Still I think it would be best to also fix the underlying problem. If someone clicks 'save' without closing the date picker first, the current entries should be used. Is this technically possible @jibees?

**Comment by RachL** [comment]
@drummer83 from what I have understood form the discussion on slack, it's not possible to change this without changing the save behavior across all pages where the save button is displayed in the app. This is a big piece of work that would need to be prioritized and deserves a wishlist.

**Comment by drummer83** [comment]
@RachL I am not so sure that this is what @jibees meant. There are two different things:

1. In order to apply any changes on any page in the admin, you always have to click 'save'. This is the general OFN approach and that's totally fine. The other approach would be to automatically save things as soon as you type them without the need of pressing a 'save' button. You can leave the page any time and your changes will be saved. This is not what we want to change here.

2. What we are discussing here is that the typed values in the datepicker should be saved (when clicking 'save'), no matter if the datepicker is still open or closed. Currently it seems that the values of the datepicker are written into the input field as soon as you click anywhere (unless the 'save' button) or when the textfields for hour or minute are losing their focus. 
If it was technically possible to change the behaviour of the hour and minute fields to some onChange() action, we might get what we want: As soon as the hour or minute is changed, the current values will be written into the input field and those values would be saved even if the datepicker was still open and the focus was still in the hour or minute field.

Would that be possible @jibees?

**Comment by jibees** [comment]
For the record: https://github.com/flatpickr/flatpickr/issues/2459

**Comment by RachL** [comment]
@drummer83 I've tested it: if you edit a field, but you don't get out of the field, it does not save either. So I'm not sure it's a problem specific to the date picker.

**Comment by jibees** [comment]
I've open a PR, which doesn't include the 'Close' button stuff. I think this is more the purpose of another issue. 
What do you think? Happy to open a new issue, or modify the current PR, no strong opinion on it.

**Comment by jibees** [comment]
I totally agree @Erioldoesdesign 
The point here is that the date is _already_ set in the field, event if the datetimepicker isn't confirmed by clicking on the button Confirm. Do you think it can be a problem?

A more process-related question: should I open another issue for dealing with the button issue?

**Comment by jibees** [comment]
To not block this issue and its attached PR, I've open an new issue to discuss about the opportunity of adding (or not) this "Close/Confirm" button into the date(time)picker all over the application (and not only for the order cycles list): #7706

Feel free to discuss, comment. Thanks! 🙏
