### ISSUE TITLE
Orders show VAT figure based on master price (excluding mark-up)

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#773]
VAT on order does not include VAT on mark-up/enterprise fee - see screenshot
![vat](https://cloud.githubusercontent.com/assets/10517702/12178546/f38d6f68-b569-11e5-8845-c0a8abf53c75.png)

**Comment by NickWeir63** [comment]
Hi @rob I hope you are well.  I just spoke to Danni and she suggested that I check with you how the VAT/GST figure should be calculated on the orders, invoices, etc.  Thanks Nick

**Comment by oeoeaio** [comment]
Thanks @NickWeir63,

I've put this in the list of things to look at for the next sprint.

**Comment by myriamboure** [comment]
@oeoeaio we have tested that and will share also our case in case there can be some clue there... we detailed it a bit more to understand ourselves what was happening...
Actually the last line (includes tax) is a complete mysterious calculation.

See our case:
We have two products with three fees of 10% each, but in the set up we have put a different tax rate to each fee (for the test) Raw fish rate (11,11%), food rate (15%) and general rate (25%).
On the master price we apply the vat food rate (15%) for the first product and vat general for the second one (25%)
![vat3](https://cloud.githubusercontent.com/assets/8135376/12461821/1ebc0824-bfbb-11e5-8720-57d6af8751e6.png)
![vat4](https://cloud.githubusercontent.com/assets/8135376/12461824/26c7ae24-bfbb-11e5-98a0-d3b1804944bd.png)

I buy one of each, so we get:
![vat1](https://cloud.githubusercontent.com/assets/8135376/12461839/33de8a74-bfbb-11e5-9eac-9fdfb71b0e38.png)
As you see 244,17 + 40,32 doesn't make 276,41.

On checkout page we see that the 276,41 is made from the VAT applied only on master price, as you said @NickWeir63 
![vat2](https://cloud.githubusercontent.com/assets/8135376/12461876/748127d0-bfbb-11e5-9100-187c962c2bfd.png)
244,17 + 10,16 + 22,08 = 276,41 so this is ok. We checked the amounts that's right.

BUT look at the amount last line of the basket, it shows 40,32... which is different from 32,24, but where does this amount comes from? We tried to find by turning that in many directions and didn't find... When we add the supposed VAT for fees on top of the VAT on master price we obtain 41,84, which is not far but not exact.

If we take out the fee, the last line is correct and correspond to the master price VAT, so that means that some VAT on fees is added already on the last line, but it's wrongly calculated and not added correctly to the price excl. VAT...

(PS: I think there might be also a problem with the rounding that can cause issues as the VAT is calculated on the rounded figures... on small quantities it's only a few cents difference but it's always disturbing not to find the good figures ;-)  And on bigger quantities you can see more differences...)

**Comment by oeoeaio** [comment]
Thanks @myriamboure! That is awesome. This has been pushed up the queue, so I am working on this today. Hopefully I can work out what is going on... :persevere:

**Comment by oeoeaio** [comment]
So I think what is happening here is at least partially a misunderstanding of how tax is calculated on fees. I just looked at the [documentation](https://openfoodnetwork.org/platform/user-guide/hubs-set-up-guide/enterprise-fees/) and there is nothing there to explain how to include tax in fees, so I imagine rectifying that will help somewhat. 

Contrary to what appears to be intuitive (going on what @NickWeir63 and @myriamboure have tried/assumed), enterprise fees to not use the same tax rate as the products to which they are assigned. They have there own tax category, which is used to apply tax to all instances of the given fee.

You can set the tax category on a given fee type from the enterprise fees page:
![screen shot 2016-01-21 at 11 44 26 am](https://cloud.githubusercontent.com/assets/2067859/12468042/649269aa-c034-11e5-87c3-44c7e17da0ec.png)


I have done a bit of testing and as far as I can tell, tax is being calculated on fees as expected when tax is included in the price of the fees/products. I will do some more testing in a moment to verify that the same is true for non-included tax rates.

Testing Included Tax Rates

Setup:
Apples (Fuji) has a price of $10.00
Has a tax category with one tax rate (10%, included in price)
Has one fee applied (also 10%)
Fee also has a tax category with one tax rate (20%, included in fee)

So:
Fee of 10% on top of $10 is obviously $1.00
Tax included in price of the Apples is 10.0 - 10.0/(1.0 + 0.1) = 0.90909091
Tax included in price of the fee is 1.0 - 1.0/(1.0 + 0.2) = 0.16666667
Total tax on the apple is therefore: 0.90909091 + 0.16666667 = 1.07575758

Which is what I am getting:
![screen shot 2016-01-21 at 10 50 40 am](https://cloud.githubusercontent.com/assets/2067859/12467278/3ed4b98a-c02e-11e5-9ea7-76d30a8b0545.png)

More products:
Apples (Fuji) as above, cost: $10.00, included tax: 10%, fee: 10% with included tax of 20%
Apricots, cost: $10.00, included tax: 20%, fee: 15% with included tax of 30%
Mandarins: cost $10.00, included tax: 30%, fee: 20% with included tax of 10% 

Apples (Fuji) tax: 10.0 - 10.0/(1.0 + 0.1) + 1.0 - 1.0/(1.0 + 0.2) = 1.07575758
Apricots tax: 10.0 - 10.0/(1.0 + 0.2) + 1.5 - 1.5/(1.0 + 0.3) = 2.01282052
Mandarins tax: 10.0 - 10.0/(1.0 + 0.3) + 2.0 - 2.0/(1.0 + 0.1) = 2.48951049
Total tax = 1.07575758 + 2.01282052 + 2.48951049 = $5.57808859 = $5.58

The shop actually calculated $5.59 (see below), which I think is due to the tax on products and fees being calculated separately, like this: 
10.0 - 10.0/(1.0 + 0.1) + 1.0 = 0.91 (Fuji Product)
1.0 - 1.0/(1.0 + 0.2) = 0.17 (Fuji Fee)
10.0 - 10.0/(1.0 + 0.2) = 1.67 (Apricot Product)
1.5 - 1.5/(1.0 + 0.3) = 0.35 (Apricot Fee)
10.0 - 10.0/(1.0 + 0.3) = 2.31 (Mandarin Product)
2.0 - 2.0/(1.0 + 0.1) = 0.18 (Mandarin Fee)
**Total = 0.91 + 0.17 + 1.67 + 0.35 + 2.31 + 0.18 = $5.59**

![screen shot 2016-01-21 at 11 36 54 am](https://cloud.githubusercontent.com/assets/2067859/12467897/529dddd4-c033-11e5-92ad-41b326d8a6e3.png)

**Comment by oeoeaio** [comment]
Update: when tax rates are **not included** in price, tax is not applied to fees correctly. This is due to tax being applied to enterprise_fees as an included amount. At the moment, the total for an enterprise fee does not include the tax that is applied to it, and so when tax is calculated on the total as though it does, we get an incorrect number:
![screen shot 2016-01-21 at 1 24 10 pm](https://cloud.githubusercontent.com/assets/2067859/12469716/49c6b762-c042-11e5-8e81-0f3c7595beec.png)


I have come up with a fix that somewhat resolves the problem (result below), by altering the total amount for a given enterprise fee to be inclusive of tax, which then results in the calculation of included tax being correct. However, this also means that price for the line_item appears to change, as the fee applied to it is now large (tax inclusive). eg. A 20% tax on the fee causes the fee total to increase from 1.0 to 1.2 in the example below. Note that the total price and the included tax are correct, but the fact that the 20% tax on the fee is included in the price of the line item, while the 10% tax on the line_item itself is not. Unfortunately, this appears difficult to resolve fully with our current setup. I'm in the office by myself today, and I think I need to bounce some ideas off another brain, mine is melting.
![screen shot 2016-01-21 at 1 18 15 pm](https://cloud.githubusercontent.com/assets/2067859/12469673/eca3de2a-c041-11e5-8eea-f3b66aa02176.png)

**Comment by oeoeaio** [comment]
Ok, so I've had a play around and I have come up with a solution which seems to work. For the following settings (as above):

Apples (Fuji), cost: $10.00, added tax: 10%, fee: 10% with added tax of 20%
Apricots, cost: $10.00, added tax: 20%, fee: 15% with added tax of 30%
Mandarins: cost $10.00, added tax: 30%, fee: 20% with added tax of 10%

Should be:
(10 &times; 0.1) + (1.0 &times; 0.2) = 1.2
(10 &times; 0.2) + (1.5 &times; 0.3) = 2.45
(10 &times; 0.3) + (2.0 &times; 0.1) = 3.2
**Total = 1.2 + 2.45 + 3.2 = 6.85**

I get: 
![screen shot 2016-01-21 at 4 56 39 pm](https://cloud.githubusercontent.com/assets/2067859/12472801/fbb10e92-c05f-11e5-8efd-cafca96cb5e3.png)


Does that look right?

**Comment by myriamboure** [comment]
Hi @oeoeaio ! And thank for all the work on that :-) It seems that you managed to find a great solution.

Here is our need that I precised in this other discussion: https://github.com/openfoodfoundation/openfoodnetwork/issues/725#issuecomment-162444902
In Europe, there are two different needs:
- in BtoB, prices are always shown without VAT, because when a shop buy to another shop, the VAT is not a cost for the company (companies just collect it for the state). So for the case a hub sell to another hub, we will want in this order cycle to show the prices and associated fees excluding VAT, and just do as you did, add the VAT at the end like in your last example which seems to work.
-BUT what is even more important for us at the moment, because we mainly use OFN for BtoC hubs, in that case prices are always shown in the shopfront INCLUDING VAT, so basically in your last example, the price of the Apples in the shopfront wuold be 12,2, the price of the Mandarins would be 14,45 and the price of the Apricots would be 14,70. And ideally, in the price breakdown that would be awesome to have a breakdown without VAT + a line for the VAT for each product (but at least then show the breakdown including VAT for each line in the breakdown). And it is a legal obligation in the invoice to show then the detail of the tax which is included, so we need in your last example to show the total price including VAT, and then (including VAT: xxx). Same on checkout page, we need the detail for every tax rate.
Because we really need to use as a masterprice the price without VAT, as if the product is sold in another hub in another country, they  need to be able to apply their own tax rate on it... So ideally we would like the tax to be added on the master price, and same for the fees, and we chosse if we wante the taxes to be displayed in shopfront or at checkout.

Does it sound like doable?

Cheers, and well done again for the chasing :-)

**Comment by oeoeaio** [comment]
Pinging: @daniellemoorhead, @NickWeir63, @myriamboure, @olivierkrener, @RohanM, @kirstenalarsen 

Hi Myriam, thanks for that info. Sorry I am not more up-to-speed, most of the work on tax has been done by @RohanM up to this point. 

#### The Way It Works Now
**This is as much for my sake as for anyone else's**

`included_in_price=true` **tax rates for products** will apply to the base price of the productin question, and will calculate the amount of tax included in the price 'backwards'. ie. the final charged price will not change due to the tax being applied, but rather a portion of the base price will be marked as being the tax component of the total price. These portions are explicitly recorded against individual line_items as TaxRate adjustments with included_tax.
`included_in_price=true` **tax rates as applied to fees** will calculate the portion of tax included in the total fee in the same was as for products above, but the included tax is stored as included_tax on the fee adjustments itself.
`included_in_price=false` **tax rates for products** are calculated 'forwards' ie. as an addition to the base price, which is then stored in a TaxRate adjustment *ON THE ORDER*. These adjustments are an **aggregated total** for the given tax rate **across all line_items in the order**. Therefore, to my understanding there is currently no way of splitting out the added tax that applies to an individual line_item. **NOTE:** if several separate tax rates apply to the order, these are split out into separate adjustments, so the aggregated total for each tax rate applied to line_items across the order can be easily accessed (as per @myriamboure's [comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/725#issuecomment-173331889)), but the fine-grained details of the application to individual line items is not currently available. This procedure is defined by the Spree codebase.
`included_in_price=false` **tax rates as applied to fees** are currently being calculated stored as though they are `included_in_price=true` tax rates. ie. the tax is calculated backwards, rather than added, and the total tax is stored in the fee adjustment itself as included_tax. That is why we are getting the wrong values for .
The work that I did yesterday basically just copied the procedure for products: I calculated the total tax applied to the fees for each tax rate, and added that value to the aggregated adjustment on the order for that tax rate. So for my last example above, the 'included tax' figure is calculated by summing the three separate adjustments for the three separate tax rates (10%, 20% and 30%).


#### The Way We Want It To Work
Given that information, it seems that the things we want to do regardless of the whether the tax is calculated 'forwards' for 'backwards' are (from #725):
1. Show included tax in the price breakdown on the shopfront.
2. Expose a breakdown of total tax by tax rate on the cart / order summary / invoice.

For `included_in_price=true` tax rates (calculated 'backwards'), tax is calculated correctly, and everything displays as it should.

For `included_in_price=false` tax rates (calculated 'forwards'), it sounds like we need to do the following:
3. Include my fix to actually calculate the tax for fees correctly
4. Allow each shop to specify whether:
  * a) added tax is added to the price of the product / fees in the shopfront, OR
  * b) added tax is hidden in the shopfront.
5. If 4a) above then, we would obviously want to expose this information in the price breakdown on the shopfront.  

**Question:** is the fact that fees (and therefore tax rates on fees) are only applicable at the producer level likely to be a deal-breaker in the short-term for anyone? The only solutions I can see to this if it is a problem are:
  * Allowing fees to applied at the product level, OR;
  * Allowing multiple instances of an incoming supplier in the order cycle interface, which can then have different fees applied to them, which is annoying because we just pulled this out.


#### What We Need To Do
##### In order of priority (IMHO)

VERY HIGH PRIORITY
* Calculate tax on fees with 'forwards' calculated fees correctly using my fix (resolves 3. from above)

HIGH PRIORITY
* Show a breakdown of aggregate tax for different tax rates (legal requirement) in the cart, order summary, invoices, etc. (Resolves 2. from above)
* Add 'forward' calculated tax to price of products + fees in the shopfront / cart / order summary / invoices (Partially resolves 4a)

NICE TO HAVE
* Included tax is shown in the price breakdown on the shopfront (regardless of whether it has been calculated 'forwards' or 'backwards') (Resolves 1. and 5. from above)
* BtoB hubs can opt to not add tax to prices of individual products / line_items in shopfront / cart / order summary / invoice (Resolves 4. from above)

**Comment by oeoeaio** [comment]
Please continue this conversation at: http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487

**Comment by oeoeaio** [comment]
Hi @NickWeir63, @pmackay, @myriamboure 

I've created a fix to calculate tax on fees correctly when using a 'forwards' calculated tax rate. The feature branch is called `tax-on-fees`, which also includes the ability for enterprise fees to 'inherit'  their tax category as a fix for #788.

Can you test this functionality to establish that it does in fact address the issues raised here?

**Comment by NickWeir63** [comment]
great thanks @oeoeaio 
happy to test it - @pmackay  is it on staging2? or UK staging?
thanks
Nick

**Comment by pmackay** [comment]
@oeoeaio I just tried deploying and got `fatal: write error: No space left on device` on https://buildkite.com/open-food-foundation/uk-deployment/builds/26#d5bb9699-df77-4e38-a8a6-0656c4c9a780. Is that a problem with the build agent machine?

**Comment by oeoeaio** [comment]
Sounds like it! I'm sure we'll sort it out tomorrow.

**Comment by daniellemoorhead** [comment]
@pmackay did you have success deploying this for testing?

**Comment by pmackay** [comment]
@daniellemoorhead no, we have the problem that the Buildkite agent has no space (see https://buildkite.com/open-food-foundation/uk-deployment/builds/29#bfb1a614-4e69-45e1-9494-dd70687a81f3). Can anyone take a look, see how to resolve? @oeoeaio did you have a chance?

**Comment by mkllnk** [comment]
@pmackay We faced the same problem yesterday and I cleaned up some space on the server. You should be able to rebuild now.

**Comment by pmackay** [comment]
@NickWeir63 deployed ok to Staging UK just now, could you test please?

**Comment by NickWeir63** [comment]
thanks @pmackay 
@oeoeaio this looks great and the VAT is calculating correctly on UK staging - thanks for all your work on it.  I am going to ask the Stroudco manager to do some more testing on it but I would be happy for these changes to go into 1.5 if that fits with you.

**Comment by daniellemoorhead** [comment]
Great news @NickWeir63. We'll include this in v1.5, which has been delayed to next Wednesday as there are a couple of things @oeoeaio needs to do (including pushing this to production) when he gets back in the office next Wednesday. All going to plan, by the time I speak with you guys at the dev catch up there'll be a shiny new release for @pmackay to deploy onto the UK servers :)

**Comment by NickWeir63** [comment]
See Oliver's test results on [788](https://github.com/openfoodfoundation/openfoodnetwork/issues/788)
