### ISSUE TITLE
Weight (per kg) Calculator not translated

### ISSUE THREAD

**Issue by marito59** [openfoodfoundation/openfoodnetwork#774]
The OpenFoodNetwork defined weight calculator string is not translated. 

It seems that the string is hardcoded in `app/models/open_food_network/calculator/weight.rb`

How should we localise that string?

![weight not translated](https://cloud.githubusercontent.com/assets/11704159/12186100/f12bc392-b59f-11e5-9840-b698d584d698.png)

**Comment by myriamboure** [comment]
@mkllnk more generally, we have some issues with the translations in the back office. Some are wrongly translated (like this one, there is a translation but it's not correct) and some are not translated, see example here:
![non-translated-backoffice](https://cloud.githubusercontent.com/assets/8135376/12230869/75d64a3a-b853-11e5-822f-8d2ab40c7f3f.png)
I guess it's because the automatic translation from Spree works on strings that are originally from Spree, and all the things that have been customized for OFN are not automatically translated...
Anselm told me that @elf-pavlik and the Hackaton team had worked on that, so that the back office can be fully translatable. Am I right? How can we move forward on that? In France most hub managers won't speak English, so we need to be able to translate the back office as well.
Thanks :-)

**Comment by mkllnk** [comment]
Ok. The admin interface was not included in the initial internationalisation project. And it's right that the Hackathon team worked on it and made huge progress (#753). But they are not finished yet. Once they are done, we can merge it into our master branch and include it in the next release. Do you have a deadline for the internationalisation of the admin panel?

**Comment by myriamboure** [comment]
You're right @mkllnk it was not in the first step of work in the internationalisation project, and as you say the hackaton people worked on it but there is still work to do. We are waiting for some feedbacl from Pavlik as he only just reached Mexico, to talk with him about the next steps. I'm not sure there is a define deadline, it's just that for the French first beta-testers, some of them are not so comfortable with English... So it's kind a priority for the French instance, and Nicolas (https://github.com/blancnic) proposed to work on it (could we add him  as a contributor so that I can ping him?) but it needs some coordination with @elf-pavlik :-) I know @marito59 also has worked on it and says that not everything has been done at the hackaton on that matter (maybe you can share your inputs?)

**Comment by blancnic** [comment]
I'm going to identify all  translation issues  in back-office and after I will contact @elf-pavlik  to check.

**Comment by blancnic** [comment]
@mkllnk I commented #753 too. Actually, it will be easier to me to continue to work on translation when you will add commits of the hackathon . Thanks!

**Comment by myriamboure** [comment]
not relevant anymore will open other specific issue on calculator's options translation
