### ISSUE TITLE
UK push_to_staging fails if there is no change

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#779]
I ran this build https://buildkite.com/open-food-foundation/uk-deployment/builds/44#84fb34df-0dbf-465a-a1c9-de50f6948824 and it fails saying everything is uptodate. However using the `UK deployment` project the staging step needs to complete before the deploy to production stp can be unlocked.

@RohanM @mkllnk any ideas? I need to push to production to move #404 along.

**Comment by mkllnk** [comment]
We didn't think of this case. The commit you try to deploy is on the staging server already. That happens only if the push to production fails and you don't change the code afterwards. The easiest solution is to deploy another commit to staging and then the one you actually want to be staged.

The other (dirty) way would be to push to your production server manually: `git push 07d691fc:production/master` if you have the remote *production* defined.

**Comment by pmackay** [comment]
Thanks for the workarounds. Is there a scripting fix that would allow the staging step to complete successfully, even if deploying the same commit?

**Comment by mkllnk** [comment]
The last two lines of `push_to_staging.sh` are:
```sh
OUTPUT=$(git push "$STAGING_REMOTE" "$OFN_COMMIT":master --force 2>&1 |tee /dev/fd/5)
[[ $OUTPUT =~ "Done" ]]
```

I guess, if you would remove the last line, everything would be fine. But we actually want to have our builds fail in that case, because it means that we are pushing the wrong branch. That said, it actually never happens and I think that both ways have their up and down sides.

In general, I think that these CI scripts are quite specific to our CI environment and could possibly go into another repository. It would be easier for other people to change the scripts then and use their own setups. What do you think? @oeoeaio @RohanM

**Comment by daniellemoorhead** [comment]
@pmackay @oeoeaio @RohanM @mkllnk where are we at with this? Rob and Rohan, do you have any thoughts on what Maikel has written above?

(can you tell I'm reviewing all issues marked 'AU Review' in an attempt to move things to done? :smile: )

**Comment by pmackay** [comment]
Interested to know if @oeoeaio @RohanM have any additional thoughts but its possible to workaround the original problem. Might sometimes involve pushing twice which is a bit odd, but its not that big an issue. Happy to close.

**Comment by oeoeaio** [comment]
I'll defer to @mkllnk and @RohanM on this one.

**Comment by mkllnk** [comment]
Ok, I think we leave our CI scripts untouched, because they do what we want in this case. If we would like different versions of CI scripts, we could have them in a separate repository.
