### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory - touch

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#785]
Just got this when deploying to UK production:

```
remote: Doing asset:precompile:primary...
remote: rake aborted!
remote: Errno::ENOMEM: Cannot allocate memory - touch
```

@mkllnk @RohanM could you please remind me what memory level you're using on Aus server? Have any recent changes likely to have increased the precompile memory requirements?

**Comment by pmackay** [comment]
@mkllnk is it possible this is also due to the server downsize you mention in #596? I would have thought this was a memory issue on the UK prod server, so just checking...

**Comment by mkllnk** [comment]
Currently, we have 7.5GB memory on our production server and 2GB on our staging servers. Since we are doing the same asset pre-compilation on the staging server, 2GB should be enough. But we have an additional 4GB swap file on staging, 1GB on production. Do you have a swap file?

Your log file shows `remote: ` in front of the error message. That means that your production server is running out of memory, not the CI server. We downgraded the CI server only.

**Comment by pmackay** [comment]
Have resolved by increasing our prod server to 4GB.

**Comment by RohanM** [comment]
Since asset precompilation only happens occasionally and doesn't have to be super-fast, adding a swap file can be a reasonable solution that reduces the amount of memory needed for each server. But if the cost of the extra memory is negligible, having more RAM is a better solution.

**Comment by pmackay** [comment]
@RohanM Digital Ocean dont recommend swap on SSD disks though, which made me wonder if its the best way to go? From https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04:

>Although swap is generally recommended for systems utilizing traditional spinning hard drives, using swap with SSDs can cause issues with hardware degradation over time. Due to this consideration, we do not recommend enabling swap on DigitalOcean or any other provider that utilizes SSD storage. Doing so can impact the reliability of the underlying hardware for you and your neighbors.
