### ISSUE TITLE
VAT miscalculation when mixed enterprise fees added to one enterprise on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#788]
Some of the products sold through Stroudco are bought from a wholesaler and then sold through our shopfront using ‘Stroudco Food Hub’ as the producer.   Some of these products attract standard rate VAT and some are zero rated.
When we add 2 enterprise fees (one for VATable products and one for zero rated products) to the producer on the order cycle, products which are zero-rated appear in the basket with an additional 20% seems to get added to the total cost of the item, even though the product itself is zero rated and with a small amount (about 2%) of VAT under the total against "(includes tax)"  - see screenshot below
This figure should be zero
![vatable enterprise fee added](https://cloud.githubusercontent.com/assets/10517702/12495153/18966bbc-c086-11e5-97c4-e7569f6946ab.png)

**Comment by oeoeaio** [comment]
Hi @NickWeir63, the 20% added to the price of the product itself will be the enterprise fee on the producer: 'Mark-up on zero rated products'.

That added tax is a worry though. Can you replicate the issue by emptying your cart (on that page, next to the update button), and starting again? Does the same thing happen with other products?

**Comment by NickWeir63** [comment]
Hi @oeoeaio thanks for looking at this.  Yes the same thing happens with a different product when I add both enterprise fees to the 'Stroudco Food Hub' producer in the current Stroudco order cycle.  I did it from a different shopper login and with a different product this time.  This was the product I chose (master price 0.83.........
![screenshot 2016-01-22 16 30 32](https://cloud.githubusercontent.com/assets/10517702/12517047/af6fc4f0-c128-11e5-94d3-308a0c604bbc.png)
.........and this was the resulting shopping basket of 1.37 with tax of 0.06
![screenshot 2016-01-22 16 31 33](https://cloud.githubusercontent.com/assets/10517702/12517088/e91b40da-c128-11e5-89a0-31e3f85feb36.png)

**Comment by oeoeaio** [comment]
Hi @NickWeir63,

I finally understand what is going on here, and unfortunately it is the expected behaviour given the settings as they currently stand.

Contrary to your use case here, there is no correlation between the tax rates applied to fees and the tax rates applied to the products to which the fees apply. Therefore: when you add two fees to a supplier in your order cycle (as per image below), **both** fees will be applied to **all** products of the supplier, regardless of the tax settings.

![screen shot 2016-01-23 at 11 04 11 am](https://cloud.githubusercontent.com/assets/2067859/12526746/f3a985d8-c1c4-11e5-956c-62e9dab4cb8a.png)


So what is happening for BILLINGTONS Muscovado Sugar at the moment is:
Master Price: 1.29
Fee from 'Mark-up on zero rated products': (0.2 * 1.29) = 0.258
Fee from 'Mark up on VATable products': (0.44 * 1.29) = 0.5676
Tax on 'Mark up on VATable products' = 0.5676 - 0.5676/(1+0.2) = 0.0946 = 0.10
Total = 1.29 + 0.258 + 0.5676 = 2.1156 = £2.12

Note that the calculation of the tax on 'Mark up on VATable products' is incorrectly calculated backwards instead of forwards and is included in the fee total due to #773.

This matches what I get in the shopfront:

![screen shot 2016-01-23 at 11 31 35 am](https://cloud.githubusercontent.com/assets/2067859/12526745/f04c71ca-c1c4-11e5-94bf-68c99cac2295.png)

**Comment by oeoeaio** [comment]
Given the above, I think the crux of this issue is about how to allow separate sets of fees to be applied to different products from the same producer. This is bigger that just tax, there are possible use cases around applying things like packing fees to some products and not others from a particular producer.

I can think of three possible solutions:

1. Allow multiple 'Incoming' instances of a single producer in the order cycle, to allow products to be split between the instances and different fees applied to each as appropriate. eg. you could have a two Stroudco Food Hub Producers, one for VAT-able products, and one for non VAT-able products. This gets very messy very quickly though, and would require a lot of validation.
2. Allow enterprise fees to be set at the product level. I am envisioning something like the use of tags to tag VariantOverrides as having a certain fee applied for a given shopfront. This would confer the benefits of both bulk editing of fee details, while also allowing fine grained control of which products are affected by which fees. Obviously this is a significant body of work, and work require some serious scoping.
3. Allow enterprise fees to automatically use the same tax category as the product they are applied to. This could be a relatively quick fix in the short term for most of the problems we are seeing at the moment around enterprise fees and tax, but it obviously doesn't address the bigger picture stuff around fees like selectively applying packing fees (as per my example above).

I think my personal preference would be for 2 or 3, but I think this is starting to look like a bigger picture discussion that belongs somewhere else...

**Comment by oeoeaio** [comment]
Please continue this conversation at: http://community.openfoodnetwork.org/t/outstanding-tax-requirements-jan-2016/487

**Comment by oeoeaio** [comment]
Hi @NickWeir63, @pmackay, 

I've added the ability to set up enterprise fees that "inherit" their tax category from the products to which they are applied. This appears as an option that can be selected under Tax Category when creating or editing an enterprise fees. The feature branch is called `tax-on-fees`, which also includes a fix to calculate tax on fees correctly.

Would you be able to please test this feature and determine whether it works as you would anticipate?

**Comment by daniellemoorhead** [comment]
@NickWeir63 @pmackay how's this all going in terms of testing? Reckon it'll be ready to for the v1.5 release at the end of this week?

**Comment by NickWeir63** [comment]
Yes this feature works well for me - thanks very much @oeoeaio 
I would like to run it past the Storudco manager but I am happy for it to be included in the v1.5 release
Thanks everyone

**Comment by NickWeir63** [comment]
this new glitch [838 ](https://github.com/openfoodfoundation/openfoodnetwork/issues/838)has cropped up - could it be linked to the VAT changes in the code?

**Comment by NickWeir63** [comment]
Oliver has done more testing on this and found that the VAT and enterprise fee is not being added correctly.
We used a standard-rated product with a master price of £2.08.....
![screenshot 2016-02-26 10 43 13](https://cloud.githubusercontent.com/assets/10517702/13350169/65f24bb8-dc76-11e5-8389-1dbb3d9c9e40.png)
.........we set up the enterprise fee to inherit the tax category from the product and add our enterprise fee of 20%
![screenshot 2016-02-26 10 49 58](https://cloud.githubusercontent.com/assets/10517702/13350249/d4404124-dc76-11e5-9f10-025b95e4f8a3.png)
......but when we put in an order for the product it showed a price of £2.50 with tax of 48p so it has not add the enterprise fee of 20%
![screenshot 2016-02-26 10 38 27](https://cloud.githubusercontent.com/assets/10517702/13350284/11f70d0e-dc77-11e5-9f06-eb101ce878ee.png)

 the total selling price should be £3.00 (£2.08 x 20% enterprise fee x 20% VAT)

**Comment by NickWeir63** [comment]
Could this be happening because i am not able to delete the second enterprise fee - see 2nd screenshot above?
I keep getting this error message even though I have changed the enterprise fee on all the enterprises to the standard rate enterprise fee (or no fee at all).  None of the products in the order cycle use this fee that i am trying to delete...

**Comment by oeoeaio** [comment]
Hi Nick,

I think the reason you are seeing what you are seeing is that you have all of your tax rates set up as "Included in price" on your staging server.

This means that the enterprise fee of 20% is added to the base price of £2.08, giving a final price of £2.50. Included tax is then calculated backwards from this price like this: £2.50(1 - 1/1.2) = £0.41666 = £0.42 total tax.

If you change your tax rate to be NOT included in price (as per your production servers) you will get the following (expected) behaviour:
![screen shot 2016-03-02 at 11 17 36 am](https://cloud.githubusercontent.com/assets/2067859/13446538/7b7c53c0-e068-11e5-8778-84d6a4b0d9f4.png)





We are going to go ahead with a release of this code with version v1.5, if there are any bugs, we'll create issues for them against v1.6.

**Comment by NickWeir63** [comment]
Sorry Rob - well spotted
Yes good plan to go ahead
