### ISSUE TITLE
Alternative invoice: reordering of the totals

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7935]
## Description

Relates to #7892.

On the Alternative Invoice, ordering of the totals is somewhat misleading, so re-ordering these was discussed as a potential improvement (see discussion on #7892).

## Expected Behavior

@drummer83 [proposed](https://github.com/openfoodfoundation/openfoodnetwork/pull/7892#issuecomment-879112924):

  -  Total (excl. tax)
  -  Total tax (x %)
  -  Total

## Actual Behaviour

Current order:

  -  Total
  -  Total tax (x %)
  -  Total (excl. tax)

 
## Steps to Reproduce

Concerns Alternative Invoices.

## Animated Gif/Screenshot

Section to be re-ordered:
![image](https://user-images.githubusercontent.com/49817236/125654702-47e68f9b-5e8d-415a-9f6d-21a8048f162a.png)

## Workaround

None needed. Just not clear.

## Severity

bug-s4: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.8
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by drummer83** [comment]
Thanks @filipefurtad0 for creating all the issues!

I think it is important to mention that the reordering only makes sense for instances with "added tax" (as stated in #7892). For instances with "included tax" the current order is fine and changing it would be a regression. See examples below.

BUT: My understanding is that instances with "added tax" use the regular invoice and instances with "included tax" use the alternative invoice. So in real life we don't have this problem it only occurs in testing, when we are looking at all possible combinations of tax variants and invoice variants.

Usually I am crazy about details, but I tend to vote for closing this one because it not an issue in production. Will ask on Slack if there are instances using "added tax" plus alternative invoice.

**Added tax (US & CA): CONFUSING** (Strange calculation + wrong headers)
![grafik](https://user-images.githubusercontent.com/1790176/125680462-5bc864a6-8e4e-47f9-b441-57a5194afda6.png)
This is confusing because the numbers above the line don't add up to the first number below the line.

**Included tax (FR, UK, DE, ...): OK**
![grafik](https://user-images.githubusercontent.com/1790176/125680538-45204c67-848d-458a-b652-4a759de513c6.png)
This is ok, because the numbers above the line add up to the first number below the line.

**Comment by filipefurtad0** [comment]
Thanks for this really useful feedback @drummer83 ,
I'm happy we're looking at this in detail.

- So, only instances with **added tax** AND using the **alternative invoice** (none currently) would see this - not an issue in production, the invoice type is not suitable for these instances.

- Changing the parcel order for instances with **included tax** AND using the **alternative invoice** (FR, UK, DE) is undesirable.

Agree: lets close this :+1: 

It's interesting to note that some instances with **included tax** do use the **regular invoice** (AU) which displays a different parcel order (seen in #5591):

![image](https://user-images.githubusercontent.com/49817236/125930200-d0d810c9-4e5e-41e8-bfd6-4152efa191e7.png)

This makes it easier to sum the GST parcels.

So, I guess keeping these differences between the two invoice types is intended, and gives flexibility to the instance to decide what's best.

So, and again, thank you for your feedback - closing.
