### ISSUE TITLE
Slug error message by clicking checkout button

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7952]
## Description

From this Slack thread:
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1626697578362000

What's known: Users getting the snail error, when clicking the checkout button, after they've had items in the cart for a few days.

~~Reported from IE, but this bugsnag error could be related - in UK 3 occurrences, all since last release:
https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/60f0a3613fe69e00099f737f?event_id=60f0a361007f90b4214f0000&i=sk&m=nw~~

## Expected Behavior

Clicking the checkout button should lead to the `/checkout` page

## Actual Behaviour

Users with items in the cart are getting the snail when clicking checkout button.

## Steps to Reproduce

WIP

1.
2.
3.
4.

## Severity

bug-s2?

## Your Environment

* Version used: v3.8.5
* Browser name and version: ?
* Operating System and version (desktop or mobile): ?

**Comment by cillian** [comment]
The bugsnag error `ie` got for this issue is `Cannot transition state via :restart_checkout from :payment`

The error occured a few times on the same hub for two of their hub managers, it hasn't occured for shoppers yet.

I found an older issue #4005 which has the same error message.

![restart-checkout-error](https://user-images.githubusercontent.com/101088/126214023-bd241920-87cf-49f3-a093-2b0ccb91b32d.png)

**Comment by filipefurtad0** [comment]
Thanks for adding more context and the Bugsnag error @cillian. This seems to have happened in other instances as well:

- DE: on an instance manager account as well
https://app.bugsnag.com/yaycode/open-food-network-germany/errors/60f017f135470b000720e50d?filters[user.id][0]=1726&pivot_tab=event

- FR: Error marked as solved:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1625604721169600
@rachel do you think we are good to downgrade the severity?

**Comment by andrewpbrett** [comment]
As fas as I can tell, this is happening because we're attaching an invalid address to an order as part of the `before_address` method on the CheckoutController

https://github.com/openfoodfoundation/openfoodnetwork/blob/40abefa9084a9c003a5eeb63ad9d7161451dd0fb/app/controllers/checkout_controller.rb#L137-L144

But it seems like that would only happen if the AddressFinder returns an empty address. This can happen if it returns the `fallback_bill_address`, which can return `Spree::Address.default`, which is basically a blank address with only the country filled in. 

https://github.com/openfoodfoundation/openfoodnetwork/blob/40abefa9084a9c003a5eeb63ad9d7161451dd0fb/lib/open_food_network/address_finder.rb#L68-L70

https://github.com/openfoodfoundation/openfoodnetwork/blob/40abefa9084a9c003a5eeb63ad9d7161451dd0fb/app/models/spree/address.rb#L25-L32

**Comment by Matt-Yorkley** [comment]
I've just been reviewing this in Bugsnag and I can't see it happening in France or UK. There's a coupe of cases of it occurring on DE, but they were two weeks ago and haven't happened since. I'll keep looking...

**Comment by Matt-Yorkley** [comment]
There's no cases of this error in the last month on AU, Katuma, CA, US, or BE. The couple of cases that occurred 2 weeks ago on DE were a single user on a single day. We made a few different improvements around payments in the last 3 releases, I'm pretty tempted to conclude this is actually fixed already...

**Comment by filipefurtad0** [comment]
Thank you for double checking this @Matt-Yorkley , let's close it then and re-open if needed.

**Comment by filipefurtad0** [comment]
Reopening, as it was reported to happen again [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1630352883006900?thread_ts=1626697578.362000&cid=CG7NJ966B).

**Comment by andrewpbrett** [comment]
There's a potential solution in https://github.com/openfoodfoundation/openfoodnetwork/pull/8233 - however, there are some failing specs, since it's modifying the AddressFinder which is used in other parts of the codebase. 

The reason this is happening, I believe, is that the CheckoutController makes some assumptions about orders having a valid bill_address and ship_address when the checkout restarts. Given that we're in the process of rewriting a lot of this logic as part of the split checkout anyway, and also that this is happening pretty rarely, I would propose that we close this and say it will be fixed when split checkout is finished, rather than spending a lot of time working through the test failures and making sure that there are no unintended consequences in other parts of the codebase (especially since the failures are related to subscriptions).
