### ISSUE TITLE
Confirmation message to cancel order not displayed correctly in french 

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8016]
## Description

From Administration > Order > Edit (on an order) > Cancel >
A confirmation message box with three errors is displaying : 

"**E**tes vous sur de vouloir **Annulercette** commande ?"

<img width="1335" alt="Capture d’écran 2021-08-06 à 15 48 55" src="https://user-images.githubusercontent.com/67476305/128520280-1ee3f1c0-5562-4bb3-b4a0-e3946dd49fee.png">

" 

## Expected Behavior

Same behavior with corrected message : 
"**Ê**tes-vous sûr de vouloir **a**nnuler **(space)** cette commande"

## Steps to Reproduce

1. Administration
2. Order
3. Edit an order
4. Cancel

**Comment by jibees** [comment]
As I can see, this one is (at least partially) managed with Transifex, like most of our wording.

 - The missing space is also missing in Transifex. Thus, this one should be easily fixed by instance/i18n manager.
 - The capital letter on the 'a' is also something that we could fix in Transifex, but it's maybe used elsewhere. I should check deeper this one.

**Comment by jibees** [comment]
The `Annuler` wording (under the key `spree.actions.cancel`) is used quite a lot elsewhere and should not be changed as it certainly needs its capital letter.
Thus, it requires some code to remove the capital letter on the action label (if we want to do so).

**Comment by Cecilia-Hn** [comment]
Ok, thanks a lot for the transiflex link. 
I don't think we need to remove the capital letter.
