### ISSUE TITLE
[Spike] Investigate our Stripe Integration

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8074]
## Description

We've been having a continuous run of Stripe related S2s since we switched to SCA. It is really causing a lot of strife to our support teams and to our users who are very aware that they are losing sales.

It seems likely that in the migration to SCA we implemented Stripe incorrectly. This spike is intended to deep dive into our Stripe integration to try and understand if we can improve.

## Expected Behavior

Stripe payments should work reliably 99.9999% of the time outside of user error.

## Actual Behaviour

Frequent failed payments, missing orders and general errors, seemingly related to asynch checks.

## Severity

Assigning S2 as this is intended to be a super issue over the existing steady flow S2s. As a spike we simply want to understand the scale of the work required to repair our stripe integration and the probability of reducing the frequency of issues.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Related Issues and Conversations
[Slack post on #bugs](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1628610531007600)
https://github.com/openfoodfoundation/openfoodnetwork/pull/7809
https://github.com/openfoodfoundation/openfoodnetwork/issues/7767
https://github.com/openfoodfoundation/openfoodnetwork/issues/8019

**Comment by mkllnk** [comment]
:+1: 

I find this a very helpful assessment with important next steps. I've been advocating for VCR for a while but never had the time to actually implement it. It actually speeds up development because you don't have to come up with mock data, it's automatically captured from the real test API.

**Comment by lin-d-hop** [comment]
@andrewpbrett this is great to read (sorry for the long delay)

I agree that improving active merchant and tests could be priorities - should be classed as tech debt.

What about[ this suggestion from Cillian](https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1628610531007600) - is this relevant?

**Comment by andrewpbrett** [comment]
Thanks @lin-d-hop. I think @cillian's suggestion is intended to solve the issue of "Paid orders that aren't appearing in the system", which I think we've tracked down to a combination of #8090 and https://github.com/openfoodfoundation/openfoodnetwork/issues/8143#issuecomment-918153640. So while we could set up listening on that webhook, it would take some time to set up correctly (in fact it might require each instance manager to configure something) and essentially just be a double check at this point. Unless we continue to see payments taken on Stripe but not marked complete in OFN, I'd recommend we hold off on listening to that webhook.

I'll close this spike since I think all of the remaining actions have their own issues and/or PR's.
