### ISSUE TITLE
Setting up a promotion makes the platform crash when editing cart

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#810]
We want to use the "promotion" feature to allow those who come help with packing etc get a discount on their orders.

I create a promotion:
![promotion](https://cloud.githubusercontent.com/assets/8135376/12853935/1db50a38-cc37-11e5-9f0d-b0a6cca7eff2.png)
The promotion is created without any problem.

But then when I go to any order cycle on the instance and put products in the basket, and click on "edit cart", got grumpy cat.

I go back to the promotion and delete it, go back to order cycle, no grumpy cat.

**Comment by myriamboure** [comment]
@NickWeir63 do you already use the promotion finally?

**Comment by lin-d-hop** [comment]
my understanding is that promotions are currently not used and currently breaks lots of things. 

will link to enhancements currently being developed to solve this issue when at my computer.

**Comment by myriamboure** [comment]
Ok, thank you @lin-d-hop :-) Ping @sigmundpetersen for info.

**Comment by lin-d-hop** [comment]
Hi @myriamboure 
We're planning to use this functionality to give discounts to volunteers/members/wholesale customers etc.
http://community.openfoodnetwork.org/t/wholesale-and-tagging/505

It is different to a promotional code type arrangement, which at some point would probably be useful.

Do you think you can use tagging for what you need? It is currently in the Aus work flow to be completed this month if all goes to plan.

**Comment by myriamboure** [comment]
Thank you @lin-d-hop, will look at it quickly then!

**Comment by sstead** [comment]
Hi all, just noting that we've had a further request from a user here for promotional codes. They are a large farmers's market running pre-sales for Christmas. There's been some small errors made by admin (accidentally listing items for $0) and the best way to fix them is to ask the customer to place their order again, but they'd like to waive the admin fee for that customer. For larger users who need to maintain their reputation with customers, it's important that they have promo tools as a way of ensuring customer satisfaction. Using the OFN can be a reputation risk for them otherwise, if they don't have adequate tools to keep customers happy.

**Comment by lin-d-hop** [comment]
I suspect this is another issue that might be hinged on spree upgrade and potentially tax overhaul. I'd like to see this in the pipeline but my sense is it's best to hold back a wee bit.

**Comment by lin-d-hop** [comment]
Closing at this is a feature that will need prioritising etc
