### ISSUE TITLE
BOM: Deleting last item (trash-bin icon and selecting/deleting) leads to an empty order

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8131]
## Description

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/7627
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/7637
Follow-up from https://github.com/openfoodfoundation/openfoodnetwork/pull/8040

Please note that this bug can be addressed together with #7637 or separately.

There were **two missing scenarios** which led to empty orders as well; while on the BOM it is possible to delete the last item of an order by:
-  clicking the trash-bin icon
-  selecting one or more items and deleting via the global action button "Delete Selected" (#7637)

## Expected Behavior

**Updated**

Clicking the trash icon or selecting on last item of an order and using the "Delete Selected" button:
- should **display a modal text** similar to the one implemented by #8040 but changing the text to "deleting this item will cancel the order as it is the last line item, do you wish to proceed: yes/no".
- selecting "yes" should **cancel the order** -> changing the order status to `cancelled` and shipment status to `none` 

## Actual Behaviour

While on the BOM it is possible to delete the last item of an order by clicking the trash-bin icon and by selecting one or more items and deleting via the global action button "Delete Selected"

## Steps to Reproduce

As admin:
1. Visit `/admin/orders/bulk_management`
2. Click the trash-bin icon to delete the last item of an order 

## Animated Gif/Screenshot

![Peek 2021-09-03 09-16](https://user-images.githubusercontent.com/49817236/131973760-5554cf66-5236-453a-97e8-cd16851766f5.gif)

## Workaround

- Edit the order and add items back to the order (reverses the deletion and makes the order accessible to the custumer)
- Manually cancel the order on the respective order edit page

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.0.1
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

See Expected Behavior section.

**Comment by RachL** [comment]
@filipefurtad0 thanks for opening the issue 🙏 

My 2 cents:

- Proposal 1 is mine so I won't comment :D 

- Proposal 2: If we go with this option I think we need a text somewhere explaining why the button does not appear for some orders otherwise people will just contact support. 

- Proposal 3: I did proposal 1 because I find it a bit annoying for a user that has a lot of orders in this case to be prevented to do an action. If they really want to delete the item, they need to 1. click on the modal to close it 2. click on the button to edit the order - but they need to think about opening the page in a new tab to avoid loosing all the filters they have used on the BOM page and 3. Cancel the order.
When you are a big hub with let's say 20 orders in this case, it makes a lot of steps...

**Comment by filipefurtad0** [comment]
Thanks for feedback! Updated the issue accordingly.

**Comment by filipefurtad0** [comment]
>when multi-selecting orders and deleting via the global action button 

This is issue https://github.com/openfoodfoundation/openfoodnetwork/issues/7637

**Comment by RachL** [comment]
Canada is having some issues with the fact that cancelling orders sends an email to the customers. They are about to create an issue for this. We need to be careful in which order we will merge the PR.

**Comment by guidoDutra** [comment]
@RachL I saw the piece of code that does that, it probably won't cause any conflcts with my PR :) I could also pick that up depending on how it goes
