### ISSUE TITLE
Enable UK Offering Different trial length to enterprises

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#814]
Enterprise trial length is hard coded on the Enterprise model at 30 days. UK would like to be able to offer 6 month trials.
Proposal: To enable setting the enterprise trial length from the SuperAdmin Config -> Business Model.
This would mean 
1) adding Spree::Config[:default_enterprise_trial_length]
2) modifying the Business Model Configuration to allow trial to be set here.
3) Testing enterprise invoicing
Looks like all calculations that need to trial length and expiry refer to Enterprise.SHOP_TRIAL_LENGTH so hopefully this will be reasonably straight forward.

Also, to fit with UK business model, we need to update so that enterprises can have a minimum turnover before being charged enterprise fees. Similarly:
1) adding Spree::Config[:default_enterprise_turnover_without_fees]
2) modifying the Business Model Configuration to allow the allowed turnover before fees to be set here.
3) Testing enterprise invoicing

@oeoeaio Can you think of things that might go wrong in these proposed changes?

**Comment by oeoeaio** [comment]
Nope, that generally sounds fine to me.

I would suggest that you remove "default_" from the beginnings of the suggested global config variable names, because these are not defaults, they are just the names of variables (which have defaults). I would also suggest that shop_trial_length is more indicative of what is happening than enterprise_trial_length. Also worried about the use of 'fees' to describe the billing of enterprises (could get confusing) could we make the name of the second variable something like minimum_billable_turnover or something?

First job should be fairly straight forward. I think substituting the constant on enterprise for the global config variable should work just fine.

Second job may get a bit tricky, but just be rigorous in speccing out all possible combinations of settings (by following the lead of the existing specs) and you should be fine.

**Comment by myriamboure** [comment]
@lin-d-hop I think the instance should be able also to determine if they want to offer a trial period at all. I don't know if that's already in what you wrote ;-)
For example in France, we might have a business model based on "volunteer commission", which means that the platform would basically be free but each hub would define the % they want to give us on a volunteer/consicous based (and we would make it transparent for the end customer). We have not yet defined how we would like that to work, but that means we should also be able to remove the trial period :-)

**Comment by oeoeaio** [comment]
Good idea @myriamboure. Also, I have done some thinking about how to implement individualised "plans" (custom trial periods, customs rates etc) for enterprises, so I'd love it if you could ping me if/when you start a new topic :)

**Comment by lin-d-hop** [comment]
Hi @myriamboure Just so you know, in this implementation the enterprise can set the number of trial days to 0, which fits your request :-)

**Comment by myriamboure** [comment]
Great! Thank you @lin-d-hop :-)

**Comment by daniellemoorhead** [comment]
@mkllnk are you able to have a look at this for @lin-d-hop and give any thoughts/comments?

**Comment by oeoeaio** [comment]
Nothing to add. 😄

**Comment by lin-d-hop** [comment]
Merged.
