### ISSUE TITLE
Additional reports to help Stroudco

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#817]
These requests are copied from old issue 318
1)Stroudco would like to have a report showing the total number of orders so far in the current order cycle?
2) Stroudco would like to  have a report showing which producers have confirmed orders for their products in the current order cycle?
3)Stroudco would like to have a report showing how many confirmed shopper orders in the current order cycle?
5) Stroudco would like to have a report showing of the current order cycle's confirmed orders how many are to each shipping method
6) Stroudco would like to have a report showing for the current order cycle's home delivery orders:name, shopper number, address, postcode, delivery instructions (provided by the shopper) and phone number.
7)Stroudco would like to see special instructions typed by the shoppers early on (before the food drop). Could these show up on all the shopper listing reports?

**Comment by lin-d-hop** [comment]
Hi @NickWeir63 
1) If you use the delivery report  mid order cycle it will show this information
2) Pack By Supplier should show this mid order cycle
3) Pack by Customer should show this mid order cycle
5) You can filter the delivery report to show this for each shipping method, albeit one at a time. Will this suffice?
6) This is the delivery report
7) Will this suffice in the delivery report, which can be seen mid order cycle? Otherwise is there a particular report you are referring to?

Thanks @NickWeir63

**Comment by NickWeir63** [comment]
Yes sorry - I will close this
