### ISSUE TITLE
Integrate Payment Gateway that supports payment mapping

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#824]
Mangopay and Stripe allow setting up complex payment relationships to minimise the work of hubs. 
Both facilitate a marketplace, so a single customer payment can automatically split between hub fees, supplier 1 to supplier x.

This diagram demonstrates well:
https://docs.mangopay.com/marketplace-workflow/

This will be a major plus for many CSA style operations that would like to diversify but can't justify extra accounting work to do so. 

ping @myriamboure

**Comment by myriamboure** [comment]
Thank you @lin-d-hop, yes, I think that's a must have at least in the French context.
I'm not sure yet wether we can offer that as an option for a hub, or if it needs to be for the whole platform. I'm trying to contact them but didn't get an answer so far.
At least it's pretty sure that a hub who would choose that payment system won't be able to offer another option as a side...
I'll let you  know when we move forward on that.
This issue is connected to that discussin as well: http://community.openfoodnetwork.org/t/generating-a-compilation-of-one-invoice-per-producer/513/2

**Comment by lin-d-hop** [comment]
Technically they could but it would cause them an accounting nightmare and would need a whole series of special reports to support. I agree it would be best to disable all other payment methods if direct payment mapping via stripe or mangopay was enabled...

This will be a very complex feature to develop and would require a large amount of funding. It's cold in the icebox :-)

**Comment by daniellemoorhead** [comment]
Have taken this out of the icebox given it's become [a topic of conversation again on Discourse](http://community.openfoodnetwork.org/t/ofn-norway-backlog/463/13).

**Comment by RachL** [comment]
As this conversation is happening on Discourse, I'm closing it here.
