### ISSUE TITLE
 Snail when editing non-numeric characters on enterprise fees

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8250]
## Description

In all things similar to #6942 and #8249, but concerning enterprise fees.

Updating an enterprise fee can cause a server error when entering invalid values.

## Expected Behavior

Invalid values should not be allowed or there should be a proper error message.

## Actual Behaviour

It shows the snail.

## Steps to Reproduce

1. Edit an enterprise fee.
2. Select the "per item" calculator.
2. Enter `'20.0'` with the single quotes as fee amount.
3. Click Update.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used: v4.1.2
* Browser name and version: Firefox 92
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

The only figures that should be allowed are:
- numbers 0123456789
- decimal point .
- negative sign -

The error message should read:
Invalid input. Please use only numbers. For example: 10, 5.5, -20

See [PR which introduces a fix](https://github.com/openfoodfoundation/openfoodnetwork/pull/8204) for a similar issue, regarding transaction fees.

**Comment by drummer83** [comment]
Looking at Filipe's comment in [#8308 ](https://github.com/openfoodfoundation/openfoodnetwork/pull/8308#issuecomment-948772358), I think this was closed by accident. I can confirm, that there are still some snails to fight.

### Summary
Payment methods are covered in #7841 and have been fixed in #8204, only weight calculator is still triggering the snail.
Shipping methods are covered in #8249 and have been addressed in #8312, but incomplete - should be reopened.
Enterprise fees are covered in #8250 and have been addressed in #8308, but incomplete - should be reopened.

### Things left to do in this issue
This is the current status of the calculators:
- flat percent --> OK
- flat rate (per order) --> snail
- flexible rate --> snail
- flat rate (per item) --> snail
- price sack --> snail
- weight (per kg or lb) --> snail

**Steps to Reproduce**
As an Admin:
- edit an enterprise fee
- choose one of the calculators marked with "snail" above
- click update
- type in an invalid value (e.g. some text or numbers with comma as separator)
- click update --> snail

I am reopening, but let me know if I am wrong.

**Comment by RachL** [comment]
Unless I'm wrong PR https://github.com/openfoodfoundation/openfoodnetwork/pull/8308 has fixed this. closing.

**Comment by drummer83** [comment]
You are wrong. :wink: 
See https://github.com/openfoodfoundation/openfoodnetwork/pull/8308#issuecomment-948772358.
Reopening.

**Comment by RachL** [comment]
ok thanks, what was confusing is that this was in progress on the welcome new dev board

**Comment by vsmay98** [comment]
Hello @filipefurtad0 @drummer83
Can I work on this issue?

**Comment by drummer83** [comment]
Sure @vsmay98! I have assigned it to you.
Maybe worth looking at the linked issues and their pull requests (if any).
Have fun! 😉
