### ISSUE TITLE
Product load speed still too slow on Stroudco shopfront on UK production (stage 2)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#828]
Following on from the work done in stage 1 (#713):

- Make "add out-of-stock item to cart" experience nicer
- Add refresh time notices to admin flash messages
- Add DJ info to admin dashboard

**Comment by daniellemoorhead** [comment]
Work to start on this in release v1.6, however will be delivered as part of v1.7

**Comment by NickWeir63** [comment]
thanks @daniellemoorhead - what does this mean in terms of timing for us to do testing on UK staging?

**Comment by daniellemoorhead** [comment]
Hi @RohanM would you be able to provide an update on how this is tracking for the UK team? I've got a session with them on Thursday evening, so would be great to get an update before then. Thanks!

**Comment by RohanM** [comment]
Hi everyone,

Here's where I'm up to on these tasks:

- Adding out of stock items to cart - I've solved all the hard problems on this task (fingers crossed), and just need to work through bringing everything together. Probably another half day's work after today.

- Delayed job info on dashboard - I've been working on this same problem on the CERES FairFood website, and I've worked out some patterns there that I can bring across to OFN. That should make this task significantly quicker than anticipated.

- Refresh time notices - The purpose of this task was to explain to admins that some of the changes they make might take some time to appear on the shopfront. However, it might be the case that the changes show up quickly enough that there's no need for those messages. I'd like to hold off on this one until (and if) we've tested the system and deemed them necessary.

**Comment by RohanM** [comment]
Another status update:

- Adding out of stock items to cart - Looks like adding out of stock items to cart is a bit more complicated than I expected, and there should be about a day's work from here. Estimated completion end of this week or mid next week.

- Delayed job info on dashboard - I estimate the solution described above should take 2 hours.

**Comment by NickWeir63** [comment]
We now have a timeline for switching Stroudco over to OFN:
23rd April - food hub as normal
27th April - orders close for the last time on old system
30th April - last food hub on old system
7th May - NO FOOD HUB
8th May - orders open on OFN for food hub on 14th May
14th May - first food hub on new system

As part of this we are asking a few regular shoppers to put in dummy orders.  This is some of the feedback we have had so far:
1) "OFN seems quite resource heavy and as I mentioned before, I find it hangs a lot. I'll try and remember taking a screen recording tonight - that's the time when it's a problem. In the morning, when I must be the only one online in most of Bussage, it's not so bad. "

2) "Last night I had a try at entering an order, but got locked out with a message about a long running script.  But managed to place the order this morning though"

@lin-d-hop is this something that we could cure with a server upgrade?

**Comment by RohanM** [comment]
Hi everyone,

This is all finished, but in the process I ended up going over my estimated time for this task. Here's a brief retrospective.

The main task related to this was: when a product has gone out of stock while a customer is shopping, we want to notify the customer and reduce the quantity in their cart. This has always been an problem, but is now doubly important because a side-effect of our caching system is that customers are somewhat more likely to encounter it.

When I looked into it, I found that the simple solution I had initially been considering would not provide a satisfactory user experience, and that the task was more technically complex than I had anticipated. In an ideal solution, we needed to communicate the stock availability between the server and the client, and when an item was reduced in stock, we needed to inform the customer and update their cart without reloading the page. To implement a more cut-down version of this experience risked confusing the customer. Due to the complexity here, my work ended up taking longer than my initial estimate.

Another factor that contributed to this was scope creep. While working on the shopfront and the cart, I addressed a few related issues (ie. #377) as it was efficient to deal with them at the same time. As my time on these tasks was logged along with the rest of this work, it contributed to exceeding my estimate, since this work wasn't considered during estimation. However, this work will contribute to a better functioning and less confusing shopfront, group buy and cart interface.

That's a bit of an overview of the project. I'm happy to answer any questions. Thanks for your support and my apologies for time over.

**Comment by NickWeir63** [comment]
Thanks for all your work on this @RohanM and it sounds like the extra work you had to do has been really useful in other ways so I am cool with the over-spend - we are building an even more awesome OFN that will benefit us all in the future.  Thanks
