### ISSUE TITLE
Update County List with more familiar names and 3 letter abbreviations

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#836]
From: Francis Priestland [mailto:fp26@st-andrews.ac.uk] 
Sent: 24 February 2016 16:35
To: nick@openfoodnetwork.org.uk
Subject: No Herefordshire

Hihi Nick,

Thanks for fixing our issues last time. One of our customers has noted that you are missing Herefordshire on the list of counties for the UK addresses.

Ta,
/F

**Comment by rhodri** [comment]
Here's the list of counties used in deployment: https://github.com/openfoodfoundation/l10n_gb/blob/master/states.yml

**Comment by pmackay** [comment]
There is a question of what is "correct" and what is typically searched for by users. "County of Herefordshire" is the correct name I think (ref http://opendatacommunities.org/doc/geography/administration/ua/E06000019). But am guessing most people would just look for Herefordshire.

**Comment by lin-d-hop** [comment]
I think we could be intuitive about this. 'City of Bristol' is hard to find in a drop down when looking for 'Bristol'. Likewise with 'County of Hereford'.
The other thing to note is the 3 letter abbreviations. These should also be intuitive rather than strictly correct in my opinion.
I get that this is a fluffy spec, apologies for that. However we've all spent enough time filling in online forms to have a good idea. In fact other online forms could be a good reference if you get stuck.

**Comment by lin-d-hop** [comment]
Merging issue with #360 and closing that one.

**Comment by NickWeir63** [comment]
i am happy to help with defining the final list of counties if that would help.

**Comment by pmackay** [comment]
Actually the ref I gave above lists it as "Herefordshire, County of", which presumably would put it in the right order. And I reckon OpenDatacommunities run by DCLG is a good reference ;) So would that be a better way to name it? Same could be true for the cities, e.g. "Bristol, City of"

**Comment by lin-d-hop** [comment]
Merged so closing.
@NickWeir63 @FiferMags in future if people say their county was missing off the list make sure you get the exact details of the county they are looking for so we can try make it more intuitive in our file. Thanks :simple_smile:
