### ISSUE TITLE
[flaky spec] /system/admin/order_spec.rb:192

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8449]
### What we should change and why (this is tech debt)

`rspec ./spec/system/admin/order_spec.rb:192 # `

```

   1) 
    As an administrator
    I want to create and edit orders
 creating a new order with a variant override creates order and shipment successfully and allows proceeding to payment
     Failure/Error: expect(page).to have_content "Customer Details updated"
       expected to find text "Customer Details updated" in "Logged in as : darcey@dach.ca Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS ENTERPRISES CUSTOMERS Order # R547728802 Customer Details ACTIONS BACK TO ORDERS LIST xxx xxx - CUSTOMER SEARCH Choose a customer 2 errors prohibited this record from being saved: There were problems with the following fields : Bill address state can't be blank Ship address state can't be blank ACCOUNT EMAIL: BILLING ADDRESS FIRST NAME: LAST NAME: STREET ADDRESS: STREET ADDRESS (CONT'D): CITY: ZIP: COUNTRY: Australia Australia STATE: New South Wales Victoria PHONE: SHIPPING ADDRESS USE BILLING ADDRESS UPDATE ORDER INFORMATION STATUS CART TOTAL : $3,888.50 ORDER DETAILS CUSTOMER DETAILS ADJUSTMENTS PAYMENTS"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_create_and_edit_orders_creating_a_new_order_with_a_variant_override_creates_order_and_shipment_successfully_and_allows_proceeding_to_payment_595.png

```
     
     # ./spec/system/admin/order_spec.rb:228:in `block (3 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:38:in `block (2 levels) in <top (required)>'

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/1421815933/attempts/1

**Comment by mkllnk** [comment]
I just ran this on my machine and had a 50% failure rate.
![failures_r_spec_example_groups_as_an_administrator_i_want_to_create_and_edit_orders_creating_a_new_order_with_a_variant_override_creates_order_and_shipment_successfully_and_allows_proceeding_to_payment_562](https://user-images.githubusercontent.com/3524483/145508656-d59f4c66-1a99-47da-bd26-7ddd72e22d41.png)

**Comment by mkllnk** [comment]
I think I found the problem.
https://github.com/openfoodfoundation/openfoodnetwork/blob/4be0536b186c842badd694700d961d0d6d76b990/spec/system/admin/order_spec.rb#L222-L223
After selecting the country, there's Javascript loading the states of that country and replacing the options in the next input. If we select the state too early then it gets cleared.

Options:

* Not select the country because it's already selected. Simple and quick. The spec won't be as explicit though.
* Wait a second after selecting the country. Quick and dirty but this can still fail.
* Disable the state input while the API call is in progress. That will make the spec wait until it's available. It's also better feedback for the user who could accidentally do the same if they had a slow connection.
