### ISSUE TITLE
Missing translation: card validations on the checkout form

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8488]
## Description

Card validation errors on the checkout form are not translated. This concerns:
- card number invalid
- card number incomplete
- card expired

## Expected Behavior

UI validation errors should appear translated.

## Actual Behaviour

UI validation errors are not translated.

## Steps to Reproduce

1. Add some items to the card
2. Proceed to **checkout**
3. Type:
- an incomplete card number: 4242 4242 4242 424
- a complete but invalid card number: 4242 4242 4242 4241
- a complete and valid card number: 4242 4242 4242 4242 and a past expiration date

or
4. log in and visit `/account#/cards` 
5. Repeat step 3.

## Animated Gif/Screenshot

![Peek 2021-11-15 15-20](https://user-images.githubusercontent.com/49817236/141807277-e1127dd1-4217-439d-9ff1-fb61a0b5226b.gif)

## Workaround

S3

## Your Environment

* Version used: 4.1.7
* Browser name and version: all
* Operating System and version (desktop or mobile): all

**Comment by Matt-Yorkley** [comment]
So I think the issue here (and maybe with some other small Stripe bits) is that these strings are not actually in our codebase, they're coming from Stripe. I'm pretty sure it's possible to pass a locale to Stripe to tell it to use a different language, like "FR" but we'd need to skim the docs to see how to do it. Also it might be slightly different with this form (which goes through Stripe.js) and some of the other bits which will go through the Stripe API.

**Comment by prathits012** [comment]
Hi, As a new member to open source, I am wondering if I can take this issue as it was tagged as a good first time issue.

**Comment by jibees** [comment]
@prathits012 : sure, feel free to ask here if you have any question! Thanks. 🙏
