### ISSUE TITLE
Enterprise user can require login for their shopfront and display messages to users not logged in

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#849]
http://community.openfoodnetwork.org/t/wholesale-and-tagging/505/14

Estimate = 1 day

**Comment by mkllnk** [comment]
@sstead and @oeoeaio: I need a bit more detail about this. Obviously, the products should not show without a login. But what about these:

- list of order cycles
- order cycles closed message
- custom shop message

Should they be shown?

**Comment by oeoeaio** [comment]
Hi @mkllnk ,

I think we want the following:
  * Order cycles dropdown disabled
  * Show a new message that tells the user the need to login (login_required_message or something)
    * I think this should look exactly like the order cycles closed message in terms of its location on the page, but the login message should always take precedence.
  * this would mean that the custom shop message would never get rendered on the page for shops that require a login unless of course the user is logged in

Does that make sense?

**Comment by mkllnk** [comment]
Okay, so we have the following order:

1. require login message
2. order cycles closed message
3. custom shop message

Sounds good.

**Comment by mkllnk** [comment]
@oeoeaio: I got this ready, but there are two annoying things. The displayed message is this one:

> Please [Login](/login) if you have an account already. Otherwise, [Register as a New User](/register) to become a customer. 

The link *Login* takes you to a new page and after the login you are at the homepage, not at the shop. The Login button in the menu works differently. It's more complex markup with an Angular controller that acts if you click the login-button there. I could replicate the code for the displayed message, but
 - a) the Login link is within i18n text. That requires to squeeze all the HTML code into a variable that is then passed into translation.
 - b) we would end up with duplicate code.

That's why I left the simple link to `/login` there. Should we make a new task to simplify the login code so that you can embed it easily into text? I think it would be nice if we could still use a helper like `link_to(t('login'), login_path)` and an Angular directive would pick up the link and make it act like the current login button in the menu.
