### ISSUE TITLE
Placing order from backoffice: product search gives results in random order and hub managers lose time

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#8507]
## Description
When a hub manager make an order for a customer from backoffice, they have to search for a product before adding it to the order. For that they type the first letters of the product. The problem is that for products with many variants starting with the same letters, the products are rendered in different order each time, without any reason. So the hub manager spends time for each new order to search again where is the product, there is no logical order in the way products are shown.

## Expected Behavior
When I start typing in the search box, products are shown in alphabetical order

## Actual Behavior
When I start typing in the search box, products are shown in random order

## Steps to Reproduce
1 Go to orders / new order / select a distributor and OC. Make sure you have some products with multiple variants whose names start the same way, like "Bread - wheat 1kg", "Bread - wheat 2kg", "Bread - spelt 1kg", etc.
2. Start typing "Brea" and see the result.
3. Redo the process again and see the result. Order has changed without reason.

## Animated Gif/Screenshot
![capture d ecran de 2018-07-12 23-30-45](https://user-images.githubusercontent.com/8135376/42660541-c9f0dace-862b-11e8-9f5a-0c738ef23c1c.png)
![capture d ecran de 2018-07-12 23-31-54](https://user-images.githubusercontent.com/8135376/42660544-cbc04862-862b-11e8-8fbb-868ef03d20fd.png)

## Context
A hub reported that bug, it is a bug that works with some people who are very bad with internet so still do some orders for them. They get very annoyed to have to go through the list of products without having any logical way to search.

## Severity
S4

## Your Environment
* Version used: V1.15
* Browser name and version: Mozilla
* Operating System and version (desktop or mobile): Ubuntu 18.

## Possible Fix
When start typing display resultats in alphabetical order?

**Comment by jibees** [comment]
I've tested and try to reproduce the issue. It seems that the issue is resolved: when searching variants through this interface (via `/admin/variants/search.json`) the variants are _always_ returned with the same order. 
@filipefurtad0 if you have some time, could you please confirm that this issue is already resolved?



**_For the record:_**
<img width="355" alt="Capture d’écran 2021-12-02 à 10 31 49" src="https://user-images.githubusercontent.com/296452/144395183-6908bf79-248e-4789-9b9f-0266069eb5eb.png">

<img width="307" alt="Capture d’écran 2021-12-02 à 10 28 10" src="https://user-images.githubusercontent.com/296452/144395219-4636d7ac-b5f9-42c2-997a-fbd0ad52d640.png">

<img width="307" alt="Capture d’écran 2021-12-02 à 10 27 59" src="https://user-images.githubusercontent.com/296452/144395230-6ce8162a-fcd1-46b7-8ade-53d65168f5a7.png">

<img width="299" alt="Capture d’écran 2021-12-02 à 10 27 48" src="https://user-images.githubusercontent.com/296452/144395247-49c8649b-ba67-4e79-accb-df57c8a90353.png">

**Comment by Matt-Yorkley** [comment]
They are ordered by id, but the id is invisible to the user in this context, right? So it will appear random in that sense, if they can only see the product names?

**Comment by jibees** [comment]
You're right but I thought the issue was about that the order changed _between_ each search, this is something I cannot reproduce. But you're right, we could order by `name asc` ;)

**Comment by RachL** [comment]
> we could order by name asc

Yes please :)

**Comment by jibees** [comment]
> > we could order by name asc
> 
> Yes please :)

Will do then ;)
