### ISSUE TITLE
Order not possible from client account 

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8524]
The 6255 user tried to order from his account in the 940 shop.
The user add : 
+ his details 
+ billing informations 
+ Shipping informations 
+ Payment informations (payment at the delivery)

After "Place order now" button selection, the client couldn't finalize his order cause this following error message appeared : **"Payment could not be processed, please check the details you entered"** 

![image](https://user-images.githubusercontent.com/67476305/143576494-975cc21f-6bf3-4249-ac33-0d7e404c7f0a.png)

In the past, the 6255 has ordered 9 times. 

I connected on his account and I tried to ordered with the same result
We ordered on the 940 shop from 3 other accounts and orders were placed.

**Comment by RachL** [comment]
I'm raising as s2 to at least understand the problem, and be able to reproduce it.

**Comment by jibees** [comment]
I tried to understand/debug a bit this issue, but it can have sooo many origins since the error message `Payment could not be processed, please check the details you entered` (key `payment_processing_failed`) seems to be the default one and be used every time a payment failed. 
I've found: 
 - if no specific message found and any other error occurs
 - if payment capture failed
 - if no _source_ specified

I don't know in which case we are, wondering if this is not the first (most generic one)
