### ISSUE TITLE
Saving cards in Stripe

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#8579]
## Description

There are two ways to save cards to be used at checkout:
- Via /accounts
- While checking out

It seems that the two methods use different aspects of the Stripe API to handle them. There are many mysterious issues that arise in subs causing failed payments even when there is a valid card in Stripe (eg #8534 #7785) that appear to be related to this.

We need to explore:
- saving new cards
- setting the default card
- adding a new saved card and changing the default (eg when a card expires)

## Acceptance Criteria & Tests

1. Provide issues and estimates to ensure that saving cards and updating the default card is consistently and accurately handled via checkout and /accounts
2. Understand how this will impact existing subs users. The ideal scenario (that we should aim for in our issues) is that existing subs users can continue their automatic subs payments without any action required
3. Understand the impact for users now that are saving their cards in one part of the system (eg /accounts) and wish to use this card in another (eg checkout). Also vice versa (saving at checkout and using in subs)

**Comment by Matt-Yorkley** [comment]
Dev notes: when we save cards in the /account page, we use the Stripe Tokens API, but when we save them at checkout we use the Stripe PaymentIntents API. There's a discrepancy there; they work differently. The /account page is where we have the UI for adding cards for subs and allowing them to be used for future payments. I'm not even sure we should be using the Tokens API, but I would need to investigate more. 

The Tokens API docs say a token can only ever be used once. On the other hand, when we save a card via the checkout I'm not sure we also explicitly set it up for future payments (eg subs).

It needs some investigation!

**Comment by mkllnk** [comment]
Matt said:

> I'm not even sure we should be using the Tokens API, but I would need to investigate more.

Stripe clarifies:

> Tokenization is the process Stripe uses to collect sensitive card or bank account details, or personally identifiable information (PII), directly from your customers in a secure manner.
> ...
> Tokens cannot be stored or used more than once. To store card or bank account information for later use, you can create [Customer](https://stripe.com/docs/api#customers) objects or [Custom accounts](https://stripe.com/docs/api#external_accounts).
> ...
> These tokens can be used only once: by [creating a new Charge object](https://stripe.com/docs/api/tokens/create_card#create_charge), or by attaching them to a [Customer object](https://stripe.com/docs/api/tokens/create_card#create_customer).

So once we created a customer object, we can use that repeatedly. But I also saw mentions of Stripe Payment Method objects and I'm not sure if we forget to associate them or if that's done automatically somewhere.

**Comment by mkllnk** [comment]
More from the docs:

> A PaymentIntent guides you through the process of collecting a payment from your customer. We recommend that you create exactly one PaymentIntent for each order or customer session in your system. You can reference the PaymentIntent later to see the history of payment attempts for a particular session.

I guess that we use one payment intent for several checkouts. That's allowed but not recommended.

When the customer stores a card, we confirm it with Stripe and make sure that a payment method is associated. It can associate a payment method object automatically. That path should be safe.

I spent an hour just reading docs and our code now. Before we investigate more, I would suggest the following actions:

- Improve Stripe testing with real API responses via VCR or Puffing Billy. We have a lot of complex code around and it's easy to break things.
- Nothing seems obviously wrong but the code complexity is high. We should try to reduce that and replace the AngularJS code at the same time.
- File each subscription failure with the following details if possible:
  * When was the card stored initially?
  * How was the card stored?
  * How often has it been charged since?

**Comment by lin-d-hop** [comment]
Created wishlist: https://github.com/openfoodfoundation/wishlist/issues/215
We also have a checkout rewrite in play
And improved stripe testing has been written up

Closing
