### ISSUE TITLE
Customer account debited twice after first order attempt failed

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8618]
**R705164323** is a complete order on 961 shop on the 7th november (FR Prod) 

<img width="1268" alt="Capture d’écran 2021-12-14 à 12 45 11" src="https://user-images.githubusercontent.com/67476305/145992359-a5954cdf-71b3-45dd-b962-4101cc0b9df7.png">

It seems that, the customer account has been debited twice 
 * Spree Order ID: R148537147-Z8QMW6E
 * Spree Order ID: R705164323-E29YM8DN

The hub reimbursed manually one of the debits to the customer, from the Stripe application, on the 7th november 
* Spree Order ID: R148537147-Z8QMW6E

R148537147-Z8QMW6E
<img width="808" alt="Capture d’écran 2021-12-14 à 12 49 25" src="https://user-images.githubusercontent.com/67476305/145992961-0f19e2cb-854b-465b-84f5-5032a94f11b4.png">

R705164323-E29YM8DN
<img width="776" alt="Capture d’écran 2021-12-14 à 12 49 33" src="https://user-images.githubusercontent.com/67476305/145993025-42c1acdf-d168-4313-978f-e55a59bc4f17.png">

I hope I well understand what happened, the customer has informed the hub after consulting his account.

I wish I'm wrong but if its happened, like [8608](https://github.com/openfoodfoundation/openfoodnetwork/issues/8608) issue, this event created a real problem of confidence between customers, users and us.

**Comment by RachL** [comment]
I'm closing here I think this is the same case as https://github.com/openfoodfoundation/openfoodnetwork/issues/8618 commenting over there

**Comment by RachL** [comment]
Ok so for a brief moment I thought I would close this in favor of https://github.com/openfoodfoundation/openfoodnetwork/issues/8608 but maybe those are 2 different cases.

The chronological scenario : 

- customer tries to checkout and checkout attempt fails. ON records an order in cart state. Stripe pursue the payment. So hub has to manually reimburse on the Stripe UI. https://coopcircuits.fr/admin/orders/R148537147/edit and

![image](https://user-images.githubusercontent.com/6525576/146028185-966f0e33-b988-4d50-a0df-14eade532306.png)


- customer tries to checkout again. This time it works: https://coopcircuits.fr/admin/orders/R705164323/edit All good

My conclusion: what's not good is that OFN did not complete the order on the first trial.

What happens when a customer closes their browser after authorizing? Could this be what happen? If you don't wait to be properly re-directed to OFN no completed order? ping @openfoodfoundation/testers
