### ISSUE TITLE
Minimum order value as a property

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#873]
We set up a minimum order product property for Audacious Veg (producer shopfront) of £50 and another minimum order property for their chard of £40 (see screenshot) but when we put an order through for £25 (order R073502278) it was accepted

![minimum order property](https://cloud.githubusercontent.com/assets/10517702/13982884/51cd12e4-f0e4-11e5-8916-a8faf02a26e9.png)

**Comment by lin-d-hop** [comment]
I am pretty sure this is not the actual purpose of the property fields. If you look how they are used by the Aus team it is for the labelling of things like 'PastureFed' or 'Organic' or 'Fictional Natural Sounding Production Method'.
See: https://openfoodnetwork.org/user-guide/advanced-features/product-properties-i-e-certified-organic-free-range-etc/

Therefore this is not actually a bug. This is an enhancement request.

It has been mentioned on discourse:
http://community.openfoodnetwork.org/t/how-important-are-these-features-to-you/368

New discourse thread opened here such that we can spec out the functionality a little more. I think there is more complexity. Here:
http://community.openfoodnetwork.org/t/minimum-orders/542

Also removing the property on UK production because it is misleading.

**Comment by NickWeir63** [comment]
thanks Lynne - all good
