### ISSUE TITLE
When deleting a line item, make returning to on-hand stock optional

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8767]
## Description

Suppliers on OFN are usually anticipating stock availability when they set up OCs. Product is still in the field. So it is often the case that their hopes did not materialize and sold products have to be removed from orders because they weren't available, or were of poor quality, etc. 

When a manager (producer's own store, or a hub they supply) removes a product from an order today, it automatically returns to stock 'on-hand' in their product list, or to inventory (if a stock over-ride is being used). This makes the unavailable product available for sale again. 

This is a problem when: 
(1) the supplier or hub is managing a very large product list so its easy to 'miss' this returned stock, 
(2) the supplier is selling in multiple order cycles open at the same time or in close sequence.

**- As a:** enterprise user
**- On page:** `/admin/orders/RXXXX/edit`
**- I want to be able to do:** 
When removing a line item from an an order I see a checkbox (checked by default) with a message like "Restock Items: return this item to stock". 
When cancelling an order I see a checkbox (checked by default) with a message: "Restock Items: return all items to stock". 

## Acceptance Criteria & Tests

_Scenario 1 : the OC is linked to an inventory_

1. As an enterprise user, I delete a line item from an order
2. I see a new check box on the modal
3.  If I check the checkbox, only inventory gets re-stocked (unless inventory is set to "use producer stock info", in which case stock is not updated)
4. If I uncheck the checkbox, stock is not updated.

_Scenario 2 : the OC is linked to an inventory_

1. As an enterprise user, I cancel an order
2. I see a new check box on the modal
3.  If I check the checkbox, only inventory gets re-stocked (unless inventory is set to "use producer stock info", in which case stock is not updated)
4. If I uncheck the checkbox, stock is not updated.

_Scenario 3 : the OC is only linked to product catalog_

1. As an enterprise user, I delete a line item from an order
2. I see a new check box on the modal
3.  If I check the checkbox, the product catalog gets re-stocked
4. If I uncheck the checkbox, stock is not updated.

_Scenario 4 : the OC is only linked to product catalog_

1. As an enterprise user, I cancel an order
2. I see a new check box on the modal
3.  If I check the checkbox, the product catalog gets re-stocked
5. If I uncheck the checkbox, stock is not updated.

**Comment by jibees** [comment]
This one should be started once https://github.com/openfoodfoundation/openfoodnetwork/pull/8766 is merged, because it's potentially on the same part of code, and could trigger conflicts.

**Comment by georgethoppil** [comment]
@RachL just wanted to know your thoughts on the popups. 

When we have multiple items in the cart and I delete an item, my pr currently has this show up: 
<img width="600" alt="Screen Shot 2022-03-28 at 7 46 04 PM" src="https://user-images.githubusercontent.com/45666083/160505868-25ec9cce-2efd-4db9-9126-f9427cb10095.png">


When there is only one item left and we try to delete it, there will be two pop ups that will present itself, one that asks about restocking the item as well as another about sending an email to notify the customer that the order will be cancelled (#8766). I figured why would we want to show a pop up twice and instead show them just one popup with multiple options like so: 
<img width="578" alt="Screen Shot 2022-03-28 at 7 45 44 PM" src="https://user-images.githubusercontent.com/45666083/160506102-9fd1b8d6-c71c-415e-808b-82e057ac0b0b.png">

Similarly for the cancel button located on the top right here: 
<img width="1078" alt="Screen Shot 2022-03-28 at 7 26 13 PM" src="https://user-images.githubusercontent.com/45666083/160506152-b7e10a6e-6119-47c8-8913-ee58594974fe.png">

my thinking here is to also present the same popup with the multiple selections ie. restock and email to customer. I figure if we are going to cancel the order, those would be nice things to have instead of just the plain are you sure popup. Let me know what you think about it

**Comment by RachL** [comment]
hello @georgethoppil yes you are absolutely right!  It's better to have only one pop up with the different options.

Regarding the cancellation button I agree too. However if it is really a lot more work maybe we can create a second issue for that one? Let me know what you prefer.

**Comment by georgethoppil** [comment]
> hello @georgethoppil yes you are absolutely right! It's better to have only one pop up with the different options.
> 
> Regarding the cancellation button I agree too. However if it is really a lot more work maybe we can create a second issue for that one? Let me know what you prefer.

Sweet thanks for the quick feedback. I have the changes done already in the pr for the cancellation button, so I should be good to go 👍
