### ISSUE TITLE
Add a "processing" icon to the edit order cycle page.

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#881]

**Comment by oeoeaio** [comment]
@bingxie: just wanted to let you know that I have done the work of adding the Save Bar to the Customers page as part of #933.

**Comment by bingxie** [comment]
@oeoeaio Thanks, could you tell me what't the branch you are working on?

**Comment by oeoeaio** [comment]
https://github.com/oeoeaio/openfoodnetwork/tree/customer-ui-improvements

**Comment by sstead** [comment]
The Save Bar is covering the cancel button in the simple OC only...
![image](https://cloud.githubusercontent.com/assets/10843056/15171084/05c5293c-178f-11e6-995d-6d690699dd95.png)

There is an inconsistency in how the buttons behave in the two OCs...
![image](https://cloud.githubusercontent.com/assets/10843056/15171247/5416a470-1790-11e6-92eb-e367e406d081.png)

I think I like the buttons staying red, because then you don't have to click cancel to leave the page after you make changes.

**Comment by bingxie** [comment]
Very good feedback! I did a little bit change to add back the 'Cancel' button. And keep the update buttons red.
![screen shot 2016-05-12 at 11 05 51 am](https://cloud.githubusercontent.com/assets/1144652/15201184/90ebccda-1831-11e6-8b50-12c036e15179.png)
