### ISSUE TITLE
Customer and admin unable to change password/email due to billing address 'error'

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#8959]
## Description

User with ID 358 raised issue they couldn't reset their password and were getting the error message that 'billing address phone number cannot be blank' when trying to reset:
![image0 (1)](https://user-images.githubusercontent.com/100226210/156741307-a7610f9c-69dc-4e5f-91e2-264ece89cd0c.png)
They had not placed an order before, so had never entered billing details.

As admin I tried to change their password and received the same error. I tried adding the user as a customer, with a completed dummy billing address, and this did not fix the issue. I also tried changing their email address as a delete account workaround, which also triggered the same error. Both user and admin are therefore unable to access the account.

## Expected Behavior

Customers who have never placed an order should not be getting billing address errors. Billing address errors should not prevent changes to account details.

## Actual Behaviour

Trying to change account details (e.g. email/reset or change password) should be possible regardless of if there are errors in the billing address.

## Steps to Reproduce

1. As admin, go to user ID 358 and enter a dummy password, click update
2. Error is triggered as in below screenshot

## Animated Gif/Screenshot

<img width="500" alt="Screenshot 2022-03-02 at 19 32 12" src="https://user-images.githubusercontent.com/100226210/156764713-0b3bf127-4e5e-4ad7-9531-a810846e8778.png">

## Workaround

No workaround possible using the existing email so I am suggesting the customer create a new account (with a google alias if they have no other email address possible).

## Severity

bug-s3: a feature is broken but there is a workaround
Whilst this isn't affecting multiple users, it is a serious issue preventing a user from using OFN at all and currently the only workaround is to create an entirely new account.

## Your Environment

* Version used: UK prod
* Browser name and version: Occuring for user on safari and myself on Chrome Version 98.0.4758.80 (Official Build) (arm64)
* Operating System and version (desktop or mobile): Occuring for user on iPhone & myself on Mac Big Sur 11.6.2

**Comment by BethanOFN** [comment]
I've now got another user, this time an enterprise owner, with this issue who is unable to log on. They had also tried resetting their password, which did not resolve the issue. I am unable to change their password/'delete' their account as admin also:
<img width="553" alt="Screenshot 2022-03-25 at 10 29 12" src="https://user-images.githubusercontent.com/100226210/160103968-9bc8e997-c1a7-43b3-9c99-2b77054c0948.png">

**Comment by jibees** [comment]
I tried to reproduce this one, and it seems that is not that easy to reproduce. 
This case seems to work (at least on my local setup):
 - create / confirm a new user
 - once new user is confirmed, fill the "Forgot password?" form
<img width="494" alt="Capture d’écran 2022-04-01 à 15 22 00" src="https://user-images.githubusercontent.com/296452/161271977-8d594132-d77f-4e08-87a4-b676bc70f071.png">
 - you receive an email, with a link to reset the password:

> Votre demande de nouveau mot de passe a bien été prise en compte.
Si vous n'avez pas demandé de nouveau mot de passe, veuillez ignorer cet e-mail.
Si vous êtes bien à l'origine de cette demande, veuillez cliquer sur le lien ci-dessous :
http://0.0.0.0:3000/user/spree_user/password/edit?reset_password_token=Ea8YjYcEgmTkTsHeshVw
Si le lien ne fonctionne pas, essayez de le copier - coller dans la barre d'adresse de votre navigateur.
Si le problème persiste, n'hésitez pas à nous contacter.
 
 - the form is well submitted, and password is changed:
> Votre mot de passe a bien été modifié. Vous êtes maintenant connecté(e).

Do you have any insights on how I can reproduce this one? Thanks! 🙏 

(sorry for the french i18n...)

**Comment by BethanOFN** [comment]
See bugsnag for one user: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61ae0d07c9511a0007ca4779?filters[event.since]=30d&filters[error.status]=open

**Comment by filipefurtad0** [comment]
No idea how this is happening. To my knowledge, the `/customers` page is the only place where one can edit that field, and this for could use some more testing. But since these are first time customers, this is probably not the root cause.

It's weird, because phone bill address only becomes relevant after orders are placed... It seems that 118 does have an order in the cart state (R836836684), but 358 has none. So, no idea on the root cause.


However, for both for user `358` and `118` we can see that the phone info is indeed empty:

```
openfoodnetwork=> select phone from spree_addresses where id = (select bill_address_id from spree_users where id = 358);
 phone 
-------
 
(1 row)
```

```

openfoodnetwork=> select phone from spree_addresses where id = (select bill_address_id from spree_users where id = 118);
 phone 
-------
 
(1 row)
```

So, one possible workaround to unblock these users would be to update the DB and attribute a number to these users. I think this should be safe (famous last words :sweat_smile: ). What do you think @lin-d-hop @BethanOFN ?

**Comment by lin-d-hop** [comment]
Sure, I'd be happy to manually update the DB to correct the problem to unlock things for these users. But it will come back if we don't find the root cause. What is the appropriate DB update? Bill_address should be able to be null, are there other users with a null email address that this might be happening for?

So why is this suddenly happening? Is it the case that bill_address have a non-null constraint? Does that mean that this will be happening for any user that tries to update the email address when they have created a cart but not completed an order?

Hopefully'll have some clues in the Stacktrace on bugsnag (linked above) :crossed_fingers:

**Comment by jibees** [comment]
Some thoughts:
- agree on the fact that the DB workaround is actually a _workaround_. So, we must investigate on that.
- I don't see any error for user 358 in bugsnap, but I see 118 and 514. As I'm a bugsnap newbie, what I'm missing? https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61ae0d07c9511a0007ca4779?filters[event.since]=all&filters[error.status]=open&pivot_tab=user.id
- @filipefurtad0 I'll ask for help on how I can browser DB (access, ssh, ...)
- Will try to investigate this data model... (😱)

**Comment by filipefurtad0** [comment]
> But it will come back if we don't find the root cause.

Yes, totally agree Lynne. It just occurred to me as a potential solution to unblock these two users.

From the stacktrace I was so far not able to understand why the `phone` field is empty on `spree_addresses`-> this is the actual offense but becomes a problem only if `bill_address_id` is not null on `spree_users`.

Happy to help somehow JB :muscle:

**Comment by jibees** [comment]
There are 865 users that have an empty phone on their bill_adress:

```
openfoodnetwork=> select count(*) from spree_addresses, spree_users where spree_users.bill_address_id = spree_addresses.id and  spree_addresses.phone is null;
 count
-------
   865
(1 row)
```

**Comment by jibees** [comment]
I tried to pass an order with an existing order, and no bill_address are registered for a spree_users (but with customer)

**Comment by jibees** [comment]
One things very strange, is that all those users have been created _at the same time_ by a script (or so) in 2015 (`2015-04-18 15:36` and `2015-03-31`). 



For the record 
```
select spree_users.id, spree_users.bill_address_id, spree_addresses.phone, spree_users.created_at, spree_users.updated_at from spree_addresses, spree_users where spree_users.bill_address_id = spree_addresses.id and  spree_addresses.phone is null order by spree_users.created_at desc;
```

**Comment by lin-d-hop** [comment]
Interesting. And super weird. 
We did import users in 2015 to UK prod. But why we suddenly getting multiple occurances of this now I have no idea.

I would be happy with either solution. I guess the second has more potential consequences?

**Comment by jibees** [comment]
Here are the list of the last users with bill_address with phone number as null order by `last_sign_in_at`: 
```

**Comment by jibees** [comment]
I'd vote for that migration. Maybe add a fake phone number to those consumers?

**Comment by jibees** [comment]
_**Investigation**_:
There is no constraint in the database level:
```sql
CREATE TABLE public.spree_addresses (
  id bigserial NOT NULL,
  ...
  phone character varying(255) NULL,
  ...
);
ALTER TABLE
  public.spree_addresses
ADD
  CONSTRAINT spree_addresses_pkey PRIMARY KEY (id)
```

Constraint is handled in a application level, by `app/models/spree/address.rb`
```ruby
validates :address1, :city, :country, :phone, presence: true
```

This could be addressed with a one-commit modification, but probably a _nightmare_ to test all the cases where a phone number is entered for an Address (bill address, shipping address, enterprise address, ...). 
I guess in term of UI/UX, we decide to **not change** the global behavior, ie. _Phone number is mandatory_ for an address?
Therefore, I'm not sure I'd be totally happy with this kind of solution: this means we decorolate the UI from the codebase and I guess it's not  
I'd invoke for @mkllnk advice.

**Comment by mkllnk** [comment]
### Why do we get these errors now?

As @jibees found, there are only a few users and they didn't log in often. So the occurrence is rare. And before October 2021, the phone field was not validated.

- #7973
- #6243

Thanks to `git blame` and Github's links from commits to PRs I could find this.

### What is the long-term fix?

We could make phone number non-mandatory but many people want phone numbers to be mandatory. Since this problem is only occurring with old invalid data, let's fix that up. @jibees suggested a fake phone number. I would suggest to delete invalid billing addresses. A user is not required to have a billing address. They just need to enter it again, with phone number, when they check out. That's clearer than having a random phone number appearing on the checkout page or your invoice.

**Comment by jibees** [comment]
>I would suggest to delete invalid billing addresses. 

Sounds perfect. Thanks @mkllnk

**Comment by lin-d-hop** [comment]
Ping @apricot12 in case you hadn't seen this.

**Comment by apricot12** [comment]
> Ping @apricot12 in case you hadn't seen this.

Shall I try the migration for removing addresses without phone numbers?

**Comment by lin-d-hop** [comment]
> > Ping @apricot12 in case you hadn't seen this.
> 
> Shall I try the migration for removing addresses without phone numbers?

I think its in hand, but perhaps ask @jibees. I just meant that its worth clocking Maikels findings above as it related to some of your changes a while back. Not a problem, the main cause was a corrupt data import years ago... but I feel like its useful to note the curly consequences to improve future foresight.

**Comment by jibees** [comment]
@apricot12 I'd be happy if you want to tackle this one ;)

**Comment by apricot12** [comment]
> 

Sure! I'll do it today.

**Comment by filipefurtad0** [comment]
Maybe good to keep in mind that `phone number` is not a mandatory field when registering an enterprise:

![image](https://user-images.githubusercontent.com/49817236/164743005-91907e0e-f46a-4c9c-b913-b7920d6e211e.png)

**Comment by apricot12** [comment]
> 

Hmm I think I might have to edit the migration a little bit then. Currently it simply deletes all spree_addresses with NULL phone.
