### ISSUE TITLE
Customer unable to access private OC with correct tagging

### ISSUE THREAD

**Issue by Renatacumming** [openfoodfoundation/openfoodnetwork#9002]
## Description
Customer Ben (user_id: 18665) shops at Timbarra Farm. Weekly customer since October 2020
Timbarra Farm uses Tagging to create private Order Cycles. 
The account's email address has been tagged correctly (farm-pick-up & yarra-junction) to access private order cycles and successfully placed weekly orders until late February.
Timbarra Farm runs three private order cycles:
-Yarra Junction
-Healesville
-Restaurant
Ben should be able to see 'Yarra-Junction' Order Cycle shop. When 'Yarra-Junction' OC is open, Ben can only sees 'Orders Closed' message that relates to the previous 'Restaurant' OC 
Ben has never been tagged in 'Restaurant' OC

Ben previously used email address ...@hotmail.com, stopped using this email address November 2020, Helen removed all tags from this email address, and added tags to new email address ...@email.org.au

@mkllnk unlinked the two email addresses, waiting for customer to test if this has solved issue.

## Expected Behavior

Customer logs in using email address ...@email.org.au
Private order cycle becomes visible (through correct tagging)
Customer places order

## Actual Behaviour

Customer logs in using email ...@email.org.au
Customer sees Order Cycle closed message
Customer cannot access shop to place order

## Steps to Reproduce

1. Create user with tags to access private order cycle
2. Place order in private order cycle
3. Change email address in account settings, place new order
4. Remove tags from old customer record
5. Try to place new order without updating new customer record

Following above steps, the bug was not able to be reproduced, the expected behaviour happened, whichever customer record and email address had the correct tags, they could access the shopfront. Immediately after changing the email address the shopfront could be accessed, but upon trying incognito window the shop could not be accessed until the new email address had tags added to the customer record. Once the customer record for the new email address had tags added, the shopfront could again be access as expected. 

## Workaround

Not tested: Give the old customer record the same tags as the new one.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
Initially on mobile device (owned by customer Ben)
Recreated on computer by different person (Helen, Timbarra Farm owner, used Ben's email address and password and experienced same issue as Ben)

## Possible Fix
@mkllnk unlinked the two email addresses, waiting for customer to test if this has solved issue.

The customer record lookup may need to include the email address to avoid fetching an old record. Alternatively, we could update the customer record instead of creating a new one after a user changed their email address.

**Comment by lin-d-hop** [comment]
This issue is more likely to be an issue with changing the email address of a user, rather than tagging.
There have been other issues with changing email addresses eg https://github.com/openfoodfoundation/openfoodnetwork/issues/8959

@Renatacumming can you update when you know if Maikels workaround has worked or not?
Downgrading to S3 until then.

**Comment by Renatacumming** [comment]
Update: Timbarra Farm owner Helen has ben able to gain access, leaving bug open until next week to make sure that the customer can also gain access and place order before closing bug.

**Comment by Renatacumming** [comment]
Customer Ben has now placed 5 orders since this bug was investigated and it is solved for Ben.

**Comment by tschumilas** [comment]
So -  by 'user' we mean someone who has registered on the platform -  is that right?  And customer might be a user and use their login at checkout.   But  a customer is someone who has not registered on the platform and chooses 'guest' at checkout.

So in the case above -   this person started as a guest I suspect and placed their first order that way.  Then,  they registered as a user,  and the manager added them to the hub's customer list,  and tagged them.   At least I think thats the history.   But today,  as a user,  they cannot log in to this private shop.   Their login shows up in super admin users list.  They are correctly tagged.

It seems like they are 'stuck' as a guest,  and can't be tagged  (or something...)

**Comment by tschumilas** [comment]
Have discovered the following -  not sure if its the same or different issue than this....
First  -  a hub was set to allow guest checkout.   And some customers purchased as 'guests' and did not create logins.   Then the hub changed their setting,  and now requires registered users.   For new customers -  no problem -  they register ....   BUT I've identified 3 customers,   labelled as 'guests' in the hub's shop,  who purchased as guests.   I've registered these logins -  and the users can login and see their OFN account,   and they can shop in other OFN shops....   BUT they cannot reliably access the private shop that now requires registered users.    These customers are able to shop once in each new order cycle -  and then if they try to access the private shop again,  they cannot access it.   So they are like 'partial guests'.

**Comment by mkllnk** [comment]
Yes, sounds like the same issue.

**Comment by mkllnk** [comment]
They can not log in? That's weird. Maybe they need to switch to another shop first...

Can you share some user ids for testing?

**Comment by tschumilas** [comment]
Login is successful. She can access any shop.  She can access her account...     But  she can't access a private shop that uses tags.  Tagging doesn't 'work' (my technical description) with the guest-stuck login.  I've redone tags - doesn't matter.  I've done tags in a different shop - doesn't matter.  User 418  login is:  'hello@smellslikeflowers.com'   The user doesn't want to use a different login because this is a wholesale shop and she wants everything in the same account she used last year.....   For now,  the hub has removed tagging to this shop and I will cancel any inappropriately placed orders on the backend.   But gosh,  it would be good to figure this out.

**Comment by mkllnk** [comment]
Looking into this, I found a different problem. Some customers have duplicate entries:
```
-- Australian production data
select cc.id, substring(cc.email, 0, 7), cc.user_id, cc.enterprise_id, cc.created_at from customers join customers as cc on customers.id!=cc.id and customers.email=cc.email and customers.enterprise_id=cc.enterprise_id;
  id  | substring | user_id | enterprise_id |         created_at         
------+-----------+---------+---------------+----------------------------
 5449 | alynda    |         |          2018 | 2018-08-31 03:47:32.530956
 5448 | alynda    |         |          2018 | 2018-08-31 03:47:32.510732
 5678 | bernad    |         |          2208 | 2018-10-29 10:49:23.079164
 5677 | bernad    |         |          2208 | 2018-10-29 10:49:20.812769
 6020 | bonnie    |         |          2246 | 2019-01-25 22:52:08.112406
 6019 | bonnie    |         |          2246 | 2019-01-25 22:52:07.924796
 6276 | deb.ch    |         |           693 | 2019-03-19 04:11:51.854624
 6275 | deb.ch    |         |           693 | 2019-03-19 04:11:51.770636
 7095 | merylm    |         |          2331 | 2019-08-05 07:28:21.085602
 7094 | merylm    |         |          2331 | 2019-08-05 07:28:20.973593
(10 rows)
```

This shouldn't be allowed but some race condition must have allowed this at some point. I'll try to fix this at the same time.

**Comment by jibees** [comment]
I re-re-read the issue and the thread, and actually, I think I don't understand what's the issue here, and what we are trying to resolve here ;) 
I _followed_ the steps to reproduce, and I cannot reproduced exactly. So, to start, just a quick question:

> 1. Create user with tags to access private order cycle

By user, you mean customer (linked to a user?) right? I don't see any interface for a User to add a tag, but I found for a Customer:

<img width="1411" alt="Capture d’écran 2022-09-12 à 10 43 29" src="https://user-images.githubusercontent.com/296452/189610720-6a95a5de-6461-45f9-84dd-88a25a0c32e8.png">

**Comment by RachL** [comment]
@jibees yes we can only tag customers, but instance managers call them users :+1:

**Comment by jibees** [comment]
0. I've configured an enterprise with OC accessible via tagging:
<img width="716" alt="Capture d’écran 2022-09-12 à 10 57 28" src="https://user-images.githubusercontent.com/296452/189613723-9fdb5ccf-aa91-4a84-a8ec-f0178107c7f2.png">
<img width="760" alt="Capture d’écran 2022-09-12 à 10 57 49" src="https://user-images.githubusercontent.com/296452/189613796-007ab2c9-75af-4a9e-b5cf-4d6cfcad3b13.png">

1. I created a user + added correct tag to its customer (linked by email address I suppose)
2. I placed an order with the private OC
3. I've changed the email of the user, via its interface (`account`)
<img width="870" alt="Capture d’écran 2022-09-12 à 10 58 47" src="https://user-images.githubusercontent.com/296452/189614041-03aae3a4-8270-4689-955e-052d41b9c94a.png">

<img width="916" alt="Capture d’écran 2022-09-12 à 10 59 02" src="https://user-images.githubusercontent.com/296452/189614019-689a8301-f7af-4e62-b845-39efc9243e8f.png">
4. I removed the tagging of the _old_ customer:
<img width="1136" alt="Capture d’écran 2022-09-12 à 10 59 51" src="https://user-images.githubusercontent.com/296452/189614265-2e962035-7e0a-445f-8976-21de9c6c3c3f.png">
5. User has then no access to the _private_ OC

To my opinion, a confusion is due to the interface that shows the customer : we think it's the old one, since it's the old email address. I think it's actually the current one, and the email address is not updated to the customer record. 

My proposition (if my comprehension is correct): update email field for the customer record to reflect the email of the user which the customer is linked to.

**Comment by RachL** [comment]
@jibees I could be wrong, but it looks to me as if the S2 was not anymore on the problem when changing email address, but rather on CA's problem.

Again if i understood clearly the list of comments, here are the (supposed) way to reproduce (haven't had time to test myself) : 

- a hub is open for everyone
- a guest user places an order
- the hub changes their settings to private and taggs all users who should be able to order. That means they are tagging guests users
- Guest users create themselves an account
- they can shop everywhere except the hub the used to shop to, even if they have the proper tagging.

**Comment by mkllnk** [comment]
Thank you for reproducing one way to trigger this issue. There may be many ways but the result is that we have several customer records for the same user. Our code assumes only one record though and chooses the first one (which can be random depending on database ordering). And then it appears random which tags are applied. As a result, access to private shops or discounted shipping methods are not available and it's very confusing for everyone.

**Comment by mkllnk** [comment]
I'm currently working on a related issue with duplicate customer entries: https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:openfoodnetwork:9002-customer-association

Once that pull request is ready for review, I will start addressing the issue around changing email addresses or signing up after being a guest customer.
