### ISSUE TITLE
Cannot remove customers from customer list

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#9039]
## Description
The user guide currently says that an enterprise can add or remove customers from their customer list.  Currently I am unable to remove a customer from my customer list.  

## Expected Behavior
An enterprise should be able to remove a customer from their customer list by clicking the delete icon beside that customer's login on the /admin/customers page.

## Actual Behaviour
Clicking to remove a customer prompts the error that the customer has orders associated with that shop.
This happens even if orders are paid.  I happens when an order is cancelled. 

So -  a customer that needs to be removed,  can never be removed,  because they will very likely have previous orders with the shop.an error.  

## Steps to Reproduce
visit a customer list for a shop & try to remove a customer.

1.shop at a shop to be added to the customer list for that shop
2.as enterprise manager - try to remove the customer.
3.
4.

## Your Environment

* Version used: OFN-CAN - latest
* Browser name and version: Chrome - latest
* Operating System and version (desktop or mobile): desktop,  windows

**Comment by jibees** [comment]
@openfoodfoundation/train-drivers-product-owners 
Should you show this modal (and prevent customers deletion) only if the customers have order in _insert appropriate order state here_?
We also can improve the modal in some way, like, add a link to the customer's current orders?

**Comment by lin-d-hop** [comment]
I think if a shop wants to remove a customer from their customer list this should impact the customers ability to place future orders. I don't think state of past orders is important from the user perspective. 

The purpose of the customer relationship is for the manipulation of the shoppers future experience, particularly through the use of tagging. Any past experiences are less relevant to my mind.
 
To me there are a few options:
1. Hard delete the customer - the 'customer id' field in the orders table for that customer is updated to be null.... are there other consequences to this?
2. Semi hard delete the customer - can we remove the relationship between a customer and a user in an effective way so that the customer id still exists but there is no link between the customer and the user and the customer no longer appears in an enterprises customer list?
3. Soft delete the customer - essentially hide the customer from the customer list and remove all tags and associated information specifically related to the customer so that the customer no longer has any of the benefits of being a customer. Note that in this case we need to ensure that if the enterprise wants to re-add the customer they can -> use case: a shopper stops paying their membership fees and the hub wants to delete them, then they start again and the hub wants to re-add them.

The important thing is that the user disappears from the enterprise customer list and that the customer doesn't receive any benefits associated with the deleted account in the future.

**Comment by jibees** [comment]
I think I'd vote for the second option, the _semi hard deletion_ and I will have a look for the consequences ; but I'll invoke @mkllnk to share its opinion on it. 🙏

**Comment by mkllnk** [comment]
I guess that we prevent the deletion of customer records because you can't undo the fact that the user ordered and therefore they are a customer. We can say though, that the user *was* a customer and *isn't* a customer any more.

So if we delete the *is current customer* relationship, we just need to decide if we need to remember that the user *was* a customer or if we are happy to just forget about it. So if we delete the relationship and later on the same user orders again, then the order history may not contain past orders. It's a new relationship.

Since guest orders don't even have a user record, we rely a lot on the email address. But email addresses can change. So just looking for all orders with a certain email address to compile the order history won't work in all cases.

Anyway, our production database shows that there are thousands of complete orders without a customer record. They are from a time when we didn't have customer records yet. That proves that our software is okay with that. We can delete customer records.

I searched the code history for a hint why we introduced this check for orders but it was committed straight to master, without pull request and without any reference to an issue that could give us a clue. So this safeguard could have been done without specification. https://github.com/openfoodfoundation/openfoodnetwork/commit/6586e67a5c4eec459557c19f64bc45e3de75bc8c

Actually, thinking about coding at the time, we may have introduced that check because it was easier than updating all associated orders to delete the customer id and avoid database errors.

I don't like to have data which we don't need. So I vote for option 1 - hard deletion of the customer record. If that becomes a problem, we then have a use case for better design. But for now, we only see the deletion of customers as a need and I can't see any big problems with that.

**Comment by tschumilas** [comment]
Just adding from a user perspective -  it is always the enterprise manager's decision whether or not to delete.  So -  in a CSA situation where members come and go (a member one year,  not a member the next,  then a member again)  the enterprise manager could decide to use tags to organize their customer list and never delete.  So managing with tagging is always an option -- if an enterprise manager thinks they want to keep historic customer orders.  And we could explain that option in the user guide.    (I'm really thankful that this is being looked into)

**Comment by RachL** [comment]
FYI this is a very old bug: I've never seen it work. So it's not really an s2, although I agree tagging is annoying. I _think_ we didn't dive into it in the past, because we were afraid of leaving orders without customers. As we have started to look at it, let's finish. But let's keep track of the time so we don't postpone everything else we are working on?

**Comment by RachL** [comment]
@openfoodfoundation/train-drivers-product-owners 20 days with this s2 open. Do we still want to look at it as part of an s2 / ie right now? if so it seems it could only be @mkllnk when he is done with active storage migration... or @jibees or @georgethoppil  you feel solution 1 can be something you can do?

**Comment by georgethoppil** [comment]
@RachL sure I can take a look at this

**Comment by georgethoppil** [comment]
@mkllnk I think we will have a similar issue if we have a subscription with the customer and try deleting the customer record. The schema currently has a non null customer id field so our option of setting this field null cannot be done. We could update the schema to remove the null is false but I think we should just destroy_all on any subscription records for the customer instead. Let me know what you think

**Comment by mkllnk** [comment]
It sounds fair to remove subscriptions if we want to remove the customer record. We currently don't support deleting subscriptions though. So I'm not sure which implications that would have.

We could investigate this option though: You can delete a customer record if there are no active subscriptions. Otherwise the subscriptions need to be cancelled first. When deleting a customer with subscriptions, there's a warning that it will delete the subscriptions, too. I would do that explicitly in the controller (not via dependent destroy) to avoid accidental deletion of customer records with subscriptions. And fewer callbacks are usually easier to manage in the future.
