### ISSUE TITLE
[Admin][Order] StripeSCA - No user feedback after making Stripe payments in the backoffice

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#9048]
## Description
When a manager makes a Stripe payment in the backoffice with the customer card, there's no feedback about how the payment went except in column "Payment Status" of the payment list. If there are multiple payments, it's not clear what happened to the payment that was just made. The user should see a green banner on top of the page with a success or error message.

(there is some code that is doing this, setting flash[], but the flash is not showing. I think this is due to the fact a redirect is being made.

I think this can be seen anywhere with Stripe configured.

## Expected Behavior
User can see flash message "Payment was successfully made" or "Payment was not successfully made".

## Actual Behaviour
No flash message, the new payment will appear in the list of payments with a payment status.

## Steps to Reproduce
Edit an order and add a stripe payment to it.

## Workaround
Memorize what payments already exist in the order and check what is the new payment in the list after you made the payment, check the payment status of that payment to see what happened to your new payment.

NOTE: most payments will have status COMPLETED or FAILED. Some other status are INVALID and CHECKOUT.
With StripeSCA there's a new case where stripe demands extra auth for the payment (which is not supported in the backoffice). If this happens, the manager is taken to the payments list and the payment status will be PROCESSING... this case will be improved as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/4178

## Possible Fix
We need to make sure the flash message in the code is sent to the browser even with the redirect.

**Comment by murjax** [comment]
I might be interested in looking at this one. Can someone confirm what page this is occurring on? Where are the "backoffice" payments? I see there's an order payments page (`admin/orders/:order_id/payments`). Is this the correct page?

**Comment by RachL** [comment]
Hi @murjax yes this is the correct page!

**Comment by murjax** [comment]
Does each payment on an order correctly reflect its payment status, or is that part of the issue? 

When I create an order and try to receive a payment on it, the payment status still shows as "Checkout" after saving. The order information column also indicates "Balance Due" on the payment. I've confirmed a payment in fact exists in the database after creating it though. Is there another step to "processing" the payment? Should we still show the flash with the payment status anyway?

**Screenshots**
Payment form:
![Screenshot from 2023-10-11 20-58-51](https://github.com/openfoodfoundation/openfoodnetwork/assets/14116496/163b0893-716e-4b3f-9856-1cd984c923b5)
Payment list:
![Screenshot from 2023-10-11 20-58-27](https://github.com/openfoodfoundation/openfoodnetwork/assets/14116496/e542ebc9-2701-41f2-b8c6-6cb21974888c)

**Comment by drummer83** [comment]
Have a look at this guide on how to set up Stripe, because this issue is about Stripe payments and can't be seen with cash payment methods.
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-in-your-local-environment

**Comment by murjax** [comment]
I was able to get my Stripe setup successfully and start looking at this.

This issue appears to be caused by a combination of the payments create endpoint returning HTML and the Angular submit handler performing a manual location pathname change. The payments create response redirects to the payments index as HTML which contains the desired flash message, but this is ignored by the frontend path change. The page seen is actually from the second request for the payments index.

![ofn_payment_flash_annotation](https://github.com/openfoodfoundation/openfoodnetwork/assets/14116496/1e0781ed-0596-4b0e-ac59-e6d587ba8df3)


Given that context, are there any issues with converting the create response to JSON? This would allow us to perform redirects and display flash messages or alerts from the frontend based on the response details. Alternatively if we need to keep the create endpoint as-is, we could capture the HTML response and manually replace the page content. This approach seems more error prone as the page could get wiped if a bad response is ever returned.

Code for reference:
[Payments controller](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/spree/admin/payments_controller.rb#L41)
[Angular payment resource](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/resources/resources/payment_resource.js.coffee)
[Angular submit handler](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/payments/services/payment.js.coffee#L46)

**Comment by dacook** [comment]
Hi @drummer83 , Ryan has submitted a fix which looks good, but removes some old code. It seems unused, but it used to provide a message "New order completed" when submitting a payment for an incomplete order, and it landed on the order edit screen (rather than payments list). Do you know if this condition is relevant, and have any ideas how to replicate it?

If not, I guess we can burn it 🔥

**Comment by drummer83** [comment]
@dacook I am not aware I ever came across this message and I couldn't find a way to trigger it. That's no proof it is unused of course. We'll just have to try. :fearful:
