### ISSUE TITLE
When creating variants the error message on incorrectly input data is unreadable

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#9068]
## Description

On the admin/products page creating new variants is simple enough using the + button.
However if you type 120g instead of 120 you get an error that is hard to understand.
It would be great if the offending fields could be highlighted instead of a cryptic message at the bottom of the screen.
Failing that, can we make this error message easier to understand?

## Expected Behavior

When I get an error it's clear to me what the error is

## Actual Behaviour

Cryptic error message

## Steps to Reproduce

1. in /admin/products click + to add a new variant
2. Enter 120g instead of 120 in the unit field
3. See an error message that is hard to understand
4.

## Animated Gif/Screenshot

![Screenshot from 2022-04-04 17-09-14](https://user-images.githubusercontent.com/8669848/161588910-f1676b79-bec0-462c-be7a-8630aab9b48f.png)

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Note that since we are about to rewrite this page its probably not worth investing too much into this, but a better error message would be nice.

**Comment by jibees** [comment]
I just tested, and not sure to exactly understand actually, or maybe there're two bugs

 - When entering a new variant with `120g` in the unit field, it feedback me as "Changes saved", but no variant is created.
 - I've double-checked your screenshot, and it appears that you checked the "on demand" checkbox. By doing this, I've the same error as you "Saving failed. Save failed due to invalid data:500". Actually this error is thrown because `You need to save the variant to create a stock item before you can set stock levels.` but error doesn't appear to user

https://github.com/openfoodfoundation/openfoodnetwork/blob/513b26f47c142294aa78488b124c42db1b54b70e/app/models/concerns/variant_stock.rb#L134-L137


Can you confirm that I found two bugs instead of one and that I am not wrong about everything? 🧠

**Comment by jibees** [comment]
It seems to be an exception, not an error: ie. I'm not sure this error should be displayed to the end-user ; actually, I'm also not sure this error is relevant in this case (why creating a stock item because of on_demand?)

**Comment by jibees** [comment]
Trying to sumup
|  unit  |  on_demande | stock_items  |   
|---|---|---|
| `120`  |  checked  |  `<Spree::StockItem id: 104, stock_location_id: 1, variant_id: 104, count_on_hand: 0, created_at: "2022-07-01 17:41:07.715372000 +1000", updated_at: "2022-07-01 17:41:07.715372000 +1000", backorderable: false, deleted_at: nil, lock_version: 0>`  |   
|  `120g` | checked   |  `empty` |
