### ISSUE TITLE
Litres and millilitres as lower case 'L'

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#921]
Oliver would like to change the unit display on the shopfront from 'L' to 'l' and from 'mL' to 'ml' please

**Comment by pmackay** [comment]
What's the rationale for this, out of interest? 

I'm slightly wary of lowercase "l" being rather unclear. 

Some points of reference:

[This page](https://www.gov.uk/guidance/packaged-goods-weights-and-measures-regulations) seems to use lowercase but with a space in front. 

Ocado, Tesco, Sainsburys, Morrisons all use uppercase L.
Riverford use lowercase but their font makes it pretty clear.
Able and Cole expand to the words, e.g. litres.

**Comment by stveep** [comment]
L is the S.I. unit :) but lower case is usually used for ml, cl etc. on drinks packaging, and even by us scientists! I guess the preference to use L or write litre in full is so that 2l is not confused with 21, for example.

Anyway, i think this would be best handled in i18n via t or l to accommodate local styles.

**Comment by OliverUK** [comment]
My reason is poorly aesthetical. You don't normally find grams abbreviated as G (100g /vs 100G) or centimeters as CM (nor cM or Cm) so L looks wrong and inconsistent.

**Comment by lin-d-hop** [comment]
Closing #gitcull2017
