### ISSUE TITLE
FR prod is slow / unreachable

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9215]
## Description

It started around 5:30 PM today. First it was super slow, now I personally don't manage to login anymore, the server is timing out.

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/ba0c97b6-77dc-4600-ba59-89cdc680d0fb)

## Steps to Reproduce

Visit coopcircuits.fr

## Animated Gif/Screenshot

Infinte loading, then snail

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: v4.1.31
* Browser name and version: Firefox, Chrome
* Operating System and version (desktop or mobile): Both

**Comment by mkllnk** [comment]
There was a suspicion that the new reports caused a performance issue. One user a trouble accessing a report and maybe that was because of timeouts. I searched the logs and found some report activity at the beginning of the slowdown:

```
egrep ' 499 [0-9]* [1-9][0-9]+\.' access.log
...
[24/May/2022:17:43:57 +0200] "GET /admin/reports/packing/customer HTTP/2.0" 499 0 140.450
[24/May/2022:17:44:00 +0200] "GET /admin/reports HTTP/2.0" 499 0 3.619
[24/May/2022:17:44:04 +0200] "GET /de-la-graine-a-l-assiette/shop HTTP/2.0" 499 0 27.240
...
```

You can read this as: `[request-time] "request" response-status response-size response-time`

That is the first request which takes longer than 20 seconds and the client times out (status 499). After that all requests are slow. The whole system can snowball into a halt because people keep refreshing pages and because responses take so long, the server can't catch up. This is my best theory so far.

A few ideas for solutions:

- Improve the performance of that report.
- Test reports in general for performance and fix others, too.
- Limit execution time which will break some reports but at least they don't bring the whole system down.

The last item is the quickest and it makes it obvious which reports need fixing. We had a requirement for that at some point and fixed everything that was slower than some definition we came up with.

**Comment by mkllnk** [comment]
France has a timeout of 4 minutes:
https://github.com/openfoodfoundation/ofn-install/blob/5020f3178ce486bf693cdd0cff337c70000f5acb/inventory/host_vars/coopcircuits.fr/config.yml#L11

**Comment by RachL** [comment]
Reporting what we talk on slack: orders and fulfillment customers reports  have an average load of 2:46 We need to put FR prod timeout back at 4min

**Comment by jibees** [comment]
I re-provisioned the server to put the timeout back at default value (ie. 4min)
