### ISSUE TITLE
AU(?) Production Low on Diskspace

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#9240]
## Description

Wormly alert

Error Continues on OFN Production. Disk space used: root is 90.29 % for 10 hours.

For more info
https://www.wormly.com/edithost/hostid/44368#metrics

I guess we have until next week to get this sorted. But marking as S2 so that we don't dawdle.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

https://github.com/openfoodfoundation/ofn-install/issues/806

**Comment by mkllnk** [comment]
I noticed that a week earlier and did a little clean-up but it seems to fill up quite quickly now.

**Comment by mkllnk** [comment]
I solved the immediate problem by rotating puma.log which saved 3GB for now and brought us back to 80% disk use:

* https://github.com/openfoodfoundation/ofn-install/issues/806

A lot of that log file was filled with Paperclip deprecation warnings. We are working on a fix for that already.

Still, we don't have heaps of space. Lets see what is using it with `ncdu`:

* Postgresql uses 4GB for data and 2GB for write ahead logs to synchronise with Metabase. Nothing to do here. Our database is naturally growing.
* The system log uses another 3GB. It has a lot of entries from our Metabase synchronisation, probably because it's not working. Since we are looking into a different option, we should deactivate the broken synching on au-prod.
* Our app takes 4.6 GB (with backups) which seems normal.

So the only action from this:
```
root@prod3:~# systemctl stop kafka-connect.service 
root@prod3:~# systemctl disable kafka-connect.service 
```

Done. Let's see how we go. We may need to increase disk space on the server but the requires a reboot and should happen at a quiet time.

**Comment by mkllnk** [comment]
This is still a problem. Australian production is now at 97% disk use.

**Comment by mkllnk** [comment]
Since the old Metabase connection is not active any more, we stopped converting the Postgresql WAL files into JSON for streaming and Postgresql was keeping all the WAL files which are filling up the disk. I removed the replication slot to tell Postgresql that we don't need those WAL files any more:
```sql
select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid |    database     | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+----------+-----------+--------+-----------------+-----------+--------+------------+------+--------------+-------------+---------------------
 debezium  | wal2json | logical   |  18001 | openfoodnetwork | f         | f      |            |      |     22209679 | 2A/ED160700 | 2A/ED160738
(1 row)

select pg_drop_replication_slot('debezium');
 pg_drop_replication_slot 
--------------------------
 
(1 row)

select * from pg_replication_slots;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
(0 rows)

```

I'm not sure when Postgres is cleaning up but I hope it's soon. We are at 98%. Maybe I need to increase disk space anyway.

**Comment by mkllnk** [comment]
Uh, it has done it within a few minutes. 7GB of space freed up.
