### ISSUE TITLE
Unable to login to staging environment with admin login

### ISSUE THREAD

**Issue by kvaithin** [openfoodfoundation/openfoodnetwork#9241]
## Description
Unable to login to staging environment with admin login.
(Could be using incorrect login details mentioned below when it comes to staging. Pls advice if so. )

## Expected Behavior
Should have been able to login. 

## Actual Behaviour
Unable to login to staging environment with the admin login provided [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/docker/README.md).

Getting a password reset confirmation warning instead. Please refer to screenshot below.

## Steps to Reproduce

1. Go to https://staging.openfoodnetwork.org.uk/#/login
2. Login with ofn@example.com. Use password provided [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/docker/README.md).
3. You'll experience the confirmation email warning instead of logging in. 

## Animated Gif/Screenshot

![fbce757abf5cb36e1cf641bbe7e0d192](https://user-images.githubusercontent.com/68995267/170861991-1b753bb1-bbd1-4226-b243-80a8f96221cf.png)

## Workaround
Not found one.

## Severity
bug-s2: a non-critical feature is broken, no workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
Staging url has this issue. 
Was able to login when using localhost:3000

* Version used:
* Chrome Version 102.0.5005.61 (Official Build) (64-bit)
* Ubuntu 18.04

## Possible Fix
Believe a user could have clicked the password reset on thie login account. 
Reset the password and update docs with new password.
Since this is a shared account for development, could we onsider disabling 'Forgot Password' button for it to prevent the issue from reoccurring.

**Comment by drummer83** [comment]
Hi @kvaithin,
our staging servers have different login data than the local setup - you couldn't know that. You are welcome to register your own accounts on those servers (both enterprise managers and customers). The super admin access is provided to the core team only as far as I know. If you let us know what you would like to test/change on the servers we are happy to support of course.

We use the staging servers for staging and testing every pull request before merging. That's why the software version is changing very often and down times can occur, which can be very confusing if you are not aware of what is happening. To avoid this, we use labels (e.g. pr-staged-uk) on the pull requests to indicate that the server is currently being used by a tester or/developer.

Maybe you can let us know what you are trying to do and we will find a solution.

**Comment by kvaithin** [comment]
Hi @drummer83, got you. 

I was trying to have a look at this issue #9232 . 

Believe I misunderstood this line. ` (all other fields don't matter).`

Thought issue only occurs when calculator field is missing.
But locally, it failed when I only added name too. 

Thus wanted to see if I experience any difference in staging environment since that's the one shown in gifs. 
But having a relook at the attached gif, does look like adding name by itself throws similar error.

**Comment by drummer83** [comment]
Cool @kvaithin, let me know if you want to be assigned to #9232.
