### ISSUE TITLE
Producer notification email improvements

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#927]
Please could the emails a producer receives as "purchase order" have a total amount at the end!!!

**Comment by myriamboure** [comment]
Agree with you @OliverUK !

I think more generally the producer email should be a bit more clear and user friendly... it's not very appealing, it can be confusing for producers who are not very tech friendly...
And it's very formal, not a very friendly language... the signature is on the same line as the greetings and not a personal signature, it's the name of the company (the name of the hub manager would be more personal I guess, and below we can have the reference of the hub so that the producer remember who this person is)
The list of products is not so friendly either, maybe a table with colums and titles for each column would be clearer...

![image](https://cloud.githubusercontent.com/assets/8135376/14871101/89bc7fe8-0cdf-11e6-8afa-683ea98337b5.png)

Until now I never used it not only because the total was missing, but I needed to make it more clear for the producers, and also it as too unfriendly for me in the relationship with the producers ;-)

Also I don't understand why there is an "unsubscribe" link at the end? This is not really an automatic message, it's an order... do we need an "unsubscribe" link?

Is this need shared by UK as well?

[Also @blancnic this is an email we need to be able to translate in French ;-) (sent by clicking on "notify producers" in the order cycle page.)]

**Comment by OliverUK** [comment]
@myriamboure 
Yes, all the above for us too. Our current software provides a nice table, much easier to read and with text customisable (though admittedly I had to ftp into the web files for this). 
![screen shot 2016-04-28 at 13 47 10](https://cloud.githubusercontent.com/assets/17590921/14886320/1bf95166-0d48-11e6-8808-2ab5088fcb72.png)
Not only is the current OFN email tricky for producers to read, they also have to add up the amounts to arrive at a total to invoice. And of course I have to add them up too - for 20 - 30 producers.

**Comment by OliverUK** [comment]
@NickWeir63 
I can't add labels but maybe this could be labelled as important?

**Comment by daniellemoorhead** [comment]
@NickWeir63 @lin-d-hop is this something that you want us to do in the next release as a priority for the UK?

**Comment by NickWeir63** [comment]
Thanks @daniellemoorhead - it seems important to Oliver and Myriam and I can see their point.  I would like to consult with @lin-d-hop and @sara and check with you how much time and budget this fix will take but given the tight timescale I am going to risk saying yes please can we include this in the next release.  Thanks

**Comment by OliverUK** [comment]
That would be great!

**Comment by stveep** [comment]
I added the total in the PR above, in case it's useful.

**Comment by NickWeir63** [comment]
Stroudco sent the first live notification emails to producers this morning and have had some negative feedback (see example below).  @OliverUK has had to create a table for each producer and send separate emails.  Can I just check that we will be getting back to the nice emails that @stveep originally designed when we get v.1.7.1?
Thanks
![screenshot 2016-05-12 08 33 38](https://cloud.githubusercontent.com/assets/10517702/15207180/4a8dc816-181c-11e6-86ae-2bef27b69635.png)

**Comment by stveep** [comment]
Can we get the uk/order_cycle_report branch put on UK staging to test? This will introduce a proper e-mail with table similar to Oliver's Stroudco example. Text will also be customisable - through translations for now. We could also have a configuration but would need to implement something in the admin interface to modify the text.

**Comment by daniellemoorhead** [comment]
@stveep @NickWeir63 1.7.1 is supposed to go out today. What do you need us to do here in Aus to get this through? Ping @mkllnk and @oeoeaio as they're sorting out 1.7.1.

**Comment by RohanM** [comment]
I've brought this branch over (uk/order_cycle_report rebased to uk-order-cycle-report) and @sstead has tested, and it all looks ok. It's now included for the 1.7.1 release :)

**Comment by RohanM** [comment]
It looks like 1.7.1 won't make it out today. If you need this feature, you can find it on the master branch, and we'll aim to have 1.7.1 out on Wednesday. Sorry for the delay!

**Comment by stveep** [comment]
Thanks @sstead @RohanM! I wasn't sure if I had handled the tax breakdown correctly, did it look OK?

**Comment by sstead** [comment]
Sorry Steevp, I've just checked the tax element again... looks like something is not quite right... 
![image](https://cloud.githubusercontent.com/assets/10843056/15240717/daf4270c-192e-11e6-8994-ae8bb21cabd6.png)

**Comment by NickWeir63** [comment]
Thanks for trying to get this into 1.7.1  @stveep has asked me to email him the latest wording of the Stroudco notification.  I will also email it to @daniellemoorhead as I dont have an email address for @mkllnk and @oeoeaio

**Comment by daniellemoorhead** [comment]
You can't just add the wording on this issue @NickWeir63 ?

**Comment by OliverUK** [comment]
You guys rock!

**Comment by stveep** [comment]
I've added the Stroudco wording. @sstead I found an issue with the tax not being correctly multiplied by the quantity and fixed it...but I'm not sure if it was actually what was causing your problem - could you check again?

I merged current master (incl. the previous PR) into the original uk/order_cycle_report branch and added these fixes there. I will put in an updated PR, or let me know if you want me to commit on the new branch instead?

**Comment by daniellemoorhead** [comment]
Hi all, from what I can see this issue can be closed now given that #908 and #936 and #1005 PRs have been merged. @stveep is there anything left for this issue?

**Comment by stveep** [comment]
All done I think!
