### ISSUE TITLE
Capturing payment ignores edited shipping fees

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9290]
## Description

If an enterprise user edits an order and changes the shipping method to a method with a higher/lower fee, then clicking 'capture' in the orders list will still capture the amount of the originally selected shipping method.
If the updated fee is higher, the order will show a 'balance due'.
If the updated fee is lower, the order will will show a 'credit owed'.

## Expected Behavior

Capturing a payment should capture the currently owed value - all edits until that point included.

## Actual Behaviour

Capturing a payment is currently capturing the original amount only - editing of shipping methods are ignored.

## Steps to Reproduce

 

1. As a customer place an order.
2. As enterprise user edit that order, i.e. change the shipping method to a method with a different fee.
3. As enterprise user capture the payment on the orders listing page.
4. Observe the balance due or credit owed.

## Animated Gif/Screenshot

![Peek 2022-06-10 11-23](https://user-images.githubusercontent.com/1790176/173034999-40d5570b-4c43-4a89-8d9d-f62fcbb8061c.gif)

## Workaround

Capture an additional payment.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.1.34
* Browser name and version: 100.0.2 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

**Comment by tschumilas** [comment]
This is not only about changing shipping fees.  It applies to any order changes -  adding/deleting products,  changing weight on variable weight products,  adding/removing an adjustment of any kind,   changing any kind of fee ....    The issue is that when a payment is accepted (via the checkmark) from the orders list,    the amount of the payment that will be applied does NOT appear on the orders list page.  Users (logically) assume that the 'balance owing'  - which shows on the screen -  is the amount that will be applied to the order when they accept the payment.    BUT -  when the payment is accepted (check marked),  the 'payment of record' is applied to the order.    This is the 'payment' made (or pledged in the case of cash payments) at checkout.    So -  the app assumes,  when a payment is accepted,  the payment amount = the checkout amount.

A hub here at OFN-CAN  that is run by a bookkeeper pointed out to me that when a cash payment method is selected  -  payment is NOT happening at checkout.  Payment happens some time later.  (Unlike credit,  or paypal - where payment happens at checkout.)    So technically (according to her)  this checkout amount is NOT a payment  -  our app should show a null payment at checkout for cash methods.

Whether we agree or not -  this assumption that the payment = checkout amount is VERY problematic,  and causes many emails to support where users can't figure out why the have all these credits.....  on orders.

Solutions?

1. when the payment is accepted (checkmark is checked) on the orders listing screen,   the app should apply the 'balance owing' (which shows in that screen)  to the order total.

2. if #1 is not possible -  can we add a column on the orders listing which shows the checkout amout in a column called 'payment amount'  or something.

**Comment by filipefurtad0** [comment]
This concerns cash payments and occurs only if the editing of the order happens after checkout, right?
If so, then I think the app is working correctly.

> 1.  when the payment is accepted (checkmark is checked) on the orders listing screen, the app should apply the 'balance owing'  (which shows in that screen) to the order total.

Currently, the hub can add additional payments under `/admin/orders/order_number/payments`, if needed. One can even void the first payment and add a second payment, including the order total. In any case, all changes on payments are listed on invoices, which both customer and hub can see to understand the payment history. In the example below, stock for a variant was increased:

![image](https://user-images.githubusercontent.com/49817236/175505012-ae88c4af-302b-4ff9-9b35-201b1a11ba6d.png)

These changes on payments would not appear on the invoice, if the captured amount would be applied by default to the 'balance due' value of the order total. I think this could generate confusion to customers. What do you think?

> 2.  if this is not possible - can we add a column on the orders listing which shows the checkout amout in a column called 'payment amount' or something.

This could be a papercut (to be confirmed).

**Comment by drummer83** [comment]
> But I'm still wondering why - why the app doesn't 'accept' the amount owing as the payment when the checkmark is checked?

Yes @tschumilas, same question here! :+1: 

>  If so, then I think the app is working correctly.

Can you explain why you are thinking that this is correct, @filipefurtad0? The order can be changed before the cash payment and then clicking 'capture' should capture the current amount and not the original one, shouldn't it?

**Comment by filipefurtad0** [comment]
Hi @drummer83,

> clicking 'capture' should capture the current amount and not the original one, shouldn't it?

I've found no specification pointing out this should be the correct behavior.

Also, the [user guide](https://guide.openfoodnetwork.org/basic-features/orders/view-orders#capturing-a-payment) reads:

"Note that this will capture the full amount of the order as paid."

I believe "as paid" refers to the amount seen by the customer when checking out, and not after order edits. So, IMO both items 1. and 2. in the discussion above are feature requests / wishlist items.

**Comment by tschumilas** [comment]
It is quite important that the store manager knows exactly what amount of money they are accruing to an order when they click the checkmark.    Clicking the checkmark, by default,  accrues the original checkout total to the order.  If the order was adjusted in any way,  the user is accruing an incorrect amount of payment to the order when they click the checkmark.

Users do not know this.  Users think that the amount owing is accrued to the order when they click the checkmark,  and are then confused about why their order goes into credit,  or still shows a balance due.  Support people are spending a lot of time going through orders forensically for the user to figure out what happened. 

This affects every enterprise that takes non-credit payment,  and makes any change to an order (adjustment changes like shipping,  or line item product changes....)  So -  it affects a lot of orders,  and we are hearing about it from  users all the time.

I think the app SHOULD accrue the balance due to the order by default.  But if that is a significant feature -  is it possible to do something that might be a papercut size?  

For example -  on the edit orders page,  ideally beside the checkmark,  could we display a caution icon when the original order total changes?   Then the user knows that they should not click the checkmark to accept payment.  They must edit the individual order,  and manually enter the payment actually received.
