### ISSUE TITLE
Convert Admin Order Cancellation Workflow to Stimulus

### ISSUE THREAD

**Issue by binarygit** [openfoodfoundation/openfoodnetwork#9447]
### What we should change and why (this is tech debt)

As OFN is transitioning to use StimulusJs in the frontend, remove all Jquery/Angular code that handles admin orders cancellation to Stimulus. The existing jquery/angular code resides in: `app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb`

**Comment by cyrillefr** [comment]
Hello @binarygit ,

May I work on this issue ?

**Comment by sigmundpetersen** [comment]
Sure, go ahead 🎉 Thanks

**Comment by cyrillefr** [comment]
Hello @sigmundpetersen , @binarygit 
I am working on it.

Cancellation is being processes (in the front-end) with an `ofnCancelOrderAlert` modal laying in `app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb` (js/jQuery).

However, the modal is called multiple times in this very file.
Also it is called by Angular controller for cancel but also by the line items controller.

Which means I cannot totally due to the scope of this PR get rid of this jQuery code.
But what I can do (and have done) is:
- created a new Stimulus controller that handles cancellation instead of the Angular controller
- created a mixin to factor the max of code
- a new  ofnCancelOrderAlert modal in another js file, but with button events taken care in Stimulus

The idea behind is to use the new Stimulus/js (maybe I can take the new modal in Stimulus, i don't know) for the cancellation, with not touching the current modal in order to not to break current workflow.
When every call is diverted from the "old" to the "new" modal, we can get rid of the legacy modal.

Is this way is ok with you ?
I will be able to push next week I think.

**Comment by binarygit** [comment]
I think it's a good idea and a great start :smile: @cyrillefr
