### ISSUE TITLE
[Flaky] Alternative Invoice - total tax line

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9556]
### What we should change and why (this is tech debt)

This fails consistently on my system, so far never on master, and often on https://github.com/openfoodfoundation/openfoodnetwork/pull/9543.

```
     Failure/Error: expect(page).to have_content "Total tax (20.0%): $324.09"
       expected to find text "Total tax (20.0%): $324.09" in "TAX INVOICE Enterprise 37 10 Lovely Street, Northwest Herndon, 20170, Victoria Billing address: Invoice issued on: 2022-08-11 John Doe Date of transaction: 2022-08-11 10 Lovely Street, Northwest Invoice number: R671343520 Herndon, 20170, Victoria 123-456-7890 benny@wuckert.info Item Qty Unit price (Incl. tax) Total price (Incl. taTax rate Product #41 - 8462 1 $12.54 $12.54 0.0% (1g) Enterprise 38 Product #42 - 2674 3 $500.15 $1,500.45 20.0% (1g) Enterprise 38 Admin & Handling $120.00 Shipping $100.55 20.0% Total (Incl. tax): $2,077.74 Total tax (20.0%): $20.11 Total (Excl. tax): $1,733.54 Payment summary Balance due : $2,077.74 Payment Date/time Payment Method State Amount Aug 11, 2022 Check checkout $1,757.54 10:34 Payment Description at Checkout"
     # ./spec/features/admin/invoice_print_spec.rb:375:in `block (5 levels) in <top (required)>'
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/runs/7785026589?check_suite_focus=true

**Comment by mkllnk** [comment]
This has been failing on CI quite a lot now. It's quite urgent. It seemed to always pass on my machine but when I kept my CPU busy I had a fail rate of 50%.

I started the command `yes > /dev/null` in four terminals to occupy all four CPUs and then ran this spec ten time:

```
for i in `seq 10`; do r spec/system/admin/invoice_print_spec.rb:239; done
```

**Comment by mkllnk** [comment]
It's weird. If my machine is cold, the spec always passes. If I keep it busy and it warms up then after 20 seconds or so the spec starts failing and then it consistently fails until my machine has some time to cool down again.

I compared the generated invoices. The total tax is the only line that's different. Everything else seems correct. The incorrect sum has only the included tax on the shipment and it ignores the adjustment on the line item.

The shipment always has included tax of $16.76 even though the 20% tax is $20. Uh, hang on, $20 are 20% of $100 which is the shipping cost. But if the tax is included in the total then $16.67 would be 20% of the untaxed value. So that's correct. So I would expect the tax total to be $250.08 + $16.76 = $266.84. Not $270.08 as stated in the spec.

A previous version was testing for the $16.76 which would pass sometimes, changed in 5aa6b14756e1e4d83830f8d3b07eb98c0949ceaa. Sooo, worse than calculating the wrong tax is to calculate a random value that's wrong. :see_no_evil:  ... But I may be wrong here, too. Help! @filipefurtad0 

At least the database values seem to be right. There's just something weird with the calculation for the invoice.

**Comment by mkllnk** [comment]
I'm getting there. The data comes from this method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/07018370e03394b636c2b252ba7d865b17c9a92c/app/helpers/checkout_helper.rb#L70-L77

The `totals` give back two tax amounts but in a random order. And because they have the same percentage, the second value overrides the first when we store them in a hash by tax rate. :heavy_check_mark:

**Comment by RachL** [comment]
In FR alcohol is taxed at 20% but so is shipping. That's why when you go visit current tax report, you have 2 columns at 20%.

Ideally, we would want shipping to be added on the invoice with a dedicated line (which is the case in the regular invoice template).

But I don't think this is a priority. If this is blocking the current build, I would favor removing the two same rate and create a tech-debt issue so that our test suite handles this case.

**Comment by filipefurtad0** [comment]
Thanks for jumping into this one @mkllnk , I agree it is urgent. I was unable to find the root cause so far but your investigation is really helpful.

Some comments so far:

> I would expect the tax total to be $250.08 + $16.76 = $266.84. Not $270.08 as stated in the spec.

Interesting. $270.08 is indeed incorrect, but I haven't really ever observed that value in my system yet. Locally, the spec usually fails with $16.76...

We have three parcels 16.76 + 20 + 250.08 (respectively, the tax value included on the shipping method, the enterprise fee, and the line item). So it seems that the "total tax" line on the invoice is rendering random values, based on combinations of these parcels...

> But the spec has two tax rates with 20% and that triggers this bug.

Great point. I'll investigate whether having three separate taxes for each of the three parcels above fixes it - at least, it should help understanding which rate did not get included on that final tax value.

**Comment by filipefurtad0** [comment]
> whether having three separate taxes for each of the three parcels above fixes it

I've tested this approach on PR 9602, which is now passing locally. Let's see :crossed_fingers:

**Comment by RachL** [comment]
@filipefurtad0 hello! Is "in dev" the correct position for this issue?

**Comment by filipefurtad0** [comment]
Thanks for double checking @RachL,
Added a PR to this - moved to code review.
