### ISSUE TITLE
[Legacy Checkout] No shipping method option on checkout prevents completing the order and leads to Stripe charges

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9614]
## Description

Aggregates openfoodfoundation/openfoodnetwork#8219 and openfoodfoundation/openfoodnetwork#9610.
Relates to openfoodfoundation/openfoodnetwork#8974.

A shipping methods can be hidden from by:
- setting as back-office only
- using tags

If no shipping method is eligible for a given customer, then:

**Legacy checkout** - If a customer reaches the final stage of checkout and places the order without having an active checkout method then the checkout will fail. The user will see a first generic error messages: `The checkout failed. Please let us know so that we can process your order`, and then, when reattempting, another generic error message: `Payment could not be processed, please check the details you entered`.

If Stripe is used as a payment method this will lead to charges, although the order is not completed.

**Split-checkout** - the user cannot proceed to further steps, and can't really place the order - this is a good thing :muscle:

## Expected Behavior

Under discussion, see below.

## Actual Behaviour

Legacy checkout: Even if a user does not see any shipping method available, it is able to proceed to checkout, and place the order, which will lead to error unclear error messages and Stripe cards being charged.

Split checkout: Even if a user does not see any shipping method available, it is able to proceed to checkout, but cannot proceed to the next step in the checkout flow.

## Steps to Reproduce

1. As a hub, set up a order cycle/shop, making it ready to order.
2. As a hub, set all shipping methods to back-office only, or set the appropriate tags to hide shipping methods from a given customer.
3. Legacy checkout: As the customer, place some items in the cart, and proceed to checkout. 
4. Repeat step 3 for split-checkout.
5. See the scenarios described in the Actual behavior and the respective screenshots below.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/49817236/187718831-4c80e91c-7f9f-4a68-81f1-cf821d69be66.png)

## Workaround

None, for the customer.

## Severity

bug-s3: a feature is broken but there is a workaround
Keeping the severity from the most recent issue openfoodfoundation/openfoodnetwork#8219.

## Your Environment

* Version used: v4.2.9
* Browser name and version: Firefox 103
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by audez** [comment]
Hi, thank you for this @filipefurtad0 ✨ A small feedback: weirdly, it looks like paying with bank card didn't automatically lead to charges: I tested to pay twice with bank card (I think it was with two separate carts, so two different requests), but only one payment made it through Stripe. On the day of testing, there were two pending payments on my bank account, but only one did appear in Stripe. Weird!

For the one that made it to Stripe, the producer clicked on "refund" to pay me back. I was totally refunded:
![Screen Shot 2022-09-01 at 10 57 14](https://user-images.githubusercontent.com/28386648/187874909-121374a2-1808-4b99-80cf-86b9a08a7a93.png)
 (I can see it on Stripe but I can't see anything on my bank account, nor the payment neither the refund, everything disappeared)
The producer has had to pay the transaction fees:
![Screen Shot 2022-09-01 at 10 55 18](https://user-images.githubusercontent.com/28386648/187874957-be30ce21-e1e2-4f6a-93cc-73ed0159d1c1.png)
So this bug was quite painful for the producer, because her orders were "blocked" during 3 days + it's hard to see which payments were problematic, because for most of the orders there's no email appearing in Stripe (people checked out without an account) + she has to pay the remaining fees. Luckily she is very kind and patient!

**Comment by audez** [comment]
Hi, thank you for this @filipefurtad0 ✨ A small feedback: it looks like paying with bank card didn't automatically lead to charges: I tested to pay twice with bank card (I think it was with two separate carts, so two different requests), but only one payment made it through Stripe. On the day of testing, there were two pending payments on my bank account, but only one payment appeared in Stripe. Weird!

We told the producer to make refunds on Stripe - which is not easy because for most of the payments there were no emails associated..

**Details on how refund works on Stripe:**
- Stripe’s fees on the original payment will not be returned in case of a refund
- The client always receive a total refund. It's the recipient - in this case, the producer - who will pay the Stripe's fees (according to Stripe support it will be immediately taken from its balance, or debited from next payout).
- If the refund is issued shortly after the original charge, it will appear in the form of a reversal instead of a refund. That means that nothing will appear on the client's bank account (that was my case, in the beginning I could see two pending payments on my bank account, but now I see nothing - as if nothing happened)
- Stripe support indicated that even in the case of a reversal, the Stripe's fees will be paid by the recipient, but that's not what we observe on our producer's account (as for now the fees weren't debited)

**Comment by RachL** [comment]
Thank you @filipefurtad0 ! I think we have a clear documentation ❤️ . I don't think we can make the shop appear as closed because you can also end up with no shipping methods using tags... https://github.com/openfoodfoundation/openfoodnetwork/pull/9536 will add a proper message. I'm not sure we can do much more. Or do we have other ideas? So I think we can close here?

@audez there are some delays before you can see everything appearing on Stripe and / or each stakeholders bankaccount. These delays also occurs in order for Stripe to only take the final correct action and not handle too many bank movement. That's why also payouts do not appear right away.

**Comment by audez** [comment]
IMO this could be split in 3 issues:
- Prevent the shop manager to put all shipping methods in "backoffice only" (i can't find an issue on this, there is #[6136](https://github.com/openfoodfoundation/openfoodnetwork/issues/6136) but it's not exactly this)
- The problem of shipping methods and tags= already handled in #9145 
 and https://github.com/openfoodfoundation/wishlist/issues/225
- Most important: legacy checkout: don't send the payment request if there's no eligible delivery method, and display a message to the user. But I don't know for how long this checkout is here..maybe it's not that important then

What do you think?

**Comment by filipefurtad0** [comment]
Thanks for all the feedback! I've updated the issue (Expected behavior = open; Severity = s3). 

> Or do we have other ideas? So I think we can close here?

Maybe adding a clear message on the legacy checkout (similar to #9145) + disabling the checkout button? I'm not sure we are still investing time fixing issues on legacy checkout. If not, agree to close - please feel free to :+1:

> I don't think we can make the shop appear as closed because you can also end up with no shipping methods using tags

Right, I keep forgetting this is used by some hubs to display products, as [you've mentioned here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9145#issuecomment-1113340574). It feels clunky to me, but no strong opinion on this.

> Prevent the shop manager to put all shipping methods in "backoffice only"

I'm not sure we'd really prevent that, but perhaps add a warning? Would be a new feature, but seems useful to me.  

PS: 

> that was my case, in the beginning I could see two pending payments on my bank account, but now I see nothing - as if nothing happened

@audez let's not test the app with real payments :biohazard:  moving the discussion into #testing

**Comment by audez** [comment]
Yes true, I think I lost a piece of thinking brain in the emergency stress... 😬☠️

After more research and according to comments on this and other issues ( [#5423](https://github.com/openfoodfoundation/openfoodnetwork/issues/5423), #5559, #8219, #9145, #5950, #1343), I tried to summarized and was stroke with a writing fever.. Please feel free to comment or edit!

——————————— 
There are 4 cases when the admin config will not allow the users to checkout:
**Case 1:** no **payment** methods available as they're all set to **“back-office only”**
**Case 2:** no **shipping** methods available as they're all set to **“back-office only”**
**Case 3:** no **shipping** methods available as they're hidden for users with certain **tags** (but available for others)
**Case 4:** the **shipping method category** doesn't match the **product category**
——————————— 
The case of not being able to checkout because all payment or shipping methods have been deactivated doesn't seem possible anymore: I tried to uncheck the last active payment or shipping method, without success..but maybe i'm missing something?
——————————— 
**CASES 1 & 2**
For consistency reasons, it would be great having the same behavior for cases 1 and 2. 

**Warning the user**
It corresponds to “Display only shopfront” described [in the user guide](https://guide.openfoodnetwork.org/basic-features/shopfront/display-only-order-cycles) and in [#5559](https://github.com/openfoodfoundation/openfoodnetwork/pull/5559): the shop shows as closed but products are displayed. Customers can't checkout.

- For case 1, current behavior is: the shop is marked as closed and when clicking on “Checkout” button, the user is redirected to homepage and the following message is displayed: “The hub you have selected is temporarily closed for orders. Please try again later.” 
I find it quite violent to go to the homepage though. I think it would be better to stay in the shopfront page as proposed [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/5559#issuecomment-646530341). 
—> Wishlist : [#271 Remove redirection to homepage when clicking on checkout in shops that 'display only shopfront' ](https://github.com/openfoodfoundation/wishlist/issues/271)

- For case 2:
—> #9628
this will prevent the awful bug described on this page from happening again ❤️

**Warning the shop manager**
Wishlist: the shop manager should be warned that the change they're making will prevent users from checking out 
[#272 Display a warning message to shop managers when they choose a config that will prevent checkout](https://github.com/openfoodfoundation/wishlist/issues/272)

——————————— 
**CASE 3 & 4**
It seems different than the 2 previous ones, as the orders are available for some but not for all. So it doesn't sound good to display the shop as closed..I'd say: display a warning message to users as soon as they land on the shop, for ex:
“Orders on this shop are currently not possible due to this shop configuration. You won’t be able to access checkout page.” + don't allow access to checkout page (same as for cases 1 & 2)

But for now these 2 options don't seem to work:
Case 3: to be written
Case 4: #9629

**Comment by RachL** [comment]
I'm closing the original isse: we won't fix legacy checkout now, let's focus on getting split checkout out :+1:
