### ISSUE TITLE
FR Prod performance issues

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9859]
## Description
FR prod experiences serious latency issues since this summer, as first stated in #9596 
We raised the RAM but the issues are still here.
[See Slack discussion](https://openfoodnetwork.slack.com/archives/CN366FPS9/p1666038286445809)

## Actual Behaviour
Several times a week the response time of the website is catastrophic. As a buyer, you would be stuck on loading a shopfront, or the checkout would take more than 1min.
As a shop manager, it can take minutes to load a page.

On Datadog, this is yesterday night latency:
![Screen Shot 2022-10-24 at 11 39 47](https://user-images.githubusercontent.com/28386648/197508920-2a4fee96-94a9-4e24-a352-9a4eee811052.png)

We can see here that it seems to happen on periods where there's a lot of traffic (wednesday, friday, sunday)
![Screen Shot 2022-10-24 at 11 44 08](https://user-images.githubusercontent.com/28386648/197508924-5625060c-5fd4-4416-9c61-c24a2f385162.png)

## Steps to Reproduce

1.
2.
3.
4.

## Severity
bug-s2: a non-critical feature is broken, no workaround

**Comment by RachL** [comment]
@BethanOFN @lin-d-hop do you have info on problems in the UK? Can you add them in this issue? High changes we are suffering from our reports and timeouts at 4min. But best to dig more into it before reaching a conlusion.

**Comment by audez** [comment]
I'm making this a s1 following an email from one of our users today, indicating that due to latency on the website, checkout is impossible or some orders are taken into account only partially in checkout 😬

The user says: "I write to you because I have noticed as well as my customers a bug of
slowdown when placing orders in our stores. The website is charging for a very long time when ordering and some orders are not taken into account or are only taken into account partially."

When looking in Datadog, filtering on his shops (number 1056; 1082 ; 28..), we can see a lot of errors starting from 14th of September
![Screen Shot 2022-10-28 at 16 02 23](https://user-images.githubusercontent.com/28386648/198630640-24510684-4b20-40c6-b758-a25da8940a9c.png)

**Comment by audez** [comment]
Some discussions on this issue on #performance Slack channel 
https://openfoodnetwork.slack.com/archives/CN366FPS9/p1666038286445809

**Comment by lin-d-hop** [comment]
@mkllnk and I had a chat about this this morning. Here are some notes:

Confident that the issue in at the DB level - so tweaking here is the next port of call.
Experiment with timeout on DB - which we'll match to nginx however DB queries are much faster so this is probably not the end solution.

There are a number of queries that are taking a long time:
- Delete queries on line-items. There isn't much cascading here. Could this be related to order locks?
- The query for Delivery report takes a long time. This can potentially be optimised using the existing reports code.
- Updating the last IP address takes time (for some reason) - this is passed to the payment gateway(??) and that's the only place used. We seem to be making a lot of redundant updates of the IP address on every request. This operates on the order and because the order gets locked for updates this can create really slow requests
- Taxons are slow. This is because we do this as a complicated query on OC, and this is run every time a shopfront is displayed. Looks like this is already cached but it is slow.

@mkllnk will look at this on his tomorrow. He'll document everything so that @jibees can have access to everything when his workday starts. Given the FR holiday today we're not changing anything now and will wait until we have people working again.

**Comment by mkllnk** [comment]
Canada was down this morning and I found that it ran out of memory. Both puma workers used most of the memory and the server was busy swapping, still responding but very slow.

**Comment by David-OFN-CA** [comment]
> Canada was down this morning and I found that it ran out of memory. Both puma workers used most of the memory and the server was busy swapping, still responding but very slow.

Hi @mkllnk just following on your request that we document more fully which reports I was running when we started run into performance issues: 

Back on Tuesday Nov 1st, at around 3pm Eastern time, I ran a few large reports in order to try get some year-on-year sales data. 

I ran a couple of the new 'Revenues by Hub' reports in super-admin, for 2021 and 2022 (Jan 01 - Nov 01). These two reports seemed to go fine and they gnerated csv files without causing too many lags. When I ran a large Order Cycle Supplier Totals queries for the whole 2022 there were more perfromance issues. And when I ran a large Order Cycle Supplier Totals report for 2021, the lag got really bad, and no csv was generated. It was at that point that we started noticing general perfomance issues with the entire site. So, for us, lesson learned in terms of how we use the report function in super-admin-- we will be careful not to run such large reports in the future, and will divvy up large reports like this into quarters (if we are trying to get annual numbers). 

Please let me know if you need any more deatils, or have any follow up questions

**Comment by dacook** [comment]
I've manually added a script to restart the Puma workers, and scheduled it every day at 02:00 UTC on FR Prod.

A full puma restart would have been fine at this time, but I figured it was worth having the script ready just in case. It can be manually executed anytime.
```
/home/openfoodnetwork/bin/puma-phased-restart
```
Installed to run on ofn-admin crontab (because the openfoodnetwork crontab is used by the rails gem `whenever`).

**Comment by RachL** [comment]
Closing as the puma restart is in place : we need to open new issues for the memory leak. As follow up on performance, I've added these two tasks in priority: 

https://github.com/openfoodfoundation/openfoodnetwork/issues/10016

and 

https://github.com/openfoodfoundation/openfoodnetwork/issues/10017
