### ISSUE TITLE
stock control bug?

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#989]
Stroudco supplier Wharf Farm
Product Goat's Milk
Reset stock level set at 30
On hand stock was also set to 30 at the beginning of the OC.
OC report shows 11 units ordered so far.

**Products** screen STILL shows 30 on hand!
**Inventory** shows ZERO and THREE on hand!

AND I CAN'T EVEN MANUALLY MAKE MORE AVAILABLE TO SHOPPERS BECAUSE I STILL CAN'T SAVE THE INVENTORY SCREEN!

![screen shot 2016-05-10 at 15 52 48](https://cloud.githubusercontent.com/assets/17590921/15151095/b2fc9d4c-16c7-11e6-88b1-c970d13be5f5.png)
![screen shot 2016-05-10 at 15 53 14](https://cloud.githubusercontent.com/assets/17590921/15151096/b3040e7e-16c7-11e6-88da-fce102fb7ddd.png)
![screen shot 2016-05-10 at 15 54 41](https://cloud.githubusercontent.com/assets/17590921/15151097/b308c68a-16c7-11e6-8a7f-5e280857aaff.png)

@NickWeir63 
@lin-d-hop 
Maybe we can take off any inventory overrides through Super Admin and just not use them for now? I'll reset the stock levels manually after each OC.

**Comment by OliverUK** [comment]
I also don't understand what's happening with Fungusloci stock. We started with 10 on hand and 10 reset stock level. No inventory and product screens show ZERO on hand but I can still select up to 9 in the shop front. 

![screen shot 2016-05-10 at 16 13 20](https://cloud.githubusercontent.com/assets/17590921/15151759/78a5df52-16ca-11e6-8f07-dcc5d4817a49.png)
![screen shot 2016-05-10 at 16 13 51](https://cloud.githubusercontent.com/assets/17590921/15151760/78a6762e-16ca-11e6-9e11-bb2583c8db69.png)
![screen shot 2016-05-10 at 16 14 05](https://cloud.githubusercontent.com/assets/17590921/15151761/78b4b932-16ca-11e6-862e-166347a0a27e.png)

**Comment by OliverUK** [comment]
For Wharf Farm Duck Eggs, however, all looks fine, with all screens including shop front showing the right amount.

**Comment by OliverUK** [comment]
For our supplier Stroud Community Agriculture the stock reset levels have disappeared but the on hand stock looks right. SCA and Fungusloci may in theory have played with the settings and messed them up but Wharf Farm update their stock through me and don't log in themselves.

**Comment by NickWeir63** [comment]
Hi @OliverUK this is what i see for wharf farm and fungusloci when logged in as superadmin.   I will try taking off any inventory overrides
![Uploading Screenshot 2016-05-10 17.21.45.png…]()
![screenshot 2016-05-10 17 24 26](https://cloud.githubusercontent.com/assets/10517702/15154145/18f4d982-16d4-11e6-9bda-92f5cb5f3bd7.png)

**Comment by NickWeir63** [comment]
OK wharf farm and funguslci are now set to 'inherit' so should take their settings from your bulk edit products list @OliverUK 
![screenshot 2016-05-10 17 40 18](https://cloud.githubusercontent.com/assets/10517702/15154652/91cc1a1c-16d6-11e6-94f5-c3a8406fe784.png)

**Comment by NickWeir63** [comment]
stroud community agriculture was set for everything to inherit apart from one variant (5kg potatoes).  @OliverUK do you want me to change this?
![screenshot 2016-05-10 17 44 34](https://cloud.githubusercontent.com/assets/10517702/15154737/089655c2-16d7-11e6-9cdc-0b18c741a115.png)

**Comment by OliverUK** [comment]
I think so Nick. Please could you do the same for Star Anise until we know what's going on?

**Comment by NickWeir63** [comment]
OK Star Anise and SCA products are now all set to inherit

**Comment by NickWeir63** [comment]
Thanks @stveep for taking this on.  Let me know if you need more info

**Comment by stveep** [comment]
Hi @OliverUK 

In the case of Fungusloci, it seems you are looking at the Inventory for the Fungusloci shop (which I can see is closed with no active order cycles from the shops page of the frontend), while Nick's screenshot is looking at Fungusloci products in the Stroudco shop. Stock levels set on the inventory page are specific to the shop that is selected, so to modify the shopfront stock level (9 in your post) that you are seeing in the _Stroudco_ shop you would need to select the Stroudco shop (and Fungusloci producer) as in Nick's screenshot (similar to your Wharf farm screenshot). This should then decrease as orders are placed, which will be reflected in the [Stroudco] inventory page but not in the products page, since the stock is overriden by the Stroudco inventory and this determines how many are left for Stroudco shoppers to buy. Sorry if any of that is obvious, I'm trying to get my head around it properly too! Does that make sense?

When you say the Wharf Farm milk stock was set to 30 at the beginning of the OC, was this from the Bulk Product page or using the Inventory page (and if so, directly or by resetting to 30?). I'm wondering if you set the stock at 30/30  in the Products page, but this was being overriden by the Inventory, which would presumably have been set at 11x2pt and 14x1pt -resulting in the current values of 0/3 after 11 orders of each. The little warning triangle next to the product variant on the Product page is supposed to alert you to the fact that there is an inventory override in place for that product - but I think this could do with being made clearer...

I've just had a play on staging using Nick's account and it worked ok for me. I added two "Stroudco Food Hub" products to the order cycle: Elderflower cordial and Lemon cordial. 

- Lemon was set at 3 on hand in the products page with no override (set to inherit on inventory).
- Elderflower was set at stock level of 200 in Inventory. The products page had 10 on hand, but this will now be overridden - the warning sign appears.
- Placed an order for 2 Lemon and 10 Elderflower. I could not select more than 3 Lemon or more than 200 Elderflower in the shopfront.
- After this, I can't select more than 1 Lemon or 190 Elderflower in the shop.
- Products page shows 1 Lemon on hand and 10 Elderflower.
- Inventory shows 1 Lemon [inherited] and 190 Elderflower. These are the amounts now available in the shopfront.

![bulkedit](https://cloud.githubusercontent.com/assets/1314715/15627006/c658203c-24cd-11e6-9811-9886479d39c5.png)

Has the problem of saving inventory now been fixed?

**Comment by OliverUK** [comment]
Hello Steve, thanks for looking into this. Obviously some time has passed and I can't remember everything I did at the time but I can't see how I would have set the Wharf Farm stock in the wrong place (products) because only the inventory page has the reset levels. So by definition I would have been there. 
I do think the stock reset function is in the wrong place. If a producer can only make a certain amount each week, which is where we use this functionality, this needs applying at product level, surely? Another problem is that a producer cannot use the reset function unless they have a shop. But most producers don't want their own OFN shop. They just want to be able to set the availability of their produce. 

Maybe I'm misunderstanding but can an inventory offer more stock for sale than the product's master stock level? And if so, does that make sense? 

I still can't save the Stroudco inventory.

**Comment by stveep** [comment]
I believe that the reset stock function can only be used by the hub co-ordinator. This was the original idea for it:
http://community.openfoodnetwork.org/t/inventory-reset/83

Giving a producer their own shop won't let them reset stock for the Stroudco shop as far as I know - any default levels that they set will only apply to the producer's own shop inventory (as I think is happening with your mushrooms above). The Inventory page, at least as I see it, is a way to maintain a stock of a product specific to a hub, separate from the 'master' stock of the product - and I think it can indeed be more than the master stock (see my Elderflower cordial example above). The use case I had in mind while developing the reset function, based on the discourse thread, was where the hub co-ordinator knows that a producer supplies the same amount of a product every order cycle. So to me it made sense to have it controlled by the hub co-ordinator, and only operating for inventory associated with the hub in question. In theory (though I guess this is not applicable to Stroudco producers at the moment) the master stock of a product could be supplied to and distributed by several different hubs. Whereas the stock levels set in inventory by the shop owner represent stock that the shop owner knows is available only for them to distribute - and this could be more than the producer has generally available (?).

We could look into adding a similar convenience method for producers to bulk reset stock levels of their products - but I think this would probably be done at the master level (If I understand correctly, this is supposed to represent stock held by the producer). Or maybe with appropriate permissions a producer could be given sufficient admin rights to reset hub stock levels of their own products. 

I hope that makes sense. Pinging @oeoeaio to make sure I've got all this right...

**Comment by OliverUK** [comment]
It does make sense and I'm clear now that producers cannot change the reset level that we apply at hub level, although that's not how this thread started in any case. But you are right that we tried giving them shop fronts in order to allow them to set the default stock level available to the hub.

I'm still not sure if the confusion that started this thread isn't a bug. I can't get my head round how all the stock got in such a muddle. I'm however more than happy to be practical about it. For now, we will carry on without using this functionality, not least because we can't save changes in inventory. Once that is fixed, I will try once more and keep track of everything.

The scenario you describe is totally feasible but I wonder how common it is, considering that most instances where OFN is put into practice are surely still quite simple "single-hub" cases? I reckon even in a multi-hub environment the master stock should surely be a limit to what all distributors can sell?

**Comment by OliverUK** [comment]
@NickWeir63  I've changed suppliers from "shop" back to "profile" for all but SCA, where I'm no longer the enterprise owner and therefore can't change it. Could you do this?

**Comment by NickWeir63** [comment]
@OliverUK I have changed SCA 'SELLS' from 'OWN' to 'NONE' (see below) and made Oliver@GMX the owner.  
![screenshot 2016-05-29 10 59 13](https://cloud.githubusercontent.com/assets/10517702/15632525/93b2049e-258c-11e6-84de-e7af78534dc3.png)

**Comment by OliverUK** [comment]
@stveep  I can now save changes to the inventory again and will test more in the coming weeks.
