### ISSUE TITLE
UK producers appear to be able to sign up for a free shopfront

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#992]
Lots of Stroudco producers are now using OFN - and they mostly love it!!
One problem is that when they go to their dashboard they have an option to change package......
![screenshot 2016-05-11 12 11 49](https://cloud.githubusercontent.com/assets/10517702/15179180/22e70660-1772-11e6-9e61-e203331b3302.png)
......and if they select this option they are told they can have a free shopfront.  How can we change this to make it clear that we charge for shopfronts - maybe direct them to the [overview doc?](https://docs.google.com/document/d/15hpqm6ab26xKy1_Zil0hF1GEJi-aqQtlHHVd3Kua6kk/edit?usp=sharing)
![screenshot 2016-05-11 12 12 10](https://cloud.githubusercontent.com/assets/10517702/15179174/1bcfd726-1772-11e6-80c6-985899ba423d.png)

**Comment by lin-d-hop** [comment]
The way it works we offer a 6month free trial if producers want to try their own shopfront. Do you agree we should change this to 'Free Trial' in the text? This can come out in the dot release next week.

**Comment by NickWeir63** [comment]
yes please

**Comment by OliverUK** [comment]
Bear in mind we use this for producers who have no way of setting default stock levels other than through the inventory page which in turn you only get with a shopfront.

**Comment by NickWeir63** [comment]
Yes we will make sure we don't charge them if they are set up for this reason and are not actually using their shopfront

**Comment by lin-d-hop** [comment]
On inspection this was a little more complicated than I first thought. I've added in the bits locally so that we can give a full low down of our pricing structure on this screen... Any feedback on the wording would be useful. Keeping the wording simple with quite complex configuration options wasn't easy and this solution can't get any more complex before it breaks. 

![producer_screen](https://cloud.githubusercontent.com/assets/8669848/15267427/bd328016-19b9-11e6-8834-85f9e7a4c00e.png)

It's going to take me a little time to get all the test case permutations completed such that the above implementation can be ready for master. I'll have this ready for v1.8. In the mean time we can display the below on production (active now).
![producer_screen_2](https://cloud.githubusercontent.com/assets/8669848/15267574/dcfc948c-19bd-11e6-9de8-39c6d9f2de2f.png)


Note free trial information will be more clear after deployment of v1.7.1

Summary:
Now: "2% of sales"
At v1.7.1: Better communication of free trial length.
At v1.8: Full communication of business model in this screen.

Let me know if there is anything you'd like changed.

**Comment by NickWeir63** [comment]
Thanks @lin-d-hop - this looks perfect

**Comment by lin-d-hop** [comment]
PR #1016

**Comment by MagsHall** [comment]
Have just run though the producer sign up and was about to flag up the need to be clearer about pricing structure, but it's obviously on its way! When you click to confirm email address on the email confirmation, it's currently saying 30 day free trial though. Once you get to the dashboard it has the correct 6 months displayed, but this initial 30 days bit is a bit confusing 
![30 day trial](https://cloud.githubusercontent.com/assets/19837861/16076347/c0a8e574-32ea-11e6-99bb-be567e3e9695.png)

**Comment by lin-d-hop** [comment]
Note to self, translations required in 
app/views/admin/enterprises/_change_type_form.html.haml

**Comment by lin-d-hop** [comment]
Closing as this has now been tested and released.
