### ISSUE TITLE
Make default time at 00:00 instead of 12:00

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9989]
## Context
Currently when using reports, the default time is 12:00 so users need to constantly change to 00:00 to not miss any info.
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/30d7eb6d-c4b2-4a8d-8ed5-8b4eae06d638)

The date selector is used on multiple pages:
- Reports
- BOM (Bulk Order Management)
- Orders
- Create OC
- maybe others?

It would be good to use this issue to bring consistency across the Date selectors.

## Description
The default start and end time for Reports, BOM and Orders
Start Time >= 00:00
End Time < 00:00

The default time in Order Cycles should not change if possible (stay at 12:00) to minimise potential for hub managers to make a mistake with this change.

You should be able to set the time in all places the date selector is used.

## Acceptance Criteria

- Setting start and end time should be possible in all places date selector is used
- Times set by default are as stated in the description.
- The filters capture all orders of these times. It will be tricky to test the edge cases around time of order placement so need to be sure that no orders will be missed.

**Comment by lin-d-hop** [comment]
> Should we make it 23:59 for end dates? thinking
Start date >= 00:00 End Date < 00:00

**Comment by drummer83** [comment]
I'm not sure I understand @lin-d-hop ...

Let's assume I want a report for the whole last week (7th to 13th Nov).
1. On date/time picker: Select start date: Monday, 7th Nov '22
2. On date/time picker: Select start time: 00:00 (the new default)
3. On date/time picker: Select end date: Sunday, 13th Nov '22
4. On date/time picker: Select end time: 23:59 (my proposed new default)

Why is that? Because
a) If the default for end time was 00:00 all orders from Sunday would not be included.
b) If the default for end time was 00:00 I would have to select Monday, 14th Nov '22. But this is not intuitive because I am not interested in Monday 14th at all...

I hope you get my point. It would be interesting if we can find examples how other websites are this. What I want to avoid is that we have to touch this again very soon because we didn't specify properly in the first place.

**Comment by drummer83** [comment]
> Start date >= 00:00 End Date < 00:00

Default times must be exact specified times. They can't be >= or < anything.

**Comment by lin-d-hop** [comment]
This is how you do it @drummer83. The date picker is to sets the boundaries and you specify how to handle them. Anyway it's not really a product question, this is something devs will just implement :)

**Comment by lin-d-hop** [comment]
We want:
Start Date >= orders to be returned < End Date.

Date times go to fractions of seconds so if you do 23:59 you miss everything between 23:59 and 00:00. Hence you handle it with >= && <

**Comment by abdellani** [comment]
For the end date, I set it to tomorrow at 00:00 to not lose records in the range [today 23:59 => tomorrow 00:00]
 
```js
moment().add(1, "days").startOf("day").format()
```

**Comment by drummer83** [comment]
My understanding of the original issue (before any edits):
- this issue is not about what the code does
- this issue is about what is shown as the default TIME when opening the date/time selector (see screenshot in opening post indicating 12:00)

@RachL: Either I completely misunderstood your issue or we are missing the goal you intended to reach.

OR: Is this about removing the option to enter a time and use dates only instead?

**Comment by RachL** [comment]
I don't know what the code does to be honest.

The problem I'm trying to fix is that currently users are always changing from 12:00 to 00:00 in the UI. It's a waste of time for them. If the code does already take into account 00:00 great, but the UI needs to reveal that (outside of english speaking users, no one understand AM vs PM, there is no translation equivalent).

Removing the time from the UI could be a good option as well. I don't think it's useful in reports. What do you think @lin-d-hop ?

**Comment by RachL** [comment]
Looks good to me!

**Comment by RachL** [comment]
So it means that instead of have one month data per default, we now will have one day?

**Comment by abdellani** [comment]
@RachL 
Yes, you're right.
I'll fix that problem

**Comment by abdellani** [comment]
@RachL 
Looks like the problem is already solved.
Can you please confirm?

**Comment by abdellani** [comment]
@RachL 

Depending on the report type, when the user loads the page, the date fields may be empty or pre-filled.
- For `Bulk Co-op Supplier Report`, the date fields are empty

![image](https://user-images.githubusercontent.com/16113997/202999884-72147f44-2168-47a5-a13d-ce1e3beaab2c.png)

- For `Order Cycle Supplier Totals`, the data fields are already filled using `Reporting::Reports::OrdersAndFulfillment::default_params` ([check here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/reporting/reports/orders_and_fulfillment/base.rb#L11))

![image](https://user-images.githubusercontent.com/16113997/203000693-1cbd15b3-f9cd-4800-a834-000e118af55b.png)

I suggest to implement the `default_params` methods on the reports, instead of sending extra-params to the javascript controller  (as I did in my initial PR).

**Comment by RachL** [comment]
Yes I know that not all reports have default dates. We use default dates to improve performance, but it's actually something users hate.

I was reacting to your comment saying: 

In end date:

    date: Tomorrow
    
=> does this mean that when there are default dates, the range is 1 day by default now?

**Comment by abdellani** [comment]
The short answer: Yes.

The long answer:

### 1. For the reports that don't have `default_params` implemented
#### Before the PR
1. The default range is `Illimited` (includes all data).
2. If the user opens  `start date` and `end date` selectors, the date range will be : [Today @ 12:00, Today @ 12:00 ] 

#### After the PR

1. The default range is `Illimited`.
2. If the user opens  `start date` and `end date` selectors, the date range will be : [Today @ 00:00, tomorrow @ 00:00 ] 


### 2. For the reports that have `default_params` implemented
#### Before the PR
3. The default range is [Today - 1 month @ 00:00, tomorrow @ 00:00 ].
4. If the user opens  `start date` and `end date` selectors, the date range will not change (same as 3). 

#### After the PR

3.  The default range is [Today- 1 month @ 00:00, tomorrow @ 00:00 ] (same).
4. If the user clicks on `start date` and `end date`, the date range will be : [**Today @ 00:00**, tomorrow @ 00:00 ] (maybe it better to not change the time if a date is already select by default ? )

**Comment by RachL** [comment]
@abdellani 

> (maybe it better to not change the time if a date is already select by default ? )

Indeed it's a bit weird in terms of UX, but if it's easier to implement for now we can move forward with the PR: it already improves the problem a lot. Thanks Mohamed!

**Comment by abdellani** [comment]
> (maybe it is better to not change the time if a date is already select by default ? )

I fixed that : )
